### ISSUE TITLE
abnormal positive/negative regulation

### ISSUE THREAD

**Issue by fypoadmin** [pombase/fypo#103]
Gah - I know I have asked about this at least twice, possibly three times, and perhaps I'm just really dim with regard to getting my head around the abnormal positive/negative regulation terms, but I'm really struggling with using them. 

Would it be possible to migrate them to something more explicit (for instance increased/decreased transcription compared to wild type) or include a definition?

Original comment by: Antonialock

**Comment by mah11** [comment]
closing because out of date; problems can go in new tickets
