### ISSUE TITLE
ntr: defective heat shock response

### ISSUE THREAD

**Issue by fypoadmin** [pombase/fypo#1102]
I want to capture a phenotype where cells have a defective heat shock response.

sensitive to heat shock
is defined
A cell phenotype in which cells show increased sensitivity to heat shock. Heat shock is a form of heat stress in which cells are briefly exposed to a very high temperature

but this does not seem to capture fully the "heat shock response"
where heat shock sensitive cells in log phase  become resistant by sublethal heat treatment.

Is this the correct term to use for this?

v

Original comment by: ValWood

**Comment by ValWood** [comment]
closing as it can be added when required
