### ISSUE TITLE
ntr: increased unequal sister chromatid recombination

### ISSUE THREAD

**Issue by fypoadmin** [pombase/fypo#1581]
increased unequal sister chromatid recombination (USCR)
the sibling (which I don't need now) would be
increased intrachromatid recombination (ICR) 

children of
increased sister chromatid recombination

PMID:20123974 fig4c

Original comment by: ValWood

**Comment by ValWood** [comment]
shall we just cloase this and open when somebody needs them to annotate. I'm years away from recombination
