### ISSUE TITLE
septation without cytokinesis

### ISSUE THREAD

**Issue by fypoadmin** [pombase/fypo#1756]
ntr: septation without cytokinesis
a A cellular process phenotype observed in the vegetative growth phase of the life cycle in which cell cycle cytokinesis does not occur, but complete barrier septa  are present

child of 
abolished cytokinesis

both 
FYPO:0001253	elongated multinucleate multiseptate vegetative cell, septa between nuclei
FYPO:0001223	binucleate multiseptate cell
are examples of "septation without cytokinesis"

and should be children of this term, possibly others

Original comment by: ValWood

**Comment by mah11** [comment]
Closing because nothing has happened on this for over a year; can reopen if you do need "septation without cell separation".
