### ISSUE TITLE
multinucleate

### ISSUE THREAD

**Issue by fypoadmin** [pombase/fypo#1764]
Every time I have used "multinucleate" I mean "more than 2 nuclei"
but multinucleate is defined as 2 or more.

We need to come up with a way of describing "more than 2 " nuclei

Original comment by: ValWood

**Comment by ValWood** [comment]
wiki says
 Need to find out when a cell is considered separate cells first. Asking Jacky and Mohan
I don't think I ever asked, will mail jacky now...

**Comment by ValWood** [comment]
>Although do we absolutely need to know that to deal with the multinucleate issue?
in
https://github.com/pombase/curation/issues/691
was probably meant for this ticket!

**Comment by mah11** [comment]
- deleted comment from the other ticket
- Do we need to sort out when one cell becomes two for this? It'll certainly help!

**Comment by mah11** [comment]
closing because it's ancient and hasn't had any updates in literally years
can reopen if we have new ideas some time ...
