### ISSUE TITLE
viable binucleate cell formed after cytokinesis - query

### ISSUE THREAD

**Issue by fypoadmin** [pombase/fypo#1837]
Jacky was describing this phenotype which occurs with some cuts

The cell undergoes cytokinesis, but both nuclei are localized to one compartment. The nucleated compartment is viable (it goes on tho grown and divide as a diploid)

I thought we had a phenotype which described this type of mis-segregation event (without the diploid part) but I couldn't find it.

Original comment by: ValWood

**Comment by ValWood** [comment]
I don't know what I was checking here, but I think this was all dealt with by a later ticket? (i.e the mononucleate and binucleate cell malarky). I think we now know that the 2 nuclei in one cell compartment can  sometimes go on to form viable diploids.

**Comment by mah11** [comment]
I admit, I'm a little hazy on this one now, but I'm happy to close it and have you open a new ticket if you spot anything odd after those other changes.

**Comment by ValWood** [comment]
Lets do that. I think improvements are made and  if there is anything else it will become obvious.
