### ISSUE TITLE
review annotation to "outer repeat transcript level"

### ISSUE THREAD

**Issue by fypoadmin** [pombase/fypo#1850]
http://www.pombase.org/spombe/related/FYPO:0000220

Some of these are the opposite that I would have expected for RNAi mutants. I wonder if in some cases the annotation is describing the increased expression of an exogenous reporter gene. In this case the correct term to use is

decreased chromatin silencing at centromere outer repeat

Original comment by: ValWood

**Comment by mah11** [comment]
closing because it's ancient and hasn't had any updates in literally years
