### ISSUE TITLE
relationship between osmotic stress and potassium chloride sensitivity

### ISSUE THREAD

**Issue by fypoadmin** [pombase/fypo#1870]
AS potassium chloride is usually used to generate osmotic stress,

should
sensitive to potassium chloride be a child of sensitive to osmotic stress?

Original comment by: ValWood

**Comment by mah11** [comment]
closing because it's ancient and hasn't had any updates in literally years
we've also done without the link for all that time
can revisit if it's worth finding or adding something in the CHEBI roles branch
