### ISSUE TITLE
biorientation query

### ISSUE THREAD

**Issue by fypoadmin** [pombase/fypo#1981]
do we need a term 

abnormal attachment of mitotic spindle microtubules to kinetochore

to mirror GO.

(I have been using "abnormal sister chromatid biorientation" which might be a little specific, so if so I will need to check these)

we have
abnormal attachment of spindle microtubules to kinetochore
--abnormal sister chromatid biorientation

Original comment by: ValWood

**Comment by ValWood** [comment]
I don't think we need to do this cos'
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:1990758#term=ancchart

BUT,  can we check that the FYPO terms apply to mitotic?

**Comment by mah11** [comment]
done.
