### ISSUE TITLE
a couple of chromosome segregation phenotype questions

### ISSUE THREAD

**Issue by fypoadmin** [pombase/fypo#1983]
(can discuss in New Year, move to curation tracker if more appropriate)

1 what is the relationship between large and small nuclei and chromosome segregation (if any). I could not see one in Bioportal.

2 what is the relationship between unequal segregation and merotelic attachment?
1. When people use the phrase  "non disjunction" are they referring to any chromosome segregation defect?

Original comment by: ValWood

**Comment by mah11** [comment]
looks like there's nothing to do here ...
