### ISSUE TITLE
PMID:15728720 increased centromere/kinetochore spindle pole body attachment during meiosis I

### ISSUE THREAD

**Issue by fypoadmin** [pombase/fypo#2035]
increased centromere/kinetochore spindle pole body attachment during meiosis I
fig 7A B C

Original comment by: ValWood

**Comment by mah11** [comment]
is it worth looking at this again, or shall we close it?

**Comment by ValWood** [comment]
Lets close. I l will ook over these when I  next use.

**Comment by mah11** [comment]
I know I can count on you for new tickets whenever anything crops up ;)
