### ISSUE TITLE
term merge, meiotic SPB related

### ISSUE THREAD

**Issue by fypoadmin** [pombase/fypo#2217]
I think these 2 terms  are the same phenotype:

FYPO:0003561 - abnormal prospore-specific spindle pole body remodeling
A cell phenotype in which prospore-specific spindle pole body remodeling is abnormal. Prospore-specific spindle pole body remodeling takes place during the second meiotic division during ascospore formation and results in the structural reorganization of the SPB, including the recruitment of sporulation-specific proteins to the outer plaque to form the meiotic outer plaque (MOP).

FYPO:0004608 abnormal spindle pole body morphology during meiosis II  
A physical cellular phenotype in which the size, shape, or structure of the spindle pole body is abnormal during the second meiotic nuclear division.

merge?

Original comment by: ValWood

**Comment by ValWood** [comment]
I think this is useful, would it be good to add something like this to the comments for these terms?

**Comment by mah11** [comment]
> I think this is useful ...

Sorry, it's not clear what "this" refers to here.

**Comment by ValWood** [comment]
Ignore. I see it will have a has_output link.

**Comment by ValWood** [comment]
Actually that's confusing.

![relation unexpected way around](https://cloud.githubusercontent.com/assets/7359272/13150577/4781ba2e-d65e-11e5-90ba5ef7a7bb8a59.jpg)

So 
abnormal prospore-speciifc spindle pole body remodeling
has_output 
abnormal spindle pole body morphology during meiosis II
?

But we wouldn't want  people to select 
*abnormal spindle pole body morphology during meiosis II*
in preference to 
abnormal prospore-speciifc spindle pole body remodeling

but we would want everything annotated to  *abnormal prospore-specific spindle pole body remodeling*
to be annotated to 
*abnormal spindle pole body morphology during meiosis II*

If the relationship is  the correct one, this doesn't work the way we  have Canto configured right now.


This page says we didn't do output of yet?
http://curation.pombase.org/pombase-trac/wiki/RelationsAndTransitivity

**Comment by ValWood** [comment]
![relation unexpected way around](https://cloud.githubusercontent.com/assets/7359272/13151027/1d725732-d660-11e5-9bc0-3fc90fd5bce8.jpg)

**Comment by mah11** [comment]
I get "403 forbidden" from the "relation unexpected way round" link.

The wiki page looks correct for annotation inference for querying. I'm fairly sure output_of was one of the major reasons we discussed adding ability to distinguish direct annotations vs. those inferred from paths in the ontology.

If you're confident that you understand how you want Canto to handle output_of, update the wiki and open a Canto ticket.

**Comment by ValWood** [comment]
I'll need to think about this, early morning task....

**Comment by ValWood** [comment]
FYPO:0003561 - abnormal prospore-specific spindle pole body remodeling
also occurs during meiosis II
would that solve the 'forbidden' problem?

**Comment by mah11** [comment]
The "forbidden" thing was a web access error, nothing whatsoever to do with the ontology (also now no longer a problem, apparently).

**Comment by mah11** [comment]
I think anything outstanding here is superseded by opening https://github.com/pombase/canto/issues/1307 for #2562.
