### ISSUE TITLE
a possible cell size homeostasis phenotype

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2235]
I am curating some of the seminal Peter Fantes/ Fantes plot papers which were mentioned so much at the meeting.

Despite these being really important papers, they are really experiments which just use a mutant and then observe the retoration of size homeostasis after a temperature shift.

The first one PMID:893551 is demonstrating
restoration of division length homeostasis over successive cell cycles (condition after shift from non-permissive to permissive temperature)

I can only annotate the elongated and normal length phenotypes for cdc2-33

I *could* make and annotation to reflect this observation

restoration of division length homeostasis over successive cell cycles (condition after shift from non-permissive to permissive temperature)

if you can think of a way that I could capture it....Have you done something else similar to this, it rings a bell.....I guess the point is that the size does  not return instantly to normal but can only be corrected to a certain degree in each generation.
If you can't think of a way that I can do this I can add a note...

**Comment by mah11** [comment]
The catch with this is that the cdc mutant is the only thing they used to make long cells in the first place; there was no way to get cells that had a wild-type genotype but were long. That means there's no way to tell whether the mutant differs from wild type in how long it takes to get back to "normal" length at division.

**Comment by ValWood** [comment]
OK, I will just leave this and add comments to the paper. We need to do something else with these types of papers at some point....

**Comment by mah11** [comment]
Closing because we can't really do anything without a wt/mutant comparison.
