### ISSUE TITLE
bent vs curved cells

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2237]
The paper I am curating 9658169 makes a distinction between bent vs curved cells

I think 'bent' generally refers to the cells which have a sharp bend, or kink.
In FYPO 'bent' is a synonym of curved.

Should we somehow disambiguate this?
Would it be possible to have a grouping term which covered bent and curved? if so I could easily sort them from here. Although there are 113 annotations most will be from 3 screens and a smallish number of other papers.

For now will use 'curved' for these bent

**Comment by mah11** [comment]
Yes, good point about disambiguating -- I can add a "bent" term and remove the synonyms from "curved".

I'm not so keen on adding a grouping term, because I haven't thought of a way to do it other than to say "cells that aren't straight". Negatives are really dodgy in ontologies.

**Comment by ValWood** [comment]
OK it would be good to add "bent" soon so at least I can add them correctly for this paper.....the others will need to be fixed slowly....

**Comment by mah11** [comment]
OK, "bent cell" is in:
  bent vegetative cell FYPO:0004700

and "bent" synonyms are gone.

If you know of any more specific terms involving "bent" that you need now, put them here; otherwise, I'll close this ticket tomorrow and you can open new tickets for new terms as & when you need them.

**Comment by mah11** [comment]
done in 09c63e367ebd2ddf4ea2f613c214a0eebc6b5c69
