### ISSUE TITLE
NTR cytoplasmic microtubules absent from cell

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2238]
cytoplasmic microtubules absent from cell
PMID:9658169

note to self, update alp1,alp11, nda3, atb2

**Comment by mah11** [comment]
cytoplasmic microtubules absent from cell FYPO:0004702

edit file a1f756ac121fb02f150b11ad8be96320fbb10b03
release ddd4e270a2170a940afaaf394d41d2784f48b0af
