### ISSUE TITLE
cant locate a mislocalized nucleus term

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2239]
I'm looking for the FYPO term when 2 nuclei end up in a single compartment. I can't find it anywhere by a number of searches and routes...any ideas

tried "nuclei" 
mislocalized nucleus, children
compartment
binucleate vegetative cell and children

**Comment by ValWood** [comment]
Its this one
septation following abnormal chromosome segregation, with anucleate cell formation

I am now wondering if chromsome segregation is strictly wrong here, its just that because the nucleus is in the wrong place ?

**Comment by mah11** [comment]
I'd just found the term myself. Let me know if any additional synonyms would help.

This term (FYPO:0003166) might also be a bit more specific than you want, precisely because it does specify abnormal chromosome segregation. It's named and defined that way because it's the sibling of cut.

**Comment by Antonialock** [comment]
yeah but I would probably have looked for a "binucleate monoseptate cell
with nuclei grouped" or something.

On Wed, Jul 8, 2015 at 3:06 PM, ValWood <notifications@github.com> wrote:

> Its this one
> septation following abnormal chromosome segregation, with anucleate cell
> formation
>
> I am now wondering if chromsome segregation is strictly wrong here, its
> just that because the nucleus is in the wrong place ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pombase/fypo/issues/2239#issuecomment-119572559>.
>



-- 
Antonia Lock, PhD
PomBase Biocurator, http://www.pombase.org
Department of Genetics, Evolution and Environment,
The Darwin Building,
University College London
London WC1E 6BT, UK

**Comment by ValWood** [comment]
let's have a new term also which does not specify a chromosome segregation problem

liberal synonyms, and should it be related to mislocalized nucleus?

**Comment by ValWood** [comment]
note to self, update curs/c4669f01934c07d6

**Comment by mah11** [comment]
OK. I think has_part mislocalized nucleus might work.

**Comment by mah11** [comment]
So far I've added this (and made it an additional parent of FYPO:0003166):

[Term]
id: FYPO:0004699
name: monoseptate vegetative cell with binucleate and anucleate compartments
def: "A cell phenotype observed in the vegetative growth phase of the life cycle in which a cell has two nuclei and one septum, but both nuclei are in a single compartment on one side of the septum." [PomBase:mah]
synonym: "binucleate monoseptate cell with nuclei grouped" RELATED [PomBase:al]
synonym: "monoseptate cell with binucleate and anucleate compartments during vegetative growth" EXACT [PomBase:mah]
synonym: "monoseptate vegetative cell with binucleate and anucleate compartments during mitotic cell cycle" RELATED [PomBase:mah]
is_a: FYPO:0001225 ! monoseptate
relationship: has_part FYPO:0002071 ! mislocalized nucleus during vegetative growth

I can add any other synonyms that might help you find it (including related ones, if 
something non-exact would be useful). Will close when you're happy with the synonym assortment.

**Comment by mah11** [comment]
done in 09c63e367ebd2ddf4ea2f613c214a0eebc6b5c69
(reopen or create new ticket if you think of any more synonyms)
