### ISSUE TITLE
Rad52 foci G0/G1

### ISSUE THREAD

**Issue by mah11** [pombase/fypo#2242]
increased number of Rad52 foci during G0 to G1 transition

and edit fypo:972 name

**Comment by ValWood** [comment]
My eyesight is so bad that I have been wondering why you had  Gene Simmons as your icon....

**Comment by mah11** [comment]
PMID:19197239
  increased number of Rad52 foci FYPO:0004709
  increased number of Rad52 foci during G0 to G1 transition FYPO:0004710

**Comment by mah11** [comment]
edit file: 93a8248299c3eb075d0ac38f150a6246b0ce5391
release: 488c2b005f76e7c489c39eeb7f2ef1cb8ee7e432
