### ISSUE TITLE
new condition : cold shock and recovery at normal temperature

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2248]
analogous to heat shock and recovery term

note to self PMID:15004232

**Comment by Antonialock** [comment]
Just so you know, I can't add this at the moment

On Mon, Jul 20, 2015 at 2:24 PM, ValWood <notifications@github.com> wrote:

> analogous to heat shock and recovery term
>
> note to self PMID:15004232
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pombase/fypo/issues/2248>.
>



-- 
Antonia Lock, PhD
PomBase Biocurator, http://www.pombase.org
Department of Genetics, Evolution and Environment,
The Darwin Building,
University College London
London WC1E 6BT, UK

**Comment by Antonialock** [comment]
PECO:0000285
