### ISSUE TITLE
decreased rate of cytoplasmic microtubule depolymerization at the minus end

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2251]
decreased rate of cytoplasmic microtubule depolymerization at the minus end

child of "decreased rate of cytoplasmic microtubule depolymerization"

A cellular process phenotype observed in the vegetative growth phase of the life cycle in which  the removal of tubulin dimers from the minus end of cytoplasmic microtubule, occurs at a lower rate, or speed, than normal.

**Comment by ValWood** [comment]
PMID:15772152

**Comment by mah11** [comment]
decreased rate of microtubule depolymerization at minus end FYPO:0004721

**Comment by mah11** [comment]
edit file: e78131ae9f80d87fc081f0db57734c7aa001fec8
release: 812c9c7c3fd5bdfc78999933ff1a79bc9634fc7c
