### ISSUE TITLE
normal mitotic spindle polar microtubule

### ISSUE THREAD

**Issue by mah11** [pombase/fypo#2252]
From Val, misfiled on the canto issue tracker:

"I want a term to indicate that the nuclear spindle microtubules are normal (the astral ones are absent)

Will this term cover it?

standard def
PMID:15772152"

**Comment by ValWood** [comment]
actually the polar microtubules are normal, but also the intranuclear 'astral-like",
so basically all nuclear microtubules are normal, but not all spindle microtubules...

"Intranuclear MTs (astral-like MTs in Phase 2) were present normally in mto1􏰁 cells (Figure 3B, Phase 2, see arrows; Sagolla et al., 2003; Zimmerman et al., 2004a)."

**Comment by mah11** [comment]
normal nuclear microtubules FYPO:0004722

**Comment by mah11** [comment]
edit file: e78131ae9f80d87fc081f0db57734c7aa001fec8
release: 812c9c7c3fd5bdfc78999933ff1a79bc9634fc7c
