### ISSUE TITLE
ntr increased number of misorientated mitotic spindle

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2253]
misorientated mitotic spindle

A physical cellular phenotype observed in the vegetative growth phase of the life cycle in which a cell forms an increased number of mitotic spindles in an abnormal orientation. The normal orientation is  parallel to the long axis of the cell.

Comment  WT 8% misorientated
PMID:15772152
mto1 delta

**Comment by mah11** [comment]
Are there more MTs overall, or just an increased proportion (of a normal total number) that are misoriented?

**Comment by ValWood** [comment]
whoops cut and past def error

A physical cellular phenotype observed in the vegetative growth phase of the life cycle in which a cell forms  mitotic spindles in an abnormal orientation. The normal orientation is parallel to the long axis of the cell.

Does that make more sense
(its increased numbers of cells which start out with incorrectly aligned spindles  (33%)
vs WT 8%) However they all get corrected eventually

**Comment by mah11** [comment]
So is it OK if I create a cell phenotype term for "misoriented mitotic spindle" and mention that it's transient (and not totally absent from wt)? The alternative would be to do this as a population phenotype, which I'd find a bit less satisfying because it's harder to do logical defs for them.

**Comment by ValWood** [comment]
Yeah, I wondered if it should be a population term but that would be less satisfying (and we have specific penetrance to attach to a cell level observation).

This is one  of  phenotypes that I was trying to think of ages ago where it might be useful  to know the background penetrance (so you know that you should only annotate if they have observed more than WT)  but I digress...

Ah I see what you men, my original request is population level isn't it...I'm not sure....

**Comment by ValWood** [comment]
OK, I think it would be fine, is it possible to say
"transiently misoriented mitotic spindle" as the phenotype?

then I would have
"transiently misoriented mitotic spindle" has_penetrance 30%and 
"normal misoriented spindle correction" (or whatever the term I requested) ...I think that would be clear enough for  people to  interpret phenotypes

**Comment by mah11** [comment]
did you close this on purpose?

I could easily re-jig the term to be a cell phenotype if you prefer that over a population phenotype; don't worry about exactly how the original request was phrased.

You can put the wt frequency on that wiki page - http://curation.pombase.org/pombase-trac/wiki/WildTypePhenotype

**Comment by mah11** [comment]
not sure I can do a logical def to include "transient" but the term can go in with just a text def if need be

**Comment by ValWood** [comment]
I think I should capture the penetrence so it needs to be 'cell phenotype' to do this?
So yes.  I'll go with your phrasing.....

**Comment by ValWood** [comment]
didn't mean to close. Close button should be bright red..... and away from me

**Comment by mah11** [comment]
transiently misoriented mitotic spindle FYPO:0004723

**Comment by mah11** [comment]
edit file: e78131ae9f80d87fc081f0db57734c7aa001fec8
release: 812c9c7c3fd5bdfc78999933ff1a79bc9634fc7c
