### ISSUE TITLE
ntr normal mitotic spindle rotation correction

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2254]
A physical cellular phenotype in which a cell corrects the orientation of a misorientated mitotic spindle  to be  parallel to the long axis of the cell.

(as 8% of WT spindles are misorientated, tis is a WT process)

PMID:15772152

**Comment by mah11** [comment]
Is there a GO term for the normal process?

**Comment by ValWood** [comment]
actually, I think its
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0051294
Any process that set the alignment of spindle relative to other cellular structures.

I could add "correction" synonyms to the GO term.....

**Comment by mah11** [comment]
There's a mitotic spindle-specific child if you want - GO:0000132. Those terms encompass setting up the spindle orientation in the first place, i.e. they're not restricted only to correcting orientation if & when it goes wrong.

For the phenotype, you may prefer to define the process of correcting spindle orientation in GO, and then we can define the phenotype as "that process is normal" (1st draft fypo def sounds too much like it's trying to define just the correction process). If you don't feel the need for separate GO terms, synonyms would be OK but can't be exact -- they'd have to be narrow -- and it would be a bit dodgy to use the existing GO term in a logical definition for a more restricted FYPO term.

**Comment by ValWood** [comment]
and yes it should be mitotic specific child GO term

re the GO term, I'm not sure. I guess I should request the new GO term

**Comment by mah11** [comment]
Sounds sensible. I can stick a FYPO term in without an xp in the meantime.

**Comment by ValWood** [comment]
Actually I'm not totally sure that correction is a 'process' maybe the spindle just  oscillates until it is in the right position but there is no mechanism for correction, just a sensor for 'correct'.

I think in this mutant they just start of in a worse 'position' , can we work with 
 GO:0000132	establishment of mitotic spindle orientation and define accordingly?
so it would be
normal GO:0000132

**Comment by mah11** [comment]
I have a feeling GO:0000132 and its parent might still be broader, because they have to cover the ways cells determine what the correct orientation is in the first place (especially in some bigger eukaryotes).

And what gets most of the spindles in the correct orientation in wild type?

Might be worth asking the GO lot for their opinion, anyway.

**Comment by mah11** [comment]
normal mitotic spindle orientation correction FYPO:0004726

**Comment by mah11** [comment]
edit file: e78131ae9f80d87fc081f0db57734c7aa001fec8
release: 812c9c7c3fd5bdfc78999933ff1a79bc9634fc7c

will close when we know what GO will do (so I know whether and how to do an xp)

**Comment by mah11** [comment]
Is there a GO ticket for this stuff?

**Comment by ValWood** [comment]
nope  which bit do I need a GO term for? I just re read but am confused!

**Comment by mah11** [comment]
Find out whether they think there's a case for a term specifically for "the process of correcting mitotic spindle orientation" (i.e. does the existing term cover more than just correcting orientation problems, as I suspect).

Or just leave FYPO:0004726 without a logical definition ;)

**Comment by ValWood** [comment]
Does a mechanism for correction necessarily exist. If the mechanism is just to  sense correct orientation, the spindle maybe just oscillates until the correct orientation is senses. In the mutants it never reaches this position because of morphological defects and so "correct" is never achieved. I don't know if the "incorrect" orientation is sensed and corrected. Does that make sense? 

We can keep like this for now and make a logical def when we know. Will probably become apparant soon...
