### ISSUE TITLE
ntr: long polar microtubules at interphase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2255]
ntr: "long polar microbules protruding through nuclear envelope at interphase"

a child of
long polar microtubules

(note this is different from 
long mitotic spindle microtubules protruding beyond spindle pole body, as it occurs during interphase, not as a consequence of spindle elongation...it appears to be the source of the cytoplasmic microtubules in this mutant)

"Many MT bundles projected outside the body of the nucleus (Figure 4E). Consistent with this, we observed that the nu- clear envelope formed thin protrusions that grew and shrank (Figure 4, G and H, Supplementary Movie 8). Such intranuclear MTs and nuclear envelope distortions were not observed in wild-type cells. Several criteria confirmed that these cells with intranuclear MTs were in interphase and not in mitosis: these cells did not exhibit cytokinetic actin rings or separated SPBs and were often shorter than mitotic cells (Figure 4, B and H; our unpublished observations)."

PMID:15772152

**Comment by ValWood** [comment]
"Thus, interphase intranu- clear MTs that pierce the nuclear envelope contribute to the formation of a significant fraction of the cytoplasmic MTs, but there are probably additional sources as well."

**Comment by mah11** [comment]
Polar microtubules are part of a spindle, by definition (in GO CC and generally). Is it part of this phenotype that the cells have spindles in interphase, or are these MTs that connect to an SPB despite not being part of a spindle?

The way they did the experiment I suspect the latter, but shout if I missed something.

**Comment by ValWood** [comment]
OK I think it is the latter
so would it be OK to just call them 

long nuclear microtubules protruding through nuclear envelope at interphase?

**Comment by mah11** [comment]
yep, I think that would be basically OK

**Comment by mah11** [comment]
long nuclear microtubules protruding through nuclear envelope during interphase FYPO:0004724
  nuclear envelope protrusion present during interphase FYPO:0004725

**Comment by mah11** [comment]
edit file: e78131ae9f80d87fc081f0db57734c7aa001fec8
release: 812c9c7c3fd5bdfc78999933ff1a79bc9634fc7c
