### ISSUE TITLE
ntr: nuclear-derived cytoplasmic microtubules

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2256]
ntr: presence of nuclear derived cytoplasmic microtubules
A cellular phenotype in which cells form cytoplasmic  microtubules from intranuclear microtubules which escape from the nucleus

(Can we do this, or similar ? otherwise its difficult to interpret where the cytoplasmic microtubules actually come from?)

PMID:15772152

(Don't worry if its bonkers)

**Comment by ValWood** [comment]
actually there is more about the 2nd mechanism the mutant generates cytoplasmic microtubules from nuclear microtubules....I think this term would be useful to cover this section too:


Time-lapse images showed that after anaphase, persistent spindle MTs frequently grew past the nucleus, split from the main spindle, and curved around cell tips. These MTs then typically broke into frag- ments that continued to propagate within the cytoplasm (Figure 3B, 28􏰆0􏰏 to 42􏰆47􏰏; see also Sawin et al., 2004). Images of the nuclear envelope and the NLS-GFP-􏰄gal marker sug- gested that these spindle MTs do not puncture the nuclear envelope as during interphase, but rather enter the cyto- plasm when the nuclear envelope fissions at the spindle midzone at the end of anaphase (our unpublished data). Time-lapse images showed that most cytoplasmic MTs orig- inated in this manner. Short intranuclear MTs were also present in postmitotic cells (Figure 3B, 31􏰆03􏰏 to 38􏰆53􏰏; see also Figure 4I, arrow) and occasionally seeded the formation of cytoplasmic MTs. However, most of these intranuclear MTs did not persist later in interphase (12% of cells exhib- ited both interphase intranuclear MTs and cytoplasmic MTs; n 􏰍 85). In summary, these findings in mto1􏰁 mutant cells document an unusual mechanism of generating cytoplasmic MTs from intranuclear MTs.

**Comment by mah11** [comment]
I freely admit my head is spinning a bit, but perhaps we could do:

cytoplasmic microtubule nucleation from nuclear microtubules
[i] cytoplasmic microtubule nucleation from nuclear microtubules following nuclear envelope breakthrough [and is this only during interphase?]
[i] cytoplasmic microtubule nucleation from nuclear microtubules following spindle microtubule fragmentation

does that look like it would work?

**Comment by ValWood** [comment]
The way I understand it, in these mutants no cytoplasmic nucleation occurs. But you get cytoplasmic microtubules. This is because, somehow you get interphase nuclear microtubules which poke through the nuclear envelope, elongate and break to form 'microtubule fragments' which  can continue to grow and treadmill. So you get cytoplasmic microtubules even though you can't nucleate any in the cytoplasm....I don't think the terms should include nucleation. Does that help?

**Comment by mah11** [comment]
OK. What if I swap out "nucleation" and use "formation"?

**Comment by ValWood** [comment]
That works!

**Comment by mah11** [comment]
hooray!

**Comment by mah11** [comment]
cytoplasmic microtubule formation from nuclear microtubules FYPO:0004727
  cytoplasmic microtubule formation from nuclear microtubules following nuclear envelope breakthrough FYPO:0004728
  cytoplasmic microtubule formation from nuclear microtubules following spindle microtubule fragmentation FYPO:0004729

**Comment by mah11** [comment]
edit file: e78131ae9f80d87fc081f0db57734c7aa001fec8
release: 812c9c7c3fd5bdfc78999933ff1a79bc9634fc7c
