### ISSUE TITLE
PMID:15772152 final

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2258]
name: protein mislocalized  to the  side of the cell during vegetative growth
proposed def:
A cell phenotype observed in the vegetative growth phase of the life cycle in which a protein that is not normally found at the cell cortex of the long axis of the cell is observed there."

normal protein localization to cytoplasmic microtubule tip (plus end)
A cell phenotype observed in the vegetative growth phase of the life cycle in which the localization of a protein to the cytoplasmic microtubule plus end is normal (i.e. indistinguishable from wild type)."

reduced number of astral microtubules
A cell phenotype observed in the vegetative growth phase of the life cycle in which a cell contains fewer astral microtubules than normal.

reduced number of cytoplasmic microtubules nucleated from equatorial microtubule organizing center 
A cell phenotype observed in the vegetative growth phase of the life cycle in which a cell contains fewer cytoplasmic microtubules nucleated from equatorial microtubule organizing center

that's it!  yay

**Comment by mah11** [comment]
protein mislocalized to lateral cell cortex FYPO:0004730
  normal protein localization to cytoplasmic microtubule plus-end FYPO:0004731
  astral microtubules present in decreased numbers FYPO:0004732
  cytoplasmic microtubules nucleated from equatorial microtubule organizing center present in decreased numbers FYPO:0004733

various synonyms included

**Comment by mah11** [comment]
edit file: e78131ae9f80d87fc081f0db57734c7aa001fec8
release: 812c9c7c3fd5bdfc78999933ff1a79bc9634fc7c
