### ISSUE TITLE
decreased protein localization to mitotic contractile ring

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2260]
descendent of
decreased protein localization to actomyosin contractile ring

def
A cell phenotype observed in the vegetative growth phase of the life cycle in which the localization of a protein to the mitotic contractile ring is decreased.

PMID:25688133

**Comment by ValWood** [comment]
Comments from Midori:
b) the existing term is already defined as applying to vegetative growth/mitotic cytokinesis, so I'll add a synonym
c) GO CC doesn't define a "mitotic contractile ring"

**Comment by ValWood** [comment]
b) OK

c) I guess they should.
The reason we have mitotic specific processes in GO is so we can get the annotations under the relevant cell cycle, but this hasn't been an issue for component...... also we  know nothing about meiotic cytokinesis or how it differs....

**Comment by mah11** [comment]
c) What I could do instead is request a GO BP term for localization to the ring during mitotic cytokinesis (should be TG-able), and switch FYPO xps to it where applicable. the FYPO term is defined as something going wrong (or not, for the "normal" term) with the localization process anyway, so that'll work and won't open worm-cans at GO.

**Comment by ValWood** [comment]
Yep I don't think Go is well placed for another can of worms right now. We can sit on that can if we can...

**Comment by mah11** [comment]
quoth TG
ID: GO:1904498 Label: protein localization to actomyosin contractile ring involved in mitotic cytokinesis

**Comment by mah11** [comment]
xp updates done; synonyms added

**Comment by mah11** [comment]
edit file: e78131ae9f80d87fc081f0db57734c7aa001fec8
release: 812c9c7c3fd5bdfc78999933ff1a79bc9634fc7c
