### ISSUE TITLE
ntr: abolished protein localization to medial cortical node, with protein mislocalized to cytoplasm

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2261]
standard def:
abolished protein localization to medial cortical node, with protein mislocalized to cytoplasm

**Comment by ValWood** [comment]
PMID:25688133

**Comment by mah11** [comment]
abolished protein localization to medial cortical node, with protein mislocalized to cytoplasm FYPO:0004735

**Comment by mah11** [comment]
edit file: e78131ae9f80d87fc081f0db57734c7aa001fec8
release: 812c9c7c3fd5bdfc78999933ff1a79bc9634fc7c
