### ISSUE TITLE
ntr: decreased F-Actin in contractile ring

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2262]
decreased abundance of actin in the actomyosin contractile ring in early mitosis

(Kathy  also added this note
the decreased abundance of actin in the actomyosin contractile ring is an abnormal actin cytoskeleton with less F-actin as the CR forms (in early mitosis) and not in anaphase)

PMID:25688133

**Comment by ValWood** [comment]
also
normal abundance of actin in the actomyosin contractile ring in anaphase B

**Comment by ValWood** [comment]
decreased abundance of actin in the actomyosin contractile ring in early mitosis
This was requested as a descendent of abnormal actin cytoskeletin, but i guess it could be 
"abnormal actin ring organization"?

**Comment by mah11** [comment]
abnormal actomyosin contractile ring FYPO:0004736
  decreased F-actin level in actomyosin contractile ring during early mitosis FYPO:0004737
  abnormal actomyosin contractile ring organization FYPO:0004738
  normal actin cytoskeleton during vegetative growth FYPO:0004739
  normal actomyosin contractile ring FYPO:0004740
  normal F-actin level in actomyosin contractile ring during anaphase B FYPO:0004741

These are structure phenotypes, so they can't have is_a links to "organization" phenotype terms. I've included 'abnormal actomyosin contractile ring' output_of 'abnormal actomyosin contractile ring organization'.

**Comment by mah11** [comment]
edit file: e78131ae9f80d87fc081f0db57734c7aa001fec8
release: 812c9c7c3fd5bdfc78999933ff1a79bc9634fc7c
