### ISSUE TITLE
ntr: increased number of actin patches at cell tip in early mitosis

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2264]
ntr: increased number of actin patches at cell tip in early mitosis

A cell phenotype in which the number of actin patches observed at the cell tip is higher than normal during early mitosis

PMID:25688133

**Comment by mah11** [comment]
actin cortical patches present in greater numbers at cell tip during early mitosis FYPO:0004747
(with various synonyms)

**Comment by mah11** [comment]
edit file: 0f9dda8eb776ac06d7de0f4795eb1ae6da751294
release: 863e7570fe1db168c75b987dcd624cf183f18827
