### ISSUE TITLE
ntr: elongated septated vegetative cell

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2266]
odd that we don't have this?

**Comment by mah11** [comment]
not that odd; life's too short for me to add every combinatorially possible intermediate 'yada yada vegetative cell' term before they get requested ;)

**Comment by mah11** [comment]
elongated septated vegetative cell FYPO:0004750

**Comment by ValWood** [comment]
odd that we haven't seen it before, not that you haven't added it. I thought we would use this phenotype all the time....it makes me worry that I have used a 'dead or alive' version when I could not possibly have known.....

**Comment by mah11** [comment]
edit file: 0f9dda8eb776ac06d7de0f4795eb1ae6da751294
release: 863e7570fe1db168c75b987dcd624cf183f18827
