### ISSUE TITLE
protein localization terms to medial cortex

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2267]
I notice that some of these have "vegetative growth" in the term names and some don't, although they are defined vegetatively.
If they don't need it  can  it be dropped from all the term names?

**Comment by mah11** [comment]
"Vegetative" cannot be dropped. With two exceptions, the names and logical defs match.

To do: add "vegetative" to names FYPO:0002558 & FYPO:0003390

**Comment by mah11** [comment]
edit file: 0f9dda8eb776ac06d7de0f4795eb1ae6da751294
release: 863e7570fe1db168c75b987dcd624cf183f18827
