### ISSUE TITLE
ntr: resistance to....

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2268]
G418
phleomycin

for Per
https://rt.sanger.ac.uk/Ticket/Display.html?id=481213
PMID:25793410

**Comment by mah11** [comment]
resistance to G418 FYPO:0004751
  resistance to phleomycin FYPO:0004752

**Comment by mah11** [comment]
edit file: 0f9dda8eb776ac06d7de0f4795eb1ae6da751294
release: 863e7570fe1db168c75b987dcd624cf183f18827
