### ISSUE TITLE
question about condition 1NM-PP1

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2272]
I want to use
NM-PP1

but the conc. here is
30 mM of the Nm-PP1 inhibitor (TRC) from a 10 mM stock in DMSO. 
(I have NO IDEA what this is, I can't remember how to work it out)

Does this term need to specify concentration?

Val

**Comment by mah11** [comment]
Don't understand the question -- in the obo file the "+ 1NM-PP1" def doesn't specify a concentration; it just uses the standard "added to the medium or assay buffer in excess compared to standard medium or assay buffers" wording. Still holds when the standard amount is "none" ;)

**Comment by ValWood** [comment]
OK I think I misread the def when I saw it (there does not seem to be a way to read a condition def again once you have used it...)

but what is the preceeding "1" for. Isn't the compound called "NM-PP1"

**Comment by mah11** [comment]
No. It's sometimes hyphenated, but never without the "1". Maybe we should use the hyphenated version for the PECO term name, because that's the way ChEBI has it - http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:52309

**Comment by ValWood** [comment]
Ok the nurse paper just calls it Nm-PP1 not 1NM-PP1

**Comment by Antonialock** [comment]
ok put + 1NM-PP1 in synonym and changed primary name to + 1-NM-PP1
