### ISSUE TITLE
abnormal sporulation resulting in formation of azygotic ascus with more than four spores

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2273]
Jacky used:
abnormal sporulation resulting in formation of azygotic ascus with more or fewer than four spores

and added the comment
60% of population have >4 spores per asci

I just checked and the >4 spored term is not visible as a descendent....could/should it be?

**Comment by mah11** [comment]
Don't know which term you mean my "the 4 spored term"; 4 spores would be normal.

This link is asserted, for the terms that don't specify "azygotic":

FYPO:0003263 abnormal sporulation resulting in formation of ascus with more than four spores 
is_a: FYPO:0001894 abnormal sporulation resulting in formation of ascus with more or fewer than four spores

But we don't have a term that's specific to both "azygotic" and "more than four spores". I can add one if that's what Jacky needs; it would be is_a FYPO:0001893 and is_a FYPO:0003263.

**Comment by ValWood** [comment]
Ah I misread that

so I need abnormal sporulation resulting in formation of azygotic ascus with more  than four spores

**Comment by mah11** [comment]
ok, in the new term queue ...

**Comment by mah11** [comment]
abnormal sporulation resulting in formation of azygotic ascus with more than four spores FYPO:0004760

**Comment by mah11** [comment]
edit file: 0f9dda8eb776ac06d7de0f4795eb1ae6da751294
release: 863e7570fe1db168c75b987dcd624cf183f18827
