### ISSUE TITLE
add comment to "inviable spore population"

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2274]
Add a comment to describe when this term should be used

for example:
gene that when knocked out in a diploid, then the resulting spores didn't germinate, but if you knocked out the gene in a vegetative cell then they were viable.

i.e This term is only used for  mutants if the entire ppulation cannot sporulate. If any of the population can germinate, but the population is inviable, gene product  is not required for sporulation and use "inivable vegetative population" term?

To describe a  mixed population  which included inviable spores, use  the cellular phenotype "inviable spore" with penetrance

**Comment by mah11** [comment]
hooray, an easy one! done.

**Comment by mah11** [comment]
edit file: 0f9dda8eb776ac06d7de0f4795eb1ae6da751294
release: 863e7570fe1db168c75b987dcd624cf183f18827
