### ISSUE TITLE
ntrs for zygotic/azygotic meiosis

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2275]
we already have 
decreased meiotic recombination during zygotic meiosis
so these are the things I would like to distinguish/capture

ntr: abolished meiosis II  during azygotic meiosis
ntr: delayed premeiotic DNA replication during azygotic meiosis
ntr: abolished meiosis II  during zygotic meiosis
ntr: abolished premeiotic DNA replication during azygotic meiosis
ntr: normal meiosis I during azygotic meiosis
ntr: normal meiosis during azygotic meiosis
ntr: normal meiosis during zygotic meiosis

I need to differentiate some at phenotype level
Jacky: Yes that's true but in some cases you might need it  eg pat1AS induced azygotic asci and crm1 rem1 dels had no phenotype where as they did in a zygotic meiosis . But still it is the type of meiosis that causes the difference rather than pat1AS . So I'm not sure.

I'm not sure the best way to do it or how far to go with replicating the meiotic terms as zygotic and azygotic...or how they should be named
"during azygotic meiosis", or "after induced azygotic sporulation" or something else

(Midori you can address the terms from this paper last as Jacky is away until 13 Aug, and I will need to go through  quite a  few questions when she returns)

**Comment by ValWood** [comment]
Also, is there anyway to do this so we can assume that all existing terms are 'zygotic'?

**Comment by ValWood** [comment]
Ah I see now, I think you were both saying they would all go under

abnormal sporulation resulting in....
(like the existing abnormal sporulation resulting in formation of azygotic ascus with more or fewer than four spores)

Is that right?

**Comment by ValWood** [comment]
but we have this term
"decreased meiotic recombination during zygotic meiosis"
How does that differ from
"decreased meiotic recombination"?

**Comment by ValWood** [comment]
The main difference between these two 'processes' seems to be the shape of the ascus (bent vs straight)
http://www.nature.com/nprot/journal/v9/n1/fig_tab/nprot.2014.013_F1.html
But it isn't clear to me whether 'azygotic' is ever 'normal' or is only ever 'induced'

**Comment by mah11** [comment]
You requested "decreased meiotic recombination during zygotic meiosis" (FYPO:0004089), correctly I think, for PMID:11907273 which showed an effect specifically on recombination in zygotic meiosis, and not in azygotic meiosis. It looks like you could also have requested and used "normal meiotic recombination during azygotic meiosis" for the same allele.

I haven't the foggiest whether fission yeasties would encounter the nutrient conditions that lead to azygotic meiosis & sporulation in the wild, but I've become convinced that azygotic m&s would be the normal course of events if they did.

**Comment by mah11** [comment]
Email discussion going on about whether to add zygotic/azygotic terms or just use presence or absence of pat1-AS allele in genotypes to distinguish. I'll await the outcome ...

**Comment by ValWood** [comment]
Re:
I haven't the foggiest whether fission yeasties would encounter the nutrient conditions that lead to azygotic meiosis & sporulation in the wild, but I've become convinced that azygotic m&s would be the normal course of events if they did.

So what would those conditions likely to be again? Just interested?

**Comment by mah11** [comment]
To the limited extent that I understand it, starvation induces mating, and then meiosis, and then sporulation. An influx of food after mating but before meiosis starts allows diploids to grow and divide. In the lab you can get that timing precise enough (although it sounds like a pain); not sure whether it happens in the wild, cos they'd have to get very lucky.

**Comment by ValWood** [comment]
how long is the time between mating and meiosis?

**Comment by mah11** [comment]
damned if I know! long enough for a determined grad student to squirt some fresh media in, but ask someone else if you want it more precise ;)

**Comment by ValWood** [comment]
I used my "phone a friend" will let you know

**Comment by mah11** [comment]
From email exchange (me):
Almost all of the meiosis & sporulation FYPO terms are neutral with respect to zygotic vs. azygotic. In other words, they're mostly the generic terms that would be is_a parents of any zygotic- or azygotic-specific terms we may need now or later.

So, if you just use the pat1 allele to distinguish genotypes, the fact that the meiosis & sporulation in those cells is azygotic will be kind of buried -- people will have to know that that's what the pat1-AS allele does (or look it up) -- i.e. the annotations won't be wrong, they'll just be a teensy bit less specific than is possible.

-

So we do want to add the specific terms in the original request here, i.e am I interpreting the last couple of  emails correctly?

**Comment by ValWood** [comment]
yep. I am still trying to find out if it is ever 'normal' but I think we should go ahead and add them....

**Comment by mah11** [comment]
ok, will keep 'em in the queue. just a few other tickets ahead of this now, I think ...

**Comment by ValWood** [comment]
You can do anything related to this paper last......

**Comment by mah11** [comment]
PMID:25891897

**Comment by mah11** [comment]
added the terms:

ticket #2275
new terms
  normal zygotic meiosis FYPO:0004795
  normal azygotic meiosis FYPO:0004796
  normal azygotic meiosis I FYPO:0004797
  abolished azygotic meiosis II FYPO:0004798
  abolished zygotic meiosis II FYPO:0004799
  abolished premeiotic DNA replication during azygotic meiosis FYPO:0004800
  delayed premeiotic DNA replication during azygotic meiosis FYPO:0004801

edit file: 31e3c0ee57831ca2436d1957c64871a1ce2649b1
release: 04f808b0e557096b51b45c9ace58b86b9757fb82
