### ISSUE TITLE
MP: viable elongated vegetative cell

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2279]
currently I don't see
viable elongated vegetative cell
as a descendent of
elongated vegetative cell?

**Comment by mah11** [comment]
This is a reasoner thing. I do not understand why it doesn't infer the link you want, when does infer these:

FYPO:0001493 inviable elongated multinucleate vegetative cell
is_a: FYPO:0000133 ! elongated multinucleate vegetative cell

does me 'ead in ...
is_a: FYPO:0001490 ! inviable elongated vegetative cell

**Comment by mah11** [comment]
I'll try changing one of the has_part links to something with 'vegetative' and see if that helps

**Comment by mah11** [comment]
well, that improved it somewhat, and is probably about the best I can do with it for the short to medium term :/

**Comment by mah11** [comment]
what fixes I could do are in
edit file: 50c79b49a8ad108d502392d5315198de054d365d
release: 2c741a5af24c2df0a7d56ce61ba1fc188161a57d
