### ISSUE TITLE
ntr: normal DNA annealing activity  PMID:25520186

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2280]
normal GO:0097617
Name	annealing activity

**Comment by ValWood** [comment]
actually due to this comment
The term 'annealing' is often used to describe the binding of a DNA probe, or the binding of a primer to a DNA strand during a polymerase chain reaction. The term is also often used to describe the reformation (renaturation) of complementary strands that were separated by heat (thermally denatured). For example, proteins such as RAD52 can help DNA anneal. If at all possible, please annotate to the more specific terms GO:0036310 'annealing helicase activity', GO:0097098 'DNA/RNA hybrid annealing activity' or GO:0033592 'RNA strand annealing activity'.

I am going to request a more specific ssDNA annealing term

**Comment by ValWood** [comment]
ID: GO:1990814 Label: ssDNA annealing activity

**Comment by mah11** [comment]
normal DNA/DNA annealing activity FYPO:0004787

**Comment by mah11** [comment]
edit file: 55e04398e5e2225aabe92448673337b58daa3dde
release: f6f0f40a298359a5ed951747756ba3b846ca8b05
