### ISSUE TITLE
ntr: abolished interphase microtubule nucleation PMID:15772152

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2281]
ntr: abolished interphase microtubule nucleation
standard def
PMID:15772152

**Comment by mah11** [comment]
abolished interphase microtubule nucleation FYPO:0004766

**Comment by mah11** [comment]
edit file: 50c79b49a8ad108d502392d5315198de054d365d
release: 2c741a5af24c2df0a7d56ce61ba1fc188161a57d
