### ISSUE TITLE
ntr: vacuolar amino acid levels

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2284]
increased vacuolar level of
threonine
serine
asparagine
glutamine
glycine
alanine
lysine
histidine
arginine
proline

reduced vacuolar levels of
lysine
histidine
arginine

 
PMID:26083598

**Comment by mah11** [comment]
added:
  increased vacuolar alanine level FYPO:0004767
  increased vacuolar arginine level FYPO:0004768
  increased vacuolar asparagine level FYPO:0004769
  increased vacuolar glutamine level FYPO:0004770
  increased vacuolar glycine level FYPO:0004771
  increased vacuolar histidine level FYPO:0004772
  increased vacuolar lysine level FYPO:0004773
  increased vacuolar proline level FYPO:0004774
  increased vacuolar serine level FYPO:0004775
  increased vacuolar threonine level FYPO:0004776

already existed:
  decreased vacuolar lysine level FYPO:0001610
  decreased vacuolar histidine level FYPO:0001611
  decreased vacuolar arginine level FYPO:0001612

**Comment by mah11** [comment]
edit file: 50c79b49a8ad108d502392d5315198de054d365d
release: 2c741a5af24c2df0a7d56ce61ba1fc188161a57d
