### ISSUE TITLE
 	 decreased histone methyltransferase activity 

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2287]
decreased histone methyltransferase activity

**Comment by mah11** [comment]
abnormal histone methyltransferase activity FYPO:0004783
  decreased histone methyltransferase activity FYPO:0004784

**Comment by mah11** [comment]
edit file: 50c79b49a8ad108d502392d5315198de054d365d
release: 2c741a5af24c2df0a7d56ce61ba1fc188161a57d
