### ISSUE TITLE
NTR: increased duration of mitotic G1 phase progression

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2308]
descendent of
abnormal mitotic G1 phase progression

can we block "abnormal mitotic G1 phase progression" for direct annotation as we should always know *how* it is abnormal?

**Comment by mah11** [comment]
We used to have a separate term for "increased duration of mitotic G1 phase", but we couldn't define a difference from "mitotic G1/S transition delay" (FYPO:0000333), so they were merged ages ago. The "duration" synonyms are related.

There are no direct annotations to "abnormal mitotic G1 phase progression" (FYPO:0000602) as of the v54 PHAF.

**Comment by ValWood** [comment]
OK, I was looking at this
http://www.pombase.org/spombe/result/SPCC4E9.02
but it is not present on stage...

**Comment by JackyVH** [comment]
Hi Val

The delay seen  in a cig1 delete in Bueno et al was wrong and an erratum was published which I've attached.  This is probably not relevant to the discussion but thought I'd mention it.

Jacky

**Comment by mah11** [comment]
Looks like Antonia is looking at the Canto session for the Bueno et al. paper (PMID:1829983, http://curation.pombase.org/pombe/curs/b65b4c7d7b9528f2).

**Comment by ValWood** [comment]
Yes it would be good if we could link erratums with the primary publications...

**Comment by ValWood** [comment]
yep, I think Antonia has removed the annotation recently. All good...
