### ISSUE TITLE
ntr: abolished response the mitotic spindle assembly checkpoint signalling

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2310]
standard def

 PMID:11080156

**Comment by mah11** [comment]
We’d previously decided that this is the same as FYPO:0004537 (details below) - see #2170 (#2133 & #2190 also relevant).

Is that still the case, or is there now a way to make (i.e. define) a distinction? Or should I just add one more synonym?

id: FYPO:0004537
name: mitotic spindle assembly checkpoint override
def: "A cellular process phenotype in which a mitotic cell cycle arrest that normally occurs in response to mitotic cell cycle spindle assembly checkpoint signaling does not occur. As a result, the septation initiation network (SIN) signaling pathway is activated despite activation of the mitotic spindle assembly checkpoint (SAC). Normally, under conditions that activate the SAC, SIN activation is inhibited and the cell cycle arrests in anaphase. In this phenotype, premature SIN activation leads to premature cytokinesis and the formation of cut cells." [PMID:11952833, PomBase:mah, PomBase:vw]
synonym: "abolished response to mitotic cell cycle spindle assembly checkpoint signaling" EXACT [PomBase:mah]
synonym: "mitotic cell cycle spindle assembly checkpoint override" EXACT [PomBase:mah]
synonym: "mitotic SAC override" EXACT [PomBase:mah]
synonym: "septation initiation signaling activation in presence of active mitotic spindle assembly checkpoint" EXACT [P\
omBase:mah]
synonym: "SIN activation in presence of active mitotic SAC" EXACT [PomBase:mah]

**Comment by ValWood** [comment]
I used the checkpoint override term

**Comment by mah11** [comment]
ok, will close
