### ISSUE TITLE
viable curved vegetative cell with elongated curved microtubules

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2312]
child of
viable curved vegetative cell

PMID:18418055

**Comment by mah11** [comment]
curved microtubules FYPO:0004862
  long curved microtubules FYPO:0004863
  viable curved vegetative cell with long curved microtubules FYPO:0004864

**Comment by mah11** [comment]
edit file: d8336ce9c1bf6f49b17dced4e4f2afd769d6cbb2
release: 8a9c45cd3600794a1651f7865b5290988dd03528
