### ISSUE TITLE
long astral microtubules during mitotic anaphase A

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2313]
child of 
long astral microtubules

PMID:18418055

**Comment by mah11** [comment]
long astral microtubules during mitotic anaphase A FYPO:0004865

**Comment by mah11** [comment]
edit file: d8336ce9c1bf6f49b17dced4e4f2afd769d6cbb2
release: 8a9c45cd3600794a1651f7865b5290988dd03528
