### ISSUE TITLE
always distinguish between normal and abnormal arrest phenotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2317]
should cell cycle arrest phenotype, and some children, be not for direct annotation?

**Comment by mah11** [comment]
FYPO:0001024 ! cell cycle arrest phenotype is flagged. Which other term(s) do you want added to the subset?

**Comment by ValWood** [comment]
The descendants are
abnormally arrested cell cycle progression  
mitotic cell cycle arrest phenotype

 so I guess "mitotic cell cycle arrest phenotype" could always be more specific?
and "mitotic cell cycle arrest phenotype"
and "normally arrested mitotic cell cycle progression" should we be able to say when?

Maybe any term which does not specify "normal" or "abnormal" would that make sense?

**Comment by mah11** [comment]
OK, flagged a few more terms

**Comment by mah11** [comment]
edit file: d8336ce9c1bf6f49b17dced4e4f2afd769d6cbb2
release: 8a9c45cd3600794a1651f7865b5290988dd03528
