### ISSUE TITLE
curved or bent spindle

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2323]
for these terms:
long curved mitotic spindle during anaphase 
and
bent spindle

does curved and bent imply the same thing?

**Comment by mah11** [comment]
They're different - "bent" means a sharp angle, whereas "curved" means following a smooth arc. The FYPO:0004439 def needs work, so I'll fix it next time I'm editing.

**Comment by mah11** [comment]
def edited

**Comment by mah11** [comment]
edit file: efec7cd516c8799b2c97b8f32feb60b54f957b00
release: 19d729c9796e57e7f473149f79135db5f54c5999
