### ISSUE TITLE
 	 increased duration of histone h2a phosphorylation during cellular response to ionizing radiation

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2326]
increased duration of histone h2a phosphorylation during cellular response to ionizing radiation

**Comment by mah11** [comment]
increased duration of histone H2A phosphorylation during cellular response to ionizing radiation FYPO:0004891

**Comment by mah11** [comment]
edit file: efec7cd516c8799b2c97b8f32feb60b54f957b00
release: 19d729c9796e57e7f473149f79135db5f54c5999
