### ISSUE TITLE
Q about "abnormal sporulation resulting in formation of ascus containing anucleate spores "

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2338]
For the term
abnormal sporulation resulting in formation of ascus containing anucleate spores 

does anucleate spores = no DAPI staining (i.e. there might be a nuclear membrane etc but with no DNA in it)? (i.e. when is a nucleus a nucleus...)
or is this term only to be used when they look for nuclei by some other means (EM?)

If it is ok to use this term when there is no DAPI staining in a subset of the spores, then this ticket can be closed, otherwise I need a term for 
abnormal sporulation resulting in formation of ascus containing spores with no DNA (or similar)

**Comment by mah11** [comment]
If the authors interpret no DAPI as no nucleus (and I suspect they would), I don't mind going along with it.

I don't think I would fuss about whether there's an empty nuclear membrane/envelope kicking around ... a bag with no DNA is pretty hard to identify as a nucleus.

**Comment by Antonialock** [comment]
ok! "bag with no DNA is pretty hard to identify as a nucleus" that's the conundrum, but I'm (more) happy to roll with that (than not)
