### ISSUE TITLE
JH term request  from PMID: 1316996 inviable elongated mononucleate aseptate cell arrested in G2"

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2339]
This is from Jacky's session

There is a sibling
inviable elongated mononucleate aseptate vegetative cell with cell cycle arrest in mitotic M phase 

It made me realise that I don't know how you know if a cell is  in G2 or M  (but in prophase or metaphase), I will ask. I might need to correct some of my old annotations to

inviable elongated mononucleate aseptate vegetative cell with cell cycle arrest in mitotic M phase

**Comment by mah11** [comment]
I'll also add one for "with cell cycle arrest" but without specifying which phase, for the ones where you can't tell (and I don't have enough pombe background to know how you'd tell).

**Comment by mah11** [comment]
inviable elongated mononucleate aseptate vegetative cell with mitotic cell cycle arrest in mitotic G2 phase FYPO:0004922
  inviable elongated mononucleate aseptate vegetative cell with mitotic cell cycle arrest FYPO:0004923

**Comment by mah11** [comment]
edit file: fedad3dc05dbea79bf554eff4835023ad8a5ab61
release: 154d4089fe3156b9a93a5cd829b2c555ac49371b
