### ISSUE TITLE
 	 normal mitotic telomere tethering at nuclear periphery 

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2340]
normal mitotic telomere tethering at nuclear periphery

**Comment by mah11** [comment]
normal telomere tethering at nuclear periphery FYPO:0004924

**Comment by mah11** [comment]
edit file: fedad3dc05dbea79bf554eff4835023ad8a5ab61
release: 154d4089fe3156b9a93a5cd829b2c555ac49371b
