### ISSUE TITLE
Q about premature/advanced

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2344]
Is premature really the same as advanced? To me premature implies that something occurs before something else in a sequence (when it should occur after), whereas advanced implies quicker than normal (may be because it has jumped ahead in a sequence, or because things ahead in the sequence completed faster than normal)
 
ID 	FYPO:0000479
Ontology 	fission_yeast_phenotype
Term name 	premature meiosis
Definition 	A cellular process phenotype in which one or both meiotic nuclear division(s) occurs prematurely.
Synonyms 	
advanced meiosis
meiosis: premature
premature meiotic nuclear division

**Comment by mah11** [comment]
> Is premature really the same as advanced?

According to PATO, yes (although "advanced" also has some slightly different possible meanings in vernacular English, for phenotype definitions we ignore them, and follow PATO).

I see that I haven't been totally consistent in whether "premature" or "advanced" is in the term names, nor in making sure the definitions include "begins earlier than normal". I'll tidy those up.

**Comment by mah11** [comment]
[Term]
id: PATO:0000694
name: premature
alt_id: PATO:0000691
alt_id: PATO:0002086
def: "A quality of a process which starts earlier than the natural start time or the reference process." [PATO:LC]
subset: value_slim
synonym: "advanced" EXACT []
synonym: "early" RELATED []
synonym: "precocious" RELATED []
is_a: PATO:0002325 ! onset quality

**Comment by Antonialock** [comment]
ok cheers!

**Comment by mah11** [comment]
all tidied - standardized on 'premature' in names and 'advanced' in exact synonyms, and made sure def wording is consistent

**Comment by mah11** [comment]
edit file: fedad3dc05dbea79bf554eff4835023ad8a5ab61
release: 154d4089fe3156b9a93a5cd829b2c555ac49371b
