### ISSUE TITLE
normal growth on CAA/chloroacetaldehyde PMID:22365419 

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2346]
normal growth on chloroacetaldehyde

**Comment by mah11** [comment]
normal growth on chloroacetaldehyde FYPO:0004940

**Comment by mah11** [comment]
edit file: fedad3dc05dbea79bf554eff4835023ad8a5ab61
release: 154d4089fe3156b9a93a5cd829b2c555ac49371b
