### ISSUE TITLE
sensitive to sodium orthovanadate PMID:11015724

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2347]
sensitive to sodium orthovanadate

**Comment by mah11** [comment]
FYPO:0000718 sensitive to trisodium vanadate

has 'sensitive to sodium orthovanadate' as an exact synonym, so should've been findable ...?

**Comment by ValWood** [comment]
ah that did come up, I wondered if it was the same, but I thought that in these cases the synonym you searched on was shown on the term page (it wasn'y)?

**Comment by mah11** [comment]
erm, I don't remember ... haven't searched by synonym in ages ...

**Comment by ValWood** [comment]
Actually I now see synonyms and a comment on the page which were not showing up previously. I think this was  when I accessed the term via the pop-up rather than via the primary search box...will evaluate further

**Comment by Antonialock** [comment]
I think you can merge 
ID 	FYPO:0003656
Ontology 	fission_yeast_phenotype
Term name 	sensitive to vanadate 

according to wikipedia:
"Dissolution of vanadium pentoxide in strongly basic aqueous solution gives the colourless VO43− ion"
and
VO43− "orthovanadate

**Comment by mah11** [comment]
I'd previously done FYPO:0000718 and FYPO:0000830 (resistance) using CHEBI:30528, meaning any vanadium oxoanion, but I'm willing to risk switching to the vanadate(3-) term (CHEBI:46442). Merge done.

**Comment by mah11** [comment]
merge in
edit file: fedad3dc05dbea79bf554eff4835023ad8a5ab61
release: 154d4089fe3156b9a93a5cd829b2c555ac49371b
