### ISSUE TITLE
normal galactose : mannose ratio in N-linked oligosaccharides PMID:11015724

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2348]
normal galactose : mannose ratio in N-linked oligosaccharides

Is that possible?

**Comment by ValWood** [comment]
PMID:11015724

**Comment by ValWood** [comment]
reduced amount of  galactose residues in oligosaccharides
reduced amount of mannose residues in oligosaccharides

(are these allowed?)

**Comment by mah11** [comment]
Modeled on existing terms under FYPO:0003290 'abnormal glycoprotein glycan structure':
  decreased mannose level in glycoprotein glycan FYPO:0004941
  for galactose use: decreased galactose level in glycoprotein glycan FYPO:0003354

Directly under 'normal phenotype':
  normal galactose:mannose ratio in glycoprotein glycan FYPO:0004942

**Comment by mah11** [comment]
edit file: fedad3dc05dbea79bf554eff4835023ad8a5ab61
release: 154d4089fe3156b9a93a5cd829b2c555ac49371b
