### ISSUE TITLE
add condition +nigericin

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2350]
+nigericin

**Comment by Antonialock** [comment]
do you think an antibiotic should be added to the conditions?

**Comment by ValWood** [comment]
Why not ? it just happens to be also an antibiotic but we have other chemicals don't we?

**Comment by Antonialock** [comment]
It just seems more term-ey than conditiony. Antibiotics often screw up the cell wall afaik? What do you want to capture?

**Comment by ValWood** [comment]
This is doing something to mitochondrial transport or membrane potential. I'm trying to capture a difference with and without the "condition". 
I guess I should just do it as increased sensitivity though....

**Comment by Antonialock** [comment]
I don't think I have specified any antibiotics in the conditions, so I was interested in what you were capturing for consistency purposes.

I don't know how to define my condition usage linguistically but some examples of my most common ones:
- yes vs minimal media
- liquid vs agar plates
- the type of salt added to "sensitive to salt" (nacl, kcl etc)

**Comment by Antonialock** [comment]
"Nigericin acts as an H+, K+, Pb2+ ionophore. Most commonly it is an antiporter of H+ and K+."

**Comment by ValWood** [comment]
yeah don't worry this is just sensitivity. I was over annotating...

**Comment by Antonialock** [comment]
so you add something that messes up the membrane potential, and in the mutant the effect is more pronounced (presumably because it already has some issues in that department)

**Comment by Antonialock** [comment]
ok cool :)

**Comment by ValWood** [comment]
I see what I was trying to do now.

It has decreased membrane potential in presence of nigericin
this is not apparant in mutant without nigericin?

**Comment by Antonialock** [comment]
hmm, well, If you think it should be a condition rather than a complete phenotype term then reopen..

**Comment by ValWood** [comment]
How would the other way to do this be?

Fully precompose?
decreased membrane potential in presence of nigericin?

Val

**Comment by Antonialock** [comment]
I wouldn't. I haven't looked at the paper (it is not linked), but I guess that I would annotate to "sensitive to nigericin" and maybe (depending on what other experiments have been done and what they infer from prior knowledge) something like "abnormal cellular (cat)ion homeostasis" (or possibly "abnormal regulation of membrane potential" if they are really looking at membrane potential - but without being an expert I'm unsure a sensitivity assay would tell you this much...so again, other experiments and prior knowledge). 

To me, it sounds like the nigericin is just a tool to enable you to see how the cell is dealing with ionic perturbations. Adding it as a condition doesn't add any more "detail" to the annotation. (Like saying that the cells grow normally in YES but perhaps not in EMM for instance).

**Comment by ValWood** [comment]
OK!

**Comment by mah11** [comment]
I don't mind whether you include nigericin as a condition or not, but I don't want to precompose this term. The cases where I've precomposed with chemical names are (a) cell growth and (b) where it's indirect via a GO BP term for "response to" the chemical. This doesn't fit either.

It's the DiOC6 staining that measures membrane potential, and that's regarded as fairly reliable (not just in pombe), although it looks qualitative rather than quantitative in this paper. The "decreased membrane potential" term Val requested in #2349 looks fine. I wouldn't use a homeostasis term.

**Comment by ValWood** [comment]
OK I'll go with "decreased membrane potential" .

**Comment by Antonialock** [comment]
ok i have added + nigericin so you can use it, I'm not sure what I would do (I still dont know what the experiments were really) but I guess it doesn't hurt

**Comment by ValWood** [comment]
I may not use it. I still need to go back and finish this paper. Putting it off...)
