### ISSUE TITLE
add synonym spindle checkpoint

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2353]
would it be reasonable to add
increased Mad2 foci
increased Bub1 foci
increased Mad2 nuclear dots
increased Bub1 nuclear dots
to

FYPO:0002638
Ontology	fission_yeast_phenotype
Term name
increased activation of mitotic cell cycle spindle assembly checkpoint

As this is what is tested, and so probably what people will search for.
v

**Comment by mah11** [comment]
Well, they look really weird to me, but that could be my total lack of pombe background. If they'll help I can add the "foci" terms as related synonyms (no way they're exact!). Google suggests the "nuclear dots" phrasing is rare for Mad2 or Bub1, so I think those would be a lot less useful.

**Comment by ValWood** [comment]
leave out the nuclear dots one. I think it will be useful for people to find this term if they search on Md2/bub1 though

**Comment by mah11** [comment]
"foci" related synonyms added

**Comment by mah11** [comment]
edit file: fedad3dc05dbea79bf554eff4835023ad8a5ab61
release: 154d4089fe3156b9a93a5cd829b2c555ac49371b
