### ISSUE TITLE
add synonym to "cell cycle arrest in mitotic G2 phase"

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2354]
add "interphase block"
(I know that interphase is more than G2 but 'interphase block' is pretty universally used to indicate "no entry into mitosis"...so perhaps related?)

FYPO:0000446
Ontology	fission_yeast_phenotype
Term name
cell cycle arrest in mitotic G2 phase

**Comment by ValWood** [comment]
ignore....

**Comment by ValWood** [comment]
add "interphase block" synonym to 
cell cycle arrest in mitotic interphase

**Comment by mah11** [comment]
added

**Comment by mah11** [comment]
edit file: fedad3dc05dbea79bf554eff4835023ad8a5ab61
release: 154d4089fe3156b9a93a5cd829b2c555ac49371b
