### ISSUE TITLE
query parentage cell cycle arrest

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2355]
abolished cell cycle arrest in mitotic G1 phase in response to nitrogen starvation
is a descendent of

cell cycle arrest in mitotic G1 phase?

**Comment by mah11** [comment]
fixed

**Comment by mah11** [comment]
edit file: fedad3dc05dbea79bf554eff4835023ad8a5ab61
release: 154d4089fe3156b9a93a5cd829b2c555ac49371b
