### ISSUE TITLE
ntr: elongated oscillating nucleus during vegetative growth PMID:16611238

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2356]
descendant of
FYPO:0000832	elongated nucleus

fig1 a&b PMID:16611238

**Comment by ValWood** [comment]
actually this phenotype only occurs when the cells are also elongated. The normal length cells have normal shape and size nucleus.

so it would be:
elongated vegetative cell with elongated oscillating nucleus.....

**Comment by mah11** [comment]
another oddball!

elongated vegetative cell with elongated oscillating nucleus FYPO:0004950

**Comment by Antonialock** [comment]
is the cell trying to do horsetail movement in the vegetative phase?

**Comment by Antonialock** [comment]
ah looks like a cool paper!

**Comment by ValWood** [comment]
Its another oldie....alp4 is going on forever! 

> is the cell trying to do horsetail movement in the vegetative phase?

kind of, that's was the assumption, but oddly its independent of dhc1/pkl1 and klp2 (next Exp), which are required for horsetail movement.....

**Comment by mah11** [comment]
edit file: fedad3dc05dbea79bf554eff4835023ad8a5ab61
release: 154d4089fe3156b9a93a5cd829b2c555ac49371b
