### ISSUE TITLE
term merge

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2358]
I think we can merge
FYPO:0001409 & FYPO:0003898
and
FYPO:0000684 & FYPO:0000442
and
FYPO:0001934 & FYPO:0003690

I think they always add small amounts of another carbon source, and that it is unimportant which one.

**Comment by mah11** [comment]
Hmm. It wouldn't do for budding yeast, which can be grown in media containing just glycerol. Not that that's a problem for FYPO, but it would be a consideration if the generic ontology gets off the ground.

PMID:23398982 has some experiments in pombe with both glycerol-only and glycerol/ethanol media (and the latter has 3% ethanol - is that still a "small amount"?). Not sure what to do here ...

**Comment by Antonialock** [comment]
I think it should be ok.... I think ethanol is utalized very different from glucose in pombe, in that growth on ethanol promotes growth on glycerol (whereas glucose represses glycerol usage).

**Comment by mah11** [comment]
closing because having separate terms hasn't yet actively caused problems; can revisit if necessary
