### ISSUE TITLE
MP elongated vegetative cell with elongated oscillating nucleus

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2364]
missing parent?
elongated vegetative cell with elongated oscillating nucleus
is not  a descendant of 
elongated  nucleus

**Comment by mah11** [comment]
edit file: 8ad92e08174157cfad7138045500f7652ec97855
release: f3fa940c3e2b1d7c71bc1e4dc7d51baff3b8160d

**Comment by ValWood** [comment]
term is
inviable elongated mononucleate vegetative cell with mislocalized nucleus
can it be "oscillating'?

it would be a child of mislocalized.

I would also like a term
NES-Alp4C also induced oscillatory movements of normal-sized nuclei in 72% of the cells (n = 65) (Fig. 5C)

so
abnormal oscillatory nuclear movement (any oscillatory movement in interphase appears to be abnormal movement). I wonder if this should be movement as opposed to 'migration'. The nucleus oscillates but it does not really migrate (which implies longer distances). It oscillates at its normal location....."These observations indicate that the nucleus is agitated by SPB movement, and this movement is mediated by MTs."

**Comment by mah11** [comment]
Is this really still the original topic, or should today's addition be in a new ticket?

**Comment by ValWood** [comment]
moved
https://github.com/pombase/fypo/issues/2383
