### ISSUE TITLE
normal telomere localization

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2365]
I need a term for normal telomere localization during mitotic interphase

(maybe a grouping term "normal telomere localization", as normal telomere clustering during meiosis could be a sibling?)

standard def

ref
PMID:16611238
"and telomeres did not cluster at the SPB but remained dispersed (Fig. 2C), showing that chromosome organi- zation in the nucleus of Alp4C-OP cells is typical of the mitotic cell cycle"

**Comment by mah11** [comment]
normal telomere localization FYPO:0004973
  normal telomere localization during mitotic interphase FYPO:0004974

**Comment by mah11** [comment]
9615de7a68bece38aa177aaedef1da62debe40c9
