### ISSUE TITLE
NTR increased  microtubule stability

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2366]
would this be an "abnormal microtubule polymerization/depolymerization" (I could not find anything like this, but 'stability' brought up one normal cytoskeletal term.

Basically I want to capture
"Backward-extending MTs are more stable in Alp4C-OP cells"
but there is a big table (1) of the  differences. It seems to summarize as  
"increased stability of backwards extending microtubules" 
"decreased stability of forwards extending microtubules" 

PMID:16611238

**Comment by mah11** [comment]
- "increased microtubule stability" is a related synonym for "decreased rate of microtubule depolymerization" (and vice versa, and propagated to terms for specific subtypes of MT e.g. cytoplasmic)

- are "backwards-extending" and "forwards-extending" commonly used designations (or are they unique to this paper/lab)? and how on earth are they defined??

**Comment by ValWood** [comment]
I've seen it before. I thought it was quite common, but it might only be from these labs.
 From what I understand it's the direction of movement of the growing microtubule. The microtubule grows from the plus end, but the movement can be from the minus end if the microtubule does not track forward?

So that would be 
a microtubule which extends/moves? in the backwards direction as it is polymerised from the plus end?

**Comment by ValWood** [comment]
If its too difficult  to model I can just so some general microtubule stability efect

**Comment by mah11** [comment]
Microtubules do not necessarily move as they polymerize or depolymerize. I'm a little confused as to whether the MTs are moving in this case, or something is moving along MTs, or both.

I can create new increased/decreased polymerization/depolymerization rate terms once I understand how to distinguish these MTs from the more general cases (existing terms FYPO:0000903, FYPO:0003194 and descendants). I'll have a more thorough look next time I do FYPO editing.

**Comment by ValWood** [comment]
From other papers, I think the movement direction  can be dependent on whether  they have reached a physical object (cell end), in addition to sliding of anti-parallell. I'm not so worried about capturing this. I only distilled it to these two terms as it was 3 sections of the paper, and a large table. Happy to just make a generic annotation.

**Comment by mah11** [comment]
did these based on descriptions in the paper (with lots of synonyms; 'stability' in related syns)

  decreased rate of microtubule depolymerization behind moving spindle pole body FYPO:0004975
  increased rate of microtubule depolymerization ahead of moving spindle pole body FYPO:0004976

**Comment by mah11** [comment]
edit file: 6adc5c7b7a97cd970a52f947b6202ff47111b8f7
release: 9615de7a68bece38aa177aaedef1da62debe40c9
