### ISSUE TITLE
question about old end/new end term

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2367]
I need a term to represent increased localization to new cell end. I used

"increased protein localization to non-growing cell tip" because this its the sibling of old cell end, but 
the new cell end is only non-growing until NETO.

Perhaps we need
"increased protein localization to new cell end"
AND
   increased protein localization to non-growing new cell-end (if the 'non-growing' part was critical to the previous annotations?

otherwise, just rename?

(should we use 'cell end' in term names? People use 'end' end 'tip' interchangeably, but I think in this context 'end' is more common. If not just synonyms)

**Comment by mah11** [comment]
I checked - the existing annotations are specific for cell ends that are not growing.

No problem to add a new term.

GO CC uses "cell tip" in names, so I'll add "cell end" synonyms to FYPO.

**Comment by mah11** [comment]
edit file: 6adc5c7b7a97cd970a52f947b6202ff47111b8f7
release: 9615de7a68bece38aa177aaedef1da62debe40c9
