### ISSUE TITLE
ntr: elongated vegetative aseptate cell

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2368]
ntr: elongated vegetative aseptate cell
ntr: elongated vegetative aseptate  aseptate cell

standard def
descendent of
elongated vegetative cell

PMID:16611237

**Comment by ValWood** [comment]
Actually these must exist but I don't see them under 
elongated vegetative cell

**Comment by ValWood** [comment]
also need
elongated monoseptate septated vegetative cell
(the existing term is mononucleate)

**Comment by mah11** [comment]
- FYPO:0000950 ! elongated aseptate cell is defined as vegetative but doesn't have veg in the name: I'll fix that

- your second request has "aseptate" repeated, and nothing else to distinguish it from the first

**Comment by ValWood** [comment]
sorry 

elongated monoseptate vegetative cell
(the elongated septate vegetative cell term I used covers mono and multi)

**Comment by mah11** [comment]
so you just need 2 terms, not 3?

**Comment by ValWood** [comment]
Ah sorry I edited one of these posts but it did not show.
I   need
ntr: elongated monoseptate vegetative cell

I found
ntr: elongated vegetative aseptate cell

both visible under
elongated vegetative cell

**Comment by mah11** [comment]
ok

**Comment by mah11** [comment]
new term
  elongated monoseptate vegetative cell FYPO:0004979
renamed FYPO:0000950 to make 'vegetative' explicit

**Comment by mah11** [comment]
edit file: 6adc5c7b7a97cd970a52f947b6202ff47111b8f7
release: 9615de7a68bece38aa177aaedef1da62debe40c9
