### ISSUE TITLE
ntr: decreased protein localization to mitotic eMTOC

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2369]
decreased protein localization to mitotic eMTOC
standard def
PMID:16611237

**Comment by mah11** [comment]
decreased protein localization to equatorial microtubule organizing center during vegetative growth FYPO:0004980

**Comment by mah11** [comment]
note - there isn't a "mitotic eMTOC" in GO CC, so I've done this as "decreased protein localization to eMTOC during vegetative growth", with synonyms

**Comment by mah11** [comment]
edit file: 6adc5c7b7a97cd970a52f947b6202ff47111b8f7
release: 9615de7a68bece38aa177aaedef1da62debe40c9
