### ISSUE TITLE
effect of chemical on enzyme activity in vitro

### ISSUE THREAD

**Issue by fypoadmin** [pombase/fypo#237]
I don't think these can be put under normal cellular response to, because the experiments were performed on purified enzyme (measured enzyme inhibition by the compound in an in vitro assay)? 

Normal response to...

-Dio-9 -?
-DCCD N,N'-dicyclohexylcarbodiimide     CHEBI:53090
-Miconazole CHEBI:6923
-DES diethylstilbestrol CHEBI:41922
Suloctidil http://en.wikipedia.org/wiki/Sulcotidil
p-hydroxymercuribenzoate CHEBI:28420
-protamine sulfate http://en.wikipedia.org/wiki/Protamine\_sulfate
-decamethylene diguanidine - ?

Original comment by: Antonialock

**Comment by mah11** [comment]
closing because it's been such a long time since the last comments
(reopen if it ever becomes a priority again)
