### ISSUE TITLE
ntr: Increased number of Brc1 foci

### ISSUE THREAD

**Issue by PRR550** [pombase/fypo#2370]
Increased number of Brc1 foci

**Comment by mah11** [comment]
Hi Paul,

I've added this new term to FYPO:

- increased number of Brc1 foci FYPO:0004951

Canto will pick up today's FYPO release overnight, so the new term will be available for you to use tomorrow.

Thanks for signing up here, and let us know if you have further questions

Best wishes,
Midori

**Comment by mah11** [comment]
(notes for our future reference:
edit file: 8ad92e08174157cfad7138045500f7652ec97855
release: f3fa940c3e2b1d7c71bc1e4dc7d51baff3b8160d)
