### ISSUE TITLE
abolished meiosis-specific transcription

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2373]
I want to change an annotation from

"abolished transcription during vegetative growth" for "assayed using" a gene which is expressed only during meiosis 
(maybe  the annotation pre dates the term becoming  v growth specific?)

ntr: abolished transcription during meiotic cell-cycle 

does that sound OK ? I guess it  could be inferred that transcription still occurred in other times?

**Comment by mah11** [comment]
FYPO:0001443 has been specific for vegetative growth for as long as we've made the distinction between vegetative growth and other life cycle stages.

> I guess it could be inferred that transcription still occurred in other times?

Any term for "abolished transcription during X" is neutral with respect to whether transcription occurs at any time/stage/phase other than X, i.e. it doesn't say one way or the other. You cannot infer anything about times other than X.

**Comment by mah11** [comment]
abolished transcription during meiotic cell cycle FYPO:0004986

**Comment by mah11** [comment]
edit file: 6adc5c7b7a97cd970a52f947b6202ff47111b8f7
release: 9615de7a68bece38aa177aaedef1da62debe40c9
