### ISSUE TITLE
query elongated

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2378]
I don't see
elongated septated vegetative cell
under elongated vegetative cell

**Comment by ValWood** [comment]
in fact, these are the only options

![only options](https://cloud.githubusercontent.com/assets/7359272/10693629/5d9d79da-7991-11e5-81c8-45487d57767c.jpg)

**Comment by mah11** [comment]
changed the xp, which should do the trick

**Comment by mah11** [comment]
edit file: e3d1b713aa95d645445e05c97850f44e29b33b5c
release: 9d851f2dcd57ad8363ea4df4506fc965481b8033

reopen if not sorted
