### ISSUE TITLE
 	 abnormal mitochondrial RNA level during vegetative growth 

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2379]
abnormal mitochondrial RNA level during vegetative growth

**Comment by mah11** [comment]
same meaning as FYPO:0004958 altered RNA level in mitochondrion
added a synonym

**Comment by mah11** [comment]
edit file: e3d1b713aa95d645445e05c97850f44e29b33b5c
release: 9d851f2dcd57ad8363ea4df4506fc965481b8033
