### ISSUE TITLE
decreased duration of horsetail nuclear movement 

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2380]
decreased duration of horsetail nuclear movement 
normal duration of horsetail movement 

forgot to request this one to previous ticket where the increased term was requested..

**Comment by mah11** [comment]
decreased duration of horsetail movement FYPO:0004998
  normal duration of horsetail movement FYPO:0004999

**Comment by mah11** [comment]
edit file: e3d1b713aa95d645445e05c97850f44e29b33b5c
release: 9d851f2dcd57ad8363ea4df4506fc965481b8033
