### ISSUE TITLE
ntr: protein mislocalized to nucleus during mitotic interphase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2381]
descendent of protein mislocalized to nucleus during vegetative growth
standard def
PMID:10485849

**Comment by mah11** [comment]
protein mislocalized to nucleus during mitotic interphase FYPO:0005000

**Comment by mah11** [comment]
edit file: e3d1b713aa95d645445e05c97850f44e29b33b5c
release: 9d851f2dcd57ad8363ea4df4506fc965481b8033
