### ISSUE TITLE
ntr: reduced cellular HMW ubiquitin conjugate level

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2382]
reduced cellular HMW ubiquitin conjugate level

mirrors
increased cellular HMW ubiquitin conjugate level

PMID:10082519

**Comment by mah11** [comment]
decreased cellular HMW ubiquitin conjugate level FYPO:0005001

**Comment by mah11** [comment]
edit file: e3d1b713aa95d645445e05c97850f44e29b33b5c
release: 9d851f2dcd57ad8363ea4df4506fc965481b8033
