### ISSUE TITLE
ntr:  oscillating nucleus related

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2383]
inviable elongated mononucleate vegetative cell with oscillating nucleus
(the nucleus oscillates at its normal location)

maybe this should replace:
inviable elongated mononucleate vegetative cell with mislocalized nucleus

note to self:
NES-Alp4C also induced oscillatory movements of normal-sized nuclei in 72% of the cells (n = 65) (Fig. 5C)
(and others)

**Comment by mah11** [comment]
elongated vegetative cell with oscillating nucleus FYPO:0005002

I wouldn't assume or infer that the nucleus in "inviable elongated mononucleate vegetative cell with mislocalized nucleus" is moving. Especially in an inviable cell, the nucleus could be just staying put in the wrong place. So I'm inclined to leave the two terms separate, and not change the existing annotation.

(note to self: older existing term is FYPO:0002337; newer is FYPO:0004950)

**Comment by ValWood** [comment]
yeah makes sense

**Comment by mah11** [comment]
edit file: e3d1b713aa95d645445e05c97850f44e29b33b5c
release: 9d851f2dcd57ad8363ea4df4506fc965481b8033
