### ISSUE TITLE
nrt: abolished APC complex assembly

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2384]
ntr? abolished protein complex assembly
ntr : abolished APC complex assembly
PMID:10526233

actually I'm not sure "abolished' is correct. Its more 'incomplete' assembly.
cut22-347 Cut4 and Nuc2  are not in 20s
nuc2-260  Cut9 is not in 20S
nuc2-260  Cut9 is not in 20S

**Comment by mah11** [comment]
would it help to do a term like 'decreased protein level in proteasome' (FYPO:0002847) for this? see #1187

**Comment by ValWood** [comment]
yes I think so,  but APC/cyclosome instead of proteasome ;)

**Comment by mah11** [comment]
well, yes, that would be why I didn't jstu say to use FYPO:0002847 itself ;)

also fits better with the fact that they looked at proteasome composition rather than trying to watch proteasomes assemble in anything like real time

**Comment by ValWood** [comment]
Ah *like* this term, got you

**Comment by mah11** [comment]
added a grouping term too

  abnormal protein complex composition FYPO:0005003
  decreased protein level in anaphase-promoting complex FYPO:0005004

**Comment by mah11** [comment]
edit file: e3d1b713aa95d645445e05c97850f44e29b33b5c
release: 9d851f2dcd57ad8363ea4df4506fc965481b8033
