### ISSUE TITLE
ntr:  a bit like cut

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2385]
I need to describe a cell which is

septated with  one mononucleate and one anucleate compartment

(it basically the same as cut except the nucleus is not bisected)

I'm sure we have this term but I can't find it under spetated

fig 2 A (dn) PMID:10526233

**Comment by mah11** [comment]
You probably want this one:

FYPO:0001992
name: inviable elongated mononucleate vegetative cell with mislocalized septum
def: "A cell phenotype in which a cell contains a single septum, has one nucleus, is elongated, and is inviable. The septum is in an abnormal location, and the nucleus is located in one compartment of the septated cell."

... it's not connected to cut because if it's only got one nucleus, there's no evidence that the cell attempted chromosome segregation. But if you think the FYPO:0000229 def also covers FYPO:0001992, I can add a link.

FYPO:0000229 septation following abnormal mitotic chromosome segregation (def: "An inviable phenotype observed in the vegetative growth phase of the life cycle in which a cell undergoes septation despite abnormal mitotic chromosome segregation, and gives rise to inviable daughter cells.")
- [i] FYPO:0003165 cut
- [i] FYPO:0003166 septation following abnormal chromosome segregation, with anucleate cell formation
	the FYPO:0003166 def specifies two nuclei, which may or may not be the same size

**Comment by Antonialock** [comment]
if the septum is in the middle then maybe this term is more appropriate?
ID 	FYPO:0002000
Ontology 	fission_yeast_phenotype
Term name 	inviable septated mononucleate vegetative cell

**Comment by ValWood** [comment]
... it's not connected to cut because

yeah thats right. Its caused by the same defect, but when  the septum doesn't crash across the chromosomes so it isn't connected to cut.

**Comment by ValWood** [comment]
I think this is closest
FYPO:0001992
name: inviable elongated mononucleate vegetative cell with mislocalized septum
def: "A cell phenotype in which a cell contains a single septum, has one nucleus, is elongated, and is inviable. The septum is in an abnormal location, and the nucleus is located in one compartment of the septated cell."

BUT
it is also true that this is an 'abolished chromosome segregation' phenotype

**Comment by JackyVH** [comment]
Hi Val

I have sort of followed this thread and if the septum is in the middle of the cell than I think that FYPO:0001992 is probably not right. Often mis segregation of the chromatin has this phenotype i.e. A single nucleus in one cell compartment normal place septum and an a nucleate cell  and is  also often called a cut phenotype. In fact the cut phenotype although used a lot seems to be defined differently by different labs. Sorry if I've got the wrong end of the stick .

Jacky

**Comment by Antonialock** [comment]
I agree with Jacky
both of these terms have some form of relationship to "abnormal chromosome segregation", via
"septation following abnormal mitotic chromosome segregation":

a. septation following abnormal chromosome segregation, with anucleate cell formation
b. inviable mononucleate monoseptate vegetative cell

both of them seem to apply in this case.

**Comment by ValWood** [comment]
This is complicated.

Summary
When cells cut the nucleus is bisected by the septum. This is a chromsome misegregation phenotype. 
Septation occurs in the absence of nuclear division.
When you see this phenotype, you also see co-occuring phenotypes in the population, which are also caused when  septation occurs in the absence of mitosis, but they look a little different because sometimes the chromsomes start to segregate, sometimes the nculeus is not ibsected, but these phenotypes are all a result of a chromsome segregation defect.

In the paper I was curating  they show these:


![10526233](https://cloud.githubusercontent.com/assets/7359272/10760116/d786487a-7cb2-11e5-8176-8e39a1344459.jpg)

The top one is WT.

The other phenotypes occur in the 'cut' mutants
i) there is 'arrest', the metaphase anaphase transition does not occur and you just see condensed chromsosomes. No septum forms (relevant checkpoints still active?)
ii) Chromosome separation did not occur correctly  but septation proceeds , septum bisects nucleus (classic cut)
iii) Chromsome separation did not occur correctly  but septation proceeds , septum does not bisect nucleus ..........but is this because the nucleus is displaced, or the septum is displaced or both? Is it possible to say? Another feature of these cells is that they appear to be slightly elongated? Is the septum in the middle but the nucleus containing end continues to grow (possibly). In this example, the septum does appear to be mislocalized, but it might not be ,islocalized in the original cell. The elongation may have occured *after* spetation????

If this is all true, I suggest:

FYPO:0002000 name: inviable septated  mononucleate vegetative cell
redefine (to make it clear this is a chromosome segregation defect)
def: "An inviable  cell phenotype in which chromosome separation is abolished, but septation has proceeded  resulting in a cell a cell contains a single septum, and the single nucleus  is located in one compartment of the septated cell."

NTR: inviable septated  mononucleate elongated vegetative cell
def: "An inviable  elongated cell phenotype in which chromosome separation is abolished, but septation has proceeded  resulting in a cell a cell contains a septum, and the single nucleus  is located in one compartment of the septated cell.  

NTR: inviable septated  mononucleate elongated vegetative cell with mislocalized septum
def: "An inviable  elongated cell phenotype in which chromosome separation is abolished, but septation has proceeded  resulting in a cell a cell contains a septum, and the single nucleus  is located in one compartment of the septated cell.   Elongation is confined to the anucleate compartment, which means that the septum is no longer localized at the  middle of the cell

These should also have a comment "consider also  'cut' and descendants as these phenotypes usually co-occur"

and "cut" should have a similar comment pointing to FYPO:0002000 

Would that work? It might require a little rejiggling and possibly a review of existing cut phenotype annotations....

**Comment by Antonialock** [comment]
ouch.

I have definitely seen the variation on the last image where the cell has
DNA in only one compartment and the septum is in the "normal" (midpoint)
position. Not sure if those were elongated.

On Tue, Oct 27, 2015 at 10:24 AM, Val Wood <notifications@github.com> wrote:

> This is complicated.
>
> Summary
> When cells cut the nucleus is bisected by the septum. This is a chromsome
> misegregation phenotype.
> Septation occurs in the absence of nuclear division.
> When you see this phenotype, you also see co-occuring phenotypes in the
> population, which are also caused when septation occurs in the absence of
> mitosis, but they look a little different because sometimes the chromsomes
> start to segregate, sometimes the nculeus is not ibsected, but these
> phenotypes are all a result of a chromsome segregation defect.
>
> In the paper I was curating they show these:
>
> [image: 10526233]
> <https://cloud.githubusercontent.com/assets/7359272/10760116/d786487a-7cb2-11e5-8176-8e39a1344459.jpg>
>
> The top one is WT.
>
> The other phenotypes occur in the 'cut' mutants
> i) there is 'arrest', the metaphase anaphase transition does not occur and
> you just see condensed chromsosomes. No septum forms (relevant checkpoints
> still active?)
> ii) Chromosome separation did not occur correctly but septation proceeds ,
> septum bisects nucleus (classic cut)
> iii) Chromsome separation did not occur correctly but septation proceeds ,
> septum does not bisect nucleus ..........but is this because the nucleus is
> displaced, or the septum is displaced or both? Is it possible to say?
> Another feature of these cells is that they appear to be slightly
> elongated? Is the septum in the middle but the nucleus containing end
> continues to grow (possibly). In this example, the septum does appear to be
> mislocalized, but it might not be ,islocalized in the original cell. The
> elongation may have occured *after* spetation????
>
> If this is all true, I suggest:
>
> FYPO:0002000 name: inviable septated mononucleate vegetative cell
> redefine (to make it clear this is a chromosome segregation defect)
> def: "An inviable cell phenotype in which chromosome separation is
> abolished, but septation has proceeded resulting in a cell a cell contains
> a single septum, and the single nucleus is located in one compartment of
> the septated cell."
>
> NTR: inviable septated mononucleate elongated vegetative cell
> def: "An inviable elongated cell phenotype in which chromosome separation
> is abolished, but septation has proceeded resulting in a cell a cell
> contains a septum, and the single nucleus is located in one compartment of
> the septated cell.
>
> NTR: inviable septated mononucleate elongated vegetative cell with
> mislocalized septum
> def: "An inviable elongated cell phenotype in which chromosome separation
> is abolished, but septation has proceeded resulting in a cell a cell
> contains a septum, and the single nucleus is located in one compartment of
> the septated cell. Elongation is confined to the anucleate compartment,
> which means that the septum is no longer localized at the middle of the cell
>
> These should also have a comment "consider also 'cut' and descendants as
> these phenotypes usually co-occur"
>
> and "cut" should have a similar comment pointing to FYPO:0002000
>
> Would that work? It might require a little rejiggling and possibly a
> review of existing cut phenotype annotations....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pombase/fypo/issues/2385#issuecomment-151513380>.
>



-- 
Antonia Lock, PhD
PomBase Biocurator, http://www.pombase.org
Department of Genetics, Evolution and Environment,
The Darwin Building,
University College London
London WC1E 6BT, UK

**Comment by ValWood** [comment]
Just to note, we defined 'cut' the phenotype to mean the described phenotype in the original papers:

"Sometimes the septa physically cut through the nucleus producing the classic Cells Untimely Torn (cut) phenotype"

 I think "cut" the mutant sometimes is used to refer to the 'collection' of phenotypes observed in 'cut' mutant cells.
The idea is that we capture the individual phenotypes occurring in 'cut' cells and their penetrance. The above would be one of the phenotypes also seen in 'cut' mutant, but is not 'cut' phenotype....but they are all related by:
i) chromosome separation abolished
ii) separation in the absence of chromosome segregation

Agree?

**Comment by Antonialock** [comment]
If it is useful to distinguish the "bisected" phenotype from the other
types than I have no problem in continuing to do so.

On Tue, Oct 27, 2015 at 10:38 AM, Val Wood <notifications@github.com> wrote:

> Just to note, we defined 'cut' the phenotype to mean the described
> phenotype in the original papers:
>
> "Sometimes the septa physically cut through the nucleus producing the
> classic Cells Untimely Torn (cut) phenotype"
>
> I think "cut" the mutant sometimes is used to refer to the 'collection' of
> phenotypes observed in 'cut' mutant cells.
> The idea is that we capture the individual phenotypes occurring in 'cut'
> cells and their penetrance. The above would be one of the phenotypes also
> seen in 'cut' mutant, but is not 'cut' phenotype....but they are all
> related by:
> i) chromosome separation abolished
> ii) separation in the absence of chromosome segregation
>
> Agree?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pombase/fypo/issues/2385#issuecomment-151521499>.
>



-- 
Antonia Lock, PhD
PomBase Biocurator, http://www.pombase.org
Department of Genetics, Evolution and Environment,
The Darwin Building,
University College London
London WC1E 6BT, UK

**Comment by ValWood** [comment]
> have definitely seen the variation on the last image where the cell has
DNA in only one compartment and the septum is in the "normal" (midpoint)
position. Not sure if those were elongated.

I am sure that I have annotated these. Oddly when I search on 
FYPO:0001992 - inviable elongated mononucleate vegetative cell with mislocalized septum)
I only find one result and that is tbf1 (not a cut mutant?)

this is actually annotated to a descendant:
inviable swollen elongated mononucleate vegetative cell with mislocalized septum near new end

so it seems that FYPO:0001992  has no annotations??????

**Comment by Antonialock** [comment]
I wouldnt have annotated these to MISLOCALIZED septum.

I would have annotated them to 
inviable mononucleate monoseptate vegetative cell and/or
septation following abnormal chromosome segregation, with anucleate cell formation

Though
 Query: ( FYPO_ID(FYPO:0003166 - septation following abnormal chromosome segregation, with anucleate cell formation) ) AND ( FYPO_ID(FYPO:0002303 - inviable mononucleate monoseptate vegetative cell) )

This query matches 2 genes.

**Comment by ValWood** [comment]
> septation following abnormal chromosome segregation, with anucleate cell formation

that is the term I was looking for.....

But I think these terms FYPO:0003166 and FYPO:0002303  are describing  the same thing?

**Comment by Antonialock** [comment]
hmm, hypothetically speaking I suppose you could also get 
 inviable mononucleate monoseptate vegetative cell
if you have abolished DNA replication? 
(would this also come under abnormal chromosome segregation?)

**Comment by ValWood** [comment]
Yes, these exist.  
Lots of DNA replication mutants give cut phenotypes too....orc1,4,5 ssp1,2,ssb1,3, rfc2
 (especially after HU treatment)

I think it is a type of abolished chromosome segregation (even though chromsomes have not replicated or not fully replicated)?  What you *observe* is a type of abnormal chomosome segregation...(its an indirect effect)

However, my definitons suggestions above need to change from 
"chromosome separation is abolished"
to 
"chromosome segregation is abolished"  (abolished chromosome *separation* would imply that the defect was in the destruction of cohesion which is clearly not true).

**Comment by mah11** [comment]
I'll take care of the straightforward tickets and then come back to this ...

**Comment by mah11** [comment]
I would greatly prefer not to add the "chromosome separation is abolished, but septation has proceeded resulting in ..." passage to these definitions. At present, the existing definitions describe what the cells are/what features they have; they do not include any inferences about how the cells got into the observed state, and I would like to keep things that way. I'm happy to put the interpretation in comments.

I also think the ontology has some is_a links that are slightly suspicious. I'll have a thorough look over the terms for this ticket, and most likely change some is_a links to has_part or output_of.

For example, I think FYPO:0002303 should be output_of FYPO:0003166.

In general, the whole-cell descriptions are of phenotypes that are outputs of processes-gone-awry, and if multiple processes are affected, a multi-process phenotype can have single-process phenotypes as parts.

Another example: I ought to change the links for FYPO:0000229 (is-a parent of cut and its sibling) so that it's a process phenotype encompassing premature septation and abnormal chromosome segregation. It'll become:

id: FYPO:0000229
name: septation following abnormal mitotic chromosome segregation
alt_id: FYPO:0000322
alt_id: FYPO:0000323
def: "A cellular process phenotype observed in the vegetative growth phase of the life cycle in which a cell undergoes septation despite abnormal mitotic chromosome segregation, and gives rise to inviable daughter cells." [PomBase:jh, PomBase:mah, PomBase:vw]
synonym: "septation following abnormal chromosome segregation during mitotic cell cycle" RELATED [PomBase:mah]
synonym: "septation following abnormal mitotic chromosome segregation during vegetative growth" EXACT [PomBase:mah]
is_a: FYPO:0001320 ! vegetative cell phenotype
relationship: has_part FYPO:0000141 ! abnormal mitotic sister chromatid segregation
relationship: has_part FYPO:0003250 ! premature septation

There may already be a suitable cell phenotype term to be output_of FYPO:0000229, or I can add one.

**Comment by mah11** [comment]
Looking at this more closely now, I think FYPO:0000229 et al. should not refer only to abolished chromosome segregation, because the terms should cover cases where segregation starts but goes awry or doesn't finish, as well as where it's really abolished (even when there's a single nucleus, parts of segregation such as condensation may have begun).

**Comment by mah11** [comment]
For reasons noted in my earlier comments, I can't do everything precisely as requested, but I've made a bunch of changes to has_part and output_of links, and added comments to several terms.

First new term is:
  inviable elongated septated mononucleate vegetative cell FYPO:0005023

The name of the second "new" term has no differences from FYPO:0001992, so I added another synonym. Let me know if you need a new term to distinguish the part of the text description where "only the anucleate compartment is elongated".

Apart from the NTR follow-up, let's see how we get on, and open new tickets for additional changes.

edit file: ba9e68937d6ce6e6ade52d2d234d93678e1e5989

**Comment by mah11** [comment]
release: 181b3899dabcbb4162464ba5e7afb857bd6e6776
