### ISSUE TITLE
ntr: decreased histone H4 acetylation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2389]
decreased histone H4 acetylation

decreased histone H4 K5  acetylation

decreased histone H4 K8 acetylation

decreased histone H4 K12 acetylation

standard def
A cellular process phenotype observed in the vegetative growth phase of the life cycle in which histone H4 *** acetylation occurs to a lower extent than normal.

PMID:15483052

**Comment by mah11** [comment]
decreased histone H4 acetylation FYPO:0005011
  decreased histone H4-K5 acetylation FYPO:0005012
  decreased histone H4-K8 acetylation FYPO:0005013
  decreased histone H4-K12 acetylation FYPO:0005014

**Comment by mah11** [comment]
edit file: e3d1b713aa95d645445e05c97850f44e29b33b5c
release: 9d851f2dcd57ad8363ea4df4506fc965481b8033
