### ISSUE TITLE
ntrs: cytokinesis for blt 

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2392]
ntr delayed completion of septation (start of septation is normal)
ntr delayed onset of actomyosin contractile ring contraction (completion is normal)

**Comment by ValWood** [comment]
24790095

**Comment by mah11** [comment]
new terms
  normal duration of septation FYPO:0005019
  normal duration of actomyosin contractile ring contraction FYPO:0005020
  decreased duration of protein localization to actomyosin contractile ring FYPO:0005021
  decreased rate of protein localization to actomyosin contractile ring FYPO:0005022

also changed 'delayed' to 'delayed onset of' for anything other than cell cycle phase transitions

**Comment by mah11** [comment]
edit file: acdd709282a32f1e5c2823337dc363dd65d027ab
release: 09bac71f58f503951fcc0055f717fcaad4ab2f2c
