### ISSUE TITLE
ntr: abnormal mitotic sister chromatid arm separation 

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2393]
ntr: abnormal mitotic sister chromatid arm separation 
child of
abnormal mitotic sister chromatid separation

def
A cellular process phenotype in which mitotic sister chromatid arm separation is abnormal.

**Comment by ValWood** [comment]
The condensin mutant cut3-477,..... shows a defect mainly in anaphase separation of the chromosome arms33 (Supplementary Fig. 5). Indeed, the growth defect in cut3-477 cells is not suppressed by centromere tethering of condensin (Fig. 1d), indicating that condensin at the kinetochore is not rate-limiting for the viability of cut3-477 cells. 

21633354

**Comment by mah11** [comment]
also see https://github.com/geneontology/go-ontology/issues/12135

**Comment by mah11** [comment]
abnormal mitotic sister chromatid arm separation FYPO:0005024

**Comment by mah11** [comment]
edit file: fd602879fa65355870ae8d5088ae34201572015f
release: 181b3899dabcbb4162464ba5e7afb857bd6e6776
