### ISSUE TITLE
ntr: abolished mitotic chromosome condensation at the kinetochore

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2394]
def
A cellular process phenotype observed in the vegetative growth phase of the life cycle in which mitotic chromosome condensation at the kinetochore is abolished.

descendent of 
abnormal mitotic chromosome condensation

PMID:21633354
Taken together, these results indicate that the pools of condensin at kinetochores and along the chromosome arms, which are recruited respectively by the Pcs1–Mde4 complex and TFIIIC, are functionally separable (Fig. 1e).

**Comment by mah11** [comment]
also see https://github.com/geneontology/go-ontology/issues/12135

**Comment by mah11** [comment]
It's the chromosome (DNA, histones, etc) rather than the kinetochore that condenses, so I think it would be better to use "centromere" in the term name, and "kinetochore" is a synonym.

**Comment by mah11** [comment]
abolished mitotic chromosome condensation at centromere FYPO:0005025
(with "kinetochore" synonym)

**Comment by mah11** [comment]
adjusted name to match GO:1990893

**Comment by mah11** [comment]
edit file: fd602879fa65355870ae8d5088ae34201572015f
release: 181b3899dabcbb4162464ba5e7afb857bd6e6776
