### ISSUE TITLE
relation checkdecreased protein localization to heterochromatin during vegetative growth

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2395]
decreased protein localization to heterochromatin during vegetative growth

**Comment by ValWood** [comment]
in canto currently
decreased protein localization to heterochromatin during vegetative growth
has the child
decreased protein localization to heterochromatin during vegetative growth

**Comment by ValWood** [comment]
FYPO:0002385 decreased protein localization to heterochromatin during vegetative growth
	FYPO:0002909 decreased protein localization to heterochromatin during vegetative growth

**Comment by ValWood** [comment]
ignore

**Comment by mah11** [comment]
FYPO:0002909 is plain chromatin, not heterochromatin
