### ISSUE TITLE
ntr: increased protein localization to chromosome arm chromatin

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2396]
ntr: increased protein localization to chromosome arm chromatin

descendant of
increased protein localization to chromatin

PMID:21633354, yay finished it!

**Comment by mah11** [comment]
increased protein localization to chromatin at chromosome arms FYPO:0005026

**Comment by mah11** [comment]
edit file: fd602879fa65355870ae8d5088ae34201572015f
release: 181b3899dabcbb4162464ba5e7afb857bd6e6776
