### ISSUE TITLE
Question about metaphase or metaphase/anaphase arrest

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2397]
I might have asked about this before.
I noticed that there is no parent child relationship between these 2 terms

I expected
abnormal cell cycle arrest in mitotic metaphase
--abnormal cell cycle arrest at mitotic metaphase/anaphase transition

because when you arrest at the metaphase/anaphase transition, you are still in metaphase
(the same would apply to other transitions too)

abnormal cell cycle arrest in mitotic metaphase
Definition
A cellular process phenotype in which progression through the mitotic cell cycle is arrested in metaphase under conditions where arrest does not normally occur.
Comment
Metaphase is defined as the part of mitosis when chromosomes are aligned in the middle of the spindle. If no spindle is present, do not use this term, but consider 'abnormal cell cycle arrest in mitotic prophase' (FYPO:0003145). If you cannot tell whether a spindle is present, or if metaphase cannot be clearly detected, annotate to the more general term 'abnormal cell cycle arrest in mitotic M phase' (FYPO:0000608).

abnormal cell cycle arrest at mitotic metaphase/anaphase transition
Definition
A cellular process phenotype in which progression through the mitotic cell cycle is arrested at the metaphase/anaphase transition under conditions where arrest does not normally occur.

**Comment by mah11** [comment]
I don't think this exact question has come up before. I don't mind moving the metaphase/anaphase transition term and similar.

**Comment by mah11** [comment]
... and done. that was easy :)

**Comment by mah11** [comment]
edit file: fd602879fa65355870ae8d5088ae34201572015f
release: 181b3899dabcbb4162464ba5e7afb857bd6e6776
