### ISSUE TITLE
descendants swollen vegetative cell

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2399]
has  no descendants

I expected,
viable swollen vegetative cell 
inviable swollen vegetative cell 
swollen spherical vegetative cell 
(I thought has_parts were displayed as descendants now?)

**Comment by mah11** [comment]
Amended xp defs to use has_part 'swollen vegetative cell' instead of 'swollen cell'. That should sort it.

**Comment by mah11** [comment]
edit file: fd602879fa65355870ae8d5088ae34201572015f
release: 181b3899dabcbb4162464ba5e7afb857bd6e6776
