### ISSUE TITLE
MP inviable after spore germination, without cell division, swollen cell with central constriction

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2400]
inviable after spore germination, without cell division, swollen cell with central constriction
should be a descendant of
inviable swollen vegetative cell with abnormal cell shape

**Comment by ValWood** [comment]
This phenotype is also multiseptate. I'm not sure that this can always be observed, so we need an identical child term with "multiseptate" (and additional parents?)

**Comment by ValWood** [comment]
both of these terms are also binucleate so:
inviable after spore germination, without cell division, swollen cell with central constriction
becomes
inviable after spore germination, binucleate without cell division, swollen cell with central constriction

and ntr:
inviable after spore germination, binucleate without cell division, swollen with multiple septa

**Comment by mah11** [comment]
Changes done. New term is:
  inviable after spore germination, without cell division, swollen binucleate multiseptate cell with central constriction FYPO:0005027

**Comment by mah11** [comment]
edit file: fd602879fa65355870ae8d5088ae34201572015f
release: 181b3899dabcbb4162464ba5e7afb857bd6e6776
