### ISSUE TITLE
distinguish multi/binucleate

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2401]
inviable after spore germination, without cell division, swollen cell with central constriction

this is describing the "dumbbell germinated spore"

I think it is usually binucleate.
There is a descendant "multinucleate" which I could use, but it seems misleading....
Did we figure out how to distinguish bi/multi yet?

flagging this paper to go back and fix when we do
PMID:8334988

**Comment by mah11** [comment]
> Did we figure out how to distinguish bi/multi yet?

No - see #1764

**Comment by ValWood** [comment]
Oddly I did see some terms with"binucleate" in the term name...maybe they are a hack?

**Comment by mah11** [comment]
Existing "binucleate" terms were requested over the years, and all are defined as the cell having (exactly) two nuclei. I don't see anything "hack"ish about them.

In PATO (and in real life) "multinucleate" means having two or more nuclei, so "binucleate" is_a "multinucleate". There isn't a term for "three or more nuclei". FYPO follows PATO's structure, i.e. binucleate cell is_a multinucleate cell and so on.

**Comment by ValWood** [comment]
Ah Ok so I can request a binucleate term describing the terminal phenotype of an arrested cell
