### ISSUE TITLE
ntr: mitotic cell cycle arrest in M-phase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2403]
ntr: mitotic cell cycle arrest in M-phase
A cell cycle phenotype that affects or involves the  occurrence of mitotic cell cycle arrest in M-phase. 

( I thought I already requested and used this term?)
(arrest with a spindle)

**Comment by mah11** [comment]
added another synonym to FYPO:0000608 ! abnormal cell cycle arrest in mitotic M phase

**Comment by mah11** [comment]
edit file: fd602879fa65355870ae8d5088ae34201572015f
release: 181b3899dabcbb4162464ba5e7afb857bd6e6776
