### ISSUE TITLE
ntr: reduced gamma-tubulin complex localization to mitotic spindle pole body

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2404]
reduced gamma-tubulin complex localization to mitotic spindle pole body

descendant of
abnormal gamma-tubulin complex localization to mitotic spindle pole body

PMID:16611237

**Comment by mah11** [comment]
decreased gamma-tubulin complex localization to mitotic spindle pole body FYPO:0005029

**Comment by mah11** [comment]
edit file: fd602879fa65355870ae8d5088ae34201572015f
release: 181b3899dabcbb4162464ba5e7afb857bd6e6776
