### ISSUE TITLE
ntr? elongated vegetative population with variable length

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2405]
Is it possible to capture this somehow with a term?
I think it might be useful because it seems to indicate the loss of mitotic entry is via a checkpoint mechanism as this is stochastic. I can't think how to describe it but that might be because I have only just finished this paper, taken most of the day. Head hurts.

in PMID:25533348
curs/7e83e3410ced8531/ro/

**Comment by mah11** [comment]
Urgh. We got rid of all the "mixed population" terms and all the population terms referring to cell morphology (or anything else besides than growth or viability), and that made me happy.

I don't see an easy way to get the "variable" bit with a cell phenotype, and this case doesn't quite fit the obsoletion reason of redundancy with (cell phenotype + penetrance), but I'm nevertheless VERY leery of reopening the "population morphology" worm can. I suspect it would be difficult to explain to community curators why this term would be allowed when other population + morphology terms aren't, so we'd probably get a slew of requests for things we wouldn't add.

**Comment by ValWood** [comment]
OK will keep as a comment. I suspect that there  will be other ways to pull these out eventually. I don't want to open any worm cans.  I only wanted it because I'm  interested in the different types of elongated....

**Comment by mah11** [comment]
I am sympathetic! I'm just also scared of what worms might come out of the can ...

We probably ought to look into making the comments more visible to users ...

**Comment by Antonialock** [comment]
can we do something like 
elongated vegetative population has_expressivity(variable)

**Comment by mah11** [comment]
ooh, nice one ... I could add a term for "variable expressivity" to FYPO_EXT. Might be worth checking whether Kim could have it show up only for expressivity, not for penetrance ...

**Comment by mah11** [comment]
I think we would still just use the cell term, not a population term - my goal is to keep the morphology stuff and the population branch separate.

**Comment by ValWood** [comment]
has_expressivity(variable) Yes!. I agree annotating on the cell term. I wanted to annotate the cell term really ....

Comments, would be great to make them visible (I would need to tidy mine up first!), I will try to make them better  from now on in case we ever do....

**Comment by mah11** [comment]
OK, I've added 'variable expressivity' FYPO_EXT:0000005 to the mini-ontology.

**Comment by mah11** [comment]
hey, I think that sorts this :D
