### ISSUE TITLE
FYPO:0004069 is this right?

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2408]
ID 	FYPO:0004069
Ontology 	fission_yeast_phenotype
Term name 	abolished phosphorylation of RNA polymerase II C-terminal domain serine 2 residues
Definition 	A cellular process phenotype observed in the vegetative growth phase of the life cycle in which the phosphorylation of the serine residue at position 2 within one or more copies of the heptapeptide repeat (YSPTSPS) of the C-terminal domain of RNA polymerase II does not occur.
Matching synonym 	decreased phosphorylation of RNA polymerase II CTD serine 2 residues
Comment 	We recommend noting which protein(s) were used in the assay when annotating to this term.
Synonyms 	
abolished phosphorylation of RNA polymerase II C-terminal domain serine 2 residues during vegetative growth
decreased phosphorylation of RNA polymerase II CTD serine 2 residues
phosphorylation of RNA polymerase II C-terminal domain serine 2 residues abolished

**Comment by mah11** [comment]
oops, no, synonym should've been edited

fixed behind the scenes but hasn't made today's release, so will be in Canto later

**Comment by mah11** [comment]
edit file: ec573cf46f49a1761abd3178e305d5f2da962eed

**Comment by mah11** [comment]
finally got the fix into a release: d1930c4357aa284188282fdcee8cef321d6e20cd
