### ISSUE TITLE
poss missing relation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2409]

**Comment by ValWood** [comment]
"decreased mitotic chromosome condensation"

is not a descendent of

"abnormal mitotic chromosome condensation"

see https://github.com/pombase/canto/issues/1024

**Comment by mah11** [comment]
Grump. Thought that ought to get inferred. Asserted.

**Comment by mah11** [comment]
edit file: 888e99dfac6ba9ba8fe0ac57b350b82f88ba85dd
release: d1930c4357aa284188282fdcee8cef321d6e20cd
