### ISSUE TITLE
MP normal protein localization to kinetochore during meiosis I

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2411]
normal protein localization to kinetochore
has no children 
but in the Canto pull down I can see
normal protein localization to kinetochore during meiosis I

(I smell a problem which is not missing parents)

**Comment by mah11** [comment]
The actual problem here is that the term currently named "normal protein localization to kinetochore" is defined (by xp and text) as specific to vegetative growth. I'll rename it and add a generic one.

**Comment by mah11** [comment]
done - new generic term is
normal protein localization to kinetochore FYPO:0005042

**Comment by mah11** [comment]
edit file: 888e99dfac6ba9ba8fe0ac57b350b82f88ba85dd
release: d1930c4357aa284188282fdcee8cef321d6e20cd
