### ISSUE TITLE
possible missing relationship between terms/ multinucleate binucleate vegetative cell

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2412]
I think these terms should  have a parent/child realtionship between them

binucleate multiseptate vegetative cell (6 annotations)
--elongated multinucleate multiseptate vegetative cell, septa between nuclei (17 annotations)

 FYPO:0001223 binucleate multiseptate vegetative cell
"... a cell has two nuclei and more than one septum. The septa are grouped together between the two nuclei."

FYPO:0001253 -  elongated multinucleate multiseptate vegetative cell, septa between nuclei
"... in which a cell is longer than normal, has two or more nuclei and more than one septum, and the septa are located so as to form separate compartments with a single nucleus in each."

Actually we need a descendant of both
elongated multinucleate binucleate vegetative cell, septa between nuclei
and a sibling
elongated vegetative cell, more than 2 nuclei with septa between nuclei (implies multiseptate)

then could block 
FYPO:0001253 -  elongated multinucleate multiseptate vegetative cell, septa between nuclei
for direct annotation and move down the annotations to one of the new terms.

At present  genes with the same phenotype are annotated to 2 different terms (FYPO:0001223 or FYPO:0001253)  because if you are drilling down   you can get stuck in separate branches.

**Comment by mah11** [comment]
> I think these terms should have a parent/child realtionship between them
> 
> binucleate multiseptate vegetative cell (6 annotations)
> --elongated multinucleate multiseptate vegetative cell, septa between nuclei (17 annotations)

No. Remember, it's binucleate is_a multinucleate ("exactly 2" is a subset of "2 or more").

> FYPO:0001223 binucleate multiseptate vegetative cell
> "... a cell has two nuclei and more than one septum. The septa are grouped together between the two nuclei."

I'll remove the "septa are grouped" bit from the FYPO:0001223 text definition, because that term has a logical def that doesn't mention it. It's misleading to have more details in the text than in the logical def (and I don't remember why I did that in the first place). I can then move FYPO:0001223 to be is_a FYPO:0001252 'multinucleate multiseptate vegetative cell'; that'll also make it a sibling of FYPO:0001253 and FYPO:0001254.

> Actually we need a descendant of both
> elongated multinucleate binucleate vegetative cell, septa between nuclei

Putting "multinucleate binucleate" into any term name makes no sense.

Even if you do clarify any desirable new terms, FYPO:0001253 is specific enough already that I don't think we'd gain enough by blocking it to make up for the effort of changing the existing annotations.

**Comment by ValWood** [comment]
I'll explain later. I need to draw a picture. There are 2 (main) distinct phenotypes and they are annotated to different terms (because both therms fit). I didn't explain properly.

I'll probably do it for Friday...

**Comment by mah11** [comment]
OK. The FYPO:0001223 changes need doing anyway. For the rest a picture should help.

**Comment by mah11** [comment]
amended FYPO:0001223 text def (reasoner infers FYPO:0001252 parent)

**Comment by mah11** [comment]
FYPO:0001223 def change in
edit file: 888e99dfac6ba9ba8fe0ac57b350b82f88ba85dd
release: d1930c4357aa284188282fdcee8cef321d6e20cd

**Comment by mah11** [comment]
curator meeting - figured out what to do:

- add binucleate multiseptate veg, septa grouped term
- amend text in "septa between nuclei" term to clarify that septa are not bunched together
- also add child for "three or more nuclei" & single septa between nuclei

**Comment by mah11** [comment]
new terms:
  binucleate multiseptate cell, septa grouped FYPO:0005055
  elongated multiseptate vegetative cell, with three or more nuclei and single septa between nuclei FYPO:0005056

**Comment by mah11** [comment]
edit file: 5b76daaf62c2cd3d78fd2084803054d652f26634
release: 4f80132ec75d13c867405dee757878e442773a77
