### ISSUE TITLE
recomb synonyms?

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2423]
Shouldn't
decreased mitotic recombination 
=
decreased DNA recombination during vegetative growth

They are currently child/parent....but gene conversion and DNA repair via homologous recombination cab both be types of mitotic recombination right? (maybe I'm missing something)

**Comment by mah11** [comment]
No - in GO gene conversion and recombinational repair are directly is_a DNA recombination, not under mitotic recombination.

**Comment by Antonialock** [comment]
ok, I still don't understand what the difference is. 

Is there one?

**Comment by mah11** [comment]
Well, I'm certainly no expert myself! I think the differences may be bigger in other species, especially multicellular euks, than in pombe. GO has a term for meiotic gene conversion, and I have no idea whether it would be applicable to fission yeasts (GO's also got some other types of gene conversion that I know don't apply to pombe).

**Comment by Antonialock** [comment]
Hmm I think they can as DNA repair via homologous recombination is active during meiosis. I think holliday junction formation is the main pathway  for repair but SDSA (which can/does result in gene conversions?) is also active.

This is an area where I feel I have a basic overall understanding but the details are a bit wooly.

**Comment by mah11** [comment]
In light of our non-expertise and uncertainty, I'll leave the terms separate for now. That feels like the way to play it safe.
