### ISSUE TITLE
silencing associated

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2425]
increased histone H3-K4 methylation  at telomere
increased histone H3-K4 methylation  at mating type locus

increased histone H3-K9 methylation at telomere
increased histone H3-K9 methylation at mating type locus
increased histone H3-K9 methylation at centromere

PMID:12417737

**Comment by mah11** [comment]
increased histone H3-K4 methylation at telomere FYPO:0005062
  increased histone H3-K4 methylation at mating type locus FYPO:0005063
  increased histone H3-K9 methylation at telomere FYPO:0005064
  increased histone H3-K9 methylation at mating type locus FYPO:0005065
  increased histone H3-K9 methylation at centromere FYPO:0005066

**Comment by mah11** [comment]
edit file: 5b76daaf62c2cd3d78fd2084803054d652f26634
release: 4f80132ec75d13c867405dee757878e442773a77
