### ISSUE TITLE
check for has_part vegetative x

### ISSUE THREAD

**Issue by mah11** [pombase/fypo#2426]
... because the reasoner isn't inferring vegetative yada ancestry in places where I thought it would

general case of specific issue noted in #2399

another current example FYPO:0000281/FYPO:0002790/FYPO:0000952

**Comment by ValWood** [comment]
Ah OK, I thought I heard you muttering about fixing it already... maybe not

**Comment by mah11** [comment]
edit file: 5b76daaf62c2cd3d78fd2084803054d652f26634
release: 4f80132ec75d13c867405dee757878e442773a77
