### ISSUE TITLE
FYPO:NEW - septation following abolished chromosome separation, with mononuclear and anucleate compartments

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2429]
FYPO:NEW - septation following abolished chromosome separation, with mononuclear and anucleate compartments

An inviable phenotype observed in the vegetative growth phase of the life cycle in which a cell undergoes septation despite abolished chromosome separation, producing inviable daughter cells, and in which the septum forms a mononucleate and an anucleate compartment.”

**Comment by ValWood** [comment]
![anucleate](https://cloud.githubusercontent.com/assets/7359272/11241123/e5326a28-8def-11e5-9bbc-afb0532ddfd8.jpg)

**Comment by ValWood** [comment]
PMID:11279037

Note to self: I have for sure seen before many times so I need to check which term I  have been using....

**Comment by mah11** [comment]
new term
  septation following abolished mitotic sister chromatid separation, with mononucleate and anucleate cell formation FYPO:0005070

My best guess for what you may have used is FYPO:0002000 'inviable septated mononucleate vegetative cell'. I've updated its output_of link to use the new term.

**Comment by mah11** [comment]
edit file: 5b76daaf62c2cd3d78fd2084803054d652f26634
release: 4f80132ec75d13c867405dee757878e442773a77

**Comment by ValWood** [comment]
not sure if this is quite right:
septation following abolished mitotic sister chromatid separation, with mononucleate and anucleate cell formation FYPO:0005070

This doesn't go on to form 2 cells (i.e  the cells don't separate. Or doesn't that matter? I'm not sure if the 2 compartments would be called cells?

**Comment by mah11** [comment]
I don't think we (plus Jacky) ever resolved at what point compartments grow up to be "cells" in their own right ... we know it's after the septum forms, and we know that you've got two cells by the time cell separation is complete, but there's still a grey area with accompanying outstanding questions.

That said, I don't mind changing "cell" to "compartment" in FYPO:0005070 if that will still work for the annotations. I would very much like to do similar terms all consistently, though, so please also look at FYPO:0003166 (the precedent for all of 'em so far) and any other terms with "with binucleate and anucleate cell formation" in the names.

Finally, ticket-management point of order: please reopen tickets if you have follow-up queries.

**Comment by ValWood** [comment]
I spot checked a few and I'm happy that these all refer to 
https://github.com/pombase/curation/issues/787
A single undivided cell with a binucleate and an anucleate compartment. 
With the exception of 
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3730917/ (where I could not see this phenotype)

I think they should both be renamed as the authors usually refer to them like this. Whenver I have used this term, I meant this phenotype.
FYPO:0003166

![fypo-0003166](https://cloud.githubusercontent.com/assets/7359272/12397632/572032c8-be06-11e5-8e20-93899a8bf5c9.jpg)

**Comment by ValWood** [comment]
is the only difference between
septation following abolished mitotic sister chromatid separation, with mononucleate and anucleate cell formation FYPO:0005070
and
FYPO:0002000 'inviable septated mononucleate vegetative cell'.

that FYPO:0002000  is inviable?

(I  always thought that FYPO:0005070 was an inviable phenotype, but they can go on to form viable diploids)

**Comment by ValWood** [comment]
actually in this one:
septation following abolished mitotic sister chromatid separation, with mononucleate and anucleate cell formation FYPO:0005070
they really do look like separate cells so its probably OK to leave like this....

![ptr4](https://cloud.githubusercontent.com/assets/7359272/12398065/21a1c97e-be09-11e5-9901-ae29ce2046dc.jpg)

**Comment by mah11** [comment]
I could use "compartment" in the names, and add text saying that cell separation may or may not complete. Would that help?

**Comment by ValWood** [comment]
Good plan!

**Comment by mah11** [comment]
OK, done. I think that's everything for this ...?

edit file: 829a2180f4d321cf18dd800a8abfb1cb3c5f7816
release: 0d5f483950d46e038d7b813772942ddf053b62db
