### ISSUE TITLE
ntr: normal protein localization to  centromeric chromatin

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2431]
normal protein localization to  centromeric chromatin

**Comment by ValWood** [comment]
PMID:21633354

**Comment by mah11** [comment]
normal protein localization to centromeric chromatin FYPO:0005072

**Comment by mah11** [comment]
edit file: 5b76daaf62c2cd3d78fd2084803054d652f26634
release: 4f80132ec75d13c867405dee757878e442773a77
