### ISSUE TITLE
ntr:decreased mitotic chromosome condensation along chromosome arms

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2432]
decreased mitotic chromosome condensation along chromosome arms
descendent of
decreased mitotic chromosome condensation

**Comment by mah11** [comment]
decreased mitotic chromosome arm condensation FYPO:0005073

**Comment by mah11** [comment]
edit file: 5b76daaf62c2cd3d78fd2084803054d652f26634
release: 4f80132ec75d13c867405dee757878e442773a77
