### ISSUE TITLE
ntr: normal protein level in APC

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2433]
PMID:9264466

A cell phenotype in which the amount of a protein measured in the anaphase-promoting complex is  normal when the cell is in the vegetative growth phase of the life cycle.

**Comment by mah11** [comment]
normal protein level in anaphase-promoting complex FYPO:0005074

**Comment by mah11** [comment]
edit file: 5b76daaf62c2cd3d78fd2084803054d652f26634
release: 4f80132ec75d13c867405dee757878e442773a77

**Comment by ValWood** [comment]
For this one, variants of the APC exist during meiosis too. Maybe just remove vegetative growth from def and move it up so its phase agnostic?
