### ISSUE TITLE
child terms not visible (elongated vegetative)

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2434]
Sorry..... I know this is driving you crazy.

I don't see
elongated mononucleate vegetative cell
as a descendant of 
elongated vegetative cell (or all of the elongated septated vegetative cell etc)
I only see these:

**Comment by ValWood** [comment]
![only see these](https://cloud.githubusercontent.com/assets/7359272/11246907/a669dd36-8e11-11e5-99e7-033b7f4cba15.jpg)

**Comment by mah11** [comment]
see #2426
