### ISSUE TITLE
mitotic G2 arrest phenotype

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2435]
I think 
FYPO:0004922	
inviable elongated mononucleate aseptate vegetative cell with cell cycle arrest in mitotic G2 phase

should be a descendant of
FYPO:0003373	
abnormal cell cycle arrest in mitotic G2 phase

**Comment by mah11** [comment]
This link exists:

id: FYPO:0004922
name: inviable elongated mononucleate aseptate vegetative cell with cell cycle arrest in mitotic G2 phase
relationship: has_part FYPO:0003373 ! abnormal cell cycle arrest in mitotic G2 phase

**Comment by ValWood** [comment]
but we don't follow has_par in canto right? so if you are at  FYPO:0003373/FYPO:0004922 you don't see the other term

Do we follow has output? becase it seems that if reworded, it could also be:

It seems that it could be also be 
abnormal cell cycle arrest in mitotic G2 phase
--abnormal cell cycle arrest in mitotic G2 phase resulting in elongated mononucleate cell (has output?)
(the vegetative, inviable are a given)


we need some way for curators to see FYPO:0004922 when using FYPO:0003373

**Comment by mah11** [comment]
I don't understand what you mean with the has_output thing, but it seems to me that a better solution would be to have Canto use has_part again. We had Kim disable it because the "normal phenotype" suggestions were confusing, but I've removed has_part links in the "normal" branch so that wouldn't be a problem any more.

**Comment by ValWood** [comment]
Ah right. Definitely.
I did not know we could reestablish the has_part ...
I'll open a Canto ticket.

**Comment by mah11** [comment]
Kim has traced the problem in Canto (https://github.com/pombase/canto/issues/1031).
