### ISSUE TITLE
abnormal mitotic cell cycle phase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2438]
I'm not sure that we should be using this term for direct annotation. You should know at minimum which phase is abnormal and/or what is abnormal about it? 

I think most are from the Graml paper? Maybe there is a reason they can't be more specific but I can't think why... (I"m suspecting that its likely these are  'elongated cells' ?)

**Comment by mah11** [comment]
is already in subset: qc_do_not_manually_annotate
