### ISSUE TITLE
PMID:24322298 poly (A) polymerase  related

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2451]
PMID:24322298
normal poly(U) polymerase/PUP activity 
reduced poly(A) polymerase/PAP activity
decreased poly(U) RNA binding

**Comment by mah11** [comment]
abnormal poly(A) polymerase activity FYPO:0005098
  decreased poly(A) polymerase activity FYPO:0005099
  normal poly(U) polymerase activity FYPO:0005100
  decreased poly(U) RNA binding FYPO:0005101

**Comment by mah11** [comment]
edit file: 0ced6bfa9217652be586f19ff66c40f7058eacc9
release: 494d8d1501aa70b5aa96f73b38d012267f3e8bf5
