### ISSUE TITLE
FYPO:0003090 link problem

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2452]
ID 	FYPO:0001722
Ontology 	fission_yeast_phenotype
Term name 	decreased sodium export 

 If possible, please refine your term selection. Clicking on a child term from the list below selects it and shows its definition:

    decreased replication fork arrest at rDNA repeats

**Comment by mah11** [comment]
Note to self: To fix, correct FYPO:0003090 xp

(Note to Antonia: I hope it's convenient for you to report link problems this way, because it's not convenient for me to see quickly what 's actually wrong.)

**Comment by Antonialock** [comment]
do you want them reported some other way specifically?

**Comment by mah11** [comment]
Some things would help ...

- usually it'll turn out to be a problem with the "child"/suggested term, so list that first (ID is most helpful but if it's not there on the screen don't waste time looking it up; the name will do)
- leave out the Canto instructions ("if possible, please refine...") and the "Ontology fission_yeast_phenotype" line cos they just get in the way

Something like "decreased replication fork arrest at rDNA repeats is in the suggestion list for decreased sodium export" would home in on the problem nicely.

**Comment by Antonialock** [comment]
ok sure

**Comment by mah11** [comment]
thanks! :)

**Comment by mah11** [comment]
fixed! (whew)

**Comment by mah11** [comment]
edit file: 0ced6bfa9217652be586f19ff66c40f7058eacc9
release: 494d8d1501aa70b5aa96f73b38d012267f3e8bf5
