### ISSUE TITLE
TPV! decreased replication fork arrest at rDNA repeats

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2454]
Is a descendant of abnormal sodium export

**Comment by mah11** [comment]
Antonia beat you to it ;)
#2452

**Comment by mah11** [comment]
Antonia beat you to it ;)
#2452

**Comment by Antonialock** [comment]
hahaha, I completly forgot #2452 (from yesterday!) this morning using the query builder :o a bit worrying really....

**Comment by mah11** [comment]
I won't tell you how stupid the editing mistake was that caused it ...

**Comment by Antonialock** [comment]
ah, that makes me feel better :*

**Comment by ValWood** [comment]
.....and  all of this makes me feel better ;) its usually me saying doh, and oh I forgot that.....
