### ISSUE TITLE
decreased protein level at mating type region heterochromatin

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2456]
descendant of
decreased protein level during vegetative growth

**Comment by ValWood** [comment]
decreased protein level at centromere outer repeat

add synonym?
decreased protein level at centromere outer repeat heterochromatin

**Comment by ValWood** [comment]
PMID:19117951

**Comment by mah11** [comment]
edit file: 02e53975e4138596f952e50fe8675346a0276112
release: bd7cb989ef38a30349babc1206d0fdb124313237
