### ISSUE TITLE
ectopic protein binding

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2464]
I will capture this if I can, it isn't critical:

Leucine 482 of B56Par2 occupies a position occupied by only valine or isoleucine in validated PP1 docking sites12. Changing this leucine to valine now allowed PP1Dis2 to bind B56Par2 (Extended Data Figure 2e).

i.e mutating par2 creates a binding site for a protein which is not normally bund. Increased protein binding seems odd. Perhaps ectopic protein binding?

**Comment by mah11** [comment]
Although "increased" technically isn't wrong -- going from zero to more than zero is an increase -- I could add something like "altered protein binding specificity" for this.

"Ectopic" is definitely wrong, because it means "existing or happening in the wrong place".

**Comment by ValWood** [comment]
yeah ectopic was crazy.

altered protein binding specificity sound good

**Comment by mah11** [comment]
altered protein binding specificity FYPO:0005119

also included a comment suggesting sibling(s)

**Comment by mah11** [comment]
edit file: 09c94cb804bc5cac89400e1cb789c445c78c855c
release: ee9e5553f11629ab4d6e12c7b384126cd7b78d5d
