### ISSUE TITLE
ntr proteasome binding related

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2473]
reduced
GO:0005838 proteasome regulatory particle
binding

abolished
GO:0005838 proteasome regulatory particle
binding

reduced 
GO:0005839	proteasome core complex
binding

abolised
 GO:0005839	proteasome core complex
binding

PMID:16096059

**Comment by mah11** [comment]
The GO IDs here are CC ... are there GO MF terms for the binding activities?

**Comment by ValWood** [comment]
yep, I was just putting them for the GO  x-products

**Comment by mah11** [comment]
The GO xps require MF terms.

**Comment by ValWood** [comment]
Ah OK, I thought you could do them with component+binding too

**Comment by mah11** [comment]
decreased proteasome core complex binding FYPO:0005142
  abolished proteasome core complex binding FYPO:0005143
  decreased proteasome regulatory particle binding FYPO:0005144
  abolished proteasome regulatory particle binding FYPO:0005145

TG'd the required GO MF terms; reasoner will fill in sensible FYPO ancestry when the new GO terms are available.

**Comment by mah11** [comment]
edit file: a411f52957726ae8601bcdc51ab138446e7a0399
release: a0f809c8ef7bf13df45f7e875d5dd36751ca02f9
