### ISSUE TITLE
new terms for nuclear localization  / proteasome 

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2474]
NTR: normal proteasome localization to nuclear periphery
descendent of
FYPO:0000644	normal protein localization during vegetative growth

NTR: abolished proteasome localization to nuclear periphery

NTR increased protein localization to nuclear periphery (cut8)
NTR normal protein localization to nuclear periphery

**Comment by mah11** [comment]
normal proteasome localization to nuclear periphery FYPO:0005146
  abolished proteasome localization to nuclear periphery FYPO:0005147
  increased protein localization to nuclear periphery FYPO:0005148

also TG'd proteasome localization to nuclear periphery, so reasoner yada yada

normal protein localization to nuclear periphery is FYPO:0002563

**Comment by mah11** [comment]
edit file: a411f52957726ae8601bcdc51ab138446e7a0399
release: a0f809c8ef7bf13df45f7e875d5dd36751ca02f9
