### ISSUE TITLE
ntr: delayed protein degradation during mitosis

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2475]
descendant of
	abnormal protein degradation during vegetative growth

PMID:11084332

**Comment by mah11** [comment]
[Term]
id: FYPO:0004332
name: delayed onset of protein degradation during mitosis
def: "A cellular process phenotype observed in the vegetative growth phase of the life cycle in which protein degradation begins later than normal during mitosis." [PomBase:mah]
[snip several other synonyms]
synonym: "delayed onset of protein degradation during mitotic M phase" EXACT [PomBase:mah]
synonym: "delayed protein degradation during mitosis" EXACT [PomBase:mah]
is_a: FYPO:0000845 ! abnormal protein degradation during vegetative growth
