### ISSUE TITLE
term refinement, delayed onset of mitotic cell cycle arrest during cellular response to hydroxyurea 

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2505]
delayed onset of mitotic cell cycle arrest during cellular response to hydroxyurea 
is a suggested term refinement for
delayed onset of cell cycle arrest in mitotic G1 phase in response to nitrogen starvation

**Comment by mah11** [comment]
already fixed last week, but Canto update was broken (https://github.com/pombase/canto/issues/1050)
