### ISSUE TITLE
 inviable swollen elongated cell with enlarged nucleus  parentage

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2509]
can
 inviable swollen elongated cell with enlarged nucleus 
be a descendant of
 inviable elongated mononucleate aseptate cell

?

**Comment by mah11** [comment]
At present, the logical definition of FYPO:0002083 (inviable swollen etc.) does not specify "mononucleate" or "aseptated". If, however, EVERY cell that is (inviable + swollen + elongated  + enlarged nucleus) is also mononucleate and aseptate, those features can be added to the xp, and has_part links that Canto can use will be inferred.

**Comment by ValWood** [comment]
I checked all of the annotations for these...

Cdc18 and cdc13 delta are classic re replication phenotype
![cdc13](https://cloud.githubusercontent.com/assets/7359272/12419513/8e1b22ee-beae-11e5-9cb3-ff72a5abc9c8.jpg)

The ade genes are a descendent term I think as they are in stationary phase
but they are also aseptate and monoucleate...

![ade s](https://cloud.githubusercontent.com/assets/7359272/12419537/b2c64434-beae-11e5-93a5-91baa4f3fc83.jpg)

**Comment by mah11** [comment]
OK, done

edit file: 829a2180f4d321cf18dd800a8abfb1cb3c5f7816
release: 0d5f483950d46e038d7b813772942ddf053b62db
