### ISSUE TITLE
new protein localization terms

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2510]
PMID:26258632

can we change
protein localization abolished during vegetative growth to
protein localization abolished during mitotic cell cycle

and
normal protein localization to kinetochore during vegetative growth
to
normal protein localization to kinetochore during mitotic cell cycle

and add a term
protein localization abolished during meiotic cell cycle 
to group
abolished protein localization to telomere during meiotic cell cycle  
abolished protein localization to prospore membrane during meiosis II with protein mislocalized to plasma membrane  
abolished protein localization to kinetochore during meiosis I  

(Yoshi didn't drill down here I suspect because he didn't see anything immediately suitable, but he did add kinetochore localization as a comment)

NTR
abolished localization to kinetochore during mitotic metaphase

also	
decreased protein localization to mitotic spindle pole body during mitotic anaphase
normal protein localization to kinetochore during 	mitotic prometaphase

**Comment by mah11** [comment]
> can we change
> protein localization abolished during vegetative growth to
> protein localization abolished during mitotic cell cycle
> and [snip other one] ?

I vote no. All* of the terms that apply to the vegetative growth phase, and aren't directly about cell cycle regulation or progression, already have "during mitotic cell cycle" synonyms, and I don't see what would be gained by swapping (it would be a tedious lot of work to do them all, but I especially see no point in changing a select couple of terms, thereby becoming inconsistent).

*except for a handful of stragglers that I'm just fixing now

New terms all fine; watch this space.

**Comment by mah11** [comment]
abolished protein localization during meiotic cell cycle FYPO:0005208
  abnormal protein localization to kinetochore FYPO:0005209
  abolished protein localization to kinetochore during mitotic metaphase FYPO:0005210
  decreased protein localization to mitotic spindle pole body during anaphase FYPO:0005211
  normal protein localization to kinetochore during mitotic prometaphase FYPO:0005512

**Comment by mah11** [comment]
edit file: 8bb855d981e006750a0fed14cfb4fd3a85a1c59f
release: 8bb855d981e006750a0fed14cfb4fd3a85a1c59f
