### ISSUE TITLE
relationship and term question

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2511]
unequal mitotic sister chromatid segregation 
indicates an inabilite to biorientate chromosomes correctly.

Should there be a relationship between

FYPO:0000326 - abnormal sister chromatid biorientation 
"A cellular process phenotype in which the stable attachment of sister chromatids to microtubules emanating from opposite poles of the mitotic spindle during metaphase plate congression is abnormal." 

and
FYPO:0003241 - unequal mitotic sister chromatid segregation

also based on above def should biorientation be part of plate congression in GO? (this paper also indicates that it should but in GO they are siblings)

**Comment by ValWood** [comment]
in fact Yoshi used
metaphase plate congression as his GO annotation,

but in the text he used "bi-orientation" to describe the unequal segregation defects
(if he  searched on  bi-orientation he would not find  biorientation)

**Comment by mah11** [comment]
> Should there be a relationship ...

If there is really no other way that chromosome segregation can go wrong so as to end up parcelling out DNA unequally, then we can add FYPO:0003241 output_of FYPO:0000326.

> should biorientation be part of plate congression in GO?

Someone who knows more about these processes than I do would have to address that q.

**Comment by ValWood** [comment]
I think for the relationship we should problem not add it.

I do think biorientation should be a part of plate congression though...
See later GO ticket
(some of the relationships are already in place, but the speicific mitotic congression/biorientation link is missing

https://github.com/geneontology/go-ontology/issues/12243
and
https://github.com/geneontology/go-ontology/issues/12244

**Comment by mah11** [comment]
For now, I've added comments to both FYPO terms.

**Comment by mah11** [comment]
I'll close, but reopen or do a new ticket if you spot anything in FYPO that doesn't play nice with the revamped GO.
