### ISSUE TITLE
ntr: normal mitotic spindle formation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2512]
normal bipolar spindle

(Or should I just use 'normal mitotic spindle', I'm just not sure if everything is normal....

**Comment by mah11** [comment]
"Normal bipolar spindle" sounds redundant, because a normal spindle is by definition bipolar.

I guess I would annotate to "normal mitotic spindle" if I didn't see any evidence actively suggesting that something was abnormal about it.

**Comment by ValWood** [comment]
OK

**Comment by mah11** [comment]
as an aside, added synonym "normal mitotic spindle formation" to normal mitotic spindle assembly
