### ISSUE TITLE
abolished  microtubule plus-end directed mitotic chromosome migration

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2513]
need to wait for GO term
https://github.com/geneontology/go-ontology/issues/12244

(in the mean time I have used  the parent abnormal mitotic chromoosme congression)

**Comment by mah11** [comment]
GO:0099606 now available

**Comment by mah11** [comment]
abnormal microtubule plus-end directed mitotic chromosome migration FYPO:0005271
  abolished microtubule plus-end directed mitotic chromosome migration FYPO:0005272

**Comment by mah11** [comment]
edit file: 6ed67908e769470d4cd5e32b2e31751cba8581c2
release: 177067ba0b96083275fece46904f9eb490e908ca
