### ISSUE TITLE
increased antisense RNA transcription

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2515]
increased antisense RNA transcription 
is not a suggested refinement term of 	
increased antisense RNA level

**Comment by mah11** [comment]
added link increased antisense RNA transcription (FYPO:0002913) has_output increased antisense RNA level FYPO:0003557)

**Comment by mah11** [comment]
added link FYPO:0002913 has_output FYPO:0003557

**Comment by mah11** [comment]
edit file: 8bb855d981e006750a0fed14cfb4fd3a85a1c59f
release: 8bb855d981e006750a0fed14cfb4fd3a85a1c59f
