### ISSUE TITLE
decreased chromatin silencing parentage

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2516]
decreased chromatin silencing at centromere central core 
is not a suggested refinement term of 
abnormal chromatin silencing at centromere central core 

The same is true for eg outer repeat

**Comment by mah11** [comment]
That's weird. I thought those ought to be inferred. Oh well, I'll assert them manually.

**Comment by mah11** [comment]
edit file: 8bb855d981e006750a0fed14cfb4fd3a85a1c59f
release: 8bb855d981e006750a0fed14cfb4fd3a85a1c59f
