### ISSUE TITLE
ntr: decreased protein localization to kinetochore during M-phase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2517]
Apologies if I already requested this one but I can't see it in canto or open tickets so I'm guessing not..

standard def

PMID:15930132

**Comment by ValWood** [comment]
also
normal protein localization to mitotic spindle pole body during metaphase
PMID:15930132

**Comment by mah11** [comment]
decreased protein localization to kinetochore during mitosis FYPO:0005215 ('mitotic M phase' in exact synonym; there are a bunch like this already)
  normal protein localization to mitotic spindle pole body during metaphase FYPO:0005216

**Comment by mah11** [comment]
edit file: 8bb855d981e006750a0fed14cfb4fd3a85a1c59f
release: 8bb855d981e006750a0fed14cfb4fd3a85a1c59f
