### ISSUE TITLE
MP abolished proteasome localization to nuclear periphery

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2518]
abolished proteasome localization to nuclear periphery
is not visible as a descendant of
abolished protein localization to nuclear periphery

**Comment by mah11** [comment]
Looks like there's a link missing in GO:

[Term]
id: GO:1990920
name: proteasome localization to nuclear periphery
namespace: biological_process
def: "Any process in which the proteasome is transported to, or maintained at the nuclear periphery." [PMID:11084332]
is_a: GO:0031144 ! proteasome localization

Ask them to add is_a: GO:1990139 ! protein localization to nuclear periphery, and the FYPO link will then be inferred.

**Comment by mah11** [comment]
The link GO has finally gone live, so the inference is happening as desired.
