### ISSUE TITLE
ntr: abnormal oligomerization

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2521]
From discussion.

**Comment by mah11** [comment]
threw in normal too for good measure

  abnormal protein oligomerization FYPO:0005220
  normal protein oligomerization FYPO:0005221

**Comment by mah11** [comment]
edit file: 17834391eeacebf18b869e1bf7e18376215ff0fd
release: 8d709f8812432f5eb16aabe63422f573b6366b8a
