### ISSUE TITLE
MP decreased protein localization to mitotic spindle pole body during anaphase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2523]
I don't think
decreased protein localization to mitotic spindle pole body during anaphase
is a descendent of 
decreased protein localization to mitotic spindle pole body during mitosis?

**Comment by mah11** [comment]
drat, thought that'd be inferred, but I think reasoner only really follows is_a
added manually

**Comment by mah11** [comment]
edit file: 17834391eeacebf18b869e1bf7e18376215ff0fd
release: 8d709f8812432f5eb16aabe63422f573b6366b8a
