### ISSUE TITLE
ntr: ubiquitinated protein level

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2525]
descendant of
FYPO:0002082	increased protein ubiquitination	

def
A cellular process phenotype observed in the vegetative growth phase of the life cycle in which the occurrence of ubiquitination  is increased.

I don't know if we do it this way. They just looked at ubiqutinated protein generally?

**Comment by ValWood** [comment]
just reilised I should have used
increased level of ubiquitinated protein in cell during vegetative growth
so as a child of this

**Comment by Antonialock** [comment]
Just use FYPO:0002082 increased protein ubiquitination  and don't specify a substrate

**Comment by mah11** [comment]
I would use 'increased level of ubiquitinated protein in cell during vegetative growth' (FYPO:0002774) if they only measured the amount of Ub'd protein.

**Comment by ValWood** [comment]
actually it seems that its normal so
ntr normal level of ubiquitinated protein in cell during vegetative growth

**Comment by ValWood** [comment]
and 
decreased level of ubiquitinated protein in cell during vegetative growth

**Comment by mah11** [comment]
decreased level of ubiquitinated protein in cell FYPO:0005226
  normal level of ubiquitinated protein in cell FYPO:0005227

**Comment by mah11** [comment]
edit file: 17834391eeacebf18b869e1bf7e18376215ff0fd
release: 8d709f8812432f5eb16aabe63422f573b6366b8a
