### ISSUE TITLE
comment needed to clarify usage (protein localization to spindle)

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2532]
in this session
~curs/558b22ef42aa6ec2

I  changed
abnormal spindle pole body localization
to
decreased protein localization to mitotic spindle pole body during mitosis

maybe we should add a comment to this to make it clear that this is 'spindle localization' not a protein localized to the spindle... it can be confusing

**Comment by mah11** [comment]
added text from GO def

**Comment by mah11** [comment]
edit file: 245cc5e9bac91981cfa01a2e702333db2eae4f12
release: fac9f9f87d3b8884f99eb5614ae1338d20e8f50b
