### ISSUE TITLE
more from PMID:25665008

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2536]
decreased cellular proline level
increased cell population growth at high temperature
increased cell density in stationary phase
increased cell density in stationary phase
increased cell population growth at high temperature
increased cell population growth at high temperature
increased cell population growth at low temperature
increased cell population growth on galactose carbon source
increased cell population growth on galactose carbon source
increased cell population growth on maltose carbon source
increased cell population growth on maltose carbon source
increased cellular arginine level during vegetative growth
resistance to dithiothreitol
resistance to lead
resistance to sodium dodecyl sulfate
sensitive to aluminium

**Comment by mah11** [comment]
decreased cellular proline level FYPO:0005257
  increased cell population growth at high temperature FYPO:0005258
  increased cell density in stationary phase FYPO:0005259
  increased cell population growth at low temperature FYPO:0005260
  increased cell population growth on galactose carbon source FYPO:0005261
  increased cell population growth on maltose carbon source FYPO:0005262
  increased cellular arginine level FYPO:0005263
  resistance to dithiothreitol FYPO:0005264
  resistance to lead FYPO:0005265
  resistance to sodium dodecyl sulfate FYPO:0005266
  sensitive to aluminium FYPO:0005267

**Comment by mah11** [comment]
edit file: 9027d261a94b01dbb01ff548fd1013c275ce8dfa
release: 223def626685c49cf956fe0665de08de5fb8dc50
