### ISSUE TITLE
decreased chromatin silencing at centromere outer repeat relationship to abnormal chromatin silencing at centromere outer repeat 

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2540]
decreased chromatin silencing at centromere outer repeat is not showing as a suggested refinement term for 
 	abnormal chromatin silencing at centromere outer repeat

**Comment by mah11** [comment]
drat, I'd hoped that would be inferred. oh well, added link manually

edit file: afcfab44c621b3e43b077939e753237e935f340d
release: a9cf2376c674b95ce113f48a25ab6257722de61f
