### ISSUE TITLE
inviable septated mononucleate vegetative cell descendent

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2543]
should I see
FYPO:NEW - septation following abolished chromosome separation, with mononuclear and anucleate compartments

i

**Comment by ValWood** [comment]
I see
inviable septated mononucleate vegetative cell 
as a descendant of 
septation following abolished chromosome separation, with mononuclear and anucleate compartments

**Comment by mah11** [comment]
Right now there is a link (FYPO:0002000 is_a FYPO:0005070), but I think I ought to remove it, because FYPO:0002000 isn't defined as specific for forming anucleate and mononucleate compartments, as opposed to cut. Will that work for you?

**Comment by ValWood** [comment]
yes, but I think we also need
septated mononucleate vegetative cel|
and 
FYPO:NEW - septation following abolished chromosome separation, with mononuclear and anucleate 

would be a descendant of it?

When I drill down its still hard to find the new term (mainly because I was in the wrong place), but I think this would help
I might need to move some of 
inviable septated mononucleate vegetative cell  to this new term I used to think this was an inviable phenotype, but some can go on to form viable diploids.

Make sense?

**Comment by mah11** [comment]
new term
  septated mononucleate vegetative cell FYPO:0005276

deleted link FYPO:0002000 is_a FYPO:0005070
adjusted some other links in relevant branch

**Comment by mah11** [comment]
edit file: 6ed67908e769470d4cd5e32b2e31751cba8581c2
release: 177067ba0b96083275fece46904f9eb490e908ca
