### ISSUE TITLE
FYPO term corresponding to "wee"

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2544]
I'm not sure where we got to with this but can you remind me why this isn't possible:
viable small vegetative cell with premature mitosis
A cellular process phenotype in which cells enter mitosis earlier, relative to cell size than normal.
(Val to do, once we have a term which is an exact synonym of 'wee', migrate all wee phenotype to this term)

For more background see
https://sourceforge.net/p/pombase/fission-yeast-phenotype/1770/
(but I think this covers it)

(Note to self, if we have a term, will need to migrate some annotations, true 'wee')

**Comment by mah11** [comment]
When we last left this question, it needed you to figure out what, if any, criteria can be used to determine *independently of cell size* whether mitosis happens prematurely.

It might also be interesting to define explicitly what's going on in a cell that is smaller than normal but has mitosis taking place at the normal time, but that's not as essential for adding a new term.

**Comment by mah11** [comment]
Val to ask Jacky if there's any way for a cell to be small other than to be "born that way". If not, M to add to texd def, and add has_part premature mitosis to FYPO:0000648.

**Comment by mah11** [comment]
Because this question has arisen again, specific points to consider:

- Is "wee" really exactly FYPO:0000648 ! viable small vegetative cell, or are more differentiae needed?

- Either way, how should wee connect to cell cycle? I doubt that an is_a link to cell cycle will work, but has_part premature mitosis would probably do the trick.

**Comment by mah11** [comment]
From curator meeting, we finally have a distinguishing feature: growth rate. Hooray!

add two terms, is_a fypo:648
1. ... with normal growth rate
2. ... with slow growth

move "wee" synonym to new1

**Comment by ValWood** [comment]
list in brown notepad and in my query manager

**Comment by ValWood** [comment]
https://github.com/pombase/curation/issues/2085

**Comment by ValWood** [comment]
I think you can close this. I'm guessing this was the "external change" I was waiting for to do 
pombase/curation#2085

**Comment by mah11** [comment]
are we back to "this can be closed"?

I'd be happier not swapping which ID goes with which definition, because doing so would be colossally dodgy (and not possible at all if anyone else were using FYPO).

**Comment by mah11** [comment]
I'd still feel most comfortable leaving 'viable small vegetative cell' as FYPO:0000648, and adding the two sub-types with new IDs. But I could do it the other way round (FYPO:0000648 add 'normal growth rate' is_a new1, and new2 is_a new1).

In light of the edit to https://github.com/pombase/fypo/issues/2544#issuecomment-459048061, I'm no longer sure which you want ...

**Comment by ValWood** [comment]
Do what you think is best, I can migrate accordingly...

**Comment by mah11** [comment]
OK, added

  viable small vegetative cell with normal cell growth rate FYPO:0006822
  viable small vegetative cell with slow cell growth FYPO:0006823

(and some grouping terms
  normal vegetative cell growth rate FYPO:0006819
  abnormal cell growth rate FYPO:0006820
  slow vegetative cell growth FYPO:0006821
)

edit file: 64d9f12ae1eab54159a520b37ace4bb79f55b7cc
release: 4faa0186ac4092ea41fe1d9dca5ae9b4c6cf43fc

**Comment by ValWood** [comment]
viable small vegetative cell with normal cell growth rate FYPO:0006822

can we add a synonym
viable small vegetative cell with premature mitosis 
(in fact could this be the primary name as it will be more obvious to users, they aren't thinking about growth rate here they are thinking about  size at division.

to this?
and "Wee" if it doesn't have it, but I think it has.

Also, this should be a descendant of 
"viable small vegetative cell"
(users are missing it)

**Comment by ValWood** [comment]
also update the comment:
(since this should  be  related to premature mitosis?)

~Also consider annotating to 'premature mitosis (FYPO:0001046), because small cells arise when mitosis takes place earlier than normal (i.e. at a smaller cell size).~ Note that if you have done an experiment that assays the viability of a population of cells, such as looking at colony growth or growth in liquid culture, you should also annotate to 'viable cell population' (FYPO:0002058) or one of its descendants.

**Comment by mah11** [comment]
> viable small vegetative cell with normal cell growth rate FYPO:0006822
> 
> can we add a synonym
> viable small vegetative cell with premature mitosis

This brings back my original question, because I still don't understand what you're using other than cell size to tell mitosis is premature. In other words, why would "with premature mitosis" apply to FYPO:0006822 but not to FYPO:0006823 or the parent FYPO:0000648? (That's also why all three terms have the comment at present.) Is it just based on the amount of time that has elapsed since the previous mitosis?

> Also, this should be a descendant of "viable small vegetative cell"

I can see whether reasoning gets thrown off if I assert 
 FYPO:0006822 is_a FYPO:0000648 and
 FYPO:0006822 is_a FYPO:0000648.

Be warned that if bad things happen I may have to revert.

Note to self: something looks borked with the logical defs. Fix 'em.

p.s. this has been closed long enough that it would have been easier to find a new ticket than to reopen this one

**Comment by ValWood** [comment]
> This brings back my original question, because I still don't understand what you're using other than cell size to tell mitosis is premature. In other words, why would "with premature mitosis" apply to FYPO:0006822 but not to FYPO:0006823 or the parent FYPO:0000648? (That's also why all three terms have the comment at present.) Is it just based on the amount of time that has elapsed since the previous mitosis?

I thought that was what we established? The fact that if cell is growing at a normal rate, but divides small indicates premature mitosis ?

this was to distinguish from cells which grow slowly and divide small because of lack of nutrients (they are just starved small)

> Is it just based on the amount of time that has elapsed since the previous mitosis?
yes

@JackyVH  have I got this right?

**Comment by mah11** [comment]
> I thought that was what we established? The fact that if cell is growing at a normal rate, but divides small indicates premature mitosis ?

It depends on how mitosis gets defined as "premature" - if it's by time elapsed, then we can make this distinction. If it had been defined relative to cell size, then we couldn't, hence my question. Its' taken a long time to find a definition for "premature mitosis" that wasn't just "mitosis before cells are as big as normal".

I'll put something explicit about elapsed time in the FYPO:0006822 text def.

> this was to distinguish from cells which grow slowly and divide small because of lack of nutrients (they are just starved small)

Don't forget that to annotate any abnormal phenotype, the cells have to be different from wild type under the same conditions. IOW, don't use FYPO:0006823 unless mutant cells are even smaller than wild type when both are starved and growing slowly. (This may be another reason for my lingering confusion.)

**Comment by ValWood** [comment]
Yes, true "wee" grow at a normal rate but divide early (this is how I understand it).

We should only be using this term when cells are smaller then normal compared to WT. There is no starvation in these assays.

That said in the session I was doing I am probably going to move back up to the 'parent'

"small viable vegetative cell". I'm using a bit of 'insider knowledge because this is   upstream of wee1

**Comment by ValWood** [comment]
Actually I think i'm OK to leave as is:

When imaging mid1-9A cells, we noticed that they reproducibly divided at a shorter cell length than wild-type, indicating that the G2/M transition was advanced (Figures 4E and S4E) [33].

**Comment by mah11** [comment]
> Yes, true "wee" grow at a normal rate but divide early (this is how I understand it).

How is "early" defined? Just making sure that it's something like "less than x min after previous division, where WT divides at x min".

> We should only be using this term when cells are smaller then normal compared to WT.

True. Moreover, we should only use _any_ "small cell" term when cells are smaller than normal compared to WT under the same conditions.

> There is no starvation in these assays.

Fine, but this is irrelevant to the definitions (and to the distinction between "wee" and "that other kind of small veg cell that isn't wee"). If starvation makes both WT and mutant divide at the same smaller-than-unstarved size, _don't_ annotate the mutant to a "small cell" term.

**Comment by mah11** [comment]
various edits done in
edit file: 771ddc6a790a6ebe6b86dea23a41583aca8b0b1c
release: 9cb110e7652dad44b54e9ba751cb393db4b03d13
