### ISSUE TITLE
terms not to annotate

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2545]
As a follow up from
https://github.com/pombase/curation/issues/755

I evaluated all
FYPO:0001223 - binucleate multiseptate vegetative cell
FYPO:0001253 - elongated multinucleate multiseptate vegetative cell, septa between nuclei
and I could not find anything which should be annotated directly to that term rather than a descendant.
could we 'block' these with a soft check (if it changes we can remove)
(this will also indicate if I missed one where there were multiple alleles)

Also,
I could not see
FYPO:0003344
elongated multinucleate multiseptate cell, single septa between nuclei, during stationary phase

as a descendant of
FYPO:0001253 - elongated multinucleate multiseptate vegetative cell, septa between nuclei

**Comment by mah11** [comment]
We do not have the "soft check" system set up for FYPO as we do for GO. If you want to implement it, create a file analogous to pombe-embl/supporting_files/GO_terms_excluded_from_pombase.txt, and open a ticket on the Chado tracker for Kim to add to the loading procedure.

I'll look into the links for 3344 & 1253 next time I'm editing, and will close this then.

**Comment by mah11** [comment]
Val to do soft check file & open ticket for Kim
M to remove a few terms from "don't annotate" subset in the ontology

**Comment by ValWood** [comment]
https://github.com/pombase/pombase-chado/issues/522

**Comment by mah11** [comment]
I've moved a slew of terms from the subset specified within the ontology to the new soft-check file.
