### ISSUE TITLE
loss of viability in S-phase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2564]
How would you capture this? I'm not sure if there is an existing term?

Viability was lost during the S phase at 268C only in the presence of 2mM HU (Fig. 2b).
	PMID:12000964

**Comment by ValWood** [comment]
At higher concentrations its 
abnormal cell cycle arrest in mitotic S-phase
so could I have this term too.

It will be difficult to differentiate the HU conc. so I'll just to this one.

**Comment by mah11** [comment]
I'm pretty sure I've just cheated and annotated this sort of thing as "sensitive to x". There are a few "sensitive to x during cell cycle phase y" terms, and I'm happy to add another.

I.e. I'd add and use "sensitive to hydroxyurea during mitotic S phase".

**Comment by mah11** [comment]
yeah, that's fine too

**Comment by mah11** [comment]
holler if you want the new term - if no further comments, I'll leave as is

**Comment by ValWood** [comment]
I'll get this one:
abnormal cell cycle arrest in mitotic S-phase

**Comment by mah11** [comment]
ok. The existing term (FYPO:0000611) has a synonym that implies it's meant to mean "abnormal" already anyway. Should I just rename it?

**Comment by ValWood** [comment]
OK

**Comment by mah11** [comment]
renamed & moved, so use FYPO:0000611

**Comment by mah11** [comment]
edit file: deaef0426ccef63b4fdb8e7b0497838810101852
release: b0b60d0941f0bc92c4971f6a2dad85df58ea1031
