### ISSUE TITLE
ntr:elongated vegetative cell in response to ultraviolet irradiation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2565]
PMID:12000964
elongated vegetative cell in response to ultraviolet irradiation

**Comment by mah11** [comment]
so, like FYPO:0005200 but not including "inviable"?

id: FYPO:0005200
name: inviable elongated vegetative cell during cellular response to UV

**Comment by ValWood** [comment]
yep  they seem to limp along...

**Comment by mah11** [comment]
elongated vegetative cell during cellular response to UV FYPO:0005303

**Comment by mah11** [comment]
edit file: deaef0426ccef63b4fdb8e7b0497838810101852
release: b0b60d0941f0bc92c4971f6a2dad85df58ea1031
