### ISSUE TITLE
ntr: increased duration of mitotic interphase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2566]
child of
increased duration of mitotic cell cycle phase
PMID:12000964

**Comment by ValWood** [comment]
and 
normal duration of mitotic interphase

**Comment by mah11** [comment]
increased duration of mitotic interphase FYPO:0005304
  normal duration of mitotic interphase FYPO:0005305

**Comment by mah11** [comment]
edit file: deaef0426ccef63b4fdb8e7b0497838810101852
release: b0b60d0941f0bc92c4971f6a2dad85df58ea1031
