### ISSUE TITLE
2 possible oddities in centromere stuff

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2568]
1. abolished  protein localization to centromere central core
has descendent 
abolished protein localization to chromatin at centromere central core

I don't see any real difference here? The chromosome central core region is chromatin 

2.
normal protein localization to CENP-A contning chromatin
is sibling to
normal protein localization to centromeric chromatin

but I think 
normal protein localization to CENP-A containing chromatin
is_a
normal protein localization to centromeric chromatin

**Comment by mah11** [comment]
Is no. 1 applicable to all "protein localization to centromere" terms? Or just the central core?

**Comment by ValWood** [comment]
just the central core.

**Comment by mah11** [comment]
asserted links
  FYPO:0004312 is_a FYPO:0003744
  FYPO:0004314 is_a FYPO:0005072

merged
  FYPO:0003765 into FYPO:0003786
  FYPO:0005224 into FYPO:0004904

also added a new grouping term
  abnormal protein localization to centromeric chromatin during vegetative growth FYPO:0005306

**Comment by mah11** [comment]
edit file: deaef0426ccef63b4fdb8e7b0497838810101852
release: b0b60d0941f0bc92c4971f6a2dad85df58ea1031
