### ISSUE TITLE
move microtubule term?

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2573]
should
microtubules absent from cell 
be a descendent of
abnormal microtubule cytoskeleton during vegetative growth
as defined?

**Comment by mah11** [comment]
Rats, another one I thought would be inferred. Done manually.

**Comment by mah11** [comment]
edit file: deaef0426ccef63b4fdb8e7b0497838810101852
release: b0b60d0941f0bc92c4971f6a2dad85df58ea1031
