### ISSUE TITLE
sensitive to TSA PMID:17004072

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2574]
a histone deacetylase inhibitor.
Never heard of it before?
PMID:17004072

**Comment by ValWood** [comment]
I wonder if this is it?
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:45825

**Comment by mah11** [comment]
They say in the methods that it's trichostatin A. I'll add a synonym to FYPO:0002546.

**Comment by ValWood** [comment]
ah thankyou!

**Comment by mah11** [comment]
edit file: deaef0426ccef63b4fdb8e7b0497838810101852
release: b0b60d0941f0bc92c4971f6a2dad85df58ea1031
