### ISSUE TITLE
some small 'cut' phenotype tweaks

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2577]
1. cut following normal mitosis
An inviable phenotype observed in the vegetative growth phase of the life cycle in which a cell becomes cut after it has undergone a normal mitotic nuclear division and passed through the subsequent mitotic interphase. In a cut phenotype, a cell undergoes septation despite abnormal chromosome segregation, such that the septum physically divides the nucleus into two parts, and produces inviable daughter cells.

Comment	
This phenotype affects the second round of mitosis to take place after a mutation exerts its effect. For example, if a conditional mutant is shifted to restrictive conditions in G1 or S phase and the first mitosis thereafter is normal, but the second results in a cut cell (even if cells are returned to permissive conditions in the second G1 or S phase), this term is applicable.

All good

but I remembered we have a term
"abnormal mitosis following normal mitosis" which is very similar (should be a parent).
A cellular process phenotype in which mitosis takes place abnormally after the cell has undergone a normal mitotic nuclear division and passed through the subsequent mitotic interphase.
Comment	
This phenotype affects the second round of mitosis to take place after a mutation exerts its effect. For example, if a conditional mutant is shifted to restrictive conditions in G1 or S phase and the first mitosis thereafter is normal, but the second is not (even if cells are returned to permissive conditions in the second G1 or S phase), this term is applicable.

Also, so it is less confusing what this term means, I think we should rename
 cut following normal mitosis to
cut in mitosis following normal mitosis

(just to be explicit)

**Comment by ValWood** [comment]
2.  Then, we have another term
cut following normal mitotic entry 
An inviable phenotype in which a cell enters mitosis normally, but then undergoes septation despite abnormal chromosome segregation, such that the septum physically divides the nucleus into two parts, and produces inviable daughter cells.

This one,  looking at the annotations, really means not only 'normal mitotic entry' (how would we know), but that everything preceding separation is normal.

I think we could rename and redefine this one as:

cut following normal mitotic chromosome condensation?
 An inviable phenotype in which a cell enters mitosis normally, *the spindle forms normally and the chromosomes condense normally*, but then undergoes septation despite abnormal chromosome **separation**, such that the septum physically divides the nucleus into two parts, and produces inviable daughter cells.


I think this then distinguishes two major cut phenotypes
1. Those where the defect is in interphase
2. those where the defect is in anaphase/metaphase transition (checkpoint, APC, securin pathway)

3. One other small thing
inviable after spore germination, single or double cell division, arrest with cut
should not be a descendent of "cut following normal mitotic entry"
(which would correctly get rid of orc5, smc5, pol1 from this term)

4. Finally, I'm puzzled by the period of the temperature shift. I thought that for 1 the temperature shift would need to take place *after* S-phase (because its S-phase that has the problem). S-phase would be normal. Temperature shift.  Normal mitosis. Abnormal replication. Abnormal mitosis.










(normal chromosome condensation, i.e everything unto separation is normal)
spindles form and chromosomes condense normally
(child looks wrong)
	inviable after spore germination, single or double cell division, arrest with cut
(which would get rid of orc5, smc5, pol1)

**Comment by mah11** [comment]
> "abnormal mitosis following normal mitosis" ... (should be a parent) [of FYPO:0004592]

Are you asking for an is_a link? That would have the logical implication cut itself should be is_a 'abnormal mitosis'. I haven't done it that way because the abnormal mitosis is only part of the cut phenotype -- the septation happening anyway is the other part, not covered by 'abnormal mitosis'.

So I could add 'cut following normal mitosis' has_part 'abnormal mitosis following normal mitosis'. That would work better than is_a.


> rename ... to cut in mitosis following normal mitosis

Actually, I find this more confusing, not less (as well as looking a bit silly).


> [lots re FYPO:0001055] - rename and redefine this one as: cut following normal mitotic chromosome condensation?

So, does this all mean that the definition should stay the same for most of the 'cut' phenotypes (FYPO:0003165 and its is_a descendants other than FYPO:0001055), i.e. they can continue to refer to the broader "chromosome segregation" process?

We did add FYPO:0001055 at the same time as most of the 'mitotic catastrophe' terms, I think to represent cut-without-catastrophe explicitly, so if the def wording change is consistent with that intent it makes sense. (ticket #190)


> inviable after spore germination, single or double cell division, arrest with cut should not be a descendent of "cut following normal mitotic entry"

easy to delete that link

> Finally, I'm puzzled by the period of the temperature shift.

It's not clear which term(s) you're referring to here, but this doesn't look like an ontology question. (There are comments to help explain what the "following normal mitosis" means, but they don't restrict what temperature shift experiments can be annotated; they just say "for example, [yada]".)

**Comment by ValWood** [comment]
1.
I wonder if cut should not be a cytokinesis defect. There isn't a problem with cytokinesis per se. The problem is with chromosome segregation, but it can't be overcome so cytokinesis happens anyway (normally).

2. rename ... to cut in mitosis following normal mitosis
Actually, I find this more confusing, not less (as well as looking a bit silly).
-> ignore

3. So, does this all mean that the definition should stay the same for most of the 'cut' phenotypes (FYPO:0003165 and its is_a descendants other than FYPO:0001055), i.e. they can continue to refer to the broader "chromosome segregation" process?

Yes for now. This is specifically for the instances where no separation has occurred. Might need to refine others later.It may turn out that they all  enter mitosis normally, but I don't know yet...If everything ends up on this term we can consider getting rid of some of the other terms, or merging...

**Comment by mah11** [comment]
> I wonder if cut should not be a cytokinesis defect

Cut is not defined as a type of cytokinesis defect. It's defined (by transitivity, from the FYPO:0000229 logical def) as having premature septation (aka cytokinesis) as one of its parts. To me that's consistent with "cytokinesis happens anyway" (can be normal except for timing relative to state of chromosome segregation).

> > [Should only FYPO:0001055 have its def changed?]

> Yes for now.

OK, will do.

**Comment by mah11** [comment]
- added link FYPO:0004592 has_part FYPO:0004588

- edited name & text def FYPO:0001055

- deleted link FYPO:0003760 is_a FYPO:0001055

I think that's everything for this ... and I'm sure it'll be easier to open a new ticket if I missed anything!

**Comment by ValWood** [comment]
Yes, I've confused myself but I think that's everything for now

**Comment by mah11** [comment]
edit file: 138d806d362c771009d917f669073b54cb4452af
release: 0c9f107ee56df966ee46641cac1897aa7fa31157
