### ISSUE TITLE
relationship between "abolished mitotic sister chromatid separation" and metaphase/anaphase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2578]
FYPO:0001946	abolished mitotic sister chromatid separation

and

abnormal cell cycle arrest at mitotic metaphase/anaphase transition

?

Its true I guess, but in this case I think we would want to record what we see if that is 
abolished mitotic sister chromatid separation

I presume its has_output
abnormal cell cycle arrest at mitotic metaphase/anaphase transition

If so, I think we need to reconsider whether we still see these as suggestions, because we wouldn't really be capturing what we saw.
I think I have  another ticket about this issue, so I'll see if its the same relation as this one, and we can make a decision based on this.

**Comment by mah11** [comment]
The link is has_part. Can you ever get arrest at the metaphase/anaphase transition but still have chromatid separation happen? I thought not, so I included the link.

I suspect has_output would also agree with biology (i.e. arrest has_output abolished separation, not the other way round), and might even be a bit better.

If you can have metaphase/anaphase arrest but still get some chromatid separation, then I'll have to just delete the link.

**Comment by ValWood** [comment]
I'm now not sure how we could separate these 2 terms.


I would use 
FYPO:0001946 abolished mitotic sister chromatid separation
if NO separation was detected (i.e chromosomes were condensed, but cells were still in metaphase , i.e the APC was never activated)

I would use
"abnormal cell cycle arrest at mitotic metaphase/anaphase transition"
in exactly the same circumstances, I think.  (i.e chromosomes were condensed, but cells were still in metaphase , i.e the APC was never activated)

I'm going to check what the phenotypes look like for these 2 terms.

**Comment by ValWood** [comment]
this is the phenotype for 
abnormal cell cycle arrest at mitotic metaphase/anaphase transition
you could also easily also make the annotation 
abolished mitotic sister chromatid separation any time you saw this?

![dis3](https://cloud.githubusercontent.com/assets/7359272/13567453/502a6042-e453-11e5-9db8-915a0884949c.jpg)


![dis3-3](https://cloud.githubusercontent.com/assets/7359272/13567476/716a1630-e453-11e5-8e99-a1b9ff764f7e.jpg)

**Comment by ValWood** [comment]
However, we also have a term
"abolished rDNA separation"
I don't know if this means that only the rDNA fails to separate.

**Comment by ValWood** [comment]
So in summary, its all OK isn't it!

abnormal cell cycle arrest at mitotic metaphase/anaphase transition
is the best term to use, because this will always be annotated to 
abolished mitotic sister chromatid separation

I think it might be useful just to add a comment to 
Definition: "A cellular process phenotype in which progression through the mitotic cell cycle is arrested at the metaphase/anaphase transition under conditions where arrest does not normally occur." [

that NO chromosome separation occurs in this phenotype.

**Comment by mah11** [comment]
Over in #2580 we've decided FYPO:0000392 gets the ax, so I've made changes for this ticket to FYPO:0000620. Added a comment and the link FYPO:0000620 has_output FYPO:0001946.

**Comment by mah11** [comment]
edit file: 138d806d362c771009d917f669073b54cb4452af
release: 0c9f107ee56df966ee46641cac1897aa7fa31157
