### ISSUE TITLE
FYPO:0004532 - abnormal cell cycle arrest in mitotic metaphase with abnormal spindle (fission_yeast_phenotype)

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2582]
there was a single annotation to this term:

abnormal cell cycle arrest in mitotic metaphase with abnormal spindle

it does not appear to be metaphase arrested though, so I deleted the annotation.

I think we should get rid of this term, as abnormal spindle is probably a general hallmark of metaphase arrest (although I  now think you can arrest in metaphase with a short spindle, or an abnormally  long spindle?)

**Comment by mah11** [comment]
Antonia requested FYPO:0004532 in #2146, so it won't hurt to have her thoughts on this.

In cells generally, I don't think the spindle has to be abnormal for cells to arrest in metaphase. I don't know enough about pombe to know if you can get metaphase arrest with a normal spindle, but if not, I suspect the restriction would be pombe- (or at least fission yeasts-) specific.

@Antonialock

**Comment by ValWood** [comment]
OK,  but I looked through this paper a few times and I don't see any metaphase arrest phenotype.

However, I  do think you can arrest in metaphase with a normal short spindle, or an abnormally long spindle. We can keep this term, but flag as not for annotation, because it would be more useful to know how the spindle is abnormal here.

**Comment by Antonialock** [comment]
I don't think cell cycle arrest with abnormal spindle is wrong? 
I based that annotation on

1. cells overexpressing pkl1 arrest and die (and they say the chromatin is condensed)
![screen shot 2016-03-15 at 17 37 34](https://cloud.githubusercontent.com/assets/12727506/13787648/a53f45ac-ead4-11e5-80d4-13ebdb8451ba.png)

2. They say:
The numbers of these aberrant spindles increased as the level of pkl1 increased, and there was a concomitant decrease in the number of normal-looking spindles in the population (Figure 3C). At 22 h after the switch to thiamine-free medium, therewere very few normal looking spindles in the pREP3X-PKL1culture.

They also call the abnormal spindle "star shaped"
![screen shot 2016-03-15 at 17 38 40](https://cloud.githubusercontent.com/assets/12727506/13787712/ee4f06b0-ead4-11e5-8f90-a538bbfd70d0.png)

**Comment by ValWood** [comment]
Ah OK. I was thinking that the star shaped spindle was a post anaphase phenotype. I got this from the fact that all of the cells which display the late anaphase phenotype at 11 hours go on to display the star shaped spindle at 22h, so I inferred that these are not metaphase arrested and were displaying some sort of post-anaphase spindle collapse.

There is a slight problem aligning the 'classical'  markers of metaphase/anaphase etc with how you would define the stages when things go awry (because the classical  phase markers don't occur int e same order). I am trying to pick this apart as I work through the chromosome segregation papers.

The absolute determinant of anaphase/metaphase transition  is that the SAC is turned off, APC  active (and therefore separase active) and chromosome separation has occurred.

Here it looks from the schematic like chromosomes separate, but they might not.  Conjoined sister chromatids could be segregated. If this *is* the case, you are correct, you are still in metaphase.

**Comment by ValWood** [comment]
I'm sure I have seen these 'star-shaped' splndles before, but I don't  know how I have curated them.

I found 	"multiple mitotic spindles with abolished sister chromatid separation"
Which *might* be the same thing:
![spindles](https://cloud.githubusercontent.com/assets/7359272/13803391/1f09f6d6-eb3c-11e5-9741-9e516c626ced.jpg)

I now wonder if both of these are  broken or fragmented elongated spindles?

**Comment by Antonialock** [comment]
Ok, so I was wrong about the metaphase arrest. 
But you said "it does not appear to be metaphase arrested though, so I deleted the annotation." 
why didn't you change it to some other abnormal spindle term? Should this not be annotated at all?

**Comment by ValWood** [comment]
It could actually  *be* metaphase arrest if the chromosomes never separate, it just isn't possible to establish from this data, i think.

I should have made a new ' abnormal spindle" annotation but I was too focussed on metaphase arrest.

Ignoring what I said above about specifying how the spindle is abnormal (because it isn't so clear what has happened to is) it could be annotated to

"abnormal cell cycle arrest in M-phase with abnormal spindle"

We might be able to refine later when it is clearer what is happening to the spindle and the chromosomes at this point and whether they have really progressed into anaphase.

**Comment by Antonialock** [comment]
Ok so can the old term change / or can we have a new term for 
abnormal cell cycle arrest in mitotic M phase with abnormal spindle
please Midori? cheers

**Comment by Antonialock** [comment]
i've put the session on my list to update so thi can be closed after that :)

**Comment by mah11** [comment]
I went for re-jigging the existing term, since it's not used for anything else.

**Comment by mah11** [comment]
edit file: 36a0132ad81c1ca6c58d5359cde67b290188929d
release: 26871d42eabe9730906d4a2e850f973d24f88ad8
