### ISSUE TITLE
normal length viable cell

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2585]
I could use 2 different things to describe this, but they are in different branches

1. normal vegetative length
2. viable vegetative cell with normal cell size

So I think the final annotation should be
viable vegetative cell with normal cell size

but is it possible to have a relationship which allows this to also be annotated to 
 normal vegetative cell length
viable vegetative cell with normal cell length.?

**Comment by mah11** [comment]
Is this a request for "viable vegetative cell with normal cell length"?

If "the final annotation should be viable vegetative cell with normal cell size" surely you would simply annotate to "viable vegetative cell with normal cell size" ...

**Comment by ValWood** [comment]
I would use 
"viable vegetative cell with normal cell size"
but most people only think about the length and not size so most of our terms are cell lenght related.

If I use 
"viable vegetative cell with normal cell size"
it won't be annotated to "normal cell length" with the current term arrangement.

**Comment by mah11** [comment]
I just want this question answered directly: Do you want me to add "viable vegetative cell with normal cell length"?

**Comment by mah11** [comment]
Terms with "size" in the names are defined as meaning, well, size (not restricted to length). If the definition is specific for length, the name will also use "length". It is therefore not accurate to say "most of our terms are cell length related".

**Comment by ValWood** [comment]
yes please, I think this will be more helpful for searching.

**Comment by ValWood** [comment]
What I mean is, people use  the words length and size interchangeably. People usually refer to length for mutants (because width doesn't vary) We know that If length is normal, overall size is usually normal and size is the correct term to use. However, having the  normal size annotations automatically annotated to the equivalent normal  length term will be helpful if you are searching. Most people won't realise that to find normal length they need to use "normal size".

**Comment by mah11** [comment]
> people use the words length and size interchangeably

I wish they knew better. Sigh. I cannot do something that sloppy in the ontology.

I can change "cell size" to "cell length" globally if you want. I will not use "size" in names and "length" in definitions, especially logical defs.

**Comment by ValWood** [comment]
That isn't what I was asking.

If there was a term
viable vegetative cell with normal cell length
with a relationship to 
viable vegetative cell with normal cell size
which allowed the annotations to propagate (I forget which relationship this would be has_part?)

Then anyone who wants  to search on "normal cell length" (and it maybe that they really are only interested in length) will find the correct annotations. I will annotate correctly to the size term.

**Comment by mah11** [comment]
Well, yes, normal cell size would have normal cell length as a part, but ...

We got rid of the has_part links in the "normal phenotype" branch because they caused a lot of term suggestions in Canto that you didn't want to see. We can't have it both ways; I can justify handling "normal" differently from "abnormal but I can't make a logical case for "some normal phenotypes can have has_part links but others can't".

Probably the only thing I could realistically do is add narrow "length" synonyms to "size" terms.

**Comment by ValWood** [comment]
OK I can't remember which relations we are following anymore.

related synonyms would be a good compromise.

**Comment by mah11** [comment]
synonyms added

edit file: b6f863a875ac7c9704d2ffe278d196a9a4e8b7de
release: 9154d65b31275615b2675821e618d59e667f3b83
