### ISSUE TITLE
ntr: transient arrest  during G1 phase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2586]

**Comment by ValWood** [comment]
PMID:1655416 

descendent of 
FYPO:0005097	abnormal cell cycle arrest in mitotic G1 phase

**Comment by mah11** [comment]
different from FYPO:0000333 mitotic G1/S transition delay? or should I add a synonym?

**Comment by ValWood** [comment]
that'll work!

**Comment by ValWood** [comment]
it would be good somehow if we knew that if the delay was transient we should be looking at the transition delay (I guess the synonyms will do that?).

**Comment by mah11** [comment]
synonyms added

edit file: b6f863a875ac7c9704d2ffe278d196a9a4e8b7de
release: 9154d65b31275615b2675821e618d59e667f3b83
