### ISSUE TITLE
mitotic cell cycle arrest phenotype

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2587]
I was looking fro a term for cell cycle arrest  with 2N DNA.

I  got mitotic cell cycle arrest phenotype, and none of the children fit, so I though the term mustn't exist.

![arrest_descendants](https://cloud.githubusercontent.com/assets/7359272/13600453/d320047a-e520-11e5-960e-0e3f027e49cb.jpg)

then I searched on 2N and found the term I wanted
abnormal mitotic cell cycle arrest with replicated DNA

so which term is it under here?  (I checked them all now I think, but they all seemed a bit wrong)

For this phenotype it is G2 arrest, but I'm not sure how you could be sure about that from the experiment. This could be just because I'm rubbish at reading flow cytometry data. Isn't it possible the cells could be in interphase  but not yet in anaphase, wouldn't that look the same as a G2/M transition block?

**Comment by mah11** [comment]
FYPO:0000444 is intended precisely for those cases where you know DNA is fully replicated but you can't nail it down any more specifically.

I'll have to have a closer look at links next time I'm doing ontology work - probably something I hoped would be reasoner-inferred isn't, so I'll review manually asserted links.

**Comment by ValWood** [comment]
similarly, I couldn't locate 
	abnormal cell cycle arrest in mitotic metaphase
under
mitotic cell cycle arrest phenotype

**Comment by mah11** [comment]
Added link 'abnormally arrested mitotic cell cycle progression' is_a 'mitotic cell cycle arrest phenotype' (FYPO:0000502 is_a FYPO:0004040), which will give FYPO:0000444 a path.

The second example already had a path to 'mitotic cell cycle arrest phenotype' via 'cell cycle arrest in mitotic interphase', but will now have another.

edit file: b6f863a875ac7c9704d2ffe278d196a9a4e8b7de
release: 9154d65b31275615b2675821e618d59e667f3b83
