### ISSUE TITLE
abnormal mitosis following normal mitosis

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2590]
Definition
A cellular process phenotype in which mitosis takes place abnormally after the cell has undergone a normal mitotic nuclear division and passed through the subsequent mitotic interphase.

Comment	This phenotype affects the second round of mitosis to take place after a mutation exerts its effect. For example, if a conditional mutant is shifted to restrictive conditions in G1 or S phase and the first mitosis thereafter is normal, but the second is not (even if cells are returned to permissive conditions in the second G1 or S phase), this term is applicable.

Comment	This phenotype affects the second round of mitosis to take place after a mutation exerts its effect. For example, if a conditional mutant is shifted to restrictive conditions in G2 phase and the first mitosis thereafter is normal, but the second is not (even if cells are returned to permissive conditions), this term is applicable.

I have changed it because I think the cells *have* to be synchronised and transferred to restrictive temparature in G2. They divide normally once because the problem only manifests once the cells have been through G1 or S. A problem is encountered which causes a problem with the subsequent division. If you restricted these cells in G1 or S in line with the current comment, you would see a different phenotype (because the problem would manifest earlier). The block has to be in  G2. A problem occurs in G1 or S, the phenotype does not manifest until the M phase after the cells have passed through the abnormal G1 or S-phase. I don't think I explained this properly before. Its quite a common cell cycle phenotype.

**Comment by ValWood** [comment]
e.g. 
In the paper I am doing now:

We have also shown that, when alp1- t1 cells are synchronized in G2 phase of the cell cycle and cells are then transferred to the restric- tive temperature, they divide normally once and lose their viability only during the second mito- sis (Grishchuk et al., 1998). By analogy with other fission yeast mutants with this cell cycle pheno- type, this result suggested that cofactor D may have some function in G1 or S phases of the cell cycle (Furuya et al., 1998; Saitoh et al., 1997).

PMID:19330768 

but it also occurs for unrelated processed like establishment of centromeric chromatin.Is established in G1 or S. If you move to restrictive temperature in G2, get one normal mitosis, because properly established. Next mitosis is compromised because the cells go through the abnormal G1/S and  don't establish chromatin properly. Defects in following mitosis. If you restricted in G1/S instead of G2 the defects would occur during the first mitosis instead (I think?).

**Comment by ValWood** [comment]
Although maybe you could see similar if you restricted in G1 if a protein was stable and took time to titrate or something....not sure, I just can't remember seeing this

**Comment by mah11** [comment]
Remember that the comments say "FOR EXAMPLE" and therefore do not pretend to cover every possible experimental design.

That said, it's not a lot of work to make the comments a bit less specific.

**Comment by ValWood** [comment]
I think broader would be better,  (mainly because the phenotype is usually observed with a G2 shift) so now i have another (related) problem.

I have the same allele, with different phenotypes depending when the termperature shift is done.
As predicted if the shift is during G1 this fails at the first mitosis,  to indicate that the problem is due to a requirement during G1:

Therefore, alp1-1315 cells die in the first mito- sis after the G1 phase synchronization, although they can divide normally once after the G2 phase synchronization. Similar behaviour was described for mutants in genes whose products have essential function in G1 phase, e.g. mis6-306 and mis4-242 (Furuya et al., 1998; Saitoh et al., 1997). There- fore, the above results were consistent with the notion that function of Alp1p was required dur- ing the G1 phase, and that failure to execute this function led to unequal chromosome segregation in the following mitosis.

However, I can't distinguish this because there isn't a way to indicate when the temperature shift took place.  I can only think to do this by having conditions
shift to non-permissive temperature in G1
shift to non-permissive temperature in G2

Would that be OK?

**Comment by mah11** [comment]
Yes, that has to be done with conditions.

**Comment by ValWood** [comment]
OK I'll   put that in a new ticket.

**Comment by mah11** [comment]
comments edited

edit file: b6f863a875ac7c9704d2ffe278d196a9a4e8b7de
release: 9154d65b31275615b2675821e618d59e667f3b83
