### ISSUE TITLE
ntr : conditions to reflect when Temperature Shift occurred

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2591]
shift to non-permissive temperature in G1
shift to non-permissive temperature in G2

**Comment by Antonialock** [comment]
I guess it is a block and release? 
Do you want to specify the type of block?
eg HU block and release into G2 at non-permissive temperature

**Comment by ValWood** [comment]
no release though....its to see how long the cells take to die when they t.s. at different time points.

bummer, can't remember which paper this was,

**Comment by Antonialock** [comment]
they must synchronize them somehow so that the  temperature block is at the specific cell cycle stage?

(if the mutant just stops dividing at a specific cell cycle phase without synchronization then it should be done as a phenotype..)

**Comment by ValWood** [comment]
Oh yes.  IIRK, they synchronised first with a ts block and release (but this  is background).

Than, they move to the restrictive temperature for the mutant they are *really* testing, and see where it dies. What I wanted to capture was that the 'point of death' depended where the TS shift was administered.

**Comment by mah11** [comment]
you mentioned PMID:19330768 in #2590

**Comment by ValWood** [comment]
thats the one. Will re-read tomorrow...

**Comment by ValWood** [comment]
I have the same thing in this paper,

PMID:9808627

its
unequal mitotic sister chromatid segregation following normal mitosis
if the block is in G2,
but palin
unequal mitotic sister chromatid segregation 
if the shift is in G1
(i.e needs to go through S-phase unmutated)

**Comment by Antonialock** [comment]
Hmm, I created 
id: PECO:0000292
name: nitrogen starvation at normal temperature and shift to high temperature in rich medium

for the G1 synch. For G2 synch they just elutriated the cells and then shited to high temp, so you can use the already existing high temperature condition.

However, I don't think I would annotate to two different phenotype terms with different conditions based on this. I haven't properly thought about it but does something happen during G1/S that cause trouble down the line? 

I don't think that's two different phenotypes observed in one population - it is the same phenotype? (i.e. cells go though G1/S, something goes wrong -> unequal chromosome seg in the following mitosis)

**Comment by mah11** [comment]
closing because it's ancient and hasn't had any updates in literally years
also not sure whether there was anything left to do for it ...
