### ISSUE TITLE
can't find term fr "loss of viability"

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2592]
I just can't think what to  use for 

"loss of viability"

I have "inviable population" but htat doesn't capture that there are a few generations before the cells die

**Comment by mah11** [comment]
There are a few terms with "loss of viability" in the names. Each also describes circumstances under which viability decreases.

**Comment by ValWood** [comment]
I saw those but there isn't one for just 'vegetative growth'

**Comment by Antonialock** [comment]
That sounds like a weird phenotype
Is it a conditional mutant? (like a ts mutant)?

If so then maybe there is enough protein around for a cell cycle (or two?) = normal growth
but then at, for example high temperature, translation may be affected and the population dies after a bit of growth because there is now no protein left
-> population inviability in the mutant is temporally delayed because there is initially some WT protein around

**Comment by ValWood** [comment]
exactly, its for things which live for a cycle or two, probably because its a stable protein, then die.
Its interesting to capture, because it explains a lot of other stuff.....

**Comment by mah11** [comment]
This isn't as straightforward as it might look. To add a term for "loss of viability during vegetative growth", I'll obviously have to define it. So: how is viability loss detected, and especially, how is it distinguished from decreased population growth?

With the existing "loss of viability" terms, the experiment can detect viability loss by growing a population under problem conditions, and then seeing how many viable colonies form after the problem goes away (e.g. upon returning to permissive temperature, restoring nutrients, etc.). For example:

id: FYPO:0000244
name: loss of viability upon nutrient depletion
def: "A cell population phenotype in which a smaller than normal proportion of the population remains viable when cells are deprived of nutrients such as carbon or nitrogen." [PomBase:mah]
comment: Use this term to annotate experiments in which a culture is grown under nutrient-depleted conditions, and then the number of cells viable enough to form a colony upon return to nutrient-replete conditions is measured and compared to wild type.

What's the equivalent when there's no change in conditions to reverse?

(Yes, the "loss of viability" terms do mix condition information in with "true" phenotype information. I haven't worked out a way round that without simply losing the terms entirely. Life is messy.)

**Comment by ValWood** [comment]
Hmm, I guess you can't normally easily distinguish between loss of viability and slow growth. The only reason that I can see here that its loss of viability is that all of the cells end up dead.

Is that the differentia?. Its slow growth if the population size doesn't increase, its loss of viability of the population size decreases (because they are dying faster than they are dividing).

**Comment by ValWood** [comment]
Damn it. I forgot to put the PMID again.
I'm not sure which paper it was as it doesn't see to be in approval.
  I don't think it was this one, but this would be an e.g.

alp1-1315, CFU

![loss](https://cloud.githubusercontent.com/assets/7359272/13805630/263521d0-eb4e-11e5-92bf-cb0868dfc945.jpg)

**Comment by ValWood** [comment]
I think it was this one
![17178839](https://cloud.githubusercontent.com/assets/7359272/13805783/48435386-eb4f-11e5-94d4-9fa9818916f3.jpg)

**Comment by Antonialock** [comment]
I would call that "loss of viability at high temperature"

**Comment by mah11** [comment]
me too

**Comment by ValWood** [comment]
durr of course!

**Comment by mah11** [comment]
sounds like we're good, then ;)

**Comment by ValWood** [comment]
PMID:19330768 note to self

**Comment by ValWood** [comment]
I'm reopening this because its a follow on.I now have a  mutant (OX) normal temperature, which displays no loss of viability.
Can I capture that? Other than
FYPO:0002060	viable vegetative cell population

The show that the growth is slow, but viability is unaffected?
These results showed that the conserved C-terminal fragment of separase induced the pointed nuclear chromatin accom- panying with certain inhibitory effects on growth but not the loss of cell viability.

(Maybe I  use penetrance or expressivity? not sure?)

**Comment by ValWood** [comment]
These results showed that the conserved C-terminal fragment of separase induced the pointed nuclear chromatin accompanying with certain inhibitory effects on growth but not the loss of cell viability.
12390246_cut1

(Its not terribly important that I capture this but I thought I would mention this separation because the growth and viability phenotypes in FYPO appear to be parent/child)

**Comment by ValWood** [comment]
That last comment might be nonsense. I was looking for examples I thought I saw, but I can't find any.

**Comment by mah11** [comment]
Roughly the same question as for loss of viability: how are they distinguishing population growth from viability? I could add a term for "normal cell population viability" defined as "same proportion of cells in the population stay alive under a given set of conditions as a wild type population" but to use it you need a way to tell how many cells are alive. That's easier when there's a change to adverse conditions that can be reversed.

I could also move population growth out from under population viability, but I bet you don't really want that, because then we would have to co-annotate "viable population" along with ("normal population growth" or "decreased population growth") and that would be a pain.

**Comment by ValWood** [comment]
Lets ignore. Its not important here.

but for future ref

The viability of cells in the liquid culture was meas- ured by plating (Fig. 2D, right panel) and found to be high for cells overproducing the C-fragment (Cut1C).
A quantitative analysis of the cell number increase, however, suggested that cells producing the C-fragment (Cut1C) grew slower (the generation time was roughly twice as long than cells carrying the vector plasmid, left panel).

![viability](https://cloud.githubusercontent.com/assets/7359272/14279079/035164f0-fb23-11e5-924c-c1920e98aec8.jpg)

**Comment by mah11** [comment]
another angle, for future reference:

I've just curated some from PMID:9826747 where they counted how many cells they plated, and then counted colonies. I did it as "inviable veg cell" with penetrance at (100% - colony-forming %). Not only did that save me adding a potentially awkward new term, it dodges the fact that there's no way to tell when the non-colony-forming cells died.
