### ISSUE TITLE
inviable elongated mononucleate aseptate vegetative cell with cell cycle arrest in mitotic M phase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2594]
should
inviable elongated mononucleate aseptate vegetative cell with cell cycle arrest in mitotic M phase

be
inviable elongated mononucleate aseptate vegetative cell with cell cycle arrest in mitotic metaphase

(if it has a single nucleus it must be still in metaphase?)

**Comment by mah11** [comment]
I would've thought arrest could be in prophase (or at least that it could be tough to tell)

**Comment by ValWood** [comment]
OK  good point. So for when we can be more precise....

inviable elongated mononucleate aseptate vegetative cell with cell cycle arrest in mitotic metaphase phase

(I'm trying to gather the metaphase arrest ones, and this one is definitely metaphase, I can see the separated spindle poles). These terms will be also be  useful because historically 'elongated' was used to infer a block at G2/M but a lot of them are clearly later (so probably a G2/M delay plus a metaphase block).....

**Comment by mah11** [comment]
inviable elongated mononucleate aseptate vegetative cell with cell cycle arrest in mitotic metaphase FYPO:0005321

edit file: b6f863a875ac7c9704d2ffe278d196a9a4e8b7de
release: 9154d65b31275615b2675821e618d59e667f3b83

**Comment by ValWood** [comment]
Grr, crap .....why can't I remember to put the PMID!
