### ISSUE TITLE
add synonym: abnormal cell cycle arrest with unseparated condensed chromosomes

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2595]
add synonym
abnormal cell cycle arrest with unseparated condensed chromosomes

to
abnormal cell cycle arrest in mitotic metaphase

**Comment by mah11** [comment]
related synonym added (chromsomes are also condensed for at least part of prophase)

edit file: b6f863a875ac7c9704d2ffe278d196a9a4e8b7de
release: 9154d65b31275615b2675821e618d59e667f3b83
