### ISSUE TITLE
check parent decreased cell cycle arrest in mitotic G1 phase in response to nitrogen starvation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2600]
a gp annotated to
	decreased cell cycle arrest in mitotic G1 phase in response to nitrogen starvation

isn't annotated to
abnormal mitotic cell cycle ( but has abnormal cell cycle)
is parentage OK?

**Comment by ValWood** [comment]
and
increased cell cycle arrest in mitotic G1 phase in response to nitrogen starvation

**Comment by ValWood** [comment]
and
	inviable after spore germination, without cell division, cell cycle arrest, elongated cell
	multiseptate vegetative cell (I presume this would have via abnormal mitotic cytokinesis)
delayed onset of cell cycle arrest in mitotic G1 phase in response to nitrogen starvation

**Comment by mah11** [comment]
For arrest in N starvation, I've moved an ancestor so increased/decreased/etc. get a path to abnormal mitotic cell cycle.

For the other one, I'd been meaning to add more has_part links to a lot of terms in the "inviable after spore germination" branch, so this has prodded me to actually raise the priority and do it.

**Comment by mah11** [comment]
edit file: ff3e9860357968565ed1b0e47aceb8a9eae9037e
release: 2a233340de4d8d1af6a2ca8804da4f72e0aa4646
