### ISSUE TITLE
ntr: spindle elongation PMID:19686686

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2606]
normal rate of spindle elongation during anaphase B
decreased rate of spindle elongation during anaphase B
PMID:19686686

**Comment by mah11** [comment]
normal rate of mitotic spindle elongation during anaphase B FYPO:0005342
  decreased rate of mitotic spindle elongation during anaphase B FYPO:0005343

**Comment by mah11** [comment]
edit file: 36a0132ad81c1ca6c58d5359cde67b290188929d
release: 26871d42eabe9730906d4a2e850f973d24f88ad8
