### ISSUE TITLE
Query, could these mitotic spindle terms be the same?

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2607]
FYPO:0000276 - monopolar mitotic spindle (fission_yeast_phenotype) [BioPortal]

Definition: "A physical cellular phenotype in which the mitotic spindle forms with microtubules emanating from only one pole." [PMID:11792803, PMID:9763447]

and
FYPO_ID(FYPO:0001683 - abolished mitotic spindle assembly)
 "A cell phenotype in which mitotic spindle assembly does not occur." 

If you have a monopolar spindle, spindle assembly has not occurred?

**Comment by mah11** [comment]
This makes no sense. If you see a monopolar spindle, you can conclude that spindle assembly has not gone normally, but if no spindle assembly occurred at all, there wouldn't be anything identifiable as a spindle at all.

**Comment by ValWood** [comment]
Also the sibling of 
FYPO_ID(FYPO:0001683 - abolished mitotic spindle assembly)



Ah OK,
abolished spindle midzone assembly = FYPO:0000276 - monopolar mitotic spindle

**Comment by mah11** [comment]
added
abolished mitotic spindle midzone assembly FYPO:0005344

and made monopolar mitotic spindle output_of FYPO:0005344

**Comment by mah11** [comment]
edit file: 36a0132ad81c1ca6c58d5359cde67b290188929d
release: 26871d42eabe9730906d4a2e850f973d24f88ad8
