### ISSUE TITLE
ntr: mitotic sister chromatid separation in interphase 	PMID:9808627

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2608]
FYPO:0000670	abnormal mitotic sister chromatid separation

	PMID:9808627
A cellular process phenotype in which mitotic sister chromatid separation occurs prematurely in interphase (before spindle formation). Mitotic sister chromatid separation is the process in which sister chromatids are physically detached from each other during mitosis.

Comment: "Note that these interphase cells revealing the two split signals did not contain the spindle at all, so that separation was not attributable to the spindle force."
This phenotype is usually a cohesion defect.

**Comment by mah11** [comment]
mitotic sister chromatid separation during interphase FYPO:0005345

**Comment by mah11** [comment]
edit file: 36a0132ad81c1ca6c58d5359cde67b290188929d
release: 26871d42eabe9730906d4a2e850f973d24f88ad8

**Comment by ValWood** [comment]
does not appear as descendant of "abnormal mitotic sister chromatid separation" my placeholder term. Should it?

**Comment by mah11** [comment]
fixed by amending an asserted link further up-tree
