### ISSUE TITLE
add synonym to normal RNA level

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2610]
normal transcript level.

Only because I can't believe how long I just spent looking for it (doesn't come up in any of suggestions)

**Comment by mah11** [comment]
added "transcript" synonyms to any and all "RNA level" terms that didn't already have 'em

**Comment by mah11** [comment]
edit file: 36a0132ad81c1ca6c58d5359cde67b290188929d
release: 26871d42eabe9730906d4a2e850f973d24f88ad8
