### ISSUE TITLE
ntr: abolished localization to cytoplasm in interphase PMID:9635190 summary

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2611]
ntr: abolished localization to cytoplasm during mitotic interphase
synonym: abolished cytoplasmic retention during mitotic interphase

child of
abolished protein localization during vegetative growth

A cell phenotype in which a protein which normally localizes to the cytoplasm during mitotic interphase is localised to the nucleus.

Comment	If this term is used, we recommend noting which protein(s) were used in the assay.

**Comment by mah11** [comment]
abolished protein localization to cortical microtubule cytoskeleton during vegetative growth FYPO:0005346

**Comment by mah11** [comment]
edit file: 653f4b9a27d3fcabf1d06845eeb5caab64d1d108
release: 21dbe123051bc992f88e2e2f9cc898264ea4e28d
