### ISSUE TITLE
ntr:  pointed nucleus during mitotic cell cycle PMID:12390246

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2612]
term: pointed nucleus during mitotic interphase
def
A physical cellular phenotype observed in  which the mitotic interphase nucleus is " pointed". 
The tip of the pointed nuclear chromatin is associated with the SPB.

(Good luck modelling that one!)
Comment: might also be described as "pointed nuclear chromatin"

(maybe this should be the primary phenotype with has_output ?)

child of
FYPO:0000062 abnormal nuclear morphology during vegetative growth
(add synonym "deformed nucleus" to this term?

**Comment by ValWood** [comment]
![pointed_nucleus](https://cloud.githubusercontent.com/assets/7359272/14277317/a2a25392-fb1a-11e5-8193-e9eec1d1b007.jpg)

cut1 C-term OX in  PMID:12390246

**Comment by mah11** [comment]
pointed nucleus during mitotic interphase FYPO:0005347

**Comment by mah11** [comment]
edit file: 653f4b9a27d3fcabf1d06845eeb5caab64d1d108
release: 21dbe123051bc992f88e2e2f9cc898264ea4e28d
