### ISSUE TITLE
ntr: increased mitotic spindle pole body movement PMID:12390246

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2613]
ntr: increased mitotic spindle pole body movement
synonym:  increased mitotic spindle pole body oscillation

See PMID:12390246
In cells overproducing the C-fragment, the SPB rapidly moved back and forth (schematized cell shape is illustrated in Fig. 4A). 

Descendant of
FYPO:0000534	abnormal spindle pole body localization?

**Comment by mah11** [comment]
Is this kind of movement a thing that happens at all in wild type? If not, it sounds like it would fit under abnormal maintenance of SPB localization (which would be another new term; note to self, TGFF a GO term).

**Comment by ValWood** [comment]
I think it is normal for the SPB to oscilalte slightly. 
because they say

" In control cells not overproducing the Cut1 C-fragment, the movement of SPB was found to be restricted within a small space, as reported previously (Tran et al. 2001; see Discussion)."

But I never came across it before, I have first seen it mentioned in this paper......
(I hope I didn't do the Tran paper already, because if I did, I missed it)

**Comment by mah11** [comment]
I don't suppose the SPB has to be totally static for the mutant phenotype to qualify as a problem with maintaining SPB localization. Does that sound sensible?

**Comment by ValWood** [comment]
I thought I would check what GO does for movement.
Hmpph.
There are lots of movemnt terms, these aren't localization. Not sure if they should be.
But I found this:

GO:0006928 movement of cell or subcellular component
maybe could make a child
-movement of subcellular component

Would that help?

**Comment by mah11** [comment]
no; I think a small amount of wiggle is still consistent with maintaining localization of a component in a place, and that's not happening to the same extent for the SPB in the mutant as in wild type

**Comment by ValWood** [comment]
OK

**Comment by mah11** [comment]
abnormal maintenance of spindle pole body localization FYPO:0005348
  increased mitotic spindle pole body movement FYPO:0005239

**Comment by mah11** [comment]
edit file: 653f4b9a27d3fcabf1d06845eeb5caab64d1d108
release: 21dbe123051bc992f88e2e2f9cc898264ea4e28d
