### ISSUE TITLE
ntr? possibly? chromatin phenotype PMID:16453724

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2614]
I don't know how to describe it, but I think I have seen it before...

Its described as "Ring", describing the chromatin organization

![top2](https://cloud.githubusercontent.com/assets/7359272/14282444/4a113a92-fb36-11e5-9f34-4366f11bb3c3.jpg)

![ring](https://cloud.githubusercontent.com/assets/7359272/14282473/72d3091a-fb36-11e5-9c19-19db2278a8dc.jpg)

It isn't curated in   curs/b2369c57c9545f6d/ro/
which is the cited paper

**Comment by ValWood** [comment]
Found the term I was thinking of, but here its not only nucleolar?

FYPO:0004506	abnormal nucleolar chromatin organization resulting in peripheral chromatin distribution

**Comment by ValWood** [comment]
The only other annotation is arc1 this paper
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2290841/figure/fig6/
Is it a  phenotype of nuc1632 as well?

**Comment by mah11** [comment]
FYPO:0004506 (added in #2122) mentions nucleolar chromatin specifically because of all the stuff in PMID:18362178 saying that Nuc1 specifically associates with rDNA, so that's what they're following in the figure 6 (and yep, looks similar in both mutants).

It won't be any trouble to add a similar term that's chromatin-generic.

**Comment by ValWood** [comment]
OK, please.
I thought it was there somewhere.
Can we add a 'ring' related synonym too?

**Comment by mah11** [comment]
abnormal chromatin organization resulting in peripheral chromatin distribution FYPO:0005350
synonyms include: abnormal chromatin organization resulting in ring-shaped chromatin distribution

**Comment by mah11** [comment]
edit file: 653f4b9a27d3fcabf1d06845eeb5caab64d1d108
release: 21dbe123051bc992f88e2e2f9cc898264ea4e28d
