### ISSUE TITLE
TPV possibly , lagging chromosomes

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2617]
Not sure about this but is lagging chromosomes a separation defect? (it sounds like a segregation defect rather than separation).

A cellular process phenotype observed in the vegetative growth phase of the life cycle in which sister chromatids do not move towards the spindle poles at the same time during mitosis, but instead one or more chromosomes remain distant from the spindle pole after the bulk of the DNA has separated. Mitotic sister chromatid segregation may stop before completing separation of chromosomes, or may eventually be completed.

**Comment by mah11** [comment]
fixed

**Comment by mah11** [comment]
edit file: 653f4b9a27d3fcabf1d06845eeb5caab64d1d108
release: 21dbe123051bc992f88e2e2f9cc898264ea4e28d
