### ISSUE TITLE
ntr: mitotic M-phase arrest with rereplication

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2618]
ntr: mitotic M-phase arrest with rereplication
A cellular process phenotype in which progression through the mitotic cell cycle is arrested in M phase under conditions where arrest does not normally occur, and  although cytokinesis does not take place, DNA re-replicates resulting in an enlarged nucleus.

child of
FYPO:0003172 abnormal cell cycle arrest in mitotic M phase without septation?
FYPO:0000158 DNA content increased during vegetative growth
FYPO:0000344  enlarged nucleus during vegetative growth

I'm not sure all of this is logically correct but we'll see how it pans out when the "is this stuck in M-phase" problem is sorted.
No hurry.

**Comment by mah11** [comment]
Yeah, this is a nasty one. It feels dodgy to call it M phase with replication happening. If DNA replicates, one could argue that the cell is in S phase ... or more likely, all wild-type-based phase designations are off.

**Comment by ValWood** [comment]
Well in pombe S-phase begins before cytokinesis is complete so all phase designations are also off in WT too in that case!

**Comment by mah11** [comment]
GO defines M phase as the phase when nuclear division takes place, saying nothing about cytokinesis (possibly to accommodate pombe, tho I don't remember precisely).

**Comment by mah11** [comment]
oh yeah, also to accommodate situations where cytokinesis doesn't normally happen (e.g. insect first ~13 rounds of division; any other instances of GO:0000769 ...)

**Comment by ValWood** [comment]
Next paper says:

DNA synthesis is normally dependent on a cell having
previously gone through mitosis. Hirano et al.
(1986), however, found that DNA synthesis continued
at the restrictive temperature in the double mutant
cutl cdcll of Schizosaccharomyces pombe even
though mitosis was blocked in some of the cells. 

PMID:2229195
which sounds like we can call it M-phase arrest
but will keep thinking.

**Comment by mah11** [comment]
The stuff in #2850 seems to supersede this - now we seem to be thinking we would only call something M phase arrest if everything stops in an M phase that otherwise appears/appeared normal.
