### ISSUE TITLE
normal attachment of mitotic spindle microtubules to kinetochore PMID:18262494

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2620]
child of
FYPO:0003570	normal attachment of spindle microtubules to kinetochore

standard def

**Comment by mah11** [comment]
normal attachment of mitotic spindle microtubules to kinetochore FYPO:0005352

**Comment by mah11** [comment]
edit file: 653f4b9a27d3fcabf1d06845eeb5caab64d1d108
release: 21dbe123051bc992f88e2e2f9cc898264ea4e28d
