### ISSUE TITLE
ntr: decreased mitotic spindle intra-nuclear microtubule depolymerization during chromosome recapture

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2621]
chromosome recapture:

ntr: decreased mitotic spindle intra-nuclear microtubule depolymerization during chromosome recapture
PMID:18256284

id: GO:1990942
name: mitotic metaphase chromosome recapture
namespace: biological_process
def: "A mechanism to recapture 'lost' chromosomes (chromosomes which have become detached from the spindle) during metaphase of mitotic chromosome segregation. Chromosomes with unattached kinetochores are migrated along (non polar) spindle microtubules to the mitotic spindle pole body by a combination of microtubule depolymerisation and 'kinetochore sliding' (migration of the chromosome along the microtubule). The chromosome subsequently migrates along the polar spindle microtubule to the metaphase plate." [PMID:18256284]
subset: termgenie_unvetted
synonym: "kinetochore retrieval" EXACT []
synonym: "metaphase chromosome retrieval to the spindle pole body" EXACT []
synonym: "sister kinetochore recapture" EXACT []
is_a: GO:0051303 ! establishment of chromosome localization
relationship: part_of GO:0007080 ! mitotic metaphase plate congression

**Comment by mah11** [comment]
"intra-nuclear" is spurious here, isn't it?

**Comment by ValWood** [comment]
ntr:  decreased kinetochore sliding during mitiotic metaphase chromosome recapture

**Comment by ValWood** [comment]
mmmmmm  "intra-nuclear" is spurious here, isn't it?

Its a bit horrible. 
There are non nuclear spindle microtubules (astral ones) which  go into the cytoplasm from the SPB.
I can't figure out which microtubules these are.  The aren't polar microtubules.

They aren't kinetochore microtubules at this point because they are unattached, and then they depolymerise:

![schematic](https://cloud.githubusercontent.com/assets/7359272/14321553/9a7e623a-fc11-11e5-9345-57100e9c5fa8.jpg)

**Comment by ValWood** [comment]
I think they are a type of kinetochore microtubule. At least it doesn't seem wrong to call them that (they do become attached to kinetochores, even if they are not the same ones which subsequently align the chromsomes at the metaphase plate.....
![kinetochore](https://cloud.githubusercontent.com/assets/7359272/14321649/072b163a-fc12-11e5-8981-60864d759d49.jpg)

**Comment by mah11** [comment]
I would've thought the astral MTs wouldn't get involved in kinetochore capture or recapture, but I'm still not an expert.

Anyway, as a language thing we can say "nuclear" rather than "intra-nuclear" - less clunky, and consistent with GO CC names for MT terms.

**Comment by mah11** [comment]
oh, and do you want "during" or "after" in the term name? ticket summary says one thing, body has the other

**Comment by ValWood** [comment]
>I would've thought the astral MTs wouldn't get involved in kinetochore capture or recapture, but I'm still not an expert.

Correct (I thought you were saying that all spindle microtubules were nuclear)

>Anyway, as a language thing we can say "nuclear" rather than "intra-nuclear" - less clunky, and consistent with GO CC names for MT terms.

I want to make it clear it isn't the polar microtubules....(I think we can call them kinetochore)

>oh, and do you want "during" or "after" in the term name? ticket summary says one thing, body has the other

Sorry was trying to edit all to 'during' will finish

**Comment by ValWood** [comment]
I also need
decreased rate of  kinetochore sliding during chromosome recapture

both 
 decrease the rate of chromosome migration (along kinetochore microtubule) to spindle pole body  during chromosome recapture

**Comment by ValWood** [comment]
And for some mutants 

abolished migration (along kinetochore microtubule) to spindle pole body during chromosome recapture

**Comment by mah11** [comment]
> abolished migration (along kinetochore microtubule) to spindle pole body during chromosome recapture

migration of what? a chromosome?

**Comment by Antonialock** [comment]
does "chromosome recapture" happen as part of GO:0072766 centromere clustering at the nuclear envelope ?

**Comment by Antonialock** [comment]
i.e. is it an iterative process to get the centromeres clustered, or do things sometimes go wrong and then they need to be "reclustered"?

**Comment by ValWood** [comment]
No that's something else.....
This is when chromsomes are aligning at the metaphase plate but become detached from the  SPB/microtubules.

**Comment by ValWood** [comment]
GO:0072766 is in interphase...

**Comment by mah11** [comment]
I hope these will be the last questions before I add terms:

1) Are these all of the term requests?

a) decreased kinetochore microtubule depolymerization during mitotic metaphase chromosome recapture
b) decreased rate of kinetochore sliding during chromosome recapture
c) abolished migration of chromosome (along kinetochore microtubule) to spindle pole body during chromosome recapture

2) Are there GO terms for the parts of recapture (and are they MT depolymerization and "kinetochore sliding")? If not, do you plan to request them?

3) Do "kinetochore sliding", "kinetochore migration", and "chromosome migration" all refer to the same thing in this context? If so, which do you want in term names? I WILL use the same text for ( b ) and ( c ) unless they're actually different, and put the other wordings in synonyms. If they're not the same, how are the differences defined?

**Comment by ValWood** [comment]
1. Those are the 3 terms I need.
2. I didn't request GO terms for the parts of recapture. I was planning just to capture that part as phenotypes and annotated to
name: mitotic metaphase chromosome recapture
3. Yes all the same in this context. They are used interchangeably. Its usually called "kinetochore sliding" which is a bit misleading becuse it is the entire chromosome, but lets stick with that.

I don't know if I made it clear (possibly not), there appear to be 2 mechanisms for chromosome movement at this point, one via sliding and one via depolymerization via end on attachment. I wanted to capture the phenotypes but I didn't think it was appropriate to request GO terms until its a bit more fleshed out (from other papers I have read sound like the same 2 types of migration  also  occur  during normal congression, not only when chromsomes are lost, so it was difficult for me to figure out exactly how these should be placed in GO right now....).

**Comment by mah11** [comment]
Shiny new terms:

  abnormal mitotic metaphase chromosome recapture FYPO:0005362
  decreased kinetochore microtubule depolymerization during mitotic metaphase chromosome recapture FYPO:0005363
  decreased rate of kinetochore sliding during chromosome recapture FYPO:0005364
  abolished kinetochore sliding during chromosome recapture FYPO:0005365

They've got a ton of synonyms, especially the "sliding" terms, and I can add even more if they'd help.

**Comment by mah11** [comment]
oops, should've closed this y'day
edit file: 76449529e5d827a31f0be4a85e357c1d2d46ed78
release: e5283ec1c96a63ba40deabd933a78b358133e2b5
