### ISSUE TITLE
ntr: inviable  mononucleate aseptate vegetative cell with cell cycle arrest in mitotic G2 phase PMID:15507118

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2624]
15507118

inviable  mononucleate aseptate vegetative cell with cell cycle arrest in mitotic G2 phase

orc5

**Comment by mah11** [comment]
inviable mononucleate aseptate vegetative cell with cell cycle arrest in mitotic G2 phase FYPO:0005367

**Comment by mah11** [comment]
edit file: 76449529e5d827a31f0be4a85e357c1d2d46ed78
release: e5283ec1c96a63ba40deabd933a78b358133e2b5
