### ISSUE TITLE
expected links missing (ontology or canto?)

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2625]
Small vegetative cell children

![no small viable](https://cloud.githubusercontent.com/assets/7359272/14359072/bb7b68b2-fce7-11e5-99c6-cc248b2263b3.jpg)

no viable/inviable etc

**Comment by mah11** [comment]
drat, I'll have to investigate why the reasoner doesn't infer more.

**Comment by ValWood** [comment]
possibly related

	abolished mitotic spindle midzone assembly
not a descendant of 
	abolished  spindle midzone assembly

**Comment by mah11** [comment]
midzone assembly terms have nothing to do with the small cell terms (but that link is easy to add)

**Comment by ValWood** [comment]
OK I though it might be a connected reasoner problem affecting a specific relation.
Do you want a separate ticket? (needs link)

**Comment by mah11** [comment]
A separate ticket might have made more sense in the first place, but now that it's in here, don't bother.

**Comment by mah11** [comment]
changed some xps to use more specific term

**Comment by mah11** [comment]
edit file: 76449529e5d827a31f0be4a85e357c1d2d46ed78
release: e5283ec1c96a63ba40deabd933a78b358133e2b5
