### ISSUE TITLE
ntr: abolished protein cleavage PMID:16483313

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2634]
back on the cuts...

(for abolished cleavage of rad21, cohesin, by saparase)

I can't use abolished processing, cos its not maturation.

PMID:16483313

**Comment by mah11** [comment]
Is there a specific term in the relevant GO branch we can use, or will it have to point directly to the generic "proteolysis" (GO:0006508)?

**Comment by mah11** [comment]
answer (meeting chat): just use proteolysis

**Comment by mah11** [comment]
abnormal proteolysis FYPO:0005376
  abolished proteolysis during vegetative growth FYPO:0005377

"cleavage" in narrow synonyms

**Comment by mah11** [comment]
edit file: 5f36967d7cb5b61e4a6211eb22979c7f1be12d30
release: b8e8e14d27cdadda3688d067256838564a118a90
