### ISSUE TITLE
ntr: PMID:11102508 abnormal f-actin/actin patch localization

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2635]
A cell phenotype  during interphase when the actin patches are localized to a single cell tip (instead of both)

(Used to indicate loss of bipolarity)

Not sure where this should go?

**Comment by ValWood** [comment]
I found it...
	monopolar actin cortical patch localization

I got stuck in "abnormal actin cable localization" and was going to request a sibling.
Maybe we should have a grouping term for "abnormal actin localization"

**Comment by mah11** [comment]
Neither GO nor FYPO has any terms with "actin cable localization". There are localization terms in GO only for actin cortical patches. The rest of the actin cytoskeleton structures, including actin filament bundles/cables, just have the standard organization/assembly/disassembly terms. So the grouping term in FYPO is "abnormal actin cytoskeleton organization". I can add a related synonym if it'll help.

**Comment by ValWood** [comment]
I think I meant  to type "actin filament localization"

**Comment by mah11** [comment]
no such term as that in FYPO; exists as a narrow synonym in GO

**Comment by mah11** [comment]
i.e. it still comes back to "actin X organization"; I can add synonyms but separate terms would be inconsistent with GO

**Comment by ValWood** [comment]
I think it was this term:
abnormal actin cable distribution
presumable a localization term?

**Comment by mah11** [comment]
points to GO:0070650, which is is_a GO:0061572 ! actin filament bundle organization

**Comment by mah11** [comment]
added a pile of synonyms

**Comment by mah11** [comment]
edit file: 5f36967d7cb5b61e4a6211eb22979c7f1be12d30
release: b8e8e14d27cdadda3688d067256838564a118a90
