### ISSUE TITLE
spindle defects PMID:11102508

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2636]
Was looking for  "bent, V-shaped spindle" under mitotic spindle defects and couldn't see it.
Found under bipolar spindle defects.
I wasn't sure if that was correct, and seems to be confirmed by

 "however, these cells contained disproportionally large numbers of V-, star-, or fan- shaped spindles, anomalies that were rarely detectable at 30°C (Figure 5, A and B). We have evidence (below) that these spindles are monopolar. "

![spindles](https://cloud.githubusercontent.com/assets/7359272/14672526/45529166-06f0-11e6-8b91-45e82f96ff6b.jpg)

**Comment by ValWood** [comment]
I think "abnormal mitotic spindle morphology" might help for locating too....
(there is a "abnormal spindle morphology" but I came in below that.

**Comment by ValWood** [comment]
I need a term to describe the "star or fan shaped monopole spindle (see above)
AND
The  very long monopolar spindle

**Comment by ValWood** [comment]
I got to the "bit below"
"As described above, moe1􏰍 mal3􏰍 cells contained a large number of cells with a V-, fan-, or star-shaped spindle. We double-stained these cells to view the spindle and the SPB at the same time and found that  most of these abnormal spin- dles (􏰅85%) were nucleated from only one of the SPBs (Figure 7, A and B). This result indicates that these abnormal spindles are monopolar. "

**Comment by ValWood** [comment]
Onle the "V" and "star" ones
In contrast, despite their excessive length, the abnormally long S-shaped spindles are bipolar, as evidenced by the presence of two SPBs of equal size attached to the ends of the spindle (Figure 7A).

**Comment by ValWood** [comment]
I remembered what the 'thing' was !

I *think* there are 2 phenotypes which manifest 'V' shaped  spindles.

The first ones are in metaphase, like this one, when the spindle  is monpolar.

I think you see a 'larger' V shaped, bent spindle later, after anaphase spindle elongation. I seem to recollect these being described as 'broken' spindle. I think there might be some constraint, maybe the nucleus doesn't divide and the spindle continues to try  elongate but breaks. I would need to go back to look at these phenotypes, so I'll do that this week to see if I can separate them. Maybe they really are all like this one....

**Comment by mah11** [comment]
> I remembered what the 'thing' was !

Woohoo!

And OK, I guess the best approach depends on whether there are both monopolar and bipolar V-shaped spindles.

The FYPO:0001978 definition cites a couple of papers that show diagrams with two spindle poles, but with the MTs from each pole meeting at an acute angle. They're old papers, and I'm not sure how much of the diagram was speculation as opposed to clear results. If need be, I can change its name to "bent bipolar mitotic spindle"; the "V-shaped" synonym already specifies bipolar.

If there are both monopolar and bipolar V-shapes, then FYPO:0001978 is OK apart from the name change, and I'll add generic and monopolar terms. If the old model was pure speculation, and now known to be wrong (i.e. there are no bipolar Vs) I can rejig FYPO:0001978 itself.

**Comment by mah11** [comment]
p.s. will be easy enough to add the terms for star- and fan-shaped, and a grouping "abnormal mitotic spindle morphology", but I'll wait until you know what's up with V shapes so I can do it all in one go.

**Comment by ValWood** [comment]
OK it fine as it is I think. There are only 3 annotation. I checked them:

sim3
Star or V-shaped spindles were seen frequently in sim3 mutants, which may indicate defects in the organization of a bipolar spindle.
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2172903/figure/fig2/
problem is in anaphase, possibly interdigitated spindle collapses?

spc7 (this looks a bit different ?)
 elongating anaphase spindles that were bent (Figure 5Ae),
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1924829/figure/F5/

cut7
required for half spindle interdigitation (I think this is like sim3)
![schematic from cut7 paper](https://cloud.githubusercontent.com/assets/7359272/16085981/d6d9c0f4-3315-11e6-9695-cc577c93e0a7.jpg)

They do look slightly  different, but they all seem to be  anaphase defects , probably where the spindle collapses to look like a mono polar spindle, so they are , effectively a defect in bipolar spindle formation.....Have a look and see what you think. Actually I don't know what my problem was....

**Comment by mah11** [comment]
I think you must have been worried that some of the V-shaped spindles only had one pole. But if they're all bipolar then the existing term for V-shaped is ok.

Also, do you still want terms for star-shaped and fan-shaped?

**Comment by ValWood** [comment]
I think for now I can just use 'bent'.

Although spc7 looks quite different ( like a bow), maybe this one should be 'curved'
Perhaps this is earlier before the interdigitation 'breaks'

**Comment by mah11** [comment]
OK. Might be simplest to close this and do a new ticket if you want a new term to distinguish 'bent' from 'curved'.
