### ISSUE TITLE
NTR: gamma tubulin complex is localization PMID:11102508

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2638]
I want to represent a phenotype where the gamma tubulin complex is localized  to only one instead of both spinlde pole bodies

abnormal gamma-tubulin complex localization to a single  mitotic spindle pole body

child of 
abnormal gamma-tubulin complex localization to mitotic spindle pole body

and
abnormal asymmetric protein localization to old or new mitotic spindle pole body

**Comment by ValWood** [comment]
Oh it seems  not
abnormal asymmetric protein localization to old or new mitotic spindle pole body

this is for things which *should* be asymmetrically localized but aren't.
This one is but shouldn't be

**Comment by mah11** [comment]
asymmetric gamma-tubulin complex localization to single mitotic spindle pole body FYPO:0005381
(with various synonyms)

**Comment by mah11** [comment]
p.s. I have added this synonym to FYPO:0001874:
"abnormal occurrence of normally asymmetric protein localization to old or new mitotic spindle pole body"

I sincerely hope the synonym will be enough to avoid confusion, and we don't have to start using that as the term name!

**Comment by mah11** [comment]
edit file: 5f36967d7cb5b61e4a6211eb22979c7f1be12d30
release: b8e8e14d27cdadda3688d067256838564a118a90
