### ISSUE TITLE
ensure that 'normal protein degradation' has assayed_using extension option

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2639]
I spotted that 

normal protein degradation during vegetative growth

had no "assayed using" prompt

Will let you add if necessary as it will need to be higher up the graph than this?

**Comment by mah11** [comment]
asserted a link that should sort it (FYPO:0002799 is_a FYPO:0004849)

**Comment by mah11** [comment]
edit file: 5f36967d7cb5b61e4a6211eb22979c7f1be12d30
release: b8e8e14d27cdadda3688d067256838564a118a90
