### ISSUE TITLE
ntr: delayed exit from meiosis

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2640]
"Thus neither Ste9, Fzr2, nor Fzr3 appears to be involved in the transition between meiosis I and meiosis II, although they might partially or redundantly contribute to the exit from meiosis."

data in  (Figure 1B) supports this "slight delay at the end of meiosis"

**Comment by mah11** [comment]
There isn't a GO term for "exit from meiosis". Should we request one (analogous to GO:0010458 exit from mitosis) or should I model the phenotype as "increased duration of meiosis" (or increased duration of meiotic telophase, under FYPO:0002220)?

**Comment by ValWood** [comment]
Term]
id: GO:1990947
name: exit from meiosis
namespace: biological_process
def: "Any process involved in the progression from anaphase/telophase of meiosis II to G1 of mitosis." [PMID:212917197]
subset: termgenie_unvetted
is_a: GO:0044771 ! meiotic cell cycle phase transition

**Comment by mah11** [comment]
delayed exit from meiosis FYPO:0005382

**Comment by mah11** [comment]
edit file: 5f36967d7cb5b61e4a6211eb22979c7f1be12d30
release: b8e8e14d27cdadda3688d067256838564a118a90
