### ISSUE TITLE
delayed onset of meiotic anaphase I

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2642]
synonym delayed metaphase/anaphase I transition

PMID:21389117

**Comment by mah11** [comment]
The mitotic equivalent is "mitotic metaphase/anaphase transition delay" (FYPO:0000324{, so I'll do meiotic terms the same way, and make sure synonyms are also consistent.

**Comment by ValWood** [comment]
abolished meiotic metaphase/anaphase I transition,
	

descendant of FYPO:0003378	abolished meiosis I

**Comment by mah11** [comment]
Is there a difference between an abolished metaphase/anaphase transition and arrest in metaphase?

Whether there is or not, can't put the abolished transition (or arresT) term under abolished meiosis I because FYPO:0003378 mean that none of meiosis I happens.

**Comment by ValWood** [comment]
OK, wasn't sure about that either....

**Comment by mah11** [comment]
hm, still need to know whether the new term should be arrest or abolished transition (and whether there's any difference)

**Comment by mah11** [comment]
meeting chat: agreed to model meiosis (+ I & II) terms on mitotic arrest term (FYPO:0000392), and add "abolished transition" synonyms to lots of arrest terms

**Comment by mah11** [comment]
meiosis I metaphase/anaphase transition delay FYPO:0005384
  abnormal cell cycle arrest in metaphase of meiosis I FYPO:0005385

**Comment by mah11** [comment]
edit file: 5f36967d7cb5b61e4a6211eb22979c7f1be12d30
release: b8e8e14d27cdadda3688d067256838564a118a90
