### ISSUE TITLE
ntr: reduced eukaryotic translation initiation factor 2B complex assembly

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2644]
PMID:27023709
fig 2i

**Comment by mah11** [comment]
decreased eukaryotic translation initiation factor 2B complex assembly FYPO:0005387

**Comment by mah11** [comment]
edit file: 53392dc6fb01d6e738b705279acd16fc5f87d341
release: e38d2ae281f1089faead8e3f729d8abc1756e5c3
