### ISSUE TITLE
ntr: normal nucleocytoplasmic protein import & export PMID:15161942

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2648]
Standard defs

descendent of
FYPO:0004848	normal protein transport PMID:15161942

**Comment by mah11** [comment]
These exist:

id: FYPO:0004121
name: normal protein import into nucleus

id: FYPO:0004397
name: normal protein export from nucleus

I can add synonyms, but note that the xp'd GO terms do not have synonyms using "nucleocytoplasmic".

**Comment by mah11** [comment]
note to self: also add 'normal intracellular protein transport' xp GO:0006886 to get desired inferred ancestry

**Comment by ValWood** [comment]
But they are descendants of 'nucleocytoplasmic', so the GO terms  *could* have those synonyms...
Doesn't matter tho' they are the terms I needed...

**Comment by mah11** [comment]
added synonyms and
normal intracellular protein transport FYPO:0005397

**Comment by mah11** [comment]
edit file: 53392dc6fb01d6e738b705279acd16fc5f87d341
release: e38d2ae281f1089faead8e3f729d8abc1756e5c3

**Comment by ValWood** [comment]
FYI
, don't see as a descendant of
FYPO:0005397	normal intracellular protein transport

**Comment by mah11** [comment]
Those really, really ought to get inferred. Doesn't make sense. Grump.

**Comment by mah11** [comment]
OK, I think maybe the problem is the paths in GO involving the big hairy transport vs. targeting mess. I've asserted links as a workaround. Grumble.

**Comment by mah11** [comment]
edit file: c8a3c80b1ab0ad92eff599604216ff22314cb836
release: bc216a53995af2ca206b7dc3a28293bf8f3b978b
