### ISSUE TITLE
A question about poly A export and ntr

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2649]
A question...

How do we distinguish between:

FYPO:0003119	increased nuclear polyadenylated mRNA level during vegetative growth

and

decreased poly(A)+ mRNA export from nucleus

**Comment by ValWood** [comment]
ntr : increased *nucleolar* polyadenylated mRNA level during vegetative growth

**Comment by mah11** [comment]
It's the usual - if the assay watches the export (e.g. movie or time series), use the export term; if it just measures how much RNA is in the nucleus, use the level term.

I'll add an output link between the 2 terms.

**Comment by mah11** [comment]
added link FYPO:0002522 has_output FYPO:0003119

**Comment by mah11** [comment]
edit file: 53392dc6fb01d6e738b705279acd16fc5f87d341
release: e38d2ae281f1089faead8e3f729d8abc1756e5c3
