### ISSUE TITLE
what does expressivity mean for "abolished G1 arrest?"

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2652]
should any 'abolished' have 'expressivity'?

**Comment by mah11** [comment]
No, but I think configuring it correctly wouldn't be trivial. Canto ticket https://github.com/pombase/canto/issues/1021 is relevant.

**Comment by ValWood** [comment]
Ok, can ignore...

**Comment by mah11** [comment]
I'll close this until we can reconfigure.

**Comment by mah11** [comment]
Canto ticket and config done
