### ISSUE TITLE
ntr: increased protein level during G1 arrest

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2654]
I think the term I need may be 
"increased protein level during cellular response to nitrogen starvation"
but here the cell cycle stage seems more appropriate (I would add nitrogen depletion as a condition?)

Or maybe a term should specify both?

At 48 h, more than 90% of the cells were in
G with a nearly undetectable level of Cdc13. By con- 1
trast, in 􏰊srw1 cells, the amount of Cdc13 did not decrease, but tended to rather slightly increase, at 48 h despite that more than one-half the cells arrested in G1. This result shows that Srw1 is essential for de- crease of Cdc13 upon nitrogen starvation.

**Comment by ValWood** [comment]
also, this term
increased protein level during cellular response to nitrogen starvation
has this comment:

Consider annotating to a term describing abnormal translation or abnormal regulation of translation, but note that changes in protein levels may result from changes in protein stability or degradation as well as changes in protein synthesis. This term can be used for any circumstances in which cells are starved for nitrogen. Note that cells may enter G0 (quiescence) when subjected to prolonged nitrogen starvation; this term is not restricted to G0. We recommend noting which protein(s) were used in the assay when annotating to this term.

Should that be there?

**Comment by ValWood** [comment]
OK  looking at existing annotation I think I need

increased protein level during G1 arrest in response to nitrogen starvation

**Comment by ValWood** [comment]
I'm a bit confused now...

I found

**Comment by mah11** [comment]
added
increased protein level during mitotic G1 cell cycle arrest in response to nitrogen starvation FYPO:0005401

The comment on FYPO:0001219 is OK - it's explaining that some but not all instances of nitrogen starvation go on long enough to put cells into G0, and the term can be used in any case, not just the G0 cases.

**Comment by mah11** [comment]
edit file: 6661305a803ccbc7889ba3e7d176839bc56a0dd0
release: ec9073a2c1a23a15d859cbed4d611d4e06281726
