### ISSUE TITLE
ntr: 	normal protein degradation during mitotic M-phase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2659]
descendant of
FYPO:0002800	normal protein degradation during vegetative growth

another one I missed... moved term suggestion PMID:16483313 to comment

**Comment by mah11** [comment]
normal protein degradation during mitosis FYPO:0005410

**Comment by mah11** [comment]
edit file: c8a3c80b1ab0ad92eff599604216ff22314cb836
release: bc216a53995af2ca206b7dc3a28293bf8f3b978b
