### ISSUE TITLE
PMID:9802907 advanced mitotic spindle elongation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2663]
synonym premature mitotic spindle elongation

descendent of
	FYPO:0000131	abnormal mitotic spindle elongation

standard def

**Comment by mah11** [comment]
premature mitotic spindle elongation FYPO:0005417

(everything else is name 'premature', synonym 'advanced', so I did this one the same way round)

**Comment by mah11** [comment]
edit file: c8a3c80b1ab0ad92eff599604216ff22314cb836
release: bc216a53995af2ca206b7dc3a28293bf8f3b978b
