### ISSUE TITLE
new condition temperature shift, low to high

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2667]
yada yada.... follow pattern

**Comment by ValWood** [comment]
and  high to low

**Comment by Antonialock** [comment]
id: PECO:0000293
name: temperature shift, low to high

id: PECO:0000293
name: temperature shift, high to low

**Comment by Antonialock** [comment]
id: PECO:0000294
name: temperature shift, high to low

**Comment by ValWood** [comment]
now i'm stumped:
![stumped](https://cloud.githubusercontent.com/assets/7359272/15500518/f07943c6-21a0-11e6-9e97-02cc5fe5edcb.jpg)

any ideas.  they do low to standard (upon mitotic entry) then standard to high (after anaphase A)!

**Comment by Antonialock** [comment]
I can't tell from that image alone without seeing any text

**Comment by ValWood** [comment]
shift  from  low to standard upon mitotic entry, then shift from standard to high in early anaphase....

**Comment by ValWood** [comment]
OK, I called it
two-step shift, low to standard, standard to high

**Comment by Antonialock** [comment]
id: PECO:0000295
name: two-step shift, low to standard, standard to high
