### ISSUE TITLE
tpv: monoseptate vegetative cell with binucleate and anucleate compartments

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2668]
monoseptate vegetative cell with binucleate and anucleate compartments

has descendant:
septation following abolished mitotic sister chromatid separation, with mononucleate and anucleate compartment formation

**Comment by mah11** [comment]
fixed

**Comment by mah11** [comment]
edit file: a760fa43a796d2330cd62ac432969cc41ec40ced
release: b51f1da33aae79745f62d7c2015f90d7a38c922a
