### ISSUE TITLE
question about chromosome segregation phenotype

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2669]
Is this
"incomplete mitotic sister chromatid segregation, with phi-shaped DNA mass"

this?
![q](https://cloud.githubusercontent.com/assets/7359272/15501447/6c1168b6-21a5-11e6-8e25-9b7dc4c71eb8.jpg)

**Comment by mah11** [comment]
yes

(note - corrected def xref PMID)

**Comment by mah11** [comment]
correction in
edit file: a760fa43a796d2330cd62ac432969cc41ec40ced
release: b51f1da33aae79745f62d7c2015f90d7a38c922a

**Comment by mah11** [comment]
ontology stuff looks ok, so closing
