### ISSUE TITLE
should this be 'segregation' not separation?

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2672]
lagging mitotic chromosomes, with complete sister chromatid separation
Definition
A cellular process phenotype observed in the vegetative growth phase of the life cycle in which sister chromatids do not move towards the spindle poles at the same time during mitosis prior to completion of chromosome segregation. Although one or more chromosomes remain distant from the spindle pole after the bulk of the DNA has separated, mitotic sister chromatid segregation does eventually go on to complete separation of chromosomes.

I am trying to annotate
We and others (20, 21, 32) have noted that when dam1 is deleted, many anaphase cells have one or more chromosomes lagging be- hind the bulk of chromosomes in anaphase (Fig. 5B). The lagging chromosomes usually caught up with the bulk of chromosomes later, with only a small percentage of cells suffering chromosome missegregation (20, 21, 32). 

fig5 B
PMID:20624975
lagging chromosomes, but  complete segregation

**Comment by mah11** [comment]
I kind of suspect that "lagging" reflects delays in separation (GO:0051306), polewards movement (GO:0007079), or both, and in FYPO:0004101 both do eventually finish. I don't know whether the entire whole segregation process would also be completed - seems likely but I'm not sure, especially about decondensation (GO:0007083).

We haven't explicitly added a term for chromosome(s) continuing to lag for as long as anyone keeps looking, but we could, as that's the distinction we've made in the ontology given the placement and definition of FYPO:0004101.

**Comment by ValWood** [comment]
Ah OK I see, I thought this was just a mistake and menat segregation.
In this case is
"with complete sister chromatid separation" necessary then?

**Comment by mah11** [comment]
If we want to continue allowing for the possibility that separation (+ movement to poles) doesn't complete in some cases, then yes, the "with complete ... separation" is necessary. That's the difference between FYPO:0004101 and its parent, which at present explicity says separation may or may not complete.

Background in #1916

**Comment by ValWood** [comment]
ok, yep

**Comment by mah11** [comment]
I've added comments to the "lagging chromosome" terms. OK to leave things as they are otherwise? If so, I'll close this.

**Comment by mah11** [comment]
comments in
edit file: a760fa43a796d2330cd62ac432969cc41ec40ced
release: b51f1da33aae79745f62d7c2015f90d7a38c922a

**Comment by mah11** [comment]
no further squawking, so closing
