### ISSUE TITLE
ntr : decreased mitotic spindle microtubule depolymerization during movement of chromosomes towards separated spindle pole bodies 

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2673]
decreased mitotic spindle microtubule depolymerization during movement of chromosomes towards separated spindle pole bodies 

descendent of
FYPO:0004650

PMID:20624975

**Comment by mah11** [comment]
Would "... during anaphase A" work? It would make for a much nicer term name, and I'm not aware of an obvious difference.

**Comment by ValWood** [comment]
Hmm, I knew this was clunky.

Actually I think that might work. The other possible instances, during  chromosome recapture (before complete bipolar attachment), will  be in metaphase....

**Comment by mah11** [comment]
hooray! and I'm happy to put the long essay version in as an exact synonym

**Comment by mah11** [comment]
decreased mitotic spindle microtubule depolymerization during anaphase A FYPO:0005423

(and yes, I included the mile-long synonym ;) )

**Comment by mah11** [comment]
edit file: a760fa43a796d2330cd62ac432969cc41ec40ced
release: b51f1da33aae79745f62d7c2015f90d7a38c922a
