### ISSUE TITLE
	decreased mitotic chromosome condensation at telophase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2674]
decreased mitotic chromosome condensation
descendant of
FYPO:000328

	PMID:21540296

**Comment by mah11** [comment]
decreased mitotic chromosome condensation during telophase FYPO:0005424

**Comment by mah11** [comment]
edit file: a760fa43a796d2330cd62ac432969cc41ec40ced
release: b51f1da33aae79745f62d7c2015f90d7a38c922a
