### ISSUE TITLE
reduced DNA/DNA annealing activity

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2675]
XPs depend on outcome of
https://github.com/geneontology/go-ontology/issues/12465

PMID:9285594

**Comment by mah11** [comment]
OK, then, I'll wait until they get it sorted. (If GO drags on, let me know if you want me to add FYPO terms without xps sooner; it's not that big a deal to fill the xp in later.)

**Comment by ValWood** [comment]
oh, add without XPs if poss, then I can get this session through....

**Comment by mah11** [comment]
abnormal DNA/DNA annealing activity FYPO:0005438
  decreased DNA/DNA annealing activity FYPO:0005439

xp'd to GO:1990814 for now; I'll change it if the GO ticket outcome dictates

**Comment by mah11** [comment]
edit file: 78a1fbc60da524ea66a75ea414d47ddb92382e22
release: 8eb81f314401b27a2f0a353f677d1f3c9206c599
