### ISSUE TITLE
ntr curved elongated vegetative cell with long curved microtubules PMID:11739790

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2676]
PMID:11739790

curved elongated vegetative cell with long curved microtubules

descendent of 
FYPO:0005103	curved elongated vegetative cell
FYPO:0004863	long curved microtubules

parent of
FYPO:0004864	viable curved vegetative cell with long curved microtubules

**Comment by ValWood** [comment]
Ideally, I'd also like
curved "J" shaped elongated vegetative cell with long curved microtubules
curved "C" shaped elongated vegetative cell with long curved microtubules

(the one with G2 block has the bend in the middle,  G1 block ha bend at the end (elongation is only from one end)

**Comment by ValWood** [comment]
hmm , the curved microtubules here aren't just curved followin the cell, they are 'proper looped around end of cell"

![curved](https://cloud.githubusercontent.com/assets/7359272/15761314/64fdda20-290f-11e6-85a4-583c181bdb42.jpg)


![but not in j-shaped](https://cloud.githubusercontent.com/assets/7359272/15761320/6de224ca-290f-11e6-9ec3-3cb0220f3f1d.jpg)

**Comment by mah11** [comment]
This bit

> parent of
> FYPO:0004864 viable curved vegetative cell with long curved microtubules

would cause a TPV because FYPO:0004864 does not specify that the cell itself is elongated.

Looped vs not-looped MTs will have to go just in definition text.

(note to self: can request 'C-shaped' and 'J-shaped' from PATO; looks like there's ample precedent for other letters)

**Comment by ValWood** [comment]
Could we word it in some way so that the "elongated microtubules"  curve around the cell end. The normal length ones stop at the cell tip.

So  in H above it would be
elongated cell with elongated microtubules (curling around the cell tip can be in the def)

But F would be normal length microtubules, because they are normal for a long cell. They still stop at the cell tip.

Does that make any sense?

**Comment by mah11** [comment]
opened https://github.com/pato-ontology/pato/issues/96

**Comment by mah11** [comment]
curved elongated vegetative cell with long curved microtubules FYPO:0005425
  elongated C-shaped vegetative cell with long curved microtubules FYPO:0005426
  elongated J-shaped vegetative cell with long curved microtubules FYPO:0005427

**Comment by mah11** [comment]
edit file: a760fa43a796d2330cd62ac432969cc41ec40ced
release: b51f1da33aae79745f62d7c2015f90d7a38c922a
