### ISSUE TITLE
ntr: increased/decreased protein cleavage product PMID:15329725

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2677]
under
FYPO:0001327	increased protein level during vegetative growth

suggested def
A cell phenotype observed in the vegetative growth phase of the life cycle in which the amount of a protein cleavage product is higher than normal. Total protein or a specific protein may be affected.

Comment recommend noting the protein, yada yada...

**Comment by mah11** [comment]
1. I would much rather do this using FYPO:0001327 with a PR:nnn ID extensoin for the specific product assayed.

2. If you do insist on a separate ontology term, (a) we'll need a more precise definition of "protein cleavage product", and (b) I suspect that the "total protein" part of the usual definition wouldn't make sense.

**Comment by ValWood** [comment]
closing.
https://sourceforge.net/p/pro-obo/term-requests/108/

**Comment by ValWood** [comment]
I am now checking and in  a previous paper I did this as

abolished proteolysis during vegetative growth (assayed_using :gene)
instead  of 
 increased protein level during vegetative growth (assayed using  PR:cleavage product)

Which way do we think is best?

With the first option, I don't need to go for PRO IDs (although if we get them I can use them)

**Comment by mah11** [comment]
I wouldn't object to either. I suspect I'd go for a proteolysis term unless I had some specific reason to think the product level assay could reflect anything else going on.

**Comment by ValWood** [comment]
OK, I think I'll go for the proteolysis term, easier. I don't  know why I did it this way this time....
