### ISSUE TITLE
ntr: delayed UV-damage excision repair PMID:15329725

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2679]
ntr: delayed UV-damage excision repair

standard def

**Comment by ValWood** [comment]
plus ntr
decreased UV-damage excision repair during mitotic G2 phase
(already have G1)

**Comment by mah11** [comment]
delayed onset of UV-damage excision repair FYPO:0005428
  decreased UV-damage excision repair during mitotic G2 phase FYPO:0005429

**Comment by mah11** [comment]
edit file: a760fa43a796d2330cd62ac432969cc41ec40ced
release: b51f1da33aae79745f62d7c2015f90d7a38c922a
