### ISSUE TITLE
synonyms for "inviable vegetative cell population"

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2680]
should we add 'synthetic lethal" as related? I can imagine people typing this in to describe double mutants....

**Comment by mah11** [comment]
No. The "synthetic" part of synthetic lethal reflects the genotype, not the phenotype. It would look stupid when the term is viewed in any context that shows synonyms.


note to self: do need to review "lethal" in synonyms - missing from at least some population terms

**Comment by mah11** [comment]
many 'lethal' synonyms added

**Comment by mah11** [comment]
edit file: a760fa43a796d2330cd62ac432969cc41ec40ced
release: b51f1da33aae79745f62d7c2015f90d7a38c922a
