### ISSUE TITLE
ntr: inviable after spore germination with elongated germ tube and fragmented nuclear DNA

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2685]
descendant of FYPO:0000314	
PMID:17178839

**Comment by mah11** [comment]
inviable after spore germination with elongated germ tube and fragmented nucleus FYPO:0005435

We've used 'fragmented nucleus' in other terms inspired by this sort of data, so I made the term name consistent. I also added related synonyms with 'fragmented nuclear DNA' to 'fragmented nucleus' terms.

**Comment by mah11** [comment]
edit file: 51d8717d25e520da70c8db80f272ffd7bec05954
release: e07924407651cf5794e0cd066ef0d69fa571dacf
