### ISSUE TITLE
ntr abolished double-strand break repair

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2686]
PMID:17178839

parent of

abolished double-strand break repair by yada yada....

I could inferI guess.....
In cycling S. pombe cells, HR is the dominant pathway for
DSB repair whereas NHEJ is dispensable for cell survival (7).

**Comment by mah11** [comment]
abolished double-strand break repair FYPO:0005436

**Comment by mah11** [comment]
edit file: 51d8717d25e520da70c8db80f272ffd7bec05954
release: e07924407651cf5794e0cd066ef0d69fa571dacf
