### ISSUE TITLE
ntr: normal number of rad52 foci (in response to dna damage)

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2687]
standard def
PMID: 17178839

(cut8 delta) Fig. 4D

**Comment by mah11** [comment]
normal number of Rad52 foci during cellular response to bleomycin FYPO:0005437

**Comment by mah11** [comment]
edit file: 51d8717d25e520da70c8db80f272ffd7bec05954
release: e07924407651cf5794e0cd066ef0d69fa571dacf
