### ISSUE TITLE
OTR FYPO:0003675 

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2689]
Could you change the name and def for FYPO:0003675 from
increased 5.8S rRNA level 
to
increased 5.8SL rRNA level 

apparantly 5.8S rRNA exist in 2 forms, S and L. I must have thought that the short form was produced from the long form but that's not the case apparantly.

**Comment by mah11** [comment]
ok, done (removed xp)

**Comment by mah11** [comment]
edit file: 78a1fbc60da524ea66a75ea414d47ddb92382e22
release: 8eb81f314401b27a2f0a353f677d1f3c9206c599
