### ISSUE TITLE
ntr:  swollen elongated cell with enlarged nucleus

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2690]
Parent of
inviable swollen elongated cell with enlarged nucleus

This phenotype might be inviable. Certainly at its extreme as when seen in cdc13 it is inviable but I am not sure about the one I am looking at because it isn't fully penetrant.

(also, this phentype almost always  (probably always)  indicates a diploid...
I searched on diploid first. Should it have this as some sort of synonym, or in a comment?

**Comment by ValWood** [comment]
PMID:12653962

**Comment by mah11** [comment]
swollen elongated cell with enlarged nucleus FYPO:0005440

I put the diploid bit in a comment - it can't be part of the def, and I'm very leery of putting it in a synonym, because it's a genotype feature.

**Comment by ValWood** [comment]
Maybe the best way would be to say:
consider also "increased diploidization" or whatever the term is for this....

**Comment by mah11** [comment]
ok, included that in the comment

**Comment by mah11** [comment]
edit file: 78a1fbc60da524ea66a75ea414d47ddb92382e22
release: 8eb81f314401b27a2f0a353f677d1f3c9206c599
