### ISSUE TITLE
FYPO:0005425, follow on from fypo/issues/2676

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2691]
1. spurious comment needs deleting

2. curved elongated vegetative cell with long curved microtubules

This and its descendants should all refer to cytoplasmic microtubules. Can this be added?

**Comment by ValWood** [comment]
3.

So here I haven't differentiated my phenotypes properly.

There are distinct phenotypes. 

A.  where the cell is long, and the microtubules are long. But they are probably "normal' microtubules for the length of the cell (they touch the cell tip)

B. Where the cell is long, but the microtubules really are long because the curl around the cell tips. These are the ones which appear to have microtubule depol defects but I am losing this

C. there are others where the cells are normal length but the microtubules are long and curved around the cell tip.

At present, some of the defs say "the microtubules may or may not curl around the tip"

I think its important to capture/separate the phenotypes there the microtubules do n't stop growing at the cell ends.


Can we have terms to differentiate depending on whether the microtubules stop at the cell tip or not?
I flagged in which session

the cdc10/klp*  mutant (J-shaped) don't curl around the ends
https://curation.pombase.org/pombe/curs/8d41506ec01aec5b#

but the cdc25/klp* mutant do

**Comment by mah11** [comment]
No definitions say "microtubules may or may not curl around the tip". The FYPO:0005426 definition includes "Microtubules may loop around the ends of the cell.", and one term, 'long curved cytoplasmic microtubules' (FYPO:0004511), has a comment saying "In severe instances of this phenotype, microtubules grow long enough to curve around the cell tip.". In both cases, the term names and text definitions specify that the microtubules are always curved, so they exclude case A. The minor distinction is how much extra MT length is being stuffed into the cell. If the FYPO:0005426 cells always have loopy MTs, I can delete "may".

Is it always the case that cytoplasmic interphase MTs that are longer than normal for the cell will be curved?

It's not explicit at present, but we don't actually say that straight end-to-end MTs in an elongated cell are elongated MTs. So it sort of implies that if MTs remain straight and extend no further than end-to-end, they're normal length for that cell, whether the cell itself is normal length or not.

**Comment by ValWood** [comment]
> In both cases, the term names and text definitions specify that the microtubules are always curved, so they exclude case A. 

not here
![curved](https://cloud.githubusercontent.com/assets/7359272/16049847/320a28f8-3251-11e6-8112-53c09c71376b.jpg)

The microtubules are curved (but not bent around the tip)
They are long, but that is probably only because the sell is long....

**Comment by ValWood** [comment]
Contrast to:
![curved_long_microtubule](https://cloud.githubusercontent.com/assets/7359272/16049926/6cf38c3e-3251-11e6-8dfc-fcc0bd10f60f.jpg)

Here the cell is normal lentht but the microtubules are very long and curve around the tip

**Comment by ValWood** [comment]
These are long and curved around the end of the elongated cell

![curved long](https://cloud.githubusercontent.com/assets/7359272/16049976/a337948e-3251-11e6-9aa5-eb680abccb63.jpg)

**Comment by ValWood** [comment]
> Is it always the case that cytoplasmic interphase MTs that are longer than normal for the cell will be curved?

I think so... ('curled' even, not just curved)

**Comment by mah11** [comment]
Your initial description of case A does not say that either the cell or the microtubules are curved. I took your latter two images (H and H) to represent cases B and C, and I don't see a text description in this ticket that refers exclusively to the first pic (D). The case A description encompasses pic D and cells that are long but straight, with straight MTs.

**Comment by ValWood** [comment]
> It's not explicit at present, but we don't actually say that straight end-to-end MTs in an elongated cell are elongated MTs. So it sort of implies that if MTs remain straight and extend no further than end-to-end, they're normal length for that cell, whether the cell itself is normal length or not.

Ah OK, so to annotate D above, I would just say 'elongated curved cell with curved microtubules' and not say anything about microtubule length at all. That would work....

That way we could stick with the original def for long microtubules, and say that they may curve around the end, but if describing the microtubules in an elongated cell, and they didn't curl around the end we would just not refer to microtubule length at all.....

**Comment by mah11** [comment]
Yes, I think that would be fine. Hooray.

For future reference, and to see if I've got it, is it true that
a) normal length MTs will be straight in a straight cell, but will curve along with the long axis in a curved cell;
b) following on from (a), curved MTs may be normal length or elongated;
c) all longer-than-normal MTs are curved (sometimes unto loopitude)
?

I think all that is consistent with pic D = 'elongated curved cell with curved microtubules' too.

**Comment by mah11** [comment]
recast FYPO:0005425-5427 to specify cytoplasmic MTs
moved & edited FYPO:0005427 to remove "long MT" part of description
deleted spurious comments, and added others

that might be everything for this ticket; if not, can reopen later or do a new one

**Comment by mah11** [comment]
edit file: 78a1fbc60da524ea66a75ea414d47ddb92382e22
release: 8eb81f314401b27a2f0a353f677d1f3c9206c599
