### ISSUE TITLE
ntr: abolished mitotic centromeric DNA separation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2692]
descendant oof:
	abolished centromeric DNA separation

	PMID:11861765

**Comment by ValWood** [comment]
also mitotic version of this
FYPO:0001779	abnormal centromere clustering at nuclear periphery

**Comment by mah11** [comment]
Both terms are already defined as mitotic. I'll add more synonyms if that will help.

Do you also need generic and/or meiotic equivalents?

**Comment by ValWood** [comment]
not at the momnet, but they will be needed eventually I guess, so good to clarify what we are using for now...

**Comment by mah11** [comment]
synonyms added
