### ISSUE TITLE
PMID:20624975 abolished protein localization to microtubule during mitotic interphase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2693]
abolished protein localization to microtubule during mitotic interphase
descendant of

FYPO:0003269	abolished protein localization to microtubule during vegetative growth

stndard def

**Comment by mah11** [comment]
abolished protein localization to microtubule during mitotic interphase FYPO:0005441

**Comment by mah11** [comment]
edit file: 78a1fbc60da524ea66a75ea414d47ddb92382e22
release: 8eb81f314401b27a2f0a353f677d1f3c9206c599
