### ISSUE TITLE
ntr: abnormal sister chromatid separation at the telomeres

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2694]
standard def
PMID:21540296

**Comment by mah11** [comment]
abnormal telomeric DNA separation FYPO:0005442 (with synonyms)

**Comment by mah11** [comment]
edit file: 78a1fbc60da524ea66a75ea414d47ddb92382e22
release: 8eb81f314401b27a2f0a353f677d1f3c9206c599
