### ISSUE TITLE
ntr: decreased proteolysis during vegetative growth

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2695]
standard

to finalise
https://github.com/pombase/fypo/issues/2677#

**Comment by mah11** [comment]
decreased proteolysis during vegetative growth FYPO:0005443

edit file: 7ecd34e4efc50bcf3304ca13ffb3ecaee7eb7e14
release: 1bb27ea77c93c656687cde2ca8005eee1f8db4b1
