### ISSUE TITLE
possible term rename

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2704]
FYPO:0000938	abolished protein localization to cortical microtubule cytoskeleton during vegetative growth

could this be renamed
FYPO:0000938	abolished protein localization to cortical microtubule cytoskeleton during mitotic interphase
(since the cortical cytoskeleton only exists during interphase this should be OK?)

and it will match:

normal protein localization to microtubule cytoskeleton during mitotic interphase

**Comment by mah11** [comment]
Done. More importantly, it's safe to rename because FYPO:0000938 isn't used for any annotations at present.

(note: the 'normal' term you mention isn't specific to the cortical MT cytoskeleton, so matching it is irrelevant)

**Comment by ValWood** [comment]
ok

**Comment by mah11** [comment]
edit file: b457a5e39cea1a313d9ee4badbdb7642b6e73d30
release: cfd04996f5dd4eeea9667c5ab978103c937b76ad
