### ISSUE TITLE
NTR:  abnormal protein anchoring at the cell end

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2705]
In tea1∆ cells, Tea2–GFP dots moved from the cell middle to the cell ends at a rate of 3.8 ± 1.0 μm min−1 (n = 31), very similar to the rate measured in wild-type cells (Fig. 5c; see Supplementary Information, MovieS3). However, once Tea2 reached the cell ends, it failed to accumulate there

I guess  in GO speak establishment is normal but maintenance is abnormal?

**Comment by mah11** [comment]
abnormal maintenance of protein location at cell tip FYPO:0005464

What's the paper? I've opened https://github.com/geneontology/go-ontology/issues/12502 for terms to use in xps for this and FYPO:0003157, and the one for this new term needs a PMID.

**Comment by ValWood** [comment]
ombe/curs/edfddf218bf755ae
PMID:12894167

**Comment by mah11** [comment]
edit file: b457a5e39cea1a313d9ee4badbdb7642b6e73d30
release: cfd04996f5dd4eeea9667c5ab978103c937b76ad
