### ISSUE TITLE
ntr: localization terms

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2709]
Standard defs
1. 
decreased protein localization to actomyosin contractile ring during mitosis
descendant of FYPO:0002699

2. 	increased protein localization to cell tip during mitosis
descendant of  FYPO:0002852

PMID:8978670

**Comment by mah11** [comment]
decreased protein localization to actomyosin contractile ring during mitosis FYPO:0005467
  increased protein localization to cell tip during mitosis FYPO:0005468

**Comment by mah11** [comment]
edit file: b457a5e39cea1a313d9ee4badbdb7642b6e73d30
release: cfd04996f5dd4eeea9667c5ab978103c937b76ad
