### ISSUE TITLE
ntr: inviable after spore germination, without cell division, lysed cells

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2710]
inviable after spore germination, without cell disvision, lysed cells
descendant of

0001991	inviable after spore germination, without cell division

	PMID:8978670

**Comment by mah11** [comment]
inviable after spore germination, without cell division, lysed cell FYPO:0005469

**Comment by mah11** [comment]
edit file: b457a5e39cea1a313d9ee4badbdb7642b6e73d30
release: cfd04996f5dd4eeea9667c5ab978103c937b76ad
