### ISSUE TITLE
ntrs: catalytic activity

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2711]
abolished GS GO:0004356
abolished GOGAT    GO:0016040	
aboished NADP-GDH GO:0004354

normal NADP-GDH  GO:0004354
normal GOGAT GO:0016040	

	PMID:7773104

**Comment by mah11** [comment]
> abolished GS GO:0004356

is FYPO:0002268

new terms:
  abnormal glutamate synthase (NADH) activity FYPO:0005470
  abolished glutamate synthase (NADH) activity FYPO:0005471
  abolished glutamate dehydrogenase (NADP+) activity FYPO:0005472
  normal glutamate synthase (NADH) activity FYPO:0005473
  normal glutamate dehydrogenase (NADP+) activity FYPO:0005474

names match the GO terms; synonyms abound

**Comment by mah11** [comment]
edit file: 5f9e1f7f2c79f550643ff39dd9b6ca856a8f7c1b
release: da67beb7808271cd3cf2fc95521977f3fb0f9b42
