### ISSUE TITLE
ntr: filamentous actin, reduced

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2713]
filamentous actin, reduced
PMID:9459302
standard def

**Comment by mah11** [comment]
decreased cellular level?

**Comment by ValWood** [comment]
yep...

**Comment by mah11** [comment]
decreased filamentous actin level FYPO:0005476

**Comment by mah11** [comment]
edit file: 5f9e1f7f2c79f550643ff39dd9b6ca856a8f7c1b
release: da67beb7808271cd3cf2fc95521977f3fb0f9b42
