### ISSUE TITLE
term to describe increased activity toward a non-normal substrate

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2716]
This paper it isn't possible to get any annotation as its a structure paper
curs/66d0d6609144ac64

However, they make a couple of mutant variants which make  it possible to modify a previously unmodifiable human substrate.

irst, we examined whether Pvg1p could use pNP-attached Gal-α1,4-GlcNAc (LacNAc), which is nor- mally found at the end of human-type complex glycan chains, as a substrate. We found that the wild-type Pvg1p has very low pyruvyltransferase activity for the LacNAc-pNP (Supplementary Fig. S4a). Based on our predicted substrate-binding model of Pvg1p, less pyruvylation was probably due to the steric hindrance posed by the NAc group of the LacNAc-pNP with the H168 of Pvg1p (Fig. 4d), as a result of which it could not bind properly to the active site of Pvg1p. Thus, we created the H168A mutant of Pvg1p (Pvg1pH168A) to examine whether this Pvg1p mutant would recognize the human-type complex oligosaccharides. For this purpose, we expressed recombinant Pvg1pH168A in E. coli and successfully purified it. Remarkably, Pvg1pH168A exhibited higher activity for transferring pyruvyl group to LacNAc-pNP than the wild-type Pvg1p (Supplementary Fig. S4b), suggesting that Pvg1pH168A may be able to add pyruvate on the human-type complex oligosaccharides.

is there a way to capture this?

**Comment by mah11** [comment]
FYPO:0003347 altered substrate specificity

or a new is_a child, a la FYPO:0003348, if you can name the activity the mutant acquires

**Comment by ValWood** [comment]
I *knew* we had done it before.....

**Comment by ValWood** [comment]
I'll just use this.  It doesn't make sense to make a more specific term as it a modification substrate so its just a specific gene product . At least we get a link to the paper on the page.
