### ISSUE TITLE
protein mislocalized to the vacuolar membrane

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2719]
ntr: protein mislocalized to the vacuolar membrane

standard def
PMID:22484924

**Comment by ValWood** [comment]
also what term to use for a  normally resident vacuolar protein which is secreted?


protein mislocalized from vacuole to extracellular region?

**Comment by ValWood** [comment]
also
normal endosome to Golgi transport

Note that, as all of these are proteins, for this one I started from 'normal protein transport' and ended up under  'intracellular protein transport', which is a different branch.

This always worries me. This is because  veiscles can  presumable carry other things. However, I think every assay we have curated refers to proteins. I wonder if we can make our terms

normal protein transport endosome to Golgi transport etc...and add x-p to intracellular protein transport?
Then, if we come across an instance which does not refer to protein, we just create a new parent?

**Comment by mah11** [comment]
> also what term to use for a normally resident vacuolar protein which is secreted?

How about 'abolished [or decreased, if some makes it to the vacuole] maintenance of protein localization in vacuole, with protein secreted'? I can include friendlier synonyms.

**Comment by ValWood** [comment]
Yep, do both terms...there are lots of papers which do this assay (secretion of CPY) and they might be both.IIRC this one is abolished but I'll need to double check.

**Comment by mah11** [comment]
by 'both' you mean 'decreased yada' and 'abolished yada'? if so, no problem

**Comment by mah11** [comment]
on to the other issue ...

> This is because vesicles can presumable carry other things.

That's correct; the FYPO structure mirrors GO's.

> I wonder if we can make our terms normal protein transport endosome to Golgi transport etc...and add x-p to intracellular protein transport?

How many terms are affected?
I am always very leery of narrowing the definitions of existing terms. I've only done it on rare occasions, for single terms that have 1 or 2 (or in one case, zero) annotations, and usually where the term either didn't have a logical definition, or where the xp could be changed cleanly.

Doing a batch would make me twitchy, and no, I don't think simply adding intracellular protein transport would work (or at least, it's not obvious how to build it in). I also doubt that GO would add protein-specific terms (e.g. normal endosome to Golgi protein transport) unless there are cases where different mechanisms operate or different gene products are involved in moving proteins as opposed to other substances.

Unless you're only talking about one or two terms, I would prefer to:
- add narrow synonyms that include 'protein';
- add comments to explain that proteins or other stuff can be transported, and that if transport of a protein was assayed, put it in an extension;
- add to the extension config to allow (but not require) a gene ID to represent an assayed protein.

This also has the advantage of being generic - I can do the same for the term in https://github.com/pombase/curation/issues/968 and any new terms in this area.

**Comment by ValWood** [comment]
yep

**Comment by ValWood** [comment]
Go with your preferred solution. I haven't come across an e.g where  the gp in question does not transport proteins (ever).
It would be great if these could be XP-d to  intracellular protein transport, but I have always been aware of this sub-opitimality? in GO so I often IC to "intracellular protein transport" for enrichment purposes.

**Comment by mah11** [comment]
new terms
  protein mislocalized to vacuolar membrane FYPO:0005489
  abnormal protein localization to vacuole FYPO:0005490
  decreased maintenance of protein localization in vacuole, with protein secreted FYPO:0005491
  abolished maintenance of protein localization in vacuole, with protein secreted FYPO:0005492
  normal endosome to Golgi transport FYPO:0005493

synonyms & comments added as described, and extension config updated (new ticket if you spot any I missed)

edit file: 87bbd5a48383ecf64dfdfde1fc48c7f8b8c05389
release: a1a90675d29890871922540ab49849611cfd8bc0
