### ISSUE TITLE
NTR: decreased microtubule-based transport

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2720]
decreased microtubule-based transport
This term for X-P
https://github.com/geneontology/go-ontology/issues/12521

For
https://curation.pombase.org/pombe/curs/edfddf218bf755ae/ro/

with assayed_using option in config (might be automatic?)

**Comment by mah11** [comment]
If you want the phenotype term to be specific for proteins, we can xp to GO:0098840 'protein transport along microtubule' and make the FYPO term name match.

**Comment by ValWood** [comment]
Yep.

**Comment by mah11** [comment]
decreased protein transport along microtubule FYPO:0005494

edit file: 87bbd5a48383ecf64dfdfde1fc48c7f8b8c05389
release: a1a90675d29890871922540ab49849611cfd8bc0
