### ISSUE TITLE
ntr protein mislocalized from cortical regions to cytoplasm during vegetative growth

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2722]
child of
protein mislocalized to cytoplasm during vegetative growth

standard def
fig 1B
PMID:26749213

(move existing annotations down)

**Comment by mah11** [comment]
abolished protein localization to cell cortex, with protein mislocalized to cytoplasm, during vegetative growth FYPO:0005501

edit file: 87bbd5a48383ecf64dfdfde1fc48c7f8b8c05389
release: a1a90675d29890871922540ab49849611cfd8bc0
