### ISSUE TITLE
assayed_using

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2724]
Not available for
"normal protein secretion"

PMID:26749213

**Comment by mah11** [comment]
configuration adjusted

... but please decide which tracker these should go on - extension config tickets have now appeared here, on the curation tracker, and on the canto tracker. It gets confusing!

**Comment by ValWood** [comment]
curation?

**Comment by mah11** [comment]
fine ... I have no real preference other than to pick just one!
