### ISSUE TITLE
+ Zymolyase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2727]
in condition ontology

I have increased cell lysis  when grown in  + Zymolyase

I've made this in addition to the "increased sensitiivty to cell wall degrading enzyme" , because they looked at this in addition to growth. Does that sound OK

**Comment by Antonialock** [comment]
Well if they are sensitive to cell wall degrading enzymes then isn't it quite logical that you get increased cell lysis with +zymolyase?...not sure what it adds..

**Comment by ValWood** [comment]
I guess so, but  not all cell lysis are cell wall problems, and I looked at the sensitivities to 'cell wall degrading enzymes' first and they seem to affect other processes to, so I'm wasn't sure that cell  lysis is always a phenotype....

In this this case the assumption is that it is, I thought if people wanted they could get the intersection between lysis term and  the sensitivity term .....

am I overthinking it?

**Comment by ValWood** [comment]
I think I'd still like to capture the cell lysis as a 'better' grouping term:

FYPO_ID(FYPO:0001190 - sensitive to cell wall-degrading enzymes) for All Alleles	 | ☆	46
FYPO:0000647 - vegetative cell lysis) for All Alleles	 | ☆	93

**Comment by Antonialock** [comment]
ok id: 
PECO:0000298
name: + zymolyase
