### ISSUE TITLE
 abnormal plasma membrane to vacuole transport PMID:26749213

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2729]
abnormal plasma membrane to vacuole transport 

(there is already a term for this 'during nitrogen starvation' for def)

**Comment by mah11** [comment]
abnormal plasma membrane to vacuole transport FYPO:0005508

**Comment by mah11** [comment]
edit file: 2c1f3954eb41e1e924972274fa79f9dca97f499c
release: 8122bc163911279170474760863ce139a3bbd738
