### ISSUE TITLE
abnormal meiotic sister chromatid segregation	PMID:26483559

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2730]
abnormal meiotic sister chromatid segregation

child of
abnormal meiotic chromosome segregation

**Comment by mah11** [comment]
abnormal meiotic sister chromatid segregation FYPO:0005509

**Comment by mah11** [comment]
edit file: 2c1f3954eb41e1e924972274fa79f9dca97f499c
release: 8122bc163911279170474760863ce139a3bbd738
