### ISSUE TITLE
PMID:26483559 NTR: meiosis II metaphase/anaphase transition delay

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2731]
NTR: meiosis II metaphase/anaphase transition delay
standard def

**Comment by mah11** [comment]
meiosis II metaphase/anaphase transition delay FYPO:0005510

**Comment by mah11** [comment]
edit file: 2c1f3954eb41e1e924972274fa79f9dca97f499c
release: 8122bc163911279170474760863ce139a3bbd738
