### ISSUE TITLE
  NTR increased activation of meiosis I cell cycle spindle assembly checkpoint PMID:26483559

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2732]
increased activation of meiosis I cell cycle spindle assembly checkpoint

**Comment by mah11** [comment]
meiotic cell cycle checkpoint phenotype FYPO:0005511
  increased activation of meiosis I spindle assembly checkpoint FYPO:0005512

**Comment by mah11** [comment]
edit file: 2c1f3954eb41e1e924972274fa79f9dca97f499c
release: 8122bc163911279170474760863ce139a3bbd738
