### ISSUE TITLE
NTR : increased protein localization to kinetochore during meiosis	 PMID:26483559

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2734]
+ increased

	FYPO:0004762	abnormal protein localization to kinetochore during meiosis

**Comment by ValWood** [comment]
Here I'm going to stick with Hui-Ju's original annotation (abnormal), because it became more obvious towards the end that it could be increased  because it was not removed earlier or premature 

Terms will be required some time I guess....

**Comment by mah11** [comment]
increased protein localization to kinetochore during meiosis FYPO:0005513

no worries if it isn't used immediately ;)

**Comment by mah11** [comment]
edit file: 2c1f3954eb41e1e924972274fa79f9dca97f499c
release: 8122bc163911279170474760863ce139a3bbd738
