### ISSUE TITLE
protein mislocalized to vacuoles from cortical region

### ISSUE THREAD

**Issue by mah11** [pombase/fypo#2738]
PMID:26749213

model actual name & def on FYPO:0005501

transferred from wrong tracker (https://github.com/pombase/curation/issues/973)

**Comment by mah11** [comment]
protein mislocalized to vacuole FYPO:0005514
  abolished protein localization to cell cortex, with protein mislocalized to vacuole, during vegetative growth FYPO:0005515

**Comment by mah11** [comment]
edit file: 2c1f3954eb41e1e924972274fa79f9dca97f499c
release: 8122bc163911279170474760863ce139a3bbd738

**Comment by ValWood** [comment]
should this be under 
protein mislocalized to cytoplasm during vegetative growth?

**Comment by mah11** [comment]
I've made 'protein mislocalized to vacuole' is_a 'protein mislocalized to cytoplasm during vegetative growth'. That should give FYPO:0005515 a path including is_a and has_part links.
