### ISSUE TITLE
FYPO:0005526 parentage query

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2742]
I didn't find

decreased transport along microtubule
under
decreased microtubule based movement

should I?

**Comment by mah11** [comment]
At a quick glance, I don't see why that link isn't being inferred. I'll dig a little more next time I'm in full FYPO mode.

**Comment by ValWood** [comment]
no hurry...

**Comment by mah11** [comment]
Well, THAT was subtle. Corrected a relation in the xp and now it gets inferred as expected.

**Comment by mah11** [comment]
edit file: 3b73975600f7352daadf94928cd05c932c18a7de
release: 3e4b597b16433cc1d4ec56935ff216aaa2836528
