### ISSUE TITLE
NTR abnormal protein targeting to vacuole of  extracellular protein

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2743]
Follow on from
https://github.com/pombase/fypo/issues/2719

I missed this.
I want to capture the vacuolar targeting of normally secreted proteins.

At present I'm just using
abnormal protein targeting to vacuole

Do you think its appropriate to have something along the lines

abnormal protein targeting to vacuole of  extracellular protein?

**Comment by mah11** [comment]
I looked at the paper, and I don't see this phenotype. I only see the other way round - Cpy1 is normally vacuolar, but secreted in the vps901 mutants; Cps1 is also normally vacuolar but kind of goes punctate cytoylasmic (as far as I can tell) in the mutants.

I can add a new term such as 'decreased protein targeting to vacuole', or even 'decreased protein targeting to vacuole, with protein secreted'. How specific do you want? How many terms?

**Comment by mah11** [comment]
or maybe everything you'd need went in for #2719 ...?

**Comment by ValWood** [comment]
>I looked at the paper, and I don't see this phenotype....

 You are right ...I thought that the acid phosphatase secretion assay was  identifying pho1 in the vacuole instead of extracellular, but her it is only  *not* in the supernatant.

**Comment by ValWood** [comment]
Oh I'm looking a the wrong paper. I'm still doing PMID:27082518 scrub that

**Comment by ValWood** [comment]
I went back to the vps paper

curs/92800aaf61c226d9#

I still need
decreased protein targeting to vacuole, with protein secreted'
for that one, then I think i'm done.

**Comment by mah11** [comment]
decreased protein targeting to vacuole, with protein secreted FYPO:0005547

**Comment by mah11** [comment]
edit file: f60ef64b041e47900fcd4c23fc8df2509c03bb7a
release: 256754d4c284572089d920f8ed9bdab8139dce99
