### ISSUE TITLE
NTR: increased duration of actomyosin contractile ring contraction PMID:27082518

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2746]
synonym
prolonged ...actomyosin contractile ring contraction

standard def

**Comment by mah11** [comment]
increased duration of actomyosin contractile ring contraction FYPO:0005543

**Comment by mah11** [comment]
edit file: 3b73975600f7352daadf94928cd05c932c18a7de
release: 3e4b597b16433cc1d4ec56935ff216aaa2836528
