### ISSUE TITLE
NTR: abnormal protein localization to plasma membrane division site during vegetative growth PMID:27082518 

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2747]
descendant of FYPO:0002125
abnormal protein localization to plasma membrane during vegetative growth

**Comment by mah11** [comment]
abnormal protein localization to plasma membrane at cell division site during vegetative growth FYPO:0005544

**Comment by mah11** [comment]
edit file: 3b73975600f7352daadf94928cd05c932c18a7de
release: 3e4b597b16433cc1d4ec56935ff216aaa2836528
