### ISSUE TITLE
FYPO:0005535 missing parentage

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2751]
increased histone H4-K16 acetylation at telomere FYPO:0005535

is not a child of 

ID 	FYPO:0005532
Ontology 	fission_yeast_phenotype
Term name 	abnormal histone H4-K16 acetylation

**Comment by mah11** [comment]
also noticed that I botched the xp ... fixed now, and link added

edit file: c200b859777ed28722a00311852236e74830b581
release: ca17f7c018c1f3a6f50ecac2a0740d651b787180
