### ISSUE TITLE
NTR decreased protein localization to cleavage furrow

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2755]
Term name
NTR  decreased protein localization to cleavage furrow

Parent
FYPO:0002869	decreased protein localization to cell division site

Def
A cellular process phenotype observed in the vegetative growth phase of the life cycle in which the localization of a protein to the cleavage furrow (GO:0032154) is decreased.

Ref
PMID:27082518

FYI
https://github.com/geneontology/go-ontology/issues/12556

**Comment by ValWood** [comment]
Term name
NTR decreased protein localization to cleavage furrow rim

Parent
FYPO:0002869 decreased protein localization to cleavage furrow

Def
A cellular process phenotype observed in the vegetative growth phase of the life cycle in which the localization of a protein to the cleavage furrow rim is decreased.

Ref
PMID:27082518

(I'm not completely sure  how to define cleavage furrow rim, so if this is not clear to you I will ask Jian-Qiu)

**Comment by mah11** [comment]
yes, of course it'll need a definition of cleavage furrow rim

**Comment by ValWood** [comment]
I have tentative defs which I am checking with the authors, will get back to  you...

**Comment by mah11** [comment]
decreased protein localization to cleavage furrow FYPO:0005551
  decreased protein localization to cleavage furrow rim FYPO:0005552

**Comment by mah11** [comment]
edit file: f60ef64b041e47900fcd4c23fc8df2509c03bb7a
release: 256754d4c284572089d920f8ed9bdab8139dce99
