### ISSUE TITLE
abolished histone H3-K9 dimethylation at centromere inner repeat

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2758]
related
abolished histone H3-K9 dimethylation at centromere CENP-A containing region

descendent of
FYPO:0004170	abolished histone H3-K9 dimethylation at centromere

standard def

fig 3 c
PMID:27334362

NB Usually the assays are for a specific repeat, bt the CENP-A region spans the inner core and the imr repeat
![repeats](https://cloud.githubusercontent.com/assets/7359272/17142664/dc031280-5348-11e6-98da-9ae60669e648.jpg)

**Comment by mah11** [comment]
abolished histone H3-K9 dimethylation at centromere inner repeat FYPO:0005554

**Comment by mah11** [comment]
edit file: f60ef64b041e47900fcd4c23fc8df2509c03bb7a
release: 256754d4c284572089d920f8ed9bdab8139dce99
