### ISSUE TITLE
Q-MT bundle phenotypes 	PMID:26124291

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2761]
To describe these 3

Q-MT bundle was either both thicker and longer (klp5Δklp6Δ, alp7Δ, and dis1Δ),
 just thinner (ase1Δ), 
or both shorter and thinner (mal3Δ and alp14Δ; Fig. 4, E and F). 
These results indicated that MAPs involved in interphase MT length regulation are also involved in shaping the Q-MT bundle in quiescence.

I'll link the GO term  discussed when requested

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/12561

**Comment by ValWood** [comment]
T-shaped cell during recovery from quiescence

abnormal microtubule bundle during recovery from quiescence

abnormal cell polarity during  recovery from quiescence

**Comment by mah11** [comment]
I take it "recovery from quiescence" = G0 to G1 transition?

**Comment by ValWood** [comment]
yep.

Now I think about it,  T-shaped cell is alway an "output of"  abnormal cell polarity
so could we add this relation too?

**Comment by mah11** [comment]
abnormal microtubule bundle FYPO:0005558
  thick stable microtubule bundle FYPO:0005559
  thin stable microtubule bundle FYPO:0005560
  long stable microtubule bundle FYPO:0005561
  short stable microtubule bundle FYPO:0005562
  long, thick stable microtubule bundle FYPO:0005563
  short, thin stable microtubule bundle FYPO:0005564
  abnormal microtubule bundle during G0 to G1 transition FYPO:0005565
  T-shaped cell FYPO:0005566
  T-shaped cell during G0 to G1 transition FYPO:0005567
  abnormal cell polarity FYPO:0005568
  abnormal cell polarity during G0 to G1 transition FYPO:0005569
  
renamed FYPO:000026 to make 'vegetative' explicit
added link FYPO:0005566 output_of FYPO:0005568

**Comment by mah11** [comment]
p.s. when the GO CC term is in, I'll be able to add xps that will get the new MT bundle terms organized better

**Comment by ValWood** [comment]
Weird, I was sure we already had T-shaped cell?

**Comment by mah11** [comment]
> Weird, I was sure we already had T-shaped cell?

see "renamed FYPO:000026 to make 'vegetative' explicit"

**Comment by ValWood** [comment]
yep ....

**Comment by mah11** [comment]
edit file: 746f58ea7398be3632fe74b5599808a6a26507e6
release: b23bd2763fe080f268e151c5bdaaf4117f1c5f22
