### ISSUE TITLE
ntr: abnormal nuclear transport during meiosis PMID:26483559

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2763]
abnormal nuclear transport during meiosis

A cellular process phenotype observed during meiosis/sporulation in which nuclear transport is abnormal.

supplied by Hui-Ju Yang
PMID:26483559
Fig. S2

**Comment by mah11** [comment]
abnormal nuclear transport FYPO:0005573
  abnormal nuclear transport during meiosis FYPO:0005574

renamed FYPO:000518 to make 'vegetative' explicit

**Comment by mah11** [comment]
edit file: 746f58ea7398be3632fe74b5599808a6a26507e6
release: b23bd2763fe080f268e151c5bdaaf4117f1c5f22
