### ISSUE TITLE
add synonym for population growth term

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2765]
can we add
"reduced vegetative cell population growth"
as a synonym for
"decreased vegetative cell population growth"

I always type this and I can never figure out why I cant find it....

![veg](https://cloud.githubusercontent.com/assets/7359272/17328843/bf208f8e-58b7-11e6-99ef-f45ff46e0aff.jpg)

**Comment by mah11** [comment]
added in
edit file: 746f58ea7398be3632fe74b5599808a6a26507e6
release: b23bd2763fe080f268e151c5bdaaf4117f1c5f22
