### ISSUE TITLE
normal protein localization after G0-G1 transition

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2772]
normal protein localization (after?) G0-G1? transition
I  forgot to request this one, or I wasn't sure how to word it?
curs/433d2f2e8d0427b7#

**Comment by mah11** [comment]
localization to any specific CC/destination?

(tangent: I wonder if it's worth putting the protein localization terms that don't specify a location in the soft-check file?)

**Comment by ValWood** [comment]
I think that's a good plan, I was going to suggest at some point. Its probably quite a lot at the moment but can have a look.....

For the mto1/2  its 'normal re-localization to nuclear membrane'

**Comment by mah11** [comment]
new terms
  normal protein localization to nuclear envelope FYPO:0005612
  normal protein localization to nuclear envelope during G0 to G1 transition FYPO:0005613

for FYPO:0005613 I put "relocalization" in a narrow synonym
renamed FYPO:0000838, FYPO:0004885-4887 to make 'vegetative' explicit

also added some terms to the soft-check file

**Comment by mah11** [comment]
edit file: 229df8d770aef4b0510aa521421dd9ca000cdd25
release: 3caf7d02c15e71d60f609bd7f528ea32bf8bf34d
