### ISSUE TITLE
	PMID:24947517 NTR: septation, cell separation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2776]
sepatation defect
decreased rate of cell separation
descendant of FYPO:0001972	(you see increased number of septated cells with this phenotype)
Fig 1 D

normal septum assembly
(septum assembly is normal, the cell separation step is abnormal)
Fig 1 D

**Comment by mah11** [comment]
new term
  decreased rate of cell separation after cytokinesis FYPO:0005628

because existing terms follow the model that septation = barrier septum assembly, added another synonym to FYPO:0000673

**Comment by mah11** [comment]
edit file: e2816903d4ae2f47002007968587dc9569ff77c7
release: 4b1d3545f1c805349439e356195f3a4a60356b77
