### ISSUE TITLE
PMID:26483559 duration of mitotic division

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2779]
Hui-Ju Yang  requested a slight change to the annotation here

required new term
normal duration of mitotic division
normal duration of mitosis

===
The 8th row: FYPO:0001007
    Comment: in the text of the result section
    Annotation extension: duration of mitotic division for nup132Δ, 29 ± 3 min
                                        duration of mitotic division for wild type, 31 ± 3 min

Best wishes,
Hui-Ju

**Comment by mah11** [comment]
normal duration of mitosis FYPO:0005632

**Comment by mah11** [comment]
edit file: c25adbc98d6aa70b5d5546fcda9e3fcf2d29ef84
release: 29a45a758b00fedb8ecd9abb0ec17625543a0302
