### ISSUE TITLE
PMID:26687354 cohesin loading

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2781]
Back to this one...I will finish it *one* day...I will hopefully try to LEGO this one at the workshop...

FYPO:0005555	decreased cohesin loading
could this be renamed
decreased mitotic cohesin loading (it is defined vegetatively)

**Comment by ValWood** [comment]
and 
FYPO:0005556	abolished cohesin loading

**Comment by ValWood** [comment]
FYPO:0005557	decreased cohesin unloading

**Comment by mah11** [comment]
text edits done in
edit file: c25adbc98d6aa70b5d5546fcda9e3fcf2d29ef84
release: 29a45a758b00fedb8ecd9abb0ec17625543a0302

forgot to update the xps; will close when that's done
