### ISSUE TITLE
ntr: sister chromatid separation during meiosis I, with normal disjunction PMID:21920317 

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2782]
I want to describe a phenotype where sister kinetochore split (bipolar attachment) , but segregation is normal....

fig 1D PMID:21920317

**Comment by ValWood** [comment]
sister chromatid separation during meiosis I leading to equational segregation of sister chromatids during meiosis I

So these are the 2 phenotypes.
I'm not sure if they exist, but I don;t think so?

**Comment by ValWood** [comment]
Hmm, I think I see a problem.

Sister chromatids can 'split' but become correctly separated is they have the correct SPB/kinetochore attachments, so its sort of 2 steps.

See Fig 3 for schematic
I guess we need to be clear about 
i) sister chromatid 'separation', chromatids can split' due to merotelic attachment.
and

these can be correctly co-segregated

ii) equational segregation during mieosis I is observed

**Comment by ValWood** [comment]
So currently
sister chromatid separation during meiosis I
equational sister chromatid segregation at meiosis I [exact]

could be
sister chromatid separation during meiosis I
  --equational sister chromatid segregation at meiosis I 

equational sister chromatid segregation at meiosis I 
defined as  sister chromatid separation during meiosis I leading to equations segregation
of sister chromatids
(or similar)

**Comment by mah11** [comment]
new terms
  sister chromatid separation during meiosis I followed by normal chromosome separation FYPO:0005633
  sister chromatid separation during meiosis I followed by equational sister chromatid segregation FYPO:0005634

I included a couple of synonyms, and can add more if you think of any that would be useful.

updated some comments to refer to FYPO:0005634 instead of FYPO:0003604

**Comment by mah11** [comment]
changes so far in
edit file: c25adbc98d6aa70b5d5546fcda9e3fcf2d29ef84
release: 29a45a758b00fedb8ecd9abb0ec17625543a0302

**Comment by ValWood** [comment]
I don't know what you added but I suggest
 increased merotelic attachment in meiosis I (assuming this causes the splitting phenotype)

**Comment by ValWood** [comment]
typo, term and def, 2nd separation->segregation

FYPO:0005633
Ontology	fission_yeast_phenotype
Term name
sister chromatid separation during meiosis I followed by normal chromosome separation

don't  stress ;)

**Comment by mah11** [comment]
No, "separation" is correct here, given GO's definitions. I'll correct the sibling.

**Comment by ValWood** [comment]
I mean segregation. Its the complete segregation which happens correctly.

**Comment by mah11** [comment]
The overall segregation process isn't completely normal if it includes the sister chromatids separating during meiosis I.

**Comment by ValWood** [comment]
OK, I always think of normal segregation as meaning that  everything is correctly segregated.

So here I am not only trying to capture that they eventually 'separate'  normally (I.e are no longer joined by cohesin or chiasmata or whatever) , but that everything is ***partitioned*** correctly (nothing is unequal, or . How can we capture that? Is normal disjuction more correct as that encompasses that all of the moving apart is correct?)

**Comment by mah11** [comment]
I would think if everything is partitioned correctly, separation must have been normal.

It occurs to me that this is one reason I bang on about distinguishing process phenotypes from  structure and other static phenotypes - in some cases you can reach a normal physical setup by either a normal process or one that's abnormal somewhere along the way, but not too badly to be put right.

"Disjunction" is just a word that's used in a slightly less precise way than the way GO uses "segregation" and "separation" in term names. It seems to me it's usually closer to "separation". (That said, the literature uses "chromosome segregation", "chromosome separation", and a zillion other words more loosely than GO does; that's one of the reasons we need ontologies.)

**Comment by mah11** [comment]
also, if you want that much detail, I could add a term for 'normal GO:0051758'

[Term]
id: GO:0051758
name: homologous chromosome movement towards spindle pole involved in homologous chromosome segregation
namespace: biological_process
def: "The directed movement of homologous chromosomes from the center of the spindle towards the spindle poles, mediated by the shortening of microtubules attached to the chromosomes, that contributes to meiosis I." [GOC:ai]
synonym: "homologous chromosome movement towards spindle pole during meiosis I" RELATED [GOC:dph, GOC:tb]
synonym: "meiosis I, homologous chromosome movement towards spindle pole" EXACT []
is_a: GO:0016344 ! meiotic chromosome movement towards spindle pole
relationship: part_of GO:0045143 ! homologous chromosome segregation

**Comment by mah11** [comment]
Closing because the originally requested terms are in. Open a new ticket if you want anything further.
