### ISSUE TITLE
PMID:21920317 meiotic chromosome segregation various

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2783]
NTR: continuous rate of spindle elongation during meiosis I (if possible to model, not critical)

standard defs
NTR: delayed protein localization to meiotic spindle during meiosis I
NTR: delayed protein localization to meiotic spindle from kinetochore during meiosis I
NTR: increased duration of meiotic metaphase I (or delayed anaphase onset, cant remember which way you model it), also need normal for this one

**Comment by mah11** [comment]
> NTR: continuous rate of spindle elongation during meiosis I

In light of #2647 and the discussion in https://github.com/geneontology/go-ontology/issues/12431, is there a difference between the "continuous elongation rate" here and the "premature elongation" requested for the mitotic case in #2647? If so, what is it, i.e. what should I put in the text definitions to explain the distinction?

(The rest look easy.)

**Comment by ValWood** [comment]
The continuous rate doesn't have the multistep elongation (i.e elongation in prophase/ constant length in metaphase, elongation in anaphase...it just elongates at the same rate...if its tricky leave it our, I don't think its really critical to demonstrate anything....

**Comment by mah11** [comment]
I'm not sure I'm any the wiser - in #2647 it sounded like you were describing the same thing, "no phase 2", as in no time window when the spindle length stays constant. But you called it "premature elongation" there.

So: are the mitotic and meiotic phenotypes different somehow? If not -- if they're the same in that they both skip the constant-length step -- they should be modeled the same way. Which do you prefer (for "premature" I could do an xp, but it's not a big deal if you prefer the other way).

**Comment by ValWood** [comment]
Its subtle...pink line!

![spindle length](https://cloud.githubusercontent.com/assets/7359272/17931750/de772e66-6a04-11e6-9bf4-e0d4c6ef44ac.jpg)

we can leave that one...I'm being OCD

**Comment by mah11** [comment]
That figure shows the difference between wild type and mutant during meiosis.

What I'm asking is whether there's a difference between the mutant phenotypes seen in _mitosis_ versus _meiosis_. Is the phenotype requested in the other ticket the same except it's seen in mitosis?

**Comment by ValWood** [comment]
I think they look similar, even though this is meiosis I (they look more similar because in meiosis they are studied by following univalents....
(Sorry I was answering a question you didn't ask)

**Comment by mah11** [comment]
OK, I've got the straightforward stuff in now anyway, and I'll leave this open until we decide what, if anything, else to add for mitotic or meiotic spindle elongation timing.

> NTR: increased duration of meiotic metaphase I (or delayed anaphase onset, cant remember which way you model it), also need normal for this one

I have done these as transition delay, with 'increased duration of phase' in related synonyms, but the synonyms were missing from the metaphase/anaphase transition delay terms until I added them just now.

the meiosis I term is FYPO:0005384
name: meiosis I metaphase/anaphase transition delay

**Comment by mah11** [comment]
new terms
  delayed onset of protein localization to spindle during meiosis I FYPO:0005635
  delayed onset of protein localization from kinetochore to spindle during meiosis I FYPO:0005636
  normal onset of metaphase/anaphase transition of meiosis I FYPO:0005637

**Comment by mah11** [comment]
changes so far in
edit file: c25adbc98d6aa70b5d5546fcda9e3fcf2d29ef84
release: 29a45a758b00fedb8ecd9abb0ec17625543a0302

**Comment by ValWood** [comment]
I forgot one
increased duration of  meiosis I metaphase

**Comment by mah11** [comment]
> increased duration of meiosis I metaphase

FYPO:0005384 - see https://github.com/pombase/fypo/issues/2783#issuecomment-242100813
