### ISSUE TITLE
PMID:21920317 abnormal meiotic centromere clustering child

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2787]
FYPO:0004086
Ontology	fission_yeast_phenotype
Term name
abnormal meiotic centromere clustering
Matching synonym	increased unclustered centromeres during meiosis
Definition
A cellular process phenotype in which centromere clustering is abnormal during one or both meiotic nuclear divisions. Centromeres are normally located in one or two clusters away from the spindle pole body during meiosis.

I would use this but there is a child
abnormal meiotic centromere clustering resulting in centromere-spindle pole body colocalization

which is not what I am describing, so I think I need a sibling?

![abnormal clustering](https://cloud.githubusercontent.com/assets/7359272/17967021/defba48a-6abc-11e6-8acf-1794d2c4fb93.jpg)

**Comment by ValWood** [comment]
So the meiotic centromeree (red cnp1 marker) are unclustered...but they aren't at the SPB.

**Comment by ValWood** [comment]
Hmm I guess they are unclustered and sort of towards the SPB. I think we are trying to describe the same phenotype here. Maybe the existing terms need merging and tweaking.

I would say that the unclustered centromere/kinetochore are 'irregular' on the spindle

**Comment by ValWood** [comment]
I think its probably OK..I'll use the parent, it fits

**Comment by mah11** [comment]
It's not wrong to use the parent. If the situation described by the existing child term can be distinguished in any cases (i.e. whatever mutant, not necessarily the one you're annotating now), there's no particular need to merge. It's also no problem to add a sibling now or later if we can define it (I could imagine "centromeres dissociate from the spindle pole body, but do not cluster with each other".)

**Comment by ValWood** [comment]
"centromeres dissociate from the spindle pole body, but do not cluster with each other"

actually that is happening here?

**Comment by mah11** [comment]
OK, then, I'll add the new term.

**Comment by mah11** [comment]
abnormal meiotic centromere clustering with centromeres dissociated from spindle pole body FYPO:0005640

**Comment by mah11** [comment]
edit file: 502037384246b921861b98a5686db1aa00aaf950
release: c136177d2f6ece14a68bf41de8de6b74323072c6
