### ISSUE TITLE
NTR: abnormal  kinetochore orientation at meiosis I PMID:21920317

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2790]
The  kinetochore is no longer oriented  so that if faces outwards (away from the chromosome)

fig 6 A PMID:21920317

**Comment by mah11** [comment]
did it thusly (with synonyms):
abnormal meiotic homologous chromosome biorientation resulting in abnormal kinetochore orientation FYPO:0005642

**Comment by mah11** [comment]
edit file: 502037384246b921861b98a5686db1aa00aaf950
release: c136177d2f6ece14a68bf41de8de6b74323072c6

**Comment by ValWood** [comment]
I'm looking at this again as I am not sure that I have got everything totally correct.

For this one the way I onderstand it is:

rec12 mutant abolished recombination
This causes to segregation defects at meiosis 1.
Somehow, recombination /chiasma formation at the centromeres is important  to form the popped our kinetochore structure orients the kinetochore in such a way that  which enables
biorientation.

So if this is correct, the biorientation does not cause the kineotchore misorientation, its the other way around....

**Comment by mah11** [comment]
I think I shall punt and just change "resulting in" to "with" in the term name, so it'll be:

abnormal meiotic homologous chromosome biorientation with abnormal kinetochore orientation

That will make it neutral with respect to which goes awry first, and make less work for me ;)

Any problem with that plan?

**Comment by ValWood** [comment]
Thats fine, thats what we see....

I'm going to ask the authors to check the final session for me to make sure that my interpretation does make sense. I keep getting confused, probably because I have spent so much time on mitotic chromosome segregation.  Hopefully I got it sort of right.... its basically lots of different coloured dots  subtly  closer together or further apart...

**Comment by mah11** [comment]
rejig done in
edit file: f14c0eac4a5a646b2d3a74ed10281625439e35db
release: 2e411809995df8079922d7b3d846b7b3324bc081
