### ISSUE TITLE
abnormally monopolar protein localization to cell tip child?

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2791]
should "abolished protein localization to non-growing cell tip"
be a child of: "abnormally monopolar protein localization to cell tip"?

**Comment by mah11** [comment]
Hmm. Are there any proteins that normally localize only to the non-growing tip? If so, localization of such a protein could be abolished and leave you with localization to no tips, not one.

So unless we can be sure that no protein is ever normally only found at the non-growing tip, it's not safe to add this link.

**Comment by Antonialock** [comment]
ah I see. I don't think it is safe to add it then, cheers.
