### ISSUE TITLE
Correction to chromosome separation term

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2794]
I think I got this wrong too...
https://github.com/pombase/fypo/issues/2782

So this is what I know:

Early on, you can see that the kinetochores are slightly pulled apart, but segregation ends up normal. I was calling this '
sister chromatid separation during meiosis I '. I think this is wrong because we don't know what happens to the rest of the sister chromatid arms.
I was assuming that the arms were separated in the type II splitting (see the schematic in  figure 3 C), but there is nothing really to show that they do...)

I now wonder if what we are seeing is 
1) no recombination, no chiasma, kinetochores not oriented or fused correctly
2) but arms are still joined by cohesin (and shugoshin in type I )

3) some separation of ONLY the centromere kinetochores, can occur, because of the lack of chiasma, this causes biorientation,  and the tension of the biorentation allows kinetochores to be pulled slightly apart
4) However, . they come back together,  presumably because separation never really occurs

So instead of 
sister chromatid separation during meiosis I followed by normal chromosome separation

just call these
split kinetochores  during meiosis I followed by normal chromosome separation

Does that seem better?

![fig](https://cloud.githubusercontent.com/assets/7359272/18012480/89b2ae9c-6bb1-11e6-88ef-8c7d1a787fd8.jpg)

**Comment by ValWood** [comment]
Note that I was lumping the type I and type II splitting because  both result in co-segregation, and it only appeared to be a difference in severity.

**Comment by mah11** [comment]
Well, I can adapt the terms I added for #2872, since there's no danger of throwing off any other annotations. BUT it's going to take more extensive work than just renaming them.

The existing split kinetochore term, FYPO:0002650, is defined (correctly) as a structural phenotype, so I'll have to add a term for the structural split kinetochore aspect in meiosis, and then craft some links to the rejigged terms. It's all doable, but will take a bit more time than I have today.

(FYPO:0002650 is also defined by text and xp as vegetative/mitotic, but that is a simple name change to adjust.)

note to self: affects FYPO:0005633, FYPO:0005634, FYPO:0005641

**Comment by mah11** [comment]
done, with a few new terms
  abnormal kinetochore morphology FYPO:0005646
  split kinetochore FYPO:0005647
  split kinetochore during meiosis I FYPO:0005648

term names now
  FYPO:0005633 'abnormal chromosome segregation during meiosis I with split kinetochore and normal chromosome separation'
  FYPO:0005634 'abnormal chromosome segregation during meiosis I with split kinetochore and equational sister chromatid separation'
  FYPO:0005641 'abnormal chromosome segregation during meiosis I with split kinetochore, lagging chromosomes, and normal chromosome separation'

edit file: f14c0eac4a5a646b2d3a74ed10281625439e35db
release: 2e411809995df8079922d7b3d846b7b3324bc081

**Comment by ValWood** [comment]
These look a bit strange.
Could they just be called

FYPO:0005633 'split kinetochore in meiosis I and normal chromosome separation'

etc.
(they could still be under abnormal segregations because of the kinetochore problem, but I don't think we need to say this explicitly in the term names?)

**Comment by mah11** [comment]
I would prefer not to name process phenotypes in a way that makes them look like structure phenotypes.

**Comment by ValWood** [comment]
Yeah, I'm still a bit confused about what is a process phenotype and what is a structure phenotype. Is this is a combination of both?
Not to worry anyway. I know what this means. There might be a better way to do it once I understand better what is going on.

I also asked the author to look closely at the phenotypes  to see if I  interpreted correctly so 
hopefully they will tell us if I got anything totally wrong.....

**Comment by mah11** [comment]
Yeah, I guess "combination of both" is the least head-melty way to put it. It's a phenotype where a process goes somewhat wrong, and the wrongness shows up partly in processy ways but also with a structural problem visible.

**Comment by mah11** [comment]
last bit addressed in #3298
