### ISSUE TITLE
question about cut

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2802]
I didn't see this under 
"inviable vegetative cell" ? (but the cut with mitotic catastrophe are there. But all cuts are inviable?

**Comment by mah11** [comment]
Cut itself is a "grandchild" of inviable veg via is_a:

inviable vegetative cell
[is_a] septation following abnormal mitotic chromosome segregation
 - [is_a] cut

whereas the mitotic catastrophe/cut terms have inviable and cut as parts, e.g. 

id: FYPO:0001048
name: mitotic catastrophe with cut
is_a: FYPO:0001047 ! mitotic catastrophe
intersection_of: FYPO:0000002 ! cell phenotype
intersection_of: happens_during GO:0072690 ! single-celled organism vegetative growth phase
intersection_of: has_part FYPO:0000141 ! abnormal mitotic sister chromatid segregation
intersection_of: has_part FYPO:0001204 ! mistimed mitosis
intersection_of: has_part FYPO:0001489 ! inviable vegetative cell
intersection_of: has_part FYPO:0003165 ! cut

(not all bits shown)

I don't have a good way to work around the way Canto shows is_a and has_part links for these terms; anything that might make cut show up directly under inviable veg would mess up something else.

**Comment by ValWood** [comment]
No thats fine, I should have known it was under there. I didn't read the list properly....
