### ISSUE TITLE
cdr- (changed division response) phenotype PMID:12399381

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2805]
I want to describe the phenotype of cdr mutants.

Described thus:

We have reisolated sal3 in an insertional mutagenesis screen for c hanged division response (Cdr)􏰝 mutants that are defective in reducing the size threshold for cell division in response to nitrogen deprivation.

Now, these mutants (at least this one, is elongated to start with) and stays elongated upon  Nitrogen starvation.

I don't  know if this is a general characteristic of elongated genes,  (  and applies to all "viable elongated), or if it is only a feature of a subset of elongated genes....

![sal3](https://cloud.githubusercontent.com/assets/7359272/18386358/7c5dd89c-768e-11e6-9f53-a4cf2416bd84.jpg)

I presume we don't have the term, because when I rant the 4 cdr genes through Angeli they have no common phenotype annotation.....

I might add more to this ticket, or even close it...

**Comment by ValWood** [comment]
Maybe just 
viable elongated vegetative cell during nitrogen starvation would do it
we have
viable elongated vegetative cell during phosphate starvation

**Comment by ValWood** [comment]
cdr1 and 2 are annotated to this term, will need to be moved down to the new term...this phenotype is viable, vegetatative
http://www.pombase.org/spombe/related/FYPO:0000998

Oddly this term did not show in the Angeli enrichment even though some  transporter terms which only had 2 annotations did, and these would have a much higher number of annotation thatn this term, which only has 21....I need to report that....

**Comment by ValWood** [comment]
Angeli was fine. I thought the enrichment was to a transporter term, but it was to a domain which only occurs twice in the genome and included  2  out of my list of 4

**Comment by mah11** [comment]
viable elongated cell during nitrogen starvation FYPO:0005664

sounds like that will sort it, so closing

edit file: dcace5c74b66df03601e5378512255518d09c607
release: 0637ba5ebee9ce3c6b523430d2c37166e78f3898
