### ISSUE TITLE
   PMID:12399381 G1 and G2 arrest upon nitrogen starvation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2806]
are FYPO:0003345 and FYPO:0001001
2 ways of saying the same thing?

![same thing](https://cloud.githubusercontent.com/assets/7359272/18387616/7691fcac-7695-11e6-93fb-60744a313650.jpg)

**Comment by mah11** [comment]
Not exactly, although I suppose we could add the link FYPO:0001001 is_a FYPO:0003345. 

FYPO:0003345 says cells don't arrest in G1 as normal, but doesn't say anything further; it leaves open the possibility that they may arrest in G2 instead (FYPO:0001001) or do something else, such as not arrest cleanly in any phase.

**Comment by ValWood** [comment]
When asynchronous wild- type cells are rapidly deprived of nitrogen, they divide approximately twice, increasing the initial cell numbers by 􏲦3.6 times before arresting in G1 (Young and Fantes 1987). In contrast, the cell number of the sal3 disruptant increased by only about one-half of the wild-type level during nitrogen deprivation (Figure 2C), indicating the occurrence of only a single cell division. Furthermore, FACS analysis revealed that the sal3 disruptant accumu- lated a G2 peak during an extended period of nitrogen deprivation while wild-type cells displayed a G1 peak under the same conditions (Figure 2D).

**Comment by Antonialock** [comment]
"Altogether, these results demonstrate that loss of sal3+ causes a failure to undergo the second cell division and G1 arrest in response to nitrogen starvation."

I guess you want a child of this term to specify that the second division doesn't happen
Term name 	abnormal cell cycle arrest in mitotic G2 phase during nitrogen starvation

**Comment by ValWood** [comment]
I don't think this is critical. I was just curious.


I guess this is just because  the cells can't get through  the first G2... I don't even think I need to abolished arrest in G1. Originally I was thinking it was arresting in the subsequent G2....
