### ISSUE TITLE
NTR: PMID:11260263 cytoskeleton

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2807]
abnormal actin cytoskeleton during meiosis

**Comment by mah11** [comment]
abnormal actin cytoskeleton FYPO:0005665
  abnormal actin cytoskeleton during meiosis FYPO:0005666

edit file: dcace5c74b66df03601e5378512255518d09c607
release: 0637ba5ebee9ce3c6b523430d2c37166e78f3898
