### ISSUE TITLE
nitrogen arrest terms to check

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#2809]
two cell divisions prior to cell cycle arrest in mitotic G1 phase in response to pheromone 
abolished / single cell division prior to G0 entry

**Comment by mah11** [comment]
let me know if/when there's anything for me to do in the ontology for this

**Comment by Antonialock** [comment]
yep

**Comment by mah11** [comment]
is this still "live"?

**Comment by ValWood** [comment]
@Antonialock  for you

**Comment by mah11** [comment]
ancient, and not clear whether anything needs doing
