### ISSUE TITLE
ntr: advanced loaclization to nucleus 	PMID:12399381

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2810]
descendant of
FYPO:0001129	abnormal protein localization to nucleus during vegetative growth

**Comment by mah11** [comment]
premature protein localization to nucleus during vegetative growth FYPO:0005667

edit file: dcace5c74b66df03601e5378512255518d09c607
release: 0637ba5ebee9ce3c6b523430d2c37166e78f3898
