### ISSUE TITLE
sensitive to cAMP

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2811]
How do I do this?

term?
condition?

**Comment by mah11** [comment]
Term if the phenotype is an effect on population growth; condition for any other phenotypes.

**Comment by ValWood** [comment]
OK, I need a term for this then pls.....

**Comment by ValWood** [comment]
as you can imagine...no hurry...at all

**Comment by mah11** [comment]
sensitive to cAMP FYPO:0005668

edit file: 908d32eb3f1f1ef4f1761ae3d4faf4d98ad57e0c
release: 414e6fc960b435814462dd0d012605f0ff5e6823
