### ISSUE TITLE
cut, broad def

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2813]
I thought we had a term,  which was a parent of

FYPO:0003165 (classical cut)
and
FYPO:0003166

Sometimes people refer to both as 'cut' even though the cut really means the nucleus is bisected (becasue they co occur and are caused by the same defect).

The closest I found is
FYPO:0001973	abnormal cell separation after cytokinesis, with abnormal nuclear division
A cellular process phenotype observed in the vegetative growth phase of the life cycle in which nuclear division, cytokinesis and subsequent cell separation are abnormal, resulting in the formation of a cell in which an undivided mass of DNA is located on one side of the septum. The septum does not degrade.

but it has neither of the above as descendants (although the term name would fit the 'classical cut' the def is too restrictive)

Anyone know what I mean?

**Comment by ValWood** [comment]
i.e a term for everything which is "cytokinesis without nuclear division"

**Comment by mah11** [comment]
[Term]
id: FYPO:0000229
name: septation following abnormal mitotic chromosome segregation
alt_id: FYPO:0000322
alt_id: FYPO:0000323
def: "An inviable phenotype observed in the vegetative growth phase of the life cycle in which a cell undergoes septation despite abnormal mitotic chromosome segregation, and gives rise to inviable daughter cells." [PomBase:jh, PomBase:mah, PomBase:vw]
synonym: "septation following abnormal chromosome segregation during mitotic cell cycle" RELATED [PomBase:mah]
synonym: "septation following abnormal mitotic chromosome segregation during vegetative growth" EXACT [PomBase:mah]
is_a: FYPO:0001489 ! inviable vegetative cell
relationship: has_part FYPO:0000141 ! abnormal mitotic sister chromatid segregation
relationship: has_part FYPO:0003250 ! premature septation

[Term]
id: FYPO:0003165
name: cut
is_a: FYPO:0000229 ! septation following abnormal mitotic chromosome segregation

[Term]
id: FYPO:0003166
name: monoseptate vegetative cell with binucleate and anucleate compartments
is_a: FYPO:0000229 ! septation following abnormal mitotic chromosome segregation

**Comment by ValWood** [comment]
That the one....

**Comment by ValWood** [comment]
Can this have "cut" as broad synonym (because some people use it 'loosely' for this...

Cuts are indicative of cells undergoing cytokinesis without nuclear division and are scored by counting cells with a single nucleus located to one side of the division plate or cells with nuclei bisected by the division plate (Fig. 3D).

**Comment by ValWood** [comment]
can I get 

septation following abnormal mitotic chromosome segregation in response to HU
 septation following abnormal mitotic chromosome segregation in response to MMS


(these are important because they are used to distinguish abolished replication and DNA dame checkpoints respectively- there are some 'true cut' descendants with this differentia)

increased septation index in response to MMS
