### ISSUE TITLE
NTR reduced protein localization to nucleus during mitosis PMID:10523629

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2815]
standard def
reduced protein localization to nucleus during mitosis

**Comment by mah11** [comment]
decreased protein localization to nucleus during mitosis FYPO:0005672

edit file: 19ebdbdb0e2cae0d1b90961a57115efd15b9bdf4
release: 3a2745c6a0a452731fd890b1799aca8fb4b94a41
