### ISSUE TITLE
ntr: loss of viability in response to HU PMID:8497322

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2816]
A cell population phenotype in which a smaller than normal proportion of cells in the population remains viable when cells are exposed to hydroxyurea

**Comment by ValWood** [comment]
and 
loss of viability in response to UV

**Comment by mah11** [comment]
loss of viability following cellular response to hydroxyurea FYPO:0005704
  loss of viability following cellular response to UV FYPO:0005705

edit file: b195a9d2b07819052614b9be249a6853a8888f7e
release: 99819ea12811962b4b71c6793722c4377f141fde
