### ISSUE TITLE
query 	decreased 14-3-3 protein binding

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2820]
```
I was wondering why we have this gene product specific binding term?
```

decreased 14-3-3 protein binding

(I just  used it, but he "normal decreased protein binding" term and specifying path GPs would work the same?)

**Comment by mah11** [comment]
Users would have to do a tiny bit more work to make the 14-3-3 connection if the annotation just uses 'decreased protein binding' and extensions, but I don't think it's a big deal either way.

I just implicitly follow GO - if it has a binding term I'll make a distinct binding phenotype term; if they rethink and obsolete or merge I'll merge FYPO terms.

**Comment by ValWood** [comment]
But we don't annotate to  gene product specific binding terms (my understanding is that they will disappear from GO eventually....)

**Comment by mah11** [comment]
I'm willing to let them do the heavy thinking about what belongs in GO,  and just keep FYPO consistent. They still seem more inclined to tolerate protein family or domain binding terms, at least in the short run, than outright individual gene product binding.

If you find areas where it's worth the effort of diverging from GO, it might help to raise questions promptly ... FYPO:0004636 was added over a year ago for #2196.

**Comment by mah11** [comment]
will merge if & when GO does

**Comment by mah11** [comment]
merged

edit file: 48bb20dca3bc5c96c788dee0894d8586ea0770c6
release: 3d6d8217e41d38e07e812c7f918f3ea4487460dd
