### ISSUE TITLE
microtubule dynamics terms PMID:16394105

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2821]
decreased migrotubule polymerization
synonym decreased microtubule growth

decreased microtubule shrinkage
synonym decreased microtubule shrinkage

both the growth and shrinkage rates were decreased down to 33 and 60%, respectively, in the atb2-983 mutant (Table 2).

**Comment by ValWood** [comment]
and normal microtubule cytoskeletoon morphology

**Comment by mah11** [comment]
> and normal microtubule cytoskeleton morphology

not specific to vegetative growth? 'cos we have FYPO:0003702 normal microtubule cytoskeleton morphology during vegetative growth

**Comment by ValWood** [comment]
Yep thats what I need. I think I landed in the wrong place...

**Comment by mah11** [comment]
do you still want to first 2 terms about polymerization/depolymerization added?

**Comment by ValWood** [comment]
oh yes!

**Comment by mah11** [comment]
decreased microtubule polymerization FYPO:0005681
  decreased microtubule depolymerization FYPO:0005682

added 'growth' and 'shrinkage' synonyms to MT polymerization & depolymerization terms respectively

edit file: 774d5dd9b89cea0676a37c022a8b71b72d5d1585
release: e0bbc398974d9c8b721de72cddd6079c2c82ce6a
