### ISSUE TITLE
PMID:16394105 cell cycle duration terms

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2822]
increased duration of mitotic prophase
increased duration of mitotic prometaphase

**Comment by ValWood** [comment]
increased duration of mitotic anaphase B

**Comment by mah11** [comment]
increased duration of mitotic prophase FYPO:0005683
  increased duration of mitotic prometaphase FYPO:0005684

edit file: 774d5dd9b89cea0676a37c022a8b71b72d5d1585
release: e0bbc398974d9c8b721de72cddd6079c2c82ce6a
