### ISSUE TITLE
normal protein localization to mitotic spindle PMID:16394105

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2824]
child of

normal protein localization during mitosis

standard def
PMID:16394105

**Comment by mah11** [comment]
it's FYPO:0002966 normal protein localization to mitotic spindle

leave this open to remind me to check its ancestry - I suspect I'll have to assert the 'during mitosis' parent

**Comment by mah11** [comment]
asserted link FYPO:0002966 is_a FYPO:0004328

edit file: 774d5dd9b89cea0676a37c022a8b71b72d5d1585
release: e0bbc398974d9c8b721de72cddd6079c2c82ce6a
