### ISSUE TITLE
NTR: decreased mitotic spindle pole body oscillation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2825]
partner term of

FYPO:0005349
Ontology	fission_yeast_phenotype
Term name
increased mitotic spindle pole body movement
Definition
A cellular process phenotype observed in the vegetative growth phase of the life cycle in which the mitotic spindle pole body (SPB) moves rapidly back and forth over a large area. Normally, the SPB may move slightly but such movement is restricted to a small space.

Perhaps revise the definition to 
A cellular process phenotype observed in ***mitotic prophase****

(I wonder if the synonym 'oscillation' is a better name than movement, because there is other movement apart from the 'rapid oscillation' described here?)

**Comment by mah11** [comment]
I looked at the ticket for FYPO:0005349 and didn't see any reason not to use "oscillation" in the name, so no problem to swap name & synonym.

> Perhaps revise the definition to
> A cellular process phenotype observed in mitotic prophase

No, the "observed in the vegetative growth phase of the life cycle" bit is the standard boilerplate for all "vegetative" term defs. I'll put something about prophase elsewhere in the def.

**Comment by ValWood** [comment]
OK

**Comment by mah11** [comment]
Looking at this again ... the FYPO:0005349 def implies that oscillatory movement isn't really a normal thing for the mitotic SPB to do. Was that incorrect? If oscillation can be decreased by a mutant, there must be some oscillation happening in wild type, and if that's true we ought to rephrase the FYPO:0005349 def to just say "more than normal".

**Comment by ValWood** [comment]
It appears to be normal, but I hadn't come across it in mitosis before this paper (or at least it hadn't stuck...)

PMID:16394105
Sister Chromatid Oscillation during Prometaphase Is Less Dynamic in the atb2-983 Mutant Independent of Mal3 Dysfunction
It is shown that during mid-mitosis, fission yeast kineto- chores display, like animal cells, back-and-forth oscillation between the two poles, which is likely to correspond to the prometaphase state (Saitoh et al., 1997; Garcia et al., 2002b).

**Comment by mah11** [comment]
That seems to be about kinetochores moving between SPBs, not the SPB itself moving ...?

**Comment by mah11** [comment]
for now, I've swapped the name and "oscillation" synonym FYPO:0005349

edit file: 774d5dd9b89cea0676a37c022a8b71b72d5d1585
release: e0bbc398974d9c8b721de72cddd6079c2c82ce6a

**Comment by ValWood** [comment]
Durr yes sorry kinetochore oscillation... that makes more sense!

**Comment by ValWood** [comment]
Although: PMID:19001497
 and a strong reduction in SPB oscillations, which probably reflects reduced interactions between cytoplasmic MTs and the SPB (Fig. 1E; supplementary material Movies 2-4).

**Comment by mah11** [comment]
new term
   mitotic spindle pole body oscillation FYPO:0005691

edited def FYPO:0005349

I think that's everything for this one ...

edit file: 11877ed76fce9ae9583da5947f28b4c5e4ee6c6c
release: db5d4e543f7f6dbe443a927feaedadd5e3158917
