### ISSUE TITLE
decreased interphase microtubule arrays

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2826]
I guess this could also be 
decreased interphase microtubule bundles (at least thats what I see 1 or 2 bundles instead of  3 or 4?)

child of
microtubule bundles present in decreased numbers

**Comment by ValWood** [comment]
couls also be called 
cytoplasmic microtubules  present in decreased numbers

and be a parent of
cytoplasmic microtubules nucleated from equatorial microtubule organizing center present in decreased numbers

**Comment by mah11** [comment]
I would go with whatever is more accurate - bundles or microtubules. Which is better for your annotations? Either way, I can include "microtubule arrays" in a synonym.

**Comment by ValWood** [comment]
bundles is what I have always used. They call them arrays in this paper though....

**Comment by mah11** [comment]
microtubule bundles present in decreased numbers during mitotic interphase FYPO:0005686

added "microtubule array" RELATED synonyms to "microtubule bundle" terms

edit file: 774d5dd9b89cea0676a37c022a8b71b72d5d1585
release: e0bbc398974d9c8b721de72cddd6079c2c82ce6a
