### ISSUE TITLE
eMTOC

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2827]
FYPO:0004624	abolished equatorial microtubule organizing center assembly

Add synonym  "eMTOC absent" 

Add comment

Consider also FYPO:0003126	post-anaphase array absent from cell
(post anaphase array is nucleated from the eMTOC)
or should that have a has_output?

**Comment by mah11** [comment]
"eMTOC absent" would be a structural description, and FYPO:0004624 is a process phenotype (usual distinctions and annotation advice apply), so if I do a synonym it'll be 'related' scope.

**Comment by ValWood** [comment]
I think that is OK... its kins of both

First they show:
Notably, although mitotic cells contained a normal spindle, an EM- TOC was not detected in late anaphase cells (Figure 3, A and C). As a result, septating cells did not contain a PAA of microtubules.

then
Given that the EMTOC was not observed in mto2􏰁 cells, we analyzed the localization of individual 􏰀-TuC compo- nents in mto2􏰁 cells.

Hence, we conclude that mto2􏰁 cells are defective in the localization of the 􏰀-TuC to the EMTOC.

since emtoc=
A microtubule organizing center formed by a band of gamma-tubulin that is recruited to a circumferential band of F-actin at the midpoint of a cell and which nucleates microtubules from the cell division site at the end of mitosis. 
PMID:11792817

it seems that assembly is abolished?

**Comment by mah11** [comment]
added new term
  equatorial microtubule organizing center absent from cell FYPO:0005687

and link FYPO:0004624 has_output FYPO:000568

edit file: 774d5dd9b89cea0676a37c022a8b71b72d5d1585
release: e0bbc398974d9c8b721de72cddd6079c2c82ce6a
