### ISSUE TITLE
add condition "gamma radiation"

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2829]
I can't find anything.....

curs/f3b2e78baad1483c

**Comment by ValWood** [comment]
If you can add this next time you are working I can get this session through...

**Comment by Antonialock** [comment]
I wonder if you are annotating to
normal mitotic G2/M phase transition + the condition "gamma radiation"

Where I may have annotated to
normal cell cycle regulation during cellular response to ionizing radiation during mitotic G2 phase

**Comment by Antonialock** [comment]
For the 
mitotic G2/M transition delay 

I would have requested a more specific term. I think the DNA damage makes it different from a 'normal' laboratory cell cycle.

**Comment by Antonialock** [comment]
but I added PECO:0000305 ionizing radiation (to match FYPO)

**Comment by Antonialock** [comment]
Ok, the term 
normal cell cycle regulation during cellular response to ionizing radiation during mitotic G2 phase 
sounds pretty horrendous...but I think we need to make sure we are consistent here.... what do you think?
 eg mitotic G2/M transition delay during cell resp to ionizing radiation
or
normal cell cycle regulation during cellular response to ionizing radiation

**Comment by ValWood** [comment]
I'lll go back to this one and see what I was trying to capture ! leave it with me...

**Comment by ValWood** [comment]
I think what I was trying to capture was
abolished mitotic G2 DNA damage checkpoint (condition:  ionizing radiation)

(this results in a G2 transition delay which was abolished in the mutant)

I still think the condition is essential as the checkpoint would not be active without it.

**Comment by Antonialock** [comment]
Condition should be available by now :-)
