### ISSUE TITLE
ntr:  abolished protein localization to eMTOC 	PMID:15800064

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2830]
PMID:15800064
abolished protein localization  to eMTOC

standard def

**Comment by ValWood** [comment]
That doesn't really make sense does it? You can't have abolished protein localization to a component whose assembly is abolished.
Should this be abolished localization to medial cortex  (or some paretn of eMTOC) maybe?

**Comment by ValWood** [comment]
Hence, we conclude that mto2􏰁 cells are defective in the localization of the 􏰀-TuC to the EMTOC.
hmm....

**Comment by ValWood** [comment]
This indicates that Mto2p, like Mto1p, is required to recruit and/or stabilize the 􏰀-TuC in the medial region of the cell to establish a functional EMTOC structure. 
...An EMTOC was not assembled in any of 17 mitotic mto2􏰁 cells examined, even though spindle disassembly was readily observed (Figure 3C and Fig 3video2 and Fig 3video3)

**Comment by mah11** [comment]
I'm now a bit confused - do you want the new term or not? I could imagine some protein failing to localize to an assembled eMTOC, although I have no idea if there are any real examples and if it's not the best term to use for the mto2 mutant, we can wait until an actual example crops up.

**Comment by ValWood** [comment]
Sorry some information is missing.
In this paper the authors say that in the delation eMTOC assembly is abolished (mto2 delta).
Later that say that for the same mutant (mto2 delta)  "abolished protein localization to eMTOC"  for  mto1 localization.

This seems odd to say because there is no eMTOC in this mutant.... so instead I was thinking that, as they are trying to show that mto1 is dependent on mto2 for normal localization, instead I would say that mto1 no longer localizes to the medial cortex.
Does that make sense?

**Comment by mah11** [comment]
That was all in the earlier comments, but it doesn't answer the question I posed: do you want the "abolished protein localization to eMTOC" term added now?

**Comment by ValWood** [comment]
Ah OK, no I dont need it, but if you have made it it can stay.

**Comment by mah11** [comment]
OK. I haven't added it, but if I had I wouldn't fuss. I'll close this, since the medial cortex localization terms exist.
