### ISSUE TITLE
NTR: inviable binucleate aseptate cell with mitotic cell cycle arrest before cell separation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2831]
FYPO:0003825 - inviable binucleate aseptate cell with mitotic cell cycle arrest in G2 before cell separation)
A cell phenotype observed in the vegetative growth phase of the life cycle in which a cell is inviable and has two nuclei but no septum, and the mitotic cell cycle is arrested with nuclei in G2 phase." 

the cells have done mitosis,  but the 2 nuclei arrest in a  G2 state in the following cell cycle (I.e they complete S-phase before they arrest). 

We would not always know this though so we probably need

NTR inviable binucleate aseptate cell with mitotic cell cycle arrest before cell separation

as a parent

**Comment by mah11** [comment]
inviable binucleate aseptate cell with mitotic cell cycle arrest before cell separation FYPO:0005689

edit file: 774d5dd9b89cea0676a37c022a8b71b72d5d1585
release: e0bbc398974d9c8b721de72cddd6079c2c82ce6a
