### ISSUE TITLE
interphase and mitotic microtubule nucleation PMID:19001497

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2833]
Interphase (cytoplasmic) microtubules, can be nucleated from the cytoplasm, or from the SPB.

There are mutants where 'cytoplasmic microtubule nucleation" is abolished, BUT   interphase  microtubules are present in the cytoplasm, because they 
"These intranuclear MTs eventually escape into the cytoplasm, acting as progenitors of essentially all cytoplasmic MTs in the mutant cells and forming abnormal MT bundles that often curve around the cell tips"

Also, cytoplasmic (astral) microtubules exist after during mitosis?
so not all cytoplasmic microtubules are interphase microtubules.

Soo....I think we need to make
NTR abnormal interphase microtubule nucleation from cytoplasm
--NTR abnormal interphase microtubule nucleation from iMTOC
--NTR abnormal interphase astral microtubule nucleation (def include: occurs from cytoplasmic side of SPB)
plus "abolished" and "decreased" for all

and 

"NTR abnormal/abolished astral microtubule nucleation"
--NTR abnormal interphase astral microtubule nucleation (def include: occurs from cytoplasmic side of SPB)
--NTR abnormal mitotic astral microtubule nucleation (def include: occurs from cytoplasmic side of SPB)

**Comment by ValWood** [comment]
"interphase cytoplasmic microtubule nucleation" might be better wording?

**Comment by mah11** [comment]
It's going to help _a lot_ if you can define what is and isn't covered by "interphase microtubule".

If some astral microtubules hang around after mitosis, then either (a) "interphase microtubule" includes those astral microtubules, _or_ (b) "interphase microtubule" doesn't simply mean "a microtubule that exists during interphase".

**Comment by ValWood** [comment]
I will need to check what people refer to as interphase microtubules.
@jvhayles do you know? I  can ask Ken...

**Comment by ValWood** [comment]
I have altered the above request a little.

We should probably stop calling them "interphase  microtubules". This can be a related synonym.

We should refer to "cytoplasmic microtubules during interphase" .  But "Interphase cytoplasmic microtubules" can't NOT include  the cytoplasmic microtubules  generated from astral microtubules. 
Does this help:

Only a small number of cytoplasmic MTs are present at any given time in fission yeast (Hoog et al., 2007), and these can be imaged by expressing GFP-tubulin at physiological concentrations. During interphase, MTs are nucleated not only from the spindle pole body  but also from several interphase microtubule organizing centre ‘satellite’ particles (iMTOCs) present on the nuclear envelope, in the cytoplasm and on MTs themselves. During late mitosis, cytoplasmic astral MTs analogous to those seen in budding yeast are nucleated from the duplicated SPBs.

**Comment by mah11** [comment]
OK, I think the existing terms can all be adjusted without much pain to "cytoplasmic microtubules [or microtubule nucleation] during interphase" - def text will need editing too, but that should be straightforward. I may have time to look at it properly tomorrow.

**Comment by mah11** [comment]
and would this be OK for the new terms?

abnormal cytoplasmic microtubule nucleation during mitotic interphase
-- abnormal microtubule nucleation from iMTOC [is "during mitotic interphase" needed in the name for this one?]
-- abnormal astral microtubule nucleation during mitotic interphase

and 

abnormal astral microtubule nucleation
-- abnormal astral microtubule nucleation during mitotic interphase
-- abnormal astral microtubule nucleation during mitosis

**Comment by ValWood** [comment]
Don't worry if it needs to wait until you get back...

Above looks perfect. No need for during interphase from iMTOC .....

**Comment by ValWood** [comment]
Listing ALL the precise terms I need for annotation of this paper

rename
FYPO:0004619	cytoplasmic microtubules nucleated from equatorial microtubule organizing center absent from cell
to
abolished microtubule nucleation from eMTOC?

NTR: abolished astral microtubule nucleation during mitosis
NTR: normal cytoplasmic microtubule nucleation from the SPB during interphase
NTR abolished microtubule nucleation from the iMTOC (these are interphase cytoplasmic but this should be implicit from therm)
NTR: normal protein localzation to mitotic SPB
NTR: abolished protein localization to eMTOC
NTR: abolished protein localization to iMTOC
NTR: decreased mitotic SPB oscillation
NTR decreased cytoplasmic microtubule nucleation during interphase (not sure which MTOC)
NTR: abolished cytoplasmic microtubule nucleation 
NTR: abolished cytoplasmic microtubule nucleation from the SPB  during interphase

I think that's it. Phew!

**Comment by mah11** [comment]
new terms
  abnormal microtubule nucleation FYPO:0005692
  abolished cytoplasmic microtubule nucleation FYPO:0005693
  decreased cytoplasmic microtubule nucleation during mitotic interphase FYPO:0005694
  abolished astral microtubule nucleation during mitosis FYPO:0005695
  abolished cytoplasmic microtubule nucleation from interphase microtubule organizing center FYPO:0005696
  abolished cytoplasmic microtubule nucleation from spindle pole body during mitotic interphase FYPO:0005697
  abolished microtubule nucleation from equatorial microtubule organizing center FYPO:0005698
  normal cytoplasmic microtubule nucleation from spindle pole body during mitotic interphase FYPO:0005699
  abolished protein localization to equatorial microtubule organizing center FYPO:0005700
  abolished protein localization to interphase microtubule organizing center FYPO:0005701
  abnormal protein localization to microtubule organizing center FYPO:0005702

renamed existing terms from using "interphase microtubule" to "microtubule [x] during mitotic interphase"; adjusted defs accordingly

edit file: 11877ed76fce9ae9583da5947f28b4c5e4ee6c6c
release: db5d4e543f7f6dbe443a927feaedadd5e3158917
