### ISSUE TITLE
NTR increased duration of mitotic anaphase B PMID:16394105

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2837]
NTR increased duration of mitotic anaphase B
child of
FYPO:0000618	increased duration of mitotic anaphase

standard def
PMID:16394105

**Comment by mah11** [comment]
increased duration of mitotic anaphase B FYPO:0005706

edit file: b195a9d2b07819052614b9be249a6853a8888f7e
release: 99819ea12811962b4b71c6793722c4377f141fde
