### ISSUE TITLE
NTR: normal protein localization to iMTOC/eMTOC 	PMID:19001497

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2838]
NTR: normal protein localization to iMTOC
NTR: normal protein localization to eMTOC

Standard defs
	PMID:19001497

(Would it be possible for all of the terms containing eMTOC/iMTOC to have these as primary names instead of synonyms as this is the community usage...they never write it out in full and the abbreviation is easier to read/distinguish quickly)

**Comment by mah11** [comment]
new terms
  normal protein localization to eMOTC FYPO:0005707
  normal protein localization to iMOTC FYPO:0005708

name/synonym swaps done

edit file: b195a9d2b07819052614b9be249a6853a8888f7e
release: 99819ea12811962b4b71c6793722c4377f141fde
