### ISSUE TITLE
NTR: normal protein localization to mitotic spindle pole body 	PMID:19001497

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2839]
NTR: normal protein localization to mitotic spindle pole body
(current term is not mitosis specific?)
	PMID:19001497

**Comment by mah11** [comment]
Do you mean that you need "normal protein localization to mitotic spindle pole body during mitosis"?

**Comment by ValWood** [comment]
yes, I don't say that do I?

**Comment by mah11** [comment]
normal protein localization to mitotic spindle pole body during mitosis FYPO:0005709

edit file: b195a9d2b07819052614b9be249a6853a8888f7e
release: 99819ea12811962b4b71c6793722c4377f141fde
