### ISSUE TITLE
possible term rename (FYPO:0004619

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2840]
FYPO:0004619
cytoplasmic microtubules nucleated from equatorial microtubule organizing center absent from cell

could this be
abolished microtubule nucleation from eMTOC?
PMID:19001497

**Comment by mah11** [comment]
did this for #2833

    id: FYPO:0005698
    name: abolished microtubule nucleation from equatorial microtubule organizing center
    relationship: has_output FYPO:0004619 ! cytoplasmic microtubules nucleated from equatorial microtubule organizing center absent from cell

**Comment by ValWood** [comment]
A consistent request then;)
