### ISSUE TITLE
rename FYPO:0003549	abnormal protein localization during meiosis

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2842]
FYPO:0003549	abnormal protein localization during meiosis

rename 
"during meiotic cell cycle"?

(Should probably disambiguate other meiosis  term names too if there are any more like this)

**Comment by mah11** [comment]
No, in FYPO meiosis means meiosis ;)

Less snarkily, FYPO:0003549 and other meiosis terms all specify by text definition, exact synonym, and (where feasible) logical definition that they do indeed refer to one or both meiotic nuclear division(s).

**Comment by ValWood** [comment]
OK I though I may have used it otherwise, but the list of annotations looks largely OK....
