### ISSUE TITLE
NTR rereplication phenotype

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2843]
NTR: abnormal negative regulation of mitotic DNA replication initiation resulting in complete rereplication and mitotic cell cycle arrest
synonym: abnormal mitotic cell cycle arrest with re-replicated DNA
synonym: abnormal mitotic arrest with 4C DNA content
A regulation phenotype observed in the vegetative growth phase of the life cycle in which negative regulation of the initiation of mitotic DNA replication is abnormal, resulting in one or more rounds of rereplication of the entire genome and mitotic cell cycle arrest  (in G2?/ before mitosis?).

descendant  of
FYPO:0001425
abnormal negative regulation of mitotic DNA replication initiation resulting in complete rereplication 
A regulation phenotype observed in the vegetative growth phase of the life cycle in which negative regulation of the initiation of mitotic DNA replication is abnormal, resulting in one or more rounds of rereplication of the entire genome.

descendant of
FYPO:0000444	abnormal mitotic cell cycle arrest with replicated DNA
A cellular process phenotype in which progression through the mitotic cell cycle is arrested when cells have replicated genomic DNA, under conditions where arrest does not normally occur.

PMID:7774573

**Comment by ValWood** [comment]
@jvhayles

**Comment by mah11** [comment]
abnormal negative regulation of DNA replication initiation resulting in complete rereplication, with mitotic cell cycle arrest FYPO:0005710

edit file: b195a9d2b07819052614b9be249a6853a8888f7e
release: 99819ea12811962b4b71c6793722c4377f141fde

**Comment by ValWood** [comment]
Should I see this as a descendant of FYPO:0000444 placeholder term?

**Comment by mah11** [comment]
oops, forgot the has_part. will add next time I'm editing ...

**Comment by mah11** [comment]
link added

edit file: cbe103231a15beb10dd459ec1fe7cc3be47463b7
release: b00a4204edc68986290523b3a5695954b3d19b46
