### ISSUE TITLE
NTR: decreased cyclin B1-CDK1 complex level PMID:8087848

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2844]
decreased cyclin B1-CDK1 complex level

( can do this with  
decreased protein complex and GO term in an extension if this is preferred (and allowed)

PMID:8087848

**Comment by ValWood** [comment]
One of Jacky's

**Comment by mah11** [comment]
There's precedent, i.e. I've added FYPO:0003684 ! altered level of macromolecular complex and some descendants. If it threatens to get out of hand we can switch to using extensions.

**Comment by mah11** [comment]
decreased cyclin B1-CDK1 complex level FYPO:0005711

edit file: b195a9d2b07819052614b9be249a6853a8888f7e
release: 99819ea12811962b4b71c6793722c4377f141fde
