### ISSUE TITLE
ntr: condition: nitrogen starvation followed by heatshock and recovery at permissive temperature

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2847]
nitrogen starvation followed by heatshock and recovery at permissive temperature

(its the shortest we could make it!)

**Comment by ValWood** [comment]
required to approve curs/86f72e4a0d568a17

**Comment by Antonialock** [comment]
I can't see these conditions in the session? Do you still need it?

**Comment by ValWood** [comment]
yep, I had a long discussion with jacky. This will replace all of the exisiting conditions, which don't work on their own.

**Comment by Antonialock** [comment]
ok so
1. cells were nitrogen starved at what temp? permissive? 
2. cells were heatshocked in what medium? 
3. cells were allowed to recover at "permissive" temp?

**Comment by Antonialock** [comment]
I'm just trying to get at what they did, cells can be "primed" for survival to different stresses (like, growing cells at high temperature make them more likely to survive heat shocks)

so for example,
nitrogen starvation followed by heatshock, then recovery in glucose rich medium
or
nitrogen starvation at high temperature followed by heatshock, then recovery at standard temperature in rich medium

or something, does that make sense? 
How about nitrogen starvation followed by heatshock and recovery in glucose rich medium

**Comment by ValWood** [comment]
Can we say

 Digging through old e-mail Jacky said

nitrogen starvation followed by heatshock and recovery at permissive temperature
If not I’m happy with "nitrogen starvation followed by heatshock and recovery' as you say people can go to the paper for details

going back through the e-mails its
nitrogen starvation followed by heatshock and recovery in glucose MM

If that sounds OK maybe @mah11 you can add this too, to get this session through?

**Comment by mah11** [comment]
note to self PMID:8087848

**Comment by mah11** [comment]
added

[Term]
id: PECO:0000309
name: nitrogen starvation followed by heat shock and recovery at normal temperature
def: "Cells are first grown in minimal medium lacking nitrogen, then subjected to heat shock, and are then allowed to recover in rich medium at standard temperature." []
synonym: "nitrogen starvation followed by heat shock and recovery at permissive temperature" RELATED []
is_a: PECO:0000094 ! grouping sequential growth conditions
