### ISSUE TITLE
query:  metaphase arrest vs abnormal regulation of mitotic metaphase/anaphase transition

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2848]
FYPO_ID(FYPO:0000200 - abnormal regulation of mitotic metaphase/anaphase transition) for All Alleles	 | ☆	26

FYPO_ID(FYPO:0000620 - abnormal cell cycle arrest in mitotic metaphase) for All Alleles	 | ☆	16

I would expect all  FYPO:0000620 to be  FYPO:0000200

but
( FYPO_ID(FYPO:0000200 - abnormal regulation of mitotic metaphase/anaphase transition) for All Alleles ) AND 
( FYPO_ID(FYPO:0000620 - abnormal cell cycle arrest in mitotic metaphase) for All Alleles )	 | ☆	6

(maybe need abolished?)

**Comment by ValWood** [comment]
I tried to look at existing metaphase arrest, this is as far as I got...
https://github.com/pombase/curation/issues/1100

**Comment by mah11** [comment]
I admit I'm not entirely free of confusion here, but would it help to add the link FYPO:0000620 output_of FYPO:0000200 (i.e. abnormal cell cycle arrest in mitotic metaphase output_of abnormal regulation of mitotic metaphase/anaphase transition)?

**Comment by ValWood** [comment]
I don't think that would work.
You could  have  abnormal regulation of mitotic metaphase/anaphase transition
which did not result in 
abnormal cell cycle arrest in mitotic metaphase
(regulating  the timing).

Ah thats why probably....doh

**Comment by mah11** [comment]
That's why it won't be FYPO:0000200 has_output FYPO:0000620. But if metaphase arrest always means that metaphase/anaphase transition went wrong somehow, then 620 output_of 200 works.

**Comment by ValWood** [comment]
I'm not confident that that is correct.

metaphase arrest always causes  abolished metaphase/anaphase transition

that doesn't sound like what you are saying though?

**Comment by ValWood** [comment]
would it make sense for 

FYPO_ID(FYPO:0000620 - abnormal cell cycle arrest in mitotic metaphase
to be
part of
FYPO_ID(FYPO:0000200 - abnormal regulation of mitotic metaphase/anaphase transition)
?

**Comment by mah11** [comment]
It looks as though there are two things getting mixed up here

> metaphase arrest always causes abolished metaphase/anaphase transition
> 
> that doesn't sound like what you are saying though?

That is indeed not what I'm saying.

Your original question wasn't about an "abolished transition" term (except for the brief comment at the end, which I didn't even understand at the time); it was about the metaphase arrest term and abnormal _regulation_ of the metaphase/anaphase transition. We don't have any terms for abolished cell cycle phase transitions in FYPO, and I'm not at all confident that I could define any such terms so as to distinguish them from arrest terms.

It's also trivially true that if you block a step in any pathway or cycle, subsequent steps don't happen. If we were to say "arrest in metaphase causes the metaphase/anaphase transition to be abolished", how could we argue against also saying "arrest in S phase causes the metaphase/anaphase transition to be abolished"?

> would it make sense for FYPO:0000620 to be part of FYPO:0000200?

No, not at all. If the only way to get metaphase arrest is for _regulation of the metaphase/anaphase transition_ to go awry, then the output_of link I asked about would make sense; if there's any other way to get metaphase arrest, then I don't think these two terms can be linked.

**Comment by ValWood** [comment]
ok, got it!
