### ISSUE TITLE
chromosome recapture PMID:17881496

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2859]
abolished GO:1990942
normal GO:1990942
standard defs
PMID:17881496

**Comment by mah11** [comment]
GO:1990942 is 'mitotic metaphase chromosome recapture', and it doesn't say anything about clustering in the def or synonyms. Should I just make the FYPO term names consistent with the GO name?

**Comment by ValWood** [comment]
the title was another phenotype, which I already have...

**Comment by mah11** [comment]
abolished mitotic metaphase chromosome recapture FYPO:0005719
  normal mitotic metaphase chromosome recapture FYPO:0005720

edit file: c1e05ea3b8989eba0ed96dee128c7a554cf6fde9
release: aed22ae32d4bad9af58aadf470a791c96e3db8e5
