### ISSUE TITLE
ntr: curved mitotic spindle during anaphase B PMID:15147872

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2861]
descendent of FYPO:0001574

A spindle phenotype in which the mitotic spindle forms an arched or circular structure during anaphase B.

 PMID:15147872

![curved_spindle](https://cloud.githubusercontent.com/assets/7359272/19305388/89bb4b8e-9068-11e6-8e54-0c169b0a4d4d.jpg)

**Comment by ValWood** [comment]
addition 

Time- lapse photographs of skp1-A7 showed that a live cell under- going mitosis appears to proceed normally until phase 2 (prophase to anaphase A) [19] (from 0 to 600 s in Fig. 2), but during phase 3 (anaphase B equivalent, starting at 690 s)

The anaphase B part is important as this shows it isn't required for the metaphase/anaphase transition. I previously asked UniProt to remove this annotation, for this paper, so this should disappear soon....

**Comment by mah11** [comment]
curved mitotic spindle during anaphase B FYPO:0005721

edit file: c1e05ea3b8989eba0ed96dee128c7a554cf6fde9
release: aed22ae32d4bad9af58aadf470a791c96e3db8e5
