### ISSUE TITLE
ntr: possible revision: mitotic spindle collapse, new term and updates PMID:15147872

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2862]
current term
mitotic spindle collapse
A cell phenotype in which a short mitotic spindle assembles, but does not elongate. The spindle pole bodies fail to separate, and often become spatially closer together, suggesting that the spindle shrinks.

however,
there is a different type of "collapse"
(I wonder if the first type is really called 'collapse" I will double check this)

mitotic spindle collapse in anaphase B
A cell phenotype in which the mitotic spindle elongates during anaphase B, becomes curved
and eventually collapses.
output_of FYPONEW:/issues/2861

**Comment by ValWood** [comment]
after this need to check existing 9 annotations to see if they are "without spindle elongation" 
so assign to me when done and I'll open a ticket on curation tracker. Sooner if I remember...

**Comment by ValWood** [comment]
![spindle collapse](https://cloud.githubusercontent.com/assets/7359272/19306561/2d2005a8-906e-11e6-9ea5-c8b6559f09cc.jpg)

**Comment by ValWood** [comment]
It also looks like this:
![collapse](https://cloud.githubusercontent.com/assets/7359272/19306744/ff25fc74-906e-11e6-8e80-78ebf6e68a9d.jpg)

(this was to show that elongation kinetics were normal)

**Comment by ValWood** [comment]
A clue, I only need to check annotation *after*
As far as we know, this type of spindle breakage has not been reported in any mitotic mutants previously characterized.

This is a Takashi paper,  so it won't be in any earlier papers, I only need to check later dates.

**Comment by mah11** [comment]
> I wonder if the first type is really called 'collapse"

Yes, FYPO:0002688 was added for PMID:23885124, which does call it "SPB convergence or spindle collapse". If necessary I can add "without elongation" to the name.

> after this need to check existing 9 annotations

anything from PMID:23885124 is OK, since that's where the def comes from

**Comment by ValWood** [comment]
I think this phenotype is quite different from the other one, but I'm not quite sure what the differentia should be. They both seem to elongate, but the existing  annotations one less so

These are the difference I see
This (new) one the spindle curves...
I am not quite sure what happens to the SPBs

The existing term is also called  "spindle pole body convergence" (add synonym) as the spindle poles come back together 
When shown, this appears to bend at an angle and break at the midzone

**Comment by mah11** [comment]
> The existing term is also called "spindle pole body convergence" (add synonym) 

synonym has been there all along

**Comment by ValWood** [comment]
This ticket (which I am closing https://github.com/pombase/curation/issues/1133)
shows that it is essentially 2 different phenotypes. All of the others are quite similar, with different degrees of elongation, but the problem is caused by something wrong with the spindle elongation per se., and the SPBs re-converge.

skb1 is a problem with the nuclear membrane, the  expanding spindle is constrained in the nucleus.
Maybe the differetia should be "pronounced curving " and "more  spindle microtubules hanging around afterwards"...the spindle collapses, but it doesn't seem to 'disappear' in the same way?

**Comment by mah11** [comment]
new term
  mitotic spindle collapse during anaphase B FYPO:0005722

renamed FYPO:0002688 to 'mitotic spindle collapse without elongation'

edit file: c1e05ea3b8989eba0ed96dee128c7a554cf6fde9
release: aed22ae32d4bad9af58aadf470a791c96e3db8e5
