### ISSUE TITLE
ntr: abnormally segregating nuclear membrane PMID:15147872

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2863]
child of 
? abnormal mitosis
? abnormal nuclear envelope morphology during mitosis (the morphology is abnormal, but it should probably go under "abnormal organization" which currently doesn't exist?

So
ntr: abnormally segregating nuclear membranes
A cellular process phenotype in which the nuclear membrane segregation is abnormal during mitosis. 

with a child "abnormal nuclear membrane expansion"
(this isn't from this paper, but I know that I need it for others)

**Comment by ValWood** [comment]
This is interesting, because this particular spindle defect is really not a defective spindle elongation process, but a problem with the nuclear membrane.....

The bent spindles of the skp1-A7 mutant cells seem to form a circle around the region of the nucleus. Unlike animal cells, yeast cells exhibit closed mitosis, in which the nuclear envelope never disassembles during mitosis. Given this fact, we asked whether this circular structure was a result of the spindle being con- strained by the nuclear envelope. If abnormality of spindle morphology was the primary defect, the nuclear envelope would display normal separation. 

So it will be useful to check the "spindle collapse phenotypes" to see if they are similar. From a quick scan I think this one is different. I can't remember this "curved" spindle before, and all the other gene products really do appear to be  more related to spindle organization in some way.

**Comment by mah11** [comment]
Are "nuclear membrane segregation" and "nuclear membrane expansion" defined process (a la GO BP)?

**Comment by ValWood** [comment]
ignore the 
ntr: abnormally segregating nuclear membranes
as I don't think that would be a valid GO term....it seems that the nuclear membrane division is just a physical consequence of the SPB separation.

I'm  also 
not sure that membrane synthesis is affected, or membrane "stretchability/composition"

so instead, I'll just go with

abnormal
GO:0071763 nuclear membrane organization
during mitotic nuclear division


I do have a ticket for  the "nuclear membrane expansion" 
the new term is GO:0101026	nuclear membrane biogenesis involved in mitotic nuclear division

but might be renamed to
"membrane addition to the nuclear membrane during division"
https://github.com/geneontology/go-ontology/issues/12751

for the other paper paper which is  deficient in membrane addition.

does that sound OK?

**Comment by mah11** [comment]
note: normally when waiting for GO terms I would go ahead and add the FYPO terms, and add xps later, but for this one I want to see what the GO names and defs will be so I don't have to do too much FYPO readjustment

**Comment by mah11** [comment]
Now that the GO ticket is done, should the FYPO term be "abnormal nuclear membrane biogenesis involved in mitotic nuclear division"?

**Comment by ValWood** [comment]
That will do!

**Comment by mah11** [comment]
went with
abnormal nuclear membrane biogenesis involved in mitosis FYPO:0005811

and 'mitotic nuclear division' in an exact synonym

edit file: fc60533faa64bd70bc9bd1026fa733cc05bd9520
release: e8f4e8ce0fdcdc88d2ceb9b94d8fa3ea986a384e
