### ISSUE TITLE
increased protein localization term PMID:21664573

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2867]
increased protein localization to kinetochore during M-phase

PMID:21664573

**Comment by mah11** [comment]
increased protein localization to kinetochore during mitosis FYPO:0005735

(M phase in synonym)

edit file: c1e05ea3b8989eba0ed96dee128c7a554cf6fde9
release: aed22ae32d4bad9af58aadf470a791c96e3db8e5
