### ISSUE TITLE
normal SPB localization check

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2869]
FYPO:0002967    normal protein localization to mitotic spindle pole body

does not appear to be a direct descendant of
FYPO:0001836    normal protein localization to spindle pole body

(at least this is my placeholder term, and as a decendent I see ONLY
normal protein localization to NEW mitotic spindle pole body  
?

**Comment by mah11** [comment]
I hope the corrections for https://github.com/geneontology/go-ontology/issues/12761 will make the reasoner infer sensible links for these terms.

**Comment by ValWood** [comment]
Oh yeah! saw that last night.

**Comment by mah11** [comment]
Oddly, GO is still missing some links that I would've expected to be inferred, but sod it, that's GO's problem. For now, I've asserted a more specific link in FYPO.

(On the plus side, GO has fixed the problem that was preventing me adding an xp to FYPO:0005709.)

edit file: 1cc4517275a85cb76e688bac2fdabc63214bd35f
release: c767aa1813b3acaada1519ad929404897c4caf41
