### ISSUE TITLE
ntr: abolished histone H3 S10 phosphorylation PMID:11792803

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2870]
standard def
descendant of 
FYPO:0002592    abolished histone phosphorylation

**Comment by mah11** [comment]
abolished histone H3-S10 phosphorylation FYPO:0005738

edit file: c1e05ea3b8989eba0ed96dee128c7a554cf6fde9
release: aed22ae32d4bad9af58aadf470a791c96e3db8e5
