### ISSUE TITLE
NTR: complete but unequal mitotic sister chromatid segregation with unseparated chromosomes PMID:11792803

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2871]
I'd like to be specific about this:

complete but unequal mitotic sister chromatid segregation with unseparated chromosomes

child of
complete but unequal mitotic sister chromatid segregation

Here is an example:
![unseparated](https://cloud.githubusercontent.com/assets/7359272/19685528/0a0671f0-9ab5-11e6-8cbc-0929e9c0670b.jpg)
![not split](https://cloud.githubusercontent.com/assets/7359272/19685537/146199a4-9ab5-11e6-9aa1-1bf25ede2625.jpg)

**Comment by ValWood** [comment]
I'm trying to find/link to the ticket where I go on about unequal segregation when the sister chromatids are separated or not, but I can't find it. Hopefully this makes sense without?

**Comment by mah11** [comment]
#2845

**Comment by mah11** [comment]
complete but unequal mitotic sister chromatid segregation with unseparated chromosomes FYPO:0005739

edit file: c1e05ea3b8989eba0ed96dee128c7a554cf6fde9
release: aed22ae32d4bad9af58aadf470a791c96e3db8e5
