### ISSUE TITLE
obsolete terms that require multiple evidence types to annotate

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2872]
based on:
Jacky:
For the  term FYPO:0004922 you need to have two different lines of evidence - microscopy and flow cytometry.  However you can only select one of them. Would it be best to use two different FYPO terms and give the evidence  microscopy  for one and  flow cytometry for other

I suspect we should not therefore have the compound term, if it can only be 2 separate
observations? i think this is my fault, by trying to classify the different
'types of elongated' but we will need to do this by analysing concurrent
annotations for the same alleles to
inviable elongated mononucleate aseptate vegetative
and
cell cycle arrest in mitotic G2 phase

**Comment by mah11** [comment]
There are a bunch of other terms (list below) where the same concern applies. We really should handle them all consistently, whether we keep them or make them obsolete.

I suspect I haven't used these terms as much as you & Jacky, but when I have I've just swept the evidence question under the rug and used microscopy - technically, it loses part of the evidence information, but I've chosen other battles ;)

these are definitely affected:
FYPO:0003128 inviable elongated mononucleate aseptate vegetative cell with cell cycle arrest in mitotic M phase
FYPO:0003825 inviable binucleate aseptate cell with mitotic cell cycle arrest in G2 before cell separation
FYPO:0003826 inviable elongated binucleate aseptate cell with mitotic cell cycle arrest in G2 before cell separation
FYPO:0003875 inviable elongated cell with mitotic G2/M transition delay and cell cycle arrest in M phase
FYPO:0003979 abnormal mitotic cell cycle arrest with condensed chromosomes, septated cell with 1C DNA
FYPO:0004197 inviable elongated vegetative cell with fragmented nucleus and mitotic cell cycle arrest in interphase
FYPO:0005321 inviable elongated mononucleate aseptate vegetative cell with cell cycle arrest in mitotic metaphase
FYPO:0005367 inviable mononucleate aseptate vegetative cell with cell cycle arrest in mitotic G2 phase
FYPO:0005422 inviable elongated vegetative cell with fragmented nucleus and mitotic cell cycle arrest in interphase during cellular response to UV


and maybe also these:
FYPO:0001385 inviable after spore germination, without cell division, cell cycle arrest with replicated DNA
FYPO:0001497 inviable elongated vegetative cell with mitotic cell cycle arrest in interphase
FYPO:0003171 binucleate monoseptate cell with mitotic cell cycle arrest before cell separation
FYPO:0004473 inviable after spore germination, without cell division, cell cycle arrest with unreplicated DNA
FYPO:0004719 abnormal mitotic cell cycle arrest with condensed chromosomes, septated cell
FYPO:0005421 inviable elongated vegetative cell with mitotic cell cycle arrest in interphase during cellular response to UV
FYPO:0005689 inviable binucleate aseptate cell with mitotic cell cycle arrest before cell separation

**Comment by ValWood** [comment]
Yeah this is my fault....

I think the compound terms are really useful when they are observed simultaneously, but in retrospect I think we should  limit this to things which are observed during the same experiment.

Once we have cleverer searching, users will still be able to get these lists if they can use conditions and allele-types in searches/filters etc

**Comment by mah11** [comment]
So the actual problem seems to be that it takes more than one type of evidence to show that a cell has one of these complex phenotypes.
 
Should we investigate supporting more than one evidence entry per annotation? It mightbe a pain technically or to make it user-friendly, but if we could do it, we could keep these terms, flag them in the soft-check file for now, and restore them to use later.

What I Do.Not.Want. to do is make them obsolete now, and then have them requested again later if we end up solving the evidence problem anyway.

**Comment by JackyVH** [comment]
In my limited experience I think it would be useful to be able to have more than one type of evidence per annotation.
Jacky

**Comment by Antonialock** [comment]
Would you use two evidence codes 
A. when you do 2 completely different experiments showing the same thing in one paper (for example by showing that a protein is in the mitochondria i. by microscopy and ii. by fractionation and western blotting
B. When information from two different experiments are needed to arrive at one annotation (I can't think of a neat example but this definitely happens)

**Comment by mah11** [comment]
I think you could use two evidence codes in either case, but for A making two separate annotations, one with each code, would say the same thing. It's case B that we can't cope with effectively at present.

For things like FYPO:0004922 "inviable elongated mononucleate aseptate vegetative cell with cell cycle arrest in mitotic G2 phase", you need microscopy to see the elongated, mononucleate and aseptate parts, and something else, usually FACS, to see the G2 arrest part.

**Comment by Antonialock** [comment]
and cell growth experiment to see that there really aren't any divisions? - so we'd need 3 codes ;)

**Comment by ValWood** [comment]
Let's think about this in the New Year, at a curator meeting when we are all there...

**Comment by ValWood** [comment]
Summary, we want to split.

1. Get the numbers single and multi
2. Decide how to migrate...(some will need evidence changing)
3. Implement

**Comment by mah11** [comment]
assignees: me to do ontology work; all to review annotations

**Comment by mah11** [comment]
Outcome of #2544 implies that we do _not_ want to try to eliminate this kind of precomposed term globally. Open new ticket(s) for any specific individual terms that we now think went a bit too far.

**Comment by ValWood** [comment]
Yep, we need the ability to use terms that should require combinatorial evidence codes in some circumstances... so I guess we might want to include a couple of combinatorial evidence codes...
