### ISSUE TITLE
NTR	normal global transcription during vegetative growth in response to heat stress

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2873]
Figure 8A and B  PMID:20547592

**Comment by mah11** [comment]
Given that in GO, ( a) there are no separate terms for "global" transcription and ( b) "cellular response to heat stress" is an exact synonym of "cellular response to heat", the requested term boils down to

normal transcription during cellular response to heat during vegetative growth

**Comment by mah11** [comment]
normal transcription during cellular response to heat FYPO:0005740

edit file: c1e05ea3b8989eba0ed96dee128c7a554cf6fde9
release: aed22ae32d4bad9af58aadf470a791c96e3db8e5
