### ISSUE TITLE
abolished & reduced 	homocitrate synthase activity

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2881]
GO:0004410	homocitrate synthase activity
PMID:19776021

**Comment by mah11** [comment]
abolished homocitrate synthase activity FYPO:0005762

decreased homocitrate synthase activity (synonym reduced) is FYPO:0001752

edit file: 32dd62a4340678dc2e49e0c627ef74ba9de15c63
release: a727b801a9b9948ea3f62222bfe79da8c443c0d8
