### ISSUE TITLE
order of extensions in Canto

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2888]
This is very minor, but it would be good if these could be ordered

phosphorylates,
involved in biological process
has function during,

In fact I think we have a file somewhere documenting the order in which the extensions should appear on the gene pages....this will be the same order...

@mah11  do you know where we documented this?

![order](https://cloud.githubusercontent.com/assets/7359272/20233745/cf13ff04-a86a-11e6-8f3b-a40e26254be6.jpg)

**Comment by mah11** [comment]
wrong tracker
