### ISSUE TITLE
condition request, glucose starvation and recovery

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2890]
I'm using
"glucose starvation and timing" which exists. No def. Is this a typo?

v

**Comment by mah11** [comment]
I don't see "glucose starvation" in PECO at all, with or without "and timing". There's "grouping starvation and timing" (PECO:0000239), which looks like it ought to be flagged as a grouping term not for direct use (I can fix that in a minute).

(holler if you need the new condition before Antonia is back up to scratch, and I'll add it)

**Comment by ValWood** [comment]
may as well add it (glucose starvation and recovery) or this session will hang around

**Comment by mah11** [comment]
OK, I'm going to do some FYPO tomorrow, so I'll do this then too.

**Comment by mah11** [comment]
added

[Term]
id: PECO:0000310
name: glucose starvation and recovery
def: "Cells are first grown in minimal medium lacking glucose and are then allowed to recover in rich medium." [PomBase:mah]
is_a: PECO:0000094 ! grouping sequential growth conditions
