### ISSUE TITLE
rejig cytoplasmic MT terms to MT bundle

### ISSUE THREAD

**Issue by mah11** [pombase/fypo#2893]
hived off from #2891 

Change all terms that refer to cytoplasmic microtubules to use microtubule bundle in names, defs, xps, etc.

Val: 
name: short disorganised cytoplasmic microtubules
def: Interphase microtubule bundles do not reach the cell tips ...

mah: MTs or bundles? and 
Should I change existing FYPO cytoplasmic microtubule terms to refer to bundles?

Jacky: Yes they are bundles and yes I think that the term microtubule is nearly always referring to microtubule bundles. 
[mah note: except spindle MTs]

**Comment by mah11** [comment]
note to self: TG cytoplasmic MT bundle (MT bundle part_of cytoplasm)

**Comment by mah11** [comment]
I've started taking a closer look at this, and there are a few snags, hopefully minor. It'll help a lot if you can look at the terms I'm asking about in point 2 before I muck in with the work (it also won't hurt to check the list in point 3, but the questions are the most important bit).

1. Some terms, including almost all of the process phenotype terms, look like they should remain 'microtubule', not 'microtubule bundle'. In some cases that's because they're not specific for cytoplasmic MTs, or are specific for spindle MTs. That includes:

- anything referring to microtubule nucleation
- anything referring to microtubule polymerization, depolymerization or either/both
- terms for protein localization to microtubule plus end (or minus end, but there aren't any that are cytoplasm-specific now anyway)
- These structure phenotype terms:
-- FYPO:0004088	abnormal cytoplasmic microtubules
-- FYPO:0004618	astral microtubules absent from cell
-- FYPO:0004612	long astral microtubules
-- FYPO:0004865	long astral microtubules during mitotic anaphase A
-- FYPO:0000233	long cytoplasmic microtubules
-- FYPO:0005688 normal astral microtubules
-- FYPO:0001976	normal cytoplasmic microtubules
-- FYPO:0005809	short astral microtubules

Some of the generic terms - FYPO:0004088, FYPO:0000223, FYPO:0001976 - have to stay as 'microtubule(s)' because they have 'astral microtubule' descendants. For those I'll make sure there are suitable 'microtubule bundle' terms, with '[x] microtubule bundle has_part [x] microtubule' links.



2. Queries - should these change to 'microtubule bundle'?

- process phenotypes
-- FYPO:0003191	abolished protein localization to microtubule during mitotic interphase, with protein mislocalized to cytoplasmic foci
-- FYPO:0004727	cytoplasmic microtubule formation from nuclear microtubules
-- FYPO:0004728	cytoplasmic microtubule formation from nuclear microtubules following nuclear envelope breakthrough
-- FYPO:0004729	cytoplasmic microtubule formation from nuclear microtubules following spindle microtubule fragmentation

- structure phenotype
-- FYPO:0004613	spindle pole body detached from cytoplasmic microtubules


3. I gather these should all change to 'microtubule bundle':
FYPO:0003327	curved cytoplasmic microtubules
FYPO:0005425	curved elongated vegetative cell with long curved cytoplasmic microtubules
FYPO:0004702	cytoplasmic microtubules absent from cell
FYPO:0004619	cytoplasmic microtubules nucleated from eMTOC absent from cell
FYPO:0004733	cytoplasmic microtubules nucleated from eMTOC present in decreased numbers
FYPO:0003227	cytoplasmic microtubules present during mitosis
FYPO:0004704	cytoplasmic microtubules present in increased numbers
FYPO:0005426	elongated C-shaped vegetative cell with long curved cytoplasmic microtubules
FYPO:0005427	elongated J-shaped vegetative cell with curved cytoplasmic microtubules
FYPO:0004511	long curved cytoplasmic microtubules
FYPO:0004611	long cytoplasmic microtubules during mitotic interphase
FYPO:0003328	misoriented cytoplasmic microtubules
FYPO:0001400	normal interphase cytoplasmic microtubules
FYPO:0002760	short cytoplasmic microtubules
FYPO:0003429	short cytoplasmic microtubules present in decreased numbers
FYPO:0004539	short cytoplasmic microtubules present in increased numbers
FYPO:0004613	spindle pole body detached from cytoplasmic microtubules
FYPO:0004864	viable curved vegetative cell with long curved cytoplasmic microtubules

**Comment by mah11** [comment]
also see comment about short cytoplasmic MTs in #2899

**Comment by ValWood** [comment]
> 2. Queries - should these change to 'microtubule bundle'?

I would keep these as "microtubule " for now. They might end up as bundles but they begin as microtunules

**Comment by ValWood** [comment]
> 3. I gather these should all change to 'microtubule bundle':

I'm guessing that most of these refer to interphase bundles. Jacky @jvhayles , do you think these terms would  all be correct if they were switched from "microtubule" to "bundle"

probably but not this one?
FYPO:0004613	spindle pole body detached from cytoplasmic microtubules
which might be  just microtubules? not sure?

**Comment by JackyVH** [comment]
I'm beginning to think that in most cases the term microtubules is OK whether it is an individual MT or an MT in a microtubule bundle. Even at the end of a microtubule bundle it is still at the end of a microtubule.  For example Tea2 travels along individual microtubules within a bundle to its plus end.  Tea2  can therefore be at the end of a microtubule and also also be at the end of microtubule  bundle.  I think there could be situations where a you might need to use the term microtubule bundle (child term?) but it most cases I think microtubule is enough and less confusing.

Does this make sense

Jacky

**Comment by mah11** [comment]
> in most cases I think microtubule is enough and less confusing. Does this make sense

Well, I like it ... but I'm very biased because it would mean less work for me if terms don't have to change ;)

**Comment by ValWood** [comment]
OK!

**Comment by mah11** [comment]
If you're both happy to leave things as they are, that's fine with me. Closing, so if you spot any individual terms that want editing, open a new ticket.
