### ISSUE TITLE
short astral microtubules PMID:11018050

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2894]
PMID:11018050
Jackys last request from 
Term request: short astral microtubules
Comment: During M phase spindle astral microtubules are shorter than norma

final request from
curs/b19dfb2b27f82b53#

**Comment by mah11** [comment]
short astral microtubules FYPO:0005809

edit file: fc60533faa64bd70bc9bd1026fa733cc05bd9520
release: e8f4e8ce0fdcdc88d2ceb9b94d8fa3ea986a384e
