### ISSUE TITLE
possible rejig of curved microtubule terms

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2898]
Jacky @jvhayles said:
I think there is also a situation where interphase microtubules( bundles) are long and curved but look like a bow because they stop at the cell tips This is different to the hook like phenotype where they are not so curved except they continue round the cell end. I think it happens when a single microtubule bundle is formed on one side of the cell. You can see this in Verde Mata and Nurse JCB vol131 1995 pp1529-1538 Fig 9 Fulvia says in this paper that tea1 Mts are normal but Juan showed that sometimes they curved around the end. . I feel that there is a difference between the two descriptions, for the long curved microtubules I think the cell is curved because the microtubule bundle is curved and the cell tip is organised where the MT stops i.e. at the cell end whereas in tea1 some of the microtubule bundles go pass the cell tip .

So it seems we need 2 terms for curved cytoplasmic/interphase microtubules

The, we might need to reassess annotations:
FYPO_ID(FYPO:0000055 - long microtubules) for All Alleles    32
FYPO_ID(FYPO:0004862 - curved microtubules) for All Alleles 13
FYPO_ID(FYPO:0004511 - long curved cytoplasmic microtubules) for All Alleles 6

Some of these are probably long spindle microtubules
( FYPO_ID(FYPO:0000055 - long microtubules) for All Alleles ) NOT ( FYPO_ID(FYPO:0003787 - long mitotic spindle microtubules protruding beyond spindle pole body) for All Alleles )  26

Will wait until we know what terms we have, then open curation tracker ticket for this:

First @jvhayles
- [ ] Q Are all curved microtubules long? or not necessarily?

**Comment by mah11** [comment]
We should be able to do the "C-shaped" vs. "J-shaped" distinction, as we've done for cell shapes.

(note to self: assert is_a curved for cell and MT terms)

**Comment by ValWood** [comment]
also need the curved around end of cell type for PMID:14663827

no  worries if you don't get to this one as I  have a few queries outstanding on this session, it may not make it through. If everything else gets sorted I can push this through and temporarily put this new term in comment field

**Comment by mah11** [comment]
I can add 'C-shaped microtubules' and 'J-shaped microtubules' (both is_a curved microtubules) next time I'm editing.

I think we're still waiting for you and Jacky to figure out whether all curved microtubules are always longer than normal, or if only C-shaped or only J-shaped, or if any curved MTs could be normal length or longer, so there could be some moving, new terms, and/or merging later on.

**Comment by mah11** [comment]
So far, I've added these, both under 'curved cytoplasmic microtubules':

  C-shaped cytoplasmic microtubules FYPO:0005879
  long cytoplasmic microtubules curved around cell end during mitotic interphase FYPO:0005880

I'll leave the ticket open for the question of whether all curved MTs are also long.

**Comment by mah11** [comment]
closing because it's been so long since last activity, and we can open a new ticket if you want any further changes
