### ISSUE TITLE
query term decreased spatial extent of cytoplasmic microtubule polymerization

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2899]
tea2 has:
decreased spatial extent of cytoplasmic microtubule polymerization
(only 1 annotation)

I'm wondering why I requested this one....(but from the same phenotype , did not annotate short cytoplasmic microtubules???

I guess this is really the same phenotype as "short cytoplasmic microtubules"

or
decrease cytoplasmic microtubule polymerization
?

**Comment by ValWood** [comment]
this might end up as a curation ticket, it changes as I was typing so I'll take it for now

**Comment by mah11** [comment]
OK. In the wider world, I think short microtubules could result either from polymerization not going on as long as normal, or from increased severing. I don't know whether severing is ever an issue in pombe.

I think decreased polymerization could cover polymerizing fewer microtubules or polymerizing one/-some microtubules for a shorter time/distance. Again, I don't know whether both are things that actually arise in pombe. If the distinction isn't important, I can merge the spatial extent term with 'decreased microtubule polymerization'.

**Comment by JackyVH** [comment]
Midori

For tea2/tip1 deltas the microtubules undergo catastrophe when they reach the cell cortex in any part of the cell instead of only when they reach the cell tip. So microtubules are shorter because they polymerise for a shorter distance. This could also be seen as undergoing catastrophe more frequently. Im not sure what you mean by severing and whether this is an issue in pombe.

Jacky

**Comment by mah11** [comment]
> So microtubules are shorter because they polymerise for a shorter distance.

This does sound like it fits "decreased spatial extent of cytoplasmic microtubule polymerization" .. maybe we should keep using it?

> This could also be seen as undergoing catastrophe more frequently.

Hmm. That doesn't fit the "spatial extent" term quite as nicely. But can we tell which causes which, catastrophe or shorter polymerization distance?

> I'm not sure what you mean by severing and whether this is an issue in pombe.

Multicellular organisms have enzymes that cut existing microtubules into short fragments (katanin appears to be the best studies; one review I found is http://jcs.biologists.org/content/joces/125/11/2561.full.pdf). I have no idea whether pombe has these enzymes!

Anyway, no rush to get it sorted out; I can adjust FYPO sooner or later, whenever you and Val hve a better idea what's going on.

**Comment by ValWood** [comment]
> This does sound like it fits "decreased spatial extent of cytoplasmic microtubule polymerization" .. maybe we should keep using it?

I'm happy to keep using this term. I wasn't sure how it differed  from "short cytoplasmic microtubules"
but I can see now it is more specific, the microtubules are short *because* they reach the cortex before the tip.

**Comment by mah11** [comment]
I can also add a has_output link to connect the spatial extent term to a short cytoplasmic MT term (but not the existing general one, because it also covers astral MTs).

**Comment by ValWood** [comment]
> I don't know whether severing is ever an issue in pombe.

We have the gene knk1 annotated to microtubule severing activity and process via ISS to human. I am not sure if we should?

**Comment by mah11** [comment]
The annotations look correct for the human proteins, and I trust your orthology calls ;)

There's only one paper on knk1 (PMID:25422470; Antonia has it "in progress" in Canto), which doesn't show severing activity - but at a quick glance it wasn't clear whether they'd assayed for severing. So I don't know whether we should keep the ISS annotations.

**Comment by ValWood** [comment]
Yep thats what I thought from a quick glance yesterday.

I thought I sent knk1 to Phong Tran.... @Antonialock  did you start it yet?

v

**Comment by Antonialock** [comment]
I may have taken it as part of the curation workshop..

**Comment by ValWood** [comment]
Yes I think it might have been that. 
We can assign back to Phong Tran (unless you did it?)

**Comment by Antonialock** [comment]
I did start it
https://curation.pombase.org/pombe/curs/30447cf8a308c262

**Comment by ValWood** [comment]
Okay keep it ;)

**Comment by mah11** [comment]
added short interphase microtubules FYPO:0006103 for #3045 
added link FYPO:0005463 has_output FYPO:0006103

I think that's the only ontology thing that was outstanding here, and annotations will get reviewed for the newer ticket.

edit file: ffdd83fa748d74175fd9956e24f3c5d7fca0df50
release: 76e6d3958f70dff85f97ae7f370dbb0c1f63d300
