### ISSUE TITLE
nt missing microtubule terms

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2902]
PMID:15177031
	
abolished protein localisation the microtubule plus end during mitotic interphase

probably could do this arrangement for the other microtubule transport:
normal protein movement by microtubule-dependent transport to cell tip
- normal protein movement along microtubule to cell tip
- normal prtein movement on microtubule tip  to cell tip (probably)

**Comment by mah11** [comment]
I've added this:
abolished protein localization to microtubule plus-end during mitotic interphase FYPO:0005817

The other two terms look like they overlap with the outstanding part of #2896. I'll move that stuff over there, so we have that discussion all in one ticket, and only have one ticket open for the topic.

edit file: 36f1473d65b88ad80d84642b224c9e25ec1a766e
release: 54c4efe0d431224752d8d09a11bff7486526b729
