### ISSUE TITLE
protein neddylation  PMID:23496905 

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2903]
normal protein neddylation standard def
 PMID:23496905

**Comment by ValWood** [comment]
increased protein neddylation
 standard def

**Comment by ValWood** [comment]
decreased NEDD8-specific protease activity
sibling of
FYPO:0005112	decreased ubiquitin-specific protease activity

**Comment by mah11** [comment]
normal protein neddylation FYPO:0005818
  abnormal protein neddylation FYPO:0005819
  decreased protein neddylation FYPO:0005820
  abnormal NEDD8-specific protease activity FYPO:0005821
  decreased NEDD8-specific protease activity FYPO:0005822

edit file: 36f1473d65b88ad80d84642b224c9e25ec1a766e
release: 54c4efe0d431224752d8d09a11bff7486526b729
