### ISSUE TITLE
ntr: increased phosphatidylserine externalization

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2905]
increased transfer of phosphatidylserine (PS) to the outer leaflet of the plasma membrane
(comment apoptotic marker)
PMID:27886462

**Comment by ValWood** [comment]
note to self, these 4
Strong FITC fluorescence was observed at the periphery of all Δppr3, Δppr4, Δppr6 and Δppr10 cells examined while no FITC fluorescence could be observed for wild type cells, suggesting that PS is indeed exposed to the outer membrane of the mutant cells (Figure 2B)

**Comment by mah11** [comment]
Is there supposed to be a qualifier (abnormal, decreased, etc.)? Or was this meant for the GO tracker? (or both?)

If it's a GO request, it looks like is_a GO:0045332 phospholipid translocation.

**Comment by ValWood** [comment]
corrected

**Comment by mah11** [comment]
I modeled the PS term as a "level of stuff" phenotype, with exact synonyms including "increased phosphatidylserine level in external side of plasma membrane":

  increased phosphatidylserine externalization FYPO:0005823
  increased plasma membrane permeability FYPO:0005824


edit file: b360b83b3f72fd8768b325716e4470ad2b1d99be
release: c32a451b2bda3a433bcb28614fb9f262a7d24a42
