### ISSUE TITLE
Term or condition?

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2907]
Thus, we first tested whether addition of the selective iron chelator BPS could restore the viabilities of Δppr3, Δppr4, Δppr6 and Δppr10 mutants. We found that addition of BPS resulted in restoration of viabilities of these mutants to near wild-type (Figure 6A).

**Comment by Antonialock** [comment]
I'd do this as sensitive to iron

**Comment by ValWood** [comment]
OK, that then

**Comment by ValWood** [comment]
ntr: sensitive to iron
(I couldn't find anything)

**Comment by mah11** [comment]
see #2906
