### ISSUE TITLE
vegetative vs non-vegetative (protein modification)

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2908]
Users might find this odd:

![drill down1](https://cloud.githubusercontent.com/assets/7359272/20814657/8dbf573a-b812-11e6-8992-13d6d3a38044.jpg)

![drill down2](https://cloud.githubusercontent.com/assets/7359272/20814659/901bf34e-b812-11e6-858e-75799a133d6b.jpg)

**Comment by ValWood** [comment]
so, when you drill down there are non vegetative modification terms, but for some you need to look under the vegetative term.  Then when you go to the vegetative term, the modifications are 
not named vegetatively.

I don't think it usually matters, but it seems strange here   when we will clearly need to change to "vegetative" eventually. Might be worth calling these vegetative now, and adding a non-vegetative parent for clarity.

**Comment by mah11** [comment]
I can edit term names; I won't bother adding generic parents until we need them to group any siblings that are actually not vegetative (as opposed to unspecified).

**Comment by ValWood** [comment]
Yeah that makes sense...

**Comment by mah11** [comment]
have started this slog; it's going to take several goes 'cos it's too tedious to do all at once

**Comment by ValWood** [comment]
oh I thought you were only doing it for these terms....

I think it makes sense where the terms are split like this....
we can say when it looks a bit odd when we "drill down"

**Comment by mah11** [comment]
yeah, I'm mainly just doing the protein modification branch for now, but there are tons because of all the histone this-or-that-modification on this-or-that residue terms ...

**Comment by mah11** [comment]
I've got as much of this done as I wanted to for this ticket, namely the protein modification branch. Open a new ticket for the next area that should get the refit (preferably not too soon ;) ).

**Comment by ValWood** [comment]
yep will avoid that for a while...
