### ISSUE TITLE
increased level of cleavage product

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2910]
A cell phenotype in which the amount of a protein cleavage product measured in a cell is higher than normal when the cell is in the vegetative growth phase of the life cycle. 

descendent of
FYPO:0001327

(this is distinct from increased processing because it is due to decreased degradation rather than increased processing)

PMID:27655872

**Comment by mah11** [comment]
we discussed this in #2677

**Comment by ValWood** [comment]
yep, I'll do it this way... if I can figure out the cleavage products
