### ISSUE TITLE
NTR: decreased level of generation of precursor metabolites and energy gene mRNA during vegetative growth

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2911]
decreased level of generation of precursor metabolites and energy gene mRNA during vegetative growth
(increased yada yada exists)

PMID:27886462

**Comment by mah11** [comment]
decreased level of generation of precursor metabolites and energy gene mRNA during vegetative growth FYPO:0005826

(it's such a horrible GO term ...)

edit file: b360b83b3f72fd8768b325716e4470ad2b1d99be
release: c32a451b2bda3a433bcb28614fb9f262a7d24a42

**Comment by ValWood** [comment]
yep I know.
Its a useful grouping term though...its even in the slim...
http://www.pombase.org/spombe/related/GO:0006091

I wonder why it isn't just called "energy generation". I don't really know what the precursor metabolites part means.....
