### ISSUE TITLE
ntr: normal microtubule based movement of protein

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2912]
child of
normal intracellular protein transport
normal microtubule-based movement

**Comment by mah11** [comment]
How do these relate to the terms in the outstanding part of #2896?

**Comment by ValWood** [comment]
It would be a parent,  of

normal  movement of protein along microtubule
normal microtubule movement on microtubule tip

also should have the same  terms and arrangement for 
 decreased and abolished.

This will allow me to finalise the sessions and if anything is uncertain I can use this term  instead of  the along/on tip term

I hope to go through the 3 outstanding papers again today....

**Comment by mah11** [comment]
OK, if it's all part & parcel of the same batch of edits, I'll move it to that ticket.
