### ISSUE TITLE
rejig Mmi1 focus terms

### ISSUE THREAD

**Issue by mah11** [pombase/fypo#2913]
In https://github.com/geneontology/go-ontology/issues/12850 Val requested that the GO terms referring to "mmi1 nuclear focus" go obsolete. Three FYPO terms point to GO:1902666 'protein localization to Mmi1 nuclear focus complex' and will have to be amended to keep consistent.

@valwood, @antonialock: Should we keep the FYPO terms? If so, which GO term should I use to update names, defs, and especially logical defs (xps)?

**Comment by ValWood** [comment]
We could ask GO to keep the term, but make it not a complex (revert to nuclear body).....

**Comment by mah11** [comment]
If you change your mind about making the GO terms obsolete, explain why on the GO ticket.

If your reasons for wanting them obsolete still hold, that's fine but I'll need to know how to revise FYPO. The GO ticket says "now we have much more precise/correct complex terms to use", but what are they? Will one or more of them do to define phenotypes?

**Comment by mah11** [comment]
Further comments on the GO ticket suggest that the Mmi1 focus terms may lose links to protein complex terms, but won't go obsolete, so no FYPO change is required.
