### ISSUE TITLE
ER-plasma membrane tethering phenotypes PMID:26877082

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2914]
increased rate of 
GO:0032130 medial membrane band assembly

PMID:26877082
also 
PMID: 23041194

**Comment by ValWood** [comment]
incomplete asymmetric septum formation
A phenotype where an incomplete septum forms on one side of the cell 

Descendent of
FYPO:0002023	abnormal septum morphology during vegetative growth

=====

**Comment by mah11** [comment]
added yesterday; remembered to do the release today (this and several other tickets)

  increased rate of medial membrane band assembly FYPO:0005839
  incomplete, asymmetric septum FYPO:0005840

edit file: 0b30150db46ca4fa9ec69fa8fc23d6647733f798
release: d7531c90d1f9889de8e57e611de9c402f4687db4
