### ISSUE TITLE
add synonym  "abnormal medial cortical node  condensation"

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2915]
FYPO:0003444	abnormal medial cortical node migration

at least I think these are the same phenotype.....

**Comment by ValWood** [comment]
The one I am annotating is much more severe, the  instead of forming a band it seems to coalesce into a single node... I can use this term though because I don't know how to describe it. Will just use "high expressivity"

**Comment by mah11** [comment]
added

edit file: 0b30150db46ca4fa9ec69fa8fc23d6647733f798
release: d7531c90d1f9889de8e57e611de9c402f4687db4

**Comment by ValWood** [comment]
PMID:26877082

**Comment by ValWood** [comment]
Actually here, I think  the condensation is a better primary term name. Migration implies it moves a distance but it doesn't really....

**Comment by mah11** [comment]
OK, condensation it will be with the next release.

Is there a normal process here that could have a GO BP term?

**Comment by mah11** [comment]
latest changes in
edit file: 39b7f12b4b763a4f85451bfff712d553ce002b33
release: 283902eb88adde96079e85c474853903133bd800
