### ISSUE TITLE
transient arrest phenotypes PMID:26730850

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2917]
I'm approving a paper where the author has suggested  descendant terms to represent transient arrest

NEW abnormal cell cycle arrest in mitotic G1 phase
descendant of FYPO:0005097	abnormal cell cycle arrest in mitotic G1 phase

NEW cell cycle arrest at mitotic G2/M phase transition
FYPO:0000400	cell cycle arrest at mitotic G2/M phase transition

would also be a child of viable  vegetative cell

I think this has cropped up before. Is there any reason why we didn't do it.

"This growth arrest was transient, and cells resumed growing after approximately 180 min, as indicated by the disappearance of the 1C peak and the reappearance of septated cells after 240 min (Fig 1)"

**Comment by mah11** [comment]
> NEW abnormal cell cycle arrest in mitotic G1 phase
> descendant of FYPO:0005097 abnormal cell cycle arrest in mitotic G1 phase

> NEW cell cycle arrest at mitotic G2/M phase transition
> FYPO:0000400 cell cycle arrest at mitotic G2/M phase transition

For both pairs, the existing term and the suggested new term are identical. What terms do you actually want?

> would also be a child of viable vegetative cell

We have not connected cell cycle arrest terms to viable/inviable terms to date, and I'm not sure how it would work. I am sure the link can't be is_a.

> I think this has cropped up before. Is there any reason why we didn't do it.

In #2586 we decided that transient arrest was similar enough to a transition delay that a new term wasn't needed. I added some synonyms, but at the moment they're 'related' scope so maybe they're hard to spot in Canto. Should they be exact? Also let me know if you spot any I missed.

**Comment by ValWood** [comment]
I meant to request
transient arrest  cell cycle arrest in mitotic G1 phase

So  I should be using  transition delay (that would work)
I think the synonyms would help.
Maybe a comment too,  on arrest terms that they  should be terminal  and if not use transition delay?

**Comment by mah11** [comment]
added comments to some of the arrest terms;  holler if you want any added to any more terms

edit file: 0b30150db46ca4fa9ec69fa8fc23d6647733f798
release: d7531c90d1f9889de8e57e611de9c402f4687db4

**Comment by ValWood** [comment]
this would work, except 
	FYPO:0000012	mitotic G2/M transition delay
has this as a suggestion?
inviable elongated cell with mitotic G2/M transition delay and cell cycle arrest in M phase

**Comment by mah11** [comment]
> this would work, except
> FYPO:0000012 mitotic G2/M transition delay
> has this as a suggestion?
> inviable elongated cell with mitotic G2/M transition delay and cell cycle arrest in M phase

What does the first "this" (in "this would work") refer to?

What's the problem? Canto follows has_part links, so it's expected a phenotype that has G2/M delay as a part gets suggested. As I interpret FYPO:0003875, G2 "arrest" is transient, and M arrest is permanent and fatal.

This does rather reinforce my sense that it's right not to put any arrest terms as is_a descendants of viable or inviable.

**Comment by ValWood** [comment]
>I was referring to this
In #2586 we decided that transient arrest was similar enough to a transition delay that a new term wasn't needed. I added some synonyms, but at the moment they're 'related' scope so maybe they're hard to spot in Canto. Should they be exact? Also let me know if you spot any I missed.

but I see what you mean, the arrest is in M phase, (and it would be late M-phase I think these (clp1 and ubc11) are spindle elongation and mitotic exit in M-phase, when I read it I was thinking these arrest *at* the transition point).  An alternative,  so we could keep the arrest as inviable, would be to split this term into   2 annotations representing
G2/M delay 
M phase arrest 

I have a feeling that the viability is more useful than the coupling of the 2 observations together
(which can easily  be done by the user on a single gene basis when we can filter on allele).

@jvhayles  which is most useful?  being able to see if the "arrest" is transient or terminal, or being able to see that delay/arrest occurs at 2 points in  the same mutant in a single term?

**Comment by JackyVH** [comment]
Well  the transient and the arrest could both be equally important, but I think that most users want to know the terminal phenotype as this is the most obvious phenotype   For  cdc2, some of the alleles show a G1 delay and then a G2 block  these are annotated to two terms G1 delay and G2 arrest.  The problem with this is that it in some situations is not clear that for all cells that they show both a  delay in G1 and then become blocked in G2, or that  there  is two different cell populations, so the delay and the arrest for the same mutant in the same term could be useful. Though  as you say  it in most cases it can be worked out by  the user.  Not sure this is very helpful.

Jacky

**Comment by ValWood** [comment]
Move to pending?

**Comment by mah11** [comment]
closing because it's been so long since last activity, and it's not clear, what, if anything, might be done for it
