### ISSUE TITLE
NTR: decreased splicing efficiency PMID:26730850

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2918]
decreased mRNA splicing efficiency via spliceosome

and since 
intron-specific abnormal mRNA splicing, via spliceosome
exists

decreased inton specific mRNA splicing efficiency via spliceosome

**Comment by ValWood** [comment]
a thought:
for fypo we don't need to "via splicosome" to any mRNA splicing term...
its all spliceosomal.....

**Comment by ValWood** [comment]
The highly efficient splicing of res2 and rpl29 were barely affected by inhibition of Prp4 kinase. By contrast, for res1 and tbp1, unspliced pre-mRNAs accumulated and almost no mRNA was detected, as little as 10 min after the addition of inhibitor. This strong inhibition of splicing was transient, and mature spliced mRNA transcripts of both genes were observed again after 60 min. After 180 min, spliced mRNA levels were similar to those observed in the absence of inhibition (Fig 1D)

**Comment by ValWood** [comment]
def: decreased inton specific mRNA splicing efficiency via spliceosome
A cellular process phenotype observed in the vegetative growth phase of the life cycle in which mRNA splicing via the spliceosome takes place normally for some, but abnormally for other, specific introns.

so that makes it identical to def of existing

FYPO:0003244	intron-specific abnormal mRNA splicing, via spliceosome

hmmm, help needed....

**Comment by mah11** [comment]
I don't think I understand the difference between "decreased splicing" and "decreased splicing efficiency".

**Comment by ValWood** [comment]
No I now think they are the same.
we can use
FYPO:0003244	intron-specific abnormal mRNA splicing, via spliceosome
