### ISSUE TITLE
MP  microtubule-based movement

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2919]
FYPO:0005827
Ontology	fission_yeast_phenotype
Term name
normal protein transport along microtubule during vegetative growth

needs
normal microtubule-based movement

**Comment by mah11** [comment]
grrr. that really should be inferred by the reasoner ....

**Comment by mah11** [comment]
asserted link

edit file: 0b30150db46ca4fa9ec69fa8fc23d6647733f798
release: d7531c90d1f9889de8e57e611de9c402f4687db4
