### ISSUE TITLE
ntr: normal protein transport along microtubule during vegetative growth

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2920]
I'm being a bit picky here but I'm one term short

For this one I wanted
ntr: normal protein transport along microtubule to cell cortex of cell tip during vegetative growth

**Comment by mah11** [comment]
normal protein transport along microtubule to cell tip cortex during vegetative growth FYPO:0005841

edit file: 0b30150db46ca4fa9ec69fa8fc23d6647733f798
release: d7531c90d1f9889de8e57e611de9c402f4687db4

**Comment by ValWood** [comment]
Hmm, why Oh why don't I put the PMID.... this could be one of about 10....

**Comment by ValWood** [comment]
PMID:15177031
