### ISSUE TITLE
normal protein localization to cytoplasmic microtubule

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2921]
standard def
PMID:15177031

**Comment by mah11** [comment]
normal protein localization to cytoplasmic microtubule FYPO:0005842

edit file: 0b30150db46ca4fa9ec69fa8fc23d6647733f798
release: d7531c90d1f9889de8e57e611de9c402f4687db4

**Comment by ValWood** [comment]
hmm I wanted a term in between

normal protein localization to microtubule cytoskeleton during mitotic interphase
and
normal protein localization to microtubule end during mitotic interphase


so I should have said
normal protein localization to interphase microtubule 

but all interphase microotubules are cytoplasmic so....it would also be a child of

normal protein localization to cytoplasmic microtubule FYPO:0005842

**Comment by mah11** [comment]
normal protein localization to cytoplasmic microtubule during mitotic interphase FYPO:0005856
with 'interphase microtubule' synonym

edit file: 39b7f12b4b763a4f85451bfff712d553ce002b33
release: 283902eb88adde96079e85c474853903133bd800
