### ISSUE TITLE
cell wall accumulation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2925]
JAcky used
abnormal abnormal cell wall biogenesis as a placeholder for term suggestion 
for accumulation of cell wall material.

I found
increased cell wall polysaccharide level	

can that go under abnormal cell wall biogenesis?

**Comment by mah11** [comment]
> ... for accumulation of cell wall material

FYPO:0004859 is specific for extra polysaccharide in the cell wall. Does that cover everything Jacky wants, or is there cell wall material in the cytoplasm (I can add a term and clarify names if need be)?

> can that go under abnormal cell wall biogenesis?

Will increased cell wall polysaccharide level output_of abnormal cell wall biogenesis work? They can't be linked by is_a.

**Comment by ValWood** [comment]
I'm not sure if you can tell. I remember annotating something recently. I think when there is extra cell wall material it *looks* as though it is in the cytoplasm, but that is only because the cell wall  impinges on the cytoplasmic space ...this could be the same, I'll look up the other phenotype after I finish this one.

Output_of sounds fine...

**Comment by mah11** [comment]
link added

edit file: 0b30150db46ca4fa9ec69fa8fc23d6647733f798
release: d7531c90d1f9889de8e57e611de9c402f4687db4
