### ISSUE TITLE
various, multiseptate/septa   PMID:27898700

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2929]
PMID:27898700

inviable stubby multi-septated vegetative cell
descendent of
FYPO:0002200	inviable stubby septated vegetative cell

thin incomplete primary septum
FYPO:0004654	thin, incomplete secondary cell septum
descendent of
thin discontinuous primary septum

NTR: abnormal septum site selection, incomplete septum, asymmetric assembly sites
A cellular process phenotype observed in the vegetative growth phase of the life cycle in which barrier septum assembly takes place in an abnormal location. The  septum begins assembly  at 
two sites which are not on opposite sides of the medial cortex and terminates prematurely on both sides.
child of 
FYPO:0002154	abnormal septum site selection
(is also is_a incomplete septum)

NTR thick secondary cell septum
descendent of
FYPO:0003211	abnormal secondary cell septum biogenesis

NTR abolished protein localization to cell tip

**Comment by mah11** [comment]
> thin incomplete primary septum

"thin discontinuous primary septum" isn't a term now, and will be an exact synonym of the new term

> abnormal septum site selection, incomplete septum, asymmetric assembly sites
> ..
> (is also is_a incomplete septum)

I'll polish up the name wording. We don't have a generic "incomplete septum" term; I can add one, but I can't link it by is_a to a "septum assembly" term because a process phenotype can't be a type of structure phenotype (and vice versa). I'll make sure there's a path involving output_of.

Same goes for "thick secondary cell septum" and septum biogenesis - path will include output_of.

> abolished protein localization to cell tip

is FYPO:0001585 (not so new ;) )

**Comment by ValWood** [comment]
> abolished protein localization to cell tip
is FYPO:0001585 (not so new ;) )

I keep forgetting that abolished isn't a descendent of abnormal....

**Comment by ValWood** [comment]
I always until just, thought that it should be, but its good that you insisted not. "Abolished  process"  or "abnormal process" might be really useful "slim filters" on a gene page....

so you could quickly see which alleles abolished process completely or affected them.

I see the filters as way of  accessing specific alleles of different types like this....

**Comment by mah11** [comment]
inviable stubby multiseptate vegetative cell FYPO:0005869
  incomplete septum FYPO:0005870
  thin, incomplete primary cell septum FYPO:0005871
  abnormal septum site selection from asymmetrically located sites, forming incomplete septum FYPO:0005872
  increased secondary cell septum thickness FYPO:0005873

edit file: 39b7f12b4b763a4f85451bfff712d553ce002b33
release: 283902eb88adde96079e85c474853903133bd800
