### ISSUE TITLE
decreased rate of medial membrane band assembly

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2930]
child of 
FYPO:0000419	decreased rate of cytokinesis

	PMID:26877082

(requested increased before...)

**Comment by mah11** [comment]
In GO CC, "medial ring" is an exact synonym of "medial cortex". There isn't an assembly term in GO BP - should there be?

And is medial cortex/ring assembly different from the node condensation in #2915 / FYPO:0003444? Need to know for term names, defs, etc.

I can't find any record of a corresponding "increased" term or request.

**Comment by ValWood** [comment]
I don't think "medial ring" is equivalent to "medial cortex"
However I don't know much about the composition of the medial ring....
There is also this term GO:0036391 medial cortex septin ring which we have used for gef3 and myo2 (I'm not sure that this is correct for myo2).
I'm not sure how the composition of the "medial ring" changes over time, or whether  it is a precursor to, or independent from the eventual cytokinetic ring.... I think I would need to do a lot more cytokinesis annotation....

Maybe we can punt this for a while and come back to it?

**Comment by mah11** [comment]
I don't mind waiting. Sounds like GO will also need some work when you do have a better idea what's going on.

**Comment by ValWood** [comment]
Ah I mean medial membrane band.....we have this already 
https://github.com/pombase/fypo/issues/2914

**Comment by mah11** [comment]
OK, adjusted summary accordingly

**Comment by mah11** [comment]
decreased rate of medial membrane band assembly FYPO:0005874

(might not be in release until Sunday)
