### ISSUE TITLE
min mutants

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2932]
some old genetic map mutnts are called methionine inhibited (min)

would this be a suitable synonym for "sensitive to methionine"?

**Comment by mah11** [comment]
added "methionine inhibited" synonym (just "min" isn't really specific enough)

edit file: e73dcd46b4e928057ad850069eacfd62e2b9db82
release: 718d910492a2fa5fc1c780279990ef57ebb480a6

**Comment by ValWood** [comment]
Yep thanks thats what I meant..Min is just the allele name.
Thanks.
