### ISSUE TITLE
PMID:17248775 proline, tyrosine, glutamate, tryptophan auxotrophy

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2933]
thats all....

**Comment by ValWood** [comment]
also add "auxotrophic" to "auxotrophy" parent as synonym.

**Comment by mah11** [comment]
growth auxotrophic for proline FYPO:0005875
  growth auxotrophic for tyrosine FYPO:0005876
  growth auxotrophic for glutamate FYPO:0005877
  growth auxotrophic for tryptophan FYPO:0005878

edit file: e73dcd46b4e928057ad850069eacfd62e2b9db82
release: 718d910492a2fa5fc1c780279990ef57ebb480a6
