### ISSUE TITLE
PMID:27666591	FYPO:0003410	increased spatial extent of CENP-A containing nucleosome assembly

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2936]
The paper I am checking used
	FYPO:0003410	increased spatial extent of CENP-A containing nucleosome assembly
for 

"multiple foci of CENP-A" 
"ectopic assembly of CENP-A chromatin

which is actually correct, based on the def, but is not how I intended it.
This term was meant to indicate "CENP-A containing nucleosome *spreading*" out of the centromeric region, but not its assembly at a completely ectopic location.

Can we make this clearer in the original def?
and add a new term for the ectopic assembly

"A phenotype where CENP-A containing heterochromatin is assembled at  chromatin regions spatially separated from the centromeric domain"
PMID:27666591

**Comment by mah11** [comment]
new term
  ectopic CENP-A containing nucleosome assembly FYPO:0005887

added 'centromeric region' bumf to defs FYPO:0003410,  FYPO:0004322
