### ISSUE TITLE
PMID:27666591 increased protein localization to nucleoplasm

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2937]
child of
FYPO:0000782	mislocalized protein during vegetative growth

PMID:27666591

(in this case the protein is normally localized to centromeric chromatin)

**Comment by mah11** [comment]
is FYPO:0002541

It's not is_a FYPO:0000782 because it also covers the case where a protein is normally in the nucleoplasm, but there's more of it there in a mutant.

Do you want a term like 'decreased protein localization to centromeric chromatin, with protein mislocalized to nucleoplasm'?

**Comment by ValWood** [comment]
OK please.

**Comment by mah11** [comment]
decreased protein localization to centromeric chromatin, with protein mislocalized to nucleoplasm FYPO:0005888
