### ISSUE TITLE
condition "latA pulse"

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2939]
A LatA pulse triggers actin relocalization to both ends in all cells, including those which have not undergone NETO (Rupes et al., 1999). 

Or should I just useLatA?

Jacky also added +rhodamin-phalloidin  @jvhayles i'm deleting this as it is a method to stain cells, rather than a "condition"

**Comment by Antonialock** [comment]
just use latA I think :)

**Comment by ValWood** [comment]
I guess whn this is used as a condition it is always a pulse. Will do...
