### ISSUE TITLE
ntr: increased protein level in chromatin during  vegetative growth

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2943]
I appear to have omitted this one:

increased protein level in chromatin during  vegetative growth

FYPO:0001327	increased protein level during vegetative growth

**Comment by mah11** [comment]
increased protein level in chromatin FYPO:0005893

edit file: f094bc11125c3590c697377e223d11a86047d295
release: 24e51dc0e2a4f9da07bc673ce2c61e6c314d91ba
