### ISSUE TITLE
PMID:18079700 terms for WAPL annotations

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2944]
Fig3

for
https://github.com/pombase/curation/issues/1232

normal protein localization to chromatin during mitotic G1

decreased protein localization to centromeric chromatin during mitotic G1

decreased protein localization to chromatin during mitotic G1

increased protein localization to chromatin during mitotic G1

increased protein localization to centromeric chromatin during mitotic G1

**Comment by ValWood** [comment]
This one would be useful if  it's quick and you have time

**Comment by mah11** [comment]
normal protein localization to chromatin during mitotic G1 phase FYPO:0005894
  decreased protein localization to centromeric chromatin during mitotic G1 phase FYPO:0005895
  decreased protein localization to chromatin during mitotic G1 phase FYPO:0005896
  increased protein localization to chromatin during mitotic G1 phase FYPO:0005897
  increased protein localization to centromeric chromatin during mitotic G1 phase FYPO:0005898

edit file: 4228b2a736a48ea67746f1522ac95744eacd49e8
release: 24e51dc0e2a4f9da07bc673ce2c61e6c314d91ba
