### ISSUE TITLE
ntr: normal protein level during mitosis

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2954]
standard...

**Comment by ValWood** [comment]
PMID:9312055

**Comment by ValWood** [comment]
abd 
decreased protein level during mitotic G1

**Comment by mah11** [comment]
normal protein level during mitosis FYPO:0005925

edit file: a5b32a3901749ab84810fc61c02ff13e179f38c7
release: c8062624a4989976b20aa06787b87f9d6f4b24ab

**Comment by mah11** [comment]
drat, missed the one in the follow-up comment. will add it tomorrow.

**Comment by mah11** [comment]
OK, last bit done

  decreased protein level during mitotic G1 phase FYPO:0005933

edit file: 3c0adce71a5d2f46ff0dd4d2d5ee289311ad2ce8
release: b87f9fc3d7321fedc160088bf0d21727a683f9bd

**Comment by ValWood** [comment]
found FYPO:0005933 but could not see it under place holder 

decreased protein level during vg?

**Comment by mah11** [comment]
oops, botched the xp, which made the reasoner put it in the wrong place. fixed now.

edit file: 62fd042ca65ac53d543a679a4d42bdedce18b28c
release: 3f1297b6351d47660373cd73597ad3470c37d008
