### ISSUE TITLE
ntr: ubiquitination

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2955]
normal monoubiquitination 
abolished polyubiquitination

PMID:9312055

**Comment by mah11** [comment]
normal protein monoubiquitination during vegetative growth FYPO:0005927
  abolished protein polyubiquitination during vegetative growth FYPO:0005928

edit file: a5b32a3901749ab84810fc61c02ff13e179f38c7
release: c8062624a4989976b20aa06787b87f9d6f4b24ab
