### ISSUE TITLE
evaluating behaviour of "output_of"

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2963]
This may not be the most appropriate place for this but I want to record so I can refer back to what I looked at... this one does seem to be a question about phenotype ontology, primarily...

altered protein level	FYPO:0000834	output_of	gene expression phenotype FYPO:0000142
altered protein level has  268 annotations.
These should show as a descendant/query for “gene expression phenotype”
(In the query builder they do)
and I would expect to see “altered protein level” as a descendant of “gene expression phenotype” (I do)

This seems different?
Following the above all proteins annotated to “abnormal actin cortical patch” to be also annotated to “abnormal actin cortical patch organization”
abnormal actin cortical patch	FYPO:0003987	output_of	abnormal actin cortical patch organization FYPO:0000790

but this seems the wrong way around?
If it is true that all “abnormal actin cortical patch” could be annotated to “abnormal actin cortical patch organization”, this implies that there are other ways for the actin patch to be abnormal in addition to “organisation” which would make the existing relationship untrue…
(I guess then the question would be what is the difference between these 2 terms?, Is "abnormal actin cortical patch required?).

**Comment by ValWood** [comment]
There are quite a few of these:

abnormal actomyosin contractile ring	FYPO:0004736	output_of	abnormal actomyosin contractile ring organization	FYPO:0004738

where  it seems odd in Canto to go from
abnormal actomyosin contractile ring organization	FYPO:0004738
to abnormal actomyosin contractile ring	FYPO:0004736

but everything else I looked at makes sense?

**Comment by ValWood** [comment]
I think I get it...
So  "abnormal actomyosin contractile ring" is the "observation", and organization can be inferred...

**Comment by ValWood** [comment]
Also this one appears to behave differently in the query builder.

T-shaped cell	FYPO:0005566	output_of	abnormal cell polarity	FYPO:0005568

Based on the above, I expected all
"T-shaped cell" to also be annotated to "abnormal cell polarity"
but they aren't?
Was this relationship added recently?
![t-shaped](https://cloud.githubusercontent.com/assets/7359272/23206860/278f300a-f8e7-11e6-8a4b-2bbfb7df01cc.jpg)

**Comment by ValWood** [comment]
OK, I now see that the T-shaped  business is a non- issue, because I was using vegetative cell polarity, and not cell polarity.
https://github.com/pombase/fypo/issues/2964 will fix

**Comment by mah11** [comment]
First, before we go any further with this or the Chado ticket (https://github.com/pombase/pombase-chado/issues/613), we have to nail down one thing: do you mean has_output or output_of? 

The ticket titles say has_output, but all of the example links in both tickets are output_of. They are not the same (and shout if you need me to review the difference), and I don't think confusing them is going to help us suss out how we want them handled.

(I have changed the title on #2964 - it was clear there because there was only one link in question.)

**Comment by ValWood** [comment]
It is about out_put of, I corrected the title here

**Comment by ValWood** [comment]
Anyway I think I answered my own question here, can close this. Relevent  follow up is now in
https://github.com/pombase/pombase-chado/issues/613
