### ISSUE TITLE
increased pre-mRNA level	FYPO:0001908	output_of	link

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2965]
Is this one OK?

increased pre-mRNA level	FYPO:0001908	output_of	decreased mRNA splicing, via spliceosome	FYPO:0003029

I presume you can get increased pre-mNRA by increasing transcription too?

**Comment by mah11** [comment]
good point. I'll remove that link.

**Comment by mah11** [comment]
done

edit file: 0d9722396812a51fc5f72387734c81fe4137fa4a
release: 6f259a41134e8ac25aef2208b93300fefa663bad
