### ISSUE TITLE
odd inviable aseptate mononucleate vegetative cell	FYPO:0003763	output_of

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2966]
trying to figure this one out:

inviable aseptate mononucleate vegetative cell	FYPO:0003763	output_of	abnormal cell separation after cytokinesis, with abnormal nuclear division	FYPO:0001973

I can't see an immediate connection....this is usually a cell which has not entered mitosis? I think  this arrest can occur after an unsuccessful cytokinesis, (entry into M phase is bloched in subsequent mitosis) but that isn't the only reason for the phenotype...

**Comment by mah11** [comment]
That's probably a plain old mistake; easy to fix.

**Comment by mah11** [comment]
done

edit file: 0d9722396812a51fc5f72387734c81fe4137fa4a
release: 6f259a41134e8ac25aef2208b93300fefa663bad
