### ISSUE TITLE
obsolete morphology during response to x stress

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2970]
From
https://github.com/pombase/curation/issues/777
once done, open curation ticket to fix and *add conditions* to exisiting annotation

**Comment by mah11** [comment]
obsoletes done
edit file: 59497db2cce81e698864a1e4842211f4440e9284
release: 515401f86eabfead95468105c1f170ae4baa56c5

we should get log warnings about annotations using obsolete terms - I'll put them in a curation ticket

**Comment by ValWood** [comment]
Good plan we can work through them in chunks...
