### ISSUE TITLE
ntr: increased duration of mitotic cell cycle

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2975]
(i.e. the time from the first peak of septation to the second peak)
but no additional resolution

PMID:28103117

**Comment by mah11** [comment]
increased duration of mitotic cell cycle FYPO:0005955

edit file: b895d38c963f1ff31454347fe9ddd7e811a5ea3e
release: e4176e89bd1d1c1386ada6ef10a69fa585885360
