### ISSUE TITLE
ntr: decreased protein dephosphorylation during vegetative growth

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2976]
PMID:28103117

**Comment by ValWood** [comment]
and during mitosis

**Comment by mah11** [comment]
abnormal protein dephosphorylation during vegetative growth FYPO:0005956
  decreased protein dephosphorylation during vegetative growth FYPO:0005957
  decreased protein dephosphorylation during mitosis FYPO:0005958

edit file: b895d38c963f1ff31454347fe9ddd7e811a5ea3e
release: e4176e89bd1d1c1386ada6ef10a69fa585885360
