### ISSUE TITLE
ntr: decreased mitochondrial genome copy number

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2981]
synonym: 
decreased mitochondrial DNA copy number
PMID:28334955

**Comment by mah11** [comment]
We already have decreased cellular mtDNA level (FYPO:0003769). Is that the same thing? If so, which should be the name and which the synonym?

If they're not the same, how should I define the terms so the difference is clear?

**Comment by ValWood** [comment]
Oh I can use that....could add as a related synonym (they call it decreased copy number but they really did RT PCR)

**Comment by mah11** [comment]
OK, synonyms added

edit file: 9a8aa288c26f64bf35f6505a55191a7de6331f9d
release: 8a65a1e11585e96c9d5cf4878d99dfb26181dd4b

**Comment by ValWood** [comment]
couldn't find this by "mitochondrial copy"
located via this route but something might not be updating

**Comment by mah11** [comment]
that's because it's copies of the DNA, not "copies" of mitochondria, so the new synonyms use "mitochondrial DNA copy number" and "mitochondrial genome copy number"

**Comment by ValWood** [comment]
Yep I tried different combinations. I couldn't find anything with "copy" in it?

**Comment by mah11** [comment]
talk to Kim; they're in the current FYPO release
