### ISSUE TITLE
ntr: increased rate of spindle elongation in anaphase B PMID:27872152

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2984]
PMID:27872152
standard def

**Comment by mah11** [comment]
I had a quick look at the paper and the Canto session - the term request column in Canto doesn't match the ticket summary here. It has "increased rate of spindle elongation in anaphase B".

Looking at the data, I think "decreased rate" fits the data (it's slower in mutant than in wt), but using the "spindle elongation" process makes more sense as well as being that bit more specific.

Unless you tell me I've got it wrong, I'll add "decreased rate of spindle elongation during mitotic anaphase B".

**Comment by mah11** [comment]
oops, misread their chart; corrected above comment accordingly

**Comment by ValWood** [comment]
yes thats what I meant!

**Comment by mah11** [comment]
increased rate of mitotic spindle elongation during anaphase B FYPO:0005976

edit file: ecdc047b6976174d542de36940a8a9cdc97bf601
release: 3ba2ab6d426ac43386f5b9608e397af326f9d807
