### ISSUE TITLE
ntr: prion formation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2985]
Non mendelian inheritance of protein aggregates.

**Comment by mah11** [comment]
paper?

I want to check whether it would be better to do a process phenotype or a "prions present" level-of-stuff term.

**Comment by ValWood** [comment]
PMID: 28191457

**Comment by mah11** [comment]
In the end I put it directly under "abnormal vegetative cell phenotype"

  prion formation FYPO:0005977

edit file: 0e8f579f48cae196c62f843725c458007f2aa723
release: 30815c2636b76b3e5632cfd58d6e838d57d073
