### ISSUE TITLE
actin cable vs bundle

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2987]
contrary to what we decided previously:

I asked if bundles and cables were different.
Jenna Christensen, Kovar lab:

Yes! This may vary based on organism, but at least in fission yeast, an actin cable is a very defined thing. In fission yeast, actin cables are one of the three main actin networks (actin cables, the contractile ring, and actin patches) and are defined as being assembled by a specific formin assembly factor (For3) and have a specific set of actin binding proteins associated with them. So, to say that something affects cable assembly, you would have to demonstrate that that affected actin network contains actin binding proteins that are normally present in an actin cable.  The term actin bundle is pretty generic (just means two or more actin filaments bundled together), and an actin filament is just a single filament. So, if you want a more generic term, I would go with 'actin bundle' (for two or more actin filaments) or 'actin filament' (to describe a single filament) rather than using 'actin cable'.

So we need to split...

actin bundle assembly/actin cable assembly

v

**Comment by mah11** [comment]
From this it sounds like "actin cable" corresponds to GO:0070648 "formin-nucleated actin cable" - could you confirm?

If GO:0070648 does represent pombe actin cables, then there's nothing to split; we really only have FYPO terms for actin cables and for actin filaments (not specifying bundles), not for any other types of actin filament bundle. All I would have to do is change the "actin cable" term xps and delete some synonyms.

**Comment by ValWood** [comment]
yes thats correct, all cables are formin nucleated...

I wanted the term for "decreased bundle assembly"  but the term is called "actin cable assembly" 
so we may need to review these....

**Comment by ValWood** [comment]
Oh  I see, it only has formin annotated (at least in live).

**Comment by mah11** [comment]
If I use the formin-nucleated cable GO CC term for existing xps, and remove the "filament bundle" synonyms, then what you need becomes a straightforward ntr. Which paper? (so I can get a decent definition for the bundles-that-aren't-formin-nucleated-cables)

**Comment by ValWood** [comment]
PMID: 27075176

**Comment by mah11** [comment]
new terms:
  abnormal actin filament bundle organization FYPO:0005979
  decreased actin filament bundle assembly FYPO:0005980

Bear in mind that 'formin-nucleated actin cable' is an is_a descendant of 'actin filament bundle' in GO, so some of the older terms will inherit paths to FYPO:0005979 by reasoning.

improved xps, text defs and synonyms for actin cable terms (FYPO:0002030, FYPO:0002435, and descendants) 

edit file: 0e8f579f48cae196c62f843725c458007f2aa723
release: 30815c2636b76b3e5632cfd58d6e838d57d073
