### ISSUE TITLE
non-vegetative versions of some terms

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2995]
abnormal maintenance of protein location to cell cortex of cell tip during karyogamy

normal protein localization to cell cortex of cell tip during karyogamy

**Comment by mah11** [comment]
abnormal protein localization during mating FYPO:0005989
  abnormal maintenance of protein location in cell cortex of cell tip during karyogamy FYPO:0005990
  normal protein localization to cell cortex of cell tip during karyogamy FYPO:0005991

edit file: 01ba4a11eebc4116f235ea963c18d01e231dc4ef
release: acbc41b365922deb2a26ca46510834c779d780c0

**Comment by ValWood** [comment]
normal protein localization to cell cortex of cell tip during karyogamy FYPO:0005991

I didn't see this as a descendant of 
normal protein localization to cell tip

**Comment by ValWood** [comment]
FYPO:0005991
normal protein localization to cell cortex of cell tip during karyogamy

is not a descendent of
normal protein localization to cell cortex

**Comment by ValWood** [comment]
abnormal maintenance of protein location in cell cortex of cell tip during karyogamy
is not a descendant of

FYPO:0005464
abnormal maintenance of protein location at cell tip during vegetative growth

**Comment by mah11** [comment]
That's because the existing 'normal protein localization to cell cortex' and 'normal protein localization to cell tip' terms are defined as during vegetative growth. I'll rename them to make that explicit. Once that's done, will you need non-veg equivalents?

(Mating is not counted as vegetative growth generally in FYPO - that also covers the last one.)

**Comment by ValWood** [comment]
ignore this one ;)

**Comment by mah11** [comment]
well, I will do the renaming so you don't forget and ask again ;)
(and users don't get confused the same way)

**Comment by mah11** [comment]
renaming done
