### ISSUE TITLE
ntrs PMID:28031482

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2996]
decreased protein localization to cytoplasmic P-bodies
synonym decreased protein localization to cytoplasmic P-body
descendent of
FYPO:0000443	abnormal protein localization during vegetative growth
(can we add P-body synonyms to all of the P-body terms)

normal deadenylation

normal cytoplasmic translation

abolished  localization to cytoplasmic P-bodies
FYPO:0001179	abolished protein localization during vegetative growth

**Comment by mah11** [comment]
Is the first one protein localization? Suggested ancestor says yes, but suggested name isn't that specific. Please clarify.

There is no term that mentions "P-bodies" but does not have at least one synonym using "P-body". If you want additional synonyms, I'll need a bit more specifics.

**Comment by ValWood** [comment]
hmm, I'm sure they didn't all show, will need to double check

**Comment by mah11** [comment]
For some of them te wording isn't identical - e.g. for FYPO:0001895 saying "P-body present in increased numbers" wouldn't make grammatical sense. It has "enhanced P-body formation" as a related synonym.

**Comment by ValWood** [comment]
when I type "P-body" I see
FYPO:0001900
FYPO:0001896 (although oddly I don't see P-body synonym here)
FYPO:0001895
FYPO:0001898

when I do "P-bodies" I see 8 terms

**Comment by ValWood** [comment]
Ah OK its to do with the synonym type...but off that they don't all show  up even so...

**Comment by mah11** [comment]
Different question: for "normal deadenylation", should I use GO:0000289? If not, which GO term?

    id: GO:0000289
    name: nuclear-transcribed mRNA poly(A) tail shortening
    namespace: biological_process
    def: "Shortening of the poly(A) tail of a nuclear-transcribed mRNA from full length to an oligo(A) length." [GOC:krc]
    synonym: "3' to 5' mRNA deadenylation" RELATED []
    synonym: "mRNA deadenylation" RELATED []
    synonym: "nuclear mRNA poly(A) tail shortening" RELATED []

**Comment by mah11** [comment]
decreased protein localization to P-bodies FYPO:0005992
  normal cytoplasmic translation FYPO:0005993
  normal mRNA deadenylation FYPO:0005994

For FYPO:0005992 "cytoplasmic" is in one synonym because it's redundant with the ancestry of P-body in GO.

FYPO:0005994 uses GO:0000289 in its xp, but I can change that if it should point to something else.

I did add some more "P-body" synonyms to "P-bodies" terms.

edit file: 01ba4a11eebc4116f235ea963c18d01e231dc4ef
release: acbc41b365922deb2a26ca46510834c779d780c0

**Comment by ValWood** [comment]
Yep 
GO:0000289
name: nuclear-transcribed mRNA poly(A) tail shortening
for X-P
https://github.com/geneontology/go-ontology/issues/13291

**Comment by mah11** [comment]
in that case, this is all set
