### ISSUE TITLE
Query about RNA level annotation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2997]
If we are adding these I'd like

increased level of lncRNA 

(I had a feeling that we weren't but we  have lots of RNA type specific terms, so I can't exactly remember)

**Comment by mah11** [comment]
We wouldn't add terms for specific gene transcripts and the like, but types of RNA are fine. My rule of thumb is: if it has a SO term, it can go in.

**Comment by ValWood** [comment]
can this one be renamed

FYPO:0004573
increased telomeric transcript level
Definition
A cell phenotype observed in the vegetative growth phase of the life cycle in which the amount of non-coding RNA transcribed from telomeric regions measured in a cell is higher than normal.

increased telomeric ncRNA transcript level

**Comment by ValWood** [comment]
> : if it has a SO term, it can go in.

OK makes sense

**Comment by mah11** [comment]
increased lncRNA level FYPO:0005995

edit file: 01ba4a11eebc4116f235ea963c18d01e231dc4ef
release: acbc41b365922deb2a26ca46510834c779d780c0
