### ISSUE TITLE
RNA level terms

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2998]
- [ ] increased 5.8 S rRNA level
(there are only 3, do with extensions and merge into increased rRNA level (sibling)?)

- [ ] increased rRNA precursor level, make a descendent of "increased rRNA level"

- [ ]  increased sno primary transcript level, make a descendent of "increased snoRNA level"

- [ ]  increased cenH RNA level, make a descendent of "increased centromeric transcript level"

**Comment by mah11** [comment]
> increased 5.8S[L] rRNA level ... merge into increased rRNA level?

Could do, but what would you put in an extension? The term actually says "5.8SL rRNA", not just plain 5.8S, and there isn't a SO term at present for 5.8SL. On the other hand, if SO adds a term, then doing a merge wouldn't be consistent with our notion in #2997 to allow a "level" term if there's a SO term for the RNA type.

I would also want to be sure you'd never change your mind and want a separate term later ;)

> increased rRNA precursor level, make a descendent of "increased rRNA level"
> increased sno primary transcript level, make a descendent of "increased snoRNA level"

Can't do this, because it would be inconsistent with SO. The "rRNA level" and "snoRNA level" terms refer to the mature RNAs, and the precursor transcripts are not types of mature RNA in SO or in reality.

If you want, I can use the "mature RNA" phrasings in term names (unless I missed any, these terms have "mature $RNA level" exact synonyms now).

> increased cenH RNA level, make a descendent of "increased centromeric transcript level"

done

**Comment by ValWood** [comment]
> increased 5.8S[L] rRNA level ... merge into increased rRNA level?

scub that. You explained that this is in SO in other ticket

**Comment by ValWood** [comment]
OK but I never know that the RNA level terms referred to mature...

For instance with this term
http://pombase2.aska.gen.nz/term/FYPO%3A0001117
I would expect to see all mature and non mature dependents...

 I just had a look at SO and I'm confused:
![primary vs mature](https://cloud.githubusercontent.com/assets/7359272/25037474/3296b798-20f1-11e7-9ec7-12d2873fcdc4.jpg)

It seems inconsistent?

**Comment by ValWood** [comment]
So if I understood correctly there is no way to refer to an RNA object  which covers the primary transcript and the mature transcript of a specific type of  RNA ?
Maybe SO needs to be revised here to have general rRNA_transcript etc grouping terms ?

**Comment by ValWood** [comment]
I see that only applies to rRNA and snoRNA. I think "mature" in therm names would help.
Maybe a grouping term  "increased RNA level" would be helpful for our users?

so they could see  both
http://pombase2.aska.gen.nz/term/FYPO%3A0005507
and 
http://pombase2.aska.gen.nz/term/FYPO%3A0003600
lists combined?

**Comment by mah11** [comment]
> I see that only applies to rRNA and snoRNA.

Also tRNA, and some other ncRNA types for which we don't have FYPO "level" terms. What SO has looks correct - for applicable RNA types, the mature term is linked to the primary transcript term, but by derives_from, not is_a. The mature RNA is not a type of primary transcript, nor vice versa. Similarly, in FYPO, increased level of mature RNA is not a subclass or superclass of increased level of precursor.

> I think "mature" in therm names would help.

OK, will do.

> Maybe a grouping term "increased RNA level" would be helpful for our users?

I'm struggling to name it, though. Assuming "increased RNA level" (FYPO:0001890) is a typo for "increased rRNA level", you're basically asking for terms for "level of any RNA transcribed from rDNA, or any rRNA intermediate or mature rRNA derived from an rRNA primary transcript". Is that going to be too ugly to help anyone? It also couldn't have a logical definition at present, although that's a lesser concern.

**Comment by ValWood** [comment]
I thought that if we had the "mature" and "primary" terms, we could just use
"increased rRNA level"
for def   "any rRNA primary transcript, intermediate or mature rRNA derived from an rRNA primary transcript"

It would be a useful grouping term, and it would be helpful to ensure that people always selected the most appropriate term (I'm not sure that I have, or that it is always possible to say).

**Comment by mah11** [comment]
I'm not keen on deviating from SO's names, and in SO "rRNA" is unambiguously defined as mature rRNA ("... comprises part of a ribosome ..."). I guess I can shorten a name to use "rRNA or precursor".

**Comment by ValWood** [comment]
"rRNA or precursor" would work. It's a pain think we might have to do this since none of the RNA seq etc differentiates between primary and mature....

**Comment by mah11** [comment]
new terms
  altered rRNA or precursor level FYPO:0005996
  altered snRNA or precursor level FYPO:0005997
  altered snoRNA or precursor level FYPO:0005998
  altered tRNA or precursor level FYPO:0005999
  normal rRNA or precursor level FYPO:0006000

and rename rRNA, snRNA, snoRNA, tRNA level terms to make "mature RNA" explicit

I think that's everything, but reopen if I missed something.

edit file: 232de9c892d8a21cd599c2e0873fe11181983101
release: 9f68c72c555a56e3ce39e9e6270d2ec22c5fa29d
