### ISSUE TITLE
more P-body terms PMID:28031482

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#2999]
abolished localization to P-bodies
normal  localization to P-bodies

**Comment by mah11** [comment]
_protein_ localization?

**Comment by ValWood** [comment]
Sorry yes!

**Comment by mah11** [comment]
I know I'm being finicky but since I was just looking at that ticket about RNA levels ...

**Comment by ValWood** [comment]
No it should say. I was plugging in terms last night to old sessions and then spotted that I missed some originally...

**Comment by ValWood** [comment]
I'm so glad you are "finicky" ;)

**Comment by mah11** [comment]
abolished protein localization to P-bodies FYPO:0006001
  normal protein localization to P-bodies FYPO:0006002

edit file: 232de9c892d8a21cd599c2e0873fe11181983101
release: 9f68c72c555a56e3ce39e9e6270d2ec22c5fa29d
