### ISSUE TITLE
parent query FYPO:0000214 - abnormal mitotic chromosome condensation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3000]
does not seem to have 
"abnormal  sister chromtid segregation parentage (matching GO)
http://pombase2.aska.gen.nz/term/FYPO%3A0000214

it has 
is_a DNA metabolism phenotype during vegetative growth
, but condensation os a geometric change, not a metabolic change?

**Comment by mah11** [comment]
fixed manually asserted links

**Comment by mah11** [comment]
edit file: 359f717d472bdd39049bd3df435cd8ab9d7f5111
release: 39fd08f81c88c8c1d9ba4577481b40aeee59bd53
