### ISSUE TITLE
ntr: normal interphase microtubule organization

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3001]
standard def
PMID:12791993 

FYPO:0003326	normal microtubule nucleation during mitotic interphase
as a descendant

**Comment by mah11** [comment]
normal cytoplasmic microtubule organization during mitotic interphase FYPO:0006004

on the grounds that
a) there isn't a plain "microtubule organization" GO term (cytoplasmic microtubule organization is directly under microtubule cytoskeleton organization), and

b) as far as I know it's not normal for pombe to have any nuclear microtubules during interphase

squawk if wrong ...


also included a grouping term
  normal cellular component organization FYPO:0006003

edit file: 359f717d472bdd39049bd3df435cd8ab9d7f5111
release: 39fd08f81c88c8c1d9ba4577481b40aeee59bd53
