### ISSUE TITLE
ntr: inviable binucleate aseptate cell with post-anaphase mitotic cell cycle arrest 

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3003]
inviable binucleate aseptate cell with post anaphase mitotic cell cycle arrest 

Def.
A cell phenotype observed in the vegetative growth phase of the life cycle in which a cell is inviable and has two nuclei  and a stable cytokinetic ring but no septum, the post anaphase array is present, and the mitotic cell cycle is arrested before cell separation.

Descendant of
FYPO:0005689 inviable binucleate aseptate cell with mitotic cell cycle arrest before cell separation

**Comment by mah11** [comment]
Would it be legit to call this arrest in telophase? That would let me say it has_part FYPO:0000622.

(To a pedant - and you know I am one - "post-anaphase" could be any time after anaphase, including the next G1/S or S or ...)

**Comment by ValWood** [comment]
That's much better. I was getting hooked on the post-anaphase array ;)

**Comment by mah11** [comment]
inviable binucleate aseptate cell with cell cycle arrest in mitotic telophase FYPO:0006006

edit file: 359f717d472bdd39049bd3df435cd8ab9d7f5111
release: 39fd08f81c88c8c1d9ba4577481b40aeee59bd53

**Comment by ValWood** [comment]
Doh, no idea what I was annotating here.....

**Comment by ValWood** [comment]
actually I think its equivalent to 
FYPO:0005689 inviable binucleate aseptate cell with mitotic cell cycle arrest before cell separation

because if it's binucleate its after anaphase, it has PAA, but no cytokinesis...

**Comment by mah11** [comment]
If you're sure they're exactly the same, I can merge. Which string would you want as the name (I kind of like the telophase version)?

**Comment by ValWood** [comment]
Yep I can't see a difference.
Telophase version.

**Comment by mah11** [comment]
Went to merge, and was reminded of the existence of FYPO:0003825, inviable binucleate aseptate cell with cell cycle arrest in mitotic G2 phase before cell separation. Should that one also be merged, or should we use FYPO:0005689 as a parent of both FYPO:0003815 and FYPO:0006006? For FYPO:0003825, is the PAA present, or has it gone by the time the nuclei are considered to be in G2?

Should we do this?:

    inviable binucleate aseptate cell with mitotic cell cycle arrest before cell separation
    - [i] inviable binucleate aseptate cell with cell cycle arrest in mitotic telophase
    - [i] inviable binucleate aseptate cell with cell cycle arrest in mitotic G2 phase before cell separation

**Comment by ValWood** [comment]
FYPO:0003825, inviable binucleate aseptate cell with cell cycle arrest in mitotic G2 phase before cell separation.

I think this is the term for when  cytokinesis does not happen in one cell cycle. This prevents  cells entering mitosis in the subsequent cycle...so it has done a successful mitosis (hence binucleate), but has no septum. It goes through the next G1/S since DNA already starts to replicate before cytokinesis,  but stays in G2 so no PAA.

so this is definitely a different phenotype...

**Comment by mah11** [comment]
OK, that argues for the rearranged links rather than merging any.

**Comment by mah11** [comment]
done in
edit file: 8327a5131881826ee4e520dff86baf58bd95679c
release: 85dea041789aa6f6b30f9397f131bc7615d8d37b
