### ISSUE TITLE
decreased actin cortical patch localization at non-growing end PMID:10574765

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3006]
child of
abnormal actin cortical patch localization

(Figure 3c,d)

usually detectable at both ends

**Comment by ValWood** [comment]
and normal...

**Comment by ValWood** [comment]
actually these could be under the "at interphase" term too

**Comment by mah11** [comment]
Is the "decreased" phenotype the same as FYPO:0001397 monopolar actin cortical patch localization to old end? If so, I'll add a synonym.

Likewise, is the "normal" phenotype more specific than FYPO:0002424 normal actin cortical patch localization during mitotic interphase, or should I just add an explanation of what is normal to the existing text def?

**Comment by ValWood** [comment]
Is the "decreased" phenotype the same as FYPO:0001397 monopolar actin cortical patch localization to old end? If so, I'll add a synonym.

Yes I think so


>Likewise, is the "normal" phenotype more specific than FYPO:0002424 normal actin cortical patch localization during mitotic interphase, or should I just add an explanation of what is normal to the existing text def?


yep (i didn't spot the interphase term until  the first part of ticket after so I didn't scrutinize properly)

**Comment by lem14789** [comment]
0002424

**Comment by mah11** [comment]
added synonyms

edit file: 5b70af4280ed441890d71068f03af9d2806c4067
release: a8895c791ff59e277c056136c7d0d60e268f9e26
