### ISSUE TITLE
ntr: decreased protein localization to medial cortex  with protein localized towards the cell cortex of the cell tip

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3007]
For
Cdr2 was restricted to the cell middle in wild-type cells, but localized throughout half of the cell in a pom1D mutant (Fig. 3a). pom1D cells grow in a monopolar manner, and the Cdr2 nodes extended from the cell middle out to the non-growing cell end. 

child of
FYPO:0002557	decreased protein localization to medial cortex during vegetative growth

(i'm ignoring the fact that its only half the cell (this is because pom1 grows monopolarly).

PMID:19474789

**Comment by mah11** [comment]
> (i'm ignoring the fact that its only half the cell (this is because pom1 grows monopolarly).

good. there are some things for which life is too short.

**Comment by mah11** [comment]
How similar is this to FYPO:0002556?

id: FYPO:0002556
name: abolished protein localization to medial cortex during vegetative growth, with protein distributed in non-growing half of cell
def: "A cell phenotype observed in the vegetative growth phase of the life cycle in which the localization of a protein to the medial cortex of a cell is abolished, and the protein is instead detected distributed throughout the half of the cell nearer the non-growing end."

**Comment by ValWood** [comment]
Would be useful to get this one before the weekend so I can put the session back through and see how my  updates look...

**Comment by ValWood** [comment]
Oh I just saw your comment its the correct term. I think the localization is still cortical though so could this be added to the def?

**Comment by ValWood** [comment]
Hmm, maybe should be decreased though. I wouldn't like to say there was no protein at the medial cortical nodes...

**Comment by ValWood** [comment]
which would  work as the term is only used for pom1 delete so far...

**Comment by ValWood** [comment]
abolished protein localization to medial cortex during vegetative growth, with protein distributed in non-growing half of cell

and lets remove "non growing half" of cell and just say throughout the cortex towards cell tip. I'm using this ID...

**Comment by mah11** [comment]
OK, text edits done. New name is "decreased protein localization to medial cortex during vegetative growth, with protein distributed in cell cortex near non-growing end", which just rooooolls right off the tongue ...

edit file: 0a75339a4ed8314e83775b8072c1a8f48fbd973b
release: ae480e35bed3c78f13bbfa97b902bd94eaffe92f

**Comment by ValWood** [comment]
we could leave "vegetative growth" out of the term nam if it is in the def. I don't think this could ever apply to shmooing cells or spores?
