### ISSUE TITLE
FYPO:0005078 - sensitive to canavanine and rapamycin

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3010]
seems odd to have a compound term for sensitivity?

**Comment by mah11** [comment]
well, yes, but it's intended for mutants that only differ from wild type on media that contain both

**Comment by ValWood** [comment]
Oh I see, so different than being sensitive to both independently....OK!

**Comment by mah11** [comment]
yep, we've never thought of a better way to do it

**Comment by ValWood** [comment]
I wonder if there is a way to make it clearer in the term name  without making it too clunky?

Along the lines
sensitive to canavanine and rapamycin in combination

As people might immediately assume that if they use this term in a  query they will get

"sensitive to canavanine" AND "sensitive to rapamycin"

**Comment by mah11** [comment]
I dunno, that looks too clunky to me ;)
and we do hope people will read the definitions ...

but I could add synonyms ...

**Comment by ValWood** [comment]
Yeah I think curating they would, but when using the query builder as I was just, you would not necessarily read the def of every term in the drop down...
(in fact in the current query builder you don't see defs at all in the "term search" or the results so we should remedy that )

I was hoping you could think of something less clunky but no worries...
synonym will do...
