### ISSUE TITLE
abnormal spindle pole body separation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3014]
add mitotic to term name.

**Comment by mah11** [comment]
needs a 'mitotic' GO term to point to - do you intend to request one (is_a GO:0000073, or maybe they can rejig the existing term, since its text def mentions "for a bipolar mitotic spindle to assemble")?

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/13461

**Comment by mah11** [comment]
renaming done; I'll leave this open to remind me to update xps when the GO ticket is done

edit file: e4f6b2b43fbe38b4c10631632b26bac1d526443e
release: 84ee9bd3bde6817531b0fec2be808f045a148a76

**Comment by lem14789** [comment]
84ee9bd

**Comment by mah11** [comment]
GO has used GO:0000073 as the mitotic term.
