### ISSUE TITLE
	decreased nuclear pore density PMID:28242692 

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3015]
PMID:28242692 

A physical cellular phenotype observed in the vegetative growth phase of the life cycle in which a cell contains a decreased number of nuclear pore complexes.

**Comment by mah11** [comment]
decreased nuclear pore density FYPO:0006018

edit file: e4f6b2b43fbe38b4c10631632b26bac1d526443e
release: 84ee9bd3bde6817531b0fec2be808f045a148a76
