### ISSUE TITLE
viable small vegetative cell

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3019]
Does not show up  with "cell cycle" filter, but this is a classical cell cycle phenotype.

I think there are some older tickets about whether this phenotype can occur in other contexts...

**Comment by mah11** [comment]
Filtering behavior is correct - it's classified as a cell phenotype, with cell morphology and cell viability parts.

**Comment by ValWood** [comment]
Yep should also be a cell cycle phenotype?

I think perhaps we need an additional differentia to make this possible.

"Small size at mitotic entry"

**Comment by ValWood** [comment]
will also resolve:
https://github.com/pombase/fypo/issues/2818

**Comment by ValWood** [comment]
and
https://github.com/pombase/fypo/issues/2544

**Comment by ValWood** [comment]
Probably need to ask @jvhayles about this again. I really think people will expect to see wee as a cell cycle phenotype, so there must be a way to define it in cell cycle terms. It might require a new term and moving "classical wee" to this term.

**Comment by mah11** [comment]
In that case, this becomes the same question as in #2544. Closing as duplicate.
