### ISSUE TITLE
various PMID:10462529

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3024]
increased cytosolic monomeric ribosome level

decreased cytosolic half-mer polysome level/increased polysomes

normal cytoplasmic translation initiation

decreased translation gene specific

**Comment by mah11** [comment]
> decreased translation gene specific

I would do this either by using FYPO:0001798 'decreased translation' with extensions if you know the specific genes, or by adding a term with a description of which bunch of genes are affected, a la FYPO:0004010 'decreased translation of ribosomal proteins during vegetative growth' or analogous to the many 'level of [yada] gene mRNA' terms.

The rest are straightforward.

**Comment by ValWood** [comment]
The genes are cdc25 and cdc13 so I can add them.

**Comment by mah11** [comment]
increased cytosolic monomeric ribosome level FYPO:0006036
  decreased cytosolic half-mer polysome level FYPO:0006037
  normal cytoplasmic translational initiation FYPO:0006038

edit file: 86054e611c965a4565ba3160cad116b820e88d41
release: 1a66c5a42bb70111a100b2730d4ed28f1c80d707
