### ISSUE TITLE
synonym FYPO:0005411 - increased number of unattached kinetochores

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3027]
I noticed
FYPO:0005411 - increased number of unattached kinetochores
(this term only has a single annotation

also add synonym "kinetochore loss"

**Comment by mah11** [comment]
related synonym added

edit file: 86054e611c965a4565ba3160cad116b820e88d41
release: 1a66c5a42bb70111a100b2730d4ed28f1c80d707
