### ISSUE TITLE
lipid droplet/particle terms for PMID:28011631 

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3028]
reduced localization of lipid droplets to  FSM leading edge
reduced inclusion of lipid droplets in spore cytoplasm, mislocalized to ascus cytoplasm
	
normal association of lipid droplets to  FSM leading edge

**Comment by ValWood** [comment]
normal spore number
	
reduced lipid droplet formation

**Comment by ValWood** [comment]
reduced spore survival during starvation

**Comment by ValWood** [comment]
inviable spore with normal morphology
add related synonym "abolished spore germination"

**Comment by mah11** [comment]
note to self: found https://github.com/geneontology/go-ontology/issues/13534 and commented there

**Comment by mah11** [comment]
questions & comments for Val:

> reduced localization of lipid droplets to FSM leading edge

Will the localization terms requested in the GO ticket cover this process?

> reduced inclusion of lipid droplets in spore cytoplasm, mislocalized to ascus cytoplasm

decreased level?

> normal association of lipid droplets to FSM leading edge

normal localization?

> normal spore number

Is this in a population or spores per ascus? If it's a population, use FYPO:0002052 "normal sporulation frequency". If it's per ascus, let me know if there are other problems that mean you can't use FYPO:0000590 "normal sporulation", and I can add "formation of ascus with four spores" under normal cellular process.

> abolished spore germination

has been a related synonym for "inviable spore" FYPO:0002151 for ages

> reduced spore survival during starvation

How can this be defined to make a distinction between it and FYPO:0000581 "decreased spore germination frequency"?

> inviable spore with normal morphology
> add related synonym "abolished spore germination"

would be redundant with existing synonym for "inviable spore" noted above

**Comment by ValWood** [comment]
> reduced inclusion of lipid droplets in spore cytoplasm, mislocalized to ascus cytoplasm
decreased level?

That sounds good

> normal association of lipid droplets to FSM leading edge
normal localization?

yep

> Is this in a population or spores per ascus? If it's a population, use FYPO:0002052 "normal sporulation frequency". If it's per ascus, let me know if there are other problems that mean you can't use FYPO:0000590 "normal sporulation", and I can add "formation of ascus with four spores" under normal cellular process.

Its a cell level population with a penetrance. I guess the normal way is to use the "with more or fewer than 4 spores" and add the correct percentage rather than trying to describe the normal...I can do that!

**Comment by ValWood** [comment]
Is this in a population or spores per ascus? If it's a population, use FYPO:0002052 "normal sporulation frequency". If it's per ascus, let me know if there are other problems that mean you can't use FYPO:0000590 "normal sporulation", and I can add "formation of ascus with four spores" under normal cellular process.
Its a cell level population with a penetrance. I guess the normal way is to use the "with more or fewer than 4 spores" and add the correct percentage rather than trying to describe the normal...I can do that!

Actually it is "normal sporulation frequency" which I already did from this figure, so just ignore this request.

**Comment by ValWood** [comment]
> reduced spore survival during starvation
How can this be defined to make a distinction between it and FYPO:0000581 "decreased spore germination frequency"?

ignore

**Comment by mah11** [comment]
decreased lipid droplet localization to prospore membrane leading edge FYPO:0006051
  normal lipid droplet localization to prospore membrane leading edge FYPO:0006052
  lipid droplets present in spore cytoplasm in decreased numbers, mislocalized to ascus epiplasm FYPO:0006053
  decreased lipid droplet assembly FYPO:0006054

From the follow-up comments, I _think_ that's everything for this, but reopen it if I have missed something.


edit file: 8327a5131881826ee4e520dff86baf58bd95679c
release: 85dea041789aa6f6b30f9397f131bc7615d8d37b
