### ISSUE TITLE
PMID:15385632 septin ring stuff various

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3030]
abolished protein localization to septin ring

**Comment by ValWood** [comment]
ectopic septin ring formation
normal positon septin ring forms but additional rings are present at non cell division sites

	
septin ring stabilization

**Comment by mah11** [comment]
> septin ring stabilization

What does this mean? (iow, can you describe it a bit more?)

**Comment by ValWood** [comment]
Grrr I knew you would pull me up on that one. OK it was a cop-out.

Text:
Another noteworthy consequence of mild Mid2p overexpression was the relative persistence of septin rings and the inhibition of mitotic progression, as determined by monitoring the for- mation of binucleates (Figure 8A). This result is consistent with our previous results, indicating that prolonged expres- sion of Mid2p stabilizes septin ring structures and influences cell cycle progression (Tasto et al., 2003).

Unfortunately I didn't fully understand figure 1A because it didn't have a WT  for comparison, an I just don't have this in my  head, so I plumped for "stabilization".

![eh](https://cloud.githubusercontent.com/assets/7359272/26652819/109627f0-4649-11e7-9ca3-ec5c0f53e9a8.jpg)


Just omit this one, it isn't critical info....

**Comment by ValWood** [comment]
I remember struggling with this at the time but in my defence I think it was very late on a bank holiday Sunday night !
No
Figure 8. Coalescence of septin rings can be induced during interphase by mid2􏰁 expression. (A) spn3-GFP cdc16-116 (KGY738) cells were transformed with pREP41-HA-mid2􏰁. Transformants obtained in the presence of thiamine in the medium were then grown to midlog phase in the absence of thiamine at 25°C for 15 h. They were then synchronized in early G2 phase by centrifugal elutriation and immediately shifted to 36°C. Samples of cells were collected every 15 min. One portion of each sample was imaged immediately to determine the percentage of septated cells and the percentage of cells with Spn3p-GFP medial localization. Another portion was fixed with ethanol and stained with DAPI to determine the percentage of binucleate cells. (B and C) Spn3p-GFP localization in live cells at the 75-min time point. In B, cells imaged with a single Z-series stack (0.49 􏰅m) are shown to provide the best visualization of split septin rings as indicated by the arrow. In C, the image in the left panel represents a 3D reconstruction of Z-series stacks. This image was rotated in the Z-axis (right panel) to illustrate the cortical restriction of the septin rings. The arrows point to organized septin rings.

I still don't understand it!

**Comment by mah11** [comment]
I wonder if this could be described as premature septin ring assembly, and maybe also use delayed onset of cytokinesis?

**Comment by ValWood** [comment]
Does the ring assemble early? not sure. I think they persist longer...

my notes in session say 
overexpression was the relative persistence of septin rings and the inhibition of mitotic progression, as determined by monitoring the for- mation of binucleates (Figure 8A). This result is consistent with our previous results, indicating that prolonged expres- sion of Mid2p stabilizes septin ring structures and influences cell cycle progression (Tasto et al., 2003).


maybe delayed septin ring disassembly?

**Comment by mah11** [comment]
I took it to mean that mid2 overexpression combined with cdc16-116 caused the cells to make septin rings in a cell cycle phase when they aren't normally present. "Premature" isn't an exact match for that but it seems like the least bad fit I've found so far in PATO ...

or we could punt and have a term that just says "septin ring assembly during mitotic interphase"

Disassembly could be delayed as well, once the rings form ...

**Comment by ValWood** [comment]
Hmm I guess so.  Cdc16-116 is really just to block cells transiently before SIN and ring constriction.  This is just to determine whether septin rings can form if the SIN is not activated, and they can.

I think
"septin ring assembly during mitotic interphase" works.

**Comment by mah11** [comment]
abnormal protein localization to septin ring FYPO:0006059
  abolished protein localization to septin ring FYPO:0006060
  abnormal septin ring assembly FYPO:0006061
  ectopic septin ring assembly FYPO:0006062
  septin ring assembly during mitotic interphase FYPO:0006063
  abnormal septin ring disassembly FYPO:0006064
  delayed onset of septin ring disassembly FYPO:0006065


edit file: 8327a5131881826ee4e520dff86baf58bd95679c
release: 85dea041789aa6f6b30f9397f131bc7615d8d37b
