### ISSUE TITLE
4-spore ascus (follow on from "lipid droplet")

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3036]
https://github.com/pombase/fypo/issues/3028#issuecomment-306838046

Is this in a population or spores per ascus? If it's a population, use FYPO:0002052 "normal sporulation frequency". If it's per ascus, let me know if there are other problems that mean you can't use FYPO:0000590 "normal sporulation", and I can add "formation of ascus with four spores" under normal cellular process.
Its a cell level population with a penetrance. I guess the normal way is to use the "with more or fewer than 4 spores" and add the correct percentage rather than trying to describe the normal...I can do that!

It was normal spore number (per ascus)
and
reduced spore germination frequency, so I could not use
FYPO:0000590 "normal sporulation"

**Comment by ValWood** [comment]
nore to  self dga1-delta plh1 delta fig  4A (deleted to put session through)

**Comment by mah11** [comment]
sporulation resulting in formation of ascus with than four spores FYPO:0006083


edit file: fe081173f5dc5a0e9bd9186dc2d824c47febc5a2
release: 67ce2158e9b9c31c8afe124f60530a6cd4bc743e
