### ISSUE TITLE
ntr: reduced actin patch localization to non-growing cell end   PMID:10574765

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3037]
standard def

**Comment by mah11** [comment]
We've had "decreased actin cortical patch localization at non-growing end" as a related synonym for FYPO:0001397 monopolar actin cortical patch localization to old end for a while. Can you use that term for this phenotype, or should I remove the synonym and add a new term?

**Comment by ValWood** [comment]
It sounds the same, I'll use it!

**Comment by mah11** [comment]
hooray! I'll add another synonym.
