### ISSUE TITLE
parent query fluctuating mitotic spindle length FYPO:0006049

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3038]
could not see
fluctuating mitotic spindle length FYPO:0006049
as a child of 
abnormal bipolar mitotic spindle

**Comment by mah11** [comment]
I put the parent, FYPO:0006048 ! unstable mitotic spindle, under the process phenotype FYPO:0000131 ! abnormal mitotic spindle elongation.

Would it be (a) accurate and (b) useful to add FYPO:0000131 ! abnormal mitotic spindle elongation has_output FYPO:0001574 ! abnormal bipolar mitotic spindle

**Comment by ValWood** [comment]
It sounds as though it  would be useful.

**Comment by mah11** [comment]
link added

edit file: fe081173f5dc5a0e9bd9186dc2d824c47febc5a2
release: 67ce2158e9b9c31c8afe124f60530a6cd4bc743e
