### ISSUE TITLE
PMID:27146110 more

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3039]
follow on from 
https://github.com/pombase/fypo/issues/3025#issuecomment-305214305

1.
I missed
"sensitive to cold shock" as a descendant of FYPO:0000080
(I can't remember if we decided not to do this, but we  have sensitive to heat shock?)

2.
also
Delayed mitotic sister chromatid segregation

**Comment by mah11** [comment]
> I missed
> "sensitive to cold shock" as a descendant of FYPO:0000080
> (I can't remember if we decided not to do this, but we have sensitive to heat shock?)

I think it's just that no one has requested a "cold shock" term before now.

Also, it won't hurt to have a definition of "cold shock" ... (bet you saw that coming miles off)

**Comment by ValWood** [comment]
"A cell phenotype in which cells show increased sensitivity to ~heat~ cold shock. ~Heat~ Cold shock is a form of ~heat~ cold  stress in which cells are briefly exposed to a very ~high~ low temperature." 

will that do ?

**Comment by mah11** [comment]
1. added sensitive to cold shock FYPO:0006084

2. Use FYPO:0004705 - for the older ticket I looked at the data and made this comment:

>> ntr: normal rate of chromosome segregation
>> meredith's def: Normal speed of chromosome movement toward the mitotic spindle pole during anaphase chromosome segregation
>> 
>> ntr: Delayed mitotic sister chromatid segregation
> 
> Because these are about anaphase movement, the existing "separation" term will do for "delayed", and I've added FYPO:0006050 as separation (in list above).
> 
> delayed onset of mitotic sister chromatid separation FYPO:0004705

**Comment by ValWood** [comment]
I got a bit confused here. Which term should I be suing for


"Delayed mitotic sister chromatid segregation"?

**Comment by ValWood** [comment]
I looked the figure again and "lagging mitotic chromosomes" seem to fit, so I used that...

**Comment by mah11** [comment]
If the beginning of segregation was delayed, we could add "delayed onset of mitotic sister chromatid segregation". But when I looked at this paper, the data fit FYPO:0004705 - the experiment showed a delay in starting separation.

**Comment by ValWood** [comment]
ok used this. I conveniently wiped this paper from my RAM and I don't want to re-read.....
