### ISSUE TITLE
	 premature spindle pole body separation in mitotic metaphase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3044]
premature spindle pole body separation in mitotic metaphase metaphase arrest

A phenotype where the Spindle pole bodies are observed to partially separate prematurely  during metaphase arrest.
(Note, this phenotype often accompanies lost kinetochores)

increased number of unattached kinetochores during metaphase arrest

PMID:17036054

**Comment by mah11** [comment]
When does SPB separation normally take place, relative to other mitotic events? I'm slightly more familiar with the situation in budding yeast, where SPB separation happens well before metaphase. (Remember that GO:0000073 refers specifically to disconnecting SPBs after duplication, not to further migration apart.)

**Comment by ValWood** [comment]
Yes you are right, separation occurs much earlier.

I think in these cases the  normal SPB separation only occurs in some cells (so presumably the tubulin block can cause  other earlier problems).
I will do this one as "normal SPB separation" with penetrance 20%.
Then I'll send the session to Dick to check because I got a bit confused by it...I think you need some insider knowledge  that I don't yet have for complete interpretation.....

**Comment by mah11** [comment]
Thanks. If you don't have all the requisite insider info, I don't feel so bad for getting confused ;)

**Comment by mah11** [comment]
Does this need any work?

**Comment by ValWood** [comment]
nope
