### ISSUE TITLE
NTR: normal duration of meiosis II   PMID:15509865

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3063]
child of
FYPO:0003798 | normal meiosis II

standard def 

ref PMID:15509865

**Comment by mah11** [comment]
normal duration of meiosis II FYPO:0006128

edit file: 1405904c6a591a87f61fbdcbfec7d67a9749321f
release: 8771031cabc25f8e6f5006507b21e5b5ddf00ff0
