### ISSUE TITLE
NTR decreased nuclear movement during shmooing PMID:15509865

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3064]
decreased nuclear movement during shmooing

descendant of PMID:15509865
FYPO:0005462 | decreased microtubule-based movement
-- | --

**Comment by mah11** [comment]
Is this GO:0000743?

id: GO:0000743
name: nuclear migration involved in conjugation with cellular fusion
def: "The microtubule-based movement of nuclei towards one another as a prelude to karyogamy in organisms undergoing conjugation with cellular fusion." [GOC:clt, GOC:vw, PMID:16380440]

**Comment by ValWood** [comment]
Yep

**Comment by mah11** [comment]
decreased nuclear migration during mating FYPO:0006129

edit file: 1405904c6a591a87f61fbdcbfec7d67a9749321f
release: 8771031cabc25f8e6f5006507b21e5b5ddf00ff0
