### ISSUE TITLE
abolished protein localization to microtubule during meiosis PMID:15509865

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3065]
abolished protein localization to microtubule during meiosis

standard def

sibling of
FYPO:0003269 | abolished protein localization to microtubule during vegetative growth

PMID:15509865

**Comment by mah11** [comment]
abolished protein localization to microtubule during meiosis FYPO:0006130

edit file: 1405904c6a591a87f61fbdcbfec7d67a9749321f
release: 8771031cabc25f8e6f5006507b21e5b5ddf00ff0
