### ISSUE TITLE
ntr: sensitive to magnesium chloride

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3068]
PMID:7859738

**Comment by mah11** [comment]
Just double-checking what term(s) you need - I looked at the paper, and I don't see anything testing growth in the presence of (excess?) magnesium chloride ...

**Comment by ValWood** [comment]
Ignore. Is that even a thing. `Was KCl.

**Comment by mah11** [comment]
well, magnesium chloride is a thing ;)
but I didn't think it was the thing they used
