### ISSUE TITLE
copper chelator added

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3071]
copper chelator added
PMID:24569997

synonym Tetrathiomolybdate added

**Comment by mah11** [comment]
synonym will have to be narrow, because lots of other compounds can chelate copper

**Comment by ValWood** [comment]
yep. 
do you think I should have requested "Tetrathiomolybdate added", or is it better to lump?

**Comment by mah11** [comment]
I don't have a strong preference ... lump for now and see if there's ever any demand for greater precision?

**Comment by ValWood** [comment]
yep.

**Comment by Antonialock** [comment]
added plus narrow syn
