### ISSUE TITLE
Describe usages of fypo in the OBO metadata record

### ISSUE THREAD

**Issue by cmungall** [pombase/fypo#3078]
See OBOFoundry/OBOFoundry.github.io#451

I can provide an example

**Comment by cmungall** [comment]
you can close if this is an ok example

**Comment by mah11** [comment]
That example is fine. I'll leave this ticket open for myself, to remind me to update the example URL when we release shiny new PomBase (aiming for September).

**Comment by mah11** [comment]
created pull request to update URL
