### ISSUE TITLE
NTR: mitotic spindle collapse without elongation in anaphase B 

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3082]
A CC session uses this term
FYPO:0002688 | mitotic spindle collapse without elongation
-- | --

This is no elongation after stage I( 2 um stage),

So I think this should be
 | mitotic spindle collapse without elongation in anaphase B 

to be unambiguous

aka

mitotic spindle collapse without spindle extension

**Comment by ValWood** [comment]
PMID:25375240

**Comment by mah11** [comment]
mitotic spindle collapse without elongation during anaphase B FYPO:0006172

edit file: 8aa8e2d9f153e0a57b0d4d62cdeebcfbe68024a7
release: 36712382f085093b31d1d1e73ad8414c05c15b7b
