### ISSUE TITLE
abolished mitotic spindle elongation in anaphase B

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3083]
PMID:25375240

def
A cellular process phenotype  in which mitotic spindle elongation  (spindle extension) does not occur in anaphase B. This  is indicated by the presence of the short 2 micron spindle (blob spindle).

Parents

FYPO:0003829 | abolished mitotic spindle elongation

FYPO:0000732 | short mitotic spindle

note 
FYPO:0003829 | abolished mitotic spindle elongation should have a soft check for "do not annotate" since we should be abe to say when (i.e which spindle elongation, assembly or extension)

**Comment by mah11** [comment]
abolished mitotic spindle elongation during prophase FYPO:0006173
  abolished mitotic spindle elongation during anaphase B FYPO:0006174

(you'll need both if you want to disallow annotation to FYPO:0003829)

edit file: 8aa8e2d9f153e0a57b0d4d62cdeebcfbe68024a7
release: 36712382f085093b31d1d1e73ad8414c05c15b7b
