### ISSUE TITLE
abnormal protein localization to centromere during mitotic metaphase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3084]
child of

abnormal protein localization to centromere during vegetative growth |

standard def
PMID:25375240

**Comment by mah11** [comment]
abnormal protein localization to centromere during mitotic metaphase FYPO:0006175

edit file: 8aa8e2d9f153e0a57b0d4d62cdeebcfbe68024a7
release: 36712382f085093b31d1d1e73ad8414c05c15b7b
