### ISSUE TITLE
abnormal lateral attachment of mitotic spindle microtubules to kinetochore

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3086]
abnormal
GO:0099607 | lateral attachment of mitotic spindle microtubules to kinetochore

descendant of

FYPO:0004213 | abnormal attachment of mitotic spindle microtubules to kinetochore
-- | --
PMID:12426374

(this is the phenotype when some kinetochores do not move away from the SPB in prometaphase)

PMID:12426374

**Comment by mah11** [comment]
abnormal lateral attachment of mitotic spindle microtubules to kinetochore FYPO:0006179
also adjusted asserted parent of ancestor FYPO:0000325

edit file: 2509cfe1689c57e1624c40d5d64acbf415e9b8ee
release: 1ebc4bcfcfd36cb90266efae89dced717274b8c9
