### ISSUE TITLE
ntr: increased microtubule polymerization

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3087]
standard def
parent of 

FYPO:0004615 | increased rate of interphase microtubule polymerization
-- | --

PMID:PMID:12426374

**Comment by mah11** [comment]
increased microtubule polymerization FYPO:0006180

sibling of FYPO:0004615 per https://github.com/pombase/fypo/issues/2834#issuecomment-250203174

edit file: 2509cfe1689c57e1624c40d5d64acbf415e9b8ee
release: 1ebc4bcfcfd36cb90266efae89dced717274b8c9
