### ISSUE TITLE
PMID:19696784 localization terms

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3088]
NTR  increased protein localization to nucleus  decreased protein localization to cytoplasm during vegetative growth

(this is to describe alp7 which is normally cytoplasmic in interphase but is nuclear in mitosis...
 when NES is deleted it is constitutively nuclear with a bit of cytoplasmic , so I don't think any of the other terms work)

descendant of 
FYPO:0001130 | increased protein localization to nucleus during vegetative growth
FYPO:0006099 | decreased protein localization to cytoplasm

**Comment by ValWood** [comment]
decreased localization to interphase microtubules

**Comment by mah11** [comment]
>  increased protein localization to nucleus [with] decreased protein localization to cytoplasm during vegetative growth

What's the difference between this and FYPO:0006100, "decreased protein localization to cytoplasm, with protein mislocalized to nucleus"?

**Comment by ValWood** [comment]
I was thinking that it isn't  really mislocalized to the nucleus because  it is there sometimes (during mitosis)


I suppose it would be OK to say
FYPO:0006100, "decreased protein localization to cytoplasm, with protein mislocalized to nucleus  driong interphase 

though!

**Comment by ValWood** [comment]
One more

decreased proten localization to nucleus dduring meiotic prohase


I didn't see anything under here

FYPO:0004455 | decreased protein localization to nucleus


although I did see some meiotic terms (I think), so there may be a missing parentage

**Comment by mah11** [comment]
decreased protein localization to cytoplasm, with protein mislocalized to nucleus, during mitotic interphase FYPO:0006181
  decreased protein localization to interphase microtubule FYPO:0006182
  abnormal protein localization to nucleus during prophase I FYPO:0006183

edit file: 2509cfe1689c57e1624c40d5d64acbf415e9b8ee
release: 1ebc4bcfcfd36cb90266efae89dced717274b8c9

**Comment by ValWood** [comment]
for this one
abnormal protein localization to nucleus during prophase I FYPO:0006183

I need decreased.

**Comment by mah11** [comment]
decreased protein localization to nucleus during prophase I FYPO:0006185

edit file: 28cc581ae071c1054d46c2e7040230cc73223744
release: e31b67096fa25e5ce9a6c35ddd11a0f0ecd435b7
