### ISSUE TITLE
synonym inviable vegetative cell population

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#3092]
Jurg's group would like the synonym "essential" added to "inviable vegetative cell population"

**Comment by mah11** [comment]
related synonyms added

edit file: 28cc581ae071c1054d46c2e7040230cc73223744
release: e31b67096fa25e5ce9a6c35ddd11a0f0ecd435b7

**Comment by ValWood** [comment]
Still doesn't come up in the list when "essential" typed
 "inviable vegetative cell population"

This is the term we really want people to find. Do the other terms also have "essential" as a synonym?

**Comment by mah11** [comment]
> Still doesn't come up in the list when "essential" typed

This is now a Canto issue; the ontology has what it can and should have for the population terms.

> Do the other terms also have "essential" as a synonym?

All of the 'inviable population' terms do, and most of the 'inviable cell' terms do. I've opened #3133 to fill in the rest. The synonyms have to be RELATED scope because "essential" isn't a phenotype (more explanation way back in #203).

**Comment by ValWood** [comment]
Do we need to have "essential" on the cell  viability phenotypes.

I think if people type essential, they are really looking for inviable population terms?

I think that it what Jurg's group were implying @Antonialock  can you find out?

Is there any reason why 

inviable vegetative cell population= essential (exact)?

**Comment by ValWood** [comment]
> Do the other terms also have "essential" as a synonym?

so this was really me just "wondering"  but I don't think it will be helpful to users to have essential  on all of the "inviable cell/spore" terms because it will obscure what they are really looking for...

**Comment by mah11** [comment]
You requested them in (what is now) https://github.com/pombase/fypo/issues/340#issue-93191666

**Comment by ValWood** [comment]
I probably shouldn't have.

I wasn't really thinking of what users think of when they are searching on "essential"
but over time it has become more obvious that they  don't remember that the term is

"inviable vegetative population", so this should be the term people see  first when they type "essential" into the search...

**Comment by mah11** [comment]
please take further discussion to #3133
