### ISSUE TITLE
long mitotic spindle during anaphase during  anaphase A

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3094]
whoops, missed

long mitotic spindle during anaphase during  anaphase A

descendant of

FYPO:0004438 | long mitotic spindle during anaphase 

PMID:12426374

**Comment by mah11** [comment]
long mitotic spindle during anaphase A FYPO:0006190

edit file: 28cc581ae071c1054d46c2e7040230cc73223744
release: e31b67096fa25e5ce9a6c35ddd11a0f0ecd435b7
