### ISSUE TITLE
PMID:19696784 localization terms (2)

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3095]
missed another

FYPO:0004056 | decreased protein localization to nucleus, with protein mislocalized to cytoplasm

+during mitosis

(because cytoplasmic localization is normal in interphase)

**Comment by mah11** [comment]
decreased protein localization to nucleus, with protein mislocalized to cytoplasm during mitosis FYPO:0006191

edit file: 28cc581ae071c1054d46c2e7040230cc73223744
release: e31b67096fa25e5ce9a6c35ddd11a0f0ecd435b7
