### ISSUE TITLE
ntr: short  misoriented interphase microtubules

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3101]
descendant of 
FYPO:0003328 | misoriented interphase microtubules
-- | --
and the short term

**Comment by ValWood** [comment]
PMID:11432827

**Comment by mah11** [comment]
short misoriented interphase microtubules FYPO:0006196

edit file: 223f7a9792685bcd94375b201375310a0ce2dc24
release: 6e4551640b279c78826137094d3bb3b9247e3cb5
