### ISSUE TITLE
ntr:  decreased RNA level during cellular response to copper ion starvation during spore germination

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3107]
| decreased RNA level during cellular response to copper ion starvation during spore germination

descendant of 
FYPO:0000826 | decreased RNA level | Gel electrophoresis evidence | + copper chelator | during cellular response to copper ion starvation during spore germination

should also group  with other 
decreased RNA level during cellular response to copper ion starvation
like
decreased RNA level during cellular response to copper ion starvation during meiotic cell cycle

would this term position under vegetative? I think cells are classed as vegetative once reach germination?

**Comment by ValWood** [comment]
oh PMID:28572514

**Comment by mah11** [comment]
> decreased RNA level during cellular response to copper ion starvation during meiotic cell cycle

We don't have this term. For 'during meiotic cell cycle' we only have 'during response to copper', i.e. presence of, not starvation.


> would this term position under vegetative?

I have no idea whether the sentiment is universal, but you and Jacky decided years ago (literally) to count everything as vegetative once spore germination even starts.

**Comment by ValWood** [comment]
> I have no idea whether the sentiment is universal, but you and Jacky decided years ago (literally) to count everything as vegetative once spore germination even starts.

Yes that's what my suggestion was based on so let's stick with this. It feels correct.

**Comment by mah11** [comment]
altered RNA level during cellular response to copper ion starvation FYPO:0006208
  decreased RNA level during cellular response to copper ion starvation FYPO:0006209
  decreased RNA level during cellular response to copper ion starvation during spore germination FYPO:0006210

renamed FYPO:0003197 & FYPO:0003280 to make 'vegetative' explicit
fixed an xp

edit file: 63350b41b809b761a79e6ebfdc9b0c5174a246a0
release: f14dd730383b7ee30e38190426437b3a4288f3da
