### ISSUE TITLE
NTR  inviable after spore germination

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3109]
inviable after spore germination before germ tube formation

child of
FYPO:0000316 | inviable after spore germination
-- | --

It's quite nice to add this specificity, because in JAcky's screen we only knew if they were inviable after germination if a germ tube was present.

Here they know the spores have begun to germinated because a release from dormancy can be assayed by a change in refractility, and then a subsequent spore swelling.

PMID:28572514

**Comment by ValWood** [comment]
actually this phenotype is "during copper starvation"

 but I need both during and not

**Comment by ValWood** [comment]
and

decreased spore germination frequency during copper starvation
--

**Comment by mah11** [comment]
inviable after spore germination, before germ tube formation FYPO:0006211
  inviable after spore germination, before germ tube formation, during copper ion starvation FYPO:0006212

(will do the other one from the follow-up comment tomorrow)

edit file: 63350b41b809b761a79e6ebfdc9b0c5174a246a0
release: f14dd730383b7ee30e38190426437b3a4288f3da

**Comment by mah11** [comment]
decreased spore germination frequency during copper ion starvation FYPO:0006214

edit file: c2e8a55f2b92bbd01270836b356bad8012ac4cb4
release: f0e7b733bfe262ef76c33e5ab9f3541926760b49
