### ISSUE TITLE
contractile ring sliding during vegetative growth

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3110]
contractile ring sliding during vegetative growth

def
...contractile ring forms at the medial position, but subsequently slides to an off-centre location?
PMID:28784611

based on comment in feedback form

background

We next addressed how off-center septa arise in efr3Δ. Because septum position is dictated by CR position (Marks and Hyams, 1985; Marks et al., 1986), we reasoned that either the CR forms off-center or it slides from its original medial posi- tion. To distinguish between these possibilities, we imaged WT and efr3Δ expressing CR (Rlc1-GFP) and spindle pole body (Sid4-GFP) markers. In WT, the CR formed in the cell center and maintained this position during cytokinesis (Fig. 2 A). In efr3Δ, the CR formed in the cell center but slid from its orig- inal position while remaining perpendicular to the cell’s long axis (Fig. 2, A–C). 

has_output  misplaced 
mislocalized septum during vegetative growth

I always forget how has_output works...

**Comment by ValWood** [comment]
descendent of 
actomyosin contractile ring displaced from midpoint

**Comment by ValWood** [comment]
maybe 
actomyosin contractile ring displaced from midpoint
means it moves from the midpoint, but that didn't come across to me from def...

**Comment by ValWood** [comment]
also normal GO:1903486

**Comment by mah11** [comment]
In #2551 I added this for PMID:26132084 / 80b382d361649949:

[Term]
id: FYPO:0005289
name: abnormal maintenance of mitotic actomyosin contractile ring localization
def: "A cellular process phenotype observed in the vegetative growth phase of the life cycle in which the maintenance of the mitotic actomyosin contractile ring in the correct location is abnormal." [GO:0032189, GO:1903474, PMID:26132084, PomBase:mah]
synonym: "abnormal cytokinetic ring anchoring involved in mitotic cell cycle" RELATED [GO:1903474]
[loads of other synonyms]
synonym: "actomyosin contractile ring sliding" RELATED [PMID:26132084]
is_a: FYPO:0000033 ! abnormal actomyosin contractile ring localization

Will that still do? It's what I came up with after looking at PMID:26132084, and sounds like it fits the comment in the newer session.

It was a while ago, but it was from one of the times we had a push through the outstanding term requests in Canto sessions. This one actually came from the text they put in one or two of their GO term requests. I emailed to suggest using the FYPO terms I'd added, but didn't hear back (and the session is still "curation in progress".

If abnormal maintenance of ring location only ever manifests itself as ring sliding, I could make that synonym EXACT, which should make it a bit easier to find the term.

**Comment by ValWood** [comment]
Yes I think that is fine. That's the term. I also mailed Pilar & current curator about this session last night because the one I am approving here refers to it.

I think abnormal maintenance always manifests as sliding in FY (at least so far, and I can't think of any other possibility). The other types of abnormal location all involve making the ring in the incorrect place at the onset.

Could
actomyosin contractile ring sliding
be the primary name. It's easer for users to interpret this phenotype (curating, and on the page)

with 
abnormal maintenance of mitotic actomyosin contractile ring localization
exact.

**Comment by ValWood** [comment]
oh, can it also be a descendant of 

FYPO:0002026 | actomyosin contractile ring displaced from midpoint

**Comment by mah11** [comment]
Hmm, can't do is_a because FYPO:0002026 is in the structure-looks-wrong department, not the process-gone-wrong branch. If the sliding always ends up with the ring in the wrong place, I could do FYPO:0005289 (synonym: ring sliding) has_output FYPO:0002026 (displaced ring). Is that true, i.e. the ring never winds up in the right place after it slides around for a while?

**Comment by ValWood** [comment]
no it goes off in one direction or the other if the membrane attachment is compromised because of microtubule pushing forces, but it doesn't 'float around'.

how would that look in canto?
we want them to use the sliding term to  say "we know *how* it ends up in the wrong place' 
 rather than just "the ring is in the incorrect place"
but we want annotations from
FYPO:0005289 (synonym: ring sliding
to propagate to
FYPO:0002026 (displaced ring)

**Comment by mah11** [comment]
So far, I have added the link

    abnormal septum site selection (FYPO:0002154) output_of abnormal actomyosin contractile ring localization (FYPO:0000033)

but I wonder whether we even need FYPO:0002154, or if it could merge into mislocalized septum during vegetative growth (FYPO:0000339)? The merged term wouldn't have any logical-def links to a GO process term itself, but would keep the output_of FYPO:0000033 link.

In any case, more tomorrow ...

**Comment by mah11** [comment]
I've swapped name and synonym for FYPO:0005289, and added the link FYPO:0005289 has_output FYPO:0002026. The link says that if the contractile ring slides, it _always_ ends up mislocalized.

edit file: c2e8a55f2b92bbd01270836b356bad8012ac4cb4
release: f0e7b733bfe262ef76c33e5ab9f3541926760b49

**Comment by ValWood** [comment]
> but I wonder whether we even need FYPO:0002154, or if it could merge into mislocalized septum during vegetative growth (FYPO:0000339)?

yes I think probably so....
The septum site is always based on contractile ring location.

**Comment by mah11** [comment]
3110
merge done

also spotted additional term request in comment above, so:
normal establishment of actomyosin contractile ring localization FYPO:0006216

think that's everything ...

edit file: a16a9a024893b3b63a7b4ebe0d51f1fc415fa21d
release: ff262e82c8f3b9d1f2af188e2d0fb6462ee50e65
