### ISSUE TITLE
ntr increased protein localization to nucleolar periphery

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3114]
synonym increased protein localization to nucleolar/nucleoplasm boundary.

standard def

I don't know where this shpuld be placed, because localization to the nucleolus is normal, its the distribution that appears to be abnormal.

PMID:16251348

The 􏰀CC mutant localized to the nucleolus like the wild type (Figure 2C), whereas 􏰀G1, 􏰀G3, 􏰀G4, 􏰀G5, and 􏰀RG exhib- ited an aggregation of GFP signal at the border of the nu- clear and nucleolar regions (Figure 6, A and B). The evidence is clear from the enlarged images of the nucleus (Figure 6B) showing 􏰀CC (an example of wild-type nucleolar localiza- tion) and 􏰀G5 (a representative of the 􏰀G-domain and 􏰀RG- mutants). The 􏰀CC mutant exhibits GFP fluorescence evenly distributed throughout the nucleolus (area defined by DAPI exclusion), whereas in the 􏰀G5 mutant, the 􏰀G5:GFP fluo- rescence appears to be concentrated in a specific area rather than be evenly distributed (Figure 6B, bottom panel). This area may be consistent with the granular component (GC) region of the nucleolus (Figure 6C).

**Comment by mah11** [comment]
_protein_ localization?

**Comment by ValWood** [comment]
whoops

**Comment by mah11** [comment]
> localization to the nucleolus is normal, [but] the distribution that appears to be abnormal.

at first glance, this looks self-contradictory ...

and the excerpt from the paper seems to be saying there's normal localization in one mutant but more at the periphery in different mutants

anyway, I'll look at the paper when I'm doing FYPO again (soon buut not today)

**Comment by ValWood** [comment]
I'm never sure how this works. I guess localization to the nucleolus is abnormal if the distribution within the nucleus is abnormal.

**Comment by mah11** [comment]
3114
increased protein localization to nucleolar periphery FYPO:0006217

tbh, I think that will do it - in some of the mutants the protein's localization hasn't gone as normal, such that protein is piled up around the border of the nucleolus

edit file: a16a9a024893b3b63a7b4ebe0d51f1fc415fa21d
release: ff262e82c8f3b9d1f2af188e2d0fb6462ee50e65
