### ISSUE TITLE
term merge, multi-nucleate/ septate

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3115]
are these the same?

![diff2](https://user-images.githubusercontent.com/7359272/30431539-c5319bbc-9956-11e7-90d0-7ac0c32724cf.jpg)

logic being, if a cell is 
multiseptate (has 2 or more septa)
AND
the septa are in-between nuclei

then the cell *must* have 3 or more nuclei?

**Comment by mah11** [comment]
well spotted!

**Comment by ValWood** [comment]
My brain seems to work better at 4 a.m.

**Comment by mah11** [comment]
merge done

edit file: a16a9a024893b3b63a7b4ebe0d51f1fc415fa21d
release: ff262e82c8f3b9d1f2af188e2d0fb6462ee50e65
