### ISSUE TITLE
elongated multiseptate vegetative cell not "abnormal cytokinesis"

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3116]
Can all "multiseptate" phenotypes by a type of abnormal cytokinesis. Or is this not allowed to do with has_part?

**Comment by mah11** [comment]
It's not on because no structure phenotype can be a type of (is_a) a process phenotype or vice versa (nothing to do with has_part in this case). I can add multiseptate output_of abnormal cytokinesis.

**Comment by ValWood** [comment]
that should work.

**Comment by mah11** [comment]
added link FYPO:0000118 output_of FYPO:0000032

edit file: a16a9a024893b3b63a7b4ebe0d51f1fc415fa21d
release: ff262e82c8f3b9d1f2af188e2d0fb6462ee50e65
