### ISSUE TITLE
localization phenotype, unsure how to describe...

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3119]
pxl1-delta causes contractile ring sliding.

This phenotype also results in mislocalization of the septum synthases bgs1 and  ags1 showing that  the septum synthesis machinery tracks the contractile ring when it is mislocalized.

How would I say this?
I can't say they are mislocalized to the contractile ring, because that is the normal location?

They are localized to an abnormally localized contractile ring!

**Comment by mah11** [comment]
I don't know if we have a good way to represent this kind of thing. 

We do a sort of half-assed job of capturing dependency anyway (with has_output and output_of) where there's just one "step" from phenotype 1 to dependent phenotype 2, but it's better than nothing. We don't have anything to cover dependency on two or more things at once, but that's what we're looking at in this case - "protein Y in the wrong place relative to the whole cell output_of (normal localization to subcellular structure X + abnormal localization of structure X itself)".

The synthases aren't really part of the contractile ring (as I understand it ... holler if I've got this wrong), so to me it's a bit of a grey area whether we should talk about their localization to the ring, whether it's going normally or not. Anyway, I guess that's a tangent. Even if things that just follow the ring do count as localized to the ring, it would be accurate but uninformative to say "normal localization to ring" for bgs1 and ags1 in this mutant.

Is there a concise description of where ags1 and bgs1 go in the mutant? E.g. could we get away with saying they go to the lateral cell cortex, or that their localization to the medial cortex or division site is abnormal?

**Comment by ValWood** [comment]
Re: This phenotype also results in mislocalization of the septum synthases bgs1 and ags1 showing that the septum synthesis machinery tracks the contractile ring when it is mislocalized.

I probably should probably have said  "tracks the division site"
I could say "mislocalized to lateral medial cortex".... that would work.

**Comment by mah11** [comment]
We have this:
FYPO:0004730 protein mislocalized to lateral cell cortex

I'm a little confused by "lateral medial cortex" ... how would you define that, to make it clearly different from the existing term?

**Comment by ValWood** [comment]
That'll do. IIRC it only moves a little way (still in the middle-ish) but this will do. I might even leave it.

**Comment by mah11** [comment]
I like that answer ;)
