### ISSUE TITLE
abolished protein localization to septum

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3120]
desc of

FYPO:0002719 | decreased protein localization to septum | Microscopy |   | abolished | V.W

PMID:26132084

**Comment by mah11** [comment]
abolished protein localization to septum FYPO:0006220

edit file: a16a9a024893b3b63a7b4ebe0d51f1fc415fa21d
release: ff262e82c8f3b9d1f2af188e2d0fb6462ee50e65
