### ISSUE TITLE
MP incomplete septum

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3121]
is not a descendant of  abnormal septation

**Comment by mah11** [comment]
Not via is_a, for the usual process vs. structure reason. FYPO does have:

- incomplete septum (FYPO:0002870) is_a abnormal septum morphology during vegetative growth (FYPO:0002023)
and
- abnormal septum morphology during vegetative growth (FYPO:0002023) output_of abnormal septation (FYPO:0000117)
