### ISSUE TITLE
NTR: decreased protein localization to division site, with protein mislocalized to cytoplasm

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3122]
standard def

PMID:26132084

**Comment by mah11** [comment]
decreased protein localization to cell division site, with protein mislocalized to cytoplasm FYPO:0006221

edit file: a16a9a024893b3b63a7b4ebe0d51f1fc415fa21d
release: ff262e82c8f3b9d1f2af188e2d0fb6462ee50e65
