### ISSUE TITLE
spurious comment FYPO:0003890

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3123]
![copy paste error](https://user-images.githubusercontent.com/7359272/30514684-ef9c847c-9b11-11e7-877a-1302b62cc495.jpg)

**Comment by mah11** [comment]
oops; deleted

edit file: a16a9a024893b3b63a7b4ebe0d51f1fc415fa21d
release: ff262e82c8f3b9d1f2af188e2d0fb6462ee50e65
