### ISSUE TITLE
ntr condensation terms

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3135]
abolished short range intra arm mitotic chromosome condensation during interphase
abnormal short range intra arm mitotic chromosome condensation during interphase

short range = < ~90 kb (local contacts)

increased intra centromere connection

decreased medium range intra arm mitotic chromosome condensation during mitosis

medium range = ~90 kb - 940 kb

(long range over 940 kb are reduced in WT but there are no mutants  associated with this).

including these distinctions as they seem important, and conserved (the long range is probably a physical constraint and a model is presented to explain likely reason)

Plotting the median contact probability as a function of genomic distance showed fewer intra-arm interactions shorter than 84 kb in mitosis but increased interaction frequencies for distances between 84 and 940 kb (Fig. 3c). Interactions beyond a distance of 940 kb were again depleted in mitosis (the tran- sition points lie around 90 kb and 900 kb, respectively, on all chro- mosome arms). Again, these rearrangements of contact probabilities depended on condensin and Aurora B kinase activity (Fig. 3c and Supplementary Fig. 4). The reduction of megabase-scale contacts is reminiscent of reduced longest-range interactions as human chromo- somes condense11, a probable reflection of chromosome-arm stiffening as mitotic chromosomes gain shape.

![condensin](https://user-images.githubusercontent.com/7359272/31451777-e3d199a6-aea4-11e7-9dff-90677175813a.jpg)

**Comment by ValWood** [comment]
also

increased intra centromere connection during mitosis

--

**Comment by ValWood** [comment]
PMID:28825727
--

**Comment by ValWood** [comment]
SFL tweeted this today

http://www.sciencemag.org/news/2017/10/watch-human-genome-fold-itself-four-dimensions?utm_source=newsfromscience&utm_medium=facebook-text&utm_campaign=genome4d-15687

**Comment by mah11** [comment]
> increased intra-centromere connection during mitosis

Queries about this one:

1. I don't see anything about intra-centromere contacts. Part of Figure 2 shows effects on _inter_-centromere contacts. Is that what you meant?

2. Does the "connection" correspond to centromere clustering (a la GO:0072766)?

**Comment by ValWood** [comment]
Yes sorry inter..... I don't think intra would be physically possible ;)

Hmm good question, I  don't think that anyone has said this explicity yet, but I guess it is. I  will ask Frank....

**Comment by ValWood** [comment]
Prteet sure it is. I remembered that they mentioned Rabl orientation

In addition to the expected richness of local DNA interactions along the three fission yeast chromosomes, seen in dark colors along the diagonal of the interphase contact map, prominent inter-centromeric and inter-telomeric interactions between chromosomes were appar- ent (Fig. 1a, lower left triangle; compare to Supplementary Fig. 3 for an annotated map). This is expected from the Rabl orientation of fission yeast chromosomes in interphase9,12,14

and our def says
 This process is responsible for the Rabl-like configuration of chromosomes in the interphase nuclei.

**Comment by mah11** [comment]
OK. Want me to wait until you hear from Frank, or go ahead and add "increased centromere clustering at nuclear periphery during mitosis" (with a pile of synonyms) now?

**Comment by ValWood** [comment]
no go ahead, I'm pretty certain it is and I will get him to once over my additions just in case.

**Comment by mah11** [comment]
OK. Holler (and reopen) if anything needs changing.

  abnormal short range intra-arm mitotic chromosome condensation during interphase FYPO:0006243
  abolished short range intra-arm mitotic chromosome condensation during interphase FYPO:0006244
  decreased medium range intra-arm mitotic chromosome condensation during interphase FYPO:0006245
  increased centromere clustering at nuclear periphery during mitosis FYPO:0006248

edit file: ec6ee5d677c42929881ef935adc2ab1ad48df539
release: 249295b57e3596192be096423c4b29fd442a9882
