### ISSUE TITLE
ntr PMID: 28945192

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3138]
increased short ribosome footprints upon UPR induction
I have no idea if I can do this, or how to define it!

Basically if you knock out   dom34 and ski2
implicated in ribosome rescue and mRNA no-go-decay (NGD).

you get short footprints in a ribosome profiling experiment...

how would we do this?

**Comment by mah11** [comment]
I think we could do this as "abnormal ribosome footprint size distribution", and if the additional specificity is worth capturing, I could put the bits about "increased level of short footprints" and "during UPR" in a child.

If we include the more specific term, should I refer to GO:0030968 for the "during UPR" part (tho I don't think I can do xps for either the general or specific term)?

**Comment by ValWood** [comment]
Sounds good. I think we will capture the additional specificity because they  go to a lot of effort to demonstrate the different sizes, and why they think they are so.....

**Comment by mah11** [comment]
abnormal ribosome footprint size distribution FYPO:0006254
  increased level of short ribosome footprints during endoplasmic reticulum unfolded protein response FYPO:0006255

edit file: 940e4f1fa6e57fb20827e9f138daab9844811dfb
release: e1793b5c1b70775665337bfa8900d7d6df6a4c67
