### ISSUE TITLE
ntr: abolished FYPO:0005528  + histone methylation PMID:26804021

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3143]
PMID:26804021

Here we found that the subnuclear localization of Sgo2–green
fluorescent protein (GFP) always overlapped with the knobs
(Fig. 4a), and that the knobs were completely lost in sgo2D cells
(Fig. 4b,c).

**Comment by ValWood** [comment]
and increased histine H3-K36 tri-methylation H3K36me3

**Comment by mah11** [comment]
do you mean "abolished subtelomeric chromatin knob formation"?

"abolished decreased subtelomeric chromatin knob formation" would make no sense, but that's what the ticket title asks for ;)

**Comment by ValWood** [comment]
One of these exists already, so this is the other one :)

**Comment by mah11** [comment]
my point is that you implicitly asked for a term with the nonsense name "abolished decreased subtelomeric chromatin knob formation"

**Comment by ValWood** [comment]
"abolished subtelomeric chromatin knob formation
or 
"decreased subtelomeric chromatin knob formation

(I think decreased exists, if so it was abolished)

**Comment by mah11** [comment]
abolished subtelomeric chromatin knob formation FYPO:0006260
  abolished histone H3-K36 trimethylation during vegetative growth FYPO:0006261

edit file: 940e4f1fa6e57fb20827e9f138daab9844811dfb
release: e1793b5c1b70775665337bfa8900d7d6df6a4c67

**Comment by ValWood** [comment]
wanted 
increased histone H3-K36 trimethylation during vegetative growth FYPO:0006261

;)

**Comment by mah11** [comment]
oh, so the title doesn't parse "abolished ( FYPO:0005528 + histone methylation )"?
;)

**Comment by ValWood** [comment]
oops.

**Comment by mah11** [comment]
no worries, my "oops" too for only looking at the title

might get to it today but won't promise right now ...

**Comment by mah11** [comment]
increased histone H3-K36 trimethylation during vegetative growth FYPO:0006263

edit file: 2011bfe344cf4469ff367678286868a97ecad1a5
release: e0803a1a324831c9be326794ec4c7fc8f797804c
