### ISSUE TITLE
synonym dispersed actin cortical patch localization ?

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3144]
The phenotype caused by ectopic activation of the SIN is very similar to that observed in MOR pathway loss of function mu- tants, which arrest with depolarized actin

can depolarized actin patch
be a synonym of 

FYPO:0002021 | dispersed actin cortical patch localization

?

**Comment by mah11** [comment]
added synonym: "depolarized actin cortical patch localization"
(included "localization" to avoid suggesting that the term refers to how actin is organized within the patch)

edit file: 940e4f1fa6e57fb20827e9f138daab9844811dfb
release: e1793b5c1b70775665337bfa8900d7d6df6a4c67
