### ISSUE TITLE
telomere clustering related

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3146]
1.
term name:
increased sister chromatid telomere non-disjunction at anaphase B
synonym: increased taz1 foci at anaphase B
synonym:
def:
the failure of sister chromatids to separate at anaphase B  because  the telomeres of sister chromatids are still attached
PMID:25778919

2. 

increased 
GONEW:  mitotic  telomere tethering at nuclear periphery
during mitotic metaphase

synonym
decreased mitotic telomere dispersion during metaphase

-- | --

**Comment by ValWood** [comment]
3.

unequal nucleolus inheritance
--

add synonyms
unequal rDNA segregation ?

**Comment by mah11** [comment]
> 2. increased
> GONEW: mitotic telomere tethering at nuclear periphery
> during mitotic metaphase

I'm a little tiny bit confused about this one. The latest thing on the GO ticket (https://github.com/geneontology/go-ontology/issues/14409) says to keep GO:0044820 'mitotic telomere tethering at nuclear periphery' as is, and the GO:new term should be 'mitotic telomere clustering at nuclear periphery'.

Which should FYPO:new2 point to?

**Comment by mah11** [comment]
Did new1 as
decreased telomeric DNA separation during anaphase B FYPO:0006264
with a slew of synonyms

For 3, the synonym has "related" scope because nucleolar proteins also appear to segregate (I found PMID:1661641 ...)

above two in
edit file: 2011bfe344cf4469ff367678286868a97ecad1a5
release: e0803a1a324831c9be326794ec4c7fc8f797804c

**Comment by ValWood** [comment]
For 2 i need the eventual parent

GO:new mitotic telomere clustering at the mitotic nuclear envelope

so not the tethering term as originally stated.

**Comment by mah11** [comment]
OK, thanks. I can add that next time I'm editing, and go back and fill in a logical def whenever the GO edits get done.

**Comment by mah11** [comment]
OK, I've put this in but right now it's got fairly generic parents (FYPO:0001337 and FYPO:0001362). I can move it if you know what would be better, or we can wait for GO to add the BP term and I'll use that as a guide.

 increased telomere clustering at nuclear periphery during mitotic metaphase FYPO:0006267

edit file: d7d8f7a01f37575f82a9cf2a84742841d0172598
release: 02e684c4935884929353728e299d890329b04901

**Comment by mah11** [comment]
now has xp

turns out we don't (yet) have an intermediate-level term to change parentage. open a new ticket if you need any other terms.
