### ISSUE TITLE
kinetochore morphology questions

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3149]
how is
FYPO:0005633 - abnormal chromosome segregation during meiosis I with split kinetochore and normal chromosome separation
https://www.pombase.org/term/FYPO:0005633
related to "abnormal kinetochore morphology"?

**Comment by ValWood** [comment]
actually, I see it here
https://www.pombase.org/term/FYPO:0005646
but I can't navigate to it...

**Comment by mah11** [comment]
This is its ancestry:
![fypo_5633](https://user-images.githubusercontent.com/5196259/32173932-645ba9d6-bd78-11e7-8688-91c390156dc8.png)

Not sure what you mean by "can't navigate to it" ... I can navigate from FYPO:0005646 to FYPO:0005633 Canto, and we don't really have anything else that navigates among FYPO terms yet ...

**Comment by ValWood** [comment]
I can't get to
FYPO:0005646
from here
https://www.pombase.org/term/FYPO:0005633

?

**Comment by mah11** [comment]
OK, that will require a change in what goes in the "Parents" list on the FYPO term pages.

**Comment by mah11** [comment]
see https://github.com/pombase/website/issues/326

**Comment by ValWood** [comment]
yep wanted to check...plan to look at that ticket this week.....
