### ISSUE TITLE
decreased level of UDP-glucose in the endoplasmic reticulum lumen

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3152]
~decreased level of UDP-glucose in the endoplasmic reticulum lumen~
PMID:27587357

standard def

**Comment by ValWood** [comment]
decreased cell wall galactomannan

**Comment by mah11** [comment]
why the strikethrough?

**Comment by ValWood** [comment]
I changed my mind, but I think that might be what fig 6 etc is showing?

**Comment by mah11** [comment]
Hmm. Not straightforward, is it? It's a pretty indirect way of seeing whether UDP-glucose gets into the ER lumen, and they come out and say it's not quantitative ("It is worth mentioning that the assay is able to detect the presence of UDP-Glc in the ER lumen but not its concentration or entrance rate."), but it does seem qualitatively accurate given the setup.

Maybe you could use FYPO:0003290 "abnormal glycoprotein glycan structure", or we could add a more specific descendant?


also, re 

> decreased cell wall galactomannan

We have FYPO:0002265 "decreased cell wall galactomannan level", but the data in fig 1 seem like they might be more about composition or structure than overall quantity?

**Comment by ValWood** [comment]
Yeah I wanted to keep as close as poss because the author requested...

So do you think
abnormal glycoprotein glycan structure in the ER lumen?

**Comment by mah11** [comment]
OK, this with synonyms:

  abnormal glycoprotein glycan structure in endoplasmic reticulum lumen FYPO:0006273

edit file: d7d8f7a01f37575f82a9cf2a84742841d0172598
release: 02e684c4935884929353728e299d890329b04901
