### ISSUE TITLE
add synonym to decreased protein localization to kinetochore during mitotic spindle assembly checkpoint signaling

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3153]
decreased protein localization to kinetochore during mitotic spindle assembly checkpoint signaling

add synonym exact to
defective protein recruitment to unattached kinetochores

**Comment by mah11** [comment]
done

edit file: d7d8f7a01f37575f82a9cf2a84742841d0172598
release: 02e684c4935884929353728e299d890329b04901

**Comment by mah11** [comment]
done

edit file: d7d8f7a01f37575f82a9cf2a84742841d0172598
release: 02e684c4935884929353728e299d890329b04901
