### ISSUE TITLE
ntr: abolished transport of cytosolic proteins to the vacuole via the NVT pathway

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3155]
https://github.com/geneontology/go-ontology/issues/14453

new FYPO term
abolished transport of cytosolic proteins to the vacuole via the NVT pathway

PMID:26365378

**Comment by mah11** [comment]
Given the def you recommended for the GO term in https://github.com/geneontology/go-ontology/issues/14453, "transport of cytosolic proteins to the vacuole" is redundant with "via the NVT pathway". I can put in verbose synonyms, but I would like to use a non-redundant term name, "abolished protein transport via NVT pathway". OK?

**Comment by ValWood** [comment]
I think so...

**Comment by mah11** [comment]
thanks. included synonyms

  abolished protein transport via NVT pathway FYPO:0006274

edit file: d7d8f7a01f37575f82a9cf2a84742841d0172598
release: 02e684c4935884929353728e299d890329b04901
