### ISSUE TITLE
ntr  increased pyknosis

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3157]
wikepedia
Pyknosis, or karyopyknosis, is the irreversible condensation of chromatin in the nucleus of a cell undergoing necrosis or apoptosis.

PMID:18653539
Progressive pyknosis and karyorhexis in TAG-deficient mutants in rich medium
To better understand the cell-death process in TAG-deficient mutants, we sought simple yet reliable markers with which to monitor cell death. To this end, we observed progressive pyknosis (condensation of chromatin),.......
This was accompanied by chromatin condensation in the vast majority of the population, with some cells also showing nuclear- envelope breakdown (Fig. 1D). The chromatin condensation that was detected in DKO cells was readily distinguishable from that of the metaphasic chromosomes by its higher intensity and multi- focal nature (Fig. 1H), which is probably similar to that observed in another case, in which it is referred to as hypercondensation (Demeter et al., 1995).

**Comment by ValWood** [comment]
Should probably add 
"during stationary phase"

**Comment by ValWood** [comment]
would be described as some sort of "apoptotic process"?

**Comment by ValWood** [comment]
also Karyorhexis during stationary phase
Karyorrhexis (from Greek κάρυον karyon, "kernel, seed or nucleus", and ῥῆξις rhexis, "bursting") is the destructive fragmentation of the nucleus of a dying cell whereby its chromatin is distributed irregularly throughout the cytoplasm.


Upon reaching early stationary phase (6􏰀107-8􏰀107 cells/ml), extensive chromatin condensation and fragmentation ensued with the concomitant breakdown of the nuclear envelope into membrane- enclosed compartments (Fig. 1E). Advanced breakdown and rupture of the nuclear envelope and dispersion of the hypercondensed chromatin into the cytoplasm were generally observed when DKO cells had reached the saturation density (8􏰀107-10􏰀107 cells/ml, compare to the wild-type saturation density of >12􏰀107 cells/ml) for 24 hours or more (Fig. 1F). The nucleus of the wild-type cells remained intact throughout the above time frame (Fig. 1G).

**Comment by mah11** [comment]
increased pyknosis during stationary phase FYPO:0006275
  increased karyorrhexis during stationary phase FYPO:0006276

edit file: 28e285e0e8631e06b6fcd3fc5bf7e23e770e0862
release: 6bcbf3d5135c0ce57ad9c75473590874a12a25e7
