### ISSUE TITLE
decreased kinetochore stretching

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3158]
Requested by Meredith.
I have a bit of correspondence, which I will forward...

Basically the kinetochores are "stretched" when they are under tension.

Some mutants have reduced stretch which Meredith wants to capture.

**Comment by mah11** [comment]
The forwarded email from Meredith contains this:

"Kinetochore stretch usually describes the distance between sister kinetochores of duplicated chromosomes that are bioriented on the spindle during mitosis."

... which makes it sound like the appropriate term would be FYPO:0006047, decreased interkinetochore distance before mitotic anaphase. (There's also increased, FYPO:0002639.)

So maybe the "stretch(ed)" synonym(s) should be on those terms instead?

There may be other things that we haven't got quite right. Elongated kinetochore (FYPO:0002649) and split kinetochore (FYPO:0002650, FYPO:0005647, FYPO:0005648) are each defined as applying to a single kinetochore (or what would be a single kinetochore if it weren't split). Do we need to review that too?

**Comment by ValWood** [comment]
Meredith's is
https://www.ncbi.nlm.nih.gov/pubmed/27146110
for the klp6 mutant.

I'm going to check some of the elongated. I feel I have used this post anaphase.

**Comment by ValWood** [comment]
Sometimes, merotelically attached kinetochores
are extensively stretched, creating two domains
that appear as separate spots. Importantly,
kinetochore stretching of this nature never occurs in
normally oriented (amphitelic) kinetochores and it is
therefore characteristic of merotelically attached kinetochores
[7]. Despite their small size, merotelically attached
chromatids might possess similar properties in
S. pombe. To test this, cycling cells lacking either
Pcs1, Mde4, or Clr4 were fixed and processed for immunofluorescence
with antibodies against the centromerespecific
histone H3 variant CENP-ACnp1, which forms the
chromatin platform upon which the rest of the kinetochore
is assembled (Figure 4). Fission yeast kinetochores
normally possess a round, dot-like appearance
(Figure 4A). In contrast, the kinetochores of lagging
chromosomes in the mutants displayed a variety of
CENP-ACnp1 staining patterns. Many lagging kinetochores
had a dot-like morphology that appeared indistinguishable
from normal kinetochores, as shown in
the example in Figure 4B. However, other lagging kinetochores
possessed a CENP-ACnp1 signal that was
stretched in the plane of the spindle, examples of which
are shown in Figures 4C–4J. These were classified as
having an elongated morphology, a bilobed shape, or
a kinetochore signal split in two. Stretched (including
elongated, bilobed, and split) CENP-ACnp1 signals were
observed for 25%–32% of lagging kinetochores in
pcs1D, mde4D, and clr4D mutants (Table S1). Very similar
images of stretched kinetochores were also observed
when the mutants were stained for tagged versions
of various other kinetochore proteins such as
CENP-CCnp3, Mis12, Nuf2, and Sim4 (data not shown,
and below). The diameter of kinetochores (CENPACnp1-staining
dots) in early mitosis in wild-type cells
was 0.41 6 0.03 mm (Table S2). Dot-shaped lagging kinetochores
had similar dimensions to normal kinetochores,
whereas stretched kinetochores were elongated
in the plane of the spindle approximately 2-fold
on average (w0.8 mm) but maintained a normal width
(Table S2).

**Comment by ValWood** [comment]
Meredith can use FYPO:0006047

So now are the other "Stretched" the same or different?

**Comment by mah11** [comment]
That's exactly my question. The text you pasted above sounds like it's describing a single kinetochore, not a pair of kinetochores on sister chromatids. But I also got the impression that Meredith would use "stretched" to refer to the pair of sister kinetochores.

So should we make "stretched" a related synonym for both elongated (single) kinetochore and increased interkinetochore distance? Or am I not understanding something correctly (entirely possible!)?

**Comment by ValWood** [comment]
OK, Meredith says:

I think they're different - like the other comment (I think fro Midori) said, the abstract you showed seemed to be discussing stretch of a single kinetochore due to merotelic attachments, whicvh is different than the degree of stretch between sisters.

so we just need to distinguish better and add "stretched" to both as related?

**Comment by mah11** [comment]
OK, that sounds pretty straightforward. Is there any specific text to add to the defs or comments that would help? (If you don't have anything I'll wing it.)

**Comment by ValWood** [comment]
I think you can wing it ;)

**Comment by mah11** [comment]
OK, synonyms rejigged and comments added

edit file: 28e285e0e8631e06b6fcd3fc5bf7e23e770e0862
release: 6bcbf3d5135c0ce57ad9c75473590874a12a25e7
