### ISSUE TITLE
increased sensitivity to flouride

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3161]
Just realised I did not request yet. Required  for  workshop paper!

**Comment by mah11** [comment]
The experiments use NaF as the fluoride source, so they can annotate to FYPO:0003369 sensitive to sodium fluoride.

I've also just added BROAD synonyms that don't include "sodium" to FYPO:0003368 and FYPO:0003369, but the terms should show up anyway if the students search for "fluoride" (without the typo ;) ) even if the new synonyms don't reach Canto by tomorrow.
