### ISSUE TITLE
ntr increased duration of protein localization to telomere during anaphase B

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3163]
FYPO:0005649 | increased duration of protein localization to telomere
-- | --

+ during anaphase B

**Comment by ValWood** [comment]
and
abolished
telomeric DNA separation during anaphase B
standard def

both
PMID:25778919

**Comment by mah11** [comment]
increased duration of protein localization to telomere during mitotic anaphase B FYPO:0006285

edit file: 2d923e38871c32d7b817d0f5982ca825f8bd21fa
release: 40965462a454594dfe2df7e92f240b36ee5c320b
