### ISSUE TITLE
decreased protein level during G2

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3166]
decreased protein level during G2
Situation were the level of a protein or proteins is reduced during the G2 phase of the mitotic cell cycle

(that will be mitotic)

For
PMID:17531813

**Comment by mah11** [comment]
decreased protein level during mitotic G2 phase FYPO:0006288

edit file: 2d923e38871c32d7b817d0f5982ca825f8bd21fa
release: 40965462a454594dfe2df7e92f240b36ee5c320b
