### ISSUE TITLE
small tweak to transition term comments

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3171]
Use this term for any experiments that detect early mitosis by any criteria. If you have measured CDK activity, also consider using 'premature mitotic G2/M transition' (FYPO:0002516). Also consider annotating to 'viable small vegetative cell' (FYPO:0000648), if mitosis takes place when cells are smaller than normal.

Please add
If you have measured CDK activity, or calculated the transition point,

to all of these terms.

**Comment by mah11** [comment]
No objection, but a question out of curiosity: I have no idea how one would calculate a transition point. What does that mean, and how is it done?

**Comment by ValWood** [comment]
Jacky has the textual def, @JackyVH  could you paste it here.

Basically it is a calculation of where the the function of a gene product has completed, based on how many cells  (percentage) proceed past that point after a   temperature shift for  a conditional mutant or a HU block. 
So  G1/S transiton point is calculated at ~0.29  and G2/M at about  0.68. You only see it in really old papers but  I believe somebody got a nobel prize for these experiments at some point.

**Comment by mah11** [comment]
done

edit file: 302ad9cfdf2c2d65a3ec486110edfd59cecfe065
release: 966f85e4e59fda02f2c636506d15dc1cfe5bc7df
