### ISSUE TITLE
checkpoint override

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3174]
(*) Checkpoint over-ride the same as “checkpoint bypass” and this occurs when a checkpoint target is constitutively activated in some way (i.e for the spindle checkpoint if you inhibited securin to active separase, the spindle checkpoint target, or for the DNA checkpoint if you constitutively activated cdc2 or inactivated wee1). I thought it was something else so we might need to check where we used this

mitotic spindle assembly checkpoint override
A cellular process phenotype in which a mitotic cell cycle arrest that normally occurs in response to mitotic cell cycle spindle assembly checkpoint signaling does not occur. As a result, the septation initiation network (SIN) signaling pathway is activated despite activation of the mitotic spindle assembly checkpoint (SAC). Normally, under conditions that activate the SAC, SIN activation is inhibited and the cell cycle arrests in anaphase. In this phenotype, premature SIN activation leads to premature cytokinesis and the formation of cut cells.

Is this correct. Even if it is correct, I think i misused it.

**Comment by ValWood** [comment]
actually, this seems fine. I'll check my annotations....they look odd

**Comment by mah11** [comment]
We crafted that definition very thoroughly in #2133

**Comment by ValWood** [comment]
Yes I meant to put this on the curation tracker, I think. I'm sure my annotations are wrong.
