### ISSUE TITLE
obsoletion and new terms

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3180]
After discussion with the authors, please obsolete

decreased medium range intra-arm mitotic chromosome condensation during interphase
abolished short range intra-arm mitotic chromosome condensation during interphase
abnormal short range intra-arm mitotic chromosome condensation during interphase

and add instead
"abolished changes in intra-arm contacts in mitosis"

I got that  quite a bit wrong....

v

**Comment by mah11** [comment]
done; new term is
  abolished intra-arm chromosome contact change during mitosis FYPO:0006302

edit file: 40514f97a66e3d948ce2d1d11ef8cd489f770139
release: c52c22229cee8f17ff29fdee4d75f5bfa711e0ef
