### ISSUE TITLE
NTR meiosis II spindle overextension PMID:29259000

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3185]
A phenotype observed in meiosis II anaphase  where the  two elongating spindles  meet in the centre of the cell 

fig 5

**Comment by mah11** [comment]
Is this really different from FYPO:0002222 long meiosis II spindle? If so, how? If not, I'll add a synonym.

**Comment by ValWood** [comment]
I think you are right, I  don't think it is different....

says "Live cell imaging of dms1 cells carrying LacI-GFP labels on the arm of both copies of chromosome II and mCherry-tagged tubulin revealed an unprecedented phenotype
443 (Figure 5A)."

but it seems the same to me

![spo](https://user-images.githubusercontent.com/7359272/34558049-62063c56-f134-11e7-9653-1db2103d1970.jpg)

if you add a synonym, the paper is now with the authors to prepare the HTP spreadsheet. I can check later if there is really a difference.

**Comment by mah11** [comment]
OK, synonym added. We can revisit if anything ever emerges to make a distinction.

edit file: bdb395c301451f1ddf590328479724874effa9c5
release: f15e9dc76ba8ae6cf3bc59636747ca5cfd56bab5
