### ISSUE TITLE
PMID:29259000 NTRs

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3186]
1. abolished entry into meiosis  (or arrest in meiotic prophase?)

2. abolished asci formation

3. abnormal homologous chromosome segregation
child of FYPO:0004159

4. spindle pole bodies present in increased numbers during meiosis II
child of FYPO:0004609

5. decreased protein localization to meiotic spindle pole body  during meiosis II
child of FYPO:0002772

**Comment by ValWood** [comment]
1. abolished entry into meiosis
2. abolished

**Comment by mah11** [comment]
> abolished entry into meiosis

In the end I did this as "abolished meiotic G2/MI transition" with "abolished entry into meiosis" as a related synonym, because GO has "entry into meiosis" as a narrow synonym for GO:0051728 cell cycle switching, mitotic to meiotic cell cycle, and I don't think that's what we want here.

**Comment by mah11** [comment]
abolished meiotic G2/MI transition FYPO:0006313
  abolished ascus formation FYPO:0006314
  abolished homologous chromosome segregation FYPO:0006315
  spindle pole bodies present in increased numbers during meiosis II FYPO:0006316
  decreased protein localization to meiotic spindle pole body during meiosis II FYPO:0006317

edit file: bdb395c301451f1ddf590328479724874effa9c5
release: f15e9dc76ba8ae6cf3bc59636747ca5cfd56bab5
