### ISSUE TITLE
FYPO:0004075	decreased cell growth

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3191]
I'm in the process of changing lots of

FYPO:0004075 | decreased cell growth
to

FYPO:0001355 | decreased vegetative cell population growth
-- | --

This is quite common, there is a comment, where the difference is clear  but could it be clearer in the def?

**Comment by mah11** [comment]
What specific change(s) do you recommend? It already has "Cell growth is the irreversible increase in size over time  ..." in the def. And FYPO:0004075 hasn't been used "a lot" compared to FYPO:0001355 (14 annotations live, vs. lots).

**Comment by ValWood** [comment]
Sorry that wasn't clear. I know we don't use i much, but quite often community curators use it instead of the population term and we have to fix them...

FYPO:0004075 | decreased cell growth
A cellular process phenotype in which cell growth is decreased. Cell growth is the irreversible increase in size over time by accretion and biosynthetic production of matter similar to that already present.

maybe simply something like
A cellular process phenotype in which growth  of an individual cell is decreased.

Maybe a better solution  is to see if we can change the "weighting" of the population terms so they appear first (since they are usually what people need when annotating phenotypes).

**Comment by mah11** [comment]
I can't shake the sense that there is no definition wording that will avoid confusion for everyone ...

**Comment by ValWood** [comment]
OK...I think bumping it up the suggestions  for "growth" searches will work better...I'll have another think if it keep happening...
