### ISSUE TITLE
NTR: decreased protein level  in spliceosome 

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3193]
decreased protein level  in spliceosome 

FYPO:0001324 | decreased protein level during vegetative growth | 

in spliceosome | Fig 8B

PMID:28947618

**Comment by mah11** [comment]
decreased protein level in spliceosomal complex FYPO:0006328

(used 'spliceosomal complex' to match GO)

edit file: 88754fcc0045754144edba70a6f3e482b233085a
release: a22686436a26a26c7b6c4e2ded6f4b4fc7dc41d4
