### ISSUE TITLE
NTR: abnormal ER-PM contact formation PMID:29290560

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3194]
synonym : ER-PM contact removal
synonym : ER-PM uncoupling 

the removal of  the endoplasmic reticulum-plasma membrane tethering along  the lateral cortex

![er-pm](https://user-images.githubusercontent.com/7359272/34842310-0a05a378-f703-11e7-96c3-232c4f0b9f27.jpg)

child of

FYPO:0002872 abnormal endoplasmic reticulum localization

note FYPO:0002872 is not a descendant of
FYPO:0000805 | abnormal endoplasmic reticulum organization

PMID:29290560

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/14866

**Comment by mah11** [comment]
Would it be better to model this as abnormal or decreased 'endoplasmic reticulum-plasma membrane tethering' (xp GO:0061817)? 

The proposed name, synonyms, and text def don't quite match each other. The term name says that a contact formation process (CC assembly) goes wrong, whereas the def and synonyms say that existing contact sites - which may have formed by a normal assembly process - get removed under circumstances where they stay put in wild type. Is it clear which is really going on?

To do it as abnormal/increased/decreased contact site formation/removal, I would like to have GO BP terms in the CC-organization branch to point to, which I don't think have been requested. The linked GO ticket doesn't say anything about forming or undoing membrane contacts. https://github.com/geneontology/go-ontology/issues/14861 requests a CC term for the contact site, but doesn't mention any BP terms for their organization/assembly/disassembly/etc.

I only skimmed the paper very quickly, so I don't know how much molecular detail is known about any contact site organization processes (assembly, disassembly, regulation thereof). It does look like it's sometimes normal for contacts to be removed, so "contact removal" and "uncoupling" can't be exact synonyms for a FYPO term describing an abnormal occurrence of it.

**Comment by mah11** [comment]
abnormal organelle localization FYPO:0006329
  decreased endoplasmic reticulum-plasma membrane tethering FYPO:0006330

edit file: a6fe321f489ec8d714a052a38e5635021c342359
release: 57a4c6d5dbbeaf3935f3e1426a0588c29751a947
