### ISSUE TITLE
MP decreased protein localization to kinetochore during mitotic spindle assembly checkpoint signaling

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3195]
I think

decreased protein localization to kinetochore during mitotic spindle assembly checkpoint signaling

can be a descendant of
decreased protein localization to kinetochore during mitosis

because the checkpoint is only active in mitosis?

**Comment by mah11** [comment]
OK, added link FYPO:0005300 is_a FYPO:0005215

edit file: a6fe321f489ec8d714a052a38e5635021c342359
release: 57a4c6d5dbbeaf3935f3e1426a0588c29751a947
