### ISSUE TITLE
add synonyms for chronological lifespan?

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3196]
loss of viability in stationary phase == decreased chronological lifespan

and increased

**Comment by mah11** [comment]
synonyms added (related because an individual cell has a chronological lifespan, whereas stationary phase is exclusively a population phenomenon)

edit file: a6fe321f489ec8d714a052a38e5635021c342359
release: 57a4c6d5dbbeaf3935f3e1426a0588c29751a947
