### ISSUE TITLE
NTR decreased microtubule nucleation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3201]
decreased microtubule nucleation
decreased mitotic microtubule nucleation

(and mitotic)

standard defs (we have interphase)

PMID:8834801

**Comment by ValWood** [comment]
actually also

decreased interphase microtubule nucleation from SPB

**Comment by mah11** [comment]
decreased microtubule nucleation FYPO:0006335
decreased mitotic microtubule nucleation FYPO:0006336
decreased interphase microtubule nucleation from spindle pole body FYPO:0006337

I did FYPO:0006336 as decreased GO:0051418 happens_during mitosis. Let me know if there's a more specific GO term that would work better.

edit file: a6fe321f489ec8d714a052a38e5635021c342359
release: 57a4c6d5dbbeaf3935f3e1426a0588c29751a947

**Comment by ValWood** [comment]
FYPO:0006337 | decreased interphase microtubule nucleation from spindle pole body

is not a child of

FYPO:0005694 | decreased interphase microtubule nucleation
-- | --

**Comment by mah11** [comment]
Oh yeah, no logical def so have to do these manually. Done (yesterday, but I forgot to re-close the ticket).

edit file: fc305b5149cf32f1f61ed025e9a44fda9e7ded0e
release: e18933087b9fdf5391d011847569e14f5a258b2e
