### ISSUE TITLE
NTR: nucleus mislocalized towards cell tip during mitotic telophase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3202]
descendant of 

FYPO:0002071 | mislocalized nucleus during vegetative growth
-- | --

binucleated cells in which the DNA remains at the cell tips (after cytokinesis)

(In a normal cell cycle after mitosis, the two nuclei move to the tips of the cells and then relocalize to what will be the middle of each daughter cell after cytokinesis)

**Comment by ValWood** [comment]
PMID:15937127

**Comment by ValWood** [comment]
NTR mononucleate vegetative cell with asymetrically localized nucleus

fig3

**Comment by mah11** [comment]
nucleus mislocalized towards cell tip during mitotic telophase FYPO:0006338
  mononucleate vegetative cell with mislocalized nucleus FYPO:0006339

edit file: a6fe321f489ec8d714a052a38e5635021c342359
release: 57a4c6d5dbbeaf3935f3e1426a0588c29751a947
