### ISSUE TITLE
NTR endocytosis related

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3203]
1
endocytosis restricted to old cell end

2
endocytosis restricted to cell end/ abolished equatorial endocytosis /abolished endocytosis to cell division site

--

PMID:16141239

**Comment by mah11** [comment]
endocytosis restricted to old cell end FYPO:0006340
  abolished equatorial endocytosis during mitosis FYPO:0006341

edit file: a6fe321f489ec8d714a052a38e5635021c342359
release: 57a4c6d5dbbeaf3935f3e1426a0588c29751a947
