### ISSUE TITLE
NTR: abnormal mitotic spindle localization

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3204]
standard def

"spindles are often unevenly distributed in the cell."  fig 5 B (apparently)
PMID:11967147

**Comment by mah11** [comment]
> I would like a term for when the pausing at anaphase A is abolished.

Can you pin down how that term would differ from the existing term (FYPO:0006171)?

**Comment by mah11** [comment]
Since there are only a few still images, I think FYPO:0003969 "mislocalized mitotic spindle" would do for the first term.

**Comment by ValWood** [comment]
What's FYPO:0006171
(I thought there was a term to describe this phenotype as I came across it before. If it is the term I was thinking of I'll work out why I didn't find it)

**Comment by ValWood** [comment]
>
Since there are only a few still images, I think FYPO:0003969 "mislocalized mitotic spindle" would do for the first term.
 
agreed...

**Comment by mah11** [comment]
id: FYPO:0006171
name: mitotic spindle elongation during anaphase A
def: "A cellular process phenotype observed in the vegetative growth phase of the life cycle in which mitotic spindle elongation takes place during anaphase A. Normally, the spindle elongates immediately following assembly during prophase, remains at a static length during metaphase and anaphase A, and elongates further during anaphase B." [PMID:21920317, PMID:9802907, PomBase:mah]
is_a: FYPO:0005417 ! premature mitotic spindle elongation

added for #2647

**Comment by ValWood** [comment]
Yes that's it! Thanks!

**Comment by mah11** [comment]
looks like we can close this :)
