### ISSUE TITLE
NTRs microtubules

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3205]
PMID:19430466

decreased microtubule binding

abolished microtubule bundle formation
child of 
abnormal microtubule bundle formation

**Comment by mah11** [comment]
decreased microtubule binding FYPO:0006342
  abolished microtubule bundle formation FYPO:0006343

edit file: 333e78c7701a909ba0aad492aa9fd3502f16d909
release: e9b244b1696e76b5f3458fde0cae2e4e74facdfa
