### ISSUE TITLE
NTR:abnormal cell cycle arrest in mitotic anaphase with condensed chromosome

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3206]
"Taken together, our data indicated that Mia1p-over- expressing cells were predominantly arrested in anaphase, with fully extended spindles and nonsegregated chromosomes."

So
can I have

abnormal cell cycle arrest in mitotic anaphase with condensed chromosome

(this seems odd logically since condensed chromosomes are a marker for metaphase, but the APC is activated, cohesin is cleaved and the spindle is elongated, so this is a anaphase arrest with condensed chromosomes)

child of

FYPO:0000619
FYPO:0003738

PMID:17579515

**Comment by mah11** [comment]
Ah, I thought chromosome decondensation happens in telophase .... is that out of date, or bigger-eukaryotes-only ... or was I right, and arrest in anaphase implies condensed chromosomes anyway?

**Comment by ValWood** [comment]
Yes I think that is correct. 

 Ignore me. I was thinking that condensed chromosomes  are usually a sign of  metaphase, but obviously they are still condensed in anaphase. Actually I'm not sure what I was thinking....

**Comment by mah11** [comment]
I added a synonym to the anaphase arrest term for future confusion avoidance

edit file: 333e78c7701a909ba0aad492aa9fd3502f16d909
release: e9b244b1696e76b5f3458fde0cae2e4e74facdfa
