### ISSUE TITLE
NTR: thin bipolar mitotic spindle

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3208]
PMID:12951601

child of

FYPO:0001574 | abnormal bipolar mitotic spindle

(we already have thin mitotic spindle midzone, but this is thin and dicontinuous)

fig 1a thinner discontinuous spindles

**Comment by mah11** [comment]
do you want the "discontinuous" bit in the name and def as well?

**Comment by ValWood** [comment]
Probably not, I thought i'd mention it but I'm guessing it must only really an imaging artefact of it being thin? (so could be a comment, sometimes appear discontinuous)?

**Comment by mah11** [comment]
OK, will include comment and related synonym.

**Comment by mah11** [comment]
thin bipolar mitotic spindle FYPO:0006346

edit file: 333e78c7701a909ba0aad492aa9fd3502f16d909
release: e9b244b1696e76b5f3458fde0cae2e4e74facdfa
