### ISSUE TITLE
NTR: Suppression of ricinoleic acid toxicity

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3209]
PMID:25109267
Suppression of ricinoleic acid toxicity by ptl2 overexpression in fission yeast Schizosaccharomyces pombe.

**Comment by mah11** [comment]
I am very tempted to do this as resistance to ricinoleic acid, even though most of the "resistance to" chemicals get added to growth media rather than made by tweaked cells. (Synonyms can abound, of course.)

**Comment by ValWood** [comment]
OK, makes sense....I thought maybe it would be better to do that...

**Comment by mah11** [comment]
I've added a comment and some related synonyms to FYPO:0003396.

edit file: 333e78c7701a909ba0aad492aa9fd3502f16d909
release: e9b244b1696e76b5f3458fde0cae2e4e74facdfa
