### ISSUE TITLE
abolished promoter binding

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3211]
I would like a term to describe abolished binding of  the pap1 transcription factor to promoters.

As a place holder I used

FYPO:0005460 | abolished protein localization to chromatin at MCB promoters

so I wonder if this should have a parent

FYPO:0005460 | abolished protein localization to promoter

we could insert the pap1 promoter SO term if we know it (not sure, I can't find the page)

but this is only a subset (in response to diamide)

suggestions?

**Comment by ValWood** [comment]
PMID:27664222

**Comment by mah11** [comment]
some thoughts 

If the only assay was ChIP, then a localization-to-chromatin term is safer than a DNA binding term (cf. all the GO discussion).

There isn't a SO term for "pap1 promoter" by that name, and I wouldn't ask for one based only on what's in the paper intro. But if there's a consensus sequence, that could support a SO term, especially if there's a name for it that's not so gene product-specific.

No problem to add a term for "abolished protein localization to promoter".

**Comment by ValWood** [comment]
OK  "abolished protein localization to promoter".

**Comment by mah11** [comment]
new term
  abolished protein localization to chromatin at promoter FYPO:0006349

close if that's everything ...

edit file: 5be9590487dd6fb3b07ce6a8447c7a9e4ec5ad28
release: 1f0046da736d0f32f324315cc6481247acfac7c2

**Comment by mah11** [comment]
no further activity, so closing
