### ISSUE TITLE
NTR: decreased protein localization to chromatin at rRNA gene

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3212]
standard def

PMID:27451393

**Comment by mah11** [comment]
decreased protein localization to chromatin at rRNA genes FYPO:0006350

edit file: 5be9590487dd6fb3b07ce6a8447c7a9e4ec5ad28
release: 1f0046da736d0f32f324315cc6481247acfac7c2

**Comment by ValWood** [comment]
actually I meant just rDNA  .... rRNA genes sounds a bit odd?

**Comment by mah11** [comment]
note to self: xp ok; just update name & synonyms

**Comment by mah11** [comment]
done
edit file: 0cc5c1528aab2fe6026e396f5dbc316b8551b6da
release: 2a31420dccd2a91049fc411397242105f865590b
