### ISSUE TITLE
spindle microtubules detached from spindle pole

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3213]
I thought I asked for this one, clearly not....

**Comment by ValWood** [comment]
PMID:17579515
--

**Comment by mah11** [comment]
We have this:

[Term]
id: FYPO:0004613
name: spindle pole body detached from cytoplasmic microtubules
def: "A cell phenotype observed in the vegetative growth phase of the life cycle in which the spindle pole body is not attached to any cytoplasmic microtubules. Normally, the spindle pole body is attached to a single cytoplasmic microtubule bundle." [PMID:15772152, PomBase:mah]
comment: This phenotype may result from either absence of the microtubule bundle that would normally attach to the SPB, or from a problem with the SPB-microtubule attachment process.
growth" EXACT [PomBase:mah]
is_a: FYPO:0001474 ! abnormal spindle pole body morphology during vegetative growth

which looks not quite identical, but similar enough that it's probably what you're thinking of.

There's also this, but it's specific for astral MTs:

[Term]
id: FYPO:0004623
name: abolished astral microtubule anchoring at mitotic spindle pole body
def: "A cell phenotype in which astral microtubule anchoring at the mitotic spindle pole body does not occur." [PMID:15004232, PomBase:mah]
is_a: FYPO:0000054 ! abnormal microtubule cytoskeleton organization

Should I do the new one as SPB morphology (structure) or MT cytoskeleton organization (process, using GO:0034631 or GO:1990810)?

**Comment by ValWood** [comment]
I don't think either of those work, it's the spindle SPB is detached from the spindle itself. It's not dead easy to see from the figures but there is a helpful schematic above each column in the histogram.
![spb](https://user-images.githubusercontent.com/7359272/35642229-6a005c52-06ba-11e8-859b-865fd5de5ee0.jpg)

**Comment by mah11** [comment]
I wasn't suggesting that you use either term; I referred to them to illustrate my question about a new term: should it be a structure phenotype or a process phenotype? Since that figure is a still image I'm leaning towards structure, so that's what I'll add unless there's also watching-the-process data.

**Comment by ValWood** [comment]
I'm not sure, I don't think SPB morphology is  likely to be altered , its jut the connection to the spindle, so it seems more like a localization phenotype?

**Comment by ValWood** [comment]
I guess it could be abnormal bipolar spindle morphology...

**Comment by mah11** [comment]
> abnormal bipolar spindle morphology

OK, I think that works - PATO includes "connectivity of various parts" in morphology.

**Comment by mah11** [comment]
mitotic spindle microtubules detached from spindle pole body FYPO:0006351

In light of the discussion in #3223, I've put the new term under abnormal mitotic spindle (FYPO:0000338; i.e. not under bipolar spindle), to dodge the question of whether the spindle becomes "non-polar" when the SPBs cut loose from the MTs.

edit file: 0cc5c1528aab2fe6026e396f5dbc316b8551b6da
release: 2a31420dccd2a91049fc411397242105f865590b
