### ISSUE TITLE
NTR: Normal F-actin level in actomyosin contractile ring in early mitosis

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3215]
Normal F-actin level in actomyosin contractile ring in early mitosis

author request

figure 4A  PMID:29343550

**Comment by ValWood** [comment]
viable vegetative cell with normal morphology

child of
FYPO:0001315 | normal vegetative cell morphology
-- | --

**Comment by mah11** [comment]
> viable vegetative cell with normal morphology

use FYPO:0002177; I'll add a synonym soon

**Comment by mah11** [comment]
seems like there ought to be a has_part link ... I'll look into it next time I'm editing

**Comment by mah11** [comment]
Another question, about the first requested term: can "early mitosis" be narrowed specifically to prophase and/or metaphase? If not, I can still add the term but it wouldn't get a logical def.

**Comment by ValWood** [comment]
I don't think so  ...I think people often use this for everything up to chromosome segregation

(can you define as  prophase or metaphase?)

**Comment by mah11** [comment]
> (can you define as prophase or metaphase?)

In text, yes, but if it's even possible to do in a logical def I don't know how. It's not a big deal to have one more term without a logical def in the meantime.

**Comment by ValWood** [comment]
OK, I'm mailing Alaina Willet in a minute so I'll ask if it can be more specific.

**Comment by ValWood** [comment]
can't be more specific

**Comment by mah11** [comment]
normal F-actin level in actomyosin contractile ring during early mitosis FYPO:0006352

For FYPO:0002177, I've added a has_part link to FYPO:0001315 (normal veg morph). Shout if you see any weird term suggestions - I suspect odd inferences were the reason I haven't included a logical def for FYPO:0002177, so we should keep an eye out for anomalies.

edit file: 0cc5c1528aab2fe6026e396f5dbc316b8551b6da
release: 2a31420dccd2a91049fc411397242105f865590b
