### ISSUE TITLE
NTR: decreased rate of mitotic spindle elongation, specific

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3219]
FYPO:0003268 | decreased rate of mitotic spindle elongation
-- | --

during in anaphase B

**Comment by ValWood** [comment]
PMID:29021344

**Comment by mah11** [comment]
any different from FYPO:0005343?

id: FYPO:0005343
name: decreased rate of mitotic spindle elongation during anaphase B
def: "A cellular process phenotype observed in the vegetative growth phase of the life cycle in which the rate, or speed, of mitotic spindle elongation is decreased during anaphase B." [PMID:19686686, PomBase:mah]

**Comment by ValWood** [comment]
no that's the one (it wasn't a descendant?)

**Comment by ValWood** [comment]
Ok, I had already used it in the same session !
