### ISSUE TITLE
NTR: resistance to 2-DOG induced cell lysis

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3221]
def
resistance to cell lysis induced by the presence of higher concentration of 2-deoxyglucose in the vegetative growth phase of life cycle of cell

this is a user request. It might seem a bit odd but it is what they show...

"Lysis is more efficient in cells grown in a medium containing high glucose than cells grown in the presence of low glucose. Cells of the four deletion strains lyse in the presence of 2-DG when grown at the low glucose concentration but not so at the high concentration. This indicates that the four genes are involved in the control of 2-DG induced lysis and that this control is glucose dependent. Independent of the glucose concentration, cells of the strain contain- ing the overexpressed gene odr1 are not lysed by 2-DG."]

PMID:29319508

**Comment by ValWood** [comment]
and 2-deoxyglucose induced cell lysis

A phenotype in which a cell lyses, i.e. the plasma membrane ruptures and cytoplasm is lost, in presence of higher concentration of 2-deoxyglucose.

**Comment by mah11** [comment]
> resistance to 2-DOG induced cell lysis

I would be inclined to just use the existing resistance to 2-deoxyglucose term (FYPO:0000064). We haven't folded in the mechanism for any other chemical sensitivity or resistance terms.

> 2-deoxyglucose induced cell lysis

Is this worth pre-composing? We do pretty much everything except cell population growth as term+conditions (so lysis FYPO:0000647 + condition PECO:new 2-deoxyglucose added).

**Comment by mah11** [comment]
edits to the summary don't change my position

**Comment by ValWood** [comment]
I haven't edited anything?

**Comment by ValWood** [comment]
@Antonialock  you have more experience with this type of paper. Should this just be done with conditions. There  seems to be more here than just resistance, but I just don't know how to capture it....

**Comment by mah11** [comment]
> I haven't edited anything?

from the top of this very page:

![screen shot 2018-02-02 at 18 09 35](https://user-images.githubusercontent.com/5196259/35747992-4ea58758-0844-11e8-9776-cf195634f43a.png)

**Comment by ValWood** [comment]
Yes that was the comment I added with the second request...
I didn't change/edit the first comment.

**Comment by ValWood** [comment]
Well not after your comment. it might have been about a minute apart....as I went to the paper for the text. before the second part and your comment anyway....

**Comment by Antonialock** [comment]
I agree with Midori.
2DG messes up glycolysis.

I've added + 2-DG

> I would be inclined to just use the existing resistance to 2-deoxyglucose term (FYPO:0000064). We haven't folded in the mechanism for any other chemical sensitivity or resistance terms.

> Is

 this worth pre-composing? We do pretty much everything except cell population growth as term+conditions (so lysis FYPO:0000647 + condition PECO:new 2-deoxyglucose added).

**Comment by ValWood** [comment]
OK I know how to do it (to get the differntiation of the phenotypes)

Its the lysis phenotype with the  different conditions  + 2DG and low or high glucose...

I was having a blank.

I didn't want to ignore because the first author  so clearly understood the annotation process and did the annotation so precisely

https://curation.pombase.org/pombe/curs/b466cec3cdc7c5c0

can I get + 2DG as a condition?

**Comment by Antonialock** [comment]
I added it already, that's what I meant by "I've added + 2-DG" :-)

**Comment by ValWood** [comment]
Got you ;)
