### ISSUE TITLE
Ntr horsetail /telomere clustering related paper

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3223]
1.
monopolar spindle  during meiosis I
descendant to
FYPO:0005652 | abnormal spindle morphology during meiosis I
standard def

2.
nonopolar spindle  during meiosis I
synonym SPB detached from spindle (this is simialr to the mitotic phenotype last week?)

3.
SPB detached from the nucleus

4.
abolished for
FYPO:0000172 | abnormal meiotic telomere clustering

PMID:24954111

**Comment by mah11** [comment]
The first two names are identical except for a typo. Should they be more meaningfully different?

**Comment by mah11** [comment]
in-person chat: for no. 2, use "SPB detached yada" wording in term name, and include "non-polar spindle" related synonyms for both new and existing (mitotic) terms

**Comment by mah11** [comment]
monopolar spindle during meiosis I FYPO:0006363
  spindle microtubules detached from spindle pole body during meiosis I FYPO:0006364
  spindle pole body detached from nucleus FYPO:0006365
  abolished meiotic telomere clustering FYPO:0006366

edit file: 0cc5c1528aab2fe6026e396f5dbc316b8551b6da
release: 2a31420dccd2a91049fc411397242105f865590b
