### ISSUE TITLE
various telomere attachment and SPB PMID:17632059

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3228]
PMID:17632059

NEW1:abnormal meiotic spindle pole body organization during meiosis I
child of
FYPO:0003560 | abnormal spindle pole body organization
standard def

NEW2: abnormal sporulation resulting in formation of two-spore ascus, DNA not encapsulated
child of 
FYPO:0000681 | abnormal sporulation resulting in formation of two-spore ascus
(with DNA excluded from ascus)

NEW3 normal spindle pole body oscillation during meiotic prophase
child of
FYPO:0000535 | normal spindle pole body localization

NEW4 multiple meiotic spindles
sibling of
FYPO:0003754 | multiple mitotic spindles
(have V-shaped patterns indicating multiple spindles, apparently)

NEW5 meiotic spindle absent from cell during meiosis
parent of
FYPO:0003614 | meiotic spindle absent from cell during meiosis II

NEW6
meiotic spindle pole body detached from nucleus
child of 
FYPO:0006365 | spindle pole body detached from nucleus
(are these all mitotic?)

NEW7
 abolished protein localization to meiotic spindle pole body during meiosis I
FYPO:0003542 | abolished protein localization to meiotic spindle pole body

NEW8:  abnormal meiotic spindle localization

typo FYPO:0006365
Matching synonym | SPB detached from nucleuss

**Comment by mah11** [comment]
Q re new2:
From the text accompanying Figure 1, I got the impression that the asci in which some DNA is not enclosed in spores do not all necessarily have exactly two spores. Should the term be "abnormal sporulation resulting in formation of ascus containing non-uniform spores and unencapsulated DNA" (is_a FYPO:0000913)?

Q re new6:
FYPO:0006365 was added for #3223 (PMID:24954111), and is not specific for mitotic or meiotic SPB. I gather that paper is all about meiotic stuff. I could either add new terms or convert FYPO:0006365 to meiotic, depending on whether you think a mitotic term will also be useful. Which?

Q re new8:
GO doesn't have a term for meiotic SPB localization. Do you plan to request one? In the meantime, I can put the term in without a logical def.

**Comment by mah11** [comment]
update to Q about new8: I got spindle and spindle pole body confused, but it turns out not to matter - GO also doesn't have plain "meiotic spindle localization", although it does have "establishment of meiotic spindle localization". The same is true for mitotic terms, but we haven't needed to use them for FYPO defs so far.

So the question becomes: should I use the "establishment" term or wait for a new, less specific, term to do a logical def?

**Comment by ValWood** [comment]
because it's attchment, I think you can use establishment...

**Comment by ValWood** [comment]
New2- yes sure.

New 6. 
You can change the existing term to meiotic, but I thought I had seen a very similar mitotic phenotype already (very recently)...I wonder what I used?

**Comment by ValWood** [comment]
ignore, I was thinking of
mitotic spindle microtubules detached from spindle pole body (FYPO:0006351)

**Comment by mah11** [comment]
OK, got these in and will do the rest tomorrow:
  abnormal mitotic spindle pole body organization FYPO:0006387
  abnormal meiotic spindle pole body organization during meiosis I FYPO:0006388
  normal meiotic spindle pole body oscillation during prophase I FYPO:0006389
  multiple meiotic spindles FYPO:0006390
  meiotic spindle absent from cell during meiosis FYPO:0006391
  abolished protein localization to meiotic spindle pole body during meiosis I FYPO:0006392
  localization phenotype during meiotic cell cycle FYPO:0006393
  abnormal meiotic spindle localization FYPO:0006394

renamed FYPO:0000534 & FYPO:0000535 to refer to mitotic spindle pole body (consistent with existing placement and text defs)

edit file: 5d4ced20f8321089376ba5633daec7d24225c498
release: ade0dde1b374d759a0ac9dc602c0f7c66561f321

**Comment by mah11** [comment]
last one done
abnormal sporulation resulting in formation of ascus containing non-uniform spores and unencapsulated DNA FYPO:0006383

edit file: ebfb6bcd33a1dfd2b17dccfd1b087652671669b1
release: 91086f719b0e87a8f054e0f32980d65ca61873ff
