### ISSUE TITLE
single elongated microtubule bundle curved around cell end

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3231]
single elongated microtubule bundle curved around cell end

because another paper with the same phneotype for the same deletion says

In contrast, cells lacking Mia1p usually exhibited two microtubule bundles curving around cell tips (Figure 1, D and E).

can we make this term
reduced number of elongated microtubule bundles curved around cell end

**Comment by mah11** [comment]
OK, FYPO:0006195 name is now 'decreased number of elongated microtubule bundles curved around cell end'.

I also moved it up to directly is_a FYPO:0005558 'abnormal microtubule bundle'; I didn't change the old parent FYPO:0002400 'single microtubule bundle'

edit file: ebfb6bcd33a1dfd2b17dccfd1b087652671669b1
release: 91086f719b0e87a8f054e0f32980d65ca61873ff
