### ISSUE TITLE
microtubule related

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3232]
new1: abnormal iMTOC assembly
standard
PMID:16481403

new2: cytoplasmic detached from nuclear envelope
standard
PMID:16481403

**Comment by ValWood** [comment]
oops yes

**Comment by mah11** [comment]
abnormal iMTOC assembly FYPO:0006396
cytoplasmic microtubules detached from nuclear envelope FYPO:0006397

edit file: ebfb6bcd33a1dfd2b17dccfd1b087652671669b1
release: 91086f719b0e87a8f054e0f32980d65ca61873ff
