### ISSUE TITLE
NTR fragmented spindle pole body

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3236]
fragmented spindle pole body

standard def

**Comment by ValWood** [comment]
meiotic

FYPO:0006365 | spindle pole body detached from nucleus

**Comment by mah11** [comment]
> fragmented spindle pole body

Do you want a meiotic version? We have FYPO:0001475 (FYPO:0001475), which is implicitly mitotic (and I can rename it).

> meiotic
> 
> FYPO:0006365 | spindle pole body detached from nucleus

In #3228 you said we could make FYPO:0006365 meiotic, because you haven't seen a mitotic instance yet. Then I forgot to rejig the term. I'll get on it today.

**Comment by ValWood** [comment]
yes, I think I meant to ask for the meiotic fragmented term

Yes make  FYPO:0006365 | spindle pole body detached from nucleus meiotic

tks

val

**Comment by mah11** [comment]
done; new terms (including some grouping terms):
  fragmented spindle pole body FYPO:0006404
  fragmented meiotic spindle pole body FYPO:0006405
  abnormal spindle pole body morphology during meiotic cell cycle FYPO:0006406

edit file: e9ce31b3f8d3504564d732f979a13ac91757c453
release: 4af8a951e3bba36b0ae99af818d471187455b0d4
