### ISSUE TITLE
spindle elongation ontology issue

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3241]
FYPO:0006173 | abolished mitotic spindle elongation during prophase

is a child of "abolished spindle elongation"

This means that, presumably  it comes out of a query for "abolished spindle elongation. However, the spindle elongation isn't totally abolished because it elongates normally at anaphase B.

![spindle](https://user-images.githubusercontent.com/7359272/36785206-f6b3f86e-1c79-11e8-8341-4c860183b386.jpg)

**Comment by mah11** [comment]
This is not asserted. I've changed the logical definitions for FYPO:0006173 and FYPO:0006174 to use GO:0061804 and GO:0061805. Let's see if that works - I think it should keep the links from being inferred by the reasoner. Reopen this if it doesn't work.

edit file: 93104261e59ada1a9ca056bfb1465ae158adaad7
release: 01b274219f5c6c1f7bf21ded74d8089f1094439d
