### ISSUE TITLE
monopolar mitotic  spindle /synonym

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3242]
lethal mutations lead cells into mitotic arrest with characteristic V-shaped monopolar spindles at the restric- tive temperature (Hagan and Yanagida, 1990, 1992).

add "V-shaped spindle"
as a related synonym (I think a later phenotype , bent spindle can also look V-shaped?)

**Comment by mah11** [comment]
done

edit file: 93104261e59ada1a9ca056bfb1465ae158adaad7
release: 01b274219f5c6c1f7bf21ded74d8089f1094439d

**Comment by ValWood** [comment]
is this in definitely. I searched on "V-shaped" and it didn't show...

**Comment by mah11** [comment]
Yes, it's been in for a week, and does show up in the Canto autocomplete for me. If it's not showing up in the website search, that's one for Kim.
