### ISSUE TITLE
PMID:21979813 cohesin various

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3247]
PMID:21979813
Acetylation regulates monopolar attachment at multiple levels during meiosis I in fission yeast.

decreased meiotic sister chromatid cohesion at centromere during meiosis I
abolished "
normal " 
abolished kinetochore mono orientation at meiosis I
decreased "

plus
normal mitotic sister chromatid biorientation

standard defs

**Comment by mah11** [comment]
decreased meiotic sister chromatid cohesion at centromere during meiosis I FYPO:0006423
  abolished meiotic sister chromatid cohesion at centromere during meiosis I FYPO:0006424
  normal meiotic sister chromatid cohesion at centromere during meiosis I FYPO:0006425
  normal attachment of spindle microtubules to kinetochore involved in homologous chromosome segregation FYPO:0006426
  abolished attachment of spindle microtubules to kinetochore involved in homologous chromosome segregation FYPO:0006426
  normal mitotic sister chromatid biorientation FYPO:0006428

edit file: 092e56b5c3ab9a32e4450de0a8287e92d03658bd
release: 61932ede42e2740ae48af70a5ac53ccba20848b2

(did the work yesterday but forgot to close tickets)

**Comment by ValWood** [comment]
is
abolished attachment of spindle microtubules to kinetochore involved in homologous chromosome segregation FYPO:0006426

exactly the same as 
abolished mono orientation at meiosis I?

It seems that  there is attachment, but that the chromosomes are not mono-orientated?

**Comment by mah11** [comment]
> is ... FYPO:0006426
> 
> exactly the same as
> abolished mono-orientation at meiosis I?

Yes, according to the xp'd GO term:

    id: GO:0051455
    name: attachment of spindle microtubules to kinetochore involved in homologous chromosome segregation
    synonym: "sister kinetochore mono-orientation" EXACT []

If that's not accurate, get the GO term corrected first, so I can keep FYPO consistent with GO (the GO fix might also help make it clearer how to do so).

**Comment by ValWood** [comment]
I don't think there is a problem with the go term though.

At meiosis I  correct attachment -> mono orientation..


abolished attachment of spindle microtubules to kinetochore involved in homologous chromosome segregation FYPO:0006426

doesn't work  
maybe I mean "incorrect attachment"  so just

abnormal attachment of spindle microtubules to kinetochore involved in homologous chromosome segregation

**Comment by ValWood** [comment]
"abnormal kinetochore orientation at meiosis I " is what I actually need

**Comment by mah11** [comment]
> I don't think there is a problem with the go term though.
> 
> At meiosis I correct attachment -> mono orientation..

Yep, if "attachment of spindle microtubules to kinetochore involved in homologous chromosome segregation" = "sister kinetochore mono-orientation" (as GO has it now), then abolishing the "attachment" process is abolishing the "mono-orientation" process.

> "abnormal kinetochore orientation at meiosis I " is what I actually need

That sounds a lot like FYPO:0000209. I could add another synonym ...

    id: FYPO:0000209
    name: abnormal attachment of spindle microtubules to kinetochore involved in homologous chromosome segregation
    def: "A cellular process phenotype in which the attachment of spindle microtubules to the kinetochore during the first meiotic nuclear division is abnormal." [PomBase:mah]
    comment: Abnormal kinetochore attachment may cause separation of sister chromatids during the first meiotic nuclear division, leading to equational segregation. If this occurs, also annotate to 'sister chromatid separation during meiosis I followed by equational sister chromatid segregation' (FYPO:0005634).
    synonym: "abnormal kinetochore mono-orientation at meiosis I" EXACT [PomBase:vw]
    synonym: "abnormal sister kinetochore mono-orientation" EXACT [GO:0051455]

**Comment by mah11** [comment]
synonym added, tho it didn't make today's release

**Comment by ValWood** [comment]
that's what  I need ;)
