### ISSUE TITLE
NTR: normal histone H3-K9 di methylation at subtelomeric heterochromatin during vegetative growth

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3250]
normal histone H3-K9 dimethylation at subtelomeric heterochromatin during vegetative growth

PMID:29136238

**Comment by mah11** [comment]
normal histone H3-K9 dimethylation at subtelomeric heterochromatin during vegetative growth FYPO:0006429

edit file: 092e56b5c3ab9a32e4450de0a8287e92d03658bd
release: 61932ede42e2740ae48af70a5ac53ccba20848b2
