### ISSUE TITLE
condition glucose MM, + 20 amino acids

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3260]
glucose MM, + 20 amino acids
PMID:29432178

**Comment by Antonialock** [comment]
I tweaked the def of glucose MM to say that it may include supps (it will definitely have been used like this so far). If it is important to state which ones we can either make terms for MM with XYZ supps (or just add them as +ura +ade etc)

**Comment by ValWood** [comment]
I wanted to  use
glucose MM
and 
glucose MM, + 20 aa

which seemed OK  as there are lots of
glucose MM, using x as nitrogen source?

**Comment by Antonialock** [comment]
Yes ut the the X nitrogen source is defined. Here you are just saying "lots of different amino acids added"

I presume it is it the 20 standard ones? I guess we could add "  + glucose MM, supp 20 standard aa's "...I wouldn't want to start adding e.g. YE5A etc, it's useless as it could mean different things. 
Or if we just add the supps as a standalone condition, then they can be mixed and matched?

**Comment by ValWood** [comment]
I just need a way to differentiate the experiment  from  "glucose MM" only and none of the existing work.

Just  "glucose MM, + amino acids" ?

I'm not very good with media....there might already be a way...

**Comment by Antonialock** [comment]
ok, I added the condition + 20 standard aa's
