### ISSUE TITLE
NTR amino acid response

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3261]
decreased transcription of  amino acid biosynthesis genes during response to amino acid starvation

child of
FYPO:0005229 | decreased transcription from RNA polymerase II promoter during vegetative growth

(I don't think we need to say po lII explicitly as we know these  are polI  transcribed)

PMID:29432178

**Comment by ValWood** [comment]
ntr
abnormal transcriptional response to amino acid starvation

ntr: 
decreased translation of amino acid biosynthesis genes in response to amino acid starvation

**Comment by mah11** [comment]
decreased transcription of amino acid biosynthesis genes during vegetative growth FYPO:0006443
  abnormal transcriptional response to amino acid starvation FYPO:0006444
  decreased translation of amino acid biosynthesis proteins during vegetative growth FYPO:0006445

edit file: dcfbacedfa48ea3e1ca957f71e1766e36d3b2838
release: 1f6d41e3adba95f410a59a4e7ae56538f3e7a40b
