### ISSUE TITLE
NTR increased mitochondrial pre-mRNA level

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3263]
descendant of
 increased pre-mRNA level
and
increased mitochondrial RNA level

def
A cell phenotype observed in the vegetative growth phase of the life cycle in which the amount of unspliced or incompletely spliced mitochondrial RNA measured in a cell is greater than normal. Total RNA or a specific RNA may be affected.

PMID:29458562

**Comment by mah11** [comment]
increased mitochondrial pre-mRNA level FYPO:0006446

edit file: dcfbacedfa48ea3e1ca957f71e1766e36d3b2838
release: 1f6d41e3adba95f410a59a4e7ae56538f3e7a40b
