### ISSUE TITLE
telomere length

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3270]
searching on "telomere length" gives "normal telomere length"

I could not immediately find the terms for  "abnormal telomere length"

(after a while I found elongated  telomeres, perhaps a synonym? or parent)

**Comment by mah11** [comment]
there isn't one, but I can add next time I'm editing FYPO

**Comment by ValWood** [comment]
not a biggie....thought it might be useful for searching...

**Comment by mah11** [comment]
abnormal telomere length FYPO:0006464

edit file: cf832d50824051bbfec452bac746de4807043bf2
release: 2d512e5115668d34e787fffb8b8ec690075a4b74
