### ISSUE TITLE
decreased mature nRNA level

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3271]
child of 

FYPO:0001117 | decreased RNA level during vegetative growth

(maybe group maturation?)

(this is for telomerase)

PMID:29422501

**Comment by mah11** [comment]
What's nRNA? typo? I don't see it in SO ...

and

> (maybe group maturation?)

what does this mean?

**Comment by ValWood** [comment]
typo 
ncRNA

there are quite a few 
decreased RNA level of mature ....

**Comment by mah11** [comment]
altered mature ncRNA level during vegetative growth FYPO:0006465
  decreased mature ncRNA level during vegetative growth FYPO:0006466
  increased mature ncRNA level during vegetative growth FYPO:0006467
  altered mature rRNA level during vegetative growth FYPO:0006468
  normal mature ncRNA level FYPO:0006469
  decreased mature rRNA level FYPO:0006470

edit file: cf832d50824051bbfec452bac746de4807043bf2
release: 2d512e5115668d34e787fffb8b8ec690075a4b74
