### ISSUE TITLE
finishing PMID:29432178

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3272]
I don't see

FYPO:0006444 | abnormal transcriptional response to amino acid starvation
as a descendant of

FYPO:0004064
Ontology | fission_yeast_phenotype
Term name | abnormal transcription during vegetative growth

should I?

also need

FYPO:0006445 + in response to amino acid starvation
FYPO:0006443 + in response to amino acid starvation

**Comment by mah11** [comment]
> [should FYPO:0006444 be] a descendant of FYPO:0004064

Not directly, but I can add a link to abnormal _regulation_ of transcription.

**Comment by ValWood** [comment]
ok,

and from Juan
1. In the second phenotype of gcn2delta it says 'abnormal regulation of translation in response to nitrogen starvation' - should say 'abnormal regulation of translation in response to AMINO ACID starvation' 

so NTR for this too
