### ISSUE TITLE
cohesin loading, second strand capture

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3273]
Once a term exists for 2nd  strand capture

https://github.com/geneontology/go-ontology/issues/15513

I need:
decreased mitotic cohesin ssDNA (lagging strand) loading
descendent of FYPO:0005555 | decreased mitotic cohesin loading

normal  mitotic cohesin ssDNA (lagging strand) loading
(there is no normal loaing term currently)

increased  mitotic cohesin ssDNA (lagging strand) loading

we also need the equivalent ds-loading terms for the existing phenotypes

**Comment by mah11** [comment]
> we also need the equivalent ds-loading terms for the existing phenotypes

This was a bit confusing, so reopen if I've missed any terms, and in future please provide a simple, straightforward, complete list of all new terms you're requesting.
  
decreased mitotic cohesin dsDNA (leading strand) loading FYPO:0006478
abnormal cohesin loading FYPO:0006479
normal cohesin loading FYPO:0006480
increased mitotic cohesin ssDNA (lagging strand) loading FYPO:0006481
normal mitotic cohesin ssDNA (lagging strand) loading FYPO:0006482
decreased mitotic cohesin ssDNA (lagging strand) loading FYPO:0006483
abolished mitotic cohesin dsDNA (leading strand) loading FYPO:0006484

edit file: c97b3b6deffa646901716342b8e38d25e85ae32e
release: 26292d5dada779e4c2e25ace9ed0d27185395cda
