### ISSUE TITLE
mitotic spindle breakage/collapse

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3274]
mitotic spindle breakage
child of unstable mitotic spindle
(or is collapse an output?)

I want to capture:
Interestingly, 18% of asp1
showed spindle breakage (Fig. 1C). A typical example of such a phenotype in which the spindle collapsed and then reformed is shown in Fig. 1D.

**Comment by mah11** [comment]
I'm not yet clear on what (if anything) is the difference between spindle "breakage" and spindle "collapse", especially since the quoted bit uses them as though they mean basically the same thing.

also, what paper?

**Comment by ValWood** [comment]
OK I was going to ask that next.
PMID:27697865

So would it be better to use collapse (since all of the descendants are  collapse during...)

**Comment by mah11** [comment]
> So would it be better to use collapse ...

Where?

**Comment by ValWood** [comment]
in the term name (to match the descendants?)

**Comment by mah11** [comment]
Are you talking about FYPO:0006048? If so, then no, not all of its descendants are collapse terms. If not, which term?

We have no terms with "spindle breakage" in names or synonyms, but the paper seems to be using breakage and collapse interchangeably (the latter more frequently). So it seems that it ought to work to add "breakage" synonyms to some or all of the "collapse" terms. OK?

**Comment by ValWood** [comment]
sorry I do mean
FYPO:0006048 | unstable mitotic spindle


should this be "mitotic spindle collapse" for consistency with synonyms "broken mitotic spindle" "spindle breakage" and "unstable mitotic spindle"?

**Comment by mah11** [comment]
No, because not all descendants of FYPO:0006048 are spindle collapse terms.

That would not prevent adding "broken spindle" or "spindle breakage" synonyms to the terms that are spindle collapse.

**Comment by ValWood** [comment]
So can I have a term for just "mitotic spindle collapse/ mitotic spindle breakage"?

**Comment by mah11** [comment]
yes, but be warned that I will point and laugh if you later flag the new term for the don't-annotate soft check on the grounds that one should always be able to tell if it's happening in prophase or anaphase

**Comment by ValWood** [comment]
Hmm I might do that in a minute, I should look more closely at this paper...

**Comment by ValWood** [comment]
in the first experiment I could not be sure:
 A typical example of such a phenotype in which the spindle collapsed and then reformed is shown in Fig. 1D.

later exp:
Spindle collapse occurs prior to chromosome segregation. In order to determine at which mitotic stage spindle collapse oc- curred, we used a strain where the segregation behavior of chro- mosome I sisters and the SPBs could be monitored. 
.......Upon spin- dle collapse (time point 28 min; the distance between SPBs changed from 4.5 to 1.1 􏰊m), faint spot-like Ark1-GFP signals were observed, suggesting that spindle breakage occurs prior to anaphase B. Following spindle collapse, the spindle regenerated and the cell was able to finish mitosis, as indicated by the spindle localization of Ark1-GFP (Fig. 3D, right panels). 

so here I do know,  because ark1  localization was assayed

**Comment by ValWood** [comment]
I'd still like the "mitotic spindle collapse" term, 

(Its not in anaphase but the prophase term  says the spindle is not elongated, so that doesn't fit either)

**Comment by ValWood** [comment]
aso 
NTR increased rate of mitotic spindle elongation during prophase

**Comment by mah11** [comment]
erm, it looks like you deleted the comment that had the PMID ...

**Comment by ValWood** [comment]
whoops PMID:27697865

**Comment by mah11** [comment]
mitotic spindle collapse FYPO:0006475

'breakage' synonyms also added

edit file: 5a6ce938d3fea80cbe496a7f332a70bfc22f9683
release: 556dfd1cca52e88a7b3c4812f6f244054ab740f6
