### ISSUE TITLE
FYPO:0004234	increased duration of mitosis

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3275]
has no children.

I guess this is because things like "increased duration of anaphase" do not always incur a mitotic delay?

anyway, I would like
increased duration of mitotic metaphase
(but is this the same as  

mitotic metaphase/anaphase transition delay? I guess so????

**Comment by ValWood** [comment]
Ah got you.

I think we can use "increased duration of mitotic M-phase" for "increased duration of mitosis

(mean the same for the 'duration purpose").

could we merge  and add "duration of mitosis" as a "related synonym"?


4 | normal duration of mitosis (FYPO:0005632) [single allele genotypes] | ...
  | 2 | increased duration of mitosis (FYPO:0004234) [single allele genotypes]

**Comment by mah11** [comment]
yup, no problem

**Comment by ValWood** [comment]
and
premature metaphase/anaphase transition

child of
FYPO:0000827 | premature cell cycle phase transition | Microscopy |   | metaphase /anaphase

**Comment by mah11** [comment]
new terms
  premature mitotic metaphase/anaphase transition FYPO:0006476
  abnormal mitotic metaphase/anaphase transition FYPO:0006477

merged 'duration of mitosis' terms into 'duration of M' terms
  FYPO:0004234 into FYPO:0000274
  FYPO:0005632 into FYPO:0004310

edit file: 5a6ce938d3fea80cbe496a7f332a70bfc22f9683
release: 556dfd1cca52e88a7b3c4812f6f244054ab740f6
