### ISSUE TITLE
phosphatidylinositol terms

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3276]
increased levels of PI(3,4)P2
increased levels of PI(3,4,5)P3
fig 2 

PMID:15249580

**Comment by ValWood** [comment]
normal PI(3)P levels

**Comment by ValWood** [comment]
decreased levels of PI(3,4)P2
decreased levels of PI(3,4,5)P3

**Comment by mah11** [comment]
note to self - descendants of CHEBI:28765

**Comment by ValWood** [comment]
decresed PI(4,5)P2 levels

**Comment by mah11** [comment]
decreased cellular phosphatidylinositol-3,4-bisphosphate level FYPO:0006485
  decreased cellular phosphatidylinositol-3,4,5-trisphosphate level FYPO:0006486
  increased cellular phosphatidylinositol-3,4-bisphosphate level FYPO:0006487
  increased cellular phosphatidylinositol-3,4,5-trisphosphate level FYPO:0006488
  normal cellular phosphatidylinositol-3-phosphate level FYPO:0006489

with synonyms

edit file: c97b3b6deffa646901716342b8e38d25e85ae32e
release: 26292d5dada779e4c2e25ace9ed0d27185395cda
