### ISSUE TITLE
decreased duration of mitotic M-phase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3277]
https://github.com/pombase/fypo/issues/3275

I forgot (or cant find!)

decreased duration of mitotic M-phase

**Comment by mah11** [comment]
nope, we actually didn't have it before

decreased duration of mitotic M phase FYPO:0006490

edit file: c97b3b6deffa646901716342b8e38d25e85ae32e
release: 26292d5dada779e4c2e25ace9ed0d27185395cda

**Comment by ValWood** [comment]
hmmph, I have no idea what this was for now.....
