### ISSUE TITLE
How? required for G2 arrested cells to proliferate subsequently

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3288]
How would you capture this?

the only think I can think of is

inviable population  with condition "G2 ts block and release"

**Comment by ValWood** [comment]
I think I need the condition  "G2 ts block and release"
so that I can use with the other post block phenotypes (pds5 is viable if it is not arrested in G2 first)

**Comment by mah11** [comment]
I don't think "G2" should be part of a condition. The condition in the experiments using ts mutant here is simply temperature block and release, and which phase the cells arrest in depends on their genotype.

**Comment by mah11** [comment]
Given how the experiments were done, it looks as though "loss of viability following arrest in mitotic G2 phase" should do. If you want a separate term for the stationary phase data, we can also add "loss of viability in stationary phase following entry from mitotic G2 phase" or similar.

**Comment by ValWood** [comment]
OK go for those...

**Comment by mah11** [comment]
loss of viability following cell cycle arrest in mitotic G2 phase FYPO:0006522
  loss of viability in stationary phase following entry from mitotic G2 phase FYPO:0006523

edit file: 624241bb5ea36d807028f32008966c4537678811
release: 0a472de1ef2061633019526ba2aab2df216964fb
