### ISSUE TITLE
PMID:11598020 split kinetochore

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3290]
split kinetochore during mitotic G2

**Comment by ValWood** [comment]
split kinetochore during stationary phase

(different penetrances)

**Comment by mah11** [comment]
split kinetochore during mitotic G2 phase FYPO:0006524
  split kinetochore during stationary phase FYPO:0006525

edit file: 73508f0c207dd2e6eb12452b3f175066c5bf9215
release: 247360caa543e0bfe288ba9235c2eb1c9eba35f0
