### ISSUE TITLE
PMID:20383139 various

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3291]
Eeeuh, its been a long day..this is the paper I started after our call this morning, but lots of side tracking.... (although this  2010 is not diminished by time, such elegant assays as always).

So I think this is what I need, but after around 20 side tracks I may  have missed something...

abolished meiosis I
child of  FYPO:0003603

decreased proteolysis 
child of FYPO:0005376
(not processing because it refers to  securin cleavage by  separase).

abolished protein localization to centromeric region during meiotic prophase II
child of 
FYPO:0005208  abolished protein localization during meiotic cell cycle

delayed protein degradation during meiosis
child of
FYPO:0002275 | abnormal protein degradation

**Comment by ValWood** [comment]
normal protein localization to centromeric region during meiotic prophase II

**Comment by mah11** [comment]
> abolished meiosis I
> child of FYPO:0003603

term exists (FYPO:0003378); I'll add the link

> decreased proteolysis

we have FYPO:0005443 decreased proteolysis during vegetative growth

do you need a generic term, or a meiosis- or meiotic cell cycle-specific one? (or more? all of the above?)

**Comment by mah11** [comment]
new terms (includes a couple new grouping terms)
  abnormal meiosis II  FYPO:0006526
  decreased proteolysis FYPO:0006527
  decreased proteolysis during meiotic cell cycle FYPO:0006528
  abnormal protein localization to centromere during meiotic cell cycle FYPO:0006529
  abolished protein localization to centromere during prophase II FYPO:0006530
  delayed onset of protein degradation during meiosis FYPO:0006531
  normal protein localization to centromere during prophase I FYPO:0006532
  
added link FYPO:0003378 is_a FYPO:0003603

edit file: 73508f0c207dd2e6eb12452b3f175066c5bf9215
release: 247360caa543e0bfe288ba9235c2eb1c9eba35f0
