### ISSUE TITLE
PMID:9200612 tea1 related

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3293]
decreased protein level during conjugation with cellular fusion

**Comment by ValWood** [comment]
increased RNA level during mitotic M phase

**Comment by mah11** [comment]
decreased protein level during mating FYPO:0006541

edit file: 73508f0c207dd2e6eb12452b3f175066c5bf9215
release: 247360caa543e0bfe288ba9235c2eb1c9eba35f0
