### ISSUE TITLE
possible missing parent or reasoner barf

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3296]
i didn't see:

abolished protein localization to centromere during prophase II - FYPO:0006530

under
abolished protein localization during meiotic cell cycle - FYPO:0005208

**Comment by mah11** [comment]
gonna need a hint here ;)

**Comment by ValWood** [comment]
yep I hit return too soon, it's above !

**Comment by mah11** [comment]
well, you should - the link is actually asserted, and FYPO:0006530 comes up for me

**Comment by ValWood** [comment]
hmm maybe I did not see it under 
abolished protein localization during mitosis

I added the terms now  but I had both terms as parents....

**Comment by mah11** [comment]
>      abolished protein localization during mitosis
>                                            ^^^^^^^

I think I see your problem ...

**Comment by mah11** [comment]
p.s. we don't actually have "abolished protein localization during _meiosis_" but I can add it if you want

**Comment by ValWood** [comment]
No, I'll assume I was just looking in the wrong place...
