### ISSUE TITLE
MP FYPO:0006497?

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3297]
I didn't find

FYPO:0006497 | abnormal plasma membrane phosphatidylserine distribution

under

FYPO:0000813 | abnormal plasma membrane organization

**Comment by ValWood** [comment]
I'd like to say more specifically
loss of plasma membrane phosphatidylserine polarity
(phosphatidylserine does not accumulate at tips)

and
loss of plasma membrane phosphatidylserine at the non-growing tip

**Comment by mah11** [comment]
Ah, I did the PS distribution terms as "subcellular component". Should I recast them as process phenotypes?

If I do that for the existing terms, it would probably also make sense to put the PS-at-tips terms into a process-y form too. Maybe "abnormal PS distribution resulting in ..."?

**Comment by ValWood** [comment]
I think  process might be better for these...?

**Comment by mah11** [comment]
done; a couple new grouping terms and one with a long clunky name (and some synonyms):
  abnormal membrane lipid distribution FYPO:0006545
  normal membrane lipid distribution FYPO:0006546
  abnormal plasma membrane phosphatidylserine distribution resulting in decreased concentration at cell tip FYPO:0006547

edit file: 0ab85ebfdb47f588e6ee51b7253dd606f3aed609
release: 69afaaf4a994d38bd73f28c2b9e54db281344e04
