### ISSUE TITLE
PMID:8521500 cyclin CDK various

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3303]
1.
decreased protein kinase activity during mitotic G1 phase

standard defs. fig 1

2. normal binding to cdc2-cdc13 complex during mitotic G1 phase
requested.

Suggest eventually precomposing with "A) mitotic CDK-cyclin complex"
suggested here:
https://github.com/geneontology/go-ontology/issues/15821

**Comment by mah11** [comment]
For (2), I'm wondering how many specific cyclin-CDK complexes we'd have to represent, and whether there would be complex binding GO MF terms for any or all of them. Right now all the "complex binding" FYPO terms have GO MF complex binding terms they can point to in logical defs.

It seems like it would work best to point to a fairly generic cyclin-CDK complex binding term, and put a more specific complex ID in an assayed_using extension. Even if GO adds lots of complexes, it's not so likely to include complex binding MF terms for all of them (and I wouldn't ask them to). But it would be pretty straightforward to ask for binding MFs for one or a few CC grouping terms. I think it would probably be OK to do a logical def involving inheres_in generic complex binding MF and a "towards" a more specific complex from CC.

Will GO:0000307 be repurposed so I could point a phenotype term to it now? I read the GO ticket but got a bit confused :P

**Comment by mah11** [comment]
for now I've gone with these:

  decreased protein kinase activity during mitotic G1 phase FYPO:0006560
  normal CDK-cyclin complex binding during mitotic G1 phase FYPO:0006561

I'll leave this ticket open until the GO one gets done, in case there's anything to update.

edit file: 0d9e0cf1388de76dd0c1197d2d475644171376f4
release: 2a1e2b5b008beb8d4f2a80b2801b314cba9770f3

**Comment by mah11** [comment]
let's just reopen this or create a new ticket if anything ever happens on the linked GO item
