### ISSUE TITLE
PMID:9303312 MBF trancription

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3304]
increased RNA level during mitotic G2

**Comment by ValWood** [comment]
Abolished  of MBF complex assembly in G1

**Comment by mah11** [comment]
https://github.com/geneontology/go-ontology/issues/15854

**Comment by mah11** [comment]
increased RNA level during mitotic G2 phase FYPO:0006562
  abolished MBF complex assembly during mitotic G1 phase FYPO:0006563

edit file: 0d9e0cf1388de76dd0c1197d2d475644171376f4
release: 2a1e2b5b008beb8d4f2a80b2801b314cba9770f3
