### ISSUE TITLE
is there a relationship between these 2 terms?

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3312]
FYPO:0003166 | monoseptate vegetative cell with binucleate and anucleate compartments 
 FYPO:0003241 | unequal mitotic sister chromatid segregation

**Comment by mah11** [comment]
No; there's a comment on FYPO:0003166 suggesting that FYPO:0003241 may also apply, but FYPO:0003166 and its parent and sibling (FYPO:0000229 and FYPO:0003165) are defined without specifying whether the chromosomes segregate equally, unequally, or not at all.

**Comment by ValWood** [comment]
ah right 
FYPO:0003166 | monoseptate vegetative cell with binucleate and anucleate compartments
might not be 'unequal', but it's not 'equational'  right?

**Comment by mah11** [comment]
FYPO:0003166 doesn't explicitly say whether segregation is equational or not. It just says something went wrong enough that two nuclei ended up on the same side of a septum. That means something must have gone wrong with chromosome segregation too, but the term doesn't say anything about what/how.

Also, FYPO:0003166 is defined as a vegetative growth phase phenotype, i.e. the segregation is mitotic. In a haploid, mitosis is always equational even when something goes wrong. So I suppose the term is implicitly about equational seg.

**Comment by mah11** [comment]
can reopen if any changes turn out to be needed, but so far this has just been some questions and responses
