### ISSUE TITLE
increased  metabolite level

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3313]
increased  metabolite level/concentration

I can't see anything for this.

I want to  describe

increased level of 
Diadenosine 5h,5e-P4,P7- tetraphosphate (Ap4A)   

PMID:10970777

note to self expressivity=high

**Comment by mah11** [comment]
I haven't used "metabolite" in any level-of-stuff term names because it's so broad - even as defined in ChEBI - that it pretty much covers any naturally occurring substance. I'll add a term for the specific compound in the "altered level of substance" branch. I think it's probably CHEBI:17422.

**Comment by mah11** [comment]
I had a nose round a few papers and links from the ChEBI page, and I am now convinced this is CHEBI:17422. I can't find the "5h,5e-P4,P7" string anywhere; I think it's a scanning artifact. So,

increased cellular P(1),P(4)-bis(5'-adenosyl) tetraphosphate level FYPO:0006577

edit file: 40fba236182fa955ab21d3c0212ef93056fb31b3
release: 6a623d18fa658d9addc4479b145f8c08c6938aba
