### ISSUE TITLE
NTR: normal mitotic G2 DNA damage checkpoint 

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3314]
parent of

FYPO:0005299 | normal mitotic G2 DNA damage checkpoint during cellular response to UV

PMID:9950674

**Comment by mah11** [comment]
normal mitotic G2 DNA damage checkpoint FYPO:0006578

edit file: 40fba236182fa955ab21d3c0212ef93056fb31b3
release: 6a623d18fa658d9addc4479b145f8c08c6938aba
