### ISSUE TITLE
sensitive to manganese

### ISSUE THREAD

**Issue by mah11** [pombase/fypo#3315]
PMID:29856841

**Comment by mah11** [comment]
and more:

resistance to amiodarone
sensitive to fenpropimorph

**Comment by ValWood** [comment]
They sound like characters from Lord of the Rings...

**Comment by mah11** [comment]
:D

**Comment by mah11** [comment]
sensitive to manganese FYPO:0006579
  resistance to amiodarone FYPO:0006580
  sensitive to fenpropimorph FYPO:0006581

edit file: 40fba236182fa955ab21d3c0212ef93056fb31b3
release: 6a623d18fa658d9addc4479b145f8c08c6938aba
