### ISSUE TITLE
decreased GO:0004081

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3316]
FYPO:0004644 | abnormal bis(5'-nucleosyl)-tetraphosphatase (asymmetrical) activity

PMID:10970777

**Comment by mah11** [comment]
decreased bis(5'-nucleosyl)-tetraphosphatase (asymmetrical) activity FYPO:0006582

edit file: 6c7fac3f04958d6268d202c27771ce34f27f834a
release: 4fe4578a3b868c1c95a8b11bcb826cb58dec41f2
