### ISSUE TITLE
revise FYPO:0002649 and new terms, for PMID:28974540

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3317]
I used
FYPO:0002649 | elongated kinetochore during vegetative growth
for
![extended](https://user-images.githubusercontent.com/7359272/41526462-3c2fb532-72dc-11e8-823f-3ac3f3023f83.jpg)

the author had used the parent term "abnormal kinetochore morphology..."

I think FYPO:0002649 is more accurate, but maybe

FYPO:0002649 | extended kinetochore during mitotic anaphase 
would be a better name?

(I can check if this works for existing, maybe its different as it isn't quite the current def.....)

**Comment by mah11** [comment]
I see no meaningful difference between "extended" and "elongated", but it's easy to add synonyms.

At present, neither the name nor the definitions (text & logical) restrict FYPO:0002649 to any part of mitosis or any other cell cycle phase. The comment suggests that it might be applicable at least to metaphase as well as anaphase, but if elongation is really only seen in anaphase, we can adjust the comment along with the name and defs.

**Comment by ValWood** [comment]
OK synonyms fine.
Actually this is both metaphase and anaphase so 

can we just change from:
elongated kinetochore during vegetative growth
to
elongated kinetochore during mitosis  

(sounds better)


Also need:

FYPO:0002339 | decreased protein localization to nuclear periphery
"during interphase"

for this paper

**Comment by mah11** [comment]
done; new term is

decreased protein localization to nuclear periphery during mitotic interphase FYPO:0006583

edit file: 6c7fac3f04958d6268d202c27771ce34f27f834a
release: 4fe4578a3b868c1c95a8b11bcb826cb58dec41f2
