### ISSUE TITLE
error in definition of FYPO:0003937 increased cell population growth?

### ISSUE THREAD

**Issue by dsiegele** [pombase/fypo#3318]
increased cell population growth  FYPO:0003937
     A cell population phenotype in which cell population growth is increased relative to normal. Increased growth may reflect a _reduced growth rate (i.e. faster growth)_, growth that occurs to a greater extent than normal, or both.

In bacteria, growth rate is defined as generations/hour. If the same definition is used for S. pome, when the rate of growth increases, the growth rate also increases (more generations per unit time). Increased growth rate is the result of a reduced doubling time (aka generation time).

**Comment by mah11** [comment]
It was simply a copy/paste error, now corrected. Thanks for reporting it.

edit file: c2caf3a974558d2d8a198695f21e4f8d63869c36
release: b2f2413ff77fbcf309c8e37716810579da15664d
