### ISSUE TITLE
decreased RNA pol2 localization to chromatin PMID:29899453

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3325]
decreased RNA pol2 localization to chromatin (occurs_at termination sites)

increased/decreased  transcription termination index

the ratio of protein sequence reads   in the region of the transcription termination site
2nd-to-last paragraph.

Can figure this? it doesn't seem to say precisely what it is a ratio of. I can only think its the signal in the termination region compared to the rest of the protein coding region. Let me know if you want me to double check.

**Comment by mah11** [comment]
> decreased RNA pol2 localization to chromatin (occurs_at termination sites)

It'll be "decreased protein localization to chromatin at transcription termination site" or similar.

For the RNA pol II part, put the polymerase subunit gene(s) in assayed_using extensions.

For the (occurs_at termination sites) part, I could use [SO:0002213 transcription_termination_signal](http://sequenceontology.org/browser/current_svn/term/SO:0002213) or, if that's too specific, I can just leave it without a logical def.

I can make it specific for "RNA polymerase II termination site" if you want.


> transcription termination index
> ...
> it doesn't seem to say precisely what it is a ratio of

Yes it does: that's what figure 4d illustrates. The termination index (TI) is the ratio of signal in the region marked 'y' to signal in the region marked 'x' (and termination elongation index (TEI) is the 'z'-signal-to-'x'-signal ration).

That said, is it important to make a distinction between TI and any other measure? I'd be tempted just to use increased/decreased pol II transcription (both new, is_a FYPO:0004811 abnormal termination of RNA polymerase II transcription).

**Comment by ValWood** [comment]
>That said, is it important to make a distinction between TI and any other measure? I'd be tempted just to use increased/decreased pol II transcription

no, I'll do that....it was at the end of a very long paper and I was losing the will to live...

**Comment by ValWood** [comment]
> For the (occurs_at termination sites) part, I could use SO:0002213 transcription_termination_signal or, if that's too specific,

you can precompose this part...could be useful

**Comment by mah11** [comment]
OK, here are new terms:
  decreased protein localization to chromatin at transcription termination site FYPO:0006612
  decreased termination of RNA polymerase II transcription FYPO:0006613
  increased termination of RNA polymerase II transcription FYPO:0006614

I'll close this, but reopen if anything looks amiss.

edit file: 1d2848996ab32bc5e021885e6e88b31ee293461a
release: e4683acfe7e1c93eeffbea434c48bdb1efdfe953
