### ISSUE TITLE
classical SIN phenotype

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3331]
it seems that sometimes the classical SIN phenotype is annotated as

elongated tetranucleate vegetative cell

and sometimes as
inviable multinucleate aseptate vegetative cell

I'm not sure if these are always a bit elongated? Probably? ask Jacky

but I think they are all tetranucleate because  they do one additional mitosis
if so

inviable multinucleate aseptate vegetative cell (FYPO:0004106
--FYPO_NEW inviable tetranucleate aseptate elongated vegetative cell 
Its a bit long but it's precise....

then I'll check and move down so that the same phenotypes are identically annotate.

https://github.com/pombase/curation/issues/1909

**Comment by mah11** [comment]
inviable elongated tetranucleate aseptate vegetative cell FYPO:0006630

edit file: 0ac528b14f75e5f8dab2c368f6361786fdf7327d
release: ed34ce74d1e2c18cf32e12deaa9efa80eed0d566
