### ISSUE TITLE
merge up "residue" terms phosphorylation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3332]
I think we should merge up "residue" terms phosphorylation
we don't appear to have many annotations to these, it's just  these ones: and a few more

![merge up](https://user-images.githubusercontent.com/7359272/42813243-3856c502-89b8-11e8-83f9-e52595554030.jpg)

I don' think this difference is important to capture. More important that we have the residue captured on the modification. In the phenotype annotations   we can now capture this  with an extension. If we know its ser or thr we will usually know which residue. If we don't we can just call "phosphorylation"

I have never used this particular specificity because it isn't very sustainable.

However in the feedback for the session I am checking I am getting:
suggestions to change terms:

![suggestions](https://user-images.githubusercontent.com/7359272/42813374-ae7a97a4-89b8-11e8-958e-25957e9d3e78.jpg)

So we will have inconsistency too.

I think it's better to bite the bullet and resolve sooner rather than letting them build up further...

**Comment by ValWood** [comment]
I guess there will be some increased etc too.....

**Comment by mah11** [comment]
Could you please list the terms in plain text, preferably with IDs? It's difficult to read screenshots, and impossible to copy/paste from them. Thanks!

**Comment by mah11** [comment]
> I'm not expecting you to read it!

then why include it?

> It really needs a complete list of terms but that is easier searching the ontology file

I don't need you to do the actual search, but a set of search criteria in the form of a simple list would make the search easier for either of us.

**Comment by ValWood** [comment]
> then why include it?

because I can read it?  It helps me.

**Comment by ValWood** [comment]
I know you don't like me including screenshots, but I find them quick and useful prompts when I refer back to the ticket,  (in this case a  feel for the number of times they were used). For this reason I will continue to do it (you can ignore them).

**Comment by mah11** [comment]
The problem is when there's a screenshot _instead_ of text describing what needs to be done for a ticket. When the screenshot is there in addition to sufficient text, it's a bit distracting for me but I'm happy to deal with it if it does help someone.

When I do the work for this ticket I'll delete these comments about screenshots because they have bugger-all to do with the ontology content change at hand.

**Comment by ValWood** [comment]
I can't find an *easy* way to get the full list. I would need to do lots of queries and inspect children, or grep through a gaf. Can you do this easily in Obo-edit? I could find a way to do  it but it would be tedious... and I could not be sure that I hadn't missed any...

**Comment by mah11** [comment]
What do you want to do with the histone modification terms that mention specific residues? I was under the impression that those were keepers because histones are special.

Specifically for phosphorylation, there are terms that mention H3-T3 and H3-S10 (plus all the methylation, acetylation, modification removal, etc ).

**Comment by ValWood** [comment]
Yes please, keep the histone ones because of the histone code. Just the "general" ones.

**Comment by mah11** [comment]
OK. Next question: keep or toss the ones that mention residues in the RNA pol II CTD?

FYPO:0004067	decreased phosphorylation of RNA polymerase II C-terminal domain serine 2 residues during vegetative growth
FYPO:0004068	decreased phosphorylation of RNA polymerase II C-terminal domain serine 5 residues during vegetative growth
FYPO:0004069	abolished phosphorylation of RNA polymerase II C-terminal domain serine 2 residues
FYPO:0005037	normal phosphorylation of RNA polymerase II C-terminal domain serine 5 residues during nitrogen starvation
FYPO:0005038	abolished phosphorylation of RNA polymerase II C-terminal domain serine 2 residues during nitrogen starvation
FYPO:0005039	decreased phosphorylation of RNA polymerase II C-terminal domain serine 2 residues during nitrogen starvation
FYPO:0005040	normal phosphorylation of RNA polymerase II C-terminal domain serine 2 residues during nitrogen starvation
FYPO:0005041	increased phosphorylation of RNA polymerase II C-terminal domain serine 2 residues during vegetative growth
FYPO:0005061	normal phosphorylation of RNA polymerase II C-terminal domain serine 5 residues during vegetative growth
FYPO:0005184	increased phosphorylation of RNA polymerase II C-terminal domain serine 5 residues during vegetative growth

**Comment by mah11** [comment]
Of the rest, if there are any that mention "during" phases or responses, and there isn't a residue-neutral term, I'll remove the residue part and make the term generic. For any that already have the neutral equivalent, I can make them obsolete.

The list:
FYPO:0001180	increased protein tyrosine phosphorylation during vegetative growth
FYPO:0002139	abolished protein threonine phosphorylation
FYPO:0002139	abolished protein threonine phosphorylation at Thr-Pro site during vegetative growth
FYPO:0002144	increased protein threonine phosphorylation
FYPO:0002144	increased protein threonine phosphorylation at Thr-Pro site during vegetative growth
FYPO:0002283	abolished protein tyrosine phosphorylation during cellular response to heat
FYPO:0002284	abolished protein tyrosine phosphorylation during cellular response to hydrogen peroxide
FYPO:0002288	abolished protein tyrosine phosphorylation during vegetative growth
FYPO:0002289	abolished protein tyrosine phosphorylation during cellular response to osmotic stress
FYPO:0002290	normal protein tyrosine phosphorylation during cellular response to osmotic stress
FYPO:0002291	normal protein tyrosine phosphorylation during cellular response to heat
FYPO:0002375	decreased protein tyrosine phosphorylation during vegetative growth
FYPO:0002376	decreased protein tyrosine phosphorylation during cellular response to osmotic stress
FYPO:0002542	decreased protein threonine phosphorylation at Thr-Pro site during cellular response to hydrogen peroxide
FYPO:0002543	decreased protein threonine phosphorylation at Thr-Pro site during cellular response to hydroxyurea
FYPO:0002544	abolished protein serine phosphorylation at RxxS site during cellular response to hydrogen peroxide
FYPO:0002545	abolished protein serine phosphorylation at RxxS site during cellular response to hydroxyurea
FYPO:0002644	decreased protein serine phosphorylation during vegetative growth
FYPO:0002645	decreased protein threonine phosphorylation during vegetative growth
FYPO:0002646	decreased protein serine phosphorylation during mitosis
FYPO:0002647	decreased protein threonine phosphorylation during mitosis
FYPO:0002982	abolished protein serine phosphorylation during vegetative growth
FYPO:0002983	abolished protein serine phosphorylation during cellular response to DNA damage
FYPO:0003140	decreased protein tyrosine phosphorylation during cellular response to heat
FYPO:0003141	decreased protein tyrosine phosphorylation during cellular response to hydrogen peroxide
FYPO:0003623	normal protein threonine phosphorylation
FYPO:0003623	normal protein threonine phosphorylation during cellular response to heat
FYPO:0003624	decreased protein threonine phosphorylation during cellular response to heat
FYPO:0003645	normal protein serine phosphorylation
FYPO:0003645	normal protein serine phosphorylation during vegetative growth
FYPO:0003951	increased protein tyrosine phosphorylation during cellular response to heat
FYPO:0004155	increased protein tyrosine phosphorylation during mitotic G1 phase
FYPO:0004258	decreased protein tyrosine phosphorylation during cellular response to hydroxyurea
FYPO:0004420	increased protein serine phosphorylation
FYPO:0004421	increased protein serine phosphorylation during nitrogen starvation
FYPO:0004659	abolished protein tyrosine phosphorylation during cellular response to UV
FYPO:0004660	abolished protein tyrosine phosphorylation during cellular response to methyl methanesulfonate
FYPO:0004661	normal protein tyrosine phosphorylation during vegetative growth
FYPO:0004664	increased duration of protein tyrosine phosphorylation during cellular response to salt stress
FYPO:0004788	increased protein serine phosphorylation during glucose starvation
FYPO:0004794	decreased protein phosphorylation at Ser/Thr-Pro site during vegetative growth
FYPO:0005007	normal protein serine phosphorylation at RxxS site during vegetative growth
FYPO:0005008	abolished protein serine phosphorylation at RxxS site during vegetative growth
FYPO:0005009	decreased protein serine phosphorylation at RxxS site during vegetative growth
FYPO:0005010	increased protein serine phosphorylation at RxxS site during nitrogen starvation
FYPO:0006143	delayed onset of protein tyrosine dephosphorylation during vegetative growth
FYPO:0006287	increased protein tyrosine phosphorylation during cellular response to hydroxyurea
FYPO:0006290	normal protein tyrosine phosphorylation during mitotic S phase during cellular response to hydroxyurea

**Comment by mah11** [comment]
meeting - Val says keep the pol II CTD ones.

**Comment by mah11** [comment]
oof. all done, I think. open a new ticket if you spot any I missed.

edit file: 10e913bec4587f0d13d8a796363bc6dd7e3778d4
release: f83a24425f2dadb270ef7d5e066f2619ca088e3e

**Comment by ValWood** [comment]
Great, thats a nice simplification and will  provide more consistent search results, I think....
