### ISSUE TITLE
PECO term + cerulenin PMID:30003614

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3336]
+ cerulenin

for 
PMID:30003614

**Comment by ValWood** [comment]
cerulenin, an inhibitor of β -keto-acyl ACP synthase and HMG -CoA synthase

should be in 'drug' list, I forget where this is

**Comment by Antonialock** [comment]
updated peco and the website.

website changes on github eg https://github.com/pombase/website/blob/master/frontend/src/docs/browse-curation/drugs-known-pombe-targets.md
