### ISSUE TITLE
PMID:29930085 polarity related

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3339]
FYPO:000NEW | normal protein localization to cell tip during mitotic interphase

descendant of 
FYPO:0001587 | normal protein localization to cell tip during vegetative growth

standard defs

**Comment by ValWood** [comment]
I have used

FYPO:0003390 | protein mislocalized to medial cortex during vegetative growth

to represent "PORTLI growth"

but think it would be better

FYPO:000NEW1| protein mislocalized throughout the cell cortex  from the cell tip  cortex during vegetative growth


FYPO:000NEW1| protein mislocalized throughout the cell cortex  from the medial  cortex during vegetative growth

with "PORTLI growth" as a synonym for both

**Comment by ValWood** [comment]
I think maybe we should have a term for this anyway

Accordingly, instead of growing in a polarized manner, MBC-treated cells became increasingly round over time (Fig. 2B,C). Although average growth in these cells appeared to be isotropic, because of the dynamic, nonuniform distribution of Bgs4 on the plasma membrane we will refer to this growth pattern as ‘polarity transience leading to isotropic-like’ (PORTLI) growth


So both of the mislocalizations above are a characteristic of PORTLI growth, but also the cells  lose polarity and are round

**Comment by ValWood** [comment]
NTR: normal cell width

**Comment by mah11** [comment]
I don't fully understand what new2 and new3 are supposed to mean. Can you recast them in a pattern modeled on FYPO:0006434? Swap things in for "decreased" and "medial cortical node" to get what you need:

id: FYPO:0006434
name: decreased protein localization to medial cortical node during vegetative growth, with protein distributed in cell cortex
def: "A cell phenotype observed in the vegetative growth phase of the life cycle in which the localization of a protein to the medial cortical node of a cell is decreased, and the protein is instead detected distributed throughout the cell cortex. There may be little or no protein detected at the medial cortical node." [PomBase:mah]

And does your next-to-last comment mean you want a separate term for PORTLI growth? I can do it with has_part new2 and has_part new3.

**Comment by mah11** [comment]
OK, thanks. I'll put your suggested names in as synonyms.

**Comment by ValWood** [comment]
they probably aren't required. I  should have checked the convention...
as long as they have 'mislocalized' parent they will be findable....

**Comment by ValWood** [comment]
When you are next FYPO ing could you do this one first. Ken's session has been waiting quite a while, and I was sooo pleased he participated (first time!)

**Comment by mah11** [comment]
normal protein localization to cell tip during mitotic interphase FYPO:0006635
  mislocalized protein distributed in cell cortex FYPO:0006636
  decreased protein localization to cell cortex of cell tip, with protein distributed in cortex FYPO:0006637
  decreased protein localization to medial cortex during vegetative growth, with protein distributed in cell cortex FYPO:0006638
  normal vegetative cell diameter FYPO:0006639

edit file: 47ad3a835a58e6c143b7c8f204006ebf4f8b7789
release: 81e41b8f7725fd2c5603f84cb1d9faa9007dcb91
