### ISSUE TITLE
PMID:29975113 dma1 checkpoint paper

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3340]
abnormal protein localization to mitotic spindle pole body during anaphase B
desc of
FYPO:0000939  abnormal protein localization to mitotic spindle pole body

 normal temporal protein localization
desc of
FYPO:0003627  normal protein localization

(I don't want to recapitulate all of the multiple  places that it is normal over time)

**Comment by mah11** [comment]
> normal temporal protein localization

Does this mean you want a "normal" term analogous to FYPO:0006606 ! abnormal temporal protein localization pattern?

**Comment by ValWood** [comment]
yes, if that means that the protein localizes normally to multiple places ovr time.

However, 
normal temporal protein localization
has a number of descendants:
https://www.pombase.org/term/FYPO:0006606

but probably many others can go under here.

I didn't really understand why
decreased protein localization to heterochromatin at centromere outer repeat
was under here?

and 
abnormal protein localization to mitotic spindle pole body during anaphase B
could be...

Most proteins are temporally localized.... I thought about it for a minute or two and then I parked it.

**Comment by mah11** [comment]
> > > normal temporal protein localization
> > > 
> > Does this mean you want a "normal" term analogous to FYPO:0006606 ! abnormal temporal protein localization pattern?
> > 
> yes, if that means that the protein localizes normally to multiple places over time.

Well, sort of, but for the abnormal term I've interpreted it specifically as meaning that a dynamic pattern of localization to one place is assessed over time and found to differ from wild type (so I wouldn't just use it to group anything with "localization to x during y").

I'll try to make that clearer in the text def.

> [FYPO:0006606] has a number of descendants: ..
> I didn't really understand why decreased protein localization to heterochromatin at centromere outer repeat was under here?

Not asserted; inferred by the reasoner for (erm) reasons that I don't see at a quick glance. Either I've botched a logical def (which would be easy to fix) or there's some connection in PATO that leads to inferences that I didn't intend (might be harder, or at least slower, to fix).

The only things I asserted to be is_a FYPO:0006606 are:

FYPO:0006188 decreased rate of protein exchange in actomyosin contractile ring
FYPO:0006359 decreased protein exchange at pericentric heterochromatin
FYPO:0006360 increased protein exchange at pericentric heterochromatin
FYPO:0006370 decreased protein exchange at subtelomeric heterochromatin
FYPO:0006607 abnormal intermittent protein localization to Cdr2 medial cortical node complex

I'll have a closer look next week.

**Comment by ValWood** [comment]
OK got it. If you make the def clearer for the dynamic part.

I'll   just put normal protein localization  for dma1

**Comment by mah11** [comment]
note to self: oddball inferences due to pato:57  is_a pato:2323, but that's  probably ok, so work around it in fypo

**Comment by mah11** [comment]
new term
  abnormal protein localization to mitotic spindle pole body during anaphase B FYPO:0006640

renamed FYPO:0006606, edited text def, deleted xp

edit file: 47ad3a835a58e6c143b7c8f204006ebf4f8b7789
release: 81e41b8f7725fd2c5603f84cb1d9faa9007dcb91
