### ISSUE TITLE
loss of mitotic competence upon recovery from G0

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3346]
I need a term to describe "mitotic competence" after quiescence.

Yanagida used the available:
FYPO:0001178 | loss of viability upon nitrogen starvation

but this isn't quite specific enough because cells can lose competence on entry into G0, or be unable to maintain G0. These cells can't exit G0 and restart mitosis.

Any suggestions?

(not to self Also check: However, in a previous study, we identified 164 strains from a temperature-sensitive mutant library containing point mutations defective in MC maintenance under −N (24).
24. K. Sajiki, M. Hatanaka, T. Nakamura, K. Takeda, M. Shimanuki, T. Yoshida, Y. Hanyu, T. Hayashi, Y. Nakaseko, M. Yanagida, Genetic control of cellular quiescence in S. pombe. J. Cell. Sci. 122, 1418–1429 (2009).

**Comment by ValWood** [comment]
Ah actually 
FYPO:0001178 | loss of viability upon nitrogen starvation
has a child
loss of viability in G0
so we just need
loss of viability during exit from G0?
synonym "loss of mitotic competence  during exit from quiescence?"

PMID:30116786

**Comment by ValWood** [comment]
previous paper uses
FYPO:0001001 | abnormal cell cycle arrest in mitotic G2 phase during nitrogen starvation

and

FYPO:0001178 | loss of viability upon nitrogen starvation

**Comment by mah11** [comment]
Look for the terms with "G0 to G1 transition", and let me know if you still need any new. We have

id: FYPO:0000238
name: inviable cell upon G0 to G1 transition
def: "A cell phenotype in which a cell fails to resume growth after several days in G0 phase. The inviable cells show some features characteristic of apoptosis, including loss of DNA." [PMID:19197239, PomBase:mah]
synonym: "die in G0 with an apoptotic-like phenotype" RELATED [PomBase:mah]
synonym: "lethal in cell upon G0 to G1 transition" EXACT [PomBase:mah]
is_a: FYPO:0000049 ! inviable cell

... but it would probably help to give it more synonyms.

**Comment by mah11** [comment]
Also, "loss of viability upon G0 to G1 transition" is a RELATED synonym for FYPO:0006518 loss of viability in G0. The term was added for #3285, but there's not really anything there about why we didn't create a separate term. I suspect it was because I couldn't think of how one would tell the difference, so if the current paper can make the distinction I can just remove that synonym.

**Comment by ValWood** [comment]
Could these be descendant of
FYPO:0001178 | loss of viability upon nitrogen starvation
(this is the term Yanagida used, since quiescence is a response to nitrogen starvation).

**Comment by mah11** [comment]
difference between FYPO:0000238 and a new "loss of viability upon G0 to G1 transition" would be cell vs. population

**Comment by ValWood** [comment]
Ah right, I will make the concurrent cell level annotations....

**Comment by ValWood** [comment]
So doe this sound OK?

population
NTR :  loss of viability upon G0 to G1 transition
child of
FYPO:0001178 | loss of viability upon nitrogen starvation

 cell level term exists
FYPO:0000238
name: inviable cell upon G0 to G1 transition

add
abolished mitotic competence (synonym)
and any quiescence related synonyms


(since anything annotated to " loss of viability upon G0 to G1 transition" could also be annotated to FYPO:0000238 maybe add a comment to promte concurrent annotation?)

**Comment by mah11** [comment]
Yep, that all sounds fine.

**Comment by mah11** [comment]
done; new term is
loss of viability upon G0 to G1 transition FYPO:0006660

edit file: e7bb5e5c8f6d4e493219c8bcd1e8ef25519ee4c4
release: 3b40a7f273d9a43481e34847830e468eb71ef8b8

**Comment by ValWood** [comment]
can
loss of mitotic competence
be added as some sort of synonym?

**Comment by mah11** [comment]
you mean like the three that were included when I added FYPO:0006660?
