### ISSUE TITLE
lipid particles vs lipid droplets

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3347]
We use lipid droplets elsewhere (and I think GO settled on droplets as the preferred label)

FYPO:0002552 | lipid particles present in decreased numbers

swap, add etc

**Comment by mah11** [comment]
all done

edit file: e7bb5e5c8f6d4e493219c8bcd1e8ef25519ee4c4
release: 3b40a7f273d9a43481e34847830e468eb71ef8b8
