### ISSUE TITLE
vacuolated nucleus in G0, and other nuclear morphology in quiescence

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3348]
Descendent of "fragmented nuclei in G0"

![vacuolated nuclei](https://user-images.githubusercontent.com/7359272/44706999-44757000-aa9b-11e8-814b-9475b153301e.jpg)

PMID:30116786

**Comment by ValWood** [comment]
Ah it is probably nucelophagy, got it!


![dna contient](https://user-images.githubusercontent.com/7359272/44709252-0f6c1c00-aaa1-11e8-9e1c-1fc04e705d58.jpg)

How would I describe this.?

**Comment by ValWood** [comment]
"Actually, in nem1, FACS analysis indicated nuclear degradation within 3 days after −N (Fig. 4B),"

**Comment by ValWood** [comment]
So the authors call the phenotype of 4B "degraded nucleus"

**Comment by ValWood** [comment]
NTR elongated nucleus during quiesence

FYPO:0000832 | elongated nucleus

**Comment by mah11** [comment]
> vacuolated nucleus in G0

Are any of those vacuoles really within the nucleus? I don't think I can tell from the images.

If (some of) the vacuoles are in the nucleus, I'll have to ping PATO about their definition for "vacuolated" - at present it's "A structural quality inhering in a cytoplasm that contains fluid filled cavities."

> Descendent of "fragmented nuclei in G0"

There is no such term. Do you want a new term?

Even if I add "fragmented nucleus in G0", it would not make sense as a parent of a "vacuolated nucleus" term. "Vacuolated" means "contains vacuoles", nothing more.

**Comment by mah11** [comment]
> NTR degraded nucleus in G0

Is this the same as "fragmented nucleus in G0"? If not, what's the difference?

Would it make more sense to use a process phenotype such as "increased nucleophagy during G0" (could point to GO:0044804)?

**Comment by mah11** [comment]
> although degraded appears stronger than fragmented? fragmented would imply broken up, degraded implies catabolised? maybe?

Well, I think I get what you mean, but an ontology needs clear, preferably clean-cut, definitions, and I'm a little worried that people use words like "degraded" in papers with less than ontological precision. So I'm trying to look at the data as well, and I think what the micrographs show is consistent with "fragmented" for the nucleus. They don't really say "degraded" until they bring in the FACS data, and if we're going to interpret a bunch of observations together, we might as well also pay attention to the suppression data that point to nuclear autophagy ... and use the process phenotype term.

**Comment by ValWood** [comment]
OK process phenotype it is.

**Comment by mah11** [comment]
new terms
  fragmented nucleus FYPO:0006661
  fragmented nucleus during G0 phase FYPO:0006662
  elongated nucleus FYPO:0006663
  elongated nucleus during G0 phase FYPO:0006664
  increased nucleophagy during G0 phase FYPO:0006665
renamed FYPO:0000832 & FYPO:0001919 to make 'vegetative' explicit

edit file: e7bb5e5c8f6d4e493219c8bcd1e8ef25519ee4c4
release: 3b40a7f273d9a43481e34847830e468eb71ef8b8
