### ISSUE TITLE
NTR abnormal and normal nuclear morphology during G0

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3351]
To complete PMID:30116786

Should 

FYPO:0006664 | elongated nucleus during G0 phase |
FYPO:0006662 | fragmented nucleus during G0 phase

be under normal...?

**Comment by mah11** [comment]
I may not understand the question here:

> Should
> 
> FYPO:0006664 | elongated nucleus during G0 phase |
> FYPO:0006662 | fragmented nucleus during G0 phase
> 
> be under normal...?

... but the terms don't sound like they describe normal phenotypes. The definitions refer to differences from normal (i.e. not the same as wild type cells in G0).

**Comment by ValWood** [comment]
I think I meant under "abnormal nuclear morphology  during G0...checking now...

**Comment by ValWood** [comment]
hmm, not sure what I was on about here.....

**Comment by mah11** [comment]
Do you still want these new terms?

- abnormal nuclear morphology during G0
- normal nuclear morphology during G0

**Comment by ValWood** [comment]
Yes let's have them, even searching just now I thought it would be useful to have these grouped because they are so connected.

**Comment by mah11** [comment]
abnormal nuclear morphology during G0 phase FYPO:0006667
  normal nuclear morphology during G0 phase FYPO:0006668

edit file: 2c423eb2922613003cf7a6909839bb41dbb07b66
release: 5616200d6d9c4f6cde6f1e2a0fa3a21fd2127b71
