### ISSUE TITLE
PMID:11781565 ntr

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3353]
PMID:11781565

decreased transcription in response to HU

**Comment by mah11** [comment]
decreased transcription during cellular response to hydroxyurea FYPO:0006676

edit file: 9d0ba8f64502212e143e97742ca9bfcfd171b866
release: 5d0908432606c9998efa8d4332cd6b097ec891b6

**Comment by ValWood** [comment]
also needed normal and increase , sorry!

**Comment by mah11** [comment]
increased transcription during cellular response to hydroxyurea FYPO:0006761
  normal transcription during cellular response to hydroxyurea FYPO:000676

edit file: 00e509bd70509dd88ee61010d918c0b9dc3dee72
release: 80c06eec00bc8aea8a7296792335cd6611cf9a2a
