### ISSUE TITLE
decreased double-stranded DNA break binding

### ISSUE THREAD

**Issue by mah11** [pombase/fypo#3354]
for rad50 mutants in PMID:30104346

Note for future reference: the evidence in this paper is ChIP, which GO wouldn't trust by itself to support a DNA binding annotation, but there's respectable evidence that Rad50 orthologs bind DNA, and PR interprets the results as reflecting DNA binding, so I decided to allow this and the GO MF annotations in the session.

**Comment by ValWood** [comment]
yep, especially since it needs to bind DNA to do what it does....

**Comment by ValWood** [comment]
odd that rad50 mre11 complex is only ISS, I thought it had been studied loads...

**Comment by mah11** [comment]
decreased DNA binding at double-strand break FYPO:0006677

edit file: 9d0ba8f64502212e143e97742ca9bfcfd171b866
release: 5d0908432606c9998efa8d4332cd6b097ec891b6
