### ISSUE TITLE
ntr abolished GO:0005388

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3363]
abolished
GO:0005388 | calcium-transporting ATPase activity

child of
FYPO:0002117 | abolished transporter activity

standard def

PMID:22132152

**Comment by ValWood** [comment]
decreased
GO:1903515 | calcium ion transport from cytosol to endoplasmic reticulum

**Comment by mah11** [comment]
abolished calcium-transporting ATPase activity FYPO:0006706
  decreased calcium ion transport from cytosol to endoplasmic reticulum FYPO:0006707

edit file: 613c0446447ecd0ab75228b25a497ff8213af657
release: 314bbaa4d10de03dbbc71b4ede8e3ccbfdeed9bd
