### ISSUE TITLE
missing parent, merotelic attachment

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3374]
meroterically attached lagging mitotic chromosomes (FYPO:0004382)

should be a child of
merotelic kinetochore attachment during mitosis (FYPO:0004381)

**Comment by mah11** [comment]
there is a link:

id: FYPO:0004382
name: meroterically attached lagging mitotic chromosomes
relationship: has_part FYPO:0000228 ! lagging mitotic chromosomes
relationship: has_part FYPO:0004381 ! merotelic kinetochore attachment during mitosis

**Comment by ValWood** [comment]
Is this another example of this morning discussion

**Comment by mah11** [comment]
previous comment refers to #3408 and https://github.com/pombase/website/issues/675

**Comment by ValWood** [comment]
seems OK
https://www.pombase.org/term/FYPO:0004381
