### ISSUE TITLE
rename: (FYPO:0005634)

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3375]
abnormal chromosome segregation during meiosis I with premature sister kinetochore separation and equational sister chromatid separation
to

equational sister chromatid separation in meiosis I

I think the fact that the kinetochores separate early is a given, the phenotype is usually described  just as

equational sister chromatid separation in meiosis I

and the def clarifies anyway

**Comment by mah11** [comment]
done; kept old name as exact synonym

edit file: 024ce4890acf3f5f26e9ccd7525e95f8aacb0d26
release: c38c34e27020529fbfe08feb17b8451ebf4cfbda
