### ISSUE TITLE
misc cytokinesis

### ISSUE THREAD

**Issue by mah11** [pombase/fypo#3397]
1. inviable branched, swollen vegetative cell
2. abolished protein localization to actin cortical patch, with protein mislocalized to nucleus
3. abolished protein localization to actin cortical patch, with protein mislocalized to cytoplasm
4. delayed onset of cell separation after cytokinesis

1-3 PMID:11076964, 4 PMID:16864655

**Comment by ValWood** [comment]
which fig is this one:
- inviable branched, swollen vegetative cell
(I thought the branched  inviable phenotype occurred was necessarily multiseptate and elongated...but I couldn't see any branching in the figs...)

...unless they are "T" shaped (but that isn't a cytokinesis defect, and is viable)

**Comment by ValWood** [comment]
got it....yep, I don't think we have previously identified these as "branched" but I can see they are trying to branch (they are probably the ones that got pooled in misshapen inviable, but  Jacky said looked like a potato!)

**Comment by mah11** [comment]
yeah, I couldn't tell from the pic whether the poster-child cell was elongated or septated; new term is neutral w.r.t. both features to play it safe

**Comment by mah11** [comment]
inviable branched, swollen vegetative cell FYPO:0006794
  abolished protein localization to actin cortical patch, with protein mislocalized to nucleus FYPO:0006795
  abolished protein localization to actin cortical patch, with protein mislocalized to cytoplasm FYPO:0006796
  delayed onset of cell separation after cytokinesis FYPO:0006797

edit file: 7f2d16e4ed45ac80b176a33ac6ab4a8678e08b44
release: 0fc00696a9019019ef398758b4d662feed919770
