### ISSUE TITLE
word missing

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3398]
sporulation resulting in formation of ascus with than four spores

(fewer)

**Comment by ValWood** [comment]
alao has parent
normal cellular process

**Comment by ValWood** [comment]
ok this happens normally at low level, is that why this is normal?

Because we also have:
abnormal sporulation resulting in formation of ascus with more than four spores (FYPO:0003263)

**Comment by mah11** [comment]
Hmm. Extra word, not missing - this term was added for #3028 & #3036, but from the tickets and the comment on the term I think it should have gone under abnormal sporulation. Moved, and name corrected.

edit file: 7f2d16e4ed45ac80b176a33ac6ab4a8678e08b44
release: 0fc00696a9019019ef398758b4d662feed919770
