### ISSUE TITLE
PMID:29180432 nuclear MIS12/MIND complex binding

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3399]
normal and ~abnormal~ abolished
GO:0000818 | nuclear MIS12/MIND complex
binding

(I know this one should have been sent out for CC  but I had sorted it with the structure papers as I thought it would be a quick one)

**Comment by mah11** [comment]
normal nuclear MIS12/MIND complex binding FYPO:0006798
  abolished nuclear MIS12/MIND complex binding FYPO:0006799

edit file: 4f20d530a9200c7de2f71b77100a57f8bdeb76a6
release: 198251df4ecf1ed5dc0310ed75ee9d7f11a3c1f9
