### ISSUE TITLE
lagging chromosomes query

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3400]
FYPO:0000228 | lagging mitotic chromosomes

I wonder if this should be "increased number of..."
(since WT has 6%)

**Comment by mah11** [comment]
I'd say, just annotate the penentrance if you're worried ... putting "number of" in the term name would make it sound like more chromosomes per cell lag (or even more chromosomes at all! if a non-fission-yeast person happened to see it), whereas that 6% must be percent of wt cells that have any chromosomes lag.

**Comment by mah11** [comment]
We haven't done this for any of the other things that crop up at low frequency in wild type (the question has come up before, especially w.r.t. sporulation, e.g. #1904). And one can argue that it isn't "normal" for chromosomes to lag, even if the abnormality isn't absolutely completely absent in wt.

**Comment by ValWood** [comment]
OK.
