### ISSUE TITLE
PMID:29180432 centromere declustering

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3401]
child of 
FYPO:0001779 | abnormal centromere clustering at nuclear periphery

whatever you think best to call it, but with synonym
"centromere declustering" which is how they call it in the paper.

**Comment by mah11** [comment]
decreased centromere clustering at nuclear periphery during mitosis FYPO:0006800
(don't worry, it's got the synonym ... and a ton of others)

edit file: 4f20d530a9200c7de2f71b77100a57f8bdeb76a6
release: 198251df4ecf1ed5dc0310ed75ee9d7f11a3c1f9
