### ISSUE TITLE
cut

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3402]
I see

abnormal cell separation after cytokinesis, with abnormal nuclear division

as a descendant of cut, but it should be an ancestor?

**Comment by ValWood** [comment]
also 
"cut with abnormal chromosome segregation"

cut FYPO:0000229 is defined as abnormal chromosome segregation (with cytokinesis)

**Comment by mah11** [comment]
> abnormal cell separation after cytokinesis, with abnormal nuclear division
> 
> as a descendant of cut, but it should be an ancestor?

The link in the ontology is

FYPO:0001973 ! abnormal cell separation after cytokinesis, with abnormal nuclear division has_part FYPO:0000229 ! cut

This looks correct to me - FYPO:0001973 represents the combination of the nuclear division problems of "cut" plus a problem with cell separation after cytokinesis. "Cut" by itself doesn't say anything about whether cells try to separate after the nuclear-division-gone-wrong, nor whether a separation attempt succeeds.

> also
> "cut with abnormal chromosome segregation"

For this one, we decided in the big "mitotic catastrophe" overhaul in #3173 that FYPO:0003165 was supposed to represent the combination "cut with mitotic catastrophe". I don't remember why we didn't also decide to use that as the term name, but I can change it next time I'm in a FYPO zone (maybe tomorrow).

**Comment by ValWood** [comment]
OK something is a bit odd here.

At least I don't think 
abnormal cell separation after cytokinesis, with abnormal nuclear division is even a TYPE of cut.

Cut is
abnormal cytokinesis, with abnormal nuclear division

I don't  know what the 
"abnormal cell separation after cytokinesis, with abnormal nuclear division" is about now.
Will check the annotations...

**Comment by ValWood** [comment]
OK only 1 annotation, and APC annotation, this should just be 'cut' so I changed it. That means we can obsolete
"abnormal cell separation after cytokinesis, with abnormal nuclear division"

**Comment by mah11** [comment]
> At least I don't think
> abnormal cell separation after cytokinesis, with abnormal nuclear division is even a TYPE of cut.

It isn't a type of cut in the ontology - there is no is_a link between the terms. That's what the is_a relation means.

FYPO:0001973 would be used for a cell that has both cut (nuclear division problem) AND a problem with cell separation after (attempting) cytokinesis. If there are no such cells, then yes, we can obsolete the term. But there are four annotations to it, not one, from 3 different papers (3 are multi-allele). Could you check the others before I ax the term?

**Comment by ValWood** [comment]
but
I see

abnormal cell separation after cytokinesis, with abnormal nuclear division

as a descendant of cut in Canto, hence my question?

**Comment by mah11** [comment]
Then it's really a question about how Canto handles has_part links. Canto doesn't show any relationship types (and we've gone back and forth on whether it should).

**Comment by ValWood** [comment]
and when I do a query, I only see one annotation 
nuc2	SPAC17C9.01c	anaphase-promoting complex TPR lobe subcomplex subunit Apc3
(which i fixed yesterday)

**Comment by mah11** [comment]
snap, I was just typing up basically the same thing. I don't really mind whether you do or don't want to have a term for the combination of (abnormal septum digestion + cut), but that's what FYPO:0001973 is - it does NOT claim that abnormal septum digestion is a part or type of cut, nor vice versa; it's for a cell that happens to have both problems.

**Comment by ValWood** [comment]
OK all fixed (were cuts), except for this one:
https://curation.pombase.org/pombe/curs/9442751303a5f327/ro

where I had added a comment
fig 3 cells fail to separate and are clumped together, multiple rounds of nuclear division

so this  *is a cell separation defect*.

I think here, the multiple rounds of division is "irrelevant" (it isn't abnormal division, it's continued cell cycling normally in the absence of complete separation). So I'll move this to *only* a cell sepration defect and you can obsolete.

**Comment by ValWood** [comment]
but
FYPO:0001973 

isn't for a cell which has both cut  *and* cell separation defects. Cut requires a *cytokinesis* defect and this is not specified in this term...

The terms are overlapping but cannot be related.

Again, abnormal cell separation *after* cytokinesis is not part_of cytokinesis

**Comment by mah11** [comment]
> FYPO:0001973
> 
> isn't for a cell which has both cut and cell separation defects.

YES IT IS. That is how it is defined by its text definition and relationships to other terms. 

> Cut requires a cytokinesis defect and this is not specified in this term...

Actually, it *is* specified for this term by virtue of its link *has_part cut*. That includes the parts of cut itself, i.e. the cytokinesis problem and the chromosome segregation problem, i.e.:

FYPO:00001973 = cut + cell separation defect = (cytokinesis defect + abnormal chromosome segregation) + cell separation defect

> Again, abnormal cell separation after cytokinesis is not part_of cytokinesis

WHERE HAVE I SAID OTHERWISE? I have understood this all along. As it is currently defined, FYPO:0001973 does not contradict this.

Whether we *need* the term after all is a separate question, the answer to which depends on (a) whether any such cells exist (if not, don't need the term), and (b) if there are any such cells, whether we think it's worth having a term just for them (I have no preference).

**Comment by ValWood** [comment]
Ah got it. The term name does not match the textual definition.

We can safely obsolete this.  It's  never a required term. At least the cells are arrested  before correct division , so cell separation isn't even an opition. The term, as defined wouldn't make sense biologically....

**Comment by mah11** [comment]
obsoletion done

edit file: 4f20d530a9200c7de2f71b77100a57f8bdeb76a6
release: 198251df4ecf1ed5dc0310ed75ee9d7f11a3c1f9
