### ISSUE TITLE
ntr: mitotic spindle abnormalities

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3403]
1.
multiple mitotic spindle pole bodies/ overreplicated mitotic spindle pole bodies
descendant of
FYPO:0001791 | abnormal mitotic spindle pole body duplication

2.
FYPO:0003568 | abnormal establishment of mitotic spindle pole body localization to nuclear envelope, with spindle pole body in nucleoplasm

aka "unanchored spindle pole bodies"  (might be a better primary term name?)

**Comment by ValWood** [comment]
3. Also add "fan-shaped" spindle as synonym for monopolar spindle

**Comment by mah11** [comment]
> multiple mitotic spindle pole bodies/ overreplicated mitotic spindel pole bodues
> descendant of
> FYPO:0001791 | abnormal mitotic spindle pole body duplication

this link would have to be output_of

**Comment by ValWood** [comment]
why output_of and not is_a?

(I probably don't really understand what "output of" means)

**Comment by mah11** [comment]
Because "too many SPBs" is a structure phenotype, and "abnormal SPB duplication" is a process phenotype. is_a can only link structure phenotype to structure phenotype or process phenotype to process phenotype.

**Comment by ValWood** [comment]
Oh yes I always forget this!

**Comment by mah11** [comment]
new term
  spindle pole bodies present in increased numbers during vegetative growth FYPO:0006801
renamed FYPO:0003568 to 'spindle pole body unanchored to nuclear envelope' (kept old name as exact synonym)
synonyms FYPO:0000276, FYPO:0006363

edit file: 4f20d530a9200c7de2f71b77100a57f8bdeb76a6
release: 198251df4ecf1ed5dc0310ed75ee9d7f11a3c1f9
