### ISSUE TITLE
ntr unstable actomyosin ring 	PMID:9786952

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3404]
child of
FYPO:0004736 | abnormal actomyosin contractile ring

forms normally, disappears during contraction

**Comment by ValWood** [comment]
also
dispersed actin  localization during vegetative growth

ancestor of
FYPO:0002021 | dispersed actin cortical patch localization during vegetative growth

**Comment by mah11** [comment]
> unstable actomyosin ring

Is this the same as FYPO:0001904 premature actomyosin contractile ring disassembly? If it is, I'll add synonyms. If not, can you specify what's different, so I can put info in both existing and new term defs?

> dispersed actin localization during vegetative growth
> 
> ancestor of
> FYPO:0002021 | dispersed actin cortical patch localization during vegetative growth

The new term is no problem, but I would not link it to FYPO:0002021. Patches contain actin that is not dispersed, so scattering the patches all over the cell surface doesn't disperse the actin in them.

**Comment by ValWood** [comment]
-unstable actomyosin ring

It's the same. I also made this annotation later....

**Comment by mah11** [comment]
new term
  dispersed filamentous actin FYPO:0006802
synonyms FYPO:0001904

edit file: 4f20d530a9200c7de2f71b77100a57f8bdeb76a6
release: 198251df4ecf1ed5dc0310ed75ee9d7f11a3c1f9

**Comment by ValWood** [comment]
should FYPO:0001904 be a child of abnormal actinomyosin ring?

**Comment by mah11** [comment]
update: link added in the above commit; will be visible next time I do a FYPO release, but unless this link is urgent I'll wait for the next batch of edits
