### ISSUE TITLE
ntr decreased galactosyltransferase activity

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3406]
PMID:9839953

standard def

**Comment by ValWood** [comment]
and
cell wall galactose decreased.

we have

FYPO:0002629 | galactose absent from cell wall





Both gmh3∆ and gma12∆ cells had less galactose in their cell surfaces than wild-type cells. More- over, the galactose content in the cell surface of gmh3∆ gma12∆ double mutant cells was lower than that of single mutants, sug- gesting an additive effect on cell surface galactosylation by the disruption of gmh3􏰀 and gma12􏰀 genes.

**Comment by ValWood** [comment]
actually its 
decreased cell surface galactose
(they go on to show a cell surface protein has less galactose)

**Comment by mah11** [comment]
do you think you could use FYPO:0003354? or should I add a child for "cell surface glycoprotein glycan"?

id: FYPO:0003354
name: decreased galactose level in glycoprotein glycan
def: "A phenotype in which the glycan moiety of a glycoprotein contains a lower amount of galactose residues than normal. In wild-type cells, glycoprotein glycans contain mannose and galactose residues in a 1:1.2 ratio, and the galactose residues are connected by alpha-1,2 linkages." [PMID:8782411, PomBase:mah]
[snip synonyms]
is_a: FYPO:0003290 ! abnormal glycoprotein glycan structure

**Comment by ValWood** [comment]
I think I could use this.

Should 
cell wall galactose decreased.
be a descendant of this term?

**Comment by mah11** [comment]
I don't think so, unless there are no galactose residues in the cell wall carbohydrates. Otherwise decreased galactose in the cell wall could be due to decreased gal in the polysaccharides, the glycoprotein glycans, or both.

**Comment by mah11** [comment]
abnormal galactosyltransferase activity FYPO:0006805
  decreased galactosyltransferase activity FYPO:0006806
  decreased galactose level in cell surface glycoprotein glycan FYPO:0006807

edit file: 5313b888754fee0ea183d129ac9f44e7d3f4c443
release: f267e8cda31a663837bfaf4ff55bbb069c0014a5
