### ISSUE TITLE
PMID:12479804 SPB

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3413]
premature protein localization to mitotic spindle pole body
abolished protein localization to mitotic spindle pole body during M-phase (slot inbetween existing)

**Comment by mah11** [comment]
premature protein localization to mitotic spindle pole body FYPO:0006824
  abolished protein localization to mitotic spindle pole body during mitosis FYPO:0006825

edit file: 64d9f12ae1eab54159a520b37ace4bb79f55b7cc
release: 4faa0186ac4092ea41fe1d9dca5ae9b4c6cf43fc
