### ISSUE TITLE
spindle assembly phenotype

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3415]
In https://github.com/pombase/curation/issues/1104
I have a note
" In the temperature-sensitive cut7 mutant, spindle formation is blocked shortly after duplication of the SPB."

The phenotype is "monopolar mitotic spindle"
but this isn't related to "spindle assembly"

Can it be (has output?)

**Comment by mah11** [comment]
I've added a link further 'upstream' (abnormal mitotic spindle midzone assembly is_a abnormal mitotic spindle assembly). If that _doesn't_ give you what you want in Canto or search results, reopen this.

edit file: 2cee80ade936e950c6425d0da91f425e8892866f
release: ca1830f802e83aabaa889b648dfe24c79338defa

**Comment by ValWood** [comment]
Well....I don't see cut7 yet, but is this because  has_output are not followed yet? I forget where we are up to!

**Comment by mah11** [comment]
Where are you looking? I now see monopolar mitotic spindle (FYPO:0000276) on the term page for abnormal mitotic spindle assembly (FYPO:0000177) .

**Comment by ValWood** [comment]
yes abnormal spindle assembly went up from 17 yesterday to 42 today. I don't think there was an update the day before.
