### ISSUE TITLE
NTR:Decreased cytosolic zinc ion level

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3417]
Decreased cytosolic zinc ion level
A cell phenotype observed in the vegetative growth phase of the life cycle in which the amount of zinc ion measured in the cytosol is lower than normal.

PMID:29529046

**Comment by ValWood** [comment]
...and increased

**Comment by mah11** [comment]
oh yeah, added these on wednesday but forgot to close ticket

  decreased cytosolic zinc level FYPO:0006827
  increased cytosolic zinc level FYPO:0006828
  normal RNA level during cellular response to zinc ion starvation FYPO:0006829
  normal RNA level during cellular response to replete zinc FYPO:0006830

edit file: 740ab82b50b3f94be1d4093aec3a9049ff2d9fd7
release: 4d3b75d264111b5afbb884fef54708a056ef0f1c
