### ISSUE TITLE
normal glucan endo-1,3-beta-glucanase activity

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#3421]
normal glucan endo-1,3-beta-glucanase activity
8505375

**Comment by mah11** [comment]
committed; will release when server back up:
normal glucan endo-1,3-beta-glucanase activity FYPO:0006835

**Comment by mah11** [comment]
edit file: 1094e72351ab7067a0f6a261d9cac5f2a23c84d6
release: b3228c9abdca998c5af995bd7e55444c52b8b971
