### ISSUE TITLE
one more for 30640914

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#3428]
decreased duration of meiotic S phase
cdc2-asM17

**Comment by mah11** [comment]
included a grouping term too

  decreased duration of meiotic cell cycle phase FYPO:0006851
  decreased duration of meiotic S phase FYPO:0006852

edit file: 771ddc6a790a6ebe6b86dea23a41583aca8b0b1c
release: 9cb110e7652dad44b54e9ba751cb393db4b03d13
