### ISSUE TITLE
increased and decreased H3K37 methylation PMID: 30773398

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3429]
increased and decreased H3K37 methylation 
PMID: 30773398

standard def

**Comment by ValWood** [comment]
GO:0062122 | histone methyltransferase activity (H3-K37 specific)
-- | --

**Comment by ValWood** [comment]
+ abolished

(I dont want 'vegetative' though), but maybe we don't need to specify this for activities?

**Comment by mah11** [comment]
> (I dont want 'vegetative' though), but maybe we don't need to specify this for activities?

But you have requested a process phenotype here. Do you want MF (increased|decreased|abolished activity) terms referring to GO:0052122, BP methylation terms, or both?

**Comment by ValWood** [comment]
I need
increased and decreased H3K37 methylation
but I didn't really want to say " during vegetative growth.... "
Although I guess I *could*

**Comment by mah11** [comment]
No problem to add phase-neutral BP phenotype terms. I just wanted to clarify what you actually wanted, since the GO term above is MF.

**Comment by mah11** [comment]
abnormal histone H3-K37 methylation FYPO:0006855
  increased histone H3-K37 methylation FYPO:0006856
  decreased histone H3-K37 methylation FYPO:0006857
  abolished histone H3-K37 methylation FYPO:0006858

edit file: 771ddc6a790a6ebe6b86dea23a41583aca8b0b1c
release: 9cb110e7652dad44b54e9ba751cb393db4b03d13

**Comment by ValWood** [comment]
I don't see
abolished histone H3-K37 methylation FYPO:0006858
under abnormal?

**Comment by mah11** [comment]
> I don't see
> abolished histone H3-K37 methylation FYPO:0006858
> under abnormal?

abnormal what? FYPO:0006858 is_a FYPO:0006855 !  abnormal histone H3-K37 methylation is asserted directly in the ontology

**Comment by ValWood** [comment]
from abolished histone methylation I could not see these....

**Comment by ValWood** [comment]
oh maybe I was under vegetative, ignore

**Comment by mah11** [comment]
Yep, the previously existing histone methylation terms are mostly vegetative (maybe all ... other generic ones might be acetylation ... I'd have to look).
