### ISSUE TITLE
NTR PMID:30853434 increased protein localization to medial cortex during during mitotic M-phase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3430]
increased protein localization to medial cortex during mitotic ~M-phase~ telophase

descendant of
FYPO:0001677 | increased protein localization to medial cortex during vegetative growth

standard def

ref PMID:30853434

(this session was rather exceptionally fabulous! I only needed to add  one phenotype annotation and some GO annotation, and deepen the small and elongated to indicate 'wee' and long at division....)

**Comment by ValWood** [comment]
check out the detail!
curs/de3fe5786898e2f8

**Comment by ValWood** [comment]
All the extensions on modifications and phenotypes don by Alaina.

**Comment by mah11** [comment]
increased protein localization to medial cortex during mitotic telophase FYPO:0006853

edit file: 771ddc6a790a6ebe6b86dea23a41583aca8b0b1c
release: 9cb110e7652dad44b54e9ba751cb393db4b03d13
