### ISSUE TITLE
ntr: abolished histone H3-K36 methylation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3440]
abolished histone H3-K36 methylation 
(non vegetative term)
https://www.pombase.org/reference/PMID:30773398

**Comment by mah11** [comment]
included another grouping term
  abolished histone H3-K36 methylation FYPO:0006869
  abnormal histone methylation FYPO:0006870

edit file: 01395f5f57543ab4fa25ab90630158a963daf505
release: 6a27a43c29768356dcf4af581cabcd42c7b17158
