### ISSUE TITLE
NTR abnormal protein localization to cell division site descendant

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3445]
NTR abnormal protein localization to cell division site, protein concentrated at division site center

PMID:30044717

**Comment by mah11** [comment]
increased protein localization to center of cell division site FYPO:0006880

edit file: 2a736df11cb4a1235a331761aa20a2d40cdd3f79
release: c6bb70640c22d92a2fafb32d18a7329d277aaf44
