### ISSUE TITLE
NTR: normal nuclear integrity PMID:30975915

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3448]
as opposed to

FYPO:0000772 | perforated nuclear envelope

(don't know if morphology is also normal, likely not completely normal in this particular mutant)

**Comment by ValWood** [comment]
would be great if you have time for PMID:30975915 tickets so I can get session through. If not I'll just remove these annotations and add later.

**Comment by mah11** [comment]
For this one, we would need a definition of "nuclear integrity" that clearly states how it differs from morphology of the nucleus or the nuclear envelope (it would also be a bonus for the def to make sense in broader contexts, i.e. outside FYPO). It's not obvious to me what that definition would be.

**Comment by ValWood** [comment]
It would mena that the nuclear envelope isn't perforated or broken,  i.e is continuous (maybe that is morphology, BUT we can't say morphology is normal because I think other things about the nucelar envelope are abnormal, but it doesn't have any holes in it. Does that help.? No?

**Comment by mah11** [comment]
Yep, morphology. I could create "imperforate nuclear envelope" using PATO:0001821. Would it be OK to put it under normal morphology, if not everything about the nuclear envelope is normal? We've done similar for other cases where we know a part of something is normal but not necessarily all ... but I can't shake a sense that it's a bit dodgy that way (generally, not just for this ntr).

I can do it just to get the term in today, if you want - we can revisit later if we can face the complications :P

**Comment by mah11** [comment]
oh hang on, it might be fine - I've used normal part part_of normal whole, not is_a (and it's been so long since I did any "normal part" terms that I'd forgotten ...)

**Comment by ValWood** [comment]
e "imperforate nuclear envelope"  sound perfect

**Comment by mah11** [comment]
OK! glad we found something :)

imperforate nuclear envelope FYPO:0006882

edit file: 68208d28846269e20370b5a8f35eda7f0ca07da7
release: ade0af8f24638618fc04108cf8981b9d2283a34a
