### ISSUE TITLE
PMID:11909965 cell cycle terms

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3449]
cell cycle arrest in mitotic metaphase

**Comment by mah11** [comment]
would the existing term do?

id: FYPO:0000620
name: abnormal cell cycle arrest in mitotic metaphase
def: "A cellular process phenotype in which progression through the mitotic cell cycle is arrested in metaphase under conditions where arrest does not normally occur."

**Comment by ValWood** [comment]
its normal so  i used

FYPO:0003762 | normal mitotic spindle assembly checkpoint
-- | --
