### ISSUE TITLE
increased gene expression shows no children

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3452]
I think it used to?  and the comment says

A cellular process phenotype in which gene expression occurs to a greater extent than normal. One or more parts of gene expression, such as transcription or translation, may be affected, and all genes, or a specific subset of genes, may be affected.

**Comment by mah11** [comment]
I've never changed anything about the logical def or asserted links since I added the term. It's possible something about what is and isn't inferred has changed, although that would probably only happen if GO changed its structure around "gene expression".

I can assert links for the FYPO terms that refer to GO terms that are part_of GO:0010467 if that will help.

**Comment by ValWood** [comment]
Anything related to transcription, translation, should be related to gene expression. Something has changed about the way some of these are asserted. See
https://github.com/geneontology/go-ontology/issues/17345


But, I'm not completely sure what it is, or how it affects things downstream....

![gene expression](https://user-images.githubusercontent.com/7359272/58782353-3d553280-85d6-11e9-95a5-21fe44c001c1.jpg)

**Comment by mah11** [comment]
Oh great. It's not clear from the GO ticket whether the changes they're planning will change FYPO inferences back to whatever you were seeing before, nor how long they'll take.

Do you remember when you last saw the connections you expected to see in FYPO?

**Comment by ValWood** [comment]
no, it was in the past few months ;(

@ukemi was this part of your refactoring? the relationships are still there but the inferences in the obo file have changed as a result of the way inferences are calculated. this in the only one I noticed though so far.

**Comment by ukemi** [comment]
It's possible that these are due to the 'has_primary_output' changes, but I'm a bit confused about exactly what you are asking. From the graph above, it looks like transcription and translation are part of gene expression, but mRNA catabolic process isn't. Do you think the catabolic term should be? It seems downstream to me.

**Comment by ValWood** [comment]
I'm confused too! 
I can't figure out why 

https://www.pombase.org/term/FYPO:0002875
increased transcription

does not  get propagated to 
increased gene expression
https://www.pombase.org/term/FYPO:0006548

I'm sure it used to until recently?

**Comment by ukemi** [comment]
Now I see that the catabolic terms are negative regulation of gene expression. The positive ones are children of positive regulation of gene expression. Everything in GO looks ok to me.

**Comment by ValWood** [comment]
It seems related to the mitochondrial translation issue?
Ignore the mRNA catabolic process  (we discussed this before)
but the annotations we are missing are related mainly to transcription....

**Comment by mah11** [comment]
Transcription, translation, etc. are all part_of gene expression in GO, and reasoning doesn't infer subsumption via part_of. IOW, a part_of link in GO doesn't automatically generate an is_a link in FYPO. 

That can explain why FYPO doesn't get links inferred now, but it hasn't changed recently and so doesn't explain why you used to see links (or at least think you did).

I can assert various and sundry is_a links in FYPO (and have done for a few other part_ofs in GO); let me know if you want me to wait until you've had more time to figure out if there really were FYPO links coming from some inferences somewhere, and if so, what's changed.

**Comment by ValWood** [comment]
I think something has changed in what the reasoner infers. but I can't explain what....

**Comment by mah11** [comment]
update from call: links might never have appeared in FYPO after all, so go ahead and assert FYPO is_a links based on GO part_of gene expression

**Comment by mah11** [comment]
added some links; reopen or do a new ticket if any others are still missing

edit file: cb7a12c12d6f67829ea32843801ea26c04e5aa19
release: f728486d1f9c0e6c73a4b138f90af9300df3f7b8

**Comment by ValWood** [comment]
tested, looks good
