### ISSUE TITLE
inviable cell at high/low temperature

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3460]
I'd like to remove these terms.

Because they exist, people are using them instead of

inviable cell population  condition:high temperature.

I guess this is because  it is the only term they find when the search on high termperature, so it seems more relevant.

I have to keep switching them over

![inviable population](https://user-images.githubusercontent.com/7359272/58544810-f512ca80-81f9-11e9-8cac-5a6966382dc7.jpg)

there are  so many annotations (18 for high termperature) , and some are already flagged as "penetrance complete)

![inviable cell at](https://user-images.githubusercontent.com/7359272/58544903-1d9ac480-81fa-11e9-89c1-56f3d9e3450f.jpg)

downside is that  wont be easy to separate, but low numbers indicate this isn't really an issue and will be resolved by 
https://github.com/pombase/website/issues/56

**Comment by mah11** [comment]
done

edit file: 7dd3287daf21635ace9335cf56048f08b094ff54
release: bc071a6f56d7ae11464a58e942131f7ca5dcce87

**Comment by ValWood** [comment]
Did d you merge? I guess a merge into the population term would work  but I might need to check that the condition was always present? It does not alway seem to be?

**Comment by ValWood** [comment]
ticket for  reannotations
https://github.com/pombase/curation/issues/2416
