### ISSUE TITLE
normal growth on chemical terms PMID:30658998

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3466]
normal growth on

vanoxerine, hexestrol, clomifene, ketoconazole and terconazole

PMID:30658998

**Comment by mah11** [comment]
normal growth on vanoxerine FYPO:0006910
  normal growth on hexestrol FYPO:0006911
  normal growth on clomiphene FYPO:0006912
  normal growth on ketoconazole FYPO:0006913
  normal growth on terconazole FYPO:0006914

edit file: cb7a12c12d6f67829ea32843801ea26c04e5aa19
release: f728486d1f9c0e6c73a4b138f90af9300df3f7b8
