### ISSUE TITLE
missing relation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3467]
I do not see

+ | decreased protein localization to mitotic spindle midzone, with protein distributed along spindle, during anaphase B

as a descendant of
decreased protein localization to mitotic spindle midzone during anaphase B

**Comment by mah11** [comment]
link added

edit file: cb7a12c12d6f67829ea32843801ea26c04e5aa19
release: f728486d1f9c0e6c73a4b138f90af9300df3f7b8
