### ISSUE TITLE
ntr: normal onset of mitotic metaphase/anaphase transition  PMID:31089172

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3468]
FYPO:0005637 | normal onset of mitotic metaphase/anaphase transition 

sibling of
FYPO:0005637 | normal onset of metaphase/anaphase transition of meiosis I

**Comment by mah11** [comment]
normal cell cycle process FYPO:0006915
  normal cell cycle phase transition FYPO:0006916
  normal onset of mitotic metaphase/anaphase transition FYPO:0006917

edit file: cb7a12c12d6f67829ea32843801ea26c04e5aa19
release: f728486d1f9c0e6c73a4b138f90af9300df3f7b8
