### ISSUE TITLE
more ntrs PMID:31089172

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3469]
FYPO:0002531 | abolished protein localization to nucleoplasm
PLUS
"during mitotic  interphase"

FYPO:0000838 | normal protein localization to nucleus
PUS
"during mitotic  interphase"

**Comment by mah11** [comment]
abolished protein localization to nucleoplasm during mitotic interphase FYPO:0006918
  normal protein localization to nucleus during mitotic interphase FYPO:0006919

edit file: cb7a12c12d6f67829ea32843801ea26c04e5aa19
release: f728486d1f9c0e6c73a4b138f90af9300df3f7b8
