### ISSUE TITLE
PMID:30840879 NTR

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3477]
abolished child of 

FYPO:0005290 | decreased protein localization to plasma membrane at cell division site during vegetative growth

also child of

FYPO:0001880 | abolished protein localization to cell division site

**Comment by ValWood** [comment]
plus
abolished lipid binding

**Comment by mah11** [comment]
Please confirm that you want this:

- abolished protein localization to plasma membrane at cell division site during vegetative growth

General tip: The most useful thing to put in a new term request ticket is the name of the actual term you're requesting.

Unlike GO, for FYPO I usually don't need the tickets to suggest parents; I'll ask if I can't tell easily. (Also, for processes "abolished" isn't is_a "decreased" generally at present, although that's likely to change in the big overhaul.)

**Comment by ValWood** [comment]
yes
abolished protein localization to plasma membrane at cell division site during vegetative growth

**Comment by mah11** [comment]
abolished protein localization to plasma membrane at cell division site during vegetative growth FYPO:0006936
  abolished lipid binding FYPO:0006937

edit file: 1a63eead7b803ac4b0d522b1b7e00ab88d91da43
release: 5e6ca978a1a7313e73923fcf8f66edc04fef36a1

**Comment by ValWood** [comment]
I don't see
FYPO:0006936

as a child of decreased protein localization to plasma membrane at cell division site during vegetative growth

**Comment by ValWood** [comment]
OK that's the weird PATO thing...
