### ISSUE TITLE
NTR: mid2 paper

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3495]
abolished  protein localization to medial cortex, with protein mislocalized to cytoplasm

PARENTS

spn4 |   | spn4Δ | FYPO:0002555 | abolished protein localization to medial cortex during vegetative growth | 

spn4 |   | spn4Δ | FYPO:0006221 | decreased protein localization to cell division site, with protein mislocalized to cytoplasm 

DEF standard

REF PMID:12668659

**Comment by ValWood** [comment]
| normal protein localization to medial ring during vegetative growth

descendant of

FYPO:0002558 | normal protein localization to medial cortex during vegetative growth

REF PMID:12668659

**Comment by mah11** [comment]
I've added the first term:

 abolished protein localization to medial cortex, with protein mislocalized to cytoplasm, during vegetative growth FYPO:0007027

but in GO "medial ring" is an exact synonym of "medial cortex" - see GO:0031097. If the two can now be distinguished, it will help consistency if you can get GO CC sorted first.

edit file: 4f3372764e0e885ec97cf4417808e8d47a70623e
release: b433bc3c036054f6a8b57b3e72e865df4d60549b

**Comment by ValWood** [comment]
corrected to "septin ring"

(in GO this is called "medial cortex septin ring")

medial cortex septin ring
--




medial cortex septin ring
--

**Comment by mah11** [comment]
ok, makes sense

normal protein localization to medial cortex septin ring during vegetative growth FYPO:0007028

edit file: 6e9696649435ceddb9dc4d2ecccc6f96a7beef54
release: 22c4e334b73d4418c7c787b65bd2bb21b74a2b0e
