### ISSUE TITLE
monosaccharide composition

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3497]
From the author

normal cell wall polysaccharide composition during vegetative growth
Substance quantification evidence
fig S4
Valerie Wood <vw253@cam.ac.uk>

normal cell wall polysaccharide composition should be changed to 

normal cell wall monosaccharide composition
 

could we add this term  (or change?) ?

**Comment by mah11** [comment]
I just added a new term:

normal cell wall monosaccharide composition during vegetative growth FYPO:0007030

I figure sooner or later someone will look at the polysaccharide composition, and then we'll be ready for 'em ;)

edit file: 6e9696649435ceddb9dc4d2ecccc6f96a7beef54
release: 22c4e334b73d4418c7c787b65bd2bb21b74a2b0e
