### ISSUE TITLE
abolished protein localization to *cortex* cell tip during mitotic interphase 

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3498]
abolished protein localization to *cortex* cell tip during mitotic interphase 

I wan tto move most of these down:
abolished protein localization to cell tip during mitotic interphase (FYPO:0003329)

**Comment by mah11** [comment]
abolished protein localization to cell cortex of cell tip during mitotic interphase FYPO:0007031

edit file: 6e9696649435ceddb9dc4d2ecccc6f96a7beef54
release: 22c4e334b73d4418c7c787b65bd2bb21b74a2b0e
