### ISSUE TITLE
abnormal meiotic telomere clustering (FYPO:0000172) add synonym

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3499]
abnormal bouquet formation

https://github.com/pombase/curation/issues/1859

**Comment by mah11** [comment]
added synonyms to FYPO:0000172, FYPO:0004093, FYPO:0006366

edit file: 6e9696649435ceddb9dc4d2ecccc6f96a7beef54
release: 22c4e334b73d4418c7c787b65bd2bb21b74a2b0e
