### ISSUE TITLE
one more for PMID:30389790 

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3500]
From Cecilia's feedback

increased protein glycosylation
synonym : protein hypoglycosylation

**Comment by mah11** [comment]
Name and synonym don't match - _hypo_ is Greek for below.

**Comment by mah11** [comment]
new:
id: FYPO:0007032
name: increased protein glycosylation during vegetative growth FYPO:0007032
synonym: protein hyperglycosylation during vegetative growth

existing:
id: FYPO:0001911
name: decreased protein glycosylation during vegetative growth FYPO:0007032
(new) synonym: protein hypoglycosylation during vegetative growth


edit file: 6e9696649435ceddb9dc4d2ecccc6f96a7beef54
release: 22c4e334b73d4418c7c787b65bd2bb21b74a2b0e
