### ISSUE TITLE
text fix FYPO:0003010

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#3510]
<img width="1022" alt="Screenshot 2019-08-28 at 16 45 26" src="https://user-images.githubusercontent.com/12727506/63871164-4b3b0980-c9b3-11e9-8506-5fbac3ac844d.png">

**Comment by mah11** [comment]
Can I have a text summary? Or at least a screenshot with bigger text?

**Comment by Antonialock** [comment]
it's just the comment that contains text "MERGED COMMENT:\nTARGET COMMENT: 
yadiyada

**Comment by mah11** [comment]
ok, thanks. fixed at source and will go live next time I run the release script.
