### ISSUE TITLE
QC: Duplicate labels

### ISSUE THREAD

**Issue by matentzn** [pombase/fypo#3513]
ERROR	duplicate_label	FYPO:0004527	rdfs:label	abnormal regulation of transcription during vegetative growth	
ERROR	duplicate_label	FYPO:0006471	rdfs:label	abnormal regulation of transcription during vegetative growth

**Comment by mah11** [comment]
OK, that was a weird one - the logical def for FYPO:0004527 had a spurious reference to GO:0044838. Without that, even my creaking old OORT deployment would've caught the duplication.

Merged FYPO:0006471 into FYPO:0004527.

**Comment by mah11** [comment]
release is commit 2be3bcf4483328de6d11b83e850df8417a9c73f9
