### ISSUE TITLE
ODK Migration

### ISSUE THREAD

**Issue by matentzn** [pombase/fypo#3516]
- [ ] Handle BTO import
- [ ] refresh imports (no dangling classes allowed)
- [ ] Generated fully classified fypo.obo (compare to current public version - should not be too different)
- [ ] Iteratively remove relationships 1 by one and compare fypo.obo each time to make sure nothing is lost
- [ ] Check how many more unsatisfiable classes exist
- [ ] fix remaining unsats in meetings with @mah11

**Comment by mah11** [comment]
... or come up with some other way to model phenotypes that include a reference to the growth medium for a population of single-celled organisms. I'm not wedded to using BTO if there is a better alternative.

**Comment by matentzn** [comment]
right now the problem is that BTO is simply not available anywhere.. could you make a list of steps necessary that would not to happen to facilitate the migration away from those?

**Comment by mah11** [comment]
I'm not sure I understand the question as phrased here, but here's what happens now, in case it helps ...

I do edits in creaky ol' OBO-Edit, and then run this owltools command:

/Applications/owltools-read-only/OWLTools-Oort/bin/ontology-release-runner --no-subsets -reasoner elk --simple --allow-overwrite -outdir /Users/mah79/OORT/ /Users/mah79/pombase_git/fypo/save-fypo.obo http://geneontology.org/ontology/go.obo /Users/mah79/Documents/ontologies/cell/cl-basic.owl http://purl.obolibrary.org/obo/pato.owl http://purl.obolibrary.org/obo/so.owl /Users/mah79/Documents/ontologies/chebi_lite.owl /Users/mah79/Documents/archived/phenotype/BTO_is-a_only.obo > /Users/mah79/OORT/oort.log 2>&1

As you can see if you eyeball it closely enough, it uses a locally stored obo file for BTO, which I edited with a macro to remove relations other than is_a. It was last updated (i.e. I last downloaded and munged it) in mid-2015.

Kim's release script also invokes a similar command, using the same BTO file.

That said, all of the FYPO terms that use BTO in logical defs use the same term, BTO:0000316 'culture medium', and over 90% of them describe cell population growth in a medium with a specified chemical present or at a given temperature. I'm sure we can model them somehow!

The remaining dozen or so describe phenotypes where cells secrete/release some substance into the medium to a normal, greater, or lesser extent compared to a reference (wild type pombe in our case).

**Comment by matentzn** [comment]
Since it is only a single [term](http://purl.obolibrary.org/obo/BTO_0000316
); I am half inclined to say ditch BTO in favour of a custom solution; more in our first meeting. An alternative could be [OBI](https://www.ebi.ac.uk/ols/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000079).

**Comment by mah11** [comment]
I'm open to that! Will send the file anyway in the meantime.

**Comment by mah11** [comment]
How much of this has been done? Seems a lot closer now ...

**Comment by matentzn** [comment]
It’s finished! The rest is pattern alignment!

**Comment by mah11** [comment]
hooray!
