### ISSUE TITLE
nuclear envelope terms

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3518]
decreased protein localization to nuclear envelope

normal protein localization to nuclear envelope

and abolished

**Comment by ValWood** [comment]
actually, normal is there, but not a descendant of the periphery term

**Comment by mah11** [comment]
abolished protein localization to nuclear envelope during vegetative growth is FYPO:0004886. 

Do you need a term that's not specific for vegetative growth?

> ... but not a descendant of the periphery term

Correctly so, given the placement of "nuclear periphery" in GO CC - it's defined as part of the nuclear lumen.

**Comment by ValWood** [comment]
Ah OK I did not realise that. 

Probably all the terms OI wasnt exist already. Although I didn't notice them when searching...

**Comment by mah11** [comment]
decreased protein localization to nuclear envelope during vegetative growth FYPO:0007073

edit file: 51d2fa0213b2f4cacab19ad8df262b67c74ef2fa
release: 53940dd86555e65ec07901c5ed8e36a0a1cc9ee1
