### ISSUE TITLE
add synonym for lifespan

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3521]
add
chronological cell aging
as a related synonym of "

FYPO:0001309 | increased viability in stationary phase

PMID:20829365

**Comment by mah11** [comment]
Chronological cell aging is a process (GO:0001300), so should the synonym include a modifier (e.g. decreased chr. aging for increased viability in stationary)?

**Comment by ValWood** [comment]
increased

**Comment by mah11** [comment]
isn't that backwards? you'd get increased viability with decreased, not increased, aging ...?

**Comment by ValWood** [comment]
Oh right I was thinking that  the term was "increased chronological lifespan"

increased chronological lifespan
decreased chronological aging

**Comment by mah11** [comment]
"aging" synonyms added ("lifespan" was there)

edit file: 51d2fa0213b2f4cacab19ad8df262b67c74ef2fa
release: 53940dd86555e65ec07901c5ed8e36a0a1cc9ee1
