### ISSUE TITLE
link between FYPO:0004077 FYPO:0003378

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3522]
6 abnormal sporulation resulting in formation of ascus with single large spore (FYPO:0004077) 

is an indicator of 

4 abolished meiosis I (FYPO:0003378) [single allele genotypes]

(has_output?)

**Comment by mah11** [comment]
Which direction is it always true? Is FYPO:0004077 the only result of abolished meiosis I?

**Comment by ValWood** [comment]
when
ascus with single large spore occurs
it is always due to 
abolished meiosis I 

(but isn't the only result of abolished meiosis I, because sometime miosis I can fail but then "meiosis II" can proceed  on meiosis I set up and you can get some viable spores  ..i.e >1 )

**Comment by mah11** [comment]
OK, thanks. That means the link will be FYPO:0004077 output_of FYPO:0003378 (and the actual relations will be updated to something else in the ODK/upheno overhaul ...).

**Comment by mah11** [comment]
link added

edit file: 347065c800c0106d0a95ea0cd89fcd3609c72a57
release: 3414f9f3492b36c76acc37fb2192e78938dc2f17
