### ISSUE TITLE
link between FYPO:0001683 FYPO:0001734

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3523]
abolished mitotic spindle pole body separation (FYPO:0001734) [single allele genotypes]

has output

abolished mitotic spindle assembly (FYPO:0001683) [single allele genotypes] | ...

(also for meiotic yada yada)

spindle pole body separation  is the first part of assembly.

**Comment by ValWood** [comment]
Actually here we are referring to 

https://www.ebi.ac.uk/QuickGO/term/GO:0000073

so we may need to do some reannotation too.

**Comment by ValWood** [comment]
I'm not sure on the status of this
https://github.com/geneontology/go-ontology/issues/13461

we can come back to this ticket when the GO  changes are done

**Comment by mah11** [comment]
If there are any FYPO changes other than adding an output-ish link, list them when you're ready for the edits to be done.

**Comment by mah11** [comment]
The GO ticket has been closed. Is there anything else to do for FYPO now?

**Comment by ValWood** [comment]
I don't t hink so...
