### ISSUE TITLE
ntr: PMID:31532702

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3524]
normal initial separation of the SPB in meiosis II

normal spindle elongation in meiosis II

meiotic spindle collapse

abnormal meiotic spindle pole body initial separation during meiosis I

abolished meiotic spindle pole body initial separation during meiosis I

**Comment by mah11** [comment]
normal meiotic cell cycle process FYPO:0007078
  normal initial meiotic spindle pole body separation in meiosis II FYPO:0007079
  abnormal initial meiotic spindle pole body separation in meiosis I FYPO:0007080
  abolished initial meiotic spindle pole body separation in meiosis I FYPO:0007081
  normal meiotic spindle elongation in meiosis II FYPO:0007082
  meiotic spindle collapse FYPO:0007083

edit file: 347065c800c0106d0a95ea0cd89fcd3609c72a57
release: 3414f9f3492b36c76acc37fb2192e78938dc2f17
