### ISSUE TITLE
zinc related phenotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3526]
from the author

Increased gene repression in response to zinc
A gene expression phenotype that leads to higher levels of gene repression in response to zinc

Increased DNA binding activity in response to high zinc
Higher levels of DNA binding activity in response to high zinc growth conditions

PMID:31515876

**Comment by Antonialock** [comment]
that sounds like the same as Charlie's phenotype "increased negative regulation of transcription by glucose"? (but by zinc)

**Comment by ValWood** [comment]
A number of the txn factors for  non-housekeeping processes appear respond to specific nutrients.. iron, copper, zinc  and repress expression  to prevent toxicity

**Comment by Antonialock** [comment]
Yeah to me that sounds like the ‘negative regulation of transcription by glucose’ just by another nutrient

**Comment by mah11** [comment]
GO doesn't have a BP term for "negative regulation of transcription by zinc", but I could model the new term on FYPO:0006296 anyway (without a logical def, unless you want to request a new GO term). That would give it a path to "cellular response phenotype during vegetative growth" (FYPO:0001342) - is that OK?

**Comment by ValWood** [comment]
I don't think GO will include this term  @pgaudet ? 
If so, I guess it would need to be  without logical def...

(I think the parent is OK, but would it also have an altered transcription regulation parent?

**Comment by pgaudet** [comment]
This would be nice as a GO-CAM model. It would probably look like 
- _causally upstream of_ regulation of transcription
- _part_of_ response to zinc 

As an aside, one feature that seems would solve a lot of problem would be to add another 'contextual' annotation, like 
- _causally upstream of_ regulation of transcription
- _in the presence of_ high zinc 
That zinc would not be an annotation per se, but these conditions could be queried. 

I know this is something GREEKC would like (these types of experiments are quite common in the transcription field). 

Pascale

**Comment by ValWood** [comment]
Actually, for this session I did model the GO annotation in this way, so it makes sense to do the phenotype logical defs similarly.

**Comment by ValWood** [comment]
Actually I didn't do this, the author did!


Gene | Term ID | Term name | Evidence code | Comment | Annotation extension | Curator
-- | -- | -- | -- | -- | -- | --
loz1 | GO:0001227 | DNA-binding transcription repressor activity, RNA polymerase II-specific | EXP | deletion of loz1 leads to increased expression of this transcript in high zinc g   [more...] | has_regulation_target SPNCRNA.1710 , part_of cellular response to zinc ion | Amanda Bird <xxxxx@osu.edu>

How cool is that!

**Comment by pgaudet** [comment]
Pretty awesome !!! 
That support's Paul statement that GO-CAM is closer to how scientists think about their work !

**Comment by ValWood** [comment]
Well I don't know how intuitive this one. I went through the previous papers so  now she knows how to do it. This was the last one:
https://www.pombase.org/reference/PMID:29529046

But it does show that they don't need Noctua to do it ;)

**Comment by mah11** [comment]
Housekeeping note: when I close this ticket, I am going to remove the comments that have nothing to do with the FYPO work it requests.

**Comment by Antonialock** [comment]
so we need a sibling term to GO:0061986 for zinc? @pgaudet

**Comment by ValWood** [comment]
I suspect GO:0061986  needs obsoleting, and should be post composed?
Although it is a bit inconsistent becasue we have


DNA-binding transcription repressor activity, RNA polymerase II-specific

  | regulates zrt1 part of regulation of transcription from RNA polymerase II promoter in response to zinc ion starvation

**Comment by mah11** [comment]
Please take the GO term considerations to a GO ticket.

**Comment by mah11** [comment]
> That supports Paul statement that GO-CAM is closer to how scientists think about their work !

I doubt that we can safely draw this conclusion, given how much we do to prompt, guide, and handhold users both in the Canto interface and in person. Although we have had some bench biologists turn in excellent curation done as a result, it doesn't provide evidence of what they would do or think without the prompting.

**Comment by ValWood** [comment]
This isn't ready for the GO tracker,  once I know waht is required I'll oen a GO tracker ticket. We should keep this ticket open because some of the FYPO terms might require remodelling.

**Comment by mah11** [comment]
> Actually if I can just get the requested terms.

Then what? This isn't a complete sentence ...

**Comment by ValWood** [comment]
No need to wait for GO. If I can just get the requested terms so I can make the session live. Any GO changes which affect the term can be factored in later.

**Comment by mah11** [comment]
abnormal regulation of transcription by nutrient FYPO:0007090
  increased negative regulation of transcription by zinc FYPO:0007091
  increased DNA binding during cellular response to zinc ion FYPO:0007902

edit file: a116b2296b658f7408c67160cfc150a16fe96459
release: 6fb3bbd3373ea6f15cbada9b70251ec2954fa27c
