### ISSUE TITLE
suggest change primary name

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3535]
Can we call this 
GO:0051455	attachment of spindle microtubules to kinetochore involved in homologous chromosome segregation

	GO:0051455	attachment of spindle microtubules to meiosis I  kinetochore 

(this  is a bit shorter, seems to align more with how the users describe the process,  and the  homol ch. seg. is a given)

**Comment by ValWood** [comment]
The user suggested this differentia

meiotic kinetochores
positive regulation of attachment of spindle microtubules to kinetohcore prior to meiosis I

but hey hadn't found the  "omologous chromosome segregation" term, only a parent

**Comment by mah11** [comment]
I'm happy to swap names & synonyms in FYPO, but a lot of this ticket looks aimed at GO ...

**Comment by mah11** [comment]
did some swapping & additional synonyms; will close this as the rest is for GO

edit file: 7c615f5578aaecbdaa42544f62f445982125c8af
release: 0c8676b23f5b26a53a6a44b80c518e11d337ef09

**Comment by ValWood** [comment]
ok on my list to do the GO
