### ISSUE TITLE
Help, difficult phenotype to describe

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3537]
Although I'm sure  @JackyVH  had this in one of Ken's papers. I can't find the terms used...

In contrast, for3􏰀 cells produced nonequivalent daughters;one daughter grew only in a monopolar manner at the old end, while the other daughter immediately initiated growth from both ends and proceeded to grow in a bipolar manner (Figure 1a,b). Thus, one daughter (the monopolar cell)exhibited no NETO(or a greatly delayed NETO), while the other daughter (the bipolar cell) exhibited premature NETO. These patterns occurred in the large majority of cell divisions(85%ofcell divisions, n 􏰂 52). Analyses of lineages over multiple generations and of lineages using morphological characterization of mothers showed that both bipolar cells and monopolar cells divided to produce one bipolar daughter and one monopolar daughter (75% of cell divisions with monopolar mothers [n 􏰂 16]; 81% of cell divisions with bipolarmothers[n􏰂22]).

**Comment by ValWood** [comment]
I need somthing which means  "exclusively monopolar and bipolar daughter cells"

**Comment by ValWood** [comment]
this is intertesting (although I can't think of a way to capture it!)

Although the extent of these abnormal mor- phologies was variable among cells,bipolar cells generally grew into lemon-shaped or bottle-shaped cells,while monopolar cells were more rod-shaped or bent.

**Comment by ValWood** [comment]
daughter cells with in equivalent growth polarity?

**Comment by ValWood** [comment]
That is for the first one obviously

**Comment by ValWood** [comment]
could we add this as a comment to the term?

Almost every cell (97%)that inherited the birth scar from two cell divisions prior becomes the cell with a bipolar growth pattern

**Comment by mah11** [comment]
It's not very clear to me what term(s) you're requesting here - 

> "exclusively monopolar and bipolar daughter cells"
> daughter cells with in equivalent growth polarity?

Neither of these strings makes sense.

But ... is there any overlap between this and the stuff in #2938? That one hasn't been resolved because we all moved on to other things after I raised some questions. It might not be exactly the same thing, but it still might make sense to tackle them together.

It looks like a similar question came up in #2926 but we punted it then.

**Comment by ValWood** [comment]
That should have been
daughter cells with inequivalent growth polarity

(this is the phrase used to describe the phenotype in the paper)

definition One daughter cell is exclusively monopolar, and one dauughter is exclusively biopolar

I think https://github.com/pombase/fypo/issues/2938
is different but related.
Here cells never grow  in a bipolar manner (although I would need to look at the paper again to be sure)

For this one the paper is
PMID:11696322

**Comment by mah11** [comment]
I *think* I may have this sorted in #3614 (new terms for the latest paper from Maitreyi's lab) ... check it out and see if the terms there will work for this ticket.

**Comment by mah11** [comment]
Reopen this if the terms added for #3614 & #3699 *don't* sort it out.
