### ISSUE TITLE
PMID:15298676 meiotic kinetochores

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3542]
abnormal meiotic centromere clustering resulting in centromere-spindle pole body colocalization 

please change to
abnormal meiotic centromere clustering resulting in centromere-spindle pole body colocalization  during prophase. 
This is normal after prophase.  Here  the centromeres remain clustered when the telomers are clustered.

"When meiosis was induced by Pat1 inactivation at the G1 phase of mitosis, telomeres clustered to the SPB as per normal meiosis, but in most cells the centromeres remained partially associated with the SPB. When meiosis was initiated at the G2 phase by Pat1 inactivation, both telomeres and centromeres retained their mitotic nuclear positions in the majority of cells"

Then for:

	normal meiotic centromere clustering during meiotic prophase I

change to

-> normal meiotic centromere clustering during meiotic prometaphase 1

and for

FYPO:0007108	abnormal meiotic centromere clustering during meiotic prophase I

this normally occurs drug prometaphase I
so instead say 

instead  “incomplete meiotic centromere clustering during meiotic prophase I”

- it happens at the end of prophase before metaphase
- also this change makes it clearer that it is not happening correctly at the right time (some kinetochores remain unclustered)

**Comment by mah11** [comment]
changed as requested

edit file: 64b181e14ace28def2001b8bd2549a30e9a7a59d
release: f1383ca6022a9ae20ada50c46ae1d0c7410f04c7
