### ISSUE TITLE
terms for mti1/2 PMID:31350787

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3545]
normal growth on iron

decreased respiratory complex assembly

also add synonym "loss of mitochondrial DNA" to FYPO:0003769

**Comment by mah11** [comment]
> decreased respiratory complex assembly

Any specific complex(es)? or any, or all? Which GO terms (assembly BP, or just complex CC)?

**Comment by mah11** [comment]
this is mitochondrial stuff, so we can use GO:0033108 ! mitochondrial respiratory chain complex assembly

use "one or more yada" in text def
