### ISSUE TITLE
terms for peg1/ase1 PMID:31615768

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3546]
unbundled spindle during mitotic prophase

normal spindle microtubule bundling in mitotic prophase

normal protein localization to mitotic spindle midzone during prophase

**Comment by mah11** [comment]
for second one, just use normal spindle morphology

**Comment by mah11** [comment]
more notes from chat:

edit fypo:6346 to emphasize non-uniform thickness & add that this one elongates

in new1 MTs not in parallel or antiparallel orientation, but instead radiate in many directions (see if  there's a suitable PATO; otherwise no xp)

**Comment by mah11** [comment]
new terms
  unbundled spindle during mitotic prophase FYPO:0007123
  normal protein localization to mitotic spindle midzone during prophase FYPO:0007124

renamed FYPO:0006346 to 'bipolar mitotic spindle with decreased, irregular thickness'; adjusted other details accordingly

edit file: 64b181e14ace28def2001b8bd2549a30e9a7a59d
release: f1383ca6022a9ae20ada50c46ae1d0c7410f04c7
