### ISSUE TITLE
mononucleate septated is a terminal phenotype

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3547]
so we can merge any descendant pairs like:
inviable septated mononucleate vegetative cell 
mononucleate multiseptate vegetative cell 

(keeping inviable in the term name?)

**Comment by ValWood** [comment]
Can
FYPO:0002303 | inviable mononucleate monoseptate vegetative cell

be related to abnormal mitotic exit (It's actually premature mitotic exit so maybe this should also . be a term?)

**Comment by mah11** [comment]
I found two pairs to merge

  FYPO:0002001 into FYPO:0004657
  FYPO:0005276 into FYPO:0002000

and one to add 'inviable' (FYPO:0001917)

I'll close this, and watch for a ticket in case you go for the additional things floated in https://github.com/pombase/fypo/issues/3547#issuecomment-547955557

edit file: f623968cf338deb197a749ed344b11922bde331f
release: 22a37036cb982537b07873689c6932f2397082a6
