### ISSUE TITLE
ntr: 	 chromosome separation in the absence of mitotic  spindle

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3548]
ntr: 	 chromosome separation in the absence of mitotic  spindle

PMID:9864354

**Comment by mah11** [comment]
mitotic chromosome separation in absence of mitotic spindle FYPO:0007125

edit file: f623968cf338deb197a749ed344b11922bde331f
release: 22a37036cb982537b07873689c6932f2397082a6
