### ISSUE TITLE
PMID:11870212 chromosome movement

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3551]
abnormal chromosome movement in mitotic anaphase A

descendent of:

FYPO:0000141	abnormal mitotic sister chromatid segregation

**Comment by mah11** [comment]
GO:0007079?

**Comment by ValWood** [comment]
yep! The chromosomes move up and down the spindle  but end up in the right place!

**Comment by mah11** [comment]
abnormal mitotic chromosome movement towards spindle pole FYPO:0007128

edit file: f623968cf338deb197a749ed344b11922bde331f
release: 22a37036cb982537b07873689c6932f2397082a6
