### ISSUE TITLE
PMID:20517925 gmf

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3564]
decreased number of actin cortical patches during vegetative growth

elongated actin cables

**Comment by mah11** [comment]
> abolished ectopic mitotic spindle assembly checkpoint ...
> I'm not sure if this is allowed?

Does it make any sense? More precisely, is it any different from normal activation of the checkpoint? (or just plain "abolished", if it doesn't happen at either normal or ectopic sites)

**Comment by mah11** [comment]
new term
  long actin cables FYPO:0007151

added synonym FYPO:0004964

edit file: 91b2bb7789f39baa6501546993a86ff9a05f0dca
release: e96bf3a739a2ced95bb4b13538c820dcfd2276a0

(also deleted comment stuck on wrong ticket)

**Comment by ValWood** [comment]
short, misoriented actin cables 
short, thick, misoriented actin cables 

appear as children of "long actin cables"
