### ISSUE TITLE
add synonym FYPO:0007160	

### ISSUE THREAD

**Issue by Antonialock** [pombase/fypo#3585]
Abnormal DNA replication-coupled nucleosome assembly 
synonym for:
 abnormal DNA replication-dependent nucleosome assembly 

FYPO:0007160

**Comment by mah11** [comment]
done

edit file: 8a95bc89b3f32f0d0962ebfc06b46f1998441fd3
release: 12fe516bbf65388b14137de4caf4313c9f31259e
