### ISSUE TITLE
PMID:31483748 NTR : increased sister chromatid cohesion along the chromosome arms during mitotic interphase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3588]
increased sister chromatid cohesion along the chromosome arms during mitotic interphase

 can use this strangely named term in the logical def

GO:0071961    JSON
mitotic sister chromatid cohesion, arms
The cell cycle process in which the sister chromatids of a replicated chromosome are joined along the length of the chromosome arms during mitosis.

descendant of
FYPO:0006521 | abnormal mitotic sister chromatid cohesion

**Comment by ValWood** [comment]
and a mitotic version of this term


FYPO:0007105 | increased duration of Rad52 focus presence during meiotic cell cycle

**Comment by ValWood** [comment]
and

abolished spindle poly body/centrosome lead chromosome movement during mitotic interphase

**Comment by mah11** [comment]
> abolished spindle poly body/centrosome lead chromosome movement during mitotic interphase

For this one please see comment on the relevant [GO ticket](https://github.com/geneontology/go-ontology/issues/18373) - the GO term name needs fixing.

**Comment by mah11** [comment]
added these:
  increased sister chromatid cohesion along chromosome arms during mitotic interphase FYPO:0007190
  increased duration of Rad52 focus presence during vegetative growth FYPO:0007191

for the last one, if this is true (from the GO ticket)

> Actually, I think
> spindle pole body-led chromosome movement during mitotic interphase
> 
> and
> mitotic spindle pole body oscillation
> are describing the same phenotype

which wording should I use for FYPO term names? Existing terms (FYPO:0005349 & FYPO:0005691, increased & decreased) use the "spindle pole body oscillation" version.


edit file: 48bb20dca3bc5c96c788dee0894d8586ea0770c6
release: 3d6d8217e41d38e07e812c7f918f3ea4487460dd

**Comment by ValWood** [comment]
spindle pole body-led chromosome movement during mitotic interphase think we should change to
spindle pole body-led chromosome movement during mitotic interphase
with oscillation synonyms.

This makes the oscillation purpose clearer.

**Comment by mah11** [comment]
> spindle pole body-led chromosome movement during mitotic interphase think we should change to
spindle pole body-led chromosome movement during mitotic interphase

This doesn't make sense because the "change from" and "change to" texts are identical.

**Comment by ValWood** [comment]
I pasted the change to text twice, removed one

**Comment by ValWood** [comment]
So, can I get
spindle pole body-led chromosome movement during mitotic interphase
with
spindle pole body oscillation 
synonyms

**Comment by mah11** [comment]
yup - new term
  abolished spindle pole body-led chromosome movement during mitotic interphase FYPO:0007192
renamed FYPO:0005349 & FYPO:0005691 to match; all have "spindle pole body oscillation" in exact synonyms

edit file: 1a509f11fdd6222a01744ca6f1e083623d2f8aeb
release: 0fc81ac9fd6927113bee9fed420f74b25bdde377
