### ISSUE TITLE
revise term/ spindle pole body detached from cytoplasmic microtubules

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3589]
spindle pole body detached from cytoplasmic microtubules

could we word this as
abolished microtubule attachment to spindle pole body
exact synonyms
cytoplasmic microtubules detached from spindle pole body
interphase microtubules detached from spindle pole body
interphase microtubules detached from nucleus
abolished microtubule attachment to nucleus]

not physically connected to the nucleus. In these cells, consistent with the lack of MT attachment,

and refine def to

A cell phenotype observed in the vegetative growth phase of the life cycle in which the interphase cytoplasmic microtubules are not attached to the spindle pole body, and are  therefore not connected to the nucleus

> Normally, the spindle pole body is attached to a single cytoplasmic microtubule bundle.

Is this true?

**Comment by mah11** [comment]
done

> > Normally, the spindle pole body is attached to a single cytoplasmic microtubule bundle.
> 
> Is this true?

changed to "at least one"; I think the "single bundle" must have come from how I interpreted this bit from the PMID:15772152 intro:

"During interphase, 3–5 cytoplasmic MT bundles are organized from the outer nuclear envelope. One of these is associated with the SPB, whereas the others are organized from interphase MTOCs"

... but it doesn't explicitly say the iMTOC-nucleated MTs don't attach to the SPB

edit file: 48bb20dca3bc5c96c788dee0894d8586ea0770c6
release: 3d6d8217e41d38e07e812c7f918f3ea4487460dd
