### ISSUE TITLE
mitochondrial fragmentation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3591]
I would like

 | mitochondria present in increased numbers during vegetative growth
-- | --

we have

FYPO:0003820 | mitochondria present in decreased numbers during vegetative growth
-- | --

since increased number is caused by increased fragmentation (fission)
the author used

 
Term name | fragmented mitochondria
Definition | A cell phenotype observed in the vegetative growth phase of the life cycle in which mitochondria are broken into multiple small fragments that are smaller than a normal mitochondrion.

Should this be merged or renamed?
The def is a bit unclear. I  don't think I would call these "fragments" (even id i did)

fragments makes it sound as though they are no longer complete mitochondria.
also I don't think we can say they are smaller than normal.  Mitochondria change size during the cell cycle. They are larger during interphase and smaller during mitosis.

Help!

**Comment by ValWood** [comment]
Would need to check that  ther is really no "fragmentation" that isn't  "more smaller"

Of the exiting annotations (9)
the ones from

Delerue T et al. (2016)
and
Jourdain I et al. (2009)

reefer to normal  "fragmentation" (i.e more smaller mitochondria)  type process during "fission"

I did not check
Wiley DJ et al. (2008)
Su Y et al. (2017)
Shang J et al. (2018)
 Liu Q et al. (2018)

**Comment by ValWood** [comment]
I had not spotted, the author put this suggestion

Increased mitochondrial numbers and decreased mitochondrial sizes with overall mitochondrial volume same as what is observed in wild-type cells

 Nice to not that overall volumen does not change, but there are more smaller microtubules.

**Comment by mah11** [comment]
I'd say "present in increased numbers" is broader than "fragmented" - you could have more normal-size mitochondria, for a greater total mitochondrial volume, or more-and-smaller. Only the latter is the same as fragmented.

I'm not fussed about which wording we actually use for the "more and smaller" case. It wouldn't be much trouble to convert it to something analogous to FYPO:0000281 ! small vacuoles present in increased numbers during vegetative growth.

id: FYPO:0000281
name: small vacuoles present in increased numbers during vegetative growth
def: "A cell phenotype observed in the vegetative growth phase of the life cycle in which a cell contains more, but smaller, vacuoles than normal." [PomBase:mah]
synonym: "fragmented vacuoles during vegetative growth" RELATED [PomBase:mah]
synonym: "small vacuoles present in greater numbers during vegetative growth" EXACT [PomBase:mah]
synonym: "small vacuoles present in increased numbers during mitotic cell cycle" RELATED [PomBase:mah]
synonym: "vacuole fusion defects" RELATED [PomBase:vw]
synonym: "vacuole organization defects, fragmented vacuoles during vegetative growth" RELATED [PomBase:mah]
is_a: FYPO:0000002 ! cell phenotype
intersection_of: FYPO:0000002 ! cell phenotype
intersection_of: exists_during GO:0072690
intersection_of: has_part FYPO:0000952 ! vacuoles present in increased numbers during vegetative growth
intersection_of: has_part FYPO:0002787 ! small vacuoles

**Comment by ValWood** [comment]
Yes agreed, parent child.

fragmented should be defined along the lines of
Increased mitochondrial numbers and decreased mitochondrial sizes with overall mitochondrial volume same as what is observed in wild-type cells

**Comment by mah11** [comment]
Does that mean you want the existing term changed along the lines of the vacuole term?

Either way I'd prefer to put the bit about overall mitochondrial volume in a comment, rather than restrict the "more & smaller mitos" term to only the cases where total volume is (known to be) unchanged.

**Comment by ValWood** [comment]
I could not find a term for
 mitochondria present in increased numbers during vegetative growth?
which term?

**Comment by mah11** [comment]
There isn't one yet. If you need it directly, or if you want to rejig FYPO:0003810 to be like FYPO:0000281, I would add it.

**Comment by ValWood** [comment]
Could you add it and make  "fragmented mitochondria" a child.
You are right that fragmented is different. 

Its increased number, and smaller  with normal total volume (no change in biogenesis)

**Comment by mah11** [comment]
For the third time: Do you also want "fragmented mitochondria" (FYPO:0003810) to be modeled analogous to the "more smaller vacuoles" term (FYPO:0000281), or do you want it to keep its current logical definition?

**Comment by ValWood** [comment]
I could be modelled on "more smaller" this is true. But the total volume of mitochondria  is the same. 
This is critical.

**Comment by mah11** [comment]
I am asking you whether you want the logical def change.

**Comment by ValWood** [comment]
I'm going to say "yes' because i'm clearly not following, and I trust you.

**Comment by mah11** [comment]
new terms
  small mitochondria FYPO:0007193
  mitochondria present in increased numbers FYPO:0007194
converted FYPO:0003810 to small+more logical def; adjusted name & other text bits accordingly

edit file: 1a509f11fdd6222a01744ca6f1e083623d2f8aeb
release: 0fc81ac9fd6927113bee9fed420f74b25bdde377
