### ISSUE TITLE
PMID:30602572 mitochondria

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3592]
small mitochondria
enlarged mitochondria
decreased frequency of mitochondrial fission
increased frequency of mitochondrial  fission

**Comment by mah11** [comment]
large mitochondria FYPO:0007195
  decreased mitochondrial fission FYPO:0007196
  increased mitochondrial fission FYPO:0007197

see #3592 for small mitochondria

edit file: 1a509f11fdd6222a01744ca6f1e083623d2f8aeb
release: 0fc81ac9fd6927113bee9fed420f74b25bdde377
