### ISSUE TITLE
normal mitotic sister chromatid cohesion at centromere 	PMID:31483748

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3593]
https://github.com/pombase/fypo/issues/3588
I missed one:

normal mitotic sister chromatid cohesion at centromere

**Comment by mah11** [comment]
normal mitotic centromeric sister chromatid cohesion FYPO:0007198

edit file: 1a509f11fdd6222a01744ca6f1e083623d2f8aeb
release: 0fc81ac9fd6927113bee9fed420f74b25bdde377
