### ISSUE TITLE
ntr: decreased sister chromatid cohesion along chromosome arms during mitotic interphase. 

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3599]
I requested this one the wrong way around:

-mto1D: FYPO:0007190, increased sister chromatid cohesion along chromosome arms during mitotic interphase. 

   This should be the opposite: decreased sister chromatid cohesion along chromosome arms during mitotic interphase.

**Comment by mah11** [comment]
decreased sister chromatid cohesion along chromosome arms during mitotic interphase FYPO:0007209

edit file: 5cc603c841f568d699253f4bff6a21dc41c22926
release: 10695a0185790e1d3f532ded70fc91da5b700a5b
