### ISSUE TITLE
fragmented mitochondria

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3600]
small mitochondria present in increased numbers (FYPO:0003810)
 does not seem to have the synonym "fragmented mitochondria" 

and isn't a descendant of "small mitochondria"

In fact I don't think we should say

"small mitochondria present in increased numbers " because of the number of mitochondria changes during the cell cycle.

I really wanted  this term to say "total mitochondrial volume *is* normal"

So the term could be instead

"small mitochondria with normal mitochondrial volume".
(then increased number is implicit).
(yet) been observed, so we can be precise.

The case where there is more volume of mitochondria has not b

**Comment by mah11** [comment]
> small mitochondria present in increased numbers (FYPO:0003810)
> does not seem to have the synonym "fragmented mitochondria"

It does. The synonym is 'related', following the model of the vacuole term (FYPO:0000281) as promised in #3591.

> and isn't a descendant of "small mitochondria"

The link is FYPO:0003810 has_part FYPO:0007193 small mitochondria.

> In fact I don't think we should say
> 
> "small mitochondria present in increased numbers " 

This is why I asked, several times (in #3591), whether you wanted me to implement the changes to FYPO:0003810.

> "small mitochondria with normal mitochondrial volume".
> (then increased number is implicit).

I can add "normal total volume" to the name and the text and logical definitions if it's so critical, but I am not happy to leave "increased number" implicit. That is very dangerous in ontology definitions. 

Alternatively, I can revert the term to the "fragmented" text and logical definitions. Which do you prefer?

**Comment by ValWood** [comment]
Yes I didn't really understand what the changes were.

the term I want is  a term meaning
"small mitochondria with normal total mitochondrial volume"
synonym fragmented mitochondria

**Comment by mah11** [comment]
OK, I added a term:
  normal mitochondrial volume FYPO:0007210

and amended FYPO:0003810 to have FYPO:0007210 as an additional part.

edit file: 82da54e27d6bed28200e41faad48321c09b74350
release: 1d864d8e8cc54c2bd72e6c74ca913c21854f22c3
