### ISSUE TITLE
PATO:000001 may be typo

### ISSUE THREAD

**Issue by matentzn** [pombase/fypo#3605]
Hey Midori, happy new one!

I see this class in FYPO at the moment:

https://www.ebi.ac.uk/ols/ontologies/fypo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_000001&viewMode=All&siblings=true

Probably a typo (missing a 0). Talk soon!

**Comment by mah11** [comment]
yup, typo. fixed.
