### ISSUE TITLE
are these terms the same thing?

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3610]
abolished interphase microtubule nucleation
abolished cytoplasmic microtubule nucleation from iMTOC

because all interphase microtubules are cytoplasmic aren't they?

**Comment by mah11** [comment]
The difference - as the names and definitions indicate - is that FYPO:0005696 is specific for MTs nucleated from the iMTOC, whereas the parent FYPO:0004766 says that cytoplasmic MTs can be nucleated from either the iMTOC or the SPB during interphase (and the FYPO term doesn't specify whether one, the other, or both types of nucleation are abolished; I'll reword to make that clearer).

The FYPO:0004766 name doesn't include the word "cytoplasmic"; it went in with the wording requested (#2833), but that's easy to change.

action: edit FYPO:0004766 name and FYPO:0005696 text def

**Comment by mah11** [comment]
text edits done

edit file: 690b473f3eba8d04c26bfb98f47fd9caeb3742ed
release: 4a06a471321e917fd8ade1f8e492bc8e8f4e14a9
