### ISSUE TITLE
new condition

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3613]
+ galactose

**Comment by mah11** [comment]
PECO has:

- galactose MM PECO:0000289
- galactose rich medium with trace glucose PECO:0000148

which makes me think I should do the new term similarly (and as it's done for other carbon sources). Do you need "galactose rich medium" or something else?

**Comment by ValWood** [comment]
It was YES, + galactose 
so I guess that would work...

**Comment by mah11** [comment]
with both glucose and galactose, or just galactose?

**Comment by ValWood** [comment]
Yes with glucose (3%)  (so standard YES) and galactose (2%)
