### ISSUE TITLE
NETO etc. PMID:31719163

### ISSUE THREAD

**Issue by mah11** [pombase/fypo#3614]
1. normal protein localization to old growing cell tip
2. abnormal activation of bipolar cell growth in daughter cells - A cell polarity phenotype in which activation of bipolar cell growth differs between the two daughter cells formed as a result of cell division. Normally, growth begins at the old end and then becomes bipolar with similar timing in both daughter cells.
3. abolished activation of bipolar cell growth in cell derived from growing end and premature activation of bipolar cell growth in cell derived from non-growing end
4. abolished activation of bipolar cell growth in both daughter cells
5. normal activation of bipolar cell growth in cell derived from growing end and premature activation of bipolar cell growth in cell derived from non-growing end

where "cell derived from growing end" = the daughter cell that inherits the parent cell's old end
and similarly, non-growing = inherits parent cell's new end

It's kind of a cheat putting new5 and its subtypes under "cell phenotype" since these phenotypes actually need to refer to three cells (mother and both daughters) but life's too short for the additional work it would take to be precisely predantically correct.

**Comment by mah11** [comment]
normal protein localization to old growing cell tip FYPO:0007239
  abnormal activation of bipolar cell growth in daughter cells FYPO:0007240
  abolished activation of bipolar cell growth in cell derived from growing end and premature activation of bipolar cell growth in cell derived from non-growing end FYPO:0007241
  abolished activation of bipolar cell growth in both daughter cells FYPO:0007242
  normal activation of bipolar cell growth in cell derived from growing end and premature activation of bipolar cell growth in cell derived from non-growing end FYPO:0007243

edit file: dab939f14c380bf151018100a86b523ba5a08f41
release: bbd64120cb844bc7c5a1f4eee31982816414effe

**Comment by ValWood** [comment]
Oddly I don't see
abolished activation of bipolar cell growth in cell derived from growing end and premature 
or
abolished activation of bipolar cell growth in both daughter cells FYPO:0007242
under 
abolished activation of bipolar cell growth

**Comment by mah11** [comment]
Not that odd; it's sort of on purpose because the placement of these terms is a lazy cheating hack anyway (they're not quite strictly cell phenotypes because they have to refer to multiple cells). But if it really bothers you I can add a link for FYPO:0007242. It's dodgier for FYPO:0007241 because the  premature NETO in one of the cells is obvs NOT abolished NETO.

**Comment by ValWood** [comment]
I'm a bit confused, so maybe we didn't get this quite right yet...

In these cells NETO is *Always abolished*  (i.e abolished bipolar growth).
 This is a more specific observation that *in addition* the  requisite *monopolar growth*  in the abolished NETO cell is not from the normal end. (usually monopolar growth *before NETO* is from the old end, but here it can oddly occur from the new end).

Maybe we have a missing bit that in this phenotype NETO is abolished full stop. Or we need new terms?

**Comment by mah11** [comment]
> In these cells NETO is always abolished (i.e abolished bipolar growth).
> ... but here it can oddly occur from the new end).

Which cells are "these"? Similarly, what situation is "here"?

> Maybe we have a missing bit that in this phenotype NETO is abolished full stop.

Again, which is "this" phenotype?

> Or we need new terms?

Possibly. To be able to tell, it's essential to answer the above questions about what "these cells", "here", and "this phenotype" mean -- it's not even clear whether they all refer to the same thing.

This ticket documents four terms, all of which describe the goings-on of two cells each (three if you count the mother cell), and only one of which specifies abolished NETO in both cells. My worry is that if I link FYPO:0007241 to FYPO:0001018 it will imply that abolished NETO applies to both cells. (It's more likely to be OK for FYPO:0007242, and neither FYPO:0007240 nor FYPO:0007243 mentions abolished NETO.)


Tangent: With hindsight, I guess I shouldn't have taken the lazy way out - instead of shoehorning the FYPO:0007240 branch under "cell phenotype", I probably should have created a term to group the phenotypes that require looking at more than one generation (and therefore necessarily more than one cell). I won't do anything immediately but I think I will ping Nico for advice.

**Comment by ValWood** [comment]
Hmm,, I thought there was an image in  this ticket. I will dig it out.

**Comment by mah11** [comment]
> Hmm,, I thought there was an image in this ticket. 

It's very likely you're thinking of #3699. Please don't paste the same thing here.

**Comment by ValWood** [comment]
So I think the important thing is that in  #3699 

1. NETO is failed in all cells

Then (ignoring the daughter aspect for a moment)

2. In 81 out of 200 cells  (79+2)   NETO fails but the growth is also from the new end instead of the old end.
I now think that  whether this is one or both daughter cells simultaneously is less important to record. This is just the probability of the assortment based on the occurrence.


So how about we just  simplify to:

Abolished activation or bipolar growth with (monopolar) growth  from the new end
(I can add penetrance ~40% to this and it would capture the data in the figure above.

Maybe then we can then get rid of the older terms which try to describe (unnecessarily)  the paired phenotypes in each of the daughter cells?

**Comment by mah11** [comment]
1. Can we please carry this discussion on the more recent ticket, especially since your latest comment refers to a figure there?

2. You may not need the more specific terms for the older paper in #3699, but for PMID:31719163 it looked very much as though the different daughter fates were important in elucidating the role of gef1.

**Comment by mah11** [comment]
Any required new terms can be dealt with on #3699, and I'll open new tickets for anything Nico and/or DavidOS recommend for the paths involving these terms.
