### ISSUE TITLE
cell length size odd reasoning?

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3615]
normal vegetative cell size
--normal vegetative cell length
----normal vegetative cell size

**Comment by mah11** [comment]
Where do you see this, and what is/are the relationship type(s)?

**Comment by ValWood** [comment]
in canto- I don't know the relationship types...

**Comment by mah11** [comment]
Thanks. I think I see what's happening. FYPO asserts 'normal cell size' has_part 'normal cell length'. The reasoner infers 'normal cell length' is_a 'normal cell size' from PATO (length has an is_a path to size). Canto doesn't show the relationship type, so there's no apparent difference between a has_part link and an is_a link.

The only thing I think I can do to make the Canto display stop looking like this is to remove the asserted has_part link. OK?

**Comment by ValWood** [comment]
Yep, I think its probably best to remove it here (since they are connected anyway)

So we will see:
normal vegetative cell size
--normal vegetative cell length
right?

**Comment by mah11** [comment]
done; suck it & see what shows up

edit file: 7bfe422406ff7bef832d7ccac3ef949b86f6e2af
release: 4e15e948929138259d052e330e8a766b1a0324c5
