### ISSUE TITLE
NTR;decreased protein localization to kinetochore during mitotic metaphase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3616]
decreased protein localization to kinetochore during mitotic metaphase

standard def
PMID:20739936

**Comment by mah11** [comment]
decreased protein localization to kinetochore during mitotic metaphase FYPO:0007244

edit file: 7bfe422406ff7bef832d7ccac3ef949b86f6e2af
release: 4e15e948929138259d052e330e8a766b1a0324c5
