### ISSUE TITLE
ntr normal meiotic spindle pole body etc PMID:20980623

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3617]
normal meiotic spindle pole body 
PMID:20980623

**Comment by ValWood** [comment]
abolished protein localization to meiotic spindle pole body during anaphase II

**Comment by mah11** [comment]
normal meiotic spindle pole body FYPO:0007245
  abolished protein localization to meiotic spindle pole body during anaphase II FYPO:0007246

edit file: 7bfe422406ff7bef832d7ccac3ef949b86f6e2af
release: 4e15e948929138259d052e330e8a766b1a0324c5
