### ISSUE TITLE
Inexact synonyms should be described using broadMatch or relatedMatch instead of exactMatch

### ISSUE THREAD

**Issue by matentzn** [pombase/fypo#3619]
http://purl.obolibrary.org/obo/FYPO_0000540
http://purl.obolibrary.org/obo/FYPO_0000360

**Comment by mah11** [comment]
I've just changed all of the "SGD:phenotype_annotation" synonyms to relatedMatch - that'll do, given how differently they've developed their phenotype ontology and annotations.

**Comment by matentzn** [comment]
Wow cool! Thanks!
