### ISSUE TITLE
add synonyms "decreased blah cell size

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3621]
FYPO:0000645
Ontology | fission_yeast_phenotype
Term name | small vegetative cell

because normal and elongated use normal and increased size

**Comment by mah11** [comment]
done (reopen if I missed any)

edit file: 8c52e7fd7b3bb5712c8297e39ef38b050e2352d3
release: 7aa12cd199db7e29e5ab119832b3473b9a78b5e8
