### ISSUE TITLE
abolished membrane  lipid binding. PMID:31178220

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3622]
abolished membrane lipid binding
decreased membrane lipid binding

**Comment by mah11** [comment]
How is this defined? Binding to a lipid in a membrane? (There's no GO MF term, nor a chemical classification for "membrane lipid", nor should there be.)

**Comment by ValWood** [comment]
Yes, "binding to a lipid in a membrane"

although I guess all of our existing "lipid binding" terms also refer to membrane lipids.

It would be useful to specifiy this context for inferring  things later (because this phenotype will usually mean that a protein is no longer anchored to a membrane)

**Comment by mah11** [comment]
abnormal lipid binding FYPO:0007250
  decreased lipid binding FYPO:0007251
  decreased membrane lipid binding FYPO:0007252
  abolished membrane lipid binding FYPO:0007253

edit file: 8c52e7fd7b3bb5712c8297e39ef38b050e2352d3
release: 7aa12cd199db7e29e5ab119832b3473b9a78b5e8
