### ISSUE TITLE
NTR PMID:31575705 fft3

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3624]
normal replication restart
synonym normal HR-mediated fork restart
and
decreased

**Comment by mah11** [comment]
In GO, "replication restart" is a related synonym for replication fork processing. I'll use GO's names & synonyms.

**Comment by mah11** [comment]
normal replication fork processing FYPO:0007254
decreased replication fork processing FYPO:0007255

edit file: 8c52e7fd7b3bb5712c8297e39ef38b050e2352d3
release: 7aa12cd199db7e29e5ab119832b3473b9a78b5e8
