### ISSUE TITLE
Missing parents/ and new term

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3625]
abnormal protein localization to meiotic spindle  
abnormal protein localization to meiotic spindle pole body  

should also be under "during meiotic cell cycle"

(difficult to find after "abnormal protein localization" as you need to know to look under "cytoskeleton")

**Comment by ValWood** [comment]
New term request
 premature localisiation to spindle pole body during meiotic prophase
PMID:22438582

**Comment by mah11** [comment]
> premature localisiation to spindle pole body during meiotic prophase

just to confirm: protein localization?

**Comment by ValWood** [comment]
Oh yes!

**Comment by mah11** [comment]
> abnormal protein localization to meiotic spindle
> abnormal protein localization to meiotic spindle pole body
> 
> should also be under "during meiotic cell cycle"

Both of these terms do have paths to "abnormal protein localization during meiotic cell cycle".

**Comment by ValWood** [comment]
hmm, so they do...

**Comment by mah11** [comment]
new term is

premature protein localization to meiotic spindle pole body during prophase I FYPO:0007256

edit file: 8c52e7fd7b3bb5712c8297e39ef38b050e2352d3
release: 7aa12cd199db7e29e5ab119832b3473b9a78b5e8
