### ISSUE TITLE
New terms for PMID:22438582

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3626]
protein localization to meiotic spindle pole body delayed in meiosis I

premature protein localization to meiotic spindle pole body
synonym precocious

attenuated protein localization to meiotic spindle pole body
(using analog sensitive mutant  localization is stopped abruptly)

protein localization to meiotic spindle pole body in meiosis I

increased meiotic  SPB duplication
exact synonym meiotic SPB overamplification
exact  spindle pole bodies present in increased numbers during meiosis

**Comment by mah11** [comment]
> attenuated protein localization to meiotic spindle pole body
> (using analog sensitive mutant localization is stopped abruptly)

"Attenuated" means "weakened" or "thinned". That doesn't sound like what's happening here. I had a quick look at the paper, and I would just use "abolished".

> protein localization to meiotic spindle pole body in meiosis I

What's the qualifier for this one? Increased, decreased, normal etc.?

> increased meiotic SPB duplication
> exact synonym meiotic SPB overamplification
> exact spindle pole bodies present in increased numbers during meiosis

 These can't all be exact synonyms. Increased SPB duplication is a process phenotype (exact synonym "overamplification" would be OK), but SPB number is a physical quality (roughly, structural) phenotype.

**Comment by ValWood** [comment]
OK yes abolished makes sense. Iwasn't thinking that the phenotype is only what happens after the inhibitor is added.

protein localization to meiotic spindle pole body in meiosis I
was supposed to be
premature 
and
delayed

OK related

**Comment by mah11** [comment]
A little confused now ... there's a request for

- premature protein localiziation to spindle pole body during meiotic prophase

in #3625 (and that one's prophase I, right?), and these two in various places on this ticket:

- premature protein localization to meiotic spindle pole body
- premature protein localization to meiotic spindle pole body in meiosis I

Which one(s) do you actually want? I'll add all 3 if you need them, but if you only want to use the "during prophase I" term I won't bother with the less specific ones.

**Comment by mah11** [comment]
Here's what I've added so far:

  delayed onset of protein localization to meiotic spindle pole body during meiosis I FYPO:0007257
  abnormal meiotic spindle pole body duplication FYPO:0007258
  increased meiotic spindle pole body duplication FYPO:0007259
  abnormal cellular process during meiotic cell cycle FYPO:0007260

Let me know if you need any more SPB localization terms, or close this.

edit file: 8c52e7fd7b3bb5712c8297e39ef38b050e2352d3
release: 7aa12cd199db7e29e5ab119832b3473b9a78b5e8

**Comment by ValWood** [comment]
I got everything I needed from these
