### ISSUE TITLE
 telomere tethering

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3628]
FYPO:0004790 | abnormal telomere-nuclear envelope distance
-- | --

first  does this have
decreased telomere tethering at nuclear periphery
as a synonym?

Also could these say "mitotic" explicitly (they are defined vegetatively)

**Comment by mah11** [comment]
> first does this have
> decreased telomere tethering at nuclear periphery
> as a synonym?

No, it has a link - FYPO:0004790 output_of FYPO:0001515 ! abnormal telomere tethering at nuclear periphery. If we did add a synonym, it would seem a bit odd; the synonym couldn't be exact anyway. We don't have a 'decreased tethering" term but I can add one if you need it.

> Also could these say "mitotic" explicitly (they are defined vegetatively)

Is the phenotype only seen during mitosis? If so, it's easy enough to edit the name, but that will make the actual meaning a bit narrower than it is now - it's defined as restricted to vegetative growth, but implicitly covers all of the mitotic cell cycle.

**Comment by ValWood** [comment]
I always get a bit confused by these


FYPO:0004790 | abnormal telomere-nuclear envelope distance
-- | --


is the obervation  but this indicates that the  telomeres are not tehterd.

I think we should have the term
decreased telomere tethering at nuclear periphery
(I was going to suggest merging 
abnormal telomere-nuclear envelope distance
as related, but it has kids)

No it begins at the end of mitosis and lasts until  next anaphase

**Comment by mah11** [comment]
new term is
  decreased telomere tethering at nuclear periphery during vegetative growth FYPO:0007261

also edited some term names to make "vegetative" explicit

edit file: 8c52e7fd7b3bb5712c8297e39ef38b050e2352d3
release: 7aa12cd199db7e29e5ab119832b3473b9a78b5e8
