### ISSUE TITLE
	PMID:23084836 more

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3633]
normal telomere clustering during vegetative growth
(clustering is the connecting of the telomeres as opposed to tethering which is attaching this cluster to the nuclear envelope)

decreased Tf body tethering to centromere (vegetative)

(we have other Tf body terms)

decreased Tf clustering (as above the clustering applies only to the Tfs clustering together, it is separable from the tethering)

increased TF body tethering to centromere

decreased protein localization to nucleoplasm during DNA damage

**Comment by mah11** [comment]
> decreased Tf clustering

Is this one supposed to say "Tf body clustering" to match the others?

**Comment by mah11** [comment]
> decreased protein localization to nucleoplasm during DNA damage

"... during cellular response to DNA damage", OK? because "DNA damage" isn't a phase or GO process

**Comment by mah11** [comment]
>>   decreased Tf clustering
> 
> Is this one supposed to say "Tf body clustering" to match the others?

Ignore this - I just re-read the definition we have for "decreased Tf body formation" (FYPO:0005545) and realized it means the same thing. Adding synonyms ...

**Comment by ValWood** [comment]
yep

**Comment by mah11** [comment]
new terms
  normal interphase mitotic telomere clustering during vegetative growth FYPO:0007269
  decreased Tf body tethering to centromere FYPO:0007270
  increased Tf body tethering to centromere FYPO:0007271
  decreased protein localization to nucleoplasm during cellular response to DNA damage FYPO:0007272

I used GO:0120110 for the name and xp for FYPO:0007269. I made the new Tf body terms siblings of the existing one (not term*s* plural ;) ) under abnormal chromatin organization. Let me know if any of that doesn't work.

edit file: ecf7b035ec920c8a0e9ab5ae451caccb744f50ed
release: 252448fdc2c6a1b38d6dfc10b68077832b0b9a1c

**Comment by ValWood** [comment]
normal interphase mitotic telomere clustering during vegetative growth FYPO:0007269

sounds strange to say 'mitotic' telomeres in interphase

Can we change this one to
"normal  mitotic interphase telomere clustering" ?

**Comment by mah11** [comment]
I can muck with FYPO wording when I'm back, but you might want to ping GO as well, because I just copied 'n pasted the GO:0120110 name.

**Comment by ValWood** [comment]
Actually let's keep it as it is for now, I think I might need to revise the GO terms a bit anyway but waiting for suitable papers.

Maybe we could just remove
"during vegetative growth " because that's implicit from "mitotic"?
