### ISSUE TITLE
decreased cortical tubular ER remodelling follow on  PMID:32023460 Zhang 

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3634]
I forgot this
increased cortical tubular ER remodelling

Also some minor weirdness

FYPO:0007265 | long eisosome filaments present in decreased numbers
sewems to be a descendant of itself

**Comment by ValWood** [comment]
out of my tickets could you do this one first if possible.
I 've had this session hanging around for a while because I missed some.
Cheers

**Comment by mah11** [comment]
new term
  increased cortical endoplasmic reticulum remodeling FYPO:0007273

edit file: acfc56e54aff10c2d3a89424cf1ee7daa2abd8a7
release: e5c5660840e7d9f5e51fb60aeb4d1f98e94d4ede
