### ISSUE TITLE
mitochondrial inheritance phenotypes PMID:31582398

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3639]
FYPO:0000906 | abnormal mitochondrion inheritance

need meiotic and mitotic terms

NEW abnormal mitochondrion inheritance during meiosis
synonym mitochondrial mixing during meiosis (author suggestion)

NEW normal mitochondrion inheritance during meiosis
increased mitochondrial segregation during meiosis (author suggestion)

**Comment by mah11** [comment]
Are these really during *meiosis* (the nuclear divisions), or during meiotic cell cycle?

**Comment by ValWood** [comment]
Hmm, I thought meiosis because it's to do with what happens to the mitochondria *at division*. It feels correct to me.

**Comment by mah11** [comment]
but meiosis is defined as nuclear division, and mitochondria aren't in the nucleus

**Comment by ValWood** [comment]
its what happens to the mitochondria during nuclear division.

<img width="162" alt="Screenshot 2020-03-17 at 11 44 03" src="https://user-images.githubusercontent.com/7359272/76853282-e35fe980-6844-11ea-8fa7-ab1c23082fc4.png">


you are right though
"during meiotic cell cycle" would be better as we should use the phase terms for during.

**Comment by mah11** [comment]
included a couple new grouping terms:
  abnormal mitochondrion inheritance FYPO:0007274
  abnormal mitochondrion inheritance during meiotic cell cycle FYPO:0007275
  normal mitochondrion inheritance during meiotic cell cycle FYPO:0007276
  normal cellular process during meiotic cell cycle FYPO:0007277

meiotic cell cycle ones have "during meiosis" in related synonyms

edit file: 4595eab9cbfee72ca0a5ff98d8d3c1ee1d1ac872
release: dc0e84f93ec4661e4b482ee0e97f8529ab864359
