### ISSUE TITLE
PMID:17289569 SHREC

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3640]
NTR normal protein localization to euchromatin

increased polymerase II occupancy
(I guess this would be something like 'increased level of polymerase II in association with  euchromatin?"

**Comment by mah11** [comment]
> increased polymerase II occupancy
> (I guess this would be something like 'increased level of polymerase II in association with euchromatin?"

This would be  "increased protein localization to euchromatin"with pol II in an extension.

Note: strictly speaking, "increased protein level in euchromatin" might be more accurate, but using localization would follow our current practice for nearly everything else. I strongly suspect a lot of our "protein localization to x" phenotype terms are used for things that really only look at level in x, but I haven't had brain space to make it any priority at all to sort out :P

**Comment by mah11** [comment]
normal protein localization to euchromatin FYPO:0007278
  increased protein localization to euchromatin FYPO:0007279

edit file: 4595eab9cbfee72ca0a5ff98d8d3c1ee1d1ac872
release: dc0e84f93ec4661e4b482ee0e97f8529ab864359
