### ISSUE TITLE
PMID:32012158 	Meiotic gene silencing complex MTREC/NURS r

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3642]
These assays  are really assessing the level of specific proteins in the foci.

So I think they should be
NTR decreased  protein localization to exosome foci
NTR normal   protein localization to exosome foci
NTR abolished  protein localization to exosome foci

and
NTR normal level of  meiosis gene mRNA during vegetative growth

**Comment by mah11** [comment]
Is this a request for new terms or for changes to existing terms? If it's about existing terms, please indicate which ones (IDs best, or at least the current term names).

**Comment by ValWood** [comment]
All new terms

**Comment by mah11** [comment]
Actually, given that GO:1990251 says nuclear exosome focus = Mmi1 focus, only one new localization term needed. Adjusted FYPO names & synonyms to match the recent GO swap (see FYPO:0002964 & FYPO:0003042).

new terms are:
  decreased protein localization to nuclear exosome focus FYPO:0007280
  normal level of meiosis gene mRNA during vegetative growth FYPO:0007281

edit file: 4595eab9cbfee72ca0a5ff98d8d3c1ee1d1ac872
release: dc0e84f93ec4661e4b482ee0e97f8529ab864359
