### ISSUE TITLE
term merge?

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3645]
FYPO:0002792 | small vacuoles present in increased numbers during cellular hypotonic response

and

FYPO:0004483 | abnormal vacuole fusion during cellular hypotonic response

are 2 ways of saying the same thing

**Comment by mah11** [comment]
Not exactly. For one thing, FYPO:0002792 is a physical/structural phenotype, whereas FYPO:0004483 is a process phenotype. FYPO:0004483 is also a bit broader, because abnormal could encompass increased, delayed, etc. as well as decreased.

I'll add an output link.

**Comment by mah11** [comment]
link added

edit file: 4595eab9cbfee72ca0a5ff98d8d3c1ee1d1ac872
release: dc0e84f93ec4661e4b482ee0e97f8529ab864359
