### ISSUE TITLE
ntr PMID:19942659 (galactosylation)

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3647]
decreased protein galactosylation during vegetative growth
normal  protein galactosylation during vegetative growth
decreased UDP-glucose 4-epimerase activity
normal UDP-glucose 4-epimerase activity
decreased UDP-galactose level
increased cytosolic UDP-galactose level

**Comment by mah11** [comment]
decreased protein galactosylation during vegetative growth FYPO:0007287
  normal protein galactosylation during vegetative growth FYPO:0007288
  abnormal UDP-glucose 4-epimerase activity FYPO:0007289
  decreased UDP-glucose 4-epimerase activity FYPO:0007290
  decreased cellular UDP-galactose level FYPO:0007291
  increased cytosolic UDP-galactose level FYPO:0007292


edit file: 22a612b4ff712f692916cf9c9eed8cfe54911461
release: 66f82ff26aaf76c5f756b258b6b939b9af2197e2
