### ISSUE TITLE
synonyms etc 	PMID:10087262 mok1/ags1

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3648]
The paper I was curating yesterday had a different name for our "pear shaped"
-tadpole!
we should add that:

<img width="328" alt="Screen Shot 2020-03-18 at 15 26 07" src="https://user-images.githubusercontent.com/7359272/77093682-38e1f500-6a03-11ea-97b6-1b7f7a9819ef.png">

**Comment by ValWood** [comment]
Also, they describe a mutant as side-by-side
The other was observed as pairs of di- vided cells associated side-by-side (12%), the cell wall of which appeared fragile and often lysed upon division.


I  *think*  this might be
" FYPO:0003213 explosive cytokinetic cell separation resulting in vegetative cell lysis"
at least that is what I used. Can you add as a synonym if you agree?

**Comment by ValWood** [comment]
Then because they looked

FYPO:NTR | pear-shaped vegetative cell with actin loclized to rounded (new) end

In tadpole cells, cortical F-actin localized exclusively in the swollen tips (Fig. 4 a, middle). Calcofluor-staining showed a huge accumulation of cell wall material in the swollen parts of the tadpole cells (Fig. 4 b, arrow).
Either the new or old end became swollen (the new end is the end that is produced after cytokinesis; the old end is the one that has already existed in the previous cycle). 


In Fig. 4 c, asymmetrical cell swelling that took place in the new end (marked with ar- rows) is shown. This analysis suggested that overproduction of Mok1 inhibited the translocation of F-actin (and cell wall materials) from one end to the other.

**Comment by ValWood** [comment]
NTR: abolished spore germination
I am sure we must have a term meaning this, but for some reason I cannot locate.

**Comment by ValWood** [comment]
NTR  lysed spherical vegetative cell
descendant of

FYPO:0004104 | inviable spherical vegetative cell

**Comment by ValWood** [comment]
finally, I used

FYPO:0006802 | dispersed filamentous actin

for "delocalised actin" 

add as synonym?

**Comment by mah11** [comment]
> NTR: abolished spore germination
> I am sure we must have a term meaning this, but for some reason I cannot locate.

Use 'inviable spore' FYPO:0002151 - see #783

**Comment by mah11** [comment]
> I think this might be
> "FYPO:0003213 explosive cytokinetic cell separation resulting in vegetative cell lysis"

I guess it could be - it's easier to tell in the paper cited for the def, because it's more recent and has better microscopy, including time-lapse. I don't have a problem with using it here.

> pear-shaped vegetative cell with actin loclized to rounded end

It sounds like the "tadpole" synonym should go with this new term, rather than the generic "pear" - yes/no?

**Comment by ValWood** [comment]
It could do. However, I think the tadpole probably described the shape only....

**Comment by mah11** [comment]
new terms:
  lysed spherical vegetative cell FYPO:0007293
  pear-shaped vegetative cell with actin localized to rounded end FYPO:0007294

also added synonyms; reopen if I missed anything among all the comments

edit file: 22a612b4ff712f692916cf9c9eed8cfe54911461
release: 66f82ff26aaf76c5f756b258b6b939b9af2197e2
