### ISSUE TITLE
PMID:32053662. (SRE)

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3649]
increased transcription from SRE2 promoter
decreased transcription from SRE2 promoter

we have
FYPO:0003251 | decreased transcription from SRE promoter
but there are 2 SRE promoters apparently SRE1 &2

if we can't easily disambiguate these I can move to a comment.

Also for this paper need new conditions
clotrimazole and terbinafine (both ergosterol biosynthesis inhibitors inducing hypoxia)

**Comment by mah11** [comment]
The best way to disambiguate is to get SO terms for SRE1 and SRE2. If that doesn't work out, I can still add specific terms if we can include distinguishing features (for promoters, usually consensus sequences).

**Comment by ValWood** [comment]
OK I misunderstood.  The paper refers to SRE2 and SRE3, these are just multiple copies of the motif (called Sre)

**Comment by mah11** [comment]
PECO:0000359 + clotrimazole
PECO:0000360 + terbinafine

**Comment by mah11** [comment]
If SRE2 and SRE3 are just copies of the same sequence, that doesn't call for separate terms in SO or FYPO, I think.

**Comment by ValWood** [comment]
Agree, that's what I meant....

**Comment by ValWood** [comment]
I will still require

increased/decreased transcription from SRE promoter. 
At least we have:

increased transcription from CRE promoter  
increased transcription from HSE promoter  
increased transcription from MCB promoter

**Comment by ValWood** [comment]
Oh we have decreased, just need increased

**Comment by mah11** [comment]
increased transcription from SRE promoter FYPO:0007297

edit file: 6679a5c6c8160582564d6e8b3d4fa3e1c8bcde4a
release: 9d31f52f720cc68d43dfdf1fedacbeea6c7a5906
