### ISSUE TITLE
chromatin silencing at telomere -> subtelomere

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3653]
decreased chromatin silencing at telomere

should merge into  

decreased chromatin silencing at subtelomere

and similar

**Comment by mah11** [comment]
merged FYPO:0003880 into FYPO:0004604
renamed other terms

edit file: 1406da4f08419332f5edf314d3b32c69f3d7202f
release: e78a27623827f37533246f6b61131aff7b85e8ed
