### ISSUE TITLE
PAC formation phenotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3655]
decreased protein aggregate center/centre formation
normal protein aggregate center/centre formation
abolished protein aggregate center/centre formation
PMID:32075773

**Comment by ValWood** [comment]
plus
 protein absent from cell during heat shock

**Comment by mah11** [comment]
https://github.com/geneontology/go-ontology/issues/19172

**Comment by mah11** [comment]
abnormal protein aggregate center formation FYPO:0007298
  decreased protein aggregate center formation FYPO:0007299
  abolished protein aggregate center formation FYPO:0007300
  normal protein aggregate center formation FYPO:0007301
  protein absent from cell during heat shock FYPO:0007302


edit file: 6679a5c6c8160582564d6e8b3d4fa3e1c8bcde4a
release: 9d31f52f720cc68d43dfdf1fedacbeea6c7a5906
