### ISSUE TITLE
related phenotype "metaphase arrest"

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3656]
I believe that these are referring  (usually) to the same phenotype

13 | abnormal mitotic cell cycle arrest with condensed chromosomes (FYPO:0003738) [single allele genotypes] | ...
-- | -- | --
  | 31 | abnormal cell cycle arrest in mitotic metaphase (FYPO:0000620) [single allele genotypes]

in case not , I think we should create a term
 abnormal cell cycle arrest with condensed chromosomes in mitotic metaphase
as a child of both.

I will move down the ones which are clearly metaphase  from either parent over time.

**Comment by mah11** [comment]
> I believe that these are referring (usually) to the same phenotype
> abnormal mitotic cell cycle arrest with condensed chromosomes (FYPO:0003738)
> abnormal cell cycle arrest in mitotic metaphase (FYPO:0000620)

We established ages ago that they're not the same; "with condensed chromosomes" is broader because chromosome condensation starts in prophase and ends in telophase (see #2593 and #3206).

**Comment by ValWood** [comment]
That is probably true, but  the terms are often *used* for the same phenotype. This means that we lose important specificity, and the annotations are a bit inconsistent. I'm not really sure there is even any arrest in anaphase, the checkpoint is at the metaphase/anaphase transition, then there are some checkpoints that I don't yet fully understand in telophase (cytokinesis checkpoint). The chromosomes are probably uncondensed by then because the next round of replication will already have begun.

So the child term will help to make the annotation as specific as it could have been.
We will probably end up with no direct annotations to the parent (not sure yet).

**Comment by mah11** [comment]
Is there ever arrest with *un*condensed chromosomes in what otherwise looks like metaphase? If not, I can explicitly add "with condensed chromosomes" to the existing metaphase arrest term (text, links, etc.).

>  I'm not really sure there is even any arrest in anaphase, the checkpoint is at the metaphase/anaphase transition,

That doesn't matter for the current purpose - it's still entirely consistent with the point that "with condensed chromosomes" is broader than "during metaphase".

**Comment by ValWood** [comment]
> Is there ever arrest with uncondensed chromosomes in what otherwise looks like metaphase? If not, I can explicitly add "with condensed chromosomes" to the existing metaphase arrest term (text, links, etc.).

@JackyVH  would need to confirm.

Cells can arrest at metaphase with uncondensed chromosomes if condensation is compromised.

Or they arrest at metaphase with condensed chromosomes if the spindle checkpoint cannot be satisfied.

I think, but am not sure that ALL arrest with condensed chromosomes is metaphase arrest (despite the fact that chromosomes remain condensed until telophase), because there are no checkpoints  after the metaphase/anaphase transition. The proposed child will make this clear over time.

**Comment by mah11** [comment]
abnormal cell cycle arrest in mitotic metaphase with condensed chromosomes FYPO:0007303

edit file: 6679a5c6c8160582564d6e8b3d4fa3e1c8bcde4a
release: 9d31f52f720cc68d43dfdf1fedacbeea6c7a5906
