### ISSUE TITLE
compound terms for modifications

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3658]
I don't think we should have these compound modification terms:

increased histone H4-K5, H4-K8, H4-K12 and H4-K16 acetylation at centromere outer repeat during vegetative growth

a) it isn't sustainable
b) we will only get data  for  proximal residues  (i.e the size of the mass spec fragment)
c) it would be better to be able to retrieve  all
increased H4-K5
increased  H4-K8
increased  H4-K12
individually but some modifications don't have terms, so the individual modifications are not inherited
d) Because the are observed together at the same time  doesn't indicate a dependency

So, if you could check that the individual modification phenotypes exist for all of the compound terms, I'll decompose the annotations.

tks

**Comment by mah11** [comment]
note to self: add "at otr" terms for H4K5 | H4K8 | H4K12 | H4K16 Ac.

**Comment by mah11** [comment]
OK, these have gone obsolete:
  FYPO:0002383
  FYPO:0002384
  FYPO:0003219
  FYPO:0003220
  FYPO:0004323
  FYPO:0005317
  FYPO:0005337

and these are new:
  increased histone H4-K5 acetylation at centromere outer repeat during vegetative growth FYPO:0007308
  increased histone H4-K8 acetylation at centromere outer repeat during vegetative growth FYPO:0007309
  increased histone H4-K12 acetylation at centromere outer repeat during vegetative growth FYPO:0007310
  increased histone H4-K16 acetylation at centromere outer repeat during vegetative growth FYPO:0007311
  increased histone H4-K5 acetylation at centromere central core during vegetative growth FYPO:0007312
  increased histone H4-K8 acetylation at centromere central core during vegetative growth FYPO:0007313
  increased histone H4-K12 acetylation at centromere central core during vegetative growth FYPO:0007314
  increased histone H4-K8 acetylation at subtelomeric heterochromatin during vegetative growth FYPO:0007315

edit file: 6679a5c6c8160582564d6e8b3d4fa3e1c8bcde4a
release: 9d31f52f720cc68d43dfdf1fedacbeea6c7a5906
