### ISSUE TITLE
Complex equivalence needs fixing (P-bodies present in decreased numbers)

### ISSUE THREAD

**Issue by matentzn** [pombase/fypo#3659]
Currently http://purl.obolibrary.org/obo/FYPO_0001897 and http://purl.obolibrary.org/obo/FYPO_0001898 are equivalent with each other. The reason for this is as follows:

FYPO_0001897 has the same EQ as FYPO_0001898, only that it `exists_during` some SCO vegetative growth phase. Now the problem is that both are infererred to be children of `altered level of macromolecular complex`, which in turn is a child of `abnormal sub-cellular component during vegetative growth` - which makes all of the classes mentioned here inheri the `exists_during` some SCO vegetative growth phase restriction. Including FYPO_0001898. This makes FYPO_0001897 and FYPO_0001898 equivalent. I think this is the last problem we have! Let me know when you found a solution.

:)

**Comment by mah11** [comment]
Conceptually easy - I'll add a new `altered level of macromolecular complex` term that isn't restricted to vegetative growth (and edit the name of FYPO:0003684).

**Comment by matentzn** [comment]
Thats great! :) Thanks.

**Comment by mah11** [comment]
This is now done in fypo_edit.obo - the new term is
altered level of macromolecular complex FYPO:0007316

and FYPO:0003684 has been renamed.

(in release c3bdd006d9fd63f160e0f3c85bb7dce32f9bbb4e)
