### ISSUE TITLE
increased protein trna binding PMID:15632064

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3668]
increased protein trna binding

we have normal tRNA binding

also
decreased mitochondrial tRNA 3'-end processing

**Comment by mah11** [comment]
increased tRNA binding FYPO:0007325
  decreased mitochondrial tRNA 3'-end processing FYPO:0007326

edit file: 6ddc8dcd95ec79f7c7bc17a67ecb9d46409985ec
release: 84789e208e241b6502caf8a570be07496eea232a

**Comment by ValWood** [comment]
I don't see 'decreased', I only see abnormal
