### ISSUE TITLE
kinetochore retrieval 

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3669]
normal kinetochore retrieval in  mitotic metaphase
abnormal kinetochore retrieval in mitotic metaphase

  ( kinetochores are  clusstered in anaphase b and remain clustered at the nuclear envelope in. interphase. In mitosis when chromosomes align, these 'unclustered kinetochores' can then be retrieved by the spindle machinery and correctly biorientated). This refers to the failure of this process.

required to fix
also check dam1 PMID:22375062
FYPO:0001779 | abnormal centromere clustering at nuclear periphery
(this isn't about abnormal clustering, but. about not fixing  'lost kinetochores' when they occur)

**Comment by ValWood** [comment]
actiually, I just remembered there is a GO term for the normal process.....

https://www.ebi.ac.uk/QuickGO/term/GO:1990942
mitotic metaphase chromosome recapture

**Comment by mah11** [comment]
Yep, and the FYPO terms exist too:

FYPO:0005362 abnormal mitotic metaphase chromosome recapture
FYPO:0005720 normal mitotic metaphase chromosome recapture

They have a slew of synonyms, tho not including the exact wording "kinetochore retrieval in mitotic metaphase". Want more synonyms?

**Comment by ValWood** [comment]
Won't harm. I meant to go back and check that after I found the GO term but then got side tracked ;O)

**Comment by mah11** [comment]
synonyms added

edit file: 6ddc8dcd95ec79f7c7bc17a67ecb9d46409985ec
release: 84789e208e241b6502caf8a570be07496eea232a
