### ISSUE TITLE
abnormal spindle pole body insertion  (into nuclear membrane)

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3670]
There is a term

FYPO:0003569 | abnormal establishment of mitotic spindle pole body localization to nuclear envelope, with spindle pole body in cytoplasm

which seems a bit like abnormal insertion?

THere is also a term

FYPO:0003568 | spindle pole body unanchored to nuclear envelope

with insertion synonyms. However  insertion is separable from anchoring

The SPB is already anchored to the cytoplasmic side of the nuclear envelope before it is inserted into a fenestra. I think the insertion involves (possibly) some microtubule based process. And possibly one of those complexes that makes membrane pores. Not  well studied in pombe but more complex than anchoring (although there is some anchoring to the sides of the pore involved)

I think the term for this should have 'insertion' in it's name. Maybe rename the first term (if this is equivalent). I can  review the annotations.

note to self check curs/97c70bbdfd19df1d

**Comment by mah11** [comment]
Well, those terms date to mid-2014, so they would reflect thinking from over 5 years ago.

The name of FYPO:0003568 is worded as if it's a structure phenotype, but the definition and parentage say it's a process phenotype. Odd; I don't remember why I/we did it that way but it looks funny now.

When you figure out what specific changes will work, let me know and I'll implement.

**Comment by ValWood** [comment]
OK  this was probably me- describing what I see but not really knowing what I am looking at ;)

The biology is still hazy but I think we can improve. I'll update the ticket week sometime. The current annotations indicate that this is probably what was meant here but I will revisit the papers

This is good- we captured the annotations, and now we can consolidate.

**Comment by mah11** [comment]
reopen if #3753 didn't cover everything
