### ISSUE TITLE
lipid droplet PMID:26990381

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3675]
| decreased  triglyceride level
in lipid droplet

**Comment by ValWood** [comment]
abolished lipid droplet formation

**Comment by mah11** [comment]
decreased triglyceride level in lipid droplet FYPO:0007342
  abolished lipid droplet formation FYPO:0007343

edit file: edc1833f265156f8ac09560413df1d4a56a6a2a8
release: f66d90f3ae622e1b9fa51878bf403d9b115adac1
