### ISSUE TITLE
decreased stress granule disassembly

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3677]
I missed one from
https://github.com/pombase/fypo/issues/3664#

decreased stress granule disassembly |

**Comment by ValWood** [comment]
actually  I don't need this, it was assembly not disassembly.

So I  used

FYPO:0007319 | decreased stress granule assembly during glucose starvation

but this looks a bit odd because for all of the others I did not have the "during glucose starvation" I used the limited glucose condition as recommended.

How should we make consistent? rename 
FYPO:0007319 | decreased stress granule assembly during glucose starvation
to
FYPO:0007319 | decreased stress granule assembly 

and check that existing annotation has the "limited glucose ' condition?

**Comment by mah11** [comment]
> How should we make consistent?

Answer: figure out whether the conditions used meet the "starvation" criteria. If they're still doing vegetative growth, don't use a "glucose starvation" term.

As I mentioned earlier (https://github.com/pombase/fypo/issues/3664#issuecomment-607722018), FYPO uses "glucose starvation" specifically to mean the situation where cells run low enough on glucose for long enough to trigger mating etc., and accordingly houses the terms outside the "during vegetative growth" branches. If cells have less glucose than in typical "replete" growth medium, but enough to keep them from mating, we're counting that as vegetative growth and the "glucose starvation" terms shouldn't be used. That's the distinction; I should add comments to that effect.

The question of glucose levels has plagued us for years - see #2300 and the tickets referenced therein if you want to revisit a head-spinner :P If it weren't for the exiting-vegetative-growth angle I would plump for trashing all the glucose starvation terms in favor of adding conditions.

**Comment by ValWood** [comment]
Ah OK, I forgot you already told me that.

The comment will be helpful, might need an annotation review so I will open a ticket for that.

**Comment by mah11** [comment]
comments added

edit file: edc1833f265156f8ac09560413df1d4a56a6a2a8
release: f66d90f3ae622e1b9fa51878bf403d9b115adac1
