### ISSUE TITLE
PECO should be renamed and use different IDSPACE

### ISSUE THREAD

**Issue by matentzn** [pombase/fypo#3678]
As per our length email trails about the issue, the PECO namespace is conflicting now with other ontologies. We need to:

1) rename peco.obo to pbeco.obo and change all ids from PECO:001 to PBECO:001
2) make sure CANTO handles that change, i.e. all references to PECO:001 are changed to PBECO:001

Both of the above should happen simultaneously and need to be coordinated between @mah11 and @kimrutherford .

Happy to help if needed :)

**Comment by mah11** [comment]
We have a ticket for this already, so I'm going to close this one to avoid duplication & confusion. See https://github.com/pombase/pombase-chado/issues/766
