### ISSUE TITLE
could these be a single term?

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3679]
increased level of glucose starvation gene mRNA during vegetative growth
  | git10-201 (L338P aa)
+ | increased level of glucose-repressed gene mRNA during vegetative growth
  | git11Δ,   git5Δ,   gpa2Δ

**Comment by mah11** [comment]
damned if I know; happy to merge if they do mean the same thing but I don't know this biology well enough to make the call

**Comment by ValWood** [comment]
I will check what they mean

**Comment by ValWood** [comment]
I think these are the same

A cell phenotype observed in the vegetative growth phase of the life cycle in which the amount of one or more RNAs that are normally expressed during glucose starvation measured in a cell is higher than normal (i.e. higher than observed in wild-type cells during vegetative growth).

A cell phenotype observed in the vegetative growth phase of the life cycle in which the amount of one or more glucose-repressed mRNAs measured in a cell is higher than normal (i.e. higher than observed in wild-type cells). Glucose-repressed mRNAs are transcribed from genes whose transcription is negatively regulated when glucose is present.

1 is saying normally expressed during glucose starvation
2 is saying normally repressed when glucose is present
so its the same thing from the opposite viewpoint

the annotations are all git (glucose insensitive transcription)  which are the same pathway.

I'm confident they can merge.
I think it's better to call the term

 increased level of glucose-repressed gene mRNA during vegetative growth
(at least that one was clearer to me?)

**Comment by mah11** [comment]
merged; also did the "normal" terms

edit file: edc1833f265156f8ac09560413df1d4a56a6a2a8
release: f66d90f3ae622e1b9fa51878bf403d9b115adac1
