### ISSUE TITLE
NTR:increased protein localization to centromere central core

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3681]
increased protein localization to centromere central core

**Comment by ValWood** [comment]
PMID:17677001

**Comment by mah11** [comment]
increased protein localization to centromere central core during vegetative growth FYPO:0007344

edit file: edc1833f265156f8ac09560413df1d4a56a6a2a8
release: f66d90f3ae622e1b9fa51878bf403d9b115adac1
