### ISSUE TITLE
PMID:30793188 spt6/set2 interaction

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3683]
normal histone H3-K36me3 methylation during vegetative growth
abolished histone H3-K36me2 methylation during vegetative growth

**Comment by ValWood** [comment]
and for
https://github.com/pombase/curation/issues/2674
abolished histone H3-K36me3 methylation during vegetative growth

**Comment by ValWood** [comment]
and decreased levels H3K36me3 
for the paper I need to track down pombase/curation#2674

**Comment by mah11** [comment]
two of these already exist:
FYPO:0006403 abolished histone H3-K36 dimethylation at promoter during vegetative growth
FYPO:0006261 abolished histone H3-K36 trimethylation during vegetative growth

**Comment by ValWood** [comment]
Ah OK, I forgot to check them all

**Comment by mah11** [comment]
normal histone H3-K36 trimethylation during vegetative growth FYPO:0007347
  decreased histone H3-K36 trimethylation during vegetative growth FYPO:0007348

edit file: 9ed85f6cef4b306272a5cfd92e86f761e14d3063
release: b4d5fb5497d27d46cdb600d1ed2f9b79399fd932
