### ISSUE TITLE
NTR sensitive/resistant to heavy water

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3686]
PMID:  32142608

see
Request helpdesk  7714 
sensitive/resistant to heavy water

**Comment by mah11** [comment]
sensitive to heavy water FYPO:0007358
  resistance to heavy water FYPO:0007359

edit file: 9ed85f6cef4b306272a5cfd92e86f761e14d3063
release: b4d5fb5497d27d46cdb600d1ed2f9b79399fd932
