### ISSUE TITLE
abolished vs complete

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3691]
did we decide what to do

https://curation.pombase.org/pombe/curs/edfee9c20ff8ca78

uses 

rik1Δ | FYPO:0002827 | decreased chromatin silencing at silent mating-type cassette | Cell growth assay |   | has_penetrancecomplete
-- | -- | -- | -- | -- | --

for "abolished'

logically these are the same?

**Comment by mah11** [comment]
No, these are not the same. For any cellular process phenotype, abolished means the process does not occur to a detectable extent in a given cell. For any organism-level (which = cell-level for a unicellular species) phenotype, penetrance refers to how many organisms (what proportion of the population) has the phenotype. It is entirely possible, therefore to have either complete penetrance of a decreased-but-not-abolished process (it occurs, but not as much as normal, in all cells) or incomplete penetrance of an abolished process (in some cells the process doesn't happen at all but in others with the same genotype it does).

**Comment by ValWood** [comment]
hmm,  I don't think they mean penetrance here.
will check.

**Comment by ValWood** [comment]
no they mean penetrance. I am being dim...
