### ISSUE TITLE
abolished epigenetic inheritance of heterochromatin

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3693]
Where the OFF state of heterochroatinn cannot be maintained over generations.

is this how we have used "maintenance of heterochromatin?" I am not sure??

(this is a characteristic of the varigated expression phenotype, or when the  heterochromatin isnot propagated though meiosis)

**Comment by ValWood** [comment]
The variegated expression pattern of pds5D was charac- teristic of mutants defective in epigenetic inheritance of heterochromatin (Figure 2A) (Taneja et al. 2017). To de- termine if Pds5 affects epigenetic stability, we tested whether the heterochromatic “OFF” state in cells carrying a replacement of cenH with ade6+ (KD::ade6+) (Ayoub et al. 1999) could be maintained in the absence of Pds5. Since the epigenetically maintained OFF state is stably propagated through meiosis (Grewal and Klar 1996; Ayoub et al. 1999), we introduced pds5D by a genetic cross. Tetrad anal- yses of meiotic segregants showed that the KD::ade6+ OFF state was maintained in WT progeny, as expected (Figure 4A). In contrast, maintenance of KD::ade6+ was severely af- fected in pds5D segregants, as indicated by growth on me- dium lacking adenine (Figure 4A). Loss of KD::ade6+ silencing in the pds5D background was confirmed by replica plating onto low-adenine medium plates. All KD::ade6+ pds5D segregants formed white colonies indicating loss of ade6+ silencing (Figure 4A). Defective silencing correlated with a reduction in H3K9me3 levels at the mat region (Fig- ure 4B). A similar loss of silencing occurred in pds5D cells carrying a KD::ura4+ reporter (Figure S2A), which also cor- related with reduced levels of H3K9me3 (Figure S2B). Im- portantly, cells carrying a Kint2::ura4+ reporter, in which the cenH nucleation region is unaltered, did not show de- fects in silencing (Figure S2A). These results indicate that Pds5 is required for the maintenance of heterochromatin at the mat locus.

**Comment by mah11** [comment]
So the observation is that a particular region of the genome stays structured as heterochromatin over successive generation in wild type, but not in a mutant?

If so, I don't think that will fit any logical definition gracefully (because the observation requires looking at cell populations, but heterochromatin organization is under cellular process), so it's kind of tangential to whatever happens with "heterochromatin maintenance" GO terms.

**Comment by ValWood** [comment]
Hmm, yes, I think it is also  analogous to "position variegation effect" .
https://en.wikipedia.org/wiki/Position-effect_variegation. But in multicellular orgs it results in mosaic effect. In fission yeast it results in a variegated population.

Maybe there is another way to model it but I would not worry about logical defs for now...

**Comment by mah11** [comment]
added yesterday (but I didn't get round to closing tickets):

  abolished epigenetic heterochromatin inheritance FYPO:0007376

This has gone in directly under 'abnormal phenotype'. I could add a term for 'abnormal heterochromatin maintenance during vegetative growth', and then have FYPO:0007376 output_of FYPO:new. Would that be any use? Reopen if so ...


edit file: 03fe37fd3c65983cd38ae7fa17a7f2930fabcdb9
release: e1e110f55e2353a6a104997adde5d82959ee8c56
