### ISSUE TITLE
Illegal GO id used in 'abolished double-stranded DNA bridging'

### ISSUE THREAD

**Issue by matentzn** [pombase/fypo#3695]
http://purl.obolibrary.org/obo/GO_0106260

Dont fix it now.. :P give me a day to sort this  ODK stuff out.

**Comment by mah11** [comment]
Harrumph. Sync issue. That is the correct ID, from [this GO ticket](https://github.com/geneontology/go-ontology/issues/19385). That was closed almost a week ago, and the term is visible in [QuickGO](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0106260). How long does it take to reach everything else?

**Comment by matentzn** [comment]
One week after GO release I would say! Thats great then, the issue will sort itself. If you wand you can close it.

**Comment by mah11** [comment]
the term _finally_ made it into a GO release (phew)
