### ISSUE TITLE
NTR protein mislocalized to medial cortex during interphase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3700]
PMID:9679144
child of
protein mislocalized to medial cortex during vegetative growth

**Comment by mah11** [comment]
OK, this has gone in, so now we get to find out whether it reaches Canto ... fingers crossed!

**Comment by mah11** [comment]
Id is FYPO:0007377

**Comment by ValWood** [comment]
If you have already run the reasoner, this isn't currently a child of the vegetative term.

**Comment by mah11** [comment]
note - I might not do a release until tomorrow or Thurs, in case that makes any difference for loading
