### ISSUE TITLE
NTR: normal spindle pole body oscillation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3701]
from Jacky

absence of normal oscillations of duplicated SPB position
During interphase the normal duplicated SPB position oscillations at the cell centre, parallel to the long axis of the cell are absence

PMID:18495844

**Comment by ValWood** [comment]
@JackyVH 
we have this term which I think is the same


FYPO:0007192
--
Ontology | fission_yeast_phenotype
Term name | abolished spindle pole body-led chromosome movement during mitotic interphase
Definition | A cellular process phenotype observed in the vegetative growth phase of the life cycle in which rapid, back-and-forth movement of the mitotic spindle pole body (SPB), and associated chromosome movement, do not occur. Normally, SPB oscillation occurs during mitotic interphase (as well as prophase) but is restricted to a small space.


as  interphase will be the newly duplicated SPB

(add synonyms?)

**Comment by ValWood** [comment]
oscillation is a snonym, this is the actual term


ID | FYPO:0007192
-- | --
Ontology | fission_yeast_phenotype
Term name | abolished spindle pole body-led chromosome movement during mitotic interphase
Definition | A cellular process phenotype observed in the vegetative growth phase of the life cycle in which rapid, back-and-forth movement of the mitotic spindle pole body (SPB), and associated chromosome movement, do not occur. Normally, SPB oscillation occurs during mitotic interphase (as well as prophase) but is restricted to a small space.

**Comment by ValWood** [comment]
@JackyVH  doees that sound OK?

@mah11  should this be related to mitotic SPB localization

**Comment by ValWood** [comment]
Also require a "normal" term for this phenotype

**Comment by mah11** [comment]
> should this be related to mitotic SPB localization

That feels weird; the xref'd GO term connects to chromosome localization because the entire chromosome moves.

**Comment by ValWood** [comment]
Yes I think you are right. I remember doing this in GO. It's odd though, the chromosome moves because the spb moves....

**Comment by mah11** [comment]
Added the new term:
  normal spindle pole body-led chromosome movement during mitotic interphase FYPO:0007378

For ancestry, best to leave it or change it in GO, and have FYPO follow.
