### ISSUE TITLE
Chado load problem: duplicate relation definition for output_of

### ISSUE THREAD

**Issue by kimrutherford** [pombase/fypo#3706]
On Friday 22 May 2020 at 08:30:53, Kim Rutherford wrote:

> On Thursday 21 May 2020 at 15:31:26, Midori Harris wrote:
>
> > Today I remembered to check Canto, and saw that it doesn't have the term
> > I added on Tuesday (FYPO:0007377). So I think you/we will have to switch
> > the loader(s) to use the new "pombase" file for both Canto and Chado.
> >
> > The file now lives at (whatever path to)
> > pombase-git/fypo/fypo-simple-pombase.obo
>
> I've checked in that change for the Chado load and for the Canto
> ontology update.  Previous we were using release/fypo-simple.obo for
> both cases.

The Chado load failed with this error:

```
   can't find relation term RO:0002353 for relation:
      FYPO:0000013 <-RO:0002353-> FYPO:0000026
```

The term that failed to load is:

```
   [Term]
   id: FYPO:0000013
   name: T-shaped vegetative cell
   def: "A cell morphology phenotype observed in the vegetative growth phase of the life cycle in which a new growth zone forms along the lateral portion of the cell (often in the middle) be
fore septation, such that a single cell grows in the form of the letter T. Cell length is normal." [PomBase:mah, PomBase:vw]
   comment: A T-shaped cell may septate perpendicular to the normal septation axis, and divide to form normal-shaped daughter cells. Note that if you have done an experiment that assays the 
viability of a population of cells, such as looking at colony growth or growth in liquid culture, you should also annotate to 'viable cell population' (FYPO:0002058) or one of its descendant
s.
   synonym: "cell morphology, T shaped during vegetative growth" EXACT [PomBase:mah]
   synonym: "T-shaped cell during vegetative growth" EXACT [PomBase:mah]
   synonym: "T-shaped vegetative cell during mitotic cell cycle" RELATED [PomBase:mah]
   is_a: FYPO:0000015 ! branched vegetative cell
   is_a: FYPO:0002197 ! viable vegetative cell with abnormal cell shape
   is_a: FYPO:0005566 ! T-shaped cell
   relationship: output_of FYPO:0000026 ! abnormal vegetative cell polarity
   relationship: RO:0002353 FYPO:0000026 ! abnormal vegetative cell polarity
   created_by: midori
   creation_date: 2011-03-29T05:53:56Z
```

There is an earlier warning that I think explains things: 
```
  two relationship terms with the same name ("RO:0002353" and "output_of") - using: output_of
```

Currently the OBO loader insists that there can't be two relation terms in Chado with the same name, but different IDs.  The solution it uses is to load only one of the terms.

In fypo-simple-pombase.obo we have:

```
   [Typedef]
   id: output_of
   name: output_of
   synonym: "formation results from" EXACT [PomBase:mah]
   property_value: usage "Inverse of has_output. Relation between a structure and a process that forms it, or between one process and a preceding process; A output_of B used where B has_output A isn't always true. Implies that process B is the only way to get output. Used in FYPO where one phenotype (c) always results when another phenotype (p) is present. Phenotype (p) may have other consequences in addition to phenotype (c)." xsd:string
```

And from https://github.com/oborel/obo-relations/blob/master/subsets/ro-chado.obo
we load:

```
   [Typedef]
   id: RO:0002353
   name: output_of
   def: "inverse of has output" []
   is_a: RO:0000056 ! participates in
   is_a: RO:0002328 ! functionally related to
```

One solution to this is to remove the "output_of" `[Typedef]`.  Is that possible?  If so, I think it makes sense to remove the other RO relations too in case they cause problems in future.

If the output_of relation is difficult to remove I'll work on the loading code to try to handle this.

**Comment by mah11** [comment]
ping @matentzn  (also emailed)

**Comment by mah11** [comment]
The fix is working - the test file from yesterday loads, and today's new files don't have the problem lines. Hooray!
