### ISSUE TITLE
questions about imports (1)

### ISSUE THREAD

**Issue by mah11** [pombase/fypo#3710]
There are a bunch of files in src/ontology/imports/, but the contents don't look quite the same as in GO's imports directory files. They (i.e. GO) have a lot more terms in the *_terms.txt files. Does that matter?

On a related note, How far off is FYPO from being able to follow GO's import instructions? http://wiki.geneontology.org/index.php/Adding_Terms_and_Regenerating_the_Import_Files
(it looks convenient)

**Comment by matentzn** [comment]
You cant directly use the GO way, but can you try this:

1. open `src/ontology/imports/go_terms.txt` and add an existing GO id (that does not yet exist in the module).
2. run `sh run.sh make imports/go_import.owl`

Does this refresh the go import module as you expect?

**Comment by mah11** [comment]
yes, thanks! :)
