### ISSUE TITLE
Travis status

### ISSUE THREAD

**Issue by mah11** [pombase/fypo#3712]
What's the status of using Travis builds for FYPO? It doesn't seem to be activated yet, and when I go to https://travis-ci.org/profile/pombase as directed in the README, it says "There was an error, please try again." at the top of the page (in small type).

**Comment by matentzn** [comment]
Can you register at 

https://travis-ci.org/

(click sign-in -> sign-in with Github).

Click on the +:

![image](https://user-images.githubusercontent.com/7070631/83126127-13e3bf80-a0e1-11ea-8ae4-8865e5093112.png)

Can you try to add a Travis job for FYPO? Ask me any problems on the way.

**Comment by mah11** [comment]
OK, I signed in, and changed the little toggle next to fypo in the PomBase organization. Now fypo shows up in the list of repositories on the left - is that correct? Unsurprisingly, it shows no builds yet.

**Comment by matentzn** [comment]
I think that was it!

I edited your [config file](https://github.com/pombase/fypo/blob/master/.travis.yml) to send you emails about the travis status.

You can check your Travis jobs here: https://travis-ci.org/github/pombase/fypo

But I also added a build ribbon to your [fypo frontpage](https://github.com/pombase/fypo):
![image](https://user-images.githubusercontent.com/7070631/83183468-862fc080-a130-11ea-8a43-544587be9d8a.png)

Let's see what errors it coughs up :)

**Comment by matentzn** [comment]
(build is unknown because its still running.)

FYI, whenever you commit something to master, Travis will run!

**Comment by matentzn** [comment]
Seems now to fail for a good reason!

**Comment by matentzn** [comment]
https://travis-ci.org/github/pombase/fypo

**Comment by mah11** [comment]
Yep, I'm getting the emails - thanks :)

**Comment by mah11** [comment]
Well, I don't *understand* the reason for the build failing, but I'm happy that builds are getting triggered as expected. Do I need to do anything to get builds to succeed?

**Comment by mah11** [comment]
Working! I just did the fixes for #3714 and the build passed. Thanks again :)
