### ISSUE TITLE
ntr: normal transcription regulatory region sequence-specific DNA binding

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3715]
normal transcription regulatory region sequence-specific DNA binding

PMID:28652406

....v. good session. but v. lon

**Comment by ValWood** [comment]
normal protein distribution along RNA polymerase II-transcribed genes during oxidative stress response

This session was really really outstanding. Every genotype, every annotation, every extension.
Over 60 annotations.

**Comment by mah11** [comment]
normal transcription regulatory region sequence-specific DNA binding FYPO:0007382

**Comment by ValWood** [comment]
was also
normal protein distribution along RNA polymerase II-transcribed genes during oxidative stress response

**Comment by mah11** [comment]
it's really hard to spot additional terms when they're hidden in follow-up comments. probably more effective to edit the original summary, and add a comment to trigger an email.

**Comment by mah11** [comment]
normal protein distribution along RNA polymerase II-transcribed genes during cellular response to oxidative stress FYPO:0007384
