### ISSUE TITLE
NETO term upgrade

### ISSUE THREAD

**Issue by mah11** [pombase/fypo#3729]
In GO, the NETO synonyms were moved from GO:0051519 'activation of bipolar cell growth' to GO:0051523 'cell growth mode switching, monopolar to bipolar' a while ago (see below; quickgo change log says 2016-09), but the FYPO terms for NETO-related phenotypes date back to before that GO change. So now GO and FYPO aren't quite completely consistent.

@ValWood, @JackyVH - Will it be OK if I change the FYPO NETO terms that have logical definitions to use GO:0051523?

I would also change the term names so they don't follow GO:0051519 any more, but the new term here makes me worry that using "NETO" in the names might not be ideal. Would "normal/abnormal/etc. switch from monopolar to bipolar cell growth" work (with the GO term name in exact synonyms)?

id: GO:0051519
name: activation of bipolar cell growth
namespace: biological_process
def: "Any process that initiates the inactive process of bipolar cell growth, polarized growth from both ends of a cell." [GOC:ai]
is_a: GO:0051518 ! positive regulation of bipolar cell growth

id: GO:0051523
name: cell growth mode switching, monopolar to bipolar
namespace: biological_process
def: "The process in which a cell switches from monopolar cell growth to bipolar cell growth." [GOC:ai]
synonym: "NETO" NARROW [GOC:vw]
synonym: "new end take off" NARROW [GOC:vw]

(transferred from #3699)

**Comment by ValWood** [comment]
I think changing to  GO:0051523 is correct.

I think we should continue to use NETO in the term names if possible.

NETO is  exact  isn't it? 
Maybe these only have narrow as a synonym types hangover from the old term?

**Comment by ValWood** [comment]
Although I can imagine some organisms could activate bipolar growth from the old end maybe...

I guess you could switch the names if you need to....

**Comment by mah11** [comment]
Yeah, in GO NETO is a narrow synonym for GO:0051523 but that's presumably so the BP can be used for species other than fission yeast. It's clear that for the normal process NETO = (GO:0051523 in fission yeast).

For FYPO the reason I'm fretting about using NETO in the term names is because of stuff like FYPO:0007387 ... but if you're willing to say "new end take-off" doesn't happen in a cell that grows only from its new end, I'll run with it.

**Comment by ValWood** [comment]
From what we have seen so far it doesn't so I think you can run.
