### ISSUE TITLE
NTR kinetochore localization

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3739]
normal protein localization to kinetochore during interphase
abolished protein localization to kinetochore during interphase

PMID:19680287

**Comment by mah11** [comment]
protein localization?

**Comment by ValWood** [comment]
oops fixed

**Comment by mah11** [comment]
normal protein localization to kinetochore during mitotic interphase FYPO:0007399
  abolished protein localization to kinetochore during mitotic interphase FYPO:0007400

**Comment by ValWood** [comment]
thanks!

abolished protein localization to kinetochore during interphase
was not under
abolished protein localization to kinetochore during vegetative growth

**Comment by ValWood** [comment]
ditto normal
