### ISSUE TITLE
PMID:32101481 ntr: decreased protein localization to medial cortex during vegetative growth, with protein distributed in cell cortex

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3741]
decreased protein localization to medial cortex during vegetative growth, with protein distributed in cell cortex

PMID:32101481

requested by Rahul ( not clear that it is decreased at the medial cortex, my be compensatory upregulation)

**Comment by mah11** [comment]
That's the name of FYPO:0006638 - what's the task/question here?

**Comment by ValWood** [comment]
Ah sorry  forgot to edit. Need

abnormal  protein localization to medial cortex during vegetative growth, with protein distributed in cell cortex

**Comment by mah11** [comment]
abnormal protein localization to medial cortex during vegetative growth, with protein distributed in cell cortex FYPO:0007405
