### ISSUE TITLE
FYPO:0004672 | inviable elongated vegetative cell with fragmented DNA

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3744]
FYPO:0004672 | inviable elongated vegetative cell with fragmented DNA

Definition
A cell morphology phenotype in which a vegetatively growing cell is inviable, is elongated, and contains DNA broken into small fragments.

Comment | Note that if you have done an experiment that assays the viability of a population of cells, such as looking at colony growth or growth in liquid culture, you should also annotate to 'viable cell population' (FYPO:0002058) or one of its descendants.

can we change this term slightly.

to inviable elongated vegetative cell with disorganised chromatin

A cell morphology phenotype in which a vegetatively growing cell is inviable, is elongated, and contains chromatin is disorganises.

Comment: In this phenotype   DNA may appear to be  fragmented but this cannot be inferred from microscopy

**Comment by ValWood** [comment]
The exisiting comment should say "viable"?

**Comment by mah11** [comment]
as long as you've confirmed that none of the annotations are for experiments that can detect actual DNA fragmentation, should be OK

**Comment by ValWood** [comment]
actually make this 
 inviable elongated vegetative cell with fragmented nucleus

**Comment by ValWood** [comment]
works for existin
