### ISSUE TITLE
 relationship between short telomeres terms and telomere maintenance

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3748]
https://github.com/pombase/fypo/issues/3747

Stephane used 
"FYPO:0000122 abnormal telomere maintenance" and I  was just about to request a descendant when I found

FYPO:0006511 | shortened telomeres during G0
I'm assuming this should be some sort of descendant  of FYPO:0000122
?

**Comment by mah11** [comment]
FYPO:0000122 is defined as vegetative, which means it would be neither a subclass nor a superclass of any G0 phenotype. I'll rename it to make that explicit.

I can also check for places where we could add "output" links.

**Comment by ValWood** [comment]
We probably need a superclass  too though.

Also when people refer to "telomere maintenance" aren't they really only talking about length maintenance ? (I see the def says or structure, but I haven't seen it used in this context. I guess you have annotated more telomere papers than I have, do people use this phrase to describe defects in telomere organization?)

**Comment by mah11** [comment]
> We probably need a superclass too though.

Which new term(s) do you want?

Length is by far the most commonly assayed aspect of telomere structure but the G-quartets and the ssDNA overhang come up occasionally.

**Comment by ValWood** [comment]
my question was, is "telomere maintenance" ever used in the context of structure.

For everything I have ever seen, 
telomere maintenance ==telomere length maintenance

but either way we need a generic "telomere maintenance" as a superclass of  a vegetative and G0 term...

**Comment by mah11** [comment]
> my question was, is "telomere maintenance" ever used in the context of structure

my answer was: yes

**Comment by mah11** [comment]
see #3747 for list of new terms and other changes
