### ISSUE TITLE
synonym for searching "telomeric transcription"

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3749]
Add phrase with this to " blah transcription of telomere"
terms

**Comment by mah11** [comment]
> "blah transcription of telomere" terms

FYPO has no such terms. Do you mean FYPO:0002908 ! increased transcription at telomere (synonyms include "increased transcription from telomere")?

**Comment by ValWood** [comment]
any  transcription at telomere 
to have 
"telomeric transcription" synonyms

**Comment by mah11** [comment]
FYPO:0002908 is the only one.
