### ISSUE TITLE
merge? FYPO:0003567 & FYPO:0006595

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3752]
FYPO:0003567

Ontology | fission_yeast_phenotype
Term name | abnormal establishment of mitotic spindle pole body localization to nuclear envelope
Definition | A cellular process phenotype observed in the vegetative growth phase of the life cycle in which the transport and insertion of a spindle pole body into the nuclear envelope is abnormal.

should merge into 
FYPO:0006595 abnormal mitotic spindle pole body insertion into nuclear envelope

The children:
abnormal establishment of mitotic spindle pole body localization to nuclear envelope, with spindle pole body in cytoplasm
would become

abnormal mitotic spindle pole body insertion into nuclear envelope to nuclear envelope, with spindle pole body in cytoplasm

**Comment by ValWood** [comment]
These terms include a transport step. There is no transport step. The SPB is on the nuclear membrane and it is inserted (unless insertion is transport but either way it's a single term).

**Comment by mah11** [comment]
note to self: also edit synonyms

**Comment by mah11** [comment]
> These terms include a transport step. There is no transport step.

Take that up with GO - I can edit FYPO text defs in any case, but they originally followed what GO had, and the remaining SPB localization terms (GO:0070631 and GO:1990608) still have "a spindle pole body is transported to, or maintained in, a specific location" in their defs.

**Comment by ValWood** [comment]
OK there might be a mix up. The spindle pole body can be transported or move *within* the nuclear envelope.
so there is transport of the SPB.

.But the insertion step itself  (which should be part of a more general  localization term isn't transport.

**Comment by mah11** [comment]
So is insertion part of SPB localization?

At present FYPO has terms based on the GO term for establishment of SPB localization -- the FYPO terms were added before GO merged the establishment and maintenance terms into the localization parent. I can update the existing FYPO terms, but that won't address the question about insertion.

GO has "spindle pole body localization to nuclear envelope" (and a version with 'in nuclear envelope') as a narrow synonym for  GO:1990608 ! mitotic spindle pole body localization. That makes me confused; it might help with the FYPO work to double-check GO first.

**Comment by mah11** [comment]
latest comments on the relevant GO tickets suggest that the FYPO terms in the summary should not merge ... wait & see how GO shakes out, and then do whatever FYPO changes are needed to match.

**Comment by mah11** [comment]
https://github.com/geneontology/go-ontology/issues/14887

**Comment by ValWood** [comment]
I think this is insertion

Term name | abnormal establishment of mitotic spindle pole body localization to nuclear envelope
Definition | A cellular process phenotype observed in the vegetative growth phase of the life cycle in which the transport and insertion of a spindle pole body into the nuclear envelope is abnormal.

and should not merge, because this is the "narrow synonym" GO term.

Or it should broaden to a more general 
abnormal mitotic spindle pole body localization
if we don't have that already

**Comment by ValWood** [comment]
should merge, not should not merge...

**Comment by mah11** [comment]
Based on the recent changes in GO, I have merged FYPO:0006595 into FYPO:0003567, and adjusted names & synonyms for FYPO:0003568 and FYPO:0003569.

If any further changes are warranted, open a new ticket so we don't get (more?) confused.
