### ISSUE TITLE
spindle pole body (SPB) insertion and duplication terms

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3753]
abolished new mitotic spindle pole body insertion into nuclear envelope

abnormal **old** spindle pole body insertion into nuclear envelope with spindle pole body in nucleoplasm

note, this is similar to 
spindle pole body unanchored to nuclear envelope
(would be a descendant of)
( but the definition of this term does not  say in the definition that the SPB is in the nucleoplasm)

The term I need is quite specific. The (old) SPB is inserted into the nuclear membrane from the cytoplasm. The insertion isn't right (this might be for a number of reasons. The process isn't very clear (even now) but some force sticks the SPB in the nuclear membrane, and it is tethered. Some part of this has gone wrong and  the spb drops out into the nucleus.

delayed monopolar mitotic spindle ~nucleated~ nucleation from old spindle pole body
(I can't think of a good way to say this)
would also be descendant of
FYPO:0006593 | decreased mitotic spindle microtubule nucleation from spindle pole body

**Comment by ValWood** [comment]
to clarify

abnormal spindle pole body insertion into nuclear envelope with spindle pole body in nucleoplasm
recommended
spindle pole body unanchored to nuclear envelope
so it is clearly a synonym, but I could not see what type. Maybe it is narrow in which case  the def is OK

abnormal old spindle pole body insertion into nuclear envelope with spindle pole body in nucleoplasm

**Comment by mah11** [comment]
> delayed monopolar mitotic spindle nucleated from old spindle pole body

A structure (the spindle) can't be delayed; only an event can be. What's the process that's delayed?

**Comment by ValWood** [comment]
nucleation, fixed above

**Comment by mah11** [comment]
> to clarify
> 
> abnormal spindle pole body insertion into nuclear envelope with spindle pole body in nucleoplasm
> recommended
> spindle pole body unanchored to nuclear envelope
> so it is clearly a synonym, but I could not see what type. Maybe it is narrow in which case the def is OK

Sorry, this didn't clarify anything for me. Is there a question? The "spindle pole body unanchored to nuclear envelope" is essentially as requested in #3403.

> abnormal old spindle pole body insertion into nuclear envelope with spindle pole body in nucleoplasm

This is the desired new term, right? Which naming scheme do you want to go with (remembering that the name of FYPO:0003568 was changed *to* the "unanchored" version)?

**Comment by mah11** [comment]
also: don't forget about #3670

**Comment by ValWood** [comment]
When I searched on

abnormal spindle pole body insertion into nuclear envelope

the recommended term was

spindle pole body unanchored to nuclear envelope

The synonym will need removing.  I can't see the synonyms so I'm not exactly sure what is matching and what type it is but there is one and it will need to be removed.

I think everything will resolve when the new term is added.

Insertion includes tethering, but that is only part of it. and SPB entering also occurs in other contexts in addition to insertion.

**Comment by ValWood** [comment]
I just looked at the old ticket. I think we should switch the names around to:

"abnormal spindle pole body insertion into nuclear envelope with spindle pole body in nucleoplasm"

is clearer, and SPBs can be unanchored at other time points in addition to this phenotype (I think, not sure about that, but this term is clearer)

**Comment by mah11** [comment]
I think I'll see if GO can sort its terms in a timely fashion for this one too.

**Comment by ValWood** [comment]
this was for 
PMID:19487457

note to self
abolished new mitotic spindle pole body insertion into nuclear envelope
is also required for PMID:22042620

**Comment by mah11** [comment]
I have added these. If any more changes turn out to be needed, best to put them in a new ticket to keep my head from melting.

  abolished new mitotic spindle pole body insertion into nuclear envelope FYPO:0007426
  abnormal old mitotic spindle pole body insertion into nuclear envelope, with spindle pole body in cytoplasm FYPO:0007427
  delayed onset of mitotic spindle microtubule nucleation from old spindle pole body FYPO:0007428
