### ISSUE TITLE
fragmented DNA

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3757]
You changed these to fragmented nucleus, but they still have fragmented DNA parentage

https://www.pombase.org/term/FYPO:0000160

**Comment by mah11** [comment]
Only one term is affected (FYPO:0004672). I can see the offending has_part link in the file Kim uses to load Chado and Canto, but I don't see where it's coming from -- it's not in the edit file or any of the other files generated by the release. I'll remove it manually for now, and ask Nico to investigate if it creeps back in.

**Comment by mah11** [comment]
now also hitting FYPO:0004673 ... I'll ping Nico @matentzn

**Comment by mah11** [comment]
Nico has advised how to fix (will reach next release, whenever that is).
