### ISSUE TITLE
NTR: delayed timing of mitotic entry during nitrogen stress (poor nitrogen source)

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3761]
delayed timing of mitotic entry during nitrogen stress (poor nitrogen source not starved)

I am replacing an annotation to 

FYPO:0005207 | normal mitotic cell cycle regulation upon nitrogen source shift

I think we should get rid of the 'nitrogen shift' terms   (this is captured in the conditions) by nitrogen source shift, glutamate to proline. The point is that  this is a poor nitrogen source = nitrogen stress

**Comment by ValWood** [comment]
PMID:25639242
--

**Comment by ValWood** [comment]
hmm the ticket you pointed me to 

https://github.com/pombase/fypo/issues/2508#issuecomment-172860032

alerted me to the existence of
id: FYPO:0004701
name: abolished cell division timing change upon nitrogen source shift

This term is a bit confusing too.

I think the way I would word the terms is clearer because  there are two separable phenotypes here.

WT cells divide smaller when nitrogen stressed or starved.
1. In some mutants the divide at a larger size
2. Some  of these mutants dividing at a larger size for nitrogen stress   divide with normal timing (for. a nitrogen shift change) compared to WT. Some divide later than normal.

 abolished cell division timing change upon nitrogen source shift
only has a single annotation to an older Peter Fantes paper, so I can go back and look at this one.

**Comment by ValWood** [comment]
I'm going to finish JAnni's paper, and go through some of the old ones about regulation of the nutritional shift, and then see if I can come up with terms that will work for everything.

I will run this by Jackie, then do a proposal.

**Comment by mah11** [comment]
Again, I really don't like the "nitrogen stress" phrase (see details in #3760). "N source shift" describes what happens more precisely, and even though conditions would show the specific compounds used as N sources, the fact that the cell makes metabolic adjustments to switch from eating one substance to another is biologically relevant.

> delayed timing of mitotic entry during nitrogen []

"Delayed timing" also sounds awkward, and FYPO uses "mitotic entry" only in synonyms. If mitotis takes place later in a mutant than in wild type, the name would be "delayed onset of mitosis". But I don't understand why 

> hmm the ticket you pointed me to

The tickets I referred to also contain the reasoning @Antonialock used for including both FYPO:0004701 and the FYPO:0005206/FYPO:0005207 pair. If you(both) are no longer concerned about that observation that only applies to a population, then we could dispose of FYPO:0004701.

**Comment by ValWood** [comment]
It isn't possible to say anything about the timing from these experiments
