### ISSUE TITLE
NTR: decreased change in cell length at division after shift to poor nitrogen source

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3763]
NTR: decreased change in cell length at division after shift to poor nitrogen source

A blah phenotype in which the normal decrease in cell length  observed in WT cells, in response to a shift to a poor nitrogen source (e.g. proline)    is decreased.

It could probably be a descendant 
FYPO:0005664 viable elongated cell during nitrogen starvation
because it is elongated for the conditions

We can argue about the semantics but this is the gist.

Perhaps we should even say shift to proline?

reference 
PMID:25639242
figure 1 for WT
figure 2a and 3a-G for experiments

This would help to differente from other phenotypes, and enable these phenotypes to be separated from other types of elongated.
This phenotype is 'pathway specific' for the nutrient sensing pathway. During growth on rich medium this pathway   (to inhibit TOR) is not active.

**Comment by mah11** [comment]
How is "poor nitrogen source" defined?  (This term can't be created unless the meaning of "poor nitrogen source" can be pinned down. If we get a good def for that part then it'll be worth the time to sort out the rest.)

**Comment by ValWood** [comment]
related

https://github.com/pombase/curation/issues/2787
any term mentioning  "nitrogen source shift" we need to know if it is good->poor or poor->good, even if we end up having to use  "nitrogen starvation" for the shift from good to bad.

If we do need to  use "nitrogen starvation" in the good-> poor case,  what would we use for bad-> good?

**Comment by ValWood** [comment]
I'm going to ask JAcky about this.

But could a poor nitrogen source be defined as "a nitrogen source that does not support maximum growth (i.e. size) at division?

**Comment by mah11** [comment]
> But could a poor nitrogen source be defined as "a nitrogen source that does not support maximum growth (i.e. size) at division?

That feels circular ... I'd be more comfortable with a def for "poor N source" that's independent of the very phenotype we're trying to describe.

**Comment by ValWood** [comment]
just 
""a nitrogen source that does not support   maximum size during vegetative growth"

or would that be missing something?

**Comment by ValWood** [comment]
Speaking with Jacky

poor nitrogen source is different from starvation.
In nitrogen starvation cells can't go do vegetative growth and they divide twice arrest in G1  (and either mate or go into G0)
However a poor nitrogen source such as proline (which is for somehow  less accessible). This is a universal thing (proline is a poor nitrogen source for growth) so I should be able to find a reference.

**Comment by ValWood** [comment]
It seems that  proline is a 'poor nitrogen source' universally. It is somehow less 'available. I am trying to find out why, but even if it takes a few more steps to process  I would not expect a huge affect on size (nitrogen content is the same as glutamate). Maybe it uses a lot of energy, but that seems a stretch. I can find lots of papers referring to 'poor nitrogen source' across species (an most use proline as the example) , but none that actually explain why it is poor.

This sounds like the sort of thing @deustp01  might have some wisdom to impart....

**Comment by mah11** [comment]
After some digging, I've decided to handwave the good/poor N source distinction like this:

Good (or rich) nitrogen sources are distinguished from poor sources based on how readily nitrogen is assimilated into cellular metabolism. In microorganisms, good nitrogen sources generally support higher cell population growth rates than poor sources. In fission yeast, cells divide at a smaller size when grown on a poor nitrogen source than in nitrogen-rich media; proline is commonly used as a poor nitrogen source. (Note to self: include PMID:10640599 as ref for the N source stuff.)

That should do until/unless something better comes to our attention.

For the size at division, I'll use "attenuated change in cell size at division ..." so the name doesn't have a "decreased" in there that could refer to how big the cell is or how much the division size changes.

**Comment by mah11** [comment]
> any term mentioning "nitrogen source shift" we need to know if it is good->poor or poor->good

All of the annotations using "nitrogen source shift" terms have conditions included that indicate which specific N sources were used. Given that, I don't feel a need to alter the existing terms. That won't preclude adding new terms that specify direction. I won't put specific substances in names for anything other than population growth terms, though - for consistency with the rest of the ontology, and for the sake of our all-species phenotype goals (in budding yeast urea is sometimes used as a poor N source, e.g. PMID:27072582).

**Comment by ValWood** [comment]
That sounds great!

**Comment by mah11** [comment]
attenuated change in cell size at division upon shift to poor nitrogen source FYPO:0007434
