### ISSUE TITLE
NTR: inviable elongated mononucleate cell during nitrogen starvation 

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3764]
descendant of
elongated cell during nitrogen starvation (FYPO:0000998)

(should also have some relationship to abnormal arrest at G2/M transition)

refs
PMID:12399381 https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1462273/pdf/12399381.pdf

**Comment by mah11** [comment]
> should also have some relationship to abnormal arrest at G2/M transition

How would this fit together with FYPO:0001001 ! abnormal cell cycle arrest in mitotic G2 phase during nitrogen starvation? That term has "in G2" rather than "at G2/M transition" because that's the way @Antonialock worded the request (5 years ago, in #159). Can the G2/M transition be distinguished from the rest of G2 in some experiments?

(also, this is the same paper as in #2806)

**Comment by ValWood** [comment]
All G2 arrest is at the G2/M transition.

This area  is all a bit complicated and I don' think the biology is fully clear.
I have a feeling that the 'sizer' is set in G1 but the block manifests in G2 but that's another issue. I need to discuss this with @jackyVH  related to  #2806 

But the block is at the G2/M transition becasuse for G2 that is the only arrest point.

**Comment by mah11** [comment]
> All G2 arrest is at the G2/M transition.

Just to be extra sure: is this also true of the abnormal G2 arrest in N starvation that FYPO:0001001 represents (where the main abnormality is that arrest is G2 instead of G1)? Should I rename FYPO:0001001?

**Comment by ValWood** [comment]
G2 arrest in N starvation that FYPO:0001001

is at the G2/M transition

All G2 arrest is at the G2/M transition

Renaming would make this  more consistent.

**Comment by mah11** [comment]
new term
  inviable elongated mononucleate cell during nitrogen starvation FYPO:0007435
renamed G2 arrest terms to use 'G2/M transition'
merged FYPO:0003373 into FYPO:0000400

Note: I rejigged G2 vs. G2/M for a bunch of terms, which might have the odd knock-on effect on term ancestry. If you notice any missing or dodgy links, open a new ticket.
