### ISSUE TITLE
abnormal mitotic spindle pole body insertion into nuclear envelope, with spindle pole body in nucleoplasm

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3765]
abnormal mitotic spindle pole body insertion into nuclear envelope, with spindle pole body in nucleoplasm

has the descendant

abnormal old mitotic spindle pole body insertion into nuclear envelope, with spindle pole body in cytoplasm 

I think thsi should have been nucleoplasm and could just be  edited?
I used it in this way anyway so let me know if not.

**Comment by mah11** [comment]
corrected term name for FYPO:0007427
