### ISSUE TITLE
inviable elongated mononucleate cell during nitrogen starvation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3774]
I did not see
inviable elongated mononucleate cell during nitrogen starvation
under

FYPO:0000998 | elongated cell during nitrogen starvation
-- | --

**Comment by ValWood** [comment]
also
does inviable elongated mononucleate cell during nitrogen starvation
have any relationship to
cell cycle arrest at mitotic G2/M phase transition

**Comment by ValWood** [comment]
more specifically:
FYPO:0001001 | abnormal cell cycle arrest at mitotic G2/M phase transition during nitrogen starvation

is output of?

**Comment by mah11** [comment]
> I did not see inviable elongated mononucleate cell during nitrogen starvation under FYPO:0000998

Drat, it didn't get inferred.

> does inviable elongated mononucleate cell during nitrogen starvation have any relationship to FYPO:0001001

Not at present. If you are absolutely certain that cells never become elongated & die upon/following arrest in *G1* during nitrogen starvation, then I can add an output_of link.

**Comment by ValWood** [comment]
I'm pretty certain this could not happen because  arrest in G1 would be incompatible with elongated.  Arrested cells are only elongated at G2 (unless they are elongated due to cytokinesis defects, but that is n't the case here).

I'm sure this is a safe assumption but checking with @JackyVH

**Comment by mah11** [comment]
OK< adding the link; we can take it out if it causes problems.
