### ISSUE TITLE
conditions ontology/ add synonyms

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3782]
growth <24 hrs ADD EXACT SYNONYM 
growth <24 hours

etc.
growth >24 hours
growth > 48 hours

possibly others

**Comment by ValWood** [comment]
add "G5" and  "5 generations"  as  etc as "related synonyms" for  "growth <24 hrs"

add "G80" and  "80 generations"   to  "growth > 48 hrs"

**Comment by mah11** [comment]
> add "G5" and "5 generations" as etc as "related synonyms" for "growth <24 hrs"
> 
> add "G80" and "80 generations" to "growth > 48 hrs"

Really? Seems risky, even as 'related' scope, given how much generation time can vary with conditions ...

**Comment by ValWood** [comment]
I guess so. I was thinking that  G5 would always be less than 24 hours and  G80 always more than 48 hours. However 
it does set a precedent which would not be possible to maintain so we can leave these out.

**Comment by mah11** [comment]
Now that I've caught up with the email exchange with Henry, I still think it's unwise to stick anything about generations into the conditions ontology. Generations/time will also vary between strains in any given set of conditions, and that's probably an even better reason to steer clear.

In light of what Henry says about their experiments, I suggest

- add "overnight culture" as a related synonym for growth <24 h
- add new terms for "single passage culture" and "multiple passage culture"
- co-annotate to "single" and "<24 h" for the 5-generation samples, and to "multiple" and ">24 h" for the 80-gen samples

Would that work?

**Comment by ValWood** [comment]
Yep.
