### ISSUE TITLE
missing link abnormal nuclear pore distribution

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3787]
I don't see
FYPO:0003783 abnormal nuclear pore distribution during mitosis
as a descendant of
FYPO:0003973 abnormal nuclear pore distribution

**Comment by mah11** [comment]
I just updated the logical defs to take the merge in https://github.com/geneontology/go-ontology/issues/19951 into account. I'll check in a day or two to see if that fixes it, and if not I'll manually assert the link.
