### ISSUE TITLE
new terms for PMID:32848252

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3788]
1. 
abolished nuclear pore localization to mitotic nuclear bridge
descendant of
FYPO:0003783 abnormal nuclear pore distribution during mitosis

mitotic nuclear bridge
https://github.com/geneontology/go-ontology/issues/19946

2.
abnormal nuclear envelope morphology bridge midzone morphology
descendent of
FYPO:0003779 | abnormal nuclear envelope morphology during mitosis

3. permeabilized nucleus during mitosis
Guatem put:
A [permeabilised nucleus during mitosis] is a [fragmented nucleus] that [demonstrates a transient loss of integrity due to the loss of repair and/or sealing mechanisms]

4. abnormal nuclear envelope morphology bridge  morphology

**Comment by mah11** [comment]
Names suggested for 2 and 4 are nonsense in a copy/paste mishap kind of way. Are they meant to be

- abnormal nuclear envelope morphology at mitotic nuclear bridge
- abnormal nuclear envelope morphology at mitotic nuclear bridge midzone

?

**Comment by ValWood** [comment]
Yes that is correct.

While checking existing INM morphology annotations I just spotted "perforated nuclear envelope"
which sounds like
permeabilized nucleus?

**Comment by mah11** [comment]
> While checking existing INM morphology annotations I just spotted "perforated nuclear envelope"
> which sounds like
> permeabilized nucleus?

Yep, I can add a synonym.

**Comment by mah11** [comment]
new terms
  abolished nuclear pore localization to mitotic nuclear bridge FYPO:0007458
  abnormal nuclear envelope morphology at mitotic nuclear bridge FYPO:0007459
  abnormal nuclear envelope morphology at mitotic nuclear bridge midzone FYPO:0007460
synonym FYPO:0000772
