### ISSUE TITLE
NTR: normal transcription termination  during vegetative growth

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3794]
FYPO:0001855 | normal transcription during vegetative growth

+ termination

PMID:31615333

**Comment by mah11** [comment]
normal transcription termination FYPO:0007463

**Comment by ValWood** [comment]
i don't see this under:
normal transcription during vegetative growth

**Comment by mah11** [comment]
That's probably as it should be - for a process to be normal, all of its sub-processes have to be normal. That means that "normal sub-process" isn't a type of "normal whole process" (and if we were to make a link, it would be your old friend has_part). For example, transcription termination could be OK but initiation or elongation might be abnormal.

**Comment by ValWood** [comment]
Of course...so I actually didn't need the term. I was just in  the wrong place because I was copy/pasting and editing. I used the  pol II specific descendant which already existed...
