### ISSUE TITLE
advice not sure which phenotype / condensin shifted

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3797]
for:
Condensin (Cut14) accumulation sites shifted approximately 500 bp downstream in the auxin-degron mutant of the exoribonuclease Dhp1
(this is quite important as in the abstract and  the author put it in the feedback as being unable to curate)

I used

dhp1 | nda3-cs | dhp1(Auxin-inducible degron)[Knockdown] | FYPO:0001679 | abnormal protein localization to chromatin | Transcript expression level evidence | + auxin |   | assayed_using cut14
-- | -- | -- | -- | -- | -- | -- | -- | --

but it seems suboptimal?
any suggestions?

**Comment by mah11** [comment]
I could create a term for "altered spatial extent of protein localization to euchromatin" -- I can define it as localization over a longer, shorter, or shifted length of chromosome, and there are a couple of existing increased/decreased terms that could be housed under it as well.

tangent: the placeholder would be clearer if it showed just the ontology term; it doesn't need the entire annotation line, and the metadata actually distracts a bit

**Comment by ValWood** [comment]
I copy pasted it as a lazy way to show the entire annotation. I wasn't sure if it would be better to have some sort of

"altered spatial extent of condensin"

but your suggestion sounds fine.

**Comment by mah11** [comment]
Just leaving it at "protein localization" will help keep the term explosion contained ;)

**Comment by mah11** [comment]
altered spatial extent of protein localization to chromatin FYPO:0007465

What's the paper? (I can add it as a def dbxref.)

**Comment by ValWood** [comment]
Oh that would be useful! PMID:31615333

**Comment by mah11** [comment]
cheers :)
