### ISSUE TITLE
rename FYPO:0006800

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3806]
FYPO:0006800

Ontology | fission_yeast_phenotype
Term name | decreased centromere clustering at nuclear periphery during mitosis

A cell phenotype observed in the vegetative growth phase of the life cycle in which the localization of centromeres and associated kinetochores into a cluster at the nuclear periphery is decreased. Centromere-kinetochore complexes normally cluster near the old spindle pole body during interphase of the mitotic cell cycle.

to decreased centromere clustering at nuclear periphery during mitotic interphase

**Comment by mah11** [comment]
ooh, that one slipped past! fixed now.
