### ISSUE TITLE
NTR decreased protein binding to Cohesin Associated Regions (CARs)

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3813]
decreased protein binding to Cohesin Associated Regions (CARs)

PMID:31895039

https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/499

**Comment by ValWood** [comment]
and increased

**Comment by mah11** [comment]
I was about to ask whether this is consistent with our decision in #2820 to remove protein feature-specific binding terms, but then I realized from te SO request that the CAR is a chromosome region. If I can make that mistake, users probably will too, so we really shouldn't use "protein binding" in the term name. This request is for chromatin binding phenotype terms.

**Comment by ValWood** [comment]
Agreed. I made the same mistake wehn I read it , but I didn't think to revise the term name as appropriate.

**Comment by mah11** [comment]
decreased chromatin binding at cohesin associated regions FYPO:0007498
  increased chromatin binding at cohesin associated regions FYPO:0007499
