### ISSUE TITLE
bqt1 check

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3816]
In 100% of the bqt1Δ cells that show monopolar spindles (n=11), those spindles are nucleated specifically from the old SPB (Figure S1I). Hence, failed spindle nucleation in the absence of the bouquet is specific to the new SPB.

**Comment by ValWood** [comment]
FYPO:0007485 | abolished meiotic spindle microtubule nucleation from new spindle pole body during meiosis II
-- | --
has penetrance 100%

should this term be  is_a monopolar spindle formation (or some relationship to monopolar spindle)

**Comment by mah11** [comment]
I've added FYPO:0007485 has_output FYPO:0007486.
