### ISSUE TITLE
fate of terms using GO:0099110

### ISSUE THREAD

**Issue by mah11** [pombase/fypo#3824]
These FYPO terms have logical defs using GO:0099110. When the GO term goes obsolete, what should we do with the FYPO terms? We can make them obsolete too, or just remove the LDs and adjust any text bits (names, text defs, etc.) that need work. What's best?

FYPO:0005832 ! abnormal protein transport on microtubule tip to cell tip cortex during vegetative growth
FYPO:0005834 ! decreased protein transport on microtubule tip to cell tip cortex during vegetative growth
FYPO:0005837 ! abolished protein transport on microtubule tip to cell tip cortex during vegetative growth
FYPO:0005829 ! normal protein transport on microtubule tip to cell tip cortex during vegetative growth

https://github.com/geneontology/go-ontology/issues/20318

**Comment by ValWood** [comment]
(they aren't necessarily transported by polymerization, although I think that was originally assumed becasue they look like thery are travelling on the polymerising  tip by polymerization. That could be an artifact of the  fact that the kinesisn reaches the end of the microtubule before the microtubule reaches the end of the cell .

I was never totally happy with it.

I think these  should be something along the lines

 protein transport on microtubule to cell tip cortex during vegetative growth

so we can use this branch:
GO:0010970    
transport along microtubule

which should stay. It is only the  polymerization terms that will go.

I changed te GO term already.

Does that make sense?

**Comment by mah11** [comment]
So should I convert them to match the non-cortex-specific terms that were added at the same time?

e.g. FYPO:0005831 is 'abnormal protein transport along microtubule to cell tip during vegetative growth'
so I would change FYPO:0005832 from 'abnormal protein transport on microtubule tip to cell tip cortex during vegetative growth' to 'abnormal protein transport along microtubule to cell tip cortex during vegetative growth'

OK?

**Comment by ValWood** [comment]
yep!

**Comment by mah11** [comment]
text edits done
and merged the 'normal' terms (FYPO:0005829 into FYPO:0005841) because they ended up identical
