### ISSUE TITLE
'gain of polarization during quiescence'

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3830]
for PMID:27746023
I was going to request

FYPO:0006633 | increased cell length
+ during nitrogen starvation

which is
'gain of polarization during quiescence'

 https://github.com/pombase/curation/issues/2897
Sty1 activity is critical for maintaining a non-polarized Cdc42 module in N-starved quiescent cells. 

@mah11  how would you describe this

**Comment by mah11** [comment]
It looks like you could use FYPO:0000998 'elongated cell during nitrogen starvation' for these -- the cell diameter looks the same as wt, so they meet the "elongated" criterion of increased length:diameter ratio.

We can also add a term for increased protein localization to cell tip during nitrogen starvation, for CRIB (cdc42 PR:000044799) localization, if you think it'd be useful.

I could add 'gain of polarization during quiescence' as a related synonym for FYPO:0000998 too.

**Comment by ValWood** [comment]
All sounds good. I don't know how I missed

FYPO:0000998

**Comment by mah11** [comment]
added
increased protein localization to cell tip during nitrogen starvation FYPO:0007527
