### ISSUE TITLE
PMID:32502403 NPC, nuclear envelope

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3841]
1. increased duration of protein localization to mitotic nuclear bridge (in anaphase B)
Actually 'in anaphaseB is a 'given' but it might not hurt to be  in the definition

2. Abolished nuclear envelope division
two DNA masses remain linked by the internuclear membrane bridge. 
Gloss: This can result in the coalescence of both DNA masses into one nucleus.

3. abnormal distribution  of nuclear pores at nuclear bridge  midzone membrane domain

4. abnormal nuclear bridge  midzone membrane domain organization

5. coalescence of partially separated nuclei
when the  partially separated nuclei  displaying  a distinct nuclear brid fail to separate  fully and merge back into a single nucleus

**Comment by mah11** [comment]
increased duration of protein localization to mitotic nuclear bridge FYPO:0007545
  abolished nuclear envelope division FYPO:0007546
  abnormal nuclear pore localization to mitotic nuclear bridge midzone membrane FYPO:0007547
  abnormal mitotic nuclear bridge midzone membrane domain organization FYPO:0007548
  coalescence of partially separated nuclei FYPO:0007549

synonyms included where the name differs from suggested

**Comment by ValWood** [comment]
hi,

quick one
could you add

abnormal MMD organization
as synonym
to
abnormal mitotic nuclear bridge midzone membrane domain organization

cheers

**Comment by mah11** [comment]
sure, but I'll wait until I have some other additions or edits to do

**Comment by ValWood** [comment]
no hurry.
