### ISSUE TITLE
def premature actomyosin contractile ring disassembly

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3875]
I used

premature actomyosin contractile ring disassembly

def
A cytokinesis phenotype observed in the vegetative growth phase of the life cycle in which the contractile ring collapses or disassembles upon initiation of contraction during anaphase B. Septum formation typically does not occur in cells in which the contractile ring has collapsed.

this was described as before contraction began, so could the def be tweaked?

**Comment by mah11** [comment]
I broadened the definition and moved the "anaphase B" bit to a second "gloss" sentence.
