### ISSUE TITLE
increased transcription factor activation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3888]
I need a term to describe increased transcription factor activation.

We must have described this, but I can't remember how?

**Comment by mah11** [comment]
What does "transcription factor activation" mean in this context? IOW what's going on at the molecular level?

There isn't a GO term for "transcription factor activation", so we'll need some other way of defining what it means if a new term is warranted.

Could the discussion in #1199 be what you're thinking of?

**Comment by ValWood** [comment]
Yes!  #1199  solution works


Given that transcriptional factor Rst2 regulates gene expression via
the STREP motif (Higuchi et al., 2002), we previously constructed
reporter plasmid containing three tandem repeats of STREP fused to
Renilla luciferase (3xSTREP::Renilla), and found that Rst2 transcriptional
activity in deletion cells of trx2+ gene encoding mitochondrial
thioredoxin, was approximately five times higher than that in
wild-type cells under both glucose-rich and glucose-deprived conditions
(Kato et al., 2013)

**Comment by ValWood** [comment]
increased/decresed/ normal STREP motif

**Comment by mah11** [comment]
erm, increased/decreased/normal *what* at STREP motif?

**Comment by ValWood** [comment]
transcription from STREP promoter 
following solution in #1199

**Comment by ValWood** [comment]
+ increased transcription from STREP promoter STREP motif in response to NO

**Comment by mah11** [comment]
increased transcription from STREP promoter FYPO:0007612
  decreased transcription from STREP promoter FYPO:0007613
  normal transcription from STREP promoter FYPO:0007614
  increased transcription from STREP promoter during cellular response to nitric oxide FYPO:0007615
