### ISSUE TITLE
possible synonyms

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3903]
would  it be app ropriate to add  synonyms 
increased proliferation
to terms related to 
FYPO:0000636 increased cell population growth rate (and decreased)

**Comment by mah11** [comment]
Well, I wouldn't add exact synonyms because "proliferation" doesn't seem like it's necessarily restricted to the *rate* of population growth. But we can be pretty free with related synonyms.

**Comment by ValWood** [comment]
Yep, I  was thinking  related. It just struck me from the wording when people are describing various population growth phenotypes, they might be likely to search on it.

**Comment by mah11** [comment]
OK, added a bunch to the various population growth rate terms
