### ISSUE TITLE
NTR:  inviable mononucleate aseptate  cell  arrested in mitotic M phase without nuclear displacement

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3909]
PMID:33506191
Outcome of  discussion with Masashi,

NTR inviable mononucleate aseptate  cell  arrested in mitotic M phase without nuclear displacement

descendant of
inviable aseptate mononucleate vegetative cell, normal cell length (FYPO:0003501)
cycle arrest in mitotic M phase (FYPO:0003128)

**Comment by mah11** [comment]
inviable elongated mononucleate aseptate cell with cell cycle arrest in mitotic M phase and normal nucleus localization FYPO:0007647

(with a bunch of synonyms, including suggested string)
