### ISSUE TITLE
some synonyms for meiotic chromosome segregation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3912]
FYPO:0003182	unequal meiotic sister chromatid segregation
+ non- disjunction at meiosis II flavours

FYPO:0005648 sister kinetochore separation during meiosis I
+ precocious centromeric dissociation  flavours

FYPO:0004159 | abnormal homologous chromosome segregation
+ abnormal chromosome disjunction at meiosis I

**Comment by mah11** [comment]
"flavours"???

**Comment by ValWood** [comment]
so for this term
FYPO:0005648 sister kinetochore separation during meiosis I
precocious centromeric dissociation during meiosis I

but also makes sense to add the appropriate  synonym  to
premature sister kinetochore separation and normal chromosome division in meiosis I, and unequal sister chromatid segregation in meiosis II

So I probably haven't covered the terms that could use the synonyms.

**Comment by mah11** [comment]
Well, that's somewhat more to go on ....

> so for this term
> FYPO:0005648 sister kinetochore separation during meiosis I
> *add synonym*
> precocious centromeric dissociation during meiosis I

Have I correctly inferred the action (added in italics above)?

> but also makes sense to add the appropriate synonym to
> premature sister kinetochore separation and normal chromosome division in meiosis I, and unequal sister chromatid segregation in meiosis II

What is "the appropriate synonym"? Do you mean the same string as the term name, except with "precocious" substituted for "premature"? Or do you want other text variations as well, as in the suggested synonym for FYPO:0005648?

> So I probably haven't covered the terms that could use the synonyms.

Can you describe a pattern (not in the formal-ontology sense) to identify terms that should get a particular sort of synonym? E.g. "add 'precocious' synonyms to all 'premature' terms in the meiosis branch (or chromosome segregation branch, or just everything*)"? Again, if more than one bit of the name should be changed to generate the synonym, please specify all of the parts that should change.

*ugh, that'd be 47 terms

And for this one ...

> FYPO:0003182 unequal meiotic sister chromatid segregation
>     non- disjunction at meiosis II flavours

FYPO:0003182 has no subclasses. It and its sibling and superclass already have synonyms using "nondisjunction". Do you mean you also want the hyphenated form in synonyms?

**Comment by ValWood** [comment]
1.

so for this term
FYPO:0005648 sister kinetochore separation during meiosis I
add synonym
precocious centromeric dissociation during meiosis I

yes for this

2.
premature sister kinetochore separation and normal chromosome division in meiosis I, and unequal sister chromatid segregation in meiosis II

was to add
precocious centromeric dissociation and normal chromosome division in meiosis I, and unequal sister chromatid segregation in meiosis II

but I don't know how many terms there are. It would be sufficient to identify the common parent of the "kinetochore separation" terms and add "precocious centromeric dissociation " to that.

3. 

> FYPO:0003182 has no subclasses. It and its sibling and superclass already have synonyms using "nondisjunction". Do you mean you also want the hyphenated form in synonyms?

I  think because the normal term is
normal chromosome disjunction at meiosis I
I then just edited to
abnormal chromosome disjunction at meiosis I

but that does not find
FYPO:0004159 | abnormal homologous chromosome segregation

**Comment by mah11** [comment]
added synonyms to FYPO:0000925 & subclasses, FYPO:0004159, FYPO:0005648 & subclasses

Reopen this or do a new ticket if there are any more you want.
