### ISSUE TITLE
small term name tweak and new term 'anucleate'

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3913]
septated mononucleate vegetative cell with mislocalized nucleus FYPO:0007646

just to be really explicit, can we label  this term

septated mononucleate vegetative cell with mislocalized nucleus and anucleate compartment  FYPO:0007646

and also
inviable mononucleate vegetative cell with mislocalized septum (FYPO:0001226) 
-> inviable mononucleate vegetative cell with mislocalized septum  and  anucleate compartment 

plus new parent term
mononucleate vegetative cell with mislocalized septum  and  anucleate compartment 
(because the single nucleus can  is only arrested in a ts mutant- and can go on to form diploids if returned to non-restrictive temperature). However, the deletion mutants with this phenotype will be inviable.

I know the anucleate part is a given, but the reason that I often can't locate these terms is that 'anucleate' is the first thing I search on. It's somehow much easier than thinking about the single nucleus and septa together must be anucleate compartment.

**Comment by mah11** [comment]
new term is
mononucleate vegetative cell with mislocalized septum FYPO:0007652
