### ISSUE TITLE
variable size at division

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3922]
FYPO:0007474
variable cell size at division

Defined
A cell population phenotype in which cells in a population do not divide at a uniform size. Cells in one population may be larger or smaller than normal (i.e. compared to wild-type cells under the same conditions).

Jacky suggested
variable cell length at entry into mitosis followed by equal cell division
A cell population phenotype in which cells in a population do not divide at a uniform size. Cells undergo equal cell division but the cell length at which they initiate mitosis within one population may be longer or shorter than normal (i.e. compared to wild-type cells under the same conditions).

 because a mixed population of cells could also  be caused by

abnormal cell division, large and small daughter cells (FYPO:0002029) 

@mah11 I will let you figure the solution because  one is a cell phenotype and one is a population phenotype.  We may want to
be more explicit about FYPO:0007474 rather than creating a descendant term?

**Comment by ValWood** [comment]
@JackyVH  I see you also requested another descendant of FYPO:0007474


reduced cell size homeostasis
Cellular phenotype where cells that divide at a longer or shorter size than wildtype cells fail to correct this in the following generation. Cells born shorter will fail to extend more and longer cells will fail to extend less compared to wildtype cells

maybe
variable cell size at division with reduced cell size homeostasis

(although isn't  "variable size at division
 already indicating a cell size homeostasis" problem?

**Comment by ValWood** [comment]
so
FYPO:0007474
variable cell size at division
is 'less accurate monitoring of cell size"

but
inability to correct cell-size deviations, is  "loss of homeostasis"

**Comment by ValWood** [comment]
@JackyVH  should we have some mutants annotated as "variable cell size at division" from Navarro and Nurse?

**Comment by JackyVH** [comment]
Let me check  for tomorrow

**Comment by mah11** [comment]
Add to FYPO:0007474 text def to specify that all cells in the population divide "equally", i.e. daughter cells are the same size as each other.

**Comment by mah11** [comment]
cell size homeostasis (for pombe) = a cell that has come into existence at a wild-type size itelf divides at wild-type size

**Comment by mah11** [comment]
some mutants that would be annotated to FYPO:0007474 do, and others do not, subsequently divide at normal size

It's a bit of a cheat to represent them as subclasses of FYPO:0007474, because it's a little awkward putting them in as population phenotypes, but we'll bumble along with it.

**Comment by mah11** [comment]
OK, I futzed with the FYPO:0007474 definition, and added these:

variable cell size at division with subsequent division at normal size FYPO:0007659
variable cell size at division with subsequent division at abnormal size FYPO:0007660

Let me know if I've got anything wrong in the definitions, or if the names, defs, synonyms, etc. can be improved at all. (My brain is melting ...)

**Comment by ValWood** [comment]
PMID:33419777
