### ISSUE TITLE
NTR: protein localization to kinetochore during meiosis PMID:11331883

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3925]
normal protein localization to kinetochore during meiosis I metaphase
abolished protein localization to kinetochore during meiosis I anaphase

abolished protein localization to kinetochore during meiosis II

PMID:11331883

**Comment by mah11** [comment]
Is the third item complete and typo-free? I'm not sure how to interpret the "|".

**Comment by ValWood** [comment]
Fixed, I copy pasted then read as a II

**Comment by mah11** [comment]
normal protein localization to kinetochore during meiotic metaphase I FYPO:0007661
  abolished protein localization to kinetochore during meiotic anaphase I FYPO:0007662
  abolished protein localization to kinetochore during meiosis II FYPO:0007663

**Comment by ValWood** [comment]
FYPO:0007661 | normal protein localization to kinetochore during meiotic metaphase I

didn't infer meiosis I parent
