### ISSUE TITLE
should  increased mating efficiency/mating without nitrogen starvation be related?

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3926]
increased mating efficiency (FYPO:0001043)
A biological process phenotype in which the observed mating efficiency is higher than normal.

mating without nitrogen starvation (FYPO:0003031) 
A cellular process phenotype in which conjugation takes place in cells that are not subject to nitrogen starvation.

"increased mating efficiency" is  sometimes used to curate 
mating without nitrogen starvation (FYPO:0003031) 
since  obviously the mating efficiency is improved. 

I don't  really know if this was the intended use  of "increased mating efficiency" though. It seems quite different from over expressing a gene and seeing  increased mating.

**Comment by mah11** [comment]
duplicates #3920
