### ISSUE TITLE
small change to label FYPO:0002303

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3927]
could this term:
inviable mononucleate monoseptate vegetative cell (FYPO:0002303)
be
inviable mononucleate monoseptate vegetative cell and anucleate compartment 
(like the child)?

inviable mononucleate vegetative cell with mislocalized septum and anucleate compartment (FYPO:0001226)

**Comment by ValWood** [comment]
could we also remove inviable from this term:
FYPO:0002303 ~inviable~ mononucleate monoseptate vegetative cell (FYPO:0002303)

I assumed these were inviable (they are  *almost*, but there are diploid survivors)

So it would be
FYPO:0002303 ~inviable~ mononucleate monoseptate vegetative cell with anucleate compartment

**Comment by mah11** [comment]
> could we also remove inviable from this term:
> FYPO:0002303 inviable mononucleate monoseptate vegetative cell (FYPO:0002303)

Ugh, I don't like this idea at all. This is effectively asking to change the logical as well as text definition of a term that has been in use for over 7 years. That's not an optimal ontology-maintenance practice, especially considering the inferred descendant terms.

It would be fine to add a viability-neutral term with a new ID (and see below).

> I assumed these were inviable (they are almost, but there are diploid survivors)

It would certainly be more ontologically robust, and might also do a more thorough job of conveying what's going on biologically, to add a 'viable' equivalent term, and annotate genotypes to FYPO:0002303 with high penetrance + FYPO:new with low penetrance as appropriate.

**Comment by ValWood** [comment]
OK makes sense.

**Comment by mah11** [comment]
renamed FYPO:0002303 

added
  mononucleate monoseptate vegetative cell with anucleate compartment FYPO:0007664
  viable mononucleate monoseptate vegetative cell with anucleate compartment FYPO:0007665
