### ISSUE TITLE
 inviable mononucleate monoseptate vegetative cell with normal cell length

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3931]
A version of this, with normal length
FYPO:0002303 | inviable mononucleate monoseptate vegetative cell

most of the children are elongated.
Normal size indicates an absence of G2 checkpoint (G2 checkpoint would cause elongation in the same situation).

We would need this term to distinguish mutants that have aberrant DNA synthesis but for some reason cannot  activate the G2 checkpoint.

rfc2-delta is an example of this
PMID:9862966

**Comment by mah11** [comment]
inviable mononucleate monoseptate vegetative cell with anucleate compartment and normal cell length FYPO:0007670
