### ISSUE TITLE
excess nuclear envelope present

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3933]
for PMID:33419777, I forgot this one.

**Comment by mah11** [comment]
different from FYPO:0001556? if so, how?

**Comment by ValWood** [comment]
Doh, I had noted that term in the term suggestion box, so yes that is the right term. I  now think I had noted it to enquire why it wasn't a descendant of abnormal nuclear envelope morphology?

**Comment by mah11** [comment]
I think it's because morphology doesn't encompass amount or number of parts in PATO.

**Comment by ValWood** [comment]
Ah right.  When excess nuclear envelope is present the shape changes (the nucleus doesn't just expand, although that would be size,  I'd expect that to be morphology too??)

So what is its parent, abnormal nuclear organization?

**Comment by mah11** [comment]
> When excess nuclear envelope is present the shape changes 

If there are never any exceptions, then we could manually assert that excess NE is_a abnormal NE morphology, but that would be specific to FYPO (maybe it would generalize to other nuclear envelopes but we have no grounds to request a change in PATO).

> So what is its parent, abnormal nuclear organization?

is_a: FYPO:0001322 ! abnormal subcellular component during vegetative growth
is_a: FYPO:0002403 ! abnormal nucleus

(abnormal nuclear organization is in the process phenotype branch)

**Comment by ValWood** [comment]
Hi @deygautam a question for you. If excess nuclear envelope is present, would nuclear envelope morphology always be abnormal?

Thanks,
val

**Comment by mah11** [comment]
I've added the link; it'll be easy enough to take it back out if @deygautam says it'd be a problem.

**Comment by deygautam** [comment]
Sorry, was giving this some thought and then forgot to reply. Yes I do believe that would be the case based on the evidence we have so far.

Cheers,
Gautam

———
Gautam Dey
Group Leader, EMBL
Sent on the move

On 9 Mar 2021, at 16:01, Midori Harris ***@***.***> wrote:

﻿

I've added the link; it'll be easy enough to take it back out if @deygautam<https://github.com/deygautam> says it'd be a problem.

**Comment by mah11** [comment]
Great, thanks!
