### ISSUE TITLE
types of cells present

### ISSUE THREAD

**Issue by mah11** [pombase/fypo#3943]
shoehorn these into PECO, even though it's a bit of a stretch ...

- wild type cells present [in culture]
- isogenic cells present

include related synonyms using "mating with ..."

rationale (from Sophie, via helpdesk):

"... mating phenotypes can be assessed by starvation + addition of synthetic P-factor, which is easy to express as experimental conditions, but they can also be assessed by adding cells of the opposite mating type as source of pheromone, which does not always have the same outcome. The phenotypes assessed can be variable, not just mating in general. In this specific case, I wanted to annotate that the rga3delta mutant exhibit increased shmoo formation when mixed with WT cells in a mating reaction."

**Comment by ValWood** [comment]
This is reminiscent of some of the horrid conditions we have for PHI-base.

I wonder here if it would be clearer to the users the purpose of the presence  WT cells (and  _slightly_  more in line with conditions) if the condition. was "P-factor provided by WT cells"

**Comment by ValWood** [comment]
Ah I just saw Sophie's message...

**Comment by mah11** [comment]
Yeah, I'm having trouble coming up with something that is neither too easily misinterpreted nor too obviously out of place in the conditions ontology. If I understand the experiments correctly, the most strictly correct way to represent them would be some description of the protocol ... but that would be in scope for OBI, which is a very scary thing and we do not want to go there. I'll keep trying but do feel free to horn in on the helpdesk exchange if you think of something clever.

**Comment by mah11** [comment]
Update: after some back & forth by email we've converged on these names:

wild type cells of opposite mating type added to culture
isogenic cells of opposite mating type added to culture

phew!

**Comment by mah11** [comment]
wild type cells of opposite mating type added to culture PECO:0000383
isogenic cells of opposite mating type added to culture PECO:0000384
