### ISSUE TITLE
cut descendants

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3948]
Since cut is
An inviable phenotype observed in the vegetative growth phase of the life cycle in which a cell undergoes septation despite abnormal mitotic nuclear division, such that the septum physically divides the nucleus into two parts, giving rise to inviable daughter cells.

So cut can't be 'mononucleate' since these are cells in which the nucleus has not divided, or been bisected by the septum (although this phenotype often co-occurs with 'cut').

1. inviable elongated mononucleate monoseptate vegetative cell
2. inviable elongated septated mononucleate vegetative cell
3. inviable mononucleate monoseptate vegetative cell with anucleate compartment
4. inviable mononucleate vegetative cell with mislocalized septum and anucleate compartment
 5. inviable swollen elongated mononucleate vegetative cell with mislocalized septum near new end
 6. inviable swollen elongated mononucleate vegetative cell with normally localized septum

Also, 1&2 sound  the same?

**Comment by mah11** [comment]
2 allows for monoseptate or multiseptate cells; 1 is monoseptate only.

Note to self: to fix, change output_of links for FYPO:0002303 and FYPO:0005023.

For future reference, it is vastly easier to find terms if you can include the IDs as well as the names.
