### ISSUE TITLE
not a catastrophe/  inviable small vegetative cell with premature G2/M transition

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3954]
NTR  inviable small vegetative cell with premature G2/M transition
A cell morphology in which a vegetative cell enters mitosis with inviably small size

is_a
FYPO:0000951
FYPO:0002516

broad synonym mitotic catastrophe ( we need to also add 'mitotic catastrophe' as a synonym to the other terms which mention mitotic catastrophe in the definition, namely the cuts)

definition source PMID:1706223 Lundgren et al. 1991
 
and PMID:33683349

**Comment by mah11** [comment]
> inviable small vegetative cell with premature G2/M transition

To clarify: is this a request for a new term?

> broad synonym mitotic catastrophe

No other "mitotic catastrophe" synonyms are broad; they're related. I think that's correct.

> we need to also add 'mitotic catastrophe' as a synonym to the other terms which mention mitotic catastrophe in the definition

FYPO:0003165 is the only non-obsolete term with "mitotic catastrophe" in the definition, and I think that's just an oversight; I'll edit the text.

Which terms should have "mitotic catastrophe" synonyms that don't already?

**Comment by ValWood** [comment]
>To clarify: is this a request for a new term?
yes

> No other "mitotic catastrophe" synonyms are broad; they're related. I think that's correct.
ok

> Which terms should have "mitotic catastrophe" synonyms that don't already?
I'm not sure but when I search on "mitotic catastrophe" I don't get any of the old terms that used to be "cut with mitotic catastrophe"  etc.

On the plus side, I now know more precisely what a mitotic catastrophe is, and it wasn't what we were calling it before.

**Comment by mah11** [comment]
>  when I search on "mitotic catastrophe" I don't get any of the old terms that used to be "cut with mitotic catastrophe" etc.

In Canto or on PomBase website? They show up for me in Canto.

**Comment by ValWood** [comment]
Website....

**Comment by mah11** [comment]
inviable small vegetative cell with premature mitotic G2/M phase transition FYPO:0007700

The search issue is website tracker fodder, and the new term is in, so I'll close this.
