### ISSUE TITLE
PMID:33683349 ntr

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3955]
NTR: inviable mononucleate  elongated cell with cell cycle arrest at mitotic G2/M phase transition

descendant of
FYPO:0005367 | inviable mononucleate aseptate cell with cell cycle arrest at mitotic G2/M phase transition

NTR: inviable  elongated cell with cell cycle arrest at mitotic G2/M phase transition
(this is classical cdc so we should have this? maybe I am looking in the wrong place)

**Comment by mah11** [comment]
for FYPO:0005367 to be a correct parent, the first new term would be:

inviable elongated mononucleate **aseptate** cell with cell cycle arrest at mitotic G2/M phase transition

> NTR: inviable elongated cell with cell cycle arrest at mitotic G2/M phase transition
> (this is classical cdc so we should have this? maybe I am looking in the wrong place)

There are a few terms that are more specific (e.g. including mono- or binucleate, or aseptate, or elongated ...), but none with exactly that combination of specified and unspecified features. The reason will be that no one has requested a term with this exact set of specifications before now.

**Comment by mah11** [comment]
forgot to ask: do you want new-term-1 to be a descendant of FYPO:0005367, or do you want it not to specify "aseptate"?

**Comment by ValWood** [comment]
Sorry  that wasn't clear based on suggested parent. Neither if the new terms should specify aseptate.

**Comment by mah11** [comment]
inviable elongated mononucleate cell with cell cycle arrest at mitotic G2/M phase transition FYPO:0007701
  inviable elongated cell with cell cycle arrest at mitotic G2/M phase transition FYPO:0007702
