### ISSUE TITLE
question about loss of viability phenotype

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3956]
In the session I'm approving  
  | PMID:33683349

Nick used 

loss of viability at high temperature,
A cell population phenotype in which a smaller than normal proportion of cells in the population remains viable when cells are grown at a temperature higher than standard.

 which is true but I used

FYPO:0001355 | decreased vegetative cell population growth
A cell population phenotype in which the growth of a population of cells is decreased relative to normal in the vegetative growth phase of the life cycle.
 with a 'high temperature condition' 

I have only used "loss of viability" when the population size is shown to decline over successive generations. I'm not even sure if   "loss of viability" is equivalent to " decreased vegetative cell population growth"

now I think maybe I should change it back to "loss of viability"

How can this call be made? Do you need to establish that some cells are dead to use loss of viability???

@JackyVH 
@mah11 

(@JackyVH  I'd like you to check this one for me next week, it was one of the most difficult papers I have curated done but I think you would find it really interesting)

**Comment by mah11** [comment]
The comments for the "loss of viability" terms all have comments that say they should be used when

 - a culture is grown under one condition, usually something tough (e.g. at high temperature), and then the number of cells viable enough to form a colony upon return to nicer conditions (e.g. standard or low temperature) is measured and compared to wild type."

1. Is that sufficient to explain when to use "loss of viability"?
2. If not, what else does it need?
3. If yes (or with edits), would it help to move that info from comments to definitions?

**Comment by ValWood** [comment]
It seems that Nick was probably combining 2 things here.
He suggested" A G2 arrest at high temperature is a loss of viability at high temperature that occurs due to a G2 arrest."

But we have 
I) the phenotype observed during the temperature block (G2 arrest)

and
II
 the  "loss of viability" after the return to normal temperature (I think I have used "temperature block and release" in these situations but maybe a general "return to permissive conditions " would be more useful.

**Comment by ValWood** [comment]
edited above. Maybe what we have is OK.
Just need to check in this session that we have BOTH the population AND the "cell level" phenotype

**Comment by ValWood** [comment]
Other questions for thursday:
1. Does the same apply to all "loss of viability" phenotypes  (i.e after nutrient starvation?)
2. If not  should we distinguish between "loss of viability" where the resulting population is inviable , or viable 
 because I think this might be quite important in the different situations.

I.e I have a feeling that sometimes we mean "in these conditions cells lose viability until they are all dead" and sometimes we mean "some cells lose viability during these conditions" and we can observe this when we return to normal conditions.

I know this is waffly, but I wanted to try to pinpoint what my confusion is.

**Comment by mah11** [comment]
decision: yes, do move info from comments to defs

**Comment by ValWood** [comment]
Sorry I was thinking about this more. It wouldn't be correct to include in the definition would it? 
This is really only how the loss of viability is assessed. The phenotype could also be assessed by counting dead cells as @juanmatacambridge  mention.

I guess the "loss of viability" should always also be annotated  with the viable/inviable population  term.

Anyway I don't think we need any action here- I was confused.
