### ISSUE TITLE
abnormal centromere localization parentage

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3964]
abnormal centromere localization

is_a 
abnormal protein localization (FYPO:0001370)

looks a bit odd (I would say 'abnormal cellular component localization' maybe?)

**Comment by mah11** [comment]
This is inferred from GO -- GO:0072765 'centromere localization' is_a GO:0034629 'cellular protein-containing complex localization' (and is_a GO:0051640 'organelle localization'), so it can only be avoided by changing the links in GO.

**Comment by mah11** [comment]
p.s. FYPO has asserted FYPO:0001440 abnormal protein complex localization is_a FYPO:0001370 ! abnormal protein localization, but that's consistent with GO's GO:0034629 ! cellular protein-containing complex localization is_a GO:0034613 ! cellular protein localization

**Comment by ValWood** [comment]
hmm, lets quietly ignore  and hope the logical defs fix some day...
