### ISSUE TITLE
ntr: decreased protein localization to mitotic spindle during anaphase

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3977]
PMID:16920624
 decreased protein localization to mitotic spindle during anaphase

**Comment by mah11** [comment]
decreased protein localization to mitotic spindle during anaphase FYPO:0007729

**Comment by ValWood** [comment]
just so you know, this wasn't a child of
decreased protein localization to mitotic spindle

also we could add a synonym to 

FYPO:0007729
decreased protein localization to elongating mitotic spindle

**Comment by mah11** [comment]
moved it (one of these days I'll figure out what does and doesn't get inferred ...)

synonym will be `related` because spindle elongation isn't restricted to anaphase
