### ISSUE TITLE
meiotic spindle related terms PMID:32723864

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3985]
/ spindle collapse during  meiotic prophase I
/ abnormal meiosis I spindle formation
/ (abnormal) spindle elongation during meiotic metaphase I (this is spindle phase II, usually paused)
/normal meiotic spindle length during prophase I
prolonged duration of  meiotic spindle formation (spindle phase I & II, the formation part)
/ decreased protein localization to meiotic spindle during meiosis I
/ normal protein localization to meiotic spindle during meiosis I
/ meiosis I spindle collapse during pro-metaphase I
/ meiosis I spindle regression (meiotic spindle shrinkage)
/ multiple meiotic spindles meiosis I
abnormal mitotic spindle formation, (no spindle phase II). https://github.com/geneontology/go-ontology/issues/21349 for GO term
short meiotic spindle during metaphase
/abnormal homologous chromosome segregation with collapsed spindle

**Comment by ValWood** [comment]
Any chance you could add these in advance of the GO?

**Comment by ValWood** [comment]
>Whew, what a slog.

I know!   Hopefully this will cover a lot of future experiments for meiotic spindle.

note:
spindle elongation during meiotic metaphase I FYPO:0007746 -> abnormal

**Comment by mah11** [comment]
doh! fixed.
