### ISSUE TITLE
septum assembly primary name

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3988]
In GO we call septation "septum assembly" but for  FYPO purposes can we use 
"septation" in the term labels as that is the common usage?

**Comment by mah11** [comment]
Well, OK, although it will diverge from GO  ("septation" is a BROAD synonym for GO:0000917), which risks making the FYPO names a little less suited to the species-neutral cell-level phenotype ontology vision. And it's a PITA to do text edits in Protege. But yeah, I can do it.

**Comment by ValWood** [comment]
No worries, maybe it is better as it is. People say "septation" but  thinking about it now this probably  usually  means "ring contraction+ septum formation" which occur at the same time. We tend to equate the use of in text  'septation' with 'septum assembly' but really it's the whole caboodle.

in 'cut' for example:


An inviable phenotype observed in the vegetative growth phase of the life cycle in which a cell undergoes septation despite abnormal mitotic nuclear division, such that the septum physically divides the nucleus into two parts, giving rise to inviable daughter cells.

But it's really ring constriction+septum assembly here.

I have no idea how to resolve this, so maybe we can quietly ignore until some logical issues arise...
