### ISSUE TITLE
PMID:32723864 follow up

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#3998]
https://github.com/pombase/fypo/issues/3985

follow on.

abolished mitotic spindle formation phase II 
is a descendant of
abnormal spindle assembly during meiosis I

Annoyingly this isn't even the terms I was waiting on as it wasn't fully curated- I got mixed up. It was   https://github.com/pombase/fypo/issues/3992! that I was eager to do.

**Comment by mah11** [comment]
doh. (/me mutters darkly about the Protege interface)

**Comment by ValWood** [comment]
analogous to
FYPO:0007748

 | increased duration of mitotic spindle assembly

Note that  both the meiotic and the mitotic terms are the  spindle phase 1&2 
- phase 3, which is also part of spindle assembly/elongation is not affected.
