### ISSUE TITLE
synonym

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4001]
add
abolished monopolar attachment 

exact for
FYPO:0005634 | equational sister chromatid separation during meiosis I

**Comment by ValWood** [comment]
Hmm,OK but it is the centromeric cohesion   (protection) which   enables the monopolar attachment.

If you  have problems with  the cohesion protection, the attachment is bipolar rather than monopolar 
and that causes equational segregation at meiosis I.

So if it can't be exact, definitely narrow.

**Comment by mah11** [comment]
Actually, I think a downstream effect is `RELATED` territory. `NARROW` is for parts or subtypes that don't warrant their "own" terms.

**Comment by ValWood** [comment]
OK

**Comment by mah11** [comment]
synonym added
