### ISSUE TITLE
missing parent increased RNA level

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4010]
increased gene expression

**Comment by mah11** [comment]
I think these existing connections cover it as well as possible:

- increased transcription is_a increased gene expression
- increased transcription has_output increased RNA level

(and similar for decreased yada).

It feels redundant to add increased gene expression has_output increased RNA level; `is_a` isn't the correct relation to connect a level of stuff with a process phenotype.

Improving "findability" would probably need some thought about how Canto and the website searches handle the has_output links (or whatever they morph into with further uPheno reconciliation work).

I'm inclined to say the ontology "works as is" for these terms.
