### ISSUE TITLE
two cell divisions prior to cell cycle arrest in mitotic G1 phase without nutrient starvation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4014]
abnormal cell cycle arrest in mitotic G1 phase

child

two cell divisions prior to cell cycle arrest in mitotic G1 phase without nutrient starvation

(some existing annotations to the parent will move down to this)

 Inhibition or inactivation of Tor2 in mitotically dividing cells induces a phenotype reminiscent of nitrogen starvation, where cells divide without growth, and arrest in G1 (Uritani et al., 2006),

**Comment by mah11** [comment]
which paper(s)?

**Comment by ValWood** [comment]
PMID:28476936

**Comment by mah11** [comment]
thanks
two cell divisions prior to cell cycle arrest in mitotic G1 phase without nutrient starvation FYPO:0007795
