### ISSUE TITLE
a new FYPO term - quorum sensing

### ISSUE THREAD

**Issue by snezhkaoliferenko** [pombase/fypo#4037]
Could we please get a term 'deficient in quorum sensing'?
Thank you!

**Comment by mah11** [comment]
Added these:
  abnormal quorum sensing FYPO:0007823
  decreased quorum sensing response FYPO:0007824

I think Elisa will want to use FYPO:0007824. I included FYPO:0007823 in case something turns up that doesn't make QSMs as normal.
