### ISSUE TITLE
PMID:33534698 diffentiating nitrogen starvation from amino acid starvation

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4038]
decreased protein level during cellular response to amino acid  starvation
-- decreased protein level during cellular response to leucine starvation

Note that these are a separate thing from:
FYPO:0001283 | decreased protein level during cellular response to nitrogen starvation

and
abolished protein phosphorylation during cellular response to leucine starvation

see PMID:33534698

**Comment by mah11** [comment]
> abolished protein phosphorylation during cellular response to leucine starvation

is FYPO:0006398

**Comment by mah11** [comment]
decreased protein level during cellular response to amino acid starvation FYPO:0007825
  decreased protein level during cellular response to leucine starvation FYPO:0007826
