### ISSUE TITLE
normal contractile ring maturation PMID:34133210

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4039]
NTR normal contractile ring maturation 

(this is the phase between assembly and constriction referred to in GO as 'maintenance but seems to be called more commonly 'maturation' in publications.

**Comment by ValWood** [comment]
Also
'premature protein localization to cell division site'

**Comment by mah11** [comment]
> normal contractile ring maturation
> 
> (this is the phase between assembly and constriction referred to in GO as 'maintenance

Does this mean that GO:1902406 is the GO term to use in a logical def?

**Comment by ValWood** [comment]
Yes,  To be sure I'm going to double check this with Kathy  and MAriaSanta so you might want to hold on...

**Comment by mah11** [comment]
new terms
  normal actomyosin contractile ring organization FYPO:0007827
  normal actomyosin contractile ring maturation FYPO:0007828
  premature protein localization to cell division site FYPO:0007829

renamed FYPO:0007127 to use "maturation"
