### ISSUE TITLE
Decreased protein density in medial cortical node during mitotic interphase PMID:33496728

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4042]
Community suggestion was:

Variable Myo2p motor head organization in cytokinesis nodes.

Yet 
"the spreading of the Myo2p
heads is progressively tighter in P-nodes of wild-type bands,
Δmid1 nascent strands, and Δmid1 enduring strands"

but although variable it is always 'tighter' in the mutant so I think the verb can be 'decreased'

The term should  maybe something like 
"Decreased protein density in medial cortical node during mitotic interphase"
Also we could be more specific because this is in the precursor  nodes which precede the existence of the ring, so  we can say 'during mitotic interphase'

**Comment by ValWood** [comment]
"Decreased protein density in medial cortical node during mitotic anaphase B"
( ring nodes observed in constricting cells)

**Comment by ValWood** [comment]
+ delayed protein localization to medial cortical node

**Comment by mah11** [comment]
I looked at the paper because I couldn't see how "tighter spreading" equates to "decreased density" ... and I don't think it is decreased protein density. It's narrower radial density *distribution* (the "RDD" in the figures) of a protein in the nodes in the mutant.

**Comment by ValWood** [comment]
Right, of course.  How would you call that? 

Decreased radial density distribution ?

**Comment by mah11** [comment]
I've gone with "narrow protein radial density distribution in medial cortical node", plus "decreased" in synonyms. I'll happily add more synonyms if that would help.

  narrow protein radial density distribution in medial cortical node during mitotic interphase FYPO:0007830
  narrow protein radial density distribution in medial cortical node during mitotic anaphase B FYPO:0007831
  delayed onset of protein localization to medial cortical node FYPO:0007832
