### ISSUE TITLE
abnormal cell cycle phase transition annotation drop

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4050]
around 2May
abnormal cell cycle phase transition dropped from 146 to 116

I suspect it was dues to the removal of some relations between cell cycle checkpoints and the regulation of phases. I need to look what is missing.

**Comment by mah11** [comment]
This looks like yet another knock-on effect of GO deciding that [regulates is no longer transitive over part_of](https://github.com/geneontology/go-ontology/issues/21557#issuecomment-854485669). I can manually assert links if you're sure that "abnormal regulation of X phase transition" is always a type of "abnormal X phase transition".

**Comment by ValWood** [comment]
Yes it is. I suspect some of these non regulatory parents should not really exist in GO. This area still needs a clean-up.
