### ISSUE TITLE
meiosis I spindle new phenotypes for abolished localization to meiosis I spindle PMID:34346498

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4053]
- short meiotic spindle during anaphase I

- long meiosis I spindle

- meiotic SPB-independent spindle (a meiotic spindle that forms independently of the spindle pole being correctly localized  at the spindle pole)
(this should possibly  have some relation to 
"meiotic spindle pole body detached from nucleus" (FYPO:0006365) 
but it does not appear to occur  for every single instance of this phenotype, sometimes no spindle forms.
(and also  a meiosis I and Meiosis II specific term for this phenotype)

-  abolished protein localization to meiosis I spindle

- abolished  meiosis I spindle assembly

- normal meiotic spindle polarity 
(i.e normal -/+ orientation of microtubules within the spindle)

**Comment by mah11** [comment]
> meiotic SPB-independent spindle (a meiotic spindle that forms independently of the spindle pole being correctly localized at the spindle pole)

This sounds like a process phenotype.

> abolished localization to meiosis I spindle

Protein localization?

> normal meiotic spindle polarity

Just the generic term, or do you also want terms for meiosis I and/or II?

**Comment by mah11** [comment]
oh, and which paper?

**Comment by ValWood** [comment]
> Just the generic term, or do you also want terms for meiosis I and/or II?

I think just the generic term is OK. They do track through meiosis I and II but  I doubt it will ever be different at one phase than the other...

**Comment by ValWood** [comment]
>>meiotic SPB-independent spindle (a meiotic spindle that forms independently of the spindle pole being correctly localized at the spindle pole)

> This sounds like a process phenotype.

A comment would be useful that this phenotype usually  co-occurs with "meiotic spindle pole body detached from nucleus" (FYPO:0006365)

Other Q's answered/edited

**Comment by mah11** [comment]
new terms
  short meiotic spindle during anaphase I FYPO:0007846
  long meiosis I spindle FYPO:0007847
  meiotic spindle self-assembly FYPO:0007848
  spindle self-assembly during meiosis I FYPO:0007849
  spindle self-assembly during meiosis II FYPO:0007850
  abolished spindle assembly during meiosis I FYPO:0007851
  normal meiotic spindle polarity FYPO:0007852

> abolished protein localization to meiosis I spindle

added synonym to FYPO:0006455 (and the meiosis II term, FYPO:0006456)
