### ISSUE TITLE
NTR PMID:34352089 decreased endonucleolytic cleavage-dependent decay by premature transcription termination

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4069]
in this session
/curs/f5403fffd3ecaf81
Francois used
FYPO:0006613 | decreased termination of RNA polymerase II transcription
but, it is really  decreased this is decreased termination of 'transcriptional attenuation'.
In WT the  standard conditions the expression is repressed by premature transcription termination.

In the mutant the gene is upregulated  and full length transcripts appear.

I think it might be a bit like pho84 and pho1, except there isn't any evidence that a different transcription start sit is used .....

~I was thinking, something like 
decreased endonucleolytic cleavage-dependent decay by premature transcription termination
( I will be requesting a GO term to capture both sides of this in a single term)~

**Comment by mah11** [comment]
> but, it is really decreased this is decreased termination of 'transcriptional attenuation'.

This phrase isn't grammatical, and even if I omit the extra "decreased" I can't get "termination of transcriptional attenuation" to make a lot of sense. Transcription attenuation is a regulatory mechanism that works by terminating transcription earlier in some conditions than others; it's not what's being terminated.

> decreased endonucleolytic cleavage-dependent decay by premature transcription termination

Likewise, the proposed term name doesn't make sense either. As worded, it's not clear whether it's the transcription termination that's decreased, or the RNA decay, or both. Furthermore, from a quick look at the paper, I'm also getting the impression that "endonucleolytic cleavage-dependent decay by premature transcription termination" has it backwards -- the paper seems to be saying that Pac1-mediated pre-mRNA cleavage lets exonucleases in to do more degradation, _leading to_ transcription termination.

**Comment by ValWood** [comment]
>the paper seems to be saying that Pac1-mediated pre-mRNA cleavage lets exonucleases in to do more degradation, leading to transcription termination.

that is correct from a MF perspective, but I'm trying to describe the process that is affected.
The process begins with endonucleatic cleavage, this causes premature (but normal) termination, and the cryptic  non-polyadenylated transcripts are degraded.

After I  finished the paper I  came up with a better, but still clunky phrase for the primary GO term to describe this pathway:
nuclear-transcribed mRNA decay by premature transcription termination

 However, this phenotype isn't related to the entire process. 
And what they actually observe is increased polII occupancy over the entire orf (indicating a lack of premature termination), so maybe this would be a better way to describe?

**Comment by mah11** [comment]
> nuclear-transcribed mRNA decay by premature transcription termination

That's still backwards. It says that premature transcription termination is the mechanism that makes mRNA decay happen. You could make a case for the other way round, i.e. "premature transcription termination by nuclear-transcribed mRNA decay", I think, for the termination process.

If the "decay" part is supposed to refer to the cryptic non-polyadenylated transcripts, then you might get accused of trying to build a GO-CAM into one term -- that degradation seems to be downstream of terminating transcription.

> However, this phenotype isn't related to the entire process.
> And what they actually observe is increased polII occupancy over the entire orf (indicating a lack of premature termination), so maybe this would be a better way to describe?

I wonder if we should put something under FYPO:0003049 ! increased transcriptional readthrough?

Whether we do a "readthrough" term or not, we can add a term for the direct observations under FYPO:0006020 ! abnormal protein distribution along RNA polymerase II-transcribed genes.

**Comment by ValWood** [comment]
It's definitely a single pathway, the premature termination of transcription here isn't an accident. It's an evolved process to target transcripts  for degradation if the gene products are not required during specific conditions , via a mechanism that  involves a stem loop structure in the RNA. 

The endonuclease step is  part of the  premature transcription termination  (somehow this co-trancriptional cleavage causes premature termination based on some unknown signal), THEN the premature transcription is the mechanism that makes the mRNA decay happen-  because the transcripts are prematurely terminated, that means that the transcripts do not get polyadenylated, and hence get degraded (by 5'; and 3' decay, performed by different endonucleases).

The pathway begins with pac1 an endonuclease causing premature termination, then  degradation by 
dhp1 (5'-3' and probably by exosome)


>I wonder if we should put something under FYPO:0003049 ! increased transcriptional readthrough?

I wondered that at first. But to me 'readthrough' is transcription beyond the stop codon.
This is terminating transcription BEFORE the  stop codon, (so the phenotype here is where this normal premature termination, as a mechanism of -ve regulation of gene expression, is abolished).

**Comment by mah11** [comment]
> It's definitely a single pathway, the premature termination of transcription here isn't an accident. It's an evolved process to target transcripts for degradation ...

None of my comments have said anything about pathways or accidents, nor can they reasonably be construed as claims that this is not an evolved process.

> The endonuclease step is part of the premature transcription termination (somehow this co-trancriptional cleavage causes premature termination based on some unknown signal), THEN the premature transcription is the mechanism that makes the mRNA decay happen- because the transcripts are prematurely terminated, that means that the transcripts do not get polyadenylated, and hence get degraded (by 5'; and 3' decay, performed by different endonucleases).

This still says that premature termination is upstream of, not a mechanism of, transcript degradation. Saying "degradation by premature termination" doesn't match this description -- it's not consistent with the meaning in English of (this sense of) the word "by". "X by Y" means that Y is the mechanism that does X. Something like "premature termination leading to transcript degradation" would fit the description.

>> I wonder if we should put something under FYPO:0003049 ! increased transcriptional readthrough?
> 
> I wondered that at first. But to me 'readthrough' is transcription beyond the stop codon.

If this is accurate, OK. But please double-check, because in both GO and FYPO, *transcriptional* readthrough definitions only specify going past a normal termination site ("transcriptional readthrough" is an exact synonym for "transcription antitermination" in GO). I only see the stop codon specified in the GO def for *translational* readthrough.

**Comment by ValWood** [comment]
>  Something like "premature termination leading to transcript degradation" would fit the description.

Agreed. I already revised the GO ticket  to 'via' (based on the fact that the pac1 nuclease event is the first step, and causes termination of transcription). I should have updated here too.

> But to me 'readthrough' is transcription beyond the stop codon.
Sorry, I mean beyond a normal transcription termination site, but  for an mRNA the termination site is always beyond the stop codon.
In this instance, the transcription termination occurs before the normal transcription termination site (since  it occurs before the stop codon). It could not make a functional protein.

**Comment by mah11** [comment]
> In this instance, the transcription termination occurs before the normal transcription termination site (since it occurs before the stop codon). It could not make a functional protein.

How do you reconcile this statement with the termination/degradation phenomenon in question being normal under certain conditions (in condition x, transcription goes beyond a stop codon; under condition y, the normal-for-that-condition termination site is before the stop codon)? Again, the transcription antitermination/readthrough definition doesn't mention stop codons.

**Comment by mah11** [comment]
Coming back to the phenotype term: it sounds like it should emphasize "less of this kind of transcription termination", because that's the effect being detected by the assays for RNAPolII location. I'd go for something like "decreased cleavage-dependent termination of RNA polymerase II transcription", and not try to push the knock-on effect on transcript degradation into it.

**Comment by ValWood** [comment]
"decreased cleavage-dependent termination of RNA polymerase II transcription"
sounds fine. I can work with that for the phenotype.

**Comment by mah11** [comment]
> Transcription is terminated early during standard growth, and the resulting truncated mRNAs are targeted for degradation

If this phenomenon is normal, then the place where transcription stops is a normal termination site for the conditions.

**Comment by ValWood** [comment]
that's why I suggested 'attenuated' transcription. There must be a way to say the transcription  terminates in a way that would produce an  invalid (too short) translation product?

**Comment by mah11** [comment]
decreased cleavage-dependent termination of RNA polymerase II transcription FYPO:0007883

**Comment by ValWood** [comment]
does not seem to be a descendant of
FYPO:0006613

**Comment by mah11** [comment]
Oops, it was under an actively wrong parent (pol I instead of pol II). I've moved it to pol II as a stopgap, but we could use moving it (again) to the optimal parent as demo fodder. I'll leave this open until we've done that.
