### ISSUE TITLE
**abolished** histone H3-K9 dimethylation during vegetative growth PMID:34524082

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4072]
**abolished** histone H3-K9 dimethylation during vegetative growth

**Comment by mah11** [comment]
Wanna have a go at adding this yourself? :D

(I'm happy to do it tomorrow or Weds if you don't want to wait until the 19th to use the term.)

**Comment by ValWood** [comment]
We can save that one for the demo. The author used decreased with high penetracne but said it was abolished so I already approved with the existing annotation.
So no hurry. A  good one to save.

**Comment by mah11** [comment]
OK, I've assigned both of us. Woohoo!

**Comment by ValWood** [comment]
I'm reacding what as a scary Whooooo-Hooooo

**Comment by mah11** [comment]
abolished histone H3-K9 dimethylation during vegetative growth FYPO:0007886 added
