### ISSUE TITLE
PMID:12546793 cdc7/11  localization to kinetochore

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4078]
normal protein localization to kinetochore during mitotic spindle assembly checkpoint signaling

have
FYPO:0005300 | decreased protein localization to kinetochore during mitotic spindle assembly checkpoint signaling

**Comment by ValWood** [comment]
@mah11 Any idea why these are siblings not parent child?
<img width="558" alt="Screenshot 2021-11-29 at 11 31 25" src="https://user-images.githubusercontent.com/7359272/143860713-edef016c-628d-43e2-8e77-deb64e32fc77.png">

**Comment by mah11** [comment]
Do you have a reasoner installed & running yet?

In the output files, they're not siblings; e.g. in fypo-simple-pombase.obo (the one Kim uses for Chado, Canto, website, etc.), I see 

     id: FYPO:0005779
     name: normal protein localization to kinetochore during mitosis
     [snip]
     is_a: FYPO:0002901 ! normal protein localization to kinetochore during vegetative growth
     is_a: FYPO:0004328 ! normal protein localization during mitosis

so it must be inferred by the reasoner upon release.
