### ISSUE TITLE
split into 2 conditions

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4104]
othewise will need to pecompose for different media

<img width="456" alt="split conditions" src="https://user-images.githubusercontent.com/7359272/149785222-4c7e9218-bd48-4743-9e3d-08317aaac3bb.png">

**Comment by ValWood** [comment]
id: FYECO:0000196
name: glucose MM, urea nitrogen source

**Comment by ValWood** [comment]
id: FYECO:0000254
name: glucose MM, ammonium nitrogen source

name: glucose MM, glutamate nitrogen source

id: FYECO:0000264
name: glucose MM, organic nitrogen source, no inorganic nitrogen

id: FYECO:0000266
name: glucose MM, xanthine nitrogen source

id: FYECO:0000274
name: glucose MM, adenine nitrogen source

[Term]
id: FYECO:0000276
name: glucose MM, uracil nitrogen source

id: FYECO:0000278
name: glucose MM, isoleucine nitrogen source

id: FYECO:0000296
name: glucose MM, phenylalanine nitrogen source

id: FYECO:0000296
name: glucose MM, phenylalanine nitrogen source

id: FYECO:0000331
name: glucose MM, arginine nitrogen source

id: FYECO:0000331
name: glucose MM, arginine nitrogen source

id: FYECO:0000374
name: glucose MM, serine nitrogen source

**Comment by ValWood** [comment]
These terms are in FYECO (in the fypo root node directory)
I think we should 'decomp[ose" them otherwise we will need too many combinations?
Can you look at this some time? no hurry

**Comment by ValWood** [comment]
pombmine might be the easiest way to check the usage.

**Comment by manulera** [comment]
Hi @ValWood what was this issue about?

**Comment by ValWood** [comment]
I can take this one. It will probably still be there if you run out of tasks!

We have some conditions "precomposed" in pairs in the conditions ontology. I think we should aim to decompose the 
or we will have a combinatorial nightmare. 
Do you think that makes sense?

**Comment by kimrutherford** [comment]
> Actually @kimrutherford could you do a query for the sessions where these conditions are used some time

Hi Val.  This is what I get.  Doesn't seem like a long list.  Is that expected?

```
07fb3e57038e972d  FYECO:0000331
0fb69ef0f10965a2  FYECO:0000278
19ff38e31ee375f1  FYECO:0000264
4e3227943350f291  FYECO:0000254
525329ba6a2d8440  FYECO:0000266
525b70a4b9a10b41  FYECO:0000254
5beca4251520f38b  FYECO:0000296
64464dca7a13a142  FYECO:0000254
87c7d481ace79172  FYECO:0000254
8d053bcab39833a9  FYECO:0000374
94e20d207ffa7a12  FYECO:0000276
95bc2a3172175b7a  FYECO:0000254
9878a4d6e46a6189  FYECO:0000254
ceb652bddd3380fb  FYECO:0000276
d272c70052e00b9c  FYECO:0000254
e040917969e21e31  FYECO:0000254
e583692a60c79c22  FYECO:0000254
```
