### ISSUE TITLE
PMID:35008733 ceramide synthase paper (ceramide levels)

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4107]
- [x] increased cellular dihydrosphingosine-1-phosphate level (VG)
descendant of
increased level of substance in cell during vegetative growth
synonym_exact  increased DHS-1P level
~CHEBI:82829?~ CHEBI:16893 https://github.com/ebi-chebi/ChEBI/issues/4202

FYPO:0007916

- [x] decreased cellular dihydroceramide level (VG)  
synonym_exact decreased DH-cer level
descendant of 
decreased level of substance in cell during vegetative growth
CHEBI:139048

FYPO:0007916

**Comment by ValWood** [comment]
still need to update Canto

**Comment by ValWood** [comment]
@kimrutherford  shoud I be able to see this term in Canto. It was in the successful  update last week

**Comment by kimrutherford** [comment]
>  shoud I be able to see this term in Canto. It was in the successful update last week

Do you mean FYPO:0007916?  It's not in fypo-edit.obo

**Comment by ValWood** [comment]
That's weird. I was sure that was in the previous batch.

**Comment by ValWood** [comment]
All done.
