### ISSUE TITLE
TPV terms misplaced under morphology

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4116]
I have no idea why these are here

<img width="672" alt="Screenshot 2022-03-10 at 11 09 35" src="https://user-images.githubusercontent.com/7359272/157670889-86f221cb-2735-4bd8-b769-253785ea7a97.png">

**Comment by ValWood** [comment]
This one looks like terms have been dragged and dropped to the wrong place?
bith   should be under
https://www.pombase.org/term/FYPO:0000989

(I was warned a bit this, protege is very sensitive, sometimes you can move a term without realising)

**Comment by manulera** [comment]
This is the explanation of the reasoner of why it puts the ubiquitinated protein under abnormal cell morphology, to be dicussed when I understand logical definitions:

<img width="1142" alt="Screenshot 2022-07-14 at 19 09 50" src="https://user-images.githubusercontent.com/22526102/179042727-86f03d74-e784-4659-adb6-618161adcdb9.png">

**Comment by ValWood** [comment]
It's definitely something to do with "has_part" i the logical definintion. I'm not sure why but these logical defs are bad, so I removed them:

<img width="1186" alt="Screenshot 2023-08-16 at 12 26 24" src="https://github.com/pombase/fypo/assets/7359272/f6215ac0-c453-4f63-a98f-cf8fb3c8fcce">

<img width="1515" alt="Screenshot 2023-08-16 at 12 27 36" src="https://github.com/pombase/fypo/assets/7359272/99f36f0d-7284-4925-8113-ef8dc581b14f">

**Comment by ValWood** [comment]
well its fixed....
