### ISSUE TITLE
Ontology changes from PMID:24239120

### ISSUE THREAD

**Issue by manulera** [pombase/fypo#4130]
Full discussion can be found here: https://github.com/manulera/discussions_curation/issues/5

## Rearranging the children of FYPO:0000131

As of now, it looks like this:

* FYPO:0000131 abnormal mitotic spindle elongation
  * FYPO:0007071 increased rate of mitotic spindle elongation during anaphase A
  * FYPO:0005976 increased rate of mitotic spindle elongation during anaphase B
  * FYPO:0005343 decreased rate of mitotic spindle elongation during anaphase B
  * FYPO:0003268 decreased rate of mitotic spindle elongation

I would propose to rearrange the children like this:

* FYPO:0000131 abnormal mitotic spindle elongation
  * FYPO:XXXXXXX increased rate of mitotic spindle elongation(new parent):
    * FYPO:0007071 increased rate of mitotic spindle elongation during anaphase A (moved to children of new parent)
    * FYPO:0005976 increased rate of mitotic spindle elongation during anaphase B (moved to children of new parent)
    * FYPO:XXXXXXX increased rate of mitotic spindle elongation during prophase (new term requested in the curation session of the paper).
  * FYPO:0003268 decreased rate of mitotic spindle elongation
    * FYPO:0005343 decreased rate of mitotic spindle elongation during anaphase B (made the children of FYPO:0003268)
    * FYPO:XXXXXXX decreased rate of mitotic spindle elongation during prophase (new term requested in the curation session of the paper).

## Add term "Bipolar mitotic spindle"

Just like we have:

```mermaid
graph LR;
      FYPO:0000338[FYPO:0000338<br>abnormal mitotic spindle]-->FYPO:0000276[FYPO:0000276<br>monopolar mitotic sp<br>indle];
      FYPO:0000276[FYPO:0000276<br>monopolar mitotic sp<br>indle]-->FYPO:0004591[FYPO:0004591<br>monopolar mitotic sp<br>indle following norm<br>al mitosis];
      FYPO:0000276[FYPO:0000276<br>monopolar mitotic sp<br>indle]-->FYPO:0006592[FYPO:0006592<br>monopolar mitotic sp<br>indle nucleated from<br> old spindle pole bo<br>dy];
```

You could also have a child of FYPO:0001399 (normal mitotic spindle) called "bipolar mitotic spindle". This is important for double deletions that rescue spindle bipolarity (such as cut7Dpkl1D). The genetic interaction is mentioned, but it would be good to have the rescued phenotype.

## Add term "Transient abrupt spindle length decrease at anaphase onset"

This is mentioned in the curation session. I think this is an important phenotype to record, as it most likely indicates a change in spindle architecture in which interpolar microtubules are short, and kinetochore microtubules are long, and when anaphase A starts, there is a mini-collapse when cohesin bridges are cleaved.

**Comment by ValWood** [comment]
First block of new terms added with logical definitions

<img width="530" alt="Screenshot 2022-04-27 at 09 16 04" src="https://user-images.githubusercontent.com/7359272/165473434-e0f84d88-713a-44e9-a542-adfdac2dacf7.png">

**Comment by manulera** [comment]
✨ ✨  Nice ✨ ✨

**Comment by ValWood** [comment]
@manulera  based on https://github.com/pombase/fypo/issues/2512  do you still think I should add
"normal bipolar spindle"  as a new term, or should I add it as an exact synonym  of "normal mitotic spindle"
(or even rename to "normal bipolar mitotic spindle"?)

**Comment by ValWood** [comment]
also could you open a new ticket for this:
Perhaps move FYPO:0000324 close to other phenotypes that change mitotic phases and merge with FYPO:0004309

I am, inclined to agree, but I will need to review how this entire branch is organised, and I would like to wait until I  feel more comfortable with the ontology editing. For instance I  don't know how to do a term merge and my instructions don't appear to contain this information (although I will need to dig deeper).

Also, I would like to discuss the changes in a bit more detail to make sure I get it right, so maybe after biocurator. This will allow me to get the rest of this ticket closed.

**Comment by manulera** [comment]
> @manulera based on #2512 do you still think I should add "normal bipolar spindle" as a new term, or should I add it as an exact synonym of "normal mitotic spindle" (or even rename to "normal bipolar mitotic spindle"?)

Here I would say it should be added as a new term. I would say "normal spindle" should be a spindle that is undistinguishable from the wild type in the experiment.

This is often not the case in bipolarity rescues. For example, cut7 inactivation (typically thermosensitive mutants) will cause monopolar spindles. Bipolarity can be rescued by double deletion of pkl1D cut7D or pkl1D cut7-thermosensitive. The spindle is however shorter than wild-type (image below from Loncar et al. 2020). The phenotype would not be a "normal spindle", but "shorter spindle during metaphase". The shorter spindle should still be included, but the most important conclusion of the experiment is that the bipolarity is rescued, and not so much whether the spindle length changes.

![Screenshot 2022-04-27 at 09 34 53](https://user-images.githubusercontent.com/22526102/165477959-0488d6dc-fcdd-4c82-b8e3-90fc070ff5c8.png)

At the same time, from #2512 I see how making it a child of a normal spindle could be problematic, since the spindle is only partially normal. Maybe bipolar could be even the parent of normal? Since all normal spindles are bipolar but not the opposite?

**Comment by manulera** [comment]
> also could you open a new ticket for this:
> Perhaps move FYPO:0000324 close to other phenotypes that change mitotic phases and merge with FYPO:0004309

Moved to #4132

**Comment by manulera** [comment]
> "Transient abrupt spindle length decrease at anaphase onset" can you suggest a definition for this?

A cell phenotype in which the spindle length decreases abruptly at anaphase onset. In PMID:24239120, this is likely due to interpolar microtubules being shorter than kinetochore microtubules, so cleavage of cohesin links leads to the shrinkage in length.

The second part can be removed, as this is an interpretation of the data, and there might be other causes for it (the authors did not really gave an explanation for how this happens).

**Comment by ValWood** [comment]
Thanks!

**Comment by ValWood** [comment]
I think all aspects of a process need to be normal to have a normal phenotype annotation (although this seems odd because we would not necessarily know this?)

I am looking back over old tickets, see
https://github.com/pombase/fypo/issues/2637
https://github.com/pombase/fypo/issues/318
https://github.com/pombase/fypo/issues/861

in summary, I think when we use 'normal' all of the existing parts should be normal. 

I also found that "short bipolar spindle' is an exact synonym of "short mitotic spindle" Would it be helpful to switch so that "short bipolar spindle" is the primary name? 
See also https://www.pombase.org/term/FYPO:0001574
A physical cellular phenotype in which the mitotic spindle has two poles but is otherwise structurally abnormal.

I think this is all to do with how phenotypes are modelled logically with has_parts but my knowledge about this is very vague.

**Comment by ValWood** [comment]
"Transient abrupt spindle length decrease at anaphase onset" 
A cell phenotype in which the spindle length decreases abruptly at anaphase onset. 

I added this part as a comment:
In PMID:24239120, this is likely due to interpolar microtubules being shorter than kinetochore microtubules, so cleavage of cohesin links leads to the shrinkage in length.

FYPO:0007961

**Comment by manulera** [comment]
> I also found that "short bipolar spindle' is an exact synonym of "short mitotic spindle" Would it be helpful to switch so that "short bipolar spindle" is the primary name?

Aha, yes that makes sense. Perhaps "short bipolar mitotic spindle" to also diffenciate from meiotic. This is particularly important for cut7Dpkl1D which has meoitic spindle-specific phenotypes.

**Comment by ValWood** [comment]
I switched the exact synonym and term name for "short mitotic spindle"/"short bipolar mitotic spindle" and the 2 children.

I think this ticket is done. Open a new one if I missed anything.

**Comment by ValWood** [comment]
I reopened because they get auto closed when I run the release pipeline (If I do it properly), at the moment I am checking that the changes look OK because I am a novice

**Comment by ValWood** [comment]
This did not close with hte commit, but the terms seem to be there.
