### ISSUE TITLE
PMID:18716626 sgo1 paper

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4137]
unequal meiotic sister chromatid segregation 
add exact 
nondisjunction at meiosis II
nondisjunction of sister chromatids in meiosis II

NTR decreased protein localization to centromere, meiosis I pericentromeric region
NTR normal meiotic sister chromatid cohesion protection anaphase I

**Comment by manulera** [comment]
Added the new terms, and the synonims I will replace them in the [session](https://curation.pombase.org/pombe/curs/ea1ec138d2671e21) and approve it once they are available in canto.



sgo1 | sgo1-VE(aaV242E)[Not assayed] | FYPO:0006238 | decreased protein localization to centromere
-- | -- | -- | --
sgo1 | sgo1-VE-CD(sgo1-VE-CD ectopically centromere local  ... | FYPO:0006425 | normal meiotic sister chromatid cohesion at centromere during meiosis I
-- | -- | -- | --

* [ ] Use in canto session

**Comment by manulera** [comment]
Done
