### ISSUE TITLE
Term request for PMID:32327557

### ISSUE THREAD

**Issue by manulera** [pombase/fypo#4159]
# PMID:32327557

## Term requests

Children of FYPO:0007260 -'abnormal cellular process during meiotic cell cycle'-:

* abnormal cellular process during meiotic cell cycle (FYPO:0007260):
  * abnormal spindle elongation during meiosis I (similar to FYPO:0000131)
    * decreased rate of spindle elongation during meiosis I (similar to FYPO:0003268)
      * decreased rate of spindle elongation during meiotic anaphase B I (similar to FYPO:0005343)

Children of FYPO:0000734 'abnormal meiotic spindle'

* abnormal meiotic spindle - FYPO:0000734
  * long spindle microtubules protruding beyond spindle pole body during meiosis I (similar to FYPO:0003787)

## Question

* [x] In the paper they show that klp2 localizes to the SPB during meiosis I but not during mitosis. Is this worth a NOT annotation for GO cellular component? (klp2 does not localize to SPB during mitosis). In the cut7D pkl1D background, meiosis I often has monopolar spindle, but this is moderately rescued by klp2D on top of cut7D pkl1D. On the other hand, monopolar spindles do not occur during mitosis in cut7D pkl1D. The authors associate this differential localisation with the different function of klp2 in mitosis and meiosis.

**Comment by manulera** [comment]
@ValWood what about the NOT annotation?

**Comment by ValWood** [comment]
Definitely. This is a perfect place to use a NOT. Otherwise we might get inferred annotations  later (NOT prevents this). We only use a NOT when something might be really expected but does not turn out to be the case.
