### ISSUE TITLE
new terms for PMID:25348260

### ISSUE THREAD

**Issue by manulera** [pombase/fypo#4161]
* New sibling of FYPO:0004754 ('abolished protein localization to mitotic spindle during mitosis'):
  * Abolished protein localization to mitotic spindle microtubules

I think here it would be good to have this extra sibling, because it can be that a protein properly localizes to the spindle pole but not to the spindle microtubules. For example, cut7 localizes to the SPB and spindle microtubules during metaphase, but some truncations of cut7 localize to the SPB only and not the spindle microtubules.

**Comment by ValWood** [comment]
Some existing annotations might  move down to the new term?

**Comment by manulera** [comment]
> Some existing annotations might move down to the new term?

I guess some annotations from `'abnormal protein localization to mitotic spindle'` might come here, but I would imagine that none of the `'abolished protein localization to mitotic spindle'` should.

I think this term would actually require some rearrangement, so maybe I can wait until I know how to write the logical definitions to add it. Some other children of `'abnormal protein localization to mitotic spindle'` should also be related to it, like `'abnormal protein localization to mitotic spindle midzone'`

**Comment by ValWood** [comment]
I will close this
not that 
abnormal protein localization to mitotic spindle' should also be related to it, like 'abnormal protein localization to mitotic spindle midzone'
is already instantiated
