### ISSUE TITLE
NTR final for PMID:33823663

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4165]
final term to complete :

normal mating efficiency during nitrogen stress

for byr1-S22A(aaS22A)[Not assayed]

**Comment by ValWood** [comment]
logical defs not possible until  this GO ticket is resolved
https://github.com/geneontology/go-ontology/issues/22996

**Comment by manulera** [comment]
The term is already in Canto, so I made the annotations in the curation session and approved it. Logical definition is not there as you said.

**Comment by ValWood** [comment]
closing, we might not be able to define mating efficiency logically since it's a population term
