### ISSUE TITLE
FYPO release pipeline fails in my macbook

### ISSUE THREAD

**Issue by manulera** [pombase/fypo#4175]
Hello,

I am trying to run the FYPO release again with the same docker settings as last Tuesday, when it worked:

<img width="502" alt="Screenshot 2022-06-23 at 17 17 49" src="https://user-images.githubusercontent.com/22526102/175337042-297923d0-191b-46b7-aeb0-ba6ddb2a874f.png">

Now when I run `sh run.sh make synonyms -B`, I get this error:

```
Makefile:171: warning: ignoring old recipe for target 'prepare_release'
robot --catalog catalog-v001.xml merge -i fypo-edit.obo template --template ../templates/bulk_synonyms.tsv --output ../templates/bulk_synonyms.owl
make: robot: Operation not permitted
make: *** [fypo.Makefile:65: ../templates/bulk_synonyms.owl] Error 127
```

This is a step that I could run the other day without increasing the memory from 2GB (the default). I only encountered the memory problem when running `sh run.sh make prepare_release -B`. That one required me to change to 13GB of memory. Also, even then it would try to run it and then fail, but this fails immediately. Perhaps a permissions error, since it says `make: robot: Operation not permitted`? Some chmod / sudo? Any thoughts?

I tried deleting the image and pruning docker cache, restarting docker, different settings with more swap and CPUs, nothing worked.

**Comment by manulera** [comment]
![Screenshot 2022-06-23 at 17 46 03](https://user-images.githubusercontent.com/22526102/175340562-86b0d908-bae6-439a-a5d7-671df3cdd8ca.png)

**Comment by ValWood** [comment]
Has there been an new ODK release at all? (Not that I know how to find out !)

**Comment by ValWood** [comment]
Is it possible to run any of the next 2 steps (as far as I know there is no mandated order for these). At least that might indicate whether there is something wrong with the obo  file you committed or the single step in the pipeline. Maybe...

**Comment by kimrutherford** [comment]
HI Manu.

I can't explain why it used to work but now it doesn't.

There are lots of internet posts about "Operation not permitted" on Macs.  It might be worth trying this fix: https://macreports.com/terminal-says-operation-not-permitted-on-mac-fix/

It might be Docker-specific: https://stackoverflow.com/questions/58482352/operation-not-permitted-from-docker-container-logged-as-root

If that fix doesn't help I suggest asking the ODK developers who probably use Macs.

**Comment by kimrutherford** [comment]
> Has there been an new ODK release at all? (Not that I know how to find out !)

Looks like there was a release 3 days ago: https://github.com/INCATools/ontology-development-kit/releases

Since ODK uses Docker, the update will be downloaded automatically next time you run an ODK command.

**Comment by manulera** [comment]
Hi Kim,

Thanks for having a look, unfortunately they didn't work :(.

Could you try to run the command in your computer? I pushed the changes to the repo, so you would just have to pull `fypo-release-2022-06-22` and then:

```
cd src/ontology
sh run.sh make synonyms -B
```

If that works in your computer, at least we know that the problem is in my macbook and not in the docker image.

**Comment by kimrutherford** [comment]
Hi!

I tried it on Linux on got the same error.  :-(

After a bit of Googling I found a suggestion to update my installation of Docker:
https://github.com/adoptium/temurin-build/issues/2976#issuecomment-1152142311

Updating to the latest version of Docker fixed it for me so maybe you could try that, if you haven't already?

**Comment by manulera** [comment]
Yes, that did the trick! Thanks @kimrutherford ! Also @ValWood remember to update your docker for the next time!

PS: I added this error to the wiki https://github.com/pombase/fypo/wiki/FYPO-release-procedure#release-failure

**Comment by manulera** [comment]
New error! On the final step that I left for the end of the day (`sh run.sh make prepare_release -B`)
```
if [ true  = true ]; then cat tmp/seed.txt imports/iao_terms.txt | grep -v ^# | sort | uniq >  imports/iao_terms_combined.txt; fi
if [ true  = true ]; then robot --catalog catalog-v001.xml query -i mirror/iao.owl --update ../sparql/preprocess-module.ru \
	extract -T imports/iao_terms_combined.txt --force true --copy-ontology-annotations true --individuals include --method BOT \
	query --update ../sparql/inject-subset-declaration.ru --update ../sparql/postprocess-module.ru \
	annotate --ontology-iri http://purl.obolibrary.org/obo/fypo/imports/iao_import.owl annotate -V http://purl.obolibrary.org/obo/fypo/releases/2022-06-24/imports/iao_import.owl --annotation owl:versionInfo 2022-06-24 --output imports/iao_import.owl.tmp.owl && mv imports/iao_import.owl.tmp.owl imports/iao_import.owl; fi
if [ true  = true ] && [ true  = true ] && [ true  = true ]; then curl -L http://purl.obolibrary.org/obo/chebi.owl.gz --create-dirs -o mirror/chebi.owl.gz --retry 4 --max-time 200 && robot --catalog catalog-v001.xml convert -i mirror/chebi.owl.gz -o mirror/chebi.owl.tmp.owl && mv mirror/chebi.owl.tmp.owl mirror/chebi.owl; fi
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   331  100   331    0     0   1234      0 --:--:-- --:--:-- --:--:--  1235
  0 45.4M    0  141k    0     0   7927      0  1:40:07  0:00:18  1:39:49 39328
curl: (18) transfer closed with 47480691 bytes remaining to read
make: *** [Makefile:304: mirror/chebi.owl] Error 18
rm imports/iao_terms_combined.txt imports/ro_terms_combined.txt
```

A problem with curl it seems. I guess I would need to change some setting passged to curl in this line?:

```
 then curl -L http://purl.obolibrary.org/obo/chebi.owl.gz --create-dirs -o mirror/chebi.owl.gz --retry 4 --max-time 200 && robot --catalog catalog-v001.xml convert -i mirror/chebi.owl.gz -o mirror/chebi.owl.tmp.owl && mv mirror/chebi.owl.tmp.owl mirror/chebi.owl;
```

**Comment by kimrutherford** [comment]
Hi Manu.

I think the problem this time is the EBI website.  Val and I saw this issue a few weeks ago and then it went away.  We both contacted the EBI helpdesk but that didn't help.   :-)

You can try this command download outside of the ODK and Docker with:

```
curl -L http://purl.obolibrary.org/obo/chebi.owl.gz -o /tmp/chebi.owl.gz --retry 4 --max-time 200
```

Or just go http://purl.obolibrary.org/obo/chebi.owl.gz with your browser.  At the moment that fails for me.  Also I tried downloading with `wget` and had the same problem from oliver1 and from my desktop.

I suggest trying again on another day.  If it's not working on Monday we should contact the EBI again.

**Comment by ValWood** [comment]
There seem to be major issues with EBI website right now. I have been having problems accessing Pfam (via links from external databases) and running Jackhmmr for a few days. There has been a persistent problem over the past few weeks (Confirmed by my insider contacts).

**Comment by manulera** [comment]
It worked today, I added curl error 18 to the wiki as well.
