### ISSUE TITLE
Can we use fypo-idranges.owl to setup allocated IDs in Protege?

### ISSUE THREAD

**Issue by manulera** [pombase/fypo#4181]
We have this file where it seems we could allocate IDs to different editors so that we can edit the ontology in parallel.

https://github.com/pombase/fypo/blob/fa108ba9953eaac1d0a9ce88a05c2822f67791d9/src/ontology/fypo-idranges.owl#L33-L48

For now, what we do is to go to the protege settings, and set the starting ID, but if it would be possible to set this in an external config file so we don't have to do it every time / don't forget, we would prefer that, is it possible?

**Comment by manulera** [comment]
Reply from @gouttegd on Slack:

> Not sure I understand what you mean. Each ontology editor only needs to set their ID range in Protégé only once, there is no need to do it “every time”.
The only problem is when you work on different ontologies in parallel – in that case every time you switch from one ontology to another you need to set again the correct ID range for the ontology you’re switching to. There is currently no workarounds, but the next version of Protégé will include a feature that reads the -idranges.owl file to automatically set up the range for you.

**Comment by ValWood** [comment]
yay, we did this!
