### ISSUE TITLE
Cell fusion phenotypes cellular or population?

### ISSUE THREAD

**Issue by manulera** [pombase/fypo#4185]
cc @ValWood 

This came up when revising curation from PMID:35673994, and concerns `abolished cell fusion during mating` and `decreased cell fusion during mating`:

<img width="396" alt="Screenshot 2022-07-11 at 19 50 19" src="https://user-images.githubusercontent.com/22526102/178344260-4c42717f-30e5-4b01-8c98-15af692ab0d7.png">

In this paper, they quantify the percentage of "mating pairs" that are fused. I think "mating pairs" means cells that have formed the shmoo, and present the characteristic shape. Below an example of a cell that is in a mating pair, and not fused.

![Screenshot 2022-07-11 at 21 40 37](https://user-images.githubusercontent.com/22526102/178345120-8ad3e18f-a76b-4925-b93b-0dc2ce4ca60b.png)

This means that at least in this paper, percentages represent a genuine "cell phenotype", they are not the ratio of cells in the population that have formed zygotes/asci vs. the total number of cells. In this case then, I think `decreased cell fusion during mating` should not be used, and just use `abolished` with penetrance.

Also, I think `decreased cell fusion during mating` should not be a cell phenotype, because from the cell perspective the cells are either fused or not fused, unless this would refer to a partial fusion, but this does not seem to be the case. Annotations from other Sophie Martin's papers can be moved to abolished with penetrance, and if you agree with this, I can check the rest of the papers to see whether they can also be moved there, or whether we should move them to a population phenotype.

What do you think?

**Comment by ValWood** [comment]
I agree!

**Comment by manulera** [comment]
Annotations removed (double-check before FYPO release)

**Comment by manulera** [comment]
Sent email to Sophie Martin. Term should be obsoleted either way, but there would be two solutions:

* Abolished with penetrance
* Population phenotype describing a lower proportion of fused mating pairs
> Since most annotations come from papers from your lab, I wanted to ask you if you would agree that annotations for 'reduced cellular fusion during mating' can be similarly moved to 'abolished cellular fusion during mating'. The 'reduced cellular fusion during mating' have severity annotations, that could be transferred to penetrance. My understanding is that a mating pair would always end up fusing, so the expectation would be ~100% in wild-type, similarly to the nuclear fusion case.

> My only doubt in this case is whether the lack of fusion in some cases might indicate a delay (cell fusion could still happen if waiting more). In that case, we can think of a way to annotate this differently as a population phenotype (lower frequency of fused mating pairs or something like that).
