### ISSUE TITLE
NTR for PMID:21444751 and terms FYPO:0004721 and FYPO:0004617

### ISSUE THREAD

**Issue by manulera** [pombase/fypo#4197]
@ValWood 

I think these terms should be obsoleted.

* increased rate of microtubule depolymerization at minus end (FYPO:0004617)
* decreased rate of microtubule depolymerization at minus end (FYPO:0004721)

The first term does not have any annotation, the second one has only one, mto1D, from PMID:15772152, which I think is not correct.

In wild-type cells, microtubule minus ends are capped by the gamma-tubulin complex (they are not dynamic, they don't grow or shrink), so the minus end depolymerisation speed of the wild type in normal conditions cannot be measured and compared.

I think the term FYPO:0004721 might have been originally annotated to mto1D because in those mutants, some minus-ends are not capped with gamma-turcs and are dynamic. Minus ends grow and shrink at lower rates than plus ends. In the paper, they measure all minus and plus ends shrinkage rates together in wt and mto1D cells, so the overall shrinkage rate is lower (because in wt cells there is only dynamic plus ends, and in mto1D cells there is both). This might have been confusing and lead to this annotation.

It is possible to measure shrinkage speeds of minus ends in wild-type cells, specifically using laser ablation (cutting microtubules). This leads to minus end depolymerisation. It could be that in a certain study this minus end depolymerisation is compared in two genetic backgrounds. In that case, however, the phenotype could specify "after laser ablation" or something, so I would say to obsolete the terms.

I propose new term `dynamic microtubule minus ends in interphase bundles`, with approximate synonym `uncapped microtubule minus ends in interphase bundles`, `unstabilised ...` and annotate mto1D to that.

**Comment by ValWood** [comment]
OK go ahead with the obsoletion. You know best here.

Also, this was my annotation and it seems I was unsure and needed to check!

<img width="1146" alt="Screenshot 2022-08-01 at 15 15 45" src="https://user-images.githubusercontent.com/7359272/182168150-5bd7925e-34c1-4c56-aa7d-a4d540daf368.png">


I deleted it!

**Comment by manulera** [comment]
Done in Protege
