### ISSUE TITLE
Diff as a comment in PRs

### ISSUE THREAD

**Issue by manulera** [pombase/fypo#4200]
Hi @kimrutherford and @ValWood 

I have added this github action: https://github.com/pombase/fypo/blob/fypo-release-2022-07-14/.github/workflows/diff.yml

It runs when a PR into master is made, and prints the difference between the previous and new ontology in a comment. See the comment here:

https://github.com/pombase/fypo/pull/4199#issuecomment-1222373760

From now on, we could use this for the release, so that at each release the changes made can be seen.

Let me know if you would want something else added for this.

**Comment by ValWood** [comment]
Thanks!
