### ISSUE TITLE
Files too big in next release

### ISSUE THREAD

**Issue by manulera** [pombase/fypo#4201]
Hello @kimrutherford @ValWood 

Our `fypo.owl` and `fypo-full.owl` exceed 100MB, and `fypo-non-classified.owl` soon will. Those files are too big to store them in version control in GitHub. The solution that @matentzn provided was to remove them from the repository, and attach the files at the release stage.

@kimrutherford, I suppose you are using some of these files for the websites, so we can discuss how to go about this. For now, I will not make the release until we sort this out. let me know if we should discuss on a call.

**Comment by kimrutherford** [comment]
Thank you both.  PomBase Chado uses fypo-simple-pombase.obo so it should be OK.

**Comment by manulera** [comment]
Ok, so for now I have moved the biggest three owl files mentioned to the gitignore, and I will attach them to the release when I make it. I will document this in the wiki as well.

I guess eventually we would want to move either all of them, or at least the non-obo ones, that are the biggest ones.

**Comment by matentzn** [comment]
@manulera I will have to change the OBO configuration of FYPO entirely, and it would be much easier for me if we could have either all or no release artefact be attached to the release..

**Comment by manulera** [comment]
Ok, we can make those changes in a next release (I can do it next week, there are some pending terms still), but I will release this one already, since we really need these new terms and this has been on hold for quite a while.

**Comment by matentzn** [comment]
Its fine to keep the files in the repo. Just attach them all as well to the repo, that's all!

**Comment by manulera** [comment]
Alright! I will do that

**Comment by manulera** [comment]
Should be there:
https://github.com/pombase/fypo/releases/tag/v2022-08-24

**Comment by manulera** [comment]
Ok, I have added a warning to the release wiki and added some notes on how to move files that are too big out of the repo, and how to attach files manually to the release. @matentzn says that we can automate this eventually, so we can look into that, but for now this should be enough for anyone to reproduce what I did manually.

https://github.com/pombase/fypo/wiki/FYPO-release-procedure#files-too-big

**Comment by manulera** [comment]
This is the reason for the problem with bioportal @ValWood

**Comment by matentzn** [comment]
Bioportal must be taught to use PURLs.. Not hard coded raw.github links..
