### ISSUE TITLE
Cell phenotype: Cell sensitive to mechanical stress

### ISSUE THREAD

**Issue by manulera** [pombase/fypo#4204]
Hi @ValWood, I will create an abnormal cell phenotype called `cell sensitive to mechanical stress`, and we can figure out placement and logical definition in the future.

_Originally posted by @manulera in https://github.com/pombase/fypo/issues/4182#issuecomment-1203836675_

**Comment by ValWood** [comment]
can close for now?

**Comment by manulera** [comment]
Yes, why not, will add the label in case.
