### ISSUE TITLE
NTR: decreased glucose import PMID:35781263

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4209]
decreased glucose import
child of 
FYPO:0001827 | abnormal glucose import

**Comment by ValWood** [comment]
No hurry, I used decreased to get the session through.

**Comment by manulera** [comment]
addressed in protege

**Comment by manulera** [comment]
Hi @ValWood the terms are available, I guess the terms concerned are the ones FYPO:0001827 but I was not sure.
