### ISSUE TITLE
NEW TERM REQUESTS FOR PMID:36058798, PMID:23873862

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4224]
For @snezhkaoliferenko

PMID:36058798
- [x] cell lysis during hyphal growth phase 
is_a cell lysis (FYPO:0002488)

PMID:23873862
- [x] defective blue light photoreceptor activity 
is_a  abnormal molecular function
FYPO:0008030

- [x] defective blue light response
is_a cellular response phenotype
FYPO:0008031

sexual flocculation in response to light
defective flocculation in response to light
sexual flocculation

**Comment by ValWood** [comment]
need to add
GO:0009882 blue light photoreceptor activity
to GO import and then add logical def

**Comment by ValWood** [comment]
@snezhkaoliferenko
"sexual flocculation"  and "sexual flocculation" 
do you need normal, or abnormal terms here?

**Comment by ValWood** [comment]
Also, how is it 'defective" (usually increased or decreased...)

**Comment by snezhkaoliferenko** [comment]
hello! sorry, was stuck in a meeting, just saw this. 'decreased' is good! for sexual flocculation i mean 😉

thank you!
sx
________________________________

**Comment by ValWood** [comment]
so the 
"sexual flocculation in response to light" is decreased, compared to normal WT
"sexual flocculation in response to light"?

**Comment by ValWood** [comment]
also, is this also "blue light"
(can then  be a response to blue light too)

**Comment by ValWood** [comment]
I added "sexual flocculation in response to bue  light"
so let me know if it  requires editing

**Comment by ValWood** [comment]
We have a logical problem.

Flocculation is defined as 
"Flocculation is the non-sexual aggregation of single cells."
so I can't add ""decreased sexual flocculation in response to bue light"
(or any sexual flocculation term)

Definition ([GO:0000128 GONUTS page](http://gowiki.tamu.edu/wiki/index.php/Category:GO:0000128))
The reversible, non-sexual aggregation of single-celled organisms in suspension to form aggregates of many cells known as flocs.

if it is sexual, it  needs to be just aggregation.

Please advise ;)

**Comment by ValWood** [comment]
I think the correct term in GO is:

GO:0000752   agglutination involved in conjugation with cellular fusion
Definition
The aggregation or adhesion of compatible mating types via complementary cell-cell interactions during conjugation with cellular fusion of a unicellular organism. An example of this process is agglutination in Saccharomyces cerevisiae.

**Comment by ValWood** [comment]
I'm going to label this 
"decreased sexual agglutination in response to blue light"

exact_ synonym "decreased conjugation with cellular fusion in response to blue light"

**Comment by snezhkaoliferenko** [comment]
okay!
xxxxx
________________________________

**Comment by ValWood** [comment]
equivalence axiom will be something like:

'has part' some 
    ('increased occurrence'
     and ('inheres in' some 'agglutination involved in conjugation with cellular fusion'))

with a part for "response to blue light"

**Comment by snezhkaoliferenko** [comment]
okay! the new FYPOs are not there yet, right? i've just looked
________________________________

**Comment by ValWood** [comment]
not yet, @manu will run the release pipeline later, then  Canto should update automatically overnight I think... @kimrutherford does japonicus canto update nightly?

**Comment by snezhkaoliferenko** [comment]
ah i see thank you! i think yes, japonicus canto does update nightly
________________________________

**Comment by kimrutherford** [comment]
> i think yes, japonicus canto does update nightly

Yep!  Everything should be up to date by 6am each day.

**Comment by ValWood** [comment]
Hi @snezhkaoliferenko im closing this as these terms should be available to use, but they aren't in the session yet. So let me know if you have any issues, can't find them etc.

**Comment by snezhkaoliferenko** [comment]
thank you! i used it for their paper!
sx
________________________________
