### ISSUE TITLE
Weird line in diff

### ISSUE THREAD

**Issue by manulera** [pombase/fypo#4230]
Hi @matentzn, we get this diff in fypo-edit.owl:

```diff
-# Object Property: <http://purl.obolibrary.org/obo/RO_0002573> (qualifier)
+# Object Property: <http://purl.obolibrary.org/obo/RO_0002573> (has modifier)
```

This is not fixed by running `sh run.sh make normalise_xsd_string`

Is it normal?

See diff here:
https://github.com/pombase/fypo/pull/4229/files#diff-5ddd869d886fb89b8634e3116e8ba06c6ca13f50686e5c99443e48f3fc238166L10146-R10146

**Comment by matentzn** [comment]
Yep, this is normal RO changed the label of the property http://purl.obolibrary.org/obo/RO_0002573, and OWLAPI injects that label into the serialisation automatically.

**Comment by manulera** [comment]
Thanks!
