### ISSUE TITLE
Email question on FYPO terms with logical definitions containing obsoleted GO terms

### ISSUE THREAD

**Issue by manulera** [pombase/fypo#4246]
Hi @ValWood 

Here is what you asked for in the email.

The graphs are huge, so I saved them as html files, I think you can see them if you open them in your browser. Then there are the lists with all the children of each term as txt files.

Best,
Manu

[for_val.zip](https://github.com/pombase/fypo/files/10500870/for_val.zip)

**Comment by ValWood** [comment]
Thanks, yes that's too much!

Could you do the same but only for  normal/abnormal histone modifications (this is the bulk, and  I can easily deal with the others)

Will this always use the up to date ontology ? if yes, how can I save as a pdf, so I have a copy of the   how the graph looks currently  in case all of the inferred relations are lost due  to the GO obsoletions)

**Comment by manulera** [comment]
The html pages that I sent you won't change. It's a static file, so it won't update with the ontology. Abnormal histone modification is still a huge graph. Here is a video on how you can do the same thing in the website if you want, so you can pick the right term.

Website url:

https://ontologynetwork.netlify.app/

How to change the display:

https://user-images.githubusercontent.com/22526102/214637084-c7b85ce2-ba27-470d-be61-2fa6bf907d28.mov

How to download the page forever (better than pdf since they are quite big):

https://user-images.githubusercontent.com/22526102/214635926-846a5278-b9c1-4e70-bb63-0cb9d71b91ed.mov

How to get a list of parent or child terms shown in the graph (It's printed to the browser console)

https://user-images.githubusercontent.com/22526102/214636161-2df4986b-bf18-4826-adf2-575232ccbaae.mov

**Comment by ValWood** [comment]
thanks!
