### ISSUE TITLE
Also probably better to say 'increased vegetative cell population viability'

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4272]
Also probably better to say 'increased vegetative cell population viability'

_Originally posted by @manulera in https://github.com/pombase/canto/issues/2696#issuecomment-1433437425_

**Comment by ValWood** [comment]
Actually I can't locat hte term name. Is this the primary name or a synonym?

**Comment by manulera** [comment]
It does not exist, I am creating it for the HTP paper

**Comment by ValWood** [comment]
OK
