### ISSUE TITLE
Migrating FYPO to ODK 1.4

### ISSUE THREAD

**Issue by matentzn** [pombase/fypo#4274]
@manulera I am making a big push migrating all ontology repos to ODK 1.4. Would you like to do it yourself?

```
docker pull obolibrary/odkfull
cd src/ontology
sh run.sh make update_repo
```

Then pull request and wait for QC to pass.

Let me know if you have problems.

**Comment by manulera** [comment]
Hi @matentzn. OK! I will try that now.

Best,
Manu

**Comment by manulera** [comment]
Hi @matentzn I ran this an assigned you as a reviewer in #4281, just to double-check that all went well.
