### ISSUE TITLE
PMID:36302945 adaptive growth

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4313]
~abnormal adaptive growth
abolished adaptive growth
abolished adaptive population growth in response to endogenous (R,Z)-10-hydroxyoctadec-8-enoic acid
abolished adaptive growth in response to endogenous ferrichrome
decreased adaptive growth in response to endogenous ferrichrome
normal adaptive growth in response to endogenous ferrichrome~

**Comment by manulera** [comment]
Hi @ValWood,

Sorry, it took me a while to come to this. Not sure we should really add these adaptative growth terms. I can see how for an enrichment it would be meaningful. However, from the annotation point of view, wouldn't it make more sense to add a FYECO term `co-culture with wild-type cells`, `cell extract added` or something like that?

> From the methods: Wild-type cells, 50% MeOH extracts of cells (see below), NSF or ferrichrome were spotted next to the test strains.

We could pre-compose the growth terms "decreased vegetative cell population growth when co-cultured with wild-type cells". I feel like this is more a descriptive of the experiment, adapatative growth can be a narrow synonym?

**Comment by ValWood** [comment]
I agree, it's a bit weird.
I will do as growth terms + condition.

**Comment by ValWood** [comment]
So should we just add FYECO
"co-culture with wild-type cells"
"+ (R,Z)-10-hydroxyoctadec-8-enoic acid"
"+ ferrichrome"

FYPO
decreased vegetative cell population growth when co-cultured with wild-type cells" 
decreased vegetative cell population growth in the presence of wild-type cell extract"
with adaptive growth synonyms.

We can use these as a test because I kept them waiting much longer than usual. I didn't get to this before Italy and it fell of my radar.

**Comment by manulera** [comment]
Sounds good. Do you want me to add those myself?

**Comment by ValWood** [comment]
I made the changes for FYPO and FYECO
