### ISSUE TITLE
Automation of release

### ISSUE THREAD

**Issue by manulera** [pombase/fypo#4314]
Hi @matentzn 

At some point you mentioned the possibility to automate the release procedure (via github action or something similar?). We could attempt this for our next release. Let me know what the steps would be.

**Comment by matentzn** [comment]
1. [Run a release](https://github.com/mgijax/mammalian-phenotype-ontology/blob/main/.github/workflows/deploy.yml) (Example from MP)
2. [Refresh imports](https://github.com/mgijax/mammalian-phenotype-ontology/blob/main/.github/workflows/imports.yml) (Example from MP)

I would strictly decouple the two to create single points of failure.

**Comment by manulera** [comment]
Hi @matentzn the refresh import failed:

https://github.com/pombase/fypo/actions/runs/4757474001/jobs/8454333759

**Comment by matentzn** [comment]
Yes, you need to switch your import to the CHEBI slim (most of our ontologies are already rewired):

https://github.com/mgijax/mammalian-phenotype-ontology/blob/main/src/ontology/mp-odk.yaml#L34

This will drastically reduce memory requirements.

Same for PRO (scroll up in ODK file).

**Comment by manulera** [comment]
Thanks @matentzn. Will do that. There release seems to run properly, but it has failed twice at the stage of uploading the release files (it failed on different files with "failed, reason: read ECONNRESET"). Any advice on this?

https://github.com/pombase/fypo/actions/runs/4757864436

**Comment by matentzn** [comment]
You will have to ask that in the git-n-github channel on obo slack - I assume it was a temporary fluke, as I never encountered anything like this, but I don't know for sure.

**Comment by gouttegd** [comment]
Don’t forget to run `sh run.sh make update_repo` (and to commit the updated `Makefile`) after changing anything in `fypo-odk.yaml`. Otherwise your changes have no effects.

Here, your second run is still trying to mirror the full CHEBI, because the Makefile was not updated.

**Comment by manulera** [comment]
Hi @gouttegd thanks! I didn't know that.

**Comment by manulera** [comment]
Ok, now it moved passed that point, and it will work next time. I just got the error below

```
make: *** No rule to make target 'remove_patternised_classes'.  Stop.
Error: Process completed with exit code 2.
```

I see that we are not doing this in this repo, so I have commented out these lines:

https://github.com/pombase/fypo/blob/62bc06247db4d4f4f1622227832ae886975261aa/.github/workflows/update-imports.yml#L29-L30

Hopefully this run works 🤞

**Comment by manulera** [comment]
Good news: the action worked

Bad news: the QC fails

https://github.com/pombase/fypo/actions/runs/4767074145

![](https://i.imgflip.com/5jbxqu.png?a466776)

**Comment by gouttegd** [comment]
I’ve done it recently, so happy to help with that with needed.

**Comment by gouttegd** [comment]
The vast majority of the unsats come from the PATO import, which contains an axiom that makes GO’s [chromatin](http://purl.obolibrary.org/obo/GO_0000785) a subclass of [cellular anatomical entity](http://purl.obolibrary.org/obo/GO_0110165), while the GO import defines [chromatin](http://purl.obolibrary.org/obo/GO_0000785) as a [protein-DNA complex](http://purl.obolibrary.org/obo/GO_0032993). Cellular anatomical entities and protein-containing complexes are disjoint in GO.

Why does PATO contain such an axiom is anyone’s guess, but base merging should instead fix the issue by basically discarding whatever PATO may say about GO’s _chromatin_.

**Comment by gouttegd** [comment]
The rest of the unsats is caused by logical definitions such as this one ([abnormal subcellular component during vegetative growth](http://purl.obolibrary.org/obo/FYPO_0001322):

```EquivalentTo: 
    'has part' some 
        ('physical object quality'
         and ('part of' some 'fungal cell')
         and (exists_during some 'single-celled organism vegetative growth phase')
         and ('characteristic of' some cellular_component)
         and (qualifier some abnormal))
```

The `'part of' some 'fungal cell'` seems wrong to me: I don’t think a _quality_ can be a _part of_ a _cell_. I believe [part of](http://purl.obolibrary.org/obo/BFO_0000050) should be replaced by [characteristics of part of](http://purl.obolibrary.org/obo/RO_0002314) (as done for example in the logical definition of [cell phenotype](http://purl.obolibrary.org/obo/FYPO_0000002)).

**Comment by manulera** [comment]
Ok, I just re-tried to make sure I had not messed up at any point along the way, but the same thing happenned again:

**Comment by gouttegd** [comment]
I am afraid we are still missing proper documentation on how to switch to "base merging" (AFAIK). You can try having a look at how I did the switch for the FBbt ontology a couple of months ago: https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/pull/1615 

After the ISB meeting we can find some time so that I can give you proper guidance on how to do it.

**Comment by manulera** [comment]
Hi @gouttegd. I can give it a go. It would be to basically to:
* Do an equivalent commit to this one https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/pull/1615/commits/cc463b1defe883c632e1f2d9093a99d28502b704
* Re-generate and commit Makefile
* Run the refresh imports.

Right?

**Comment by gouttegd** [comment]
Roughly, yes. If you can try that and make a PR, I can comment in the details.

**Comment by manulera** [comment]
Thank you so much you both! Especially @gouttegd for all the step-by-step guiding. I managed yesterday in the end.
