### ISSUE TITLE
Using Protege 5.6 for editing

### ISSUE THREAD

**Issue by manulera** [pombase/fypo#4366]
Hello @matentzn 

@ValWood has to upgrade to Protege v5.6 for her GO work and we were wondering what we have to do in the repository to be able to start using it for FYPO as well. Is there some documentation somewhere from the OBO foundry?

**Comment by matentzn** [comment]
Here is a course taught by @gouttegd  of the new 5.6 features. You need to do two things:

```
docker pull obolibrary/odkfull
```

If you have not done so, to get the latest ODK and

Do a normalisation PR:

Open fypo-edit, make NO change, save it with the new protege, make PR, let QC pass, merge. Thats all!

**Comment by manulera** [comment]
Hi @matentzn thanks for your quick reply, but it took me a while to get to it. I have done as you said, and it seems to have gone OK. The pull request is below

https://github.com/pombase/fypo/pull/4385

Just one question. We no longer need to run the `normalise_xsd_string`, right? I have seen a lot of changes in those lines after saving the file, but I guess from now on the new protege handles this properly, right?

BTW, it's great to see that the id ranges are working with the local file. Surely editors of multiple ontologies will greatly appreciate!

**Comment by matentzn** [comment]
Yep, you wont need normalise_xsd_string anymore!

**Comment by manulera** [comment]
Thanks @matentzn!

This is done @ValWood. I will make a release tomorrow, since today I had already done one release for some terms I needed for Canto (I did not want to do a release with both new terms and repository-wide changes).

**Comment by ValWood** [comment]
closing, thanks both!
