### ISSUE TITLE
Questions about conditions in second phenomics paper

### ISSUE THREAD

**Issue by manulera** [pombase/fypo#4375]
I have some questions regarding how to capture some of the phenotypes from the last publication:

* Nitrogen source, for two days. (E.g. Lysine as nitrogen source, for 2 days). There are a few like this that may have different result in the 1 day and 2 day.

* Carbon source with trace glucose (E.g. galactose with 0.1% starter glucose). Is it worth to coin a new FYPO term for conditions like this, or is a FYECO term (MM with trace glucose) sufficient, using the FYPO term for the carbon source only?

* 10 days incubation / 7 days incubation: Are you assessing viability or was this a growth assay? What would be an appropriate FYPO term?

* Coniditons with "rapamycin 2 pinnings". There is a couple of these. What is the experimental meaning, and how could this be captured?

**Comment by bahler** [comment]
Some thoughts on your queries:

Nitrogen source, for two days. (E.g. Lysine as nitrogen source, for 2 days). There are a few like this that may have different result in the 1 day and 2 day.
-> Not sure what the question is here?

Carbon source with trace glucose (E.g. galactose with 0.1% starter glucose). Is it worth to coin a new FYPO term for conditions like this, or is a FYECO term (MM with trace glucose) sufficient, using the FYPO term for the carbon source only?
-> I would say the latter. This seems too fringe to introduce a new term.

10 days incubation / 7 days incubation: Are you assessing viability or was this a growth assay? What would be an appropriate FYPO term?
-> All phenotypes in this paper are growth assays. Not sure what condition the incubation times refer to?

Coniditons with "rapamycin 2 pinnings". There is a couple of these. What is the experimental meaning, and how could this be captured?
-> That one is for Maria. It's possible that she printed colonies twice on rapamycin medium as there will be residual growth on 1st pinning. But probably too technical to capture.

**Comment by manulera** [comment]
> -> Not sure what the question is here?

How should we capture the phenotype of the 1 day vs. 2 day? Should we capture one of the two only? If so, which? See also next

> -> All phenotypes in this paper are growth assays. Not sure what condition the incubation times refer to?

I see, so what this means is that the cells were pre-incubated in that medium prior to be put on the plate? I thought this meant that they had been 7 or 10 days on the plate. Is this the same thing for the "day2" conditions?

> But probably too technical to capture.

I see, but is it better then to use the 2nd pinning ones instead for sensitive / resistant to rapamycin?

**Comment by manulera** [comment]
Another thing,

In the last paper you had fitness values for each phenotype: log2 of fitness or something like that. We captured those in the "severity" field in the phaf file. They are not yet displayed in PomBase, but if you have them somewhere, it would be nice to have them in the dataset in case we ever display them.

**Comment by yococonocomo** [comment]
> Some thoughts on your queries:
> 
> Nitrogen source, for two days. (E.g. Lysine as nitrogen source, for 2 days). There are a few like this that may have different result in the 1 day and 2 day. -> Not sure what the question is here?
> _this was because some conditions were making strains grow really slowly, we wanted to capture all conditions at the same timepoint (1 day) and for those where there was not much growth at day 1 we left them for longer_
> Carbon source with trace glucose (E.g. galactose with 0.1% starter glucose). Is it worth to coin a new FYPO term for conditions like this, or is a FYECO term (MM with trace glucose) sufficient, using the FYPO term for the carbon source only? -> I would say the latter. This seems too fringe to introduce a new term.
> -Same as Jurg
> 10 days incubation / 7 days incubation: Are you assessing viability or was this a growth assay? What would be an appropriate FYPO term? -> All phenotypes in this paper are growth assays. Not sure what condition the incubation times refer to?
> -we were assesing bot (we did grow all the conditions in phloxin) but we never used the data because the resolution was not enough, again as before some of the really slow growers managed to grow a bit after so long
> Coniditons with "rapamycin 2 pinnings". There is a couple of these. What is the experimental meaning, and how could this be captured? -> That one is for Maria. It's possible that she printed colonies twice on rapamycin medium as there will be residual growth on 1st pinning. But probably too technical to capture.
-I will need to re check, but we had one experiment were we grew the cells in YES+rapa and re-pinned in YES+rapa, so pre conditioned with RAPA (this is for a really specific purpose of checking viability against radiation)

**Comment by yococonocomo** [comment]
> 2 extra questions:
> 
> * What is the parental strain? `h- 972`?
> * Are there any background auxotrophies?

this is the bioneer collection crossed with an h90 turned h- by KO the h1 locus, so they should all be h- without auxotrophies and without the problem in the tht1 locus

**Comment by manulera** [comment]
Thanks for having a look @yococonocomo, but I will need the answers to be a bit more categorical, since I have to capture the info in PomBase:

## Multiple pinnings, day 1 / day 2, 7 days 10 days

We cannot capture these nuances in PomBase so far, so ideally we would keep only one condition for the ones with multiple days / pinnings. I have made a list of all the ones that are repeated:

https://github.com/manulera/phenomics_paper_HTP2/blob/master/results/repeated_rows.tsv

The table has a column `repeated_group` that is the same for all conditions that cannot be captured differently in PomBase. For example, the first three rows where `repeated_group` is 1 all represent growht assays at 25C in YES.

|repeated_group|	condition|
|---|---|
|1	|YES_glucose_0.1percent_25C_10days|
|1|YES_glucose_0.1percent_25C_1week|
|1|YES_glucose_0.1percent_25C|

There should be only one condition picked for each value of `repeated_group`. Can you give me a list of the conditions you want to keep? There should be 24 conditions out of the 57 listed in that file.

## Parent strain

What value should the column have? Does the bioneer library used have an identifier? Normally the parent strain value is `972 h-` or `968 h90`, but this does not seem to apply here.

**Comment by ValWood** [comment]
Aren't all the bioneer collections  972 h-? I thought they used Paul's WT lab strain, or does this switch  to a different strain in later collections? 

What happens to the tht1 locus. That is one of the loci that is mutated in 972 h- isn't is? is it repaired? if so perhaps this can be included in the background as tht1+

**Comment by bahler** [comment]
The Bioneer collection also has three auxotrophic markers. Maria crossed these out.

Best,
-Jurg
—-
Sent from my phone
________________________________

**Comment by ValWood** [comment]
We should add these markers to the background for the screens which don't cross them out. I will open a ticket for that.

**Comment by yococonocomo** [comment]
> Aren't all the bioneer collections 972 h-? I thought they used Paul's WT lab strain, or does this switch to a different strain in later collections?
> 
> What happens to the tht1 locus. That is one of the loci that is mutated in 972 h- isn't is? is it repaired? if so perhaps this can be included in the background as tht1+

no bioneer was made from h+ strain:
from their web
Haploid:   ED666       h+          ade6-M210 ura4-D18 leu1-32
                 ED668       h+          ade6-M216 ura4-D18 leu1-32


because the h- strains we had in the lab were all derived form the Nurse strain, I wanted to make a clean h- strain. so I took 968 and KO the h1 locus of the mating type using a NatMx6 cassette. this way I could select for h-. then crossed with bioneer and  performed several rounds of selection: for kan and nat + and for growth on EMM , so it should be h- and protrotroph

**Comment by yococonocomo** [comment]
> Thanks for having a look @yococonocomo, but I will need the answers to be a bit more categorical, since I have to capture the info in PomBase:
> 
> ## Multiple pinnings, day 1 / day 2, 7 days 10 days
> We cannot capture these nuances in PomBase so far, so ideally we would keep only one condition for the ones with multiple days / pinnings. I have made a list of all the ones that are repeated:
> 
> https://github.com/manulera/phenomics_paper_HTP2/blob/master/results/repeated_rows.tsv
> 
> The table has a column `repeated_group` that is the same for all conditions that cannot be captured differently in PomBase. For example, the first three rows where `repeated_group` is 1 all represent growht assays at 25C in YES.
> 
> repeated_group	condition
> 1	YES_glucose_0.1percent_25C_10days
> 1	YES_glucose_0.1percent_25C_1week
> 1	YES_glucose_0.1percent_25C
> There should be only one condition picked for each value of `repeated_group`. Can you give me a list of the conditions you want to keep? There should be 24 conditions out of the 57 listed in that file.
> 
> ## Parent strain
> What value should the column have? Does the bioneer library used have an identifier? Normally the parent strain value is `972 h-` or `968 h90`, but this does not seem to apply here.

Hi Manu,
I have checked the mappings and selected the conditions that I think would be most relevant to reflect. For those conditions where we have day 2 scannings I kept the day 2 (except for lower glucose concentrations, were I kept day 1 except for 0.1 ) this is because at day1 we could see things that were growing better than wt. but the size of the colonies is quite small, at day 2 the readings are more reliable. one of the groups that you have made has 2 different concentrations of cycloheximide. I have kept both
I attach here the conditions remaining

[Uploading mappings.csv…]()

**Comment by manulera** [comment]
I include here the file that @yococonocomo shared with me via email:

[mappings.csv](https://github.com/pombase/fypo/files/12816620/mappings.csv)
