### ISSUE TITLE
What action? Something is being deprecated

### ISSUE THREAD

**Issue by ValWood** [pombase/fypo#4472]
@kimrutherford @manulera 

<img width="1173" alt="Screenshot 2024-01-19 at 13 51 08" src="https://github.com/pombase/fypo/assets/7359272/4c17f4de-9a66-4e81-9407-474d9642f69e">

**Comment by kimrutherford** [comment]
Follow these docs, I've made my best guess at what the fix should be to get rid of the warning:
 - https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
 - https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files

We'll need to check the output next time a release is made.
