### ISSUE TITLE
Dont use "b" in version tags, else you may cause potential confusion in downstream usage

### ISSUE THREAD

**Issue by matentzn** [pombase/fypo#4488]
Hey @ValWood (cross post from slack).

Your latest 

https://github.com/pombase/fypo/releases/tag/v2024-01-30b

The tag with the “b” in the end makes it difficult to process FYPO in automated pipelines. Would it be possible to remove the b? I think I can also do it.

**Comment by ValWood** [comment]
Sorry about that.
We deleted the 'b'release and made a new v2024-01-31 release "Latest"

v

**Comment by matentzn** [comment]
Thaaank you!
