### ISSUE TITLE
add "x in absence of stress" 

### ISSUE THREAD

**Issue by fypoadmin** [pombase/fypo#531]
We need to
i) Identify the set of terms which have "during x stress"
ii) make checks to confirm the parent term has only been used for "unstressed"
iii) move the non-stressed term to  a child term to represent "unstressed conditions
iv) Create a parent term with comment  directing curators to child terms

Original comment by: ValWood

**Comment by mah11** [comment]
ancient and stalled; reopen if interest ever renews
