### ISSUE TITLE
sensitive to MMS

### ISSUE THREAD

**Issue by fypoadmin** [pombase/fypo#544]
I notice in this session
~/7c5a980860f3b18c

colm has added condition MMS, I was going to change this to
sensitive to MMS, but it doesn't appear as a child of 
sensitive to DNA damaging agents (although the term does exiset)

FYPO:0000089
Ontology    fission_yeast_phenotype
Term name   sensitive to methyl methanesulfonate

...I suspect this is a bug as I can't see any children of
sensitive to DNA damaging agents , and I am sure there are some, so maybe some parents have been lost?

v

Original comment by: ValWood

**Comment by mah11** [comment]
closing because it's ancient and hasn't had any updates in literally years
can open new ticket if we need to do anything to use CHEBI has_role links (they have a lot of things with has_role genotoxin now)
